        WITH 
        CTE_TEMPOS AS (
            SELECT 
                UPO.NUMEROORDEMREAL AS NR_OB,
                MAX(UNP.DTTEMPOINICIAL) AS INICIO_TING,
                MAX(UNP.DTTEMPOFINAL) AS FINAL_TING,
                MAX(SUBSTR(UNP.NUMERO_MAQUINA, 7, 4)) AS MQ_TING
            FROM SGTPRD.UP_ORDEM_MVTO UPO
            INNER JOIN SGTPRD.UNIDADE_PROGRAMACAO UNP ON UPO.NUMEROUP = UNP.NUMEROUP
            WHERE UNP.TIPO_MAQUINA = 19 
              AND UNP.EXCLUIDA = 0 
              AND UNP.TIPOUP = 0
              AND UNP.DTTEMPOFINAL >= TRUNC(SYSDATE)
            GROUP BY UPO.NUMEROORDEMREAL
        ),
        CTE_GRAFICO AS (
            SELECT IDLCRIR_PRD, MAX(GRAFICO) AS GRAFICO
            FROM SGTPRD.VW_LAC_RECPRD_RECLAB
            GROUP BY IDLCRIR_PRD
        ),
        CTE_DADOS AS (
            SELECT 
                OBFX.CODIGO_GRUPO AS GRUPO,
                OBFX.NUMERO_OB AS NR_OB,
                TRIM(OBFX.CODIGO_COR_DESENHO) AS COR_OB,
                TRIM(SUBSTR(CREX.CODCOR, 1, 11)) AS COR_REC,
                OBFX.ESPECIFICACAO_PRODUT AS EP_OB,
                CREX.ESPECIFICACAO_PRODUT AS EP_REC,
                OBFX.PROCESSO_ESPECIFICO AS PE_OB,
                CREX.PROCESSO_ESPECIFICO AS PE_REC,
                T.MQ_TING,
                T.INICIO_TING,
                T.FINAL_TING,
                GR.GRAFICO,
                DECODE(LCR.DATA_ULTIMA_PRODUC, 0, TO_DATE('1899-12-31','YYYY-MM-DD'), 
                       TO_DATE(LCR.DATA_ULTIMA_PRODUC,'YYYYMMDD')) AS DATA_ULT_PROD,
                CREX.CODIGO_CLASSIFICACAO AS CD_CLASSIF,
                UPPER(TRIM(CLF.DESCRICAO)) AS CLASSIF_COR,
                LCR.CODIGO_REDUZIDO_RECE AS CODIGO_REDUZIDO_RECE,
                UPPER(LRB.USUARIO_BLOQUEIO) AS USUARIO_BLOQUEIO,
                TO_DATE(LRB.DATA_BLOQUEIO, 'YYYY/MM/DD') AS DATA_BLOQUEIO,
                TO_DATE(LCR.DATA_ALTERACAO, 'YYYY/MM/DD') AS DATA_ALTERACAO,
                LCR.USUARIO_ALTEROU,
                UPPER(TRIM(VSU.NOME)) AS NOME_USUARIO_ALTEROU,
                CASE 
                    WHEN OBFX.PROCESSO_ESPECIFICO IS NULL OR CREX.PROCESSO_ESPECIFICO IS NULL THEN 'Indefinido'
                    WHEN OBFX.PROCESSO_ESPECIFICO = CREX.PROCESSO_ESPECIFICO THEN 'OK'
                    ELSE 'Divergente'
                END AS STATUS_PE
            FROM CTE_TEMPOS T
            INNER JOIN SGTPRD.UP_ORDEM_MVTO UPO ON UPO.NUMEROORDEMREAL = T.NR_OB
            INNER JOIN SGTPRD.OB_FASES OBFX ON OBFX.NUMERO_OB = T.NR_OB
            INNER JOIN SGTPRD.OB OB ON OBFX.NUMERO_OB = OB.NUMERO_OB
            LEFT JOIN SGTPRD.CADASTRO_RECEITAS CREX 
                ON CREX.PROCESSOINDUSTRIAL = (OBFX.CODIGO_FASE || OBFX.TIPO_PROCESSO)
                AND SUBSTR(CREX.CODCOR, 1, 11) = OBFX.CODIGO_COR_DESENHO
                AND CREX.ESPECIFICACAO_PRODUT = OBFX.ESPECIFICACAO_PRODUT
                AND CREX.PROCESSO_ATIVO_PRODU = 1
            LEFT JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR ON LCR.CODIGO_REDUZIDO_RECE = CREX.CODIGO_REDUZIDO_RECE
            LEFT JOIN CTE_GRAFICO GR ON GR.IDLCRIR_PRD = LCR.ID_LIGA_CADREC_ITEMR
            LEFT JOIN SGTPRD.CLASSIFICACAO_COR CLF ON CLF.CODIGO_CLASSIFICACAO = CREX.CODIGO_CLASSIFICACAO
            INNER JOIN SGTPRD.LABRECEITA_BLOQUEADA LRB ON LRB.ID_LABRECEITA_BLOQ = LCR.ID_LABRECEITA_BLOQ
            LEFT JOIN SGTPRD.VW_SIS_SENHA_USUARIO VSU ON VSU.CODREDUSUARIO = LCR.USUARIO_ALTEROU
            WHERE OB.STATUS <> 0
              AND OBFX.CODIGO_FASE = 40
              AND OBFX.STATUS = 0
              AND LRB.BLOQUEIO_RECEITA = 0
        )
        SELECT GRUPO, NR_OB, COR_OB, COR_REC, EP_OB, EP_REC, PE_OB, PE_REC, MQ_TING, INICIO_TING, FINAL_TING, GRAFICO, DATA_ULT_PROD, CD_CLASSIF, CLASSIF_COR, CODIGO_REDUZIDO_RECE, USUARIO_BLOQUEIO, DATA_BLOQUEIO, DATA_ALTERACAO, USUARIO_ALTEROU, NOME_USUARIO_ALTEROU, STATUS_PE FROM CTE_DADOS
        ORDER BY INICIO_TING ASC, NR_OB ASC, GRUPO ASC