/* =============================================================================
OBJETIVO: Consulta - Lotes de fios e cor dos cones
DOMÍNIO: 04_fiacao_fios
ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta - Lotes de fios e cor dos cones.sql
TIPO: Fiação e Fios
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_PRD_MOVPROD, SGTPRD.DEPOSITO,
                     SGTPRD.DEPOTIPOITEM, SGTPRD.EMBALAGENS,
                     SGTPRD.GERAATRIBUTOESTOQUE, SGTPRD.GERAPECAFARDO,
                     SGTPRD.GERAPECAFIO, SGTPRD.GERAPECACODIGOALFA,
                     SGTPRD.GERAPECASPRODUTO, SGTPRD.GRUPO_ACONDICIONAM,
                     SGTPRD.ITENS_COMPLEMENTO_FI, SGTPRD.ITENS_ESTOQUE,
                     SGTPRD.MASCARA_TIPO_INSUMO, SGTPRD.MASCARAS,
                     SGTPRD.TIPO_ACONDICIONAMENT, SGTPRD.UNIDADE_FABRIL,
                     SGTPRD.UNIDADE_MEDIDA, SGTPRD.XX2_ENUMERATES,
                     SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Consulta somente leitura; datas numéricas YYYYMMDD
                        são convertidas com máscara explícita.
REVISÃO (21/09/2026 - frente cirúrgica): camadas derivadas substituídas por
  tabelas/CTEs; conversão de data e montagem do código industrial usam apenas
  expressões nativas; a projeção ativa foi mantida.
============================================================================= */

WITH MOV_PRODUCAO AS (
    SELECT
        MOV.IDPECASPRODUTO,
        MAX(MOV.PRODUCAO_DATA) AS DATA_PRODUCAO,
        MAX(MOV.PRODUCAO_TURNO) AS TURNO_PRODUCAO
    FROM SGTPRD.BD_PRD_MOVPROD MOV
    WHERE MOV.CODIGO IN (5, 6)
    GROUP BY MOV.IDPECASPRODUTO
),
PECAS_FIO AS (
    SELECT
        GPP.IDPECASPRODUTO,
        GPP.IDGERAATRIESTOSALD,
        GPP.CODIGO_REDUZIDO_PROD AS CODIGO_REDUZIDO,
        GPP.CODIGO_DEPOSITO,
        GPP.STPECAPRODUTO,
        GPP.TISITUACAOESTOQUE,
        GPP.PADRAO_QUALIDADE_SIN,
        GPP.IDACONDICIONAMENTO,
        GPP.LOTE_PRODUTO,
        GPP.NUMERO_BOX,
        GPF.PESO_CAIXA,
        GPF.PESO_BRUTO,
        GPF.EMBALAGEM,
        GPF.QUANTIDADE_EMBALAGEN,
        GPF.COD_UNI_FABRIL AS UND_FAB,
        NVL(TRUNC(MOV.DATA_PRODUCAO), DATE '1899-12-31') AS DATA_PRODUCAO,
        NVL(MOV.TURNO_PRODUCAO, 0) AS TURNO_PRODUCAO,
        ALF.CDPECA
    FROM SGTPRD.GERAPECASPRODUTO GPP
    JOIN SGTPRD.GERAPECAFIO GPF
      ON GPF.IDPECASPRODUTO = GPP.IDPECASPRODUTO
    JOIN SGTPRD.ITENS_ESTOQUE ITE
      ON ITE.CODIGO_REDUZIDO = GPP.CODIGO_REDUZIDO_PROD
    JOIN SGTPRD.UNIDADE_MEDIDA UND
      ON UND.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
    LEFT JOIN SGTPRD.GERAPECACODIGOALFA ALF
      ON ALF.IDPECASPRODUTO = GPP.IDPECASPRODUTO
    LEFT JOIN MOV_PRODUCAO MOV
      ON MOV.IDPECASPRODUTO = GPP.IDPECASPRODUTO
    WHERE GPP.CODIGO_REGISTRO = 3
),
ITEM_MASCARA AS (
    SELECT
        ITE.CODIGO_REDUZIDO,
        ITE.DESCRICAO,
        ITE.LINHA_PRODUTO,
        ITE.CODIGO_ALTERNATIVO,
        TRIM(ITE.IDMASCARATIPOINSUMO) AS TIPO,
        ICO.TITULO_NOMINAL,
        CASE TRIM(ITE.IDMASCARATIPOINSUMO)
            WHEN 'CAV' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 4)
            WHEN 'FPP' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 7, 1) || '.' || SUBSTR(ITE.CODIGO, 8, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 10, 3) || '.' || SUBSTR(ITE.CODIGO, 13, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 16, 2) || '.' || SUBSTR(ITE.CODIGO, 18, 1) || '.' ||
                SUBSTR(ITE.CODIGO, 19, 4) || '.' || SUBSTR(ITE.CODIGO, 23, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 25, 2) || '.' || SUBSTR(ITE.CODIGO, 27, 2)
            WHEN 'FPC' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 7, 1) || '.' || SUBSTR(ITE.CODIGO, 8, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 10, 3) || '.' || SUBSTR(ITE.CODIGO, 13, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 16, 2) || '.' || SUBSTR(ITE.CODIGO, 18, 1) || '.' ||
                SUBSTR(ITE.CODIGO, 19, 4) || '.' || SUBSTR(ITE.CODIGO, 23, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 25, 2) || '.' || SUBSTR(ITE.CODIGO, 27, 2)
            WHEN 'FPT' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 6, 4) || '.' || SUBSTR(ITE.CODIGO, 10, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 13, 2) || '.' || SUBSTR(ITE.CODIGO, 15, 4) || '.' ||
                SUBSTR(ITE.CODIGO, 19, 4)
            WHEN 'FMS' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 7, 4)
            WHEN 'FRS' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 6, 3) || '.' || SUBSTR(ITE.CODIGO, 9, 4)
            WHEN 'FNT' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 7, 2) || '.' || SUBSTR(ITE.CODIGO, 9, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 12, 4)
            WHEN 'FAS' THEN
                SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 3) || '.' ||
                SUBSTR(ITE.CODIGO, 7, 2) || '.' || SUBSTR(ITE.CODIGO, 9, 4) || '.' ||
                SUBSTR(ITE.CODIGO, 13, 4) || '.' || SUBSTR(ITE.CODIGO, 17, 2) || '.' ||
                SUBSTR(ITE.CODIGO, 19, 4)
            ELSE TRIM(ITE.CODIGO)
        END AS CODIND
    FROM SGTPRD.ITENS_ESTOQUE ITE
    JOIN SGTPRD.ITENS_COMPLEMENTO_FI ICO
      ON ICO.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
    JOIN SGTPRD.MASCARA_TIPO_INSUMO MTI
      ON MTI.IDMASCARATIPOINSUMO = ITE.IDMASCARATIPOINSUMO
    JOIN SGTPRD.MASCARAS MAS
      ON MAS.IDMASCARA = MTI.IDMASCARA
    JOIN SGTPRD.UNIDADE_MEDIDA UND
      ON UND.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
    WHERE ITE.TIPO_ITEM IN (0, 1, 3, 4, 19, 28)
),
STATUS_PECA AS (
    SELECT ENI.SEQUENCE AS STPECAPRODUTO,
           ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI
      ON ENI.IDENUMERATE = ENU.ID
    WHERE ENU.NAME LIKE 'TSTATUSPECAPRODUTO%'
),
SITUACAO_ESTOQUE AS (
    SELECT ENI.SEQUENCE AS TISITUACAOESTOQUE,
           ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI
      ON ENI.IDENUMERATE = ENU.ID
    WHERE ENU.NAME LIKE 'TSITUACAOESTOQUEPECA%'
)
SELECT DEP.CDFILIAL AS FILIAL,
       TRIM(FIL.DESCRICAO) AS NOME_FILIAL,
       VPP.IDPECASPRODUTO,
       VPP.CDPECA,
       VPP.PESO_CAIXA AS PESO_LIQ,
       VPP.PESO_BRUTO,
       VPP.PESO_BRUTO - VPP.PESO_CAIXA AS TARA,
       VPP.QUANTIDADE_EMBALAGEN AS CONES,
       VPP.PADRAO_QUALIDADE_SIN AS QS,
       VPP.DATA_PRODUCAO AS DATA_PROD,
       VPP.LOTE_PRODUTO AS LOTE,
       TRIM(EMB.DESCRICAO) AS DESCR_EMBALAGEM,
       VPP.CODIGO_DEPOSITO AS DEPOSITO,
       TRIM(DEP.DESCRICAO) AS DESCR_DEPOSITO,
       VPP.UND_FAB,
       TRIM(UFA.NOME_UNIDADE_FABRIL) AS DESCR_UNIDADE_FABRIL,
       VPP.CODIGO_REDUZIDO AS REDUZ,
       TRIM(VMC.DESCRICAO) AS DESCR_ITEM,
       VMC.CODIND,
       VMC.TIPO,
       VMC.TITULO_NOMINAL,
       VPP.NUMERO_BOX AS BOX,
       VMC.CODIGO_ALTERNATIVO,
       VPP.TURNO_PRODUCAO AS TURNO_PROD,
       VPP.STPECAPRODUTO,
       TRIM(STP.DESCRICAO) AS DESCR_STATUS,
       TRIM(SES.DESCRICAO) AS DESCR_SITUACAO_ESTOQUE,
       TRIM(TIA.DESCRICAO) AS DESCR_ACOND,
       GIA.CODIGO_GRUPO AS COD_GRUPO_ACOND,
       TRIM(GIA.DESCRICAO_GRUPO) AS DESCR_GRUPO_ACOND,
       GPFA.NUMERO_FARDO,
       VMC.LINHA_PRODUTO,
       CASE
           WHEN VPP.STPECAPRODUTO = 23 THEN 0
           ELSE VPP.TISITUACAOESTOQUE
       END AS TISITUACAOESTOQUE
FROM PECAS_FIO VPP
JOIN SGTPRD.GERAATRIBUTOESTOQUE GAE
  ON GAE.ID = VPP.IDGERAATRIESTOSALD
JOIN ITEM_MASCARA VMC
  ON VMC.CODIGO_REDUZIDO = VPP.CODIGO_REDUZIDO
JOIN SGTPRD.DEPOSITO DEP
  ON DEP.CODIGO_DEPOSITO = VPP.CODIGO_DEPOSITO
LEFT JOIN SGTPRD.FILIAIS FIL
  ON FIL.FILIAL = DEP.CDFILIAL
LEFT JOIN SGTPRD.EMBALAGENS EMB
  ON EMB.EMBALAGEM = VPP.EMBALAGEM
LEFT JOIN SGTPRD.UNIDADE_FABRIL UFA
  ON UFA.CODIGO_UNIDADE_FABRI = VPP.UND_FAB
LEFT JOIN SGTPRD.TIPO_ACONDICIONAMENT TIA
  ON TIA.IDACONDICIONAMENTO = VPP.IDACONDICIONAMENTO
LEFT JOIN SGTPRD.GRUPO_ACONDICIONAM GIA
  ON GIA.IDGRUPOACONDICIONAME = TIA.IDGRUPOACONDICIONAME
LEFT JOIN SGTPRD.GERAPECAFARDO GPFA
  ON GPFA.IDPECASPRODUTO = VPP.IDPECASPRODUTO
LEFT JOIN STATUS_PECA STP
  ON STP.STPECAPRODUTO = VPP.STPECAPRODUTO
LEFT JOIN SITUACAO_ESTOQUE SES
  ON SES.TISITUACAOESTOQUE = CASE
                                 WHEN VPP.STPECAPRODUTO = 23 THEN 0
                                 ELSE VPP.TISITUACAOESTOQUE
                             END
WHERE EXISTS (
          SELECT 1
          FROM SGTPRD.DEPOTIPOITEM DTI
          WHERE DTI.CDDEPOSITO = DEP.CODIGO_DEPOSITO
            AND DTI.TIPO_ITEM IN (3, 12, 19)
            AND DTI.TICONTROLETIPOITEM = 1
      )
  AND DEP.SOCONTROLAQUILOS = 0
  AND VPP.CODIGO_REDUZIDO = 9348
  AND VPP.LOTE_PRODUTO IN ('230PVVB011', '230PVVB050', '230PVVB051', '230PVVB060');
