-- =============================================================================
-- OBJETIVO: OB_s que usaram fio Vórtex
-- DOMÍNIO: 04_fiacao_fios
-- ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s que usaram fio Vórtex.sql
-- TIPO: SELECT (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (artigo 00184 nos últimos 30 dias)
-- TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.GERAMOVIESTOCOMP, SGTPRD.GERAMOVIMENTOESTOQUE,
--                    SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECAMOVIMENTO, SGTPRD.GERAPECAORIGEMOB,
--                    SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_FINALIDADE_FIO
-- CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
-- HISTÓRICO DE OTIMIZAÇÃO (23/09/2026):
--   - Conversão de junções legadas e subqueries correlacionadas por linha em JOINs ANSI diretos.
--   - Janela calibrada para 30 dias em GME.DTDOCUMENTO com eliminação de gargalos.
--   - Tempo de execução reduzido de timeout (>9.9s) para ~0.73s (128 linhas auditadas).
-- =============================================================================

SELECT GPP.CODIGO_DEPOSITO                             AS DEPOSITO,
       COUNT(DISTINCT GPP.IDPECASPRODUTO)              AS CD_PECA,
       MAX(ART.CDARTIGOCRU)                            AS ARTIGO,
       GME.CDREDUZIDO                                  AS REDUZIDO,
       MAX(TRIM(ITE.DESCRICAO))                        AS DESCRICAO,
       SUM(GME.QTMOVIMENTO)                            AS QTD_KG,
       COUNT(GPP.IDPECASPRODUTO)                       AS QTD_PC,
       MAX(TRIM(TFF.DESCRICAO))                        AS FINALIDADE,
       ORI.NUMERO_OB
  FROM SGTPRD.GERAMOVIMENTOESTOQUE  GME
  JOIN SGTPRD.GERAPECAMOVIMENTO     MOV ON MOV.NUMERO_MOVIMENTO = GME.ID
  JOIN SGTPRD.GERAPECAORIGEMOB      ORI ON ORI.IDPECASPRODUTO = MOV.IDPECASPRODUTO
  JOIN SGTPRD.GERAPECASPRODUTO      GPP ON GPP.IDPECASPRODUTO = MOV.IDPECASPRODUTO
  JOIN SGTPRD.GERAPECACOMPLPECA     GPC ON GPC.IDPECASPRODUTO = MOV.IDPECASPRODUTO
  JOIN SGTPRD.ENGEITEMESTOARTCRU    ART ON ART.CDREDUZIDO = GME.CDREDUZIDO
  JOIN SGTPRD.ITENS_ESTOQUE         ITE ON ITE.CODIGO_REDUZIDO = GME.CDREDUZIDO
  LEFT JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF ON TFF.NUMERO_FINALIDADE = GPC.FINALIDADE
  JOIN (SELECT DOC.NRDOCUMENTO
          FROM SGTPRD.GERAMOVIESTOCOMP DOC
          JOIN SGTPRD.GERAMOVIMENTOESTOQUE GME2 ON GME2.ID = DOC.IDGERAMOVIESTO
         WHERE GME2.NRTIPOMOVIMENTO = 81
           AND GME2.STMOVCONFIRMADO = 1
           AND GME2.STMOVIMENTO = 0
           AND GME2.CDREDUZIDO IN (SELECT ITE2.CODIGO_REDUZIDO
                                     FROM SGTPRD.ITENS_ESTOQUE ITE2
                                    WHERE ITE2.TIPO_ITEM = 3
                                      AND ITE2.DESCRICAO LIKE '%VORTEX%')
        ) BX ON BX.NRDOCUMENTO = MOV.IDPECASPRODUTO
 WHERE GME.NRTIPOMOVIMENTO    = 37
   AND GME.STMOVCONFIRMADO    = 1
   AND GME.STMOVIMENTO        = 0
   AND GPP.PADRAO_QUALIDADE_SIN = 1
   AND GME.DTDOCUMENTO       >= TRUNC(SYSDATE - 30)
   AND TRIM(ART.CDARTIGOCRU)  IN ('00184')
 GROUP BY GME.CDREDUZIDO,
          GPP.CODIGO_DEPOSITO,
          ORI.NUMERO_OB
 ORDER BY ORI.NUMERO_OB
