/* =============================================================================
OBJETIVO: Peças no estoque que foram usados fio com resíduo
DOMÍNIO: 04_fiacao_fios
ARQUIVO ORIGINAL: Comandos SQL - CR\Peças no estoque que foram usados fio com resíduo.sql
TIPO: Fiação e Fios
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.GERAMOVIESTOCOMP, SGTPRD.GERAMOVIMENTOESTOQUE, SGTPRD.GERAPECACODIGOALFA, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECAMOVIMENTO, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT GPP.CODIGO_DEPOSITO                             DEPOSITO,
       (SELECT GCA.CDPECA 
          FROM SGTPRD.GERAPECACODIGOALFA GCA 
         WHERE GCA.IDPECASPRODUTO=GPP.IDPECASPRODUTO)  CD_PECA,

       (SELECT ART.CDARTIGOCRU 
          FROM SGTPRD.ENGEITEMESTOARTCRU ART 
         WHERE ART.CDREDUZIDO = GME.CDREDUZIDO)        ARTIGO,
       
       GME.CDREDUZIDO                                  REDUZIDO,
       
       (SELECT TRIM(ITE.DESCRICAO) 
          FROM SGTPRD.ITENS_ESTOQUE ITE 
         WHERE ITE.CODIGO_REDUZIDO = GME.CDREDUZIDO)   DESCRICAO,
       
       SUM(GME.QTMOVIMENTO)                            QTD_KG,
       COUNT(GPP.IDPECASPRODUTO)                       QTD_PC,
       (SELECT TRIM(TFF.DESCRICAO) 
          FROM SGTPRD.TIPO_FINALIDADE_FIO TFF 
         WHERE TFF.NUMERO_FINALIDADE = GPC.FINALIDADE) FINALIDADE
  FROM SGTPRD.GERAMOVIMENTOESTOQUE  GME,
       SGTPRD.GERAPECAMOVIMENTO     MOV,
       (SELECT DOC.NRDOCUMENTO
          FROM SGTPRD.GERAMOVIESTOCOMP DOC, SGTPRD.GERAMOVIMENTOESTOQUE GME2
         WHERE GME2.ID = DOC.IDGERAMOVIESTO
           AND GME2.NRTIPOMOVIMENTO = 81
           AND GME2.STMOVCONFIRMADO = 1
           AND GME2.STMOVIMENTO = 0
           AND GME2.CDREDUZIDO IN (SELECT ITE.CODIGO_REDUZIDO 
                                     FROM SGTPRD.ITENS_ESTOQUE ITE 
                                    WHERE ITE.TIPO_ITEM = 3 
                                      AND ITE.DESCRICAO LIKE '%RESDUO%')
        ) BX,
       SGTPRD.GERAPECASPRODUTO  GPP,
       SGTPRD.GERAPECACOMPLPECA GPC
 WHERE MOV.NUMERO_MOVIMENTO = GME.ID
   AND BX.NRDOCUMENTO = MOV.IDPECASPRODUTO
   AND GPP.IDPECASPRODUTO = MOV.IDPECASPRODUTO
   AND GPC.IDPECASPRODUTO = MOV.IDPECASPRODUTO
   AND GME.NRTIPOMOVIMENTO = 37
   AND GME.CDDEPOSITO = 90
   AND GME.STMOVCONFIRMADO = 1
   AND GME.STMOVIMENTO = 0
   AND GPP.STPECAPRODUTO IN (0,18)
   AND GPP.PADRAO_QUALIDADE_SIN = 1
   AND GPC.FINALIDADE = 1
   AND GME.CDREDUZIDO IN (SELECT ART.CDREDUZIDO FROM SGTPRD.ENGEITEMESTOARTCRU ART WHERE TRIM(ART.CDARTIGOCRU) IN ('00022','00024'))
 GROUP BY GME.CDREDUZIDO,
          GPP.IDPECASPRODUTO, 
          GPP.CODIGO_DEPOSITO, 
          GPC.FINALIDADE
 ORDER BY 1,2
