-- Versao anual (resumo agregado por mes, fase, maquina e turno)
SELECT
    D.ANO_MES,
    D.CD_DS_FASE,
    D.NUMERO_MAQUINA,
    D.TURNO_PROD,
    D.TURNO_DESC,
    D.STATUS_UP,
    CASE D.STATUS_UP
        WHEN 0 THEN 'CONFIRMADA'
        WHEN 1 THEN 'INICIADA'
        WHEN 2 THEN 'PROGRAMADA'
        WHEN 3 THEN 'PLANEJADA'
        ELSE 'STATUS ' || TO_CHAR(D.STATUS_UP)
    END AS DS_STATUS_UP,
    D.STATUS_FASE,
    CASE D.STATUS_FASE
        WHEN 0 THEN 'PROGRAMADA'
        WHEN 1 THEN 'EMITIDA'
        WHEN 2 THEN 'PESADA'
        WHEN 3 THEN 'EM EXECUÇÃO'
        WHEN 4 THEN 'CONFIRMADA'
        ELSE 'STATUS ' || TO_CHAR(D.STATUS_FASE)
    END AS DS_STATUS_FASE,
    D.DESTINO_RECEITA,
    MAX(D.REDUZ) AS REDUZ,
    MAX(D.DESCR_ITEM) AS DESCR_ITEM,
    MAX(D.TIPO) AS TIPO,
    MAX(D.ARTIGO) AS ARTIGO,
    MAX(D.DESCR_ARTIGO) AS DESCR_ARTIGO,
    MAX(D.LARGURA) AS LARGURA,
    AVG(D.RENDIMENTO) AS RENDIMENTO,
    MAX(D.COR) AS COR,
    MAX(D.DESCR_COR) AS DESCR_COR,
    MAX(D.ACABAMENTO) AS ACABAMENTO,
    MAX(D.DESENHO) AS DESENHO,
    MAX(D.VARIANTE) AS VARIANTE,
    MAX(D.CODIND) AS CODIND,
    MAX(D.CODIGO_ALTERNATIVO) AS CODIGO_ALTERNATIVO,
    MAX(D.DESCR_CLASSIFICACAO_COR) AS DESCR_CLASSIFICACAO_COR,
    MAX(D.TPUNIDADEMEDIDA) AS TPUNIDADEMEDIDA,
    MAX(D.CODIGO) AS CODIGO,
    MAX(D.NOME_MAQUINA) AS NOME_MAQUINA,
    MAX(D.TIPO_MAQUINA) AS TIPO_MAQUINA,
    MAX(D.FILIAL) AS FILIAL,
    MAX(D.UNIDADE_FABRIL) AS UNIDADE_FABRIL,
    MAX(D.UND_FAB) AS UND_FAB,
    MAX(D.NOME_UNIDADE_FABRIL) AS NOME_UNIDADE_FABRIL,
    MAX(D.LOCAL_PRODUCAO) AS LOCAL_PRODUCAO,
    MAX(D.DESCR_TIPO_DESTINO) AS DESCR_TIPO_DESTINO,
    COUNT(*) AS QT_LINHAS,
    SUM(D.QT_KG) AS QT_KG,
    SUM(D.QT_MT) AS QT_MT,
    ROUND(AVG(D.RENDIMENTO), 4) AS RENDIMENTO_MEDIO,
    SUM(D.CARGA_PREV_GRUPO) AS CARGA_PREV_GRUPO,
    ROUND(COALESCE(AVG(D.EFIC_CARGA), 0), 2) AS EFIC_CARGA_MEDIA,
    SUM(D.MIN_REAL) AS MIN_REAL,
    SUM(D.MIN_PREV) AS MIN_PREV,
    ROUND(SUM(D.MIN_REAL) - SUM(D.MIN_PREV), 2) AS DESVIO_MIN,
    ROUND(ABS(SUM(D.MIN_REAL) - SUM(D.MIN_PREV)), 2) AS DESVIO_MIN_ABS,
    ROUND(SUM(D.MIN_PREV) / NULLIF(SUM(D.MIN_REAL), 0) * 100, 2) AS EFIC_TEMPO_MEDIA,
    SUM(CASE WHEN D.REPROCESSO = 1 THEN D.QT_KG ELSE 0 END) AS QT_KG_REPROCESSO,
    SUM(CASE WHEN D.REPROCESSO = 1 THEN D.QT_MT ELSE 0 END) AS QT_MT_REPROCESSO,
    SUM(CASE WHEN D.REPROCESSO = 1 THEN 1 ELSE 0 END) AS REPROCESSO_QTDE
FROM (
-- Template anual parametrizado (ano ou janela customizada)
WITH REN AS (
    SELECT
        OBE.NUMERO_OB,
        ITE.IDUNIDADEMEDIDA AS TPUNIDADEMEDIDA,
        CASE
            WHEN EPA.TIPO_DA_GRAMATURA = 1
                 AND ICO.TIPOPRODUTO NOT IN (4, 9)
                 AND (EPA.GRAMATURA * EPA.LARGURA) <> 0
                THEN 1000 / (EPA.GRAMATURA * EPA.LARGURA)

            WHEN EPA.TIPO_DA_GRAMATURA <> 1
                 AND ICO.TIPOPRODUTO NOT IN (4, 9)
                 AND EPA.GRAMATURA <> 0
                THEN 1000 / EPA.GRAMATURA

            WHEN EPA.TIPO_DA_GRAMATURA = 1
                 AND ICO.TIPOPRODUTO IN (4, 9)
                 AND (EPA.GRAMATURA * EPA.LARGURA) <> 0
                THEN 1000 / (EPA.GRAMATURA * EPA.LARGURA * 2)

            WHEN EPA.TIPO_DA_GRAMATURA <> 1
                 AND ICO.TIPOPRODUTO IN (4, 9)
                 AND EPA.GRAMATURA <> 0
                THEN 1000 / (EPA.GRAMATURA * 2)

            ELSE 0
        END AS RENDIMENTO
    FROM sgtprd.OB OBE
    JOIN sgtprd.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
    JOIN sgtprd.ENG_PRODG_ACABADO EPA
        ON EPA.REDUZIDO_AGRUPADOR = ITE.REDUZIDO_AGRUPADOR
    JOIN sgtprd.ITENS_COMPLEMENTO ICO
        ON ICO.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
),
PROD AS (
    SELECT
        BP.CODIGO_REDUZIDO AS REDUZ,
        BP.DESCRICAO AS DESCR_ITEM,
        BP.TIPO AS TIPO,
        BP.ARTIGO AS ARTIGO,
        BP.DESCR_ARTIGO AS DESCR_ARTIGO,
        EPA.LARGURA AS LARGURA,
        BP.COR AS COR,
        BP.DESCR_COR AS DESCR_COR,
        BP.ACABAMENTO AS ACABAMENTO,
        BP.DESENHO AS DESENHO,
        BP.VARIANTE AS VARIANTE,
        BP.CODIND AS CODIND,
        BP.CODIGO_ALTERNATIVO AS CODIGO_ALTERNATIVO,
        BP.DESCR_CLASSIF_COR AS DESCR_CLASSIFICACAO_COR,
        BP.CODIGO AS CODIGO
    FROM sgtprd.BD_BAS_MASCPRODACAB BP
    LEFT JOIN sgtprd.ENG_PRODG_ACABADO EPA
        ON EPA.REDUZIDO_AGRUPADOR = BP.REDUZIDO_AGRUPADOR
),
LOCAL_PROD AS (
    SELECT /*+ MATERIALIZE */
        FFL.CODIGO_FASE,
        MAX(VEX.DESCR_PRODUCAO_EXTERNA) AS LOCAL_PRODUCAO
    FROM (
        SELECT CODIGO_FASE, PROCESSOTERCEIROS
        FROM sgtprd.FASES_FLUXO
        WHERE REGEXP_LIKE(PROCESSOTERCEIROS, '^[0-9]+$')
    ) FFL
    LEFT JOIN sgtprd.VW_F7_PRD_PROD_EXTERNA VEX
        ON VEX.PROD_EXTERNA = TO_NUMBER(FFL.PROCESSOTERCEIROS)
    GROUP BY FFL.CODIGO_FASE
),
VUP_RAW AS (
    SELECT
        UOM.NUMEROORDEMREAL AS NUMERO_OB,
        UOM.SEQUENCIAORDEMREAL AS SEQ,
        UPR.NUMEROUP,
        UPR.NUMERO_MAQUINA,
        MAQ.NOME_MAQUINA,
        UPR.TEMPOFINAL,
        UPR.TEMPOINICIAL,
        UPP.DATA_HORA_INICIO,
        UPP.DATA_HORA_FINAL,
        UPP.DATA_INI,
        UPP.TURNO_INI,
        UPP.DATA_FIM,
        UPP.TURNO_FIM,
        NVL((
            SELECT TRUNC(SUM(UPA.TEMPOFINAL - UPA.TEMPOINICIAL) * 1440)
            FROM sgtprd.UNIDADE_PROGRAMACAO UPA
            WHERE UPA.EXCLUIDA = 0
              AND UPA.SETOR = UPR.SETOR
              AND UPA.STATUS = 0
              AND UPA.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
              AND UPA.TEMPOFINAL >= UPR.TEMPOINICIAL
              AND UPA.TEMPOINICIAL >= UPR.TEMPOINICIAL
              AND UPA.TEMPOFINAL <= UPR.TEMPOFINAL
              AND UPA.TIPOUP = 5
        ), 0) AS MIN_PAR_PROC,
        CASE
            WHEN UPR.DURACAO_PREVISTA <> 0 THEN
                UPR.DURACAO_PREVISTA * 1440
            ELSE
                DECODE(
                    UPR.TEMPOFINALPROGRAMADO,
                    0,
                    (UPR.TEMPOFINALPLANEJADO - UPR.TEMPOINIPLANEJADO) * 1440,
                    (UPR.TEMPOFINALPROGRAMADO - UPR.TEMPOINIPROGRAMADO) * 1440
                )
        END AS MIN_PREV,
        ((UPR.TEMPOFINAL - UPR.TEMPOINICIAL) * 1440) AS MIN_REAL_BRUTO,
        UPP.TIPO_MAQUINA,
        UPP.CDFILIAL,
        MAQ.PROGRAM_POR_LEADTIME,
        UPR.STATUS AS STATUS_UP,
        UPR.SETOR,
        UPR.EXCLUIDA,
        UPR.TIPOUP,
        UPR.DTPRODFIM,
        UPR.DTPRODINI,
        UPR.NRTURNOINI,
        UPR.DTTEMPOINICIAL,
        UPR.DTTEMPOFINAL,
        UPR.DTTEMPOINIPROGRAMADO,
        UPR.DTTEMPOFINALPROGRAMA,
        UPR.DTTEMPOINIPLANEJADO,
        UPR.DTTEMPOFINALPLANEJAD,
        UPR.DURACAO_PREVISTA
    FROM sgtprd.UNIDADE_PROGR_PROD UPP
    JOIN sgtprd.UNIDADE_PROGRAMACAO UPR
        ON UPR.NUMEROUP = UPP.NUMEROUP
    JOIN sgtprd.UP_ORDEM_MVTO UOM
        ON UOM.NUMEROUP = UPR.NUMEROUP
    JOIN sgtprd.MAQUINA MAQ
        ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    WHERE UPR.SETOR = 5
      AND UPR.EXCLUIDA = 0
      AND UPR.TIPOUP = 0
      AND UPP.DATA_FIM >= :dt_inicio
      AND UPP.DATA_FIM < :dt_fim
),
VUP AS (
    SELECT
        V.NUMERO_OB,
        V.SEQ,
        V.NUMEROUP,
        V.NUMERO_MAQUINA,
        V.NOME_MAQUINA,
        V.TEMPOFINAL,
        V.TEMPOINICIAL,
        V.DATA_HORA_INICIO,
        V.DATA_HORA_FINAL,
        V.DATA_INI,
        V.TURNO_INI,
        V.DATA_FIM,
        V.TURNO_FIM,
        V.MIN_PAR_PROC,
        V.MIN_PREV,
        CASE
            WHEN V.MIN_REAL_BRUTO <= 1 THEN 1
            ELSE V.MIN_REAL_BRUTO - V.MIN_PAR_PROC + 1
        END AS MIN_REAL,
        V.TIPO_MAQUINA,
        V.CDFILIAL,
        V.PROGRAM_POR_LEADTIME,
        V.STATUS_UP,
        V.SETOR,
        V.EXCLUIDA,
        V.TIPOUP,
        V.DTPRODFIM,
        V.DTPRODINI,
        V.NRTURNOINI,
        V.DTTEMPOINICIAL,
        V.DTTEMPOFINAL,
        V.DTTEMPOINIPROGRAMADO,
        V.DTTEMPOFINALPROGRAMA,
        V.DTTEMPOINIPLANEJADO,
        V.DTTEMPOFINALPLANEJAD,
        V.DURACAO_PREVISTA
    FROM VUP_RAW V
),
OBF_BASE AS (
    SELECT /*+ MATERIALIZE */
        OBFX.NUMERO_OB,
        NVL(OBFX.SEQUENCIA, 0) AS SEQ,
        OBFX.NUMERO_MAQUINA,
        TRIM(MAQ.NOME_MAQUINA) AS NOME_MAQUINA,
        OBFX.CODIGO_FASE,
        OBFX.TIPO_PROCESSO,
        OBFX.PROCESSO_ESPECIFICO,
        OBFX.NUMEROORDEMMOVIMENTO,
        VUF.SEQ AS SEQUENCIAORDEMMOVIME,
        OBFX.STATUS AS STATUS_FASE,
        OBFX.DESTINO_RECEITA,
        GDX.TIPO_DESTINO AS TIPO_DESTINO,
        TRIM(DEX.DESCRICAO) AS DESCR_DESTINO,
        OBFX.CARGA_MAXIMA,
        OBFX.CODIGO_GRUPO,
        OBFX.OPERADOR_INICIO,
        OBFX.OPERADOR_FINAL,
        TO_NUMBER(OBFX.CBCORTELONGITUDINAL) AS CBCORTELONGITUDINAL,
        OBFX.ID_LIGA_CADREC_ITEMR,
        DECODE(OBFX.KILOS_PRODUZIDOS, 0, OBY.KILOS, OBFX.KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
        DECODE(OBFX.METROS_PRODUZIDOS, 0, OBY.METROS, OBFX.METROS_PRODUZIDOS) AS METROS_PRODUZIDOS,
        OBY.KILOS AS OBY_KILOS,
        OBY.METROS AS OBY_METROS,
        ITE.IDUNIDADEMEDIDA AS IDUNIDADEMEDIDA,
        OBY.CODPRO_REDUZIDO AS CODPRO_REDUZIDO,
        MAQ.TIPO_MAQUINA,
        MAQ.GRUPO AS GRUPO,
        MAQ.SECAO,
        MAQ.VELOCIDADE_MAQUINA,
        OBFX.VELOCIDADE AS VELOCIDADE_BASE,
        OBFX.CODIGO_VARIANTE,
        OBFX.CODIGO_COR_DESENHO,
        OBFX.ESPECIFICACAO_PRODUT,
        PRI.PROCESSO_INDUSTRIAL,
        PRI.TIPO_PROCESSO_INDUST,
        PRI.DESCRICAO_PI,
        OBE.NUMERO_GRUPO_PROGRAM,
        OBE.CODIGO_FLUXO,
        OBE.TIPO_ORDEM,
        OBE.IDGRUPOFLUXO,
        OBE.EXPORTACAO,
        OBE.PRIM_LOTE_POR_COR AS PRIM_LOTE_COR,
        OBE.PRIM_LOTE_PROCESSO AS PRIM_LOTE_PROC,
        OBE.OB_ALTERNATIVA,
        GPR.UNIDADE_FABRIL,
        LTRIM(TO_CHAR(GPR.UNIDADE_FABRIL), '0') AS UND_FAB,
        LP.LOCAL_PRODUCAO,
        CASE
            WHEN OBFX.CODIGO_VARIANTE <> '     ' THEN
                ((TRUNC(MAQ.HORAMAQUINA_CARGA_DE) * 60) + (MAQ.HORAMAQUINA_CARGA_DE - TRUNC(MAQ.HORAMAQUINA_CARGA_DE)) * 100)
                + NVL((
                    SELECT VDE.TEMPO_PREPARACAO_MAQ
                    FROM sgtprd.VARIANTE_DESENHO VDE
                    WHERE VDE.PROCESSO_INDUSTRIAL = PRI.PROCESSO_INDUSTRIAL
                      AND VDE.CODIGO_DESENHO = OBFX.CODIGO_COR_DESENHO
                      AND VDE.CODIGO_VARIANTE = OBFX.CODIGO_VARIANTE
                      AND VDE.ESPECIFICACAO_PRODUT = OBFX.ESPECIFICACAO_PRODUT
                ), 0)
            ELSE
                (TRUNC(MAQ.HORAMAQUINA_CARGA_DE) * 60) + (MAQ.HORAMAQUINA_CARGA_DE - TRUNC(MAQ.HORAMAQUINA_CARGA_DE)) * 100
        END AS MIN_SETUP,
        CASE
            WHEN NVL((
                SELECT MAX(MR.SEQUENCIA_AJUSTE)
                FROM sgtprd.MOVTO_RECEITA MR
                WHERE MR.NUMEROORDEM = OBFX.NUMEROORDEMMOVIMENTO
                  AND MR.SEQUENCIAFASEOB = VUF.SEQ
            ), 0) <> 0 THEN 1
            ELSE 0
        END AS AJUSTE
    FROM sgtprd.OB_FASES OBFX
    JOIN VUP VUF
        ON VUF.NUMERO_OB = OBFX.NUMERO_OB
       AND VUF.SEQ = NVL(OBFX.SEQUENCIA, 0)
    JOIN sgtprd.OB_PRODUTO OBY
        ON OBY.NUMERO_OB = OBFX.NUMERO_OB
    JOIN sgtprd.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = OBY.CODPRO_REDUZIDO
    JOIN sgtprd.OB OBE
        ON OBE.NUMERO_OB = OBFX.NUMERO_OB
    JOIN sgtprd.MAQUINA MAQ
        ON MAQ.NUMERO_MAQUINA = OBFX.NUMERO_MAQUINA
       AND MAQ.SETOR = 5
    JOIN sgtprd.PROCESSO_INDUSTRIAL PRI
        ON PRI.CODIGO_FASE = OBFX.CODIGO_FASE
       AND PRI.TIPO_PROCESSO = OBFX.TIPO_PROCESSO
    JOIN sgtprd.GRUPO_MAQUINAS GPR
        ON GPR.SETOR = MAQ.SETOR
       AND GPR.GRUPO = MAQ.GRUPO
    LEFT JOIN sgtprd.DESTINO DEX
        ON DEX.DESTINO = OBFX.DESTINO_RECEITA
    LEFT JOIN sgtprd.GRUPO_DESTINO GDX
        ON GDX.CODIGO_GRUPO = DEX.CODIGO_GRUPO
    LEFT JOIN LOCAL_PROD LP
        ON LP.CODIGO_FASE = OBFX.CODIGO_FASE
    WHERE OBFX.DESTINO_RECEITA IN (0, 1, 2, 4)
),
OBF AS (
    SELECT /*+ MATERIALIZE */
        B.NUMERO_OB,
        B.SEQ,
        B.NUMERO_MAQUINA,
        B.NOME_MAQUINA,
        B.CODPRO_REDUZIDO,
        B.CODIGO_FASE,
        B.NUMEROORDEMMOVIMENTO,
        B.SEQUENCIAORDEMMOVIME,
        B.NUMERO_GRUPO_PROGRAM,
        B.CODIGO_FLUXO,
        B.STATUS_FASE,
        B.DESTINO_RECEITA,
        B.TIPO_DESTINO,
        B.DESCR_DESTINO,
        B.CARGA_MAXIMA,
        B.GRUPO,
        B.CODIGO_GRUPO,
        B.OPERADOR_INICIO,
        B.OPERADOR_FINAL,
        B.CBCORTELONGITUDINAL,
        B.ID_LIGA_CADREC_ITEMR,
        B.KILOS_PRODUZIDOS,
        B.METROS_PRODUZIDOS,
        B.IDUNIDADEMEDIDA,
        CASE
            WHEN B.CODIGO_GRUPO = 0 THEN 100
            WHEN B.CODIGO_GRUPO <> 0
                 AND B.TIPO_MAQUINA IN (17, 18, 19, 20, 21, 22, 60)
                 AND B.IDUNIDADEMEDIDA = 1
                 AND NVL(SUM(DECODE(B.KILOS_PRODUZIDOS, 0, B.OBY_KILOS, B.KILOS_PRODUZIDOS))
                     OVER (PARTITION BY B.CODIGO_GRUPO), 0) <> 0 THEN
                B.KILOS_PRODUZIDOS / SUM(DECODE(B.KILOS_PRODUZIDOS, 0, B.OBY_KILOS, B.KILOS_PRODUZIDOS))
                    OVER (PARTITION BY B.CODIGO_GRUPO) * 100
            WHEN NVL(SUM(DECODE(B.METROS_PRODUZIDOS, 0, B.OBY_METROS, B.METROS_PRODUZIDOS))
                     OVER (PARTITION BY B.CODIGO_GRUPO), 0) <> 0 THEN
                B.METROS_PRODUZIDOS / SUM(DECODE(B.METROS_PRODUZIDOS, 0, B.OBY_METROS, B.METROS_PRODUZIDOS))
                    OVER (PARTITION BY B.CODIGO_GRUPO) * 100
            ELSE 1 / NULLIF(COUNT(*) OVER (PARTITION BY B.CODIGO_GRUPO), 0)
        END AS PERC_GRUPO,
        B.VELOCIDADE_BASE,
        B.VELOCIDADE_MAQUINA,
        B.MIN_SETUP,
        B.AJUSTE,
        B.SECAO,
        B.TIPO_PROCESSO,
        B.PROCESSO_ESPECIFICO,
        B.TIPO_PROCESSO_INDUST,
        B.DESCRICAO_PI,
        B.CODIGO_COR_DESENHO,
        B.ESPECIFICACAO_PRODUT,
        B.CODIGO_VARIANTE,
        B.TIPO_ORDEM,
        B.IDGRUPOFLUXO,
        B.EXPORTACAO,
        B.PRIM_LOTE_COR,
        B.PRIM_LOTE_PROC,
        B.OB_ALTERNATIVA,
        B.UNIDADE_FABRIL,
        B.UND_FAB,
        B.LOCAL_PRODUCAO
    FROM OBF_BASE B
),
OBF_KEYS AS (
    SELECT DISTINCT
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        B.CODIGO_FASE,
        B.NUMERO_GRUPO_PROGRAM,
        B.CODIGO_FLUXO
    FROM OBF_BASE B
),
VEL AS (
    SELECT
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        MAX(CASE WHEN GFF.SEQUENCIA = B.SEQUENCIAORDEMMOVIME THEN GFM.VELOCIDADE END) AS VELOCIDADE_SEQ,
        MAX(CASE WHEN GFF.CODIGO_FASE = B.CODIGO_FASE THEN GFM.VELOCIDADE END) AS VELOCIDADE_FASE
    FROM OBF_KEYS B
    JOIN sgtprd.GRUPO_FLUXO GFL
        ON GFL.NUMERO_GRUPO_PROGRAM = B.NUMERO_GRUPO_PROGRAM
       AND GFL.CODIGO_FLUXO = B.CODIGO_FLUXO
    JOIN sgtprd.GRUPO_FLUXO_FASES GFF
        ON GFF.IDGRUPOFLUXO = GFL.IDGRUPOFLUXO
    JOIN sgtprd.GRUPO_FLUXO_MAQUINAS GFM
        ON GFM.IDGRUPOFLUXOFASE = GFF.IDGRUPOFLUXOFASE
       AND GFM.NUMERO_MAQUINA = B.NUMERO_MAQUINA
       AND GFM.ATIVA = 1
    GROUP BY
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        B.CODIGO_FASE
)

SELECT
    TO_CHAR(VUP.DATA_FIM, 'RRRRMM') AS ANO_MES,
    CASE
        WHEN VUP.TIPO_MAQUINA = 12
             AND TRIM(VUP.NOME_MAQUINA) LIKE 'COLETOR%' THEN '01 - MONTAGEM'
        WHEN VUP.TIPO_MAQUINA = 8
             AND TRIM(VUP.NOME_MAQUINA) LIKE 'REVISADEIRA%' THEN '02 - REVISÃO'
        WHEN OBF.CODIGO_FASE = 40 THEN '03 - TINGIMENTO'
        WHEN VUP.TIPO_MAQUINA = 22 THEN '04 - HIDRO'
        WHEN VUP.TIPO_MAQUINA = 1  THEN '05 - SECADOR'
        WHEN VUP.TIPO_MAQUINA = 29 THEN '06 - FELPADEIRA'
        WHEN VUP.TIPO_MAQUINA = 14
             AND TRIM(VUP.NOME_MAQUINA) LIKE '%BRILHO%' THEN '07 - CALANDRA BRILHO'
        WHEN VUP.TIPO_MAQUINA = 14
             AND TRIM(VUP.NOME_MAQUINA) LIKE '%COMPACTA%' THEN '08 - CALANDRA COMPACTA'
        WHEN VUP.TIPO_MAQUINA = 23 THEN '09 - ABRIDOR'
        WHEN VUP.TIPO_MAQUINA = 6  THEN '10 - RAMA'
        WHEN VUP.TIPO_MAQUINA = 8
             AND TRIM(VUP.NOME_MAQUINA) LIKE 'EMBALADEIRA%' THEN '11 - EMBALADEIRA'
        ELSE '99 - NAO DEFINIDO'
    END AS CD_DS_FASE,
    LTRIM(VUP.NUMERO_MAQUINA, '0') AS NUMERO_MAQUINA,
    VUP.NOME_MAQUINA,
    VUP.TIPO_MAQUINA,
    VUP.CDFILIAL AS FILIAL,
    VUP.TURNO_FIM AS TURNO_PROD,
    CASE VUP.TURNO_FIM
        WHEN 1 THEN 'TURNO 1'
        WHEN 2 THEN 'TURNO 2'
        WHEN 3 THEN 'TURNO 3'
        ELSE 'OUTRO'
    END AS TURNO_DESC,
    VUP.STATUS_UP,
    OBF.STATUS_FASE,
    OBF.DESTINO_RECEITA,
    OBF.CODPRO_REDUZIDO AS REDUZ,
    REN.TPUNIDADEMEDIDA,
    PROD.DESCR_ITEM,
    PROD.TIPO,
    PROD.ARTIGO,
    PROD.DESCR_ARTIGO,
    PROD.LARGURA,
    PROD.COR,
    PROD.DESCR_COR,
    PROD.ACABAMENTO,
    PROD.DESENHO,
    PROD.VARIANTE,
    PROD.CODIND,
    PROD.CODIGO_ALTERNATIVO,
    PROD.DESCR_CLASSIFICACAO_COR,
    PROD.CODIGO,
    REN.RENDIMENTO,
    OBF.KILOS_PRODUZIDOS AS QT_KG,
    OBF.METROS_PRODUZIDOS AS QT_MT,
    DECODE(NULLIF(OBF.TIPO_DESTINO, 0), 1, 1, 0) AS REPROCESSO,
    CASE
        WHEN OBF.TIPO_DESTINO = 1 AND OBF.CARGA_MAXIMA = 0 THEN
            DECODE(REN.TPUNIDADEMEDIDA, 1, OBF.KILOS_PRODUZIDOS, OBF.METROS_PRODUZIDOS) * OBF.PERC_GRUPO / 100
        ELSE
            OBF.CARGA_MAXIMA * OBF.PERC_GRUPO / 100
    END AS CARGA_PREV_GRUPO,
    CASE
        WHEN OBF.TIPO_DESTINO = 1 AND OBF.CARGA_MAXIMA = 0 THEN 100
        WHEN OBF.TIPO_DESTINO <> 1 AND OBF.CARGA_MAXIMA = 0 THEN 0
        ELSE ROUND(
            DECODE(REN.TPUNIDADEMEDIDA, 1, OBF.KILOS_PRODUZIDOS, OBF.METROS_PRODUZIDOS)
            / NULLIF(OBF.CARGA_MAXIMA, 0) * 100,
            2
        )
    END AS EFIC_CARGA,
    VUP.MIN_REAL * OBF.PERC_GRUPO / 100 AS MIN_REAL,
    VUP.MIN_PREV * OBF.PERC_GRUPO / 100 AS MIN_PREV,
    OBF.UNIDADE_FABRIL,
    LTRIM(TO_CHAR(OBF.UNIDADE_FABRIL), '0') AS UND_FAB,
    TRIM(ufb.NOME_UNIDADE_FABRIL) AS NOME_UNIDADE_FABRIL,
    LP.LOCAL_PRODUCAO,
    TRIM(vtd.DESCRICAO) AS DESCR_TIPO_DESTINO
FROM VUP
JOIN OBF
    ON OBF.NUMERO_OB = VUP.NUMERO_OB
   AND OBF.SEQ = VUP.SEQ
LEFT JOIN REN
    ON REN.NUMERO_OB = OBF.NUMERO_OB
LEFT JOIN PROD
    ON PROD.REDUZ = OBF.CODPRO_REDUZIDO
LEFT JOIN sgtprd.UNIDADE_FABRIL ufb
    ON ufb.CODIGO_UNIDADE_FABRI = OBF.UNIDADE_FABRIL
LEFT JOIN LOCAL_PROD LP
    ON LP.CODIGO_FASE = OBF.CODIGO_FASE
LEFT JOIN sgtprd.VW_ENU_TIPO_DESTINO vtd
    ON vtd.TIPO_DESTINO = OBF.TIPO_DESTINO
-- Ordenacao removida para reduzir custo em carga anual
) D
GROUP BY
    D.ANO_MES,
    D.CD_DS_FASE,
    D.NUMERO_MAQUINA,
    D.TURNO_PROD,
    D.TURNO_DESC,
    D.STATUS_UP,
    D.STATUS_FASE,
    D.DESTINO_RECEITA
