-- Versao semanal (segunda a domingo da semana atual)
WITH REN AS (
    SELECT
        OBE.NUMERO_OB,
        ITE.IDUNIDADEMEDIDA AS TPUNIDADEMEDIDA,
        CASE
            WHEN EPA.TIPO_DA_GRAMATURA = 1
                 AND ICO.TIPOPRODUTO NOT IN (4, 9)
                 AND (EPA.GRAMATURA * EPA.LARGURA) <> 0
                THEN 1000 / (EPA.GRAMATURA * EPA.LARGURA)

            WHEN EPA.TIPO_DA_GRAMATURA <> 1
                 AND ICO.TIPOPRODUTO NOT IN (4, 9)
                 AND EPA.GRAMATURA <> 0
                THEN 1000 / EPA.GRAMATURA

            WHEN EPA.TIPO_DA_GRAMATURA = 1
                 AND ICO.TIPOPRODUTO IN (4, 9)
                 AND (EPA.GRAMATURA * EPA.LARGURA) <> 0
                THEN 1000 / (EPA.GRAMATURA * EPA.LARGURA * 2)

            WHEN EPA.TIPO_DA_GRAMATURA <> 1
                 AND ICO.TIPOPRODUTO IN (4, 9)
                 AND EPA.GRAMATURA <> 0
                THEN 1000 / (EPA.GRAMATURA * 2)

            ELSE 0
        END AS RENDIMENTO
    FROM sgtprd.OB OBE
    JOIN sgtprd.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
    JOIN sgtprd.ENG_PRODG_ACABADO EPA
        ON EPA.REDUZIDO_AGRUPADOR = ITE.REDUZIDO_AGRUPADOR
    JOIN sgtprd.ITENS_COMPLEMENTO ICO
        ON ICO.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
),
PROD AS (
    SELECT
        BP.CODIGO_REDUZIDO AS REDUZ,
        BP.DESCRICAO AS DESCR_ITEM,
        BP.TIPO AS TIPO,
        BP.ARTIGO AS ARTIGO,
        BP.DESCR_ARTIGO AS DESCR_ARTIGO,
        EPA.LARGURA AS LARGURA,
        BP.COR AS COR,
        BP.DESCR_COR AS DESCR_COR,
        BP.ACABAMENTO AS ACABAMENTO,
        BP.DESENHO AS DESENHO,
        BP.VARIANTE AS VARIANTE,
        BP.CODIND AS CODIND,
        BP.CODIGO_ALTERNATIVO AS CODIGO_ALTERNATIVO,
        BP.DESCR_CLASSIF_COR AS DESCR_CLASSIFICACAO_COR,
        BP.CODIGO AS CODIGO
    FROM sgtprd.BD_BAS_MASCPRODACAB BP
    LEFT JOIN sgtprd.ENG_PRODG_ACABADO EPA
        ON EPA.REDUZIDO_AGRUPADOR = BP.REDUZIDO_AGRUPADOR
),
LOCAL_PROD AS (
    SELECT /*+ MATERIALIZE */
        FFL.CODIGO_FASE,
        MAX(VEX.DESCR_PRODUCAO_EXTERNA) AS LOCAL_PRODUCAO
    FROM (
        SELECT CODIGO_FASE, PROCESSOTERCEIROS
        FROM sgtprd.FASES_FLUXO
        WHERE REGEXP_LIKE(PROCESSOTERCEIROS, '^[0-9]+$')
    ) FFL
    LEFT JOIN sgtprd.VW_F7_PRD_PROD_EXTERNA VEX
        ON VEX.PROD_EXTERNA = TO_NUMBER(FFL.PROCESSOTERCEIROS)
    GROUP BY FFL.CODIGO_FASE
),
DIM_FASE AS (
    SELECT /*+ MATERIALIZE */
        FFL.CODIGO_FASE,
        MAX(TRIM(FFL.DESCRICAO_FASE)) AS DESCR_FASE,
        MAX(TRIM(GFA.DESCRICAO)) AS DESCR_GRUPO_FASE,
        MAX(GFA.SETOR_SEQUENCIA) AS SETOR_IND_SEQ,
        MAX(TRIM(STI.DESCRICAO)) AS DESCR_SETOR_INDUST
    FROM sgtprd.FASES_FLUXO FFL
    JOIN sgtprd.GRUPO_FASES GFA
        ON GFA.CODIGO = FFL.CODIGO_GRUPO
    LEFT JOIN sgtprd.SETOR_INDUSTRIAL STI
        ON STI.SETOR_SEQUENCIA = GFA.SETOR_SEQUENCIA
    GROUP BY FFL.CODIGO_FASE
),
DIM_TIPO_MAQ AS (
    SELECT /*+ MATERIALIZE */
        VTM.TIPO_MAQUINA,
        MAX(TRIM(VTM.DESCRICAO)) AS DESCR_TIPO_MAQ
    FROM sgtprd.VW_ENU_TIPO_DE_MAQUINAS_SETOR VTM
    GROUP BY VTM.TIPO_MAQUINA
),
VUP_RAW AS (
    SELECT
        UOM.NUMEROORDEMREAL AS NUMERO_OB,
        UOM.SEQUENCIAORDEMREAL AS SEQ,
        UPR.NUMEROUP,
        UPR.NUMERO_MAQUINA,
        MAQ.NOME_MAQUINA,
        UPR.TEMPOFINAL,
        UPR.TEMPOINICIAL,
        UPP.DATA_HORA_INICIO,
        UPP.DATA_HORA_FINAL,
        UPP.DATA_INI,
        UPP.TURNO_INI,
        UPP.DATA_FIM,
        UPP.TURNO_FIM,
        NVL((
            SELECT TRUNC(SUM(UPA.TEMPOFINAL - UPA.TEMPOINICIAL) * 1440)
            FROM sgtprd.UNIDADE_PROGRAMACAO UPA
            WHERE UPA.EXCLUIDA = 0
              AND UPA.SETOR = UPR.SETOR
              AND UPA.STATUS = 0
              AND UPA.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
              AND UPA.TEMPOFINAL >= UPR.TEMPOINICIAL
              AND UPA.TEMPOINICIAL >= UPR.TEMPOINICIAL
              AND UPA.TEMPOFINAL <= UPR.TEMPOFINAL
              AND UPA.TIPOUP = 5
        ), 0) AS MIN_PAR_PROC,
        CASE
            WHEN UPR.DURACAO_PREVISTA <> 0 THEN
                UPR.DURACAO_PREVISTA * 1440
            ELSE
                DECODE(
                    UPR.TEMPOFINALPROGRAMADO,
                    0,
                    (UPR.TEMPOFINALPLANEJADO - UPR.TEMPOINIPLANEJADO) * 1440,
                    (UPR.TEMPOFINALPROGRAMADO - UPR.TEMPOINIPROGRAMADO) * 1440
                )
        END AS MIN_PREV,
        ((UPR.TEMPOFINAL - UPR.TEMPOINICIAL) * 1440) AS MIN_REAL_BRUTO,
        UPP.TIPO_MAQUINA,
        UPP.CDFILIAL,
        MAQ.PROGRAM_POR_LEADTIME,
        UPR.STATUS AS STATUS_UP,
        UPR.SETOR,
        UPR.EXCLUIDA,
        UPR.TIPOUP,
        UPR.DTPRODFIM,
        UPR.DTPRODINI,
        UPR.NRTURNOINI,
        UPR.DTTEMPOINICIAL,
        UPR.DTTEMPOFINAL,
        UPR.DTTEMPOINIPROGRAMADO,
        UPR.DTTEMPOFINALPROGRAMA,
        UPR.DTTEMPOINIPLANEJADO,
        UPR.DTTEMPOFINALPLANEJAD,
        UPR.DURACAO_PREVISTA
    FROM sgtprd.UNIDADE_PROGR_PROD UPP
    JOIN sgtprd.UNIDADE_PROGRAMACAO UPR
        ON UPR.NUMEROUP = UPP.NUMEROUP
    JOIN sgtprd.UP_ORDEM_MVTO UOM
        ON UOM.NUMEROUP = UPR.NUMEROUP
    JOIN sgtprd.MAQUINA MAQ
        ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    WHERE UPR.SETOR = 5
      AND UPR.EXCLUIDA = 0
      AND UPR.TIPOUP = 0
      AND UPP.DATA_FIM >= :dt_inicio
      AND UPP.DATA_FIM < :dt_fim
),
VUP AS (
    SELECT
        V.NUMERO_OB,
        V.SEQ,
        V.NUMEROUP,
        V.NUMERO_MAQUINA,
        V.NOME_MAQUINA,
        V.TEMPOFINAL,
        V.TEMPOINICIAL,
        V.DATA_HORA_INICIO,
        V.DATA_HORA_FINAL,
        V.DATA_INI,
        V.TURNO_INI,
        V.DATA_FIM,
        V.TURNO_FIM,
        V.MIN_PAR_PROC,
        V.MIN_PREV,
        CASE
            WHEN V.MIN_REAL_BRUTO <= 1 THEN 1
            ELSE V.MIN_REAL_BRUTO - V.MIN_PAR_PROC + 1
        END AS MIN_REAL,
        V.TIPO_MAQUINA,
        V.CDFILIAL,
        V.PROGRAM_POR_LEADTIME,
        V.STATUS_UP,
        V.SETOR,
        V.EXCLUIDA,
        V.TIPOUP,
        V.DTPRODFIM,
        V.DTPRODINI,
        V.NRTURNOINI,
        V.DTTEMPOINICIAL,
        V.DTTEMPOFINAL,
        V.DTTEMPOINIPROGRAMADO,
        V.DTTEMPOFINALPROGRAMA,
        V.DTTEMPOINIPLANEJADO,
        V.DTTEMPOFINALPLANEJAD,
        V.DURACAO_PREVISTA
    FROM VUP_RAW V
),
DIM_PECAS_ORIGEM AS (
    -- Pecas/quilos reais de origem por OB (nao escalados por fase/PERC_GRUPO,
    -- valor unico repetido em todas as linhas da mesma OB).
    SELECT /*+ MATERIALIZE */
        GPO.NUMERO_OB,
        COUNT(GPP.IDPECASPRODUTO) AS QT_PECAS,
        SUM(GPP.QTLIQUIDA) AS QT_KILOS_REAL
    FROM sgtprd.GERAPECAORIGEMOB GPO
    JOIN sgtprd.GERAPECASPRODUTO GPP
        ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    WHERE GPO.NUMERO_OB IN (SELECT DISTINCT NUMERO_OB FROM VUP)
    GROUP BY GPO.NUMERO_OB
),
DIM_PECAS_DESTINO AS (
    -- Pecas/quilos reais de destino (acabado) por OB, mesma semantica acima.
    SELECT /*+ MATERIALIZE */
        GPD.NUMERO_OB,
        COUNT(GPP2.IDPECASPRODUTO) AS QT_PECAS,
        SUM(GPP2.QTLIQUIDA) AS QT_KILOS_REAL
    FROM sgtprd.GERAPECADESTINOOB GPD
    JOIN sgtprd.GERAPECASPRODUTO GPP2
        ON GPP2.IDPECASPRODUTO = GPD.IDPECASPRODUTO
    WHERE GPD.NUMERO_OB IN (SELECT DISTINCT NUMERO_OB FROM VUP)
    GROUP BY GPD.NUMERO_OB
),
OBF_BASE AS (
    SELECT /*+ MATERIALIZE */
        OBFX.NUMERO_OB,
        NVL(OBFX.SEQUENCIA, 0) AS SEQ,
        OBFX.NUMERO_MAQUINA,
        TRIM(MAQ.NOME_MAQUINA) AS NOME_MAQUINA,
        OBFX.CODIGO_FASE,
        OBFX.TIPO_PROCESSO,
        OBFX.PROCESSO_ESPECIFICO,
        OBFX.NUMEROORDEMMOVIMENTO,
        VUF.SEQ AS SEQUENCIAORDEMMOVIME,
        OBFX.STATUS AS STATUS_FASE,
        OBFX.DESTINO_RECEITA,
        GDX.TIPO_DESTINO AS TIPO_DESTINO,
        TRIM(DEX.DESCRICAO) AS DESCR_DESTINO,
        OBFX.CARGA_MAXIMA,
        OBFX.CODIGO_GRUPO,
        OBFX.OPERADOR_INICIO,
        OBFX.OPERADOR_FINAL,
        TO_NUMBER(OBFX.CBCORTELONGITUDINAL) AS CBCORTELONGITUDINAL,
        OBFX.ID_LIGA_CADREC_ITEMR,
        DECODE(OBFX.KILOS_PRODUZIDOS, 0, OBY.KILOS, OBFX.KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
        DECODE(OBFX.METROS_PRODUZIDOS, 0, OBY.METROS, OBFX.METROS_PRODUZIDOS) AS METROS_PRODUZIDOS,
        OBY.KILOS AS OBY_KILOS,
        OBY.METROS AS OBY_METROS,
        ITE.IDUNIDADEMEDIDA AS IDUNIDADEMEDIDA,
        OBY.CODPRO_REDUZIDO AS CODPRO_REDUZIDO,
        MAQ.TIPO_MAQUINA,
        MAQ.GRUPO AS GRUPO,
        MAQ.SECAO,
        MAQ.VELOCIDADE_MAQUINA,
        OBFX.VELOCIDADE AS VELOCIDADE_BASE,
        OBFX.CODIGO_VARIANTE,
        OBFX.CODIGO_COR_DESENHO,
        OBFX.ESPECIFICACAO_PRODUT,
        PRI.PROCESSO_INDUSTRIAL,
        PRI.TIPO_PROCESSO_INDUST,
        PRI.DESCRICAO_PI,
        OBE.NUMERO_GRUPO_PROGRAM,
        OBE.CODIGO_FLUXO,
        OBE.TIPO_ORDEM,
        OBE.IDGRUPOFLUXO,
        OBE.EXPORTACAO,
        OBE.PRIM_LOTE_POR_COR AS PRIM_LOTE_COR,
        OBE.PRIM_LOTE_PROCESSO AS PRIM_LOTE_PROC,
        OBE.OB_ALTERNATIVA,
        GPR.UNIDADE_FABRIL,
        LTRIM(TO_CHAR(GPR.UNIDADE_FABRIL), '0') AS UND_FAB,
        NVL(LP.LOCAL_PRODUCAO, 'NAO DEFINIDO') AS LOCAL_PRODUCAO,
        CASE
            WHEN OBFX.CODIGO_VARIANTE <> '     ' THEN
                ((TRUNC(MAQ.HORAMAQUINA_CARGA_DE) * 60) + (MAQ.HORAMAQUINA_CARGA_DE - TRUNC(MAQ.HORAMAQUINA_CARGA_DE)) * 100)
                + NVL((
                    SELECT VDE.TEMPO_PREPARACAO_MAQ
                    FROM sgtprd.VARIANTE_DESENHO VDE
                    WHERE VDE.PROCESSO_INDUSTRIAL = PRI.PROCESSO_INDUSTRIAL
                      AND VDE.CODIGO_DESENHO = OBFX.CODIGO_COR_DESENHO
                      AND VDE.CODIGO_VARIANTE = OBFX.CODIGO_VARIANTE
                      AND VDE.ESPECIFICACAO_PRODUT = OBFX.ESPECIFICACAO_PRODUT
                ), 0)
            ELSE
                (TRUNC(MAQ.HORAMAQUINA_CARGA_DE) * 60) + (MAQ.HORAMAQUINA_CARGA_DE - TRUNC(MAQ.HORAMAQUINA_CARGA_DE)) * 100
        END AS MIN_SETUP,
        CASE
            WHEN NVL((
                SELECT MAX(MR.SEQUENCIA_AJUSTE)
                FROM sgtprd.MOVTO_RECEITA MR
                WHERE MR.NUMEROORDEM = OBFX.NUMEROORDEMMOVIMENTO
                  AND MR.SEQUENCIAFASEOB = VUF.SEQ
            ), 0) <> 0 THEN 1
            ELSE 0
        END AS AJUSTE
    FROM sgtprd.OB_FASES OBFX
    JOIN VUP VUF
        ON VUF.NUMERO_OB = OBFX.NUMERO_OB
       AND VUF.SEQ = NVL(OBFX.SEQUENCIA, 0)
    JOIN sgtprd.OB_PRODUTO OBY
        ON OBY.NUMERO_OB = OBFX.NUMERO_OB
    JOIN sgtprd.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = OBY.CODPRO_REDUZIDO
    JOIN sgtprd.OB OBE
        ON OBE.NUMERO_OB = OBFX.NUMERO_OB
    JOIN sgtprd.MAQUINA MAQ
        ON MAQ.NUMERO_MAQUINA = OBFX.NUMERO_MAQUINA
       AND MAQ.SETOR = 5
    JOIN sgtprd.PROCESSO_INDUSTRIAL PRI
        ON PRI.CODIGO_FASE = OBFX.CODIGO_FASE
       AND PRI.TIPO_PROCESSO = OBFX.TIPO_PROCESSO
    JOIN sgtprd.GRUPO_MAQUINAS GPR
        ON GPR.SETOR = MAQ.SETOR
       AND GPR.GRUPO = MAQ.GRUPO
    LEFT JOIN sgtprd.DESTINO DEX
        ON DEX.DESTINO = OBFX.DESTINO_RECEITA
    LEFT JOIN sgtprd.GRUPO_DESTINO GDX
        ON GDX.CODIGO_GRUPO = DEX.CODIGO_GRUPO
    LEFT JOIN LOCAL_PROD LP
        ON LP.CODIGO_FASE = OBFX.CODIGO_FASE
    WHERE OBFX.DESTINO_RECEITA IN (0, 1, 2, 4)
),
OBF AS (
    SELECT /*+ MATERIALIZE */
        B.NUMERO_OB,
        B.SEQ,
        B.NUMERO_MAQUINA,
        B.NOME_MAQUINA,
        B.CODPRO_REDUZIDO,
        B.CODIGO_FASE,
        B.NUMEROORDEMMOVIMENTO,
        B.SEQUENCIAORDEMMOVIME,
        B.NUMERO_GRUPO_PROGRAM,
        B.CODIGO_FLUXO,
        B.STATUS_FASE,
        B.DESTINO_RECEITA,
        B.TIPO_DESTINO,
        B.DESCR_DESTINO,
        B.CARGA_MAXIMA,
        B.GRUPO,
        B.CODIGO_GRUPO,
        B.OPERADOR_INICIO,
        B.OPERADOR_FINAL,
        B.CBCORTELONGITUDINAL,
        B.ID_LIGA_CADREC_ITEMR,
        B.KILOS_PRODUZIDOS,
        B.METROS_PRODUZIDOS,
        B.IDUNIDADEMEDIDA,
        CASE
            WHEN B.CODIGO_GRUPO = 0 THEN 100
            WHEN B.CODIGO_GRUPO <> 0
                 AND B.TIPO_MAQUINA IN (17, 18, 19, 20, 21, 22, 60)
                 AND B.IDUNIDADEMEDIDA = 1
                 AND NVL(SUM(DECODE(B.KILOS_PRODUZIDOS, 0, B.OBY_KILOS, B.KILOS_PRODUZIDOS))
                     OVER (PARTITION BY B.CODIGO_GRUPO), 0) <> 0 THEN
                B.KILOS_PRODUZIDOS / SUM(DECODE(B.KILOS_PRODUZIDOS, 0, B.OBY_KILOS, B.KILOS_PRODUZIDOS))
                    OVER (PARTITION BY B.CODIGO_GRUPO) * 100
            WHEN NVL(SUM(DECODE(B.METROS_PRODUZIDOS, 0, B.OBY_METROS, B.METROS_PRODUZIDOS))
                     OVER (PARTITION BY B.CODIGO_GRUPO), 0) <> 0 THEN
                B.METROS_PRODUZIDOS / SUM(DECODE(B.METROS_PRODUZIDOS, 0, B.OBY_METROS, B.METROS_PRODUZIDOS))
                    OVER (PARTITION BY B.CODIGO_GRUPO) * 100
            ELSE 1 / NULLIF(COUNT(*) OVER (PARTITION BY B.CODIGO_GRUPO), 0)
        END AS PERC_GRUPO,
        B.VELOCIDADE_BASE,
        B.VELOCIDADE_MAQUINA,
        B.MIN_SETUP,
        B.AJUSTE,
        B.SECAO,
        B.TIPO_PROCESSO,
        B.PROCESSO_ESPECIFICO,
        B.TIPO_PROCESSO_INDUST,
        B.DESCRICAO_PI,
        B.CODIGO_COR_DESENHO,
        B.ESPECIFICACAO_PRODUT,
        B.CODIGO_VARIANTE,
        B.TIPO_ORDEM,
        B.IDGRUPOFLUXO,
        B.EXPORTACAO,
        B.PRIM_LOTE_COR,
        B.PRIM_LOTE_PROC,
        B.OB_ALTERNATIVA,
        B.UNIDADE_FABRIL,
        B.UND_FAB,
        B.LOCAL_PRODUCAO
    FROM OBF_BASE B
),
OBF_KEYS AS (
    SELECT DISTINCT
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        B.CODIGO_FASE,
        B.NUMERO_GRUPO_PROGRAM,
        B.CODIGO_FLUXO
    FROM OBF_BASE B
),
VEL AS (
    SELECT
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        MAX(CASE WHEN GFF.SEQUENCIA = B.SEQUENCIAORDEMMOVIME THEN GFM.VELOCIDADE END) AS VELOCIDADE_SEQ,
        MAX(CASE WHEN GFF.CODIGO_FASE = B.CODIGO_FASE THEN GFM.VELOCIDADE END) AS VELOCIDADE_FASE
    FROM OBF_KEYS B
    JOIN sgtprd.GRUPO_FLUXO GFL
        ON GFL.NUMERO_GRUPO_PROGRAM = B.NUMERO_GRUPO_PROGRAM
       AND GFL.CODIGO_FLUXO = B.CODIGO_FLUXO
    JOIN sgtprd.GRUPO_FLUXO_FASES GFF
        ON GFF.IDGRUPOFLUXO = GFL.IDGRUPOFLUXO
    JOIN sgtprd.GRUPO_FLUXO_MAQUINAS GFM
        ON GFM.IDGRUPOFLUXOFASE = GFF.IDGRUPOFLUXOFASE
       AND GFM.NUMERO_MAQUINA = B.NUMERO_MAQUINA
       AND GFM.ATIVA = 1
    GROUP BY
        B.NUMERO_OB,
        B.NUMERO_MAQUINA,
        B.SEQUENCIAORDEMMOVIME,
        B.CODIGO_FASE
)

SELECT
    VUP.NUMEROUP,
    VUP.CDFILIAL AS FILIAL,
    VUP.DATA_FIM AS DATA_PROD,
    VUP.TURNO_FIM AS TURNO_PROD,
    CASE VUP.TURNO_FIM
        WHEN 1 THEN 'TURNO 1'
        WHEN 2 THEN 'TURNO 2'
        WHEN 3 THEN 'TURNO 3'
        ELSE 'OUTRO'
    END AS TURNO_DESC,
    LTRIM(VUP.NUMERO_MAQUINA, '0') AS NUMERO_MAQUINA,
    VUP.NOME_MAQUINA,
    VUP.DATA_HORA_INICIO AS DATA_HORA_INI,
    VUP.DATA_HORA_FINAL AS DATA_HORA_FIM,
    VUP.TIPO_MAQUINA,
    VUP.STATUS_UP,
    CASE VUP.STATUS_UP
        WHEN 0 THEN 'CONFIRMADA'
        WHEN 1 THEN 'INICIADA'
        WHEN 2 THEN 'PROGRAMADA'
        WHEN 3 THEN 'PLANEJADA'
        ELSE 'STATUS ' || TO_CHAR(VUP.STATUS_UP)
    END AS DS_STATUS_UP,
    OBF.NUMERO_OB,
    OBF.NUMEROORDEMMOVIMENTO || '-' || OBF.SEQUENCIAORDEMMOVIME AS DOCUMENTO,
    OBF.CODIGO_FASE,
    OBF.STATUS_FASE,
    CASE OBF.STATUS_FASE
        WHEN 0 THEN 'PROGRAMADA'
        WHEN 1 THEN 'EMITIDA'
        WHEN 2 THEN 'PESADA'
        WHEN 3 THEN 'EM EXECUÇÃO'
        WHEN 4 THEN 'CONFIRMADA'
        ELSE 'STATUS ' || TO_CHAR(OBF.STATUS_FASE)
    END AS DS_STATUS_FASE,
    OBF.DESTINO_RECEITA,
    DF.DESCR_FASE,
    DF.DESCR_GRUPO_FASE,
    DF.SETOR_IND_SEQ,
    NVL(DF.DESCR_SETOR_INDUST, 'SEM SETOR') AS DESCR_SETOR_INDUST,
    DTM.DESCR_TIPO_MAQ,
    OBF.CODPRO_REDUZIDO AS REDUZ,
    REN.TPUNIDADEMEDIDA,
    PROD.DESCR_ITEM,
    PROD.TIPO,
    PROD.ARTIGO,
    PROD.DESCR_ARTIGO,
    PROD.LARGURA,
    PROD.COR,
    PROD.DESCR_COR,
    PROD.ACABAMENTO,
    PROD.DESENHO,
    PROD.VARIANTE,
    PROD.CODIND,
    PROD.CODIGO_ALTERNATIVO,
    PROD.DESCR_CLASSIFICACAO_COR,
    PROD.CODIGO,
    OBF.DESCR_DESTINO,
    TRIM(vtd.DESCRICAO) AS DESCR_TIPO_DESTINO,
    TO_CHAR(VUP.DATA_FIM, 'DD') AS DIA,
    TO_CHAR(VUP.DATA_FIM, 'RRRRMM') AS ANO_MES,
    TO_NUMBER(TO_CHAR(VUP.DATA_FIM, 'IYYYIW')) AS ANO_SEM,
    OBF.NUMERO_GRUPO_PROGRAM,
    OBF.CODIGO_FLUXO AS FLUXO,
    OBF.SECAO,
    OBF.TIPO_ORDEM,
    DECODE(OBF.CBCORTELONGITUDINAL, 1, 1, 0) AS FASE_CORTE_LONGITUDINAL,
    OBF.ID_LIGA_CADREC_ITEMR,
    OBF.UNIDADE_FABRIL,
    OBF.UND_FAB,
    NVL(OBF.LOCAL_PRODUCAO, 'NAO DEFINIDO') AS LOCAL_PRODUCAO,
    TRIM(ufb.NOME_UNIDADE_FABRIL) AS NOME_UNIDADE_FABRIL,
    OBF.EXPORTACAO,
    OBF.PRIM_LOTE_COR,
    OBF.PRIM_LOTE_PROC,
    TO_NUMBER(OBF.CODIGO_FASE || OBF.TIPO_PROCESSO) AS PI,
    TRIM(OBF.DESCRICAO_PI) AS DESCR_PI,
    OBF.TIPO_PROCESSO_INDUST,
    OBF.KILOS_PRODUZIDOS AS QT_KG,
    OBF.METROS_PRODUZIDOS AS QT_MT,
    OBF.CARGA_MAXIMA AS CARGA_MAXIMA,
    REN.RENDIMENTO,
    CASE
        WHEN OBF.TIPO_DESTINO = 1 AND OBF.CARGA_MAXIMA = 0 THEN
            DECODE(REN.TPUNIDADEMEDIDA, 1, OBF.KILOS_PRODUZIDOS, OBF.METROS_PRODUZIDOS) * OBF.PERC_GRUPO / 100
        ELSE
            OBF.CARGA_MAXIMA * OBF.PERC_GRUPO / 100
    END AS CARGA_PREV_GRUPO,
    OBF.GRUPO,
    OBF.CODIGO_GRUPO,
    DECODE(NULLIF(OBF.TIPO_DESTINO, 0), 1, 1, 0) AS REPROCESSO,
    OBF.PERC_GRUPO,
    CASE
        WHEN OBF.TIPO_DESTINO = 1 AND OBF.CARGA_MAXIMA = 0 THEN 100
        WHEN OBF.TIPO_DESTINO <> 1 AND OBF.CARGA_MAXIMA = 0 THEN 0
        ELSE DECODE(
            OBF.CARGA_MAXIMA,
            0, 0,
            DECODE(
                OBF.PERC_GRUPO,
                0, 0,
                (DECODE(REN.TPUNIDADEMEDIDA, 1, OBF.KILOS_PRODUZIDOS, OBF.METROS_PRODUZIDOS) /
                 (OBF.CARGA_MAXIMA * OBF.PERC_GRUPO / 100))
            )
        ) * 100
    END AS EFIC_CARGA,
    CASE
        WHEN OBF.VELOCIDADE_BASE <> 0 THEN OBF.VELOCIDADE_BASE
        WHEN NVL(VEL.VELOCIDADE_SEQ, 0) <> 0 THEN VEL.VELOCIDADE_SEQ
        WHEN NVL(VEL.VELOCIDADE_FASE, 0) <> 0 THEN VEL.VELOCIDADE_FASE
        ELSE OBF.VELOCIDADE_MAQUINA
    END AS VELOCIDADE,
    OBF.MIN_SETUP * OBF.PERC_GRUPO / 100 * 100 / 100 AS MIN_SETUP,
    (VUP.MIN_PREV - OBF.MIN_SETUP) * OBF.PERC_GRUPO / 100 * 100 / 100 AS MIN_PROCESSO,
    DECODE(VUP.MIN_PREV, 0, 100, VUP.MIN_PREV / VUP.MIN_REAL * 100) AS EFIC_TEMPO,
    OBF.AJUSTE AS AJUSTE,
    VUP.DTTEMPOINIPROGRAMADO,
    VUP.DTTEMPOFINALPROGRAMA,
    VUP.DTTEMPOINIPLANEJADO,
    VUP.DTTEMPOFINALPLANEJAD,
    VUP.MIN_REAL * OBF.PERC_GRUPO / 100 AS MIN_REAL,
    VUP.MIN_PREV * OBF.PERC_GRUPO / 100 AS MIN_PREV,
    ROUND(
        (VUP.MIN_REAL * OBF.PERC_GRUPO / 100) -
        (VUP.MIN_PREV * OBF.PERC_GRUPO / 100),
        2
    ) AS DESVIO_MIN,
    ROUND(
        ABS(
            (VUP.MIN_REAL * OBF.PERC_GRUPO / 100) -
            (VUP.MIN_PREV * OBF.PERC_GRUPO / 100)
        ),
        2
    ) AS DESVIO_MIN_ABS,
    ROUND(
        OBF.KILOS_PRODUZIDOS * 60 /
        NULLIF(VUP.MIN_REAL * OBF.PERC_GRUPO / 100, 0),
        2
    ) AS QT_KG_HR,
    ROUND(
        OBF.METROS_PRODUZIDOS * 60 /
        NULLIF(VUP.MIN_REAL * OBF.PERC_GRUPO / 100, 0),
        2
    ) AS QT_MT_HR,
    ROUND(
        (
            CASE
                WHEN VUP.DURACAO_PREVISTA <> 0
                    THEN VUP.DURACAO_PREVISTA * 1440
                ELSE CASE
                    WHEN VUP.DTTEMPOFINALPROGRAMA = DATE '1899-12-30'
                        THEN (VUP.DTTEMPOFINALPLANEJAD - VUP.DTTEMPOINIPLANEJADO) * 1440
                    ELSE (VUP.DTTEMPOFINALPROGRAMA - VUP.DTTEMPOINIPROGRAMADO) * 1440
                END
            END
        )
        /
        NULLIF(VUP.MIN_REAL, 0) * 100,
        2
    ) AS EFIC_PROC_LINHA,
    DPO.QT_PECAS AS PECAS_ORIGEM,
    DPO.QT_KILOS_REAL AS KG_ORIGEM_REAL,
    DPD.QT_PECAS AS PECAS_DESTINO,
    DPD.QT_KILOS_REAL AS KG_DESTINO_REAL
FROM VUP
JOIN OBF
    ON OBF.NUMERO_OB = VUP.NUMERO_OB
   AND OBF.SEQ = VUP.SEQ
LEFT JOIN VEL
    ON VEL.NUMERO_OB = OBF.NUMERO_OB
   AND VEL.NUMERO_MAQUINA = OBF.NUMERO_MAQUINA
   AND VEL.SEQUENCIAORDEMMOVIME = OBF.SEQUENCIAORDEMMOVIME
LEFT JOIN REN
    ON REN.NUMERO_OB = OBF.NUMERO_OB
LEFT JOIN PROD
    ON PROD.REDUZ = OBF.CODPRO_REDUZIDO
LEFT JOIN sgtprd.VW_ENU_TIPO_DESTINO vtd
    ON vtd.TIPO_DESTINO = OBF.TIPO_DESTINO
LEFT JOIN sgtprd.UNIDADE_FABRIL ufb
    ON ufb.CODIGO_UNIDADE_FABRI = OBF.UNIDADE_FABRIL
LEFT JOIN DIM_FASE DF
    ON DF.CODIGO_FASE = OBF.CODIGO_FASE
LEFT JOIN DIM_TIPO_MAQ DTM
    ON DTM.TIPO_MAQUINA = VUP.TIPO_MAQUINA
LEFT JOIN DIM_PECAS_ORIGEM DPO
    ON DPO.NUMERO_OB = OBF.NUMERO_OB
LEFT JOIN DIM_PECAS_DESTINO DPD
    ON DPD.NUMERO_OB = OBF.NUMERO_OB
-- Ordenacao removida para reduzir custo em carga semanal

