// Config mínima de lint para o Dashboard (JS vanilla ES modules no browser).
// Foco em erros reais (no-undef, sintaxe); estilo fica fora do escopo.
export default [
    {
        files: ["Dashboard/js/**/*.js"],
        languageOptions: {
            ecmaVersion: 2023,
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                navigator: "readonly",
                location: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                fetch: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                requestAnimationFrame: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                AbortController: "readonly",
                WebSocket: "readonly",
                Intl: "readonly",
                atob: "readonly",
                btoa: "readonly",
                TextDecoder: "readonly",
                TextEncoder: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                CustomEvent: "readonly",
                MutationObserver: "readonly",
                ResizeObserver: "readonly",
                ApexCharts: "readonly",
                lucide: "readonly",
                confirm: "readonly",
                alert: "readonly",
                prompt: "readonly",
            },
        },
        rules: {
            "no-undef": "error",
            "no-dupe-keys": "error",
            "no-dupe-args": "error",
            "no-unreachable": "error",
            "no-constant-condition": ["error", { checkLoops: false }],
            "valid-typeof": "error",
            "no-unused-vars": ["warn", { args: "none" }],
            "no-var": "error",
            "prefer-const": ["warn", { destructuring: "all" }],
            "eqeqeq": ["error", "always", { null: "ignore" }],
        },
    },
];
