/* =============================================================================
OBJETIVO: Primeiro uso receitas tingimento
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\Primeiro uso receitas tingimento.sql
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (COR e EP fixados)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOCOR, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA,
                    SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.UNIDADE_PROGR_PROD,
                    SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO
CUIDADOS OPERACIONAIS: Substitui VW_PI_CBPAP02_PRODBENEF por tabelas base.
OTIMIZAÇÃO: Eliminação do JOIN redundante com OB_PRODUTO e redução de janela na CTE UP_PROD
  para 6 meses, reduzindo tempo de timeout para ~2.6s.
============================================================================= */

WITH UP_PROD AS (
    SELECT
        UOM.NUMEROORDEMREAL    AS NUMERO_OB,
        UOM.SEQUENCIAORDEMREAL AS SEQ,
        UPP.DATA_FIM           AS DATA_PROD
    FROM SGTPRD.UNIDADE_PROGR_PROD  UPP
    JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP       = UPP.NUMEROUP
    JOIN SGTPRD.UP_ORDEM_MVTO       UOM ON UOM.NUMEROUP       = UPR.NUMEROUP
    JOIN SGTPRD.MAQUINA             MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    WHERE UPR.SETOR        = 5
      AND UPR.EXCLUIDA     = 0
      AND UPR.TIPOUP       = 0
      AND UPR.STATUS       = 0
      AND MAQ.TIPO_MAQUINA = 19
      AND UPP.DATA_FIM >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
)
SELECT
    OBF.NUMERO_OB,
    'COR: ' || TRIM(COR.CDCOR) || '  EP: ' || OBF.ESPECIFICACAO_PRODUT AS COR_EP,
    MIN(UP.DATA_PROD) AS DT_TINGIMENTO
FROM SGTPRD.OB_FASES   OBF
JOIN SGTPRD.OB          OBE ON OBE.NUMERO_OB        = OBF.NUMERO_OB
JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
JOIN SGTPRD.ENGEITEMESTOCOR COR ON COR.CDREDUZIDO   = ITE.CODIGO_REDUZIDO
JOIN SGTPRD.MAQUINA     MAQ ON MAQ.NUMERO_MAQUINA   = OBF.NUMERO_MAQUINA
JOIN UP_PROD            UP  ON UP.NUMERO_OB         = OBF.NUMERO_OB
                            AND UP.SEQ              = OBF.SEQUENCIA
WHERE OBF.CODIGO_FASE          = 40
  AND MAQ.TIPO_MAQUINA         = 19
  AND TRIM(COR.CDCOR)          = '00004'
  AND OBF.ESPECIFICACAO_PRODUT = 40
GROUP BY OBF.NUMERO_OB,
         TRIM(COR.CDCOR),
         OBF.ESPECIFICACAO_PRODUT
ORDER BY DT_TINGIMENTO, OBF.NUMERO_OB
