/* =============================================================================
OBJETIVO: Monitoramento Máquinas de Tingimento
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\Monitoramento Máquinas de Tingimento.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.MAQUINA, SGTPRD.MOVIMENTO_MAQUINA, SGTPRD.OB_FASES, SGTPRD.PKGUTIL0001
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT 
    LTRIM(MAQ.NUMERO_MAQUINA, '0') AS NR_MAQUINA,
    ORD.NR_ORDEM,
    ORD.GRUPO_OB,
    ORD.DT_HR_INICIO,
    ORD.MIN_PROCESSO,
    ORD.DT_HR_PREVISAO_TERMINO,
    CASE 
        WHEN (ORD.DT_HR_PREVISAO_TERMINO - SYSDATE) < 0 THEN 'TERMINO ATRASADO'
        WHEN (ORD.DT_HR_PREVISAO_TERMINO - SYSDATE) IS NULL THEN NULL
        ELSE TO_CHAR(TRUNC((ORD.DT_HR_PREVISAO_TERMINO - SYSDATE) * 24), 'FM00') || ':' || TO_CHAR(MOD((ORD.DT_HR_PREVISAO_TERMINO - SYSDATE) * 1440, 60), 'FM00') 
    END AS HR_MIN_FALTANTE
FROM 
    SGTPRD.MAQUINA MAQ
    LEFT JOIN (
        SELECT 
            OBF.NUMERO_MAQUINA,
            DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO) AS NR_ORDEM,
            DECODE(OBF.CODIGO_GRUPO, 0, OBF.SEQUENCIA, 0) AS SEQUENCIA,
            DECODE(OBF.CODIGO_GRUPO, 0, 'NAO', 'SIM') AS GRUPO_OB,
            MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL AS MIN_PROCESSO,
            DATE '1996-01-01' + OBF.TEMPO_INICIAL_CONFIR / 1440 AS DT_HR_INICIO,
            DATE '1996-01-01' + (OBF.TEMPO_INICIAL_CONFIR + (MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL)) / 1440 AS DT_HR_PREVISAO_TERMINO
        FROM 
            SGTPRD.OB_FASES OBF
            JOIN SGTPRD.MOVIMENTO_MAQUINA MOV ON MOV.NUMERO_ORDEM = DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO)
                AND MOV.SEQUENCIA = DECODE(OBF.CODIGO_GRUPO, 0, OBF.SEQUENCIA, 0)
        WHERE 
            OBF.CODIGO_FASE = 40
            AND OBF.STATUS = 3
        GROUP BY 
            OBF.NUMERO_MAQUINA,
            DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO),
            DECODE(OBF.CODIGO_GRUPO, 0, OBF.SEQUENCIA, 0),
            DECODE(OBF.CODIGO_GRUPO, 0, 'NAO', 'SIM'),
            DATE '1996-01-01' + OBF.TEMPO_INICIAL_CONFIR / 1440,
            MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL,
            DATE '1996-01-01' + (OBF.TEMPO_INICIAL_CONFIR + (MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL)) / 1440
    ) ORD ON ORD.NUMERO_MAQUINA = MAQ.NUMERO_MAQUINA
WHERE 
    MAQ.TIPO_MAQUINA = 17
    AND MAQ.NUMERO_MAQUINA NOT IN ('000000MQ00', '000000MQ98')
