/* =============================================================================
OBJETIVO: Histórico detalhado de todas as lavações de máquinas
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: 01_beneficiamento_tingimento/bnf_lavacao_de_maquina_lista_todas_as_lavacoes.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.MAQUINA, SGTPRD.PARADAS_MAQUINA, SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT 
    LTRIM(UPR.NUMERO_MAQUINA, 0) AS NR_MAQUINA,
    UPR.DTPRODFIM AS DT_LAVACAO,
    (UPR.DTTEMPOFINALCONFIRMA - UPR.DTTEMPOINICONFIRMADO) * 1440 + 1 AS MIN_TOTAL,
    UPR.DTTEMPOINICONFIRMADO AS DT_HR_INICIO,
    UPR.DTTEMPOFINALCONFIRMA AS DT_HR_FINAL,
    LEAD(UPR.DTTEMPOFINALCONFIRMA) OVER (PARTITION BY LTRIM(UPR.NUMERO_MAQUINA, 0) ORDER BY UPR.DTTEMPOFINALCONFIRMA ASC) AS DT_HR_FINAL_PROXIMA,
    LEAD(UPR.DTTEMPOFINALCONFIRMA) OVER (PARTITION BY LTRIM(UPR.NUMERO_MAQUINA, 0) ORDER BY UPR.DTTEMPOFINALCONFIRMA ASC) - UPR.DTTEMPOFINALCONFIRMA AS TEMPO_RECORRENCIA
FROM 
    SGTPRD.UNIDADE_PROGRAMACAO UPR,
    SGTPRD.UP_ORDEM_MVTO UMO,
    SGTPRD.PARADAS_MAQUINA PMA,
    SGTPRD.MAQUINA MAQ
WHERE 
    UMO.NUMEROUP = UPR.NUMEROUP
    AND UMO.CODIGOMOVIMENTO = 2
    AND UPR.EXCLUIDA = 0
    AND MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    AND PMA.NUMERO_PARADA = UMO.NUMEROORDEMREAL
    AND UPR.SETOR = 5
    AND PMA.CODIGO_PARADA = 'BNF13'
    AND MAQ.GRUPO IN ('TG001', 'TG002', 'TG003')
    AND UPR.STATUS = 0
GROUP BY 
    LTRIM(UPR.NUMERO_MAQUINA, 0),
    UPR.DTPRODFIM,
    (UPR.DTTEMPOFINALCONFIRMA - UPR.DTTEMPOINICONFIRMADO) * 1440 + 1,
    UPR.DTTEMPOINICONFIRMADO,
    UPR.DTTEMPOFINALCONFIRMA;
