/* =============================================================================
OBJETIVO: OB_s com tingimento confirmado e quantidade de produtos usados
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s com tingimento confirmado e quantidade de produtos usados.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.COML_TIPOSCOR, SGTPRD.COR, SGTPRD.ENGEITEMESTOCOR, SGTPRD.ITENS_ESTOQUE, SGTPRD.MOVTO_RECEITA, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.PKGUTIL0001
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO) NR_OB,
       SUBSTR(ITE.CODIGO, 4, 5) AS COD_ARTIGO,
       SUBSTR(ITE.CODIGO, 13, 5) AS COD_COR,
       TRIM(TCO.DESCRICAO) AS DESCR_TIPOCOR,
       TRIM(ITE.DESCRICAO) AS DESCR_PRODUTO,
       SUM(OBP.KILOS) QT_OB_CRU,
       DATE '1996-01-01' + OBF.TEMPO_FINAL_CONFIRMA / 1440 HORA_TING_CONFIRMADO,
       
       (SELECT SUM(REC.QUANTIDADEPESADA)
          FROM SGTPRD.MOVTO_RECEITA REC
         WHERE REC.NUMEROORDEM =
               DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO)
           AND REC.SEQUENCIAFASEOB =
               DECODE(OBF.CODIGO_GRUPO, 0, OBF.SEQUENCIA, 0)
           AND OBF.CODIGO_FASE = 40) QUIMICO_USADO

  FROM SGTPRD.OB_FASES       OBF
  JOIN SGTPRD.OB_PRODUTO     OBP ON OBP.NUMERO_OB = OBF.NUMERO_OB
  JOIN SGTPRD.ITENS_ESTOQUE  ITE ON ITE.CODIGO_REDUZIDO = OBP.CODPRO_REDUZIDO
  LEFT JOIN SGTPRD.ENGEITEMESTOCOR EGC ON EGC.CDREDUZIDO = ITE.CODIGO_REDUZIDO
  LEFT JOIN SGTPRD.COR             COO ON COO.CODIGO_COR = EGC.CDCOR
  LEFT JOIN SGTPRD.COML_TIPOSCOR   TCO ON TCO.TIPOCOR = COO.TIPOCOR
 WHERE OBF.CODIGO_FASE = 40
   -- Janela: últimos 30 dias (antes: um único dia fixo, 09/02/2022). TEMPO_* = minutos
   -- desde 1996-01-01; faixa direta na coluna evita TRUNC e permite usar índice.
   AND OBF.TEMPO_FINAL_CONFIRMA >= (TRUNC(SYSDATE) - 30 - DATE '1996-01-01') * 1440
   AND OBF.TEMPO_FINAL_CONFIRMA <  (TRUNC(SYSDATE) + 1 - DATE '1996-01-01') * 1440
 GROUP BY SUBSTR(ITE.CODIGO, 4, 5),
          SUBSTR(ITE.CODIGO, 13, 5),
          TRIM(TCO.DESCRICAO),
          TRIM(ITE.DESCRICAO),
          DECODE(OBF.CODIGO_GRUPO, 0, OBF.NUMERO_OB, OBF.CODIGO_GRUPO),
          DECODE(OBF.CODIGO_GRUPO, 0, OBF.SEQUENCIA, 0),
          OBF.SEQUENCIA,
          OBF.CODIGO_FASE,
          OBF.TEMPO_FINAL_CONFIRMA;
