/* =============================================================================
OBJETIVO: Últimas lavações realizadas por máquina
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: 01_beneficiamento_tingimento/bnf_lavacao_de_maquina_lista_todas_as_lavacoes.sql (Query #2)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.MAQUINA, SGTPRD.PARADAS_MAQUINA, SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT DISTINCT  -- Ou adicione funções de agregação se necessário
    LTRIM(UPR.NUMERO_MAQUINA, 0) AS NR_MAQUINA,
    UPR.DTPRODFIM AS DT_LAVACAO,
    (UPR.DTTEMPOFINALCONFIRMA - UPR.DTTEMPOINICONFIRMADO) * 1440 + 1 AS MIN_TOTAL,
    UPR.DTTEMPOINICONFIRMADO AS DT_HR_INICIO,
    UPR.DTTEMPOFINALCONFIRMA AS DT_HR_FINAL,
    LEAD(UPR.DTTEMPOFINALCONFIRMA) OVER (PARTITION BY LTRIM(UPR.NUMERO_MAQUINA, 0) ORDER BY UPR.DTTEMPOFINALCONFIRMA) AS DT_HR_FINAL_PROXIMA,
    COALESCE(LEAD(UPR.DTTEMPOFINALCONFIRMA) OVER (PARTITION BY LTRIM(UPR.NUMERO_MAQUINA, 0) ORDER BY UPR.DTTEMPOFINALCONFIRMA) - UPR.DTTEMPOFINALCONFIRMA, 0) AS TEMPO_RECORRENCIA -- Tratamento de nulos
FROM 
    SGTPRD.UNIDADE_PROGRAMACAO UPR
INNER JOIN 
    SGTPRD.UP_ORDEM_MVTO UMO ON UMO.NUMEROUP = UPR.NUMEROUP
INNER JOIN 
    SGTPRD.PARADAS_MAQUINA PMA ON PMA.NUMERO_PARADA = UMO.NUMEROORDEMREAL
INNER JOIN
    SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
WHERE 
    UMO.CODIGOMOVIMENTO = 2
    AND UPR.EXCLUIDA = 0
    AND UPR.SETOR = 5
    AND PMA.CODIGO_PARADA = 'BNF13'
    AND MAQ.GRUPO IN ('TG001', 'TG002', 'TG003')
    AND UPR.STATUS = 0;
