-- =============================================================================
-- OBJETIVO: Monitora - Tingimento e Reprocesso (Auditoria Analítica Detalhada por OB)
-- DOMÍNIO: 01_beneficiamento_tingimento
-- ARQUIVO: bnf_monitora_tingimento_e_reprocesso_detalhado.sql
-- TIPO: Auditoria Analítica Detalhada / Diagnóstico e Rastreabilidade Individual de OBs
-- PARÂMETROS / BINDS: Nenhum por padrão (corte mensal automático). Para investigar uma OB
--                    específica, adicione o filtro no final: `WHERE BR.NUMERO_OB = :bind_ob`
-- TABELAS PRINCIPAIS: SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO, SGTPRD.MAQUINA,
--                    SGTPRD.OB_FASES, SGTPRD.DESTINO, SGTPRD.GRUPO_DESTINO,
--                    SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECAORIGEM, SGTPRD.GERAPECASPRODUTO,
--                    SGTPRD.OB_PRODUTO, SGTPRD.PEDPRODUCAOOB, SGTPRD.OFORDENS,
--                    SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES
-- COLUNAS DE AUDITORIA RETORNADAS:
--   - NUMERO_OB, SEQUENCIA: Chave unívoca do evento produtivo/fase
--   - OB_ATUAL, OB_PAI, OB_RAIZ: Nós genealógicos identificados
--   - NIVEL_LINHAGEM: Grau de profundidade (0=Própria, 1=Mãe, 2=Avó, 3=Bisavó)
--   - CAMINHO_LINHAGEM: String do caminho percorrido (ex: 187993 -> 187949 -> 187950)
--   - TEM_ANCESTRAL_ACIMA_NIVEL_3: 0=Encerrou no limite, 1=Existe ancestral acima da Bisavó
--   - STATUS_LINHAGEM: RESOLVIDA, RAIZ, AMBIGUA ou LINHAGEM_EXCEDE_LIMITE
--   - ORIGEM_COMERCIAL: PEDIDO_DIRETO, PEDIDO_HERDADO, MAKE_TO_STOCK, LINHAGEM_AMBIGUA, etc.
--   - NIVEL_PEDIDO_HERDADO: Nível genealógico onde o pedido foi localizado (0, 1, 2, 3)
--   - OB_ORIGEM_PEDIDO: Número da OB ancestral que continha a amarração do pedido de venda
--   - DT_ENTREGA_RESOLVIDA: Data de entrega comercial (EXPEDIREM YYYYMMDD) obtida
--   - DT_ENTREGA_AMBIGUA: 0=Data unívoca, 1=Datas comerciais conflitantes no pedido
--   - DTPRODFIM, STATUS, TIPO_DESTINO, CODIGO_FASE, GRUPO_DEFEITO: Dados fabris da ordem
--   - VALOR_KG: Peso efetivo apurado conforme regra aprovada
--   - FONTE_VALOR_KG: Rastreabilidade da fonte de peso (KILOS_PRODUZIDOS, PESO_REPROCESSO, QT_CRU, etc.)
--   - CLASSIFICACAO_FABRIL: REP_CONFIRMADO, REP_PREVISTO ou REP_POSTERIOR
--   - REP_PEND_ENTREGA_MES: Flag (1/0) indicando se a ordem atende aos critérios para pendência no mês
-- CUIDADOS OPERACIONAIS:
--   - Consulta somente leitura para suporte ao PCP, Qualidade e Engenharia de Produção.
--   - Tempo de execução medido no SGTPRD: ~3,9s para o universo completo do mês.
-- =============================================================================

WITH
CALENDARIO AS (
    SELECT
        TRUNC(B.DATA_REFERENCIA, 'MM') AS DT_INICIO_MES,
        ADD_MONTHS(TRUNC(B.DATA_REFERENCIA, 'MM'), 1) AS DT_INICIO_MES_SEGUINTE,
        TO_NUMBER(TO_CHAR(TRUNC(B.DATA_REFERENCIA, 'MM'), 'YYYYMMDD')) AS DT_EXP_INI,
        TO_NUMBER(TO_CHAR(ADD_MONTHS(TRUNC(B.DATA_REFERENCIA, 'MM'), 1) - 1, 'YYYYMMDD')) AS DT_EXP_FIM
    FROM (
        SELECT
            CASE
                WHEN EXTRACT(DAY FROM SYSDATE) <= 4 THEN ADD_MONTHS(SYSDATE, -1)
                ELSE SYSDATE
            END AS DATA_REFERENCIA
        FROM DUAL
    ) B
),
BASE_REPROCESSOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        UPR.DTPRODFIM,
        UOM.NUMEROORDEMREAL AS NUMERO_OB,
        OBF.SEQUENCIA,
        OBF.STATUS AS OBF_STATUS,
        OBF.CODIGO_FASE,
        OBF.DESTINO_RECEITA,
        TRIM(OBF.GRUPO_DEFEITO) AS GRUPO_DEFEITO,
        COALESCE(GDX.TIPO_DESTINO, 0) AS TIPO_DESTINO,
        OBF.PESO_REPROCESSO AS RAW_PESO_REPROCESSO,
        OBF.KILOS_PRODUZIDOS AS RAW_KILOS_PRODUZIDOS,
        NULLIF(OBF.PESO_REPROCESSO, 0) AS PESO_REPROCESSO,
        NULLIF(OBF.KILOS_PRODUZIDOS, 0) AS KILOS_PRODUZIDOS,
        CASE
            WHEN OBF.STATUS = 4 THEN 'REP_CONFIRMADO'
            WHEN UPR.DTPRODFIM < C.DT_INICIO_MES_SEGUINTE THEN 'REP_PREVISTO'
            ELSE 'REP_POSTERIOR'
        END AS CLASSIFICACAO_FABRIL
    FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
    JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
    JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
    LEFT JOIN SGTPRD.DESTINO DEX ON DEX.DESTINO = OBF.DESTINO_RECEITA
    LEFT JOIN SGTPRD.GRUPO_DESTINO GDX ON GDX.CODIGO_GRUPO = DEX.CODIGO_GRUPO
    CROSS JOIN CALENDARIO C
    WHERE UPR.SETOR = 5
      AND UPR.EXCLUIDA = 0
      AND UPR.TIPOUP = 0
      AND MAQ.TIPO_MAQUINA = 17
      AND GDX.TIPO_DESTINO = 1
      AND OBF.CODIGO_FASE = 40
      AND TRIM(OBF.GRUPO_DEFEITO) IN ('1', '3', '4')
      AND (
          (OBF.STATUS = 4 AND UPR.DTPRODFIM >= C.DT_INICIO_MES AND UPR.DTPRODFIM < C.DT_INICIO_MES_SEGUINTE)
          OR (OBF.STATUS <> 4)
      )
),
OBS_SEM_PESO_REP AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB 
    FROM BASE_REPROCESSOS_RAW 
    WHERE OBF_STATUS <> 4 AND PESO_REPROCESSO IS NULL
),
FALLBACK_QT_CRU AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(O POR GPP) INDEX(POR GERPECOB_INDIPECAORIGEMOB) INDEX(GPP GERPECAS_PKGERAPECASPRODUTO) */
        POR.NUMERO_OB,
        SUM(GPP.QTLIQUIDA) AS QT_CRU
    FROM OBS_SEM_PESO_REP O
    JOIN SGTPRD.GERAPECAORIGEMOB POR ON POR.NUMERO_OB = O.NUMERO_OB
    JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = POR.IDPECASPRODUTO
    GROUP BY POR.NUMERO_OB
),
FALLBACK_KILOS_PROG AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(O OBP) INDEX(OBP OB_PROD_PK_OB_PRODUTO) */
        OBP.NUMERO_OB,
        SUM(OBP.KILOS_PROGRAMADOS) AS KILOS_PROGRAMADOS
    FROM OBS_SEM_PESO_REP O
    JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = O.NUMERO_OB
    GROUP BY OBP.NUMERO_OB
),
BASE_REPROCESSOS AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        BR.DTPRODFIM,
        BR.NUMERO_OB,
        BR.SEQUENCIA,
        BR.OBF_STATUS,
        BR.CODIGO_FASE,
        BR.TIPO_DESTINO,
        BR.GRUPO_DEFEITO,
        BR.CLASSIFICACAO_FABRIL,
        CASE
            WHEN BR.OBF_STATUS = 4 THEN COALESCE(BR.RAW_KILOS_PRODUZIDOS, 0)
            ELSE COALESCE(
                BR.PESO_REPROCESSO,
                NULLIF(FQC.QT_CRU, 0),
                NULLIF(FKP.KILOS_PROGRAMADOS, 0),
                BR.KILOS_PRODUZIDOS,
                0
            )
        END AS VALOR_KG,
        CASE
            WHEN BR.OBF_STATUS = 4 THEN '1. KILOS_PRODUZIDOS_CONFIRMADO'
            WHEN BR.PESO_REPROCESSO IS NOT NULL THEN '1. PESO_REPROCESSO'
            WHEN FQC.QT_CRU IS NOT NULL AND FQC.QT_CRU > 0 THEN '2. QT_CRU'
            WHEN FKP.KILOS_PROGRAMADOS IS NOT NULL AND FKP.KILOS_PROGRAMADOS > 0 THEN '3. KILOS_PROGRAMADOS'
            WHEN BR.KILOS_PRODUZIDOS IS NOT NULL AND BR.KILOS_PRODUZIDOS > 0 THEN '4. KILOS_PRODUZIDOS_PENDENTE'
            ELSE '5. ZERO'
        END AS FONTE_VALOR_KG
    FROM BASE_REPROCESSOS_RAW BR
    LEFT JOIN FALLBACK_QT_CRU FQC ON FQC.NUMERO_OB = BR.NUMERO_OB
    LEFT JOIN FALLBACK_KILOS_PROG FKP ON FKP.NUMERO_OB = BR.NUMERO_OB
),
OBS_ALVO AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB FROM BASE_REPROCESSOS
),
MAES_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OA O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OA.NUMERO_OB AS OB_FILHA,
        O_ORIG.NUMERO_OB AS OB_MAE
    FROM OBS_ALVO OA
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OA.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OA.NUMERO_OB
),
MAES_AGRUPADAS AS (
    SELECT
        OB_FILHA,
        COUNT(DISTINCT OB_MAE) AS QTD_MAES,
        MIN(OB_MAE) AS OB_MAE
    FROM MAES_RAW
    GROUP BY OB_FILHA
),
OBS_MAE_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_MAE AS NUMERO_OB
    FROM MAES_AGRUPADAS
    WHERE QTD_MAES = 1
),
AVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OM O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OM.NUMERO_OB AS OB_MAE,
        O_ORIG.NUMERO_OB AS OB_AVO
    FROM OBS_MAE_DISTINCT OM
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OM.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OM.NUMERO_OB
),
AVOS_AGRUPADAS AS (
    SELECT
        OB_MAE,
        COUNT(DISTINCT OB_AVO) AS QTD_AVOS,
        MIN(OB_AVO) AS OB_AVO
    FROM AVOS_RAW
    GROUP BY OB_MAE
),
OBS_AVO_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_AVO AS NUMERO_OB
    FROM AVOS_AGRUPADAS
    WHERE QTD_AVOS = 1
),
BISAVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OA O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OA.NUMERO_OB AS OB_AVO,
        O_ORIG.NUMERO_OB AS OB_BISAVO
    FROM OBS_AVO_DISTINCT OA
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OA.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OA.NUMERO_OB
),
BISAVOS_AGRUPADAS AS (
    SELECT
        OB_AVO,
        COUNT(DISTINCT OB_BISAVO) AS QTD_BISAVOS,
        MIN(OB_BISAVO) AS OB_BISAVO
    FROM BISAVOS_RAW
    GROUP BY OB_AVO
),
OBS_BISAVO_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_BISAVO AS NUMERO_OB
    FROM BISAVOS_AGRUPADAS
    WHERE QTD_BISAVOS = 1
),
TATARAVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OB O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OB.NUMERO_OB AS OB_BISAVO,
        O_ORIG.NUMERO_OB AS OB_TATARAVO
    FROM OBS_BISAVO_DISTINCT OB
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OB.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OB.NUMERO_OB
),
TATARAVOS_AGRUPADAS AS (
    SELECT
        OB_BISAVO,
        COUNT(DISTINCT OB_TATARAVO) AS QTD_TATARAVOS
    FROM TATARAVOS_RAW
    GROUP BY OB_BISAVO
),
GENEALOGIA AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        OA.NUMERO_OB,
        M.OB_MAE,
        M.QTD_MAES,
        A.OB_AVO,
        A.QTD_AVOS,
        B.OB_BISAVO,
        B.QTD_BISAVOS,
        CASE WHEN T.QTD_TATARAVOS > 0 THEN 1 ELSE 0 END AS TEM_ANCESTRAL_ACIMA_NIVEL_3,
        CASE
            WHEN M.OB_MAE IS NULL THEN 0
            WHEN A.OB_AVO IS NULL THEN 1
            WHEN B.OB_BISAVO IS NULL THEN 2
            ELSE 3
        END AS NIVEL_LINHAGEM,
        CASE
            WHEN T.QTD_TATARAVOS > 0 THEN NULL
            ELSE COALESCE(B.OB_BISAVO, A.OB_AVO, M.OB_MAE, OA.NUMERO_OB)
        END AS OB_RAIZ,
        OA.NUMERO_OB || 
            CASE WHEN M.OB_MAE IS NOT NULL THEN ' -> ' || M.OB_MAE END ||
            CASE WHEN A.OB_AVO IS NOT NULL THEN ' -> ' || A.OB_AVO END ||
            CASE WHEN B.OB_BISAVO IS NOT NULL THEN ' -> ' || B.OB_BISAVO END ||
            CASE WHEN T.QTD_TATARAVOS > 0 THEN ' -> [...]' END AS CAMINHO_LINHAGEM,
        CASE
            WHEN T.QTD_TATARAVOS > 0 THEN 'LINHAGEM_EXCEDE_LIMITE'
            WHEN M.QTD_MAES > 1 OR A.QTD_AVOS > 1 OR B.QTD_BISAVOS > 1 THEN 'AMBIGUA'
            WHEN M.OB_MAE IS NULL THEN 'RAIZ'
            ELSE 'RESOLVIDA'
        END AS STATUS_LINHAGEM
    FROM OBS_ALVO OA
    LEFT JOIN MAES_AGRUPADAS M ON M.OB_FILHA = OA.NUMERO_OB
    LEFT JOIN AVOS_AGRUPADAS A ON A.OB_MAE = M.OB_MAE AND M.QTD_MAES = 1
    LEFT JOIN BISAVOS_AGRUPADAS B ON B.OB_AVO = A.OB_AVO AND A.QTD_AVOS = 1
    LEFT JOIN TATARAVOS_AGRUPADAS T ON T.OB_BISAVO = B.OB_BISAVO AND B.QTD_BISAVOS = 1
),
UNIVERSO_GENEALOGIA AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ NUMERO_OB FROM OBS_ALVO
    UNION ALL
    SELECT OB_MAE FROM MAES_RAW
    UNION ALL
    SELECT OB_AVO FROM AVOS_RAW
    UNION ALL
    SELECT OB_BISAVO FROM BISAVOS_RAW
),
DISTINCT_UNIVERSO AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB FROM UNIVERSO_GENEALOGIA
),
COMERCIAL_POR_OB AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(DU P OFO OFP IPQ) INDEX(P PPRODUOB_IND_OB_NUMERO) */
        DU.NUMERO_OB,
        MIN(OFO.NUMEROOF) AS NUMEROOF,
        MIN(IPQ.EXPEDIREM) AS DT_ENTREGA,
        MAX(IPQ.EXPEDIREM) AS DT_ENTREGA_MAX,
        COUNT(DISTINCT IPQ.EXPEDIREM) AS QTD_DATAS_ENTREGA
    FROM DISTINCT_UNIVERSO DU
    JOIN SGTPRD.PEDPRODUCAOOB P ON P.NUMEROOB = DU.NUMERO_OB
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = P.NUMERO
    LEFT JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF
    LEFT JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    GROUP BY DU.NUMERO_OB
),
RESOLUCAO_COMERCIAL AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        G.NUMERO_OB,
        G.OB_MAE,
        G.OB_AVO,
        G.OB_BISAVO,
        G.OB_RAIZ,
        G.NIVEL_LINHAGEM,
        G.CAMINHO_LINHAGEM,
        G.STATUS_LINHAGEM,
        G.TEM_ANCESTRAL_ACIMA_NIVEL_3,
        CASE
            WHEN G.STATUS_LINHAGEM = 'LINHAGEM_EXCEDE_LIMITE' THEN 'LINHAGEM_EXCEDE_LIMITE'
            WHEN G.STATUS_LINHAGEM = 'AMBIGUA' THEN 'LINHAGEM_AMBIGUA'
            WHEN CD.DT_ENTREGA IS NOT NULL THEN 'PEDIDO_DIRETO'
            WHEN CM.DT_ENTREGA IS NOT NULL THEN 'PEDIDO_HERDADO'
            WHEN CA.DT_ENTREGA IS NOT NULL THEN 'PEDIDO_HERDADO'
            WHEN CB.DT_ENTREGA IS NOT NULL THEN 'PEDIDO_HERDADO'
            WHEN CD.NUMEROOF IS NOT NULL OR CM.NUMEROOF IS NOT NULL OR CA.NUMEROOF IS NOT NULL OR CB.NUMEROOF IS NOT NULL THEN 'MAKE_TO_STOCK'
            ELSE 'LINHAGEM_NAO_RESOLVIDA'
        END AS ORIGEM_COMERCIAL,
        CASE
            WHEN G.STATUS_LINHAGEM IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE') THEN NULL
            WHEN CD.DT_ENTREGA IS NOT NULL THEN 0
            WHEN CM.DT_ENTREGA IS NOT NULL THEN 1
            WHEN CA.DT_ENTREGA IS NOT NULL THEN 2
            WHEN CB.DT_ENTREGA IS NOT NULL THEN 3
            ELSE NULL
        END AS NIVEL_PEDIDO_HERDADO,
        CASE
            WHEN G.STATUS_LINHAGEM IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE') THEN NULL
            WHEN CD.DT_ENTREGA IS NOT NULL THEN G.NUMERO_OB
            WHEN CM.DT_ENTREGA IS NOT NULL THEN G.OB_MAE
            WHEN CA.DT_ENTREGA IS NOT NULL THEN G.OB_AVO
            WHEN CB.DT_ENTREGA IS NOT NULL THEN G.OB_BISAVO
            ELSE NULL
        END AS OB_ORIGEM_PEDIDO,
        CASE
            WHEN G.STATUS_LINHAGEM IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE') THEN NULL
            ELSE COALESCE(CD.DT_ENTREGA, CM.DT_ENTREGA, CA.DT_ENTREGA, CB.DT_ENTREGA)
        END AS DT_ENTREGA_RESOLVIDA,
        CASE
            WHEN G.STATUS_LINHAGEM IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE') THEN 0
            WHEN CD.DT_ENTREGA IS NOT NULL AND CD.DT_ENTREGA <> CD.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NOT NULL AND CM.DT_ENTREGA <> CM.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NULL AND CA.DT_ENTREGA IS NOT NULL AND CA.DT_ENTREGA <> CA.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NULL AND CA.DT_ENTREGA IS NULL AND CB.DT_ENTREGA IS NOT NULL AND CB.DT_ENTREGA <> CB.DT_ENTREGA_MAX THEN 1
            ELSE 0
        END AS DT_ENTREGA_AMBIGUA
    FROM GENEALOGIA G
    LEFT JOIN COMERCIAL_POR_OB CD ON CD.NUMERO_OB = G.NUMERO_OB
    LEFT JOIN COMERCIAL_POR_OB CM ON CM.NUMERO_OB = G.OB_MAE
    LEFT JOIN COMERCIAL_POR_OB CA ON CA.NUMERO_OB = G.OB_AVO
    LEFT JOIN COMERCIAL_POR_OB CB ON CB.NUMERO_OB = G.OB_BISAVO
)
SELECT /*+ LEADING(BR RC) */
    BR.NUMERO_OB,
    BR.SEQUENCIA,
    BR.NUMERO_OB AS OB_ATUAL,
    RC.OB_MAE AS OB_PAI,
    RC.OB_RAIZ,
    RC.NIVEL_LINHAGEM,
    RC.CAMINHO_LINHAGEM,
    RC.TEM_ANCESTRAL_ACIMA_NIVEL_3,
    RC.STATUS_LINHAGEM,
    RC.ORIGEM_COMERCIAL,
    RC.NIVEL_PEDIDO_HERDADO,
    RC.OB_ORIGEM_PEDIDO,
    RC.DT_ENTREGA_RESOLVIDA,
    RC.DT_ENTREGA_AMBIGUA,
    BR.DTPRODFIM,
    BR.OBF_STATUS AS STATUS,
    BR.TIPO_DESTINO,
    BR.CODIGO_FASE,
    BR.GRUPO_DEFEITO,
    BR.VALOR_KG,
    BR.FONTE_VALOR_KG,
    BR.CLASSIFICACAO_FABRIL,
    CASE 
        WHEN BR.OBF_STATUS <> 4 
         AND RC.STATUS_LINHAGEM NOT IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE')
         AND RC.DT_ENTREGA_AMBIGUA = 0
         AND RC.DT_ENTREGA_RESOLVIDA BETWEEN C.DT_EXP_INI AND C.DT_EXP_FIM 
        THEN 1 
        ELSE 0 
    END AS REP_PEND_ENTREGA_MES
FROM BASE_REPROCESSOS BR
JOIN RESOLUCAO_COMERCIAL RC ON RC.NUMERO_OB = BR.NUMERO_OB
CROSS JOIN CALENDARIO C
ORDER BY BR.CLASSIFICACAO_FABRIL, BR.NUMERO_OB, BR.SEQUENCIA
