/* =============================================================================
OBJETIVO: Monitora montagem de lote
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\Monitora montagem de lote.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.COML_TIPOSCOR, SGTPRD.COR, SGTPRD.ENGEITEMESTOCOR, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UNIDADE_PROGR_PROD, SGTPRD.UP_ORDEM_MVTO
SUBSTITUIÇÕES: nenhuma view/função customizada; DATA_HORA_FINAL é projetada como DATA_HORA_FIM para preservar o conjunto de colunas.
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
EVIDÊNCIA PRÉVIA: ORA-00904 confirmado em UPP.DATA_HORA_FIM; catálogo/validação apontam SGTPRD.UNIDADE_PROGR_PROD.DATA_HORA_FINAL. Validação final desta correção: pendente.
============================================================================= */

WITH
    -- 1. UPs de beneficiamento de montagem (fase 10) finalizadas hoje
    UP_MTG AS (
        SELECT /*+ MATERIALIZE */
               UOM.NUMEROORDEMREAL    AS NUMERO_OB,
               UOM.SEQUENCIAORDEMREAL AS SEQ,
               UPP.DATA_INI,
               UPP.DATA_HORA_FINAL AS DATA_HORA_FIM,
               UPR.STATUS
          FROM SGTPRD.UNIDADE_PROGR_PROD  UPP
          JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP = UPP.NUMEROUP
          JOIN SGTPRD.UP_ORDEM_MVTO       UOM ON UOM.NUMEROUP = UPR.NUMEROUP
          JOIN SGTPRD.MAQUINA             MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
         WHERE UPR.SETOR    = 5
           AND UPR.EXCLUIDA = 0
           AND UPR.TIPOUP   = 0
           AND UPP.DATA_INI = TRUNC(SYSDATE)
    ),
    -- O filtro de hoje define o conjunto de OBs; reutilizá-lo evita varrer
    -- fases, movimentos e pedidos que nunca chegam ao resultado final.
    OB_ALVO AS (
        SELECT /*+ MATERIALIZE */ DISTINCT NUMERO_OB
          FROM UP_MTG
         WHERE NUMERO_OB IS NOT NULL
    ),
    SEQ_TING AS (
        SELECT OBF.NUMERO_OB,
               MIN(OBF.SEQUENCIA) AS SEQ_TING
          FROM SGTPRD.OB_FASES OBF
          JOIN OB_ALVO OBA ON OBA.NUMERO_OB = OBF.NUMERO_OB
         WHERE OBF.CODIGO_FASE = 40
         GROUP BY OBF.NUMERO_OB
    ),
    OB_MAQ AS (
        SELECT OBF.NUMERO_OB,
               OBF.SEQUENCIA,
               MAX(LTRIM(OBF.NUMERO_MAQUINA, '0')) AS MQ
          FROM SGTPRD.OB_FASES OBF
          JOIN SEQ_TING ST ON ST.NUMERO_OB = OBF.NUMERO_OB
                           AND ST.SEQ_TING = OBF.SEQUENCIA
         GROUP BY OBF.NUMERO_OB, OBF.SEQUENCIA
    ),
    -- 2. Dados de montagem da OB (peças cruas, peso cru, sequência de tingimento)
    OB_MONTADA AS (
        SELECT /*+ MATERIALIZE */
               OBE.NUMERO_OB,
               OBE.CODIGO_REDUZIDO_CRU,
               COUNT(GPO.IDPECASPRODUTO) AS PC_CRU,
               ROUND(SUM(NVL(GPP.QTLIQUIDA, 0)), 2) AS CRU_KG,
                ST.SEQ_TING
          FROM SGTPRD.OB                 OBE
          JOIN OB_ALVO                    OBA ON OBA.NUMERO_OB = OBE.NUMERO_OB
          JOIN SGTPRD.PEDPRODUCAOOB      PPO ON PPO.NUMEROOB = OBE.NUMERO_OB 
                                             AND PPO.SETOR = 5 
                                             AND PPO.OBMONTADA = 1
          LEFT JOIN SEQ_TING              ST ON ST.NUMERO_OB = OBE.NUMERO_OB
          LEFT JOIN SGTPRD.GERAPECAORIGEMOB GPO ON GPO.NUMERO_OB = OBE.NUMERO_OB
          LEFT JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
         WHERE OBE.STATUS <> 0
          GROUP BY OBE.NUMERO_OB, OBE.CODIGO_REDUZIDO_CRU, ST.SEQ_TING
    ),
    -- 3. Início do tingimento via UP (fase 40)
    UP_TING AS (
        SELECT /*+ MATERIALIZE */
               UOM.NUMEROORDEMREAL    AS NUMERO_OB,
               UOM.SEQUENCIAORDEMREAL AS SEQ,
               MAX(UPP.DATA_HORA_INICIO) AS DATA_HORA_INICIO
           FROM SGTPRD.UNIDADE_PROGR_PROD  UPP
          JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP = UPP.NUMEROUP
          JOIN SGTPRD.UP_ORDEM_MVTO       UOM ON UOM.NUMEROUP = UPR.NUMEROUP
          JOIN OB_ALVO                    OBA ON OBA.NUMERO_OB = UOM.NUMEROORDEMREAL
         WHERE UPR.SETOR    = 5
           AND UPR.EXCLUIDA = 0
           AND UPR.TIPOUP   = 0
         GROUP BY UOM.NUMEROORDEMREAL, UOM.SEQUENCIAORDEMREAL
    ),
    -- 4. Data de entrega do pedido
    PEDIDO_OB AS (
        SELECT /*+ MATERIALIZE */
               PPOB.NUMEROOB AS NR_OB,
               MAX(PED.DTENTREGA) AS DT_ENTREGA
           FROM SGTPRD.PEDPRODUCAOOB PPOB
          JOIN OB_ALVO OBA ON OBA.NUMERO_OB = PPOB.NUMEROOB
          JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
          JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO
          JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF
          JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
          JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
          JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
         GROUP BY PPOB.NUMEROOB
    )
SELECT 
    PRF.NUMERO_OB,
    OBMQ.MQ,
    TRIM(OBF.CODIGO_PLACA)                   AS PLACA,
    TRIM(ITE.CODIGO_ALTERNATIVO)             AS ALTERNATIVO,
    ITE.CODIGO_REDUZIDO                      AS REDUZ,
    OBM.CODIGO_REDUZIDO_CRU                  AS REDUZ_CRU,
    TRIM(ITE.DESCRICAO)                      AS DESCR_PRODUTO,
    OBM.PC_CRU,
    OBM.CRU_KG,
    PRF.DATA_HORA_FIM,
    PRF.STATUS,
    UTI.DATA_HORA_INICIO                     AS INICIO_TINGIMENTO,
    OBP.DT_ENTREGA                           AS DT_ENTREGA
FROM 
    UP_MTG PRF
JOIN 
    SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = PRF.NUMERO_OB 
                       AND OBF.SEQUENCIA = PRF.SEQ
                       AND OBF.CODIGO_FASE = 10
                       AND OBF.FASE_PROGRAMADA_MANU = 0
                       AND OBF.FASE_ALTERADA = 0
JOIN 
    SGTPRD.OB_PRODUTO OBPR ON OBPR.NUMERO_OB = PRF.NUMERO_OB
JOIN 
    SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBPR.CODPRO_REDUZIDO
JOIN 
    OB_MONTADA OBM ON OBM.NUMERO_OB = PRF.NUMERO_OB
LEFT JOIN 
    UP_TING UTI ON UTI.NUMERO_OB = PRF.NUMERO_OB 
               AND UTI.SEQ = OBM.SEQ_TING
LEFT JOIN
    OB_MAQ OBMQ ON OBMQ.NUMERO_OB = PRF.NUMERO_OB
               AND OBMQ.SEQUENCIA = OBM.SEQ_TING
LEFT JOIN 
    PEDIDO_OB OBP ON OBP.NR_OB = PRF.NUMERO_OB
ORDER BY 
    PRF.DATA_HORA_FIM DESC;
