/* =============================================================================
OBJETIVO: Químico - valor média comparado ao preço de faturamento
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\Químico - valor média comparado ao preço de faturamento.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.COML_GRUPOSPRECOSITE, SGTPRD.COML_ITEMPORGRUPODEP, SGTPRD.COML_PRECOSARTIGOS, SGTPRD.ITENS_ESTOQUE, SGTPRD.MOVTO_RECEITA, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.PEDPRODUCAOOB, SGTPRD.TABELA_DATAS, SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UNIDADE_PROGR_PROD, SGTPRD.UP_ORDEM_MVTO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH
    PERIODO AS (
        SELECT MIN(DAT.DATA) AS DATA_INICIO,
               MAX(DAT.DATA) + 1 AS DATA_FIM
          FROM SGTPRD.TABELA_DATAS DAT
         WHERE DAT.ANO_MES = 202203
    ),
    OB_BASE AS (
        SELECT OBF.NUMEROORDEMMOVIMENTO,
               OBF.SEQUENCIAORDEMMOVIME,
               (SELECT MAX(OBP.CODPRO_REDUZIDO) 
                  FROM SGTPRD.OB_PRODUTO OBP
                  JOIN SGTPRD.OB_FASES   OBFXX ON OBFXX.NUMERO_OB = OBP.NUMERO_OB
                 WHERE OBFXX.NUMEROORDEMMOVIMENTO = OBF.NUMEROORDEMMOVIMENTO
                   AND OBFXX.SEQUENCIAORDEMMOVIME = OBF.SEQUENCIAORDEMMOVIME
                   AND OBFXX.CODIGO_FASE = 40) AS CODIGO_REDUZIDO,
               SUM(OBF.KILOS_PRODUZIDOS)       AS QT_CRU,
               UPP.DATA_HORA_FINAL
           FROM SGTPRD.OB                 OBE
          JOIN SGTPRD.OB_FASES           OBF  ON OBF.NUMERO_OB = OBE.NUMERO_OB
          JOIN SGTPRD.PEDPRODUCAOOB      PPO  ON PPO.NUMEROOB = OBE.NUMERO_OB 
                                             AND PPO.SETOR = 5 
                                             AND PPO.OBMONTADA = 1
          JOIN SGTPRD.UP_ORDEM_MVTO      UOM  ON UOM.NUMEROORDEMREAL = OBE.NUMERO_OB 
                                             AND UOM.SEQUENCIAORDEMREAL = OBF.SEQUENCIA
          JOIN SGTPRD.UNIDADE_PROGR_PROD UPP  ON UPP.NUMEROUP = UOM.NUMEROUP
          JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP = UPP.NUMEROUP 
                                              AND UPR.SETOR = 5 
                                              AND UPR.EXCLUIDA = 0 
                                              AND UPR.TIPOUP = 0
          CROSS JOIN PERIODO P
         WHERE OBF.CODIGO_FASE = 40
           AND UPP.DATA_HORA_FINAL >= P.DATA_INICIO
           AND UPP.DATA_HORA_FINAL < P.DATA_FIM
          GROUP BY OBF.NUMEROORDEMMOVIMENTO,
                   OBF.SEQUENCIAORDEMMOVIME,
                   UPP.DATA_HORA_FINAL
    ),
    OB_CHAVES AS (
        SELECT DISTINCT OB.NUMEROORDEMMOVIMENTO,
                        OB.SEQUENCIAORDEMMOVIME
          FROM OB_BASE OB
    ),
    OB_REDUZIDOS AS (
        SELECT DISTINCT OB.CODIGO_REDUZIDO
          FROM OB_BASE OB
         WHERE OB.CODIGO_REDUZIDO IS NOT NULL
    ),
    PRC AS (
        SELECT PAR.GRUPOPRECOSITEM IDGRUPO,
               R.ITEM REDUZ,
               TRIM(ITE.CODIGO_ALTERNATIVO) CODIGO_ALTERNATIVO,
               TRIM(GPI.IDENTIFICACAOPRECO) COD_GRUPO_PRECO,
               PAR.PRECO PRECO_UNIT_BASE,
               TRIM(ITE.CODIGO) CODIND
          FROM SGTPRD.COML_PRECOSARTIGOS PAR
          JOIN SGTPRD.COML_GRUPOSPRECOSITE GPI
            ON GPI.GRUPOPRECOSITEM = PAR.GRUPOPRECOSITEM
          JOIN SGTPRD.COML_ITEMPORGRUPODEP R
            ON R.GRUPOPRECOSITEM = GPI.GRUPOPRECOSITEM
          JOIN OB_REDUZIDOS OBR
            ON OBR.CODIGO_REDUZIDO = R.ITEM
          JOIN SGTPRD.ITENS_ESTOQUE ITE
            ON ITE.CODIGO_REDUZIDO = R.ITEM
         WHERE PAR.TABELAPRECO = 9000
    ),
    REC AS (
        SELECT R.NUMEROORDEM,
               R.SEQUENCIAFASEOB,
               SUM(R.QUANTIDADE)          AS QUANTIDADE,
               SUM(R.QUANTIDADEPESADA)    AS QUANTIDADE_PESADA,
               SUM(R.QUANTIDADE_ORIGINAL) AS QUANTIDADE_ORIGINAL,
               R.EMITIDAEMGRUPO,
               R.DEPOSITO
          FROM SGTPRD.MOVTO_RECEITA R
          JOIN OB_CHAVES OBK
            ON OBK.NUMEROORDEMMOVIMENTO = R.NUMEROORDEM
           AND OBK.SEQUENCIAORDEMMOVIME = R.SEQUENCIAFASEOB
         WHERE R.TIPO_PESAGEM = 1
           AND R.MOVCONFIRMADO = 1
         GROUP BY R.NUMEROORDEM, R.SEQUENCIAFASEOB, R.EMITIDAEMGRUPO, R.DEPOSITO
    )
SELECT PRC.IDGRUPO,
       PRC.REDUZ,
       PRC.CODIGO_ALTERNATIVO,
       PRC.COD_GRUPO_PRECO,
       PRC.PRECO_UNIT_BASE,
       PRC.CODIND,
       REC.NUMEROORDEM,
       REC.SEQUENCIAFASEOB,
       REC.QUANTIDADE,
       REC.QUANTIDADE_PESADA,
       REC.QUANTIDADE_ORIGINAL,
       REC.EMITIDAEMGRUPO,
       REC.DEPOSITO,
       OB.NUMEROORDEMMOVIMENTO,
       OB.SEQUENCIAORDEMMOVIME,
       OB.CODIGO_REDUZIDO,
       OB.QT_CRU,
       OB.DATA_HORA_FINAL,
       DAT.DATA
   FROM OB_BASE OB
  JOIN REC                 ON REC.NUMEROORDEM = OB.NUMEROORDEMMOVIMENTO
                          AND REC.SEQUENCIAFASEOB = OB.SEQUENCIAORDEMMOVIME
  JOIN SGTPRD.TABELA_DATAS DAT ON DAT.DATA = TRUNC(OB.DATA_HORA_FINAL)
  LEFT JOIN PRC            ON PRC.REDUZ = OB.CODIGO_REDUZIDO
 WHERE DAT.ANO_MES = 202203
 ORDER BY OB.DATA_HORA_FINAL;
   
