/* =============================================================================
OBJETIVO: OB_s em aberto pelo Reduzido
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s com receitas que faltam emitir.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.FASES_FLUXO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_COMPLEMENTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAOOB, SGTPRD.PKGUTIL0001
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH PED_EXCLUSIVO AS (
    SELECT /*+ MATERIALIZE */
           PPO.NUMEROOB AS NUMERO_OB,
           COUNT(DISTINCT PCO.PEDIDO) AS NRO_PEDIDOS,
           MAX(TRIM(PCO.PEDIDOCLIENTE)) AS PEDIDO_CLIENTE,
           MIN(CASE WHEN NVL(IPC.EXPEDIREM, 0) = 0
                    THEN DATE '1899-12-30'
                    ELSE TO_DATE(TO_CHAR(IPC.EXPEDIREM), 'YYYYMMDD')
               END) AS DATA_ENTREGA
      FROM SGTPRD.PEDPRODUCAOOB    PPO
      JOIN SGTPRD.OFORDENS         OFO ON OFO.NUMEROPEDPRODUCAO  = PPO.NUMERO
      JOIN SGTPRD.OFPEDIDO         OFP ON OFP.NUMEROOF           = OFO.NUMEROOF
      JOIN SGTPRD.ITENSPEDIDOQTDES IPX ON IPX.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPX.IDITEMPEDGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL  PCO ON PCO.PEDIDO             = IPG.PEDIDO
      JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = PCO.PEDIDO AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
     WHERE PPO.SETOR = 5
     GROUP BY PPO.NUMEROOB
),
FASE_ATUAL AS (
    SELECT /*+ MATERIALIZE */
           OBF.NUMERO_OB,
           MIN(OBF.SEQUENCIA)     KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS SEQ,
           MIN(OBF.CODIGO_FASE)   KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS FASE,
           MIN(OBF.STATUS)        KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS STATUS_FASE,
           MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS DESCR_FASE
      FROM SGTPRD.OB_FASES OBF
      JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
     WHERE OBF.STATUS <> 4
     GROUP BY OBF.NUMERO_OB
)
SELECT CASE WHEN NVL(PED.NRO_PEDIDOS, 0) = 1 THEN PED.PEDIDO_CLIENTE ELSE '' END AS P_CLIENTE,
       OB.STATUS,
       CASE OB.STATUS
            WHEN 0 THEN 'CANCELADA'
            WHEN 1 THEN 'EM PROCESSO'
            WHEN 2 THEN 'CONCLUIDA'
            ELSE TO_CHAR(OB.STATUS)
       END                                            AS STATUS_OB,
       OB.NUMERO_OB                                   AS OB,
       OBP.CODPRO_REDUZIDO                            AS REDUZ,
       OBF.CODIGO_COR_DESENHO                         AS COR,
       OBF.ESPECIFICACAO_PRODUT                       AS EP,
       FAT.SEQ,
       FAT.FASE,
       TRIM(OBF.CODIGO_PLACA)                         AS PLACA,
       TRIM(ITE.CODIGO_ALTERNATIVO)                   AS ARTIGO,
       FAT.DESCR_FASE,
       CASE FAT.STATUS_FASE
            WHEN 0 THEN 'PROGRAMADA'
            WHEN 1 THEN 'EMITIDA'
            WHEN 2 THEN 'PESADA'
            WHEN 3 THEN 'EM PROCESSO'
            WHEN 4 THEN 'CONCLUIDO'
            WHEN 5 THEN 'CANCELADA'
            ELSE TO_CHAR(FAT.STATUS_FASE)
       END                                            AS DESCR_STATUS_FASE,
       TRUNC(CASE
                WHEN (SYSDATE - (DATE '1996-01-01' + OB.TEMPO_PROGRAMACAO / 1440)) < 0 THEN 0
                ELSE (SYSDATE - (DATE '1996-01-01' + OB.TEMPO_PROGRAMACAO / 1440))
             END, 2)                                  AS DIAS_PARADOS,
       LTRIM(OBF.NUMERO_MAQUINA, '0')                 AS MAQUINA,
       ITC.LARGURA,
       ITC.GRAMATURA,
       DATE '1996-01-01' + OB.TEMPO_PROGRAMACAO / 1440 AS DATA_PROGR,
       PED.DATA_ENTREGA                               AS DATA_ENTREGA,
       CASE
           WHEN OBP.DATA_ENTREGA_PEDIDO BETWEEN 19000101 AND 29991231
           THEN TO_DATE(TO_CHAR(OBP.DATA_ENTREGA_PEDIDO), 'YYYYMMDD')
       END AS DATA_PLANO,
       CASE
           WHEN OBP.DATA_ENTREGA_PEDIDO BETWEEN 19000101 AND 29991231
           THEN (TO_DATE(TO_CHAR(OBP.DATA_ENTREGA_PEDIDO), 'YYYYMMDD') - PED.DATA_ENTREGA) || ' DIA(S)'
       END AS ATRASO_PREVISTO
  FROM SGTPRD.OB_PRODUTO OBP
  JOIN SGTPRD.OB OB ON OBP.NUMERO_OB = OB.NUMERO_OB
  JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = OB.NUMERO_OB
  JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBP.CODPRO_REDUZIDO
  LEFT JOIN SGTPRD.ITENS_COMPLEMENTO ITC ON ITC.CODIGO_REDUZIDO = OBP.CODPRO_REDUZIDO
  LEFT JOIN PED_EXCLUSIVO PED ON PED.NUMERO_OB = OB.NUMERO_OB
  LEFT JOIN FASE_ATUAL FAT ON FAT.NUMERO_OB = OB.NUMERO_OB
 WHERE OB.STATUS <> 0
   AND OBF.CODIGO_FASE = 150
   AND SUBSTR(ITE.CODIGO, 4, 5) IN ('00056')
 ORDER BY FAT.SEQ, DIAS_PARADOS DESC;
