/* =============================================================================
OBJETIVO: Consulta Receita
DOMÍNIO: 01_beneficiamento_tingimento
ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta Receita.sql
TIPO: Tingimento e Tinturaria
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.CADASTRO_RECEITAS, SGTPRD.CLASSIFICACAO_COR, SGTPRD.ESPECIFICACAO_PRODUT, SGTPRD.LIGA_CADREC_ITEMREC
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
NOTA DE GOVERNANÇA: a projeção necessária da antiga view foi resolvida diretamente
  em CADASTRO_RECEITAS/LIGA_CADREC_ITEMREC; não há dependência de view ou pacote.
============================================================================= */

SELECT TRIM(CR.GRAFICO_RECEITA) GRAFICO,
       CR.CODIGO_REDUZIDO_RECE REDUZ_REC,
       CR.PROCESSOINDUSTRIAL PI,
       TRIM(SUBSTR(CR.CODCOR, 1, 11)) COR,
       CR.ESPECIFICACAO_PRODUT EP,
       TRIM(EPX.DESCRICAO) DESCR_EP,
       CR.PROCESSO_ESPECIFICO PE,
       CL.CODIGO_CLASSIFICACAO CD,
       CL.DESCRICAO DESCR_CLASSIFICACAO,
       DECODE(CR.PROCESSO_ATIVO_PRODU, 1, 'ATIVA', 'INATIVA') RECEITA,
       LCR.NUM_TINGIMENTOS_PROD NR_TING_PRD,
       CR.TEMPO_RECEITA,
       TO_DATE(CR.DATA_ALTERACAO, 'YYYYMMDD') DATA_ALTERACAO,
       CR.HORA_ALTERACAO,
       CR.USUARIO_ALTERACAO
  FROM SGTPRD.CADASTRO_RECEITAS CR
  JOIN SGTPRD.CLASSIFICACAO_COR CL 
    ON CL.CODIGO_CLASSIFICACAO = CR.CODIGO_CLASSIFICACAO
  LEFT JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR
    ON LCR.CODIGO_REDUZIDO_RECE = CR.CODIGO_REDUZIDO_RECE
  LEFT JOIN SGTPRD.ESPECIFICACAO_PRODUT EPX
    ON EPX.ESPECIFICACAOPRODUTO = CR.ESPECIFICACAO_PRODUT
 WHERE CR.ESPECIFICACAO_PRODUT = 32
 ORDER BY CL.CODIGO_CLASSIFICACAO, CR.CODCOR;
