-- =============================================================================
-- OBJETIVO: Monitora - Tingimento e Reprocesso (KPI Consolidado Oficial)
-- DOMÍNIO: 01_beneficiamento_tingimento
-- ARQUIVO: bnf_monitora_tingimento_e_reprocesso.sql
-- TIPO: KPI Consolidado Executivo / Gestão Fabril e Qualidade
-- PARÂMETROS / BINDS: Nenhum (corte temporal mensal dinâmico no bloco CALENDARIO)
-- TABELAS PRINCIPAIS: SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO, SGTPRD.MAQUINA,
--                    SGTPRD.OB_FASES, SGTPRD.DESTINO, SGTPRD.GRUPO_DESTINO,
--                    SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECAORIGEM, SGTPRD.GERAPECASPRODUTO,
--                    SGTPRD.OB_PRODUTO, SGTPRD.PEDPRODUCAOOB, SGTPRD.OFORDENS,
--                    SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES
-- INDICADORES GERADOS:
--   - TING_CONFIRMADO: Produção normal de tingimento finalizada no mês (STATUS=4, TIPO_DESTINO=0)
--   - REP_CONFIRMADO: Reprocesso industrial finalizado no mês (STATUS=4, TIPO_DESTINO=1, Fase 40, Defeitos 1,3,4)
--   - REP_PREVISTO: Reprocesso aberto no parque fabril com DTPRODFIM no mês (STATUS<>4)
--   - REP_POSTERIOR: Reprocesso aberto no parque fabril com DTPRODFIM no mês seguinte ou posterior (STATUS<>4)
--   - REP_PEND_ENTREGA_MES: Reprocessos pendentes cuja data de entrega comercial prometida recai no mês
--   - PERC_REP_CONFIRMADO: % Reprocesso confirmado sobre o tingimento confirmado
--   - PERC_REP_PREVISTO: % Reprocesso confirmado + previsto sobre o tingimento confirmado
--   - PERC_REP_TOTAL: % Reprocesso total em carteira sobre o tingimento confirmado
-- CUIDADOS OPERACIONAIS:
--   - Execução somente leitura no banco SGTPRD.
--   - Blindagem contra cartesian loops via MATERIALIZE NO_MERGE e isolamento split CTE.
--   - Rastreabilidade multinível reversa de ordens filhas até o 3º nível ancestral (Mãe -> Avó -> Bisavó).
--   - Fallback de peso robusto em 5 níveis com ativação indexada condicional.
-- HISTÓRICO DE OTIMIZAÇÃO:
--   - 19/09/2026: Diagnóstico de varredura global em UNIDADE_PROGRAMACAO.
--   - 23/09/2026: Pushdown temporal em CTE materializada UP_ALVO.
--   - 30/09/2026: Auditoria estrutural e fechamento da query oficial:
--       * Linhagem recursiva multinível Nível 0 -> Nível 1 -> Nível 2 -> Nível 3;
--       * Bloqueio estrito de ambiguidades genealógicas e datas conflitantes em REP_PEND_ENTREGA_MES;
--       * Reconciliação semântica de TING_CONFIRMADO com TIPO_DESTINO = 0 (expurgo de limpezas de máquina);
--       * Detecção determinística de TEM_ANCESTRAL_ACIMA_NIVEL_3 e isolamento de LINHAGEM_EXCEDE_LIMITE;
--       * Fallback robusto de peso (PESO_REPROCESSO -> QT_CRU -> KILOS_PROGRAMADOS -> KILOS_PRODUZIDOS -> 0);
--       * Arquitetura Split CTE com tempo médio de ~5,6s no Oracle SGTPRD.
-- =============================================================================

WITH
CALENDARIO AS (
    SELECT
        TRUNC(B.DATA_REFERENCIA, 'MM') AS DT_INICIO_MES,
        ADD_MONTHS(TRUNC(B.DATA_REFERENCIA, 'MM'), 1) AS DT_INICIO_MES_SEGUINTE,
        TO_NUMBER(TO_CHAR(TRUNC(B.DATA_REFERENCIA, 'MM'), 'YYYYMMDD')) AS DT_EXP_INI,
        TO_NUMBER(TO_CHAR(ADD_MONTHS(TRUNC(B.DATA_REFERENCIA, 'MM'), 1) - 1, 'YYYYMMDD')) AS DT_EXP_FIM
    FROM (
        SELECT
            CASE
                WHEN EXTRACT(DAY FROM SYSDATE) <= 4 THEN ADD_MONTHS(SYSDATE, -1)
                ELSE SYSDATE
            END AS DATA_REFERENCIA
        FROM DUAL
    ) B
),
-- 1. Produção Confirmada no Mês (Isolada, indexada diretamente por DTPRODFIM, sem OR)
PRODUCAO_CONFIRMADA AS (
    SELECT
        ROUND(COALESCE(SUM(CASE WHEN GDX.TIPO_DESTINO = 0 THEN OBF.KILOS_PRODUZIDOS END), 0), 2) AS TING_CONFIRMADO,
        ROUND(COALESCE(SUM(CASE WHEN GDX.TIPO_DESTINO = 1 AND OBF.CODIGO_FASE = 40 AND TRIM(OBF.GRUPO_DEFEITO) IN ('1', '3', '4') THEN OBF.KILOS_PRODUZIDOS END), 0), 2) AS REP_CONFIRMADO
    FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
    JOIN SGTPRD.UP_ORDEM_MVTO UOM 
        ON UOM.NUMEROUP = UPR.NUMEROUP
    JOIN SGTPRD.MAQUINA MAQ 
        ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    JOIN SGTPRD.OB_FASES OBF 
        ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL 
       AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
    LEFT JOIN SGTPRD.DESTINO DEX 
        ON DEX.DESTINO = OBF.DESTINO_RECEITA
    LEFT JOIN SGTPRD.GRUPO_DESTINO GDX 
        ON GDX.CODIGO_GRUPO = DEX.CODIGO_GRUPO
    CROSS JOIN CALENDARIO C
    WHERE UPR.SETOR = 5
      AND UPR.EXCLUIDA = 0
      AND UPR.TIPOUP = 0
      AND MAQ.TIPO_MAQUINA = 17
      AND OBF.STATUS = 4
      AND UPR.DTPRODFIM >= C.DT_INICIO_MES 
      AND UPR.DTPRODFIM < C.DT_INICIO_MES_SEGUINTE
),
-- 2. Reprocessos Pendentes no Parque Fabril com Fallback de Peso Robusto
REPROCESSOS_PENDENTES_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        UOM.NUMEROORDEMREAL AS NUMERO_OB,
        OBF.SEQUENCIA,
        UPR.DTPRODFIM,
        NULLIF(OBF.PESO_REPROCESSO, 0) AS PESO_REPROCESSO,
        NULLIF(OBF.KILOS_PRODUZIDOS, 0) AS KILOS_PRODUZIDOS
    FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
    JOIN SGTPRD.UP_ORDEM_MVTO UOM 
        ON UOM.NUMEROUP = UPR.NUMEROUP
    JOIN SGTPRD.MAQUINA MAQ 
        ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
    JOIN SGTPRD.OB_FASES OBF 
        ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL 
       AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
    LEFT JOIN SGTPRD.DESTINO DEX 
        ON DEX.DESTINO = OBF.DESTINO_RECEITA
    LEFT JOIN SGTPRD.GRUPO_DESTINO GDX 
        ON GDX.CODIGO_GRUPO = DEX.CODIGO_GRUPO
    WHERE UPR.SETOR = 5
      AND UPR.EXCLUIDA = 0
      AND UPR.TIPOUP = 0
      AND MAQ.TIPO_MAQUINA = 17
      AND OBF.STATUS <> 4
      AND GDX.TIPO_DESTINO = 1
      AND OBF.CODIGO_FASE = 40
      AND TRIM(OBF.GRUPO_DEFEITO) IN ('1', '3', '4')
),
-- Subconjunto das ordens que necessitam de fallback de peso (otimização de performance)
OBS_SEM_PESO_REP AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB 
    FROM REPROCESSOS_PENDENTES_RAW 
    WHERE PESO_REPROCESSO IS NULL
),
FALLBACK_QT_CRU AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(O POR GPP) INDEX(POR GERPECOB_INDIPECAORIGEMOB) INDEX(GPP GERPECAS_PKGERAPECASPRODUTO) */
        POR.NUMERO_OB,
        SUM(GPP.QTLIQUIDA) AS QT_CRU
    FROM OBS_SEM_PESO_REP O
    JOIN SGTPRD.GERAPECAORIGEMOB POR ON POR.NUMERO_OB = O.NUMERO_OB
    JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = POR.IDPECASPRODUTO
    GROUP BY POR.NUMERO_OB
),
FALLBACK_KILOS_PROG AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(O OBP) INDEX(OBP OB_PROD_PK_OB_PRODUTO) */
        OBP.NUMERO_OB,
        SUM(OBP.KILOS_PROGRAMADOS) AS KILOS_PROGRAMADOS
    FROM OBS_SEM_PESO_REP O
    JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = O.NUMERO_OB
    GROUP BY OBP.NUMERO_OB
),
REPROCESSOS_PENDENTES AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        RP.NUMERO_OB,
        RP.SEQUENCIA,
        RP.DTPRODFIM,
        COALESCE(
            RP.PESO_REPROCESSO,
            NULLIF(FQC.QT_CRU, 0),
            NULLIF(FKP.KILOS_PROGRAMADOS, 0),
            RP.KILOS_PRODUZIDOS,
            0
        ) AS VALOR_KG
    FROM REPROCESSOS_PENDENTES_RAW RP
    LEFT JOIN FALLBACK_QT_CRU FQC ON FQC.NUMERO_OB = RP.NUMERO_OB
    LEFT JOIN FALLBACK_KILOS_PROG FKP ON FKP.NUMERO_OB = RP.NUMERO_OB
),
TOTAIS_PENDENTES_FABRIL AS (
    SELECT
        ROUND(COALESCE(SUM(CASE WHEN RP.DTPRODFIM >= C.DT_INICIO_MES AND RP.DTPRODFIM < C.DT_INICIO_MES_SEGUINTE THEN RP.VALOR_KG END), 0), 2) AS REP_PREVISTO,
        ROUND(COALESCE(SUM(CASE WHEN RP.DTPRODFIM >= C.DT_INICIO_MES_SEGUINTE THEN RP.VALOR_KG END), 0), 2) AS REP_POSTERIOR
    FROM REPROCESSOS_PENDENTES RP
    CROSS JOIN CALENDARIO C
),
-- 3. Linhagem Genealógica Reversa Multinível para as Ordens Pendentes
OBS_PEND AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB FROM REPROCESSOS_PENDENTES
),
MAES_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OP O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OP.NUMERO_OB AS OB_FILHA,
        O_ORIG.NUMERO_OB AS OB_MAE
    FROM OBS_PEND OP
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OP.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OP.NUMERO_OB
),
MAES_AGRUPADAS AS (
    SELECT
        OB_FILHA,
        COUNT(DISTINCT OB_MAE) AS QTD_MAES,
        MIN(OB_MAE) AS OB_MAE
    FROM MAES_RAW
    GROUP BY OB_FILHA
),
OBS_MAE_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_MAE AS NUMERO_OB
    FROM MAES_AGRUPADAS
    WHERE QTD_MAES = 1
),
AVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OM O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OM.NUMERO_OB AS OB_MAE,
        O_ORIG.NUMERO_OB AS OB_AVO
    FROM OBS_MAE_DISTINCT OM
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OM.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OM.NUMERO_OB
),
AVOS_AGRUPADAS AS (
    SELECT
        OB_MAE,
        COUNT(DISTINCT OB_AVO) AS QTD_AVOS,
        MIN(OB_AVO) AS OB_AVO
    FROM AVOS_RAW
    GROUP BY OB_MAE
),
OBS_AVO_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_AVO AS NUMERO_OB
    FROM AVOS_AGRUPADAS
    WHERE QTD_AVOS = 1
),
BISAVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OA O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OA.NUMERO_OB AS OB_AVO,
        O_ORIG.NUMERO_OB AS OB_BISAVO
    FROM OBS_AVO_DISTINCT OA
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OA.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OA.NUMERO_OB
),
BISAVOS_AGRUPADAS AS (
    SELECT
        OB_AVO,
        COUNT(DISTINCT OB_BISAVO) AS QTD_BISAVOS,
        MIN(OB_BISAVO) AS OB_BISAVO
    FROM BISAVOS_RAW
    GROUP BY OB_AVO
),
OBS_BISAVO_DISTINCT AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT OB_BISAVO AS NUMERO_OB
    FROM BISAVOS_AGRUPADAS
    WHERE QTD_BISAVOS = 1
),
TATARAVOS_RAW AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(OB O_DEST GPO O_ORIG) INDEX(O_DEST GERPECOB_INDIPECAORIGEMOB) INDEX(GPO GERPCORI_PKGERAPECAORIGEM) INDEX(O_ORIG GERPECOB_PKGERAPECAORIGEMOB) */
        OB.NUMERO_OB AS OB_BISAVO,
        O_ORIG.NUMERO_OB AS OB_TATARAVO
    FROM OBS_BISAVO_DISTINCT OB
    JOIN SGTPRD.GERAPECAORIGEMOB O_DEST ON O_DEST.NUMERO_OB = OB.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GPO ON GPO.IDPECASPRODUTO = O_DEST.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAORIGEMOB O_ORIG ON O_ORIG.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM
    WHERE O_ORIG.NUMERO_OB <> OB.NUMERO_OB
),
TATARAVOS_AGRUPADAS AS (
    SELECT
        OB_BISAVO,
        COUNT(DISTINCT OB_TATARAVO) AS QTD_TATARAVOS
    FROM TATARAVOS_RAW
    GROUP BY OB_BISAVO
),
GENEALOGIA AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        OP.NUMERO_OB,
        M.OB_MAE,
        M.QTD_MAES,
        A.OB_AVO,
        A.QTD_AVOS,
        B.OB_BISAVO,
        B.QTD_BISAVOS,
        CASE WHEN T.QTD_TATARAVOS > 0 THEN 1 ELSE 0 END AS TEM_ANCESTRAL_ACIMA_NIVEL_3,
        CASE
            WHEN M.OB_MAE IS NULL THEN 0
            WHEN A.OB_AVO IS NULL THEN 1
            WHEN B.OB_BISAVO IS NULL THEN 2
            ELSE 3
        END AS NIVEL_LINHAGEM,
        CASE
            WHEN T.QTD_TATARAVOS > 0 THEN NULL
            ELSE COALESCE(B.OB_BISAVO, A.OB_AVO, M.OB_MAE, OP.NUMERO_OB)
        END AS OB_RAIZ,
        OP.NUMERO_OB || 
            CASE WHEN M.OB_MAE IS NOT NULL THEN ' -> ' || M.OB_MAE END ||
            CASE WHEN A.OB_AVO IS NOT NULL THEN ' -> ' || A.OB_AVO END ||
            CASE WHEN B.OB_BISAVO IS NOT NULL THEN ' -> ' || B.OB_BISAVO END ||
            CASE WHEN T.QTD_TATARAVOS > 0 THEN ' -> [...]' END AS CAMINHO_LINHAGEM,
        CASE
            WHEN T.QTD_TATARAVOS > 0 THEN 'LINHAGEM_EXCEDE_LIMITE'
            WHEN M.QTD_MAES > 1 OR A.QTD_AVOS > 1 OR B.QTD_BISAVOS > 1 THEN 'AMBIGUA'
            WHEN M.OB_MAE IS NULL THEN 'RAIZ'
            ELSE 'RESOLVIDA'
        END AS STATUS_LINHAGEM
    FROM OBS_PEND OP
    LEFT JOIN MAES_AGRUPADAS M ON M.OB_FILHA = OP.NUMERO_OB
    LEFT JOIN AVOS_AGRUPADAS A ON A.OB_MAE = M.OB_MAE AND M.QTD_MAES = 1
    LEFT JOIN BISAVOS_AGRUPADAS B ON B.OB_AVO = A.OB_AVO AND A.QTD_AVOS = 1
    LEFT JOIN TATARAVOS_AGRUPADAS T ON T.OB_BISAVO = B.OB_BISAVO AND B.QTD_BISAVOS = 1
),
UNIVERSO_GENEALOGIA AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ NUMERO_OB FROM OBS_PEND
    UNION ALL
    SELECT OB_MAE FROM MAES_RAW
    UNION ALL
    SELECT OB_AVO FROM AVOS_RAW
    UNION ALL
    SELECT OB_BISAVO FROM BISAVOS_RAW
),
DISTINCT_UNIVERSO AS (
    SELECT /*+ MATERIALIZE NO_MERGE */ DISTINCT NUMERO_OB FROM UNIVERSO_GENEALOGIA
),
COMERCIAL_POR_OB AS (
    SELECT /*+ MATERIALIZE NO_MERGE LEADING(DU P OFO OFP IPQ) INDEX(P PPRODUOB_IND_OB_NUMERO) */
        DU.NUMERO_OB,
        MIN(OFO.NUMEROOF) AS NUMEROOF,
        MIN(IPQ.EXPEDIREM) AS DT_ENTREGA,
        MAX(IPQ.EXPEDIREM) AS DT_ENTREGA_MAX,
        COUNT(DISTINCT IPQ.EXPEDIREM) AS QTD_DATAS_ENTREGA
    FROM DISTINCT_UNIVERSO DU
    JOIN SGTPRD.PEDPRODUCAOOB P ON P.NUMEROOB = DU.NUMERO_OB
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = P.NUMERO
    LEFT JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF
    LEFT JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    GROUP BY DU.NUMERO_OB
),
RESOLUCAO_COMERCIAL AS (
    SELECT /*+ MATERIALIZE NO_MERGE */
        G.NUMERO_OB,
        G.STATUS_LINHAGEM,
        COALESCE(CD.DT_ENTREGA, CM.DT_ENTREGA, CA.DT_ENTREGA, CB.DT_ENTREGA) AS DT_ENTREGA_RESOLVIDA,
        CASE
            WHEN G.STATUS_LINHAGEM IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE') THEN 0
            WHEN CD.DT_ENTREGA IS NOT NULL AND CD.DT_ENTREGA <> CD.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NOT NULL AND CM.DT_ENTREGA <> CM.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NULL AND CA.DT_ENTREGA IS NOT NULL AND CA.DT_ENTREGA <> CA.DT_ENTREGA_MAX THEN 1
            WHEN CD.DT_ENTREGA IS NULL AND CM.DT_ENTREGA IS NULL AND CA.DT_ENTREGA IS NULL AND CB.DT_ENTREGA IS NOT NULL AND CB.DT_ENTREGA <> CB.DT_ENTREGA_MAX THEN 1
            ELSE 0
        END AS DT_ENTREGA_AMBIGUA
    FROM GENEALOGIA G
    LEFT JOIN COMERCIAL_POR_OB CD ON CD.NUMERO_OB = G.NUMERO_OB
    LEFT JOIN COMERCIAL_POR_OB CM ON CM.NUMERO_OB = G.OB_MAE
    LEFT JOIN COMERCIAL_POR_OB CA ON CA.NUMERO_OB = G.OB_AVO
    LEFT JOIN COMERCIAL_POR_OB CB ON CB.NUMERO_OB = G.OB_BISAVO
),
REP_PEND_ENTREGA_CALC AS (
    SELECT
        ROUND(COALESCE(SUM(CASE 
            WHEN RC.STATUS_LINHAGEM NOT IN ('AMBIGUA', 'LINHAGEM_EXCEDE_LIMITE')
             AND RC.DT_ENTREGA_AMBIGUA = 0
             AND RC.DT_ENTREGA_RESOLVIDA BETWEEN C.DT_EXP_INI AND C.DT_EXP_FIM 
            THEN RP.VALOR_KG 
        END), 0), 2) AS REP_PEND_ENTREGA_MES
    FROM REPROCESSOS_PENDENTES RP
    JOIN RESOLUCAO_COMERCIAL RC ON RC.NUMERO_OB = RP.NUMERO_OB
    CROSS JOIN CALENDARIO C
)
SELECT
    PC.TING_CONFIRMADO,
    PC.REP_CONFIRMADO,
    TP.REP_PREVISTO,
    TP.REP_POSTERIOR,
    PE.REP_PEND_ENTREGA_MES,
    ROUND(PC.REP_CONFIRMADO * 100.0 / NULLIF(PC.TING_CONFIRMADO, 0), 3) AS PERC_REP_CONFIRMADO,
    ROUND((PC.REP_CONFIRMADO + TP.REP_PREVISTO) * 100.0 / NULLIF(PC.TING_CONFIRMADO, 0), 3) AS PERC_REP_PREVISTO,
    ROUND((PC.REP_CONFIRMADO + TP.REP_PREVISTO + TP.REP_POSTERIOR) * 100.0 / NULLIF(PC.TING_CONFIRMADO, 0), 3) AS PERC_REP_TOTAL
FROM PRODUCAO_CONFIRMADA PC
CROSS JOIN TOTAIS_PENDENTES_FABRIL TP
CROSS JOIN REP_PEND_ENTREGA_CALC PE