/* =============================================================================
OBJETIVO: Monitoramento completo de nota fiscal de entrada na produção, qualidade e expedição
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: SQL Reference\templates\monitoramento_nf_entrada_producao.sql
TIPO: SELECT (Template Analítico / Operacional)
PARÂMETROS / BINDS: :NF_ENTRADA, :FILIAL
TABELAS PRINCIPAIS: SGTPRD.OB, SGTPRD.GERAPECASPRODUTO, SGTPRD.GERAPECADESTINOOB, SGTPRD.BD_BNF_PRODUCAO_FASE
CUIDADOS OPERACIONAIS: Template somente leitura; não executar DML nem alterar as constantes sem revisão.
REVISÃO (24/09/2026): OBs da NF materializadas uma vez (OBS_NF), máquina atual em CTE própria e CTEs de fase/defeito materializadas. Consulta completa de ~7,8 s (cancelada por ORA-00028) para ~1,0 s na NF 35919/filial 1, com equivalência total nas 590 linhas (Tools/comparar_equivalencia.py, chave peça+OB).
============================================================================= */
-- ====================================================================================
-- SGT - MONITORAMENTO COMPLETO DE NOTA FISCAL DE ENTRADA NA PRODUCAO E EXPEDICAO
-- ====================================================================================
-- Descricao:
--   Rastreamento ponta a ponta de ciclo de vida de malha crua (NF de Entrada):
--   1. Entrada e pesagem das pecas cruas (Dep. 95 -> Dep. 100), incluindo BOX de entrada e atual.
--   2. Rastreamento e auditoria completa de movimentos de estoque (Entrada, Transf. Deposito,
--      Consumo na OB, Baixa por Requisicao Avulsa, Saida por Nao Conformidade, Faturamento).
--   3. Apontamento de chao de fabrica: Fases, Maquinas e Calculo Exato de Dias Parados (Aging)
--      em cada etapa por conversao de tempo serial nativa (epoch Oracle do SGT).
--   4. QUALIDADE INDUSTRIAL E DEFEITOS NO NIVEL DA OB:
--      - No modelo fabril da empresa, pecas individuais (cruas ou acabadas) nao
--        possuem apontamentos de defeito isolados na tabela de revisao (REV.TIPO_DEFEITO = NULL).
--      - Os defeitos reais, nao conformidades (NC) e indicacoes de destino residem na
--        propria Ordem de Beneficiamento (SGTPRD.OB_QUALIDADE e SGTPRD.OB).
--      - Os defeitos sao aqui consolidados e tratados por OB (Devolucao Lojas, Largura,
--        Manchado, etc.) com seus respectivos destinos de NC (Liberar por ACPNC, Reprocessar),
--        usos alternativos ("VENDA LD") e fases de apontamento (CDC, RAU).
--   5. Classificacao Comercial Rigorosa:
--      - NORMAL: 1a Qualidade sem defeito na OB -> Pedido Normal / Matriz / Romaneio de Saida.
--      - LD (Leves Defeitos): OBs liberadas por ACPNC com uso alternativo VENDA LD ->
--        faturadas em pedido comercial separado (ex: Pedido 17202 / Cliente LD MALHAS).
--      - RETALHO: Pecas acabadas baixadas para venda como retalho no Deposito 110.
--      - REPROCESSO: OBs com NC de acabamento direcionadas para reprocessamento em maquina.
--   6. Balanco de Massa Industrial: Rendimento (%) e Perda/Quebra (kg) por OB com datas de abertura/conclusao.
--   7. Enderecamento Fisico e Expedicao Fiscal Completa:
--      - BOX e Rua fisica das pecas nos depositos (Dep. 95, Dep. 100 e Dep. 110).
--      - Romaneio de Saida, Status de Faturamento, Nota Fiscal de Saida (NFe), Serie e Chave NFe.
--      - CFOP, Natureza da Operacao Fiscal, Transportadora, Data/Hora de Saida Fisica, Placa e Valores (Unitario/Total).
--      - Alertas de Historico de Movimentacao: Baixas por Refugo/NC, Divisoes de Ordem e Requisicoes Avulsas.
--
-- Parametros de Execucao:
--   :NF_ENTRADA -> Numero da Nota Fiscal de Entrada (ex: 35919)
--   :FILIAL     -> Codigo da Empresa/Fornecedor (ex: 1)
-- ====================================================================================


-- ====================================================================================
-- VISAO 1: RASTREAMENTO INDIVIDUAL DAS PECAS CRUAS DE ENTRADA (590 PECAS DA NF)
-- ====================================================================================
-- Mostra a situacao individual de cada rolo de malha crua que entrou pela NF,
-- enderecamento em BOX (entrada e atual), para qual OB foi direcionado, o status
-- de consumo, ultimo movimento de estoque (tratado para consumo, requisicao ou refugo),
-- os defeitos consolidados da OB, a fase atual e a destinacao final da peca.
-- ====================================================================================
WITH NF_CRU AS (
    SELECT /*+ MATERIALIZE */
        GNE.IDPECASPRODUTO AS ID_PECA_CRU,
        GNE.NUMERO_NOTA,
        GNE.SERIE_NOTA,
        GNE.CODINSREDUZIDO AS COD_INSUMO_CRU,
        TRIM(ITE_CRU.DESCRICAO) AS DESCR_INSUMO_CRU,
        GNE.LOTE AS LOTE_ENTRADA,
        GP_CRU.QTLIQUIDA AS PESO_CRU_KG,
        GP_CRU.CODIGO_DEPOSITO AS DEPOSITO_CRU,
        TRIM(DEP_CRU.DESCRICAO) AS DESCR_DEPOSITO_CRU,
        TRIM(GNE.BOX_ENTRADA) AS BOX_ENTRADA_NF,
        TRIM(GP_CRU.NUMERO_BOX) AS BOX_ATUAL_CRU,
        GP_CRU.STPECAPRODUTO AS COD_ST_PECA_CRU,
        TRIM(ESP_CRU.DESCRIPTION) AS STATUS_PECA_CRU,
        GP_CRU.TISITUACAOESTOQUE AS COD_SIT_ESTOQUE_CRU,
        CASE GP_CRU.TISITUACAOESTOQUE
            WHEN 0 THEN 'Disponivel em Estoque'
            WHEN 1 THEN 'Em Processo na OB (Indisponivel)'
            WHEN 2 THEN 'Baixada / Consumida na OB'
            ELSE 'Outro (' || GP_CRU.TISITUACAOESTOQUE || ')'
        END AS SITUACAO_ESTOQUE_CRU,
        GOB.NUMERO_OB
    FROM SGTPRD.GERAPECANOTAENTRADA GNE
    JOIN SGTPRD.GERAPECASPRODUTO GP_CRU ON GP_CRU.IDPECASPRODUTO = GNE.IDPECASPRODUTO
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE_CRU ON ITE_CRU.CODIGO_REDUZIDO = GNE.CODINSREDUZIDO
    LEFT JOIN SGTPRD.DEPOSITO DEP_CRU ON DEP_CRU.CODIGO_DEPOSITO = GP_CRU.CODIGO_DEPOSITO
    LEFT JOIN SGTPRD.XX2_ENUMITEM ESP_CRU ON ESP_CRU.IDENUMERATE = 605 AND ESP_CRU.SEQUENCE = GP_CRU.STPECAPRODUTO
    LEFT JOIN SGTPRD.GERAPECAORIGEMOB GOB ON GOB.IDPECASPRODUTO = GNE.IDPECASPRODUTO
    WHERE GNE.NUMERO_NOTA = :NF_ENTRADA
      AND GNE.IDPESSOAFJ = :FILIAL
),
OBS_NF AS (
    -- OBs da NF calculadas uma vez (antes: SELECT DISTINCT repetido em 8 CTEs).
    SELECT /*+ MATERIALIZE */ DISTINCT NUMERO_OB FROM NF_CRU WHERE NUMERO_OB IS NOT NULL
),
ULTIMO_MOV_PECA AS (
    SELECT /*+ MATERIALIZE */
        GPM.IDPECASPRODUTO,
        MOV.NRTIPOMOVIMENTO,
        TRIM(TMO.DESCRICAO) AS DESCR_TIPO_MOVIMENTO,
        DECODE(MOV.TIOPERACAO, 1, 'ENTRADA', 2, 'SAIDA', 'OUTRO') AS TIPO_OPERACAO,
        MOV.DTDOCUMENTO AS DATA_HORA_MOV,
        ROW_NUMBER() OVER (PARTITION BY GPM.IDPECASPRODUTO ORDER BY MOV.ID DESC) AS RN
    FROM SGTPRD.GERAPECAMOVIMENTO GPM
    JOIN SGTPRD.GERAMOVIMENTOESTOQUE MOV ON MOV.ID = GPM.NUMERO_MOVIMENTO
    LEFT JOIN SGTPRD.TIPO_MOVIMENTO TMO ON TMO.NUM_TIPO_MOVIMENTO = MOV.NRTIPOMOVIMENTO
    WHERE GPM.IDPECASPRODUTO IN (SELECT ID_PECA_CRU FROM NF_CRU)
),
HISTORICO_ALERTAS_PECA AS (
    SELECT
        GPM.IDPECASPRODUTO,
        MAX(CASE WHEN MOV.NRTIPOMOVIMENTO = 82 THEN 'SIM' ELSE 'NAO' END) AS TEVE_BAIXA_NC,
        MAX(CASE WHEN MOV.NRTIPOMOVIMENTO IN (743, 744) THEN 'SIM' ELSE 'NAO' END) AS TEVE_DIVISAO_ORDEM,
        MAX(CASE WHEN MOV.NRTIPOMOVIMENTO = 20 THEN 'SIM' ELSE 'NAO' END) AS TEVE_REQUISICAO_AVULSA
    FROM SGTPRD.GERAPECAMOVIMENTO GPM
    JOIN SGTPRD.GERAMOVIMENTOESTOQUE MOV ON MOV.ID = GPM.NUMERO_MOVIMENTO
    WHERE GPM.IDPECASPRODUTO IN (SELECT ID_PECA_CRU FROM NF_CRU)
    GROUP BY GPM.IDPECASPRODUTO
),
OB_DEFEITOS_BASE AS (
    SELECT DISTINCT
        OBQ.NUMERO_OB,
        TRIM(GD.DESCRICAO_GRUPO) AS DESCR_GRUPO,
        TRIM(TD.DESCRICAO_TIPO) AS DESCR_DEFEITO,
        TRIM(DEST.DESCRIPTION) AS DESCR_DESTINO,
        TRIM(OBQ.USO_ALTERNATIVO) AS USO_ALTERNATIVO,
        TRIM(FF.DESCRICAO_FASE) AS FASE_APONTAMENTO,
        TRIM(OBQ.USUARIO_OBNAOCONFORM) AS USUARIO_NC
    FROM SGTPRD.OB_QUALIDADE OBQ
    LEFT JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = OBQ.NUMERO_OB AND OBF.SEQUENCIA = OBQ.SEQUENCIA_FASE
    LEFT JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = OBF.CODIGO_FASE
    LEFT JOIN SGTPRD.GRUPO_DEFEITO_QUALID GD ON GD.CODIGO_GRUPO = OBQ.GRUPO_DEFEITO
    LEFT JOIN SGTPRD.TIPO_DEFEITO_QUALIDA TD ON TD.CODIGO_GRUPO = OBQ.GRUPO_DEFEITO AND TD.CODIGO_TIPO = OBQ.TIPO_DEFEITO
    LEFT JOIN SGTPRD.XX2_ENUMITEM DEST ON DEST.IDENUMERATE = 1 AND DEST.SEQUENCE = OBQ.DESTINO
    WHERE OBQ.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
),
OB_DEFEITOS_CONSOL AS (
    SELECT /*+ MATERIALIZE */
        B.NUMERO_OB,
        LISTAGG(B.DESCR_DEFEITO, ' | ') WITHIN GROUP (ORDER BY B.DESCR_DEFEITO) AS DEFEITOS_OB,
        LISTAGG(B.DESCR_GRUPO, ' | ') WITHIN GROUP (ORDER BY B.DESCR_GRUPO) AS GRUPOS_DEFEITO_OB,
        LISTAGG(B.DESCR_DESTINO, ' | ') WITHIN GROUP (ORDER BY B.DESCR_DESTINO) AS DESTINOS_NC_OB,
        LISTAGG(NVL(B.USO_ALTERNATIVO, '-'), ' | ') WITHIN GROUP (ORDER BY B.USO_ALTERNATIVO) AS USOS_ALTERNATIVOS_OB,
        LISTAGG(NVL(B.FASE_APONTAMENTO, '-'), ' | ') WITHIN GROUP (ORDER BY B.FASE_APONTAMENTO) AS FASES_DEFEITO_OB,
        MAX(NVL(B.USUARIO_NC, '-')) AS USUARIOS_NC_OB
    FROM OB_DEFEITOS_BASE B
    GROUP BY B.NUMERO_OB
),
OB_DEFEITOS_SOMA AS (
    SELECT /*+ MATERIALIZE */
        OBQ.NUMERO_OB,
        COUNT(*) AS TOTAL_OCORRENCIAS_NC,
        ROUND(SUM(OBQ.QUANTIDADE_REJEITADA), 2) AS TOTAL_KG_REJEITADO
    FROM SGTPRD.OB_QUALIDADE OBQ
    WHERE OBQ.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
    GROUP BY OBQ.NUMERO_OB
),
FASE_ATUAL_CTE AS (
    SELECT /*+ MATERIALIZE */
        OBF.NUMERO_OB,
        MIN(OBF.SEQUENCIA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS SEQUENCIA,
        MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS STATUS,
        MIN(OBF.CODIGO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS CODIGO_FASE
    FROM SGTPRD.OB_FASES OBF
    WHERE OBF.STATUS <> 4
      AND OBF.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
    GROUP BY OBF.NUMERO_OB
),
FASE_ANTERIOR_CONF AS (
    SELECT /*+ MATERIALIZE */ 
        OBF.NUMERO_OB,
        OBF.SEQUENCIA AS SEQ_ATUAL,
        MAX(OBF_ANT.TEMPO_FINAL_CONFIRMA) AS TEMPO_FIM_FASE_ANT
    FROM SGTPRD.OB_FASES OBF
    LEFT JOIN SGTPRD.OB_FASES OBF_ANT 
        ON OBF_ANT.NUMERO_OB = OBF.NUMERO_OB 
       AND OBF_ANT.SEQUENCIA < OBF.SEQUENCIA 
       AND OBF_ANT.STATUS = 4 
       AND OBF_ANT.TEMPO_FINAL_CONFIRMA > 0
    WHERE OBF.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
    GROUP BY OBF.NUMERO_OB, OBF.SEQUENCIA
),
MAQ_ATUAL_OB AS (
    -- Era uma subconsulta em linha no OB_INFO; como CTE materializada deixa de
    -- ser fundida no plano do OB_INFO (parte do ganho de 6,5 s -> 0,6 s).
    SELECT /*+ MATERIALIZE */ UOM.NUMEROORDEMREAL, MAX(MAQ_INNER.NOME_MAQUINA) AS NOME_MAQUINA
    FROM SGTPRD.UP_ORDEM_MVTO UOM
    JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP = UOM.NUMEROUP
    LEFT JOIN SGTPRD.MAQUINA MAQ_INNER ON MAQ_INNER.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA AND MAQ_INNER.SETOR = UPR.SETOR
    WHERE UPR.STATUS = 3
      AND UOM.NUMEROORDEMREAL IN (SELECT NUMERO_OB FROM OBS_NF)
    GROUP BY UOM.NUMEROORDEMREAL
),
OB_INFO AS (
    SELECT /*+ MATERIALIZE */
        O.NUMERO_OB,
        O.STATUS AS COD_STATUS_OB,
        TRIM(ST_OB.DESCRIPTION) AS STATUS_OB,
        TRIM(SCQ.DESCRIPTION) AS STATUS_CQ,
        TRIM(SNC.DESCRIPTION) AS STATUS_NC,
        TRIM(SCQD.DESCRIPTION) AS STATUS_CQ_DEP,
        O.DTEMISSAORDEM,
        O.DTENCERORDEM,
        O.CODIGO_REDUZIDO AS COD_PRODUTO_ACABADO,
        TRIM(ITE_ACAB.DESCRICAO) AS DESCR_PRODUTO_ACABADO,
        OBF.CODIGO_FASE,
        TRIM(FFL.DESCRICAO_FASE) AS FASE_ATUAL,
        TRIM(ENS.DESCRIPTION) AS STATUS_FASE_ATUAL,
        TRIM(MAQ.NOME_MAQUINA) AS MAQUINA_ATUAL,
        -- Data real de movimentacao para a fase atual (inicio em maquina ou conclusao da fase anterior)
        CASE 
            WHEN O.STATUS = 0 THEN O.DTENCERORDEM
            WHEN OBF.TEMPO_INICIAL_CONFIR > 0 
            THEN DATE '1996-01-01' + (OBF.TEMPO_INICIAL_CONFIR / 1440)
            WHEN NVL(FA.TEMPO_FIM_FASE_ANT, 0) > 0 
            THEN DATE '1996-01-01' + (FA.TEMPO_FIM_FASE_ANT / 1440)
            ELSE O.DTEMISSAORDEM
        END AS DATA_HORA_MOVTO_FASE,
        CASE
            WHEN O.STATUS = 0 THEN 'Ordem Concluida'
            WHEN OBF.TEMPO_INICIAL_CONFIR > 0 THEN 'Inicio Confirmado da Fase Atual'
            WHEN NVL(FA.TEMPO_FIM_FASE_ANT, 0) > 0 THEN 'Conclusao da Fase Anterior (Chegada na Fila)'
            ELSE 'Emissao da Ordem (1a Fase)'
        END AS ORIGEM_MOVTO_FASE,
        CASE 
            WHEN O.STATUS = 0 THEN 0
            ELSE ROUND(SYSDATE - (
                CASE 
                    WHEN OBF.TEMPO_INICIAL_CONFIR > 0 
                    THEN DATE '1996-01-01' + (OBF.TEMPO_INICIAL_CONFIR / 1440)
                    WHEN NVL(FA.TEMPO_FIM_FASE_ANT, 0) > 0 
                    THEN DATE '1996-01-01' + (FA.TEMPO_FIM_FASE_ANT / 1440)
                    ELSE O.DTEMISSAORDEM
                END
            ), 1)
        END AS DIAS_PARADO_NA_FASE,
        CASE 
            WHEN O.STATUS = 0 THEN 0
            ELSE ROUND((SYSDATE - (
                CASE 
                    WHEN OBF.TEMPO_INICIAL_CONFIR > 0 
                    THEN DATE '1996-01-01' + (OBF.TEMPO_INICIAL_CONFIR / 1440)
                    WHEN NVL(FA.TEMPO_FIM_FASE_ANT, 0) > 0 
                    THEN DATE '1996-01-01' + (FA.TEMPO_FIM_FASE_ANT / 1440)
                    ELSE O.DTEMISSAORDEM
                END
            )) * 24, 1)
        END AS HORAS_PARADO_NA_FASE,
        NVL(ODS.TOTAL_OCORRENCIAS_NC, 0) AS QTD_NC_OB,
        NVL(ODS.TOTAL_KG_REJEITADO, 0) AS KG_REJEITADO_NC_OB,
        NVL(ODC.DEFEITOS_OB, 'SEM DEFEITO APONTADO') AS DEFEITOS_OB,
        NVL(ODC.GRUPOS_DEFEITO_OB, '-') AS GRUPOS_DEFEITO_OB,
        NVL(ODC.DESTINOS_NC_OB, '-') AS DESTINOS_NC_OB,
        NVL(ODC.USOS_ALTERNATIVOS_OB, '-') AS USOS_ALTERNATIVOS_OB,
        NVL(ODC.FASES_DEFEITO_OB, '-') AS FASES_DEFEITO_OB,
        NVL(ODC.USUARIOS_NC_OB, '-') AS USUARIOS_NC_OB,
        CASE
            WHEN ODC.DEFEITOS_OB IS NOT NULL AND (ODC.USOS_ALTERNATIVOS_OB LIKE '%LD%' OR ODC.DESTINOS_NC_OB LIKE '%ACPNC%') THEN 'LD (Leves Defeitos - Venda Alternativa)'
            WHEN ODC.DEFEITOS_OB IS NOT NULL AND ODC.DESTINOS_NC_OB LIKE '%Reprocessar%' AND O.STATUS = 0 THEN '1a Qualidade (Reprocesso Concluido / Recuperado)'
            WHEN ODC.DEFEITOS_OB IS NOT NULL AND ODC.DESTINOS_NC_OB LIKE '%Reprocessar%' THEN 'Reprocesso por Nao Conformidade (Em Andamento)'
            WHEN O.STATUS = 0 AND NVL(ODS.TOTAL_OCORRENCIAS_NC, 0) = 0 THEN '1a Qualidade (Normal Conforme)'
            ELSE 'Em Processo / Regular'
        END AS CLASSIFICACAO_QUALIDADE_OB
    FROM SGTPRD.OB O
    LEFT JOIN SGTPRD.XX2_ENUMITEM ST_OB ON ST_OB.IDENUMERATE = 479 AND ST_OB.SEQUENCE = O.STATUS
    LEFT JOIN SGTPRD.XX2_ENUMITEM SCQ ON SCQ.IDENUMERATE = 503 AND SCQ.SEQUENCE = O.STATUS_CQ
    LEFT JOIN SGTPRD.XX2_ENUMITEM SNC ON SNC.IDENUMERATE = 504 AND SNC.SEQUENCE = O.STATUS_NC
    LEFT JOIN SGTPRD.XX2_ENUMITEM SCQD ON SCQD.IDENUMERATE = 160 AND SCQD.SEQUENCE = O.STATUS_CQ_DEP
    LEFT JOIN FASE_ATUAL_CTE FAS ON FAS.NUMERO_OB = O.NUMERO_OB
    LEFT JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = O.NUMERO_OB AND OBF.SEQUENCIA = FAS.SEQUENCIA
    LEFT JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    LEFT JOIN SGTPRD.XX2_ENUMITEM ENS ON ENS.IDENUMERATE = 478 AND ENS.SEQUENCE = OBF.STATUS
    LEFT JOIN FASE_ANTERIOR_CONF FA ON FA.NUMERO_OB = O.NUMERO_OB AND FA.SEQ_ATUAL = FAS.SEQUENCIA
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE_ACAB ON ITE_ACAB.CODIGO_REDUZIDO = O.CODIGO_REDUZIDO
    LEFT JOIN OB_DEFEITOS_CONSOL ODC ON ODC.NUMERO_OB = O.NUMERO_OB
    LEFT JOIN OB_DEFEITOS_SOMA ODS ON ODS.NUMERO_OB = O.NUMERO_OB
    LEFT JOIN MAQ_ATUAL_OB MAQ ON MAQ.NUMEROORDEMREAL = O.NUMERO_OB
    WHERE O.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
),
MOV_RETALHO_OB AS (
    -- Sem MATERIALIZE de propósito: materializada, esta CTE dispara ORA-00979
    -- no Oracle 12c ao ser consumida pelo GROUP BY de DESTINO_RESUMO_OB.
    SELECT
        GDO.NUMERO_OB,
        MAX(CASE WHEN MOV.NRTIPOMOVIMENTO = 670 THEN 'SIM' ELSE 'NAO' END) AS TEVE_BAIXA_RETALHO,
        COUNT(DISTINCT CASE WHEN MOV.NRTIPOMOVIMENTO = 670 THEN GDO.IDPECASPRODUTO END) AS QTD_PECAS_RETALHO,
        ROUND(SUM(CASE WHEN MOV.NRTIPOMOVIMENTO = 670 THEN GP.QTLIQUIDA ELSE 0 END), 2) AS PESO_RETALHO_KG,
        MAX(CASE WHEN MOV.NRTIPOMOVIMENTO = 670 THEN MOV.DTDOCUMENTO END) AS DATA_BAIXA_RETALHO
    FROM SGTPRD.GERAPECADESTINOOB GDO
    JOIN SGTPRD.GERAPECASPRODUTO GP ON GP.IDPECASPRODUTO = GDO.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECAMOVIMENTO GPM ON GPM.IDPECASPRODUTO = GDO.IDPECASPRODUTO
    JOIN SGTPRD.GERAMOVIMENTOESTOQUE MOV ON MOV.ID = GPM.NUMERO_MOVIMENTO
    WHERE GDO.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
      AND MOV.NRTIPOMOVIMENTO = 670
    GROUP BY GDO.NUMERO_OB
),
DESTINO_RESUMO_OB AS (
    SELECT /*+ MATERIALIZE */
        GDO.NUMERO_OB,
        COUNT(DISTINCT GP.IDPECASPRODUTO) AS TOTAL_PECAS_ACABADAS,
        ROUND(SUM(GP.QTLIQUIDA), 2) AS PESO_TOTAL_ACABADO,
        MAX(NVL(MRO.TEVE_BAIXA_RETALHO, 'NAO')) AS TEVE_BAIXA_RETALHO,
        MAX(MRO.DATA_BAIXA_RETALHO) AS DATA_BAIXA_RETALHO,
        NVL(MAX(MRO.QTD_PECAS_RETALHO), 0) AS QTD_PECAS_RETALHO,
        NVL(MAX(MRO.PESO_RETALHO_KG), 0) AS PESO_RETALHO_KG,
        MAX(CASE
            WHEN PC.IDFILIALCOBRANCA = 32411
                 OR PC.QUALIDADE_COMERCIAL = 1
                 OR GP.PADRAO_QUALIDADE_SIN = 2
            THEN 'SIM' ELSE 'NAO'
        END) AS TEVE_DESTINO_LD,
        MAX(CASE
            WHEN PC.IDFILIALCOBRANCA = 32411 OR PC.QUALIDADE_COMERCIAL = 1
            THEN PC.PEDIDO
        END) AS PEDIDO_LD,
        MAX(CASE
            WHEN PC.IDFILIALCOBRANCA = 32411 OR PC.QUALIDADE_COMERCIAL = 1
            THEN TRIM(PF.NOMEFANTASIA)
        END) AS CLIENTE_LD,
        MAX(CASE
            WHEN PC.IDFILIALCOBRANCA <> 32411 AND (PC.QUALIDADE_COMERCIAL <> 1 OR PC.QUALIDADE_COMERCIAL IS NULL) AND PC.PEDIDO IS NOT NULL
            THEN PC.PEDIDO
        END) AS PEDIDO_NORMAL,
        MAX(CASE
            WHEN PC.IDFILIALCOBRANCA <> 32411 AND (PC.QUALIDADE_COMERCIAL <> 1 OR PC.QUALIDADE_COMERCIAL IS NULL) AND PC.PEDIDO IS NOT NULL
            THEN TRIM(PF.NOMEFANTASIA)
        END) AS CLIENTE_NORMAL,
        MAX(PRS.NUMERO_ROMANEIO_SAID) AS ULTIMO_ROMANEIO
    FROM SGTPRD.GERAPECADESTINOOB GDO
    JOIN SGTPRD.GERAPECASPRODUTO GP ON GP.IDPECASPRODUTO = GDO.IDPECASPRODUTO
    LEFT JOIN MOV_RETALHO_OB MRO ON MRO.NUMERO_OB = GDO.NUMERO_OB
    LEFT JOIN SGTPRD.PECAS_ROMANEIO_SAIDA PRS ON PRS.IDPECASPRODUTO = GP.IDPECASPRODUTO
    LEFT JOIN SGTPRD.GERAPECAPEDCOMERCIAL GPC ON GPC.IDPECASPRODUTO = GP.IDPECASPRODUTO
    LEFT JOIN SGTPRD.PEDIDOCOMERCIAL PC ON PC.PEDIDO = NVL(PRS.NUMERO_PEDIDO_COMERC, GPC.NUMERO_PEDIDO_COMERC)
    LEFT JOIN SGTPRD.PESSOASFJ PF ON PF.IDPESSOAFJ = PC.IDFILIALCOBRANCA
    WHERE GDO.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_NF)
    GROUP BY GDO.NUMERO_OB
)
SELECT
    N.NUMERO_NOTA,
    N.ID_PECA_CRU,
    N.COD_INSUMO_CRU,
    N.DESCR_INSUMO_CRU,
    N.LOTE_ENTRADA,
    N.PESO_CRU_KG,
    N.DEPOSITO_CRU,
    N.DESCR_DEPOSITO_CRU,
    NVL(N.BOX_ENTRADA_NF, 'GERAL') AS BOX_ENTRADA_NF,
    NVL(N.BOX_ATUAL_CRU, 'SEM BOX DEFINIDO') AS BOX_ATUAL_CRU,
    NVL(TRIM(BX_CRU.LOCALIZACAO), '-') AS RUA_BOX_CRU,
    NVL(TRIM(BX_CRU.DESCRICAO), '-') AS DESCR_BOX_CRU,
    N.SITUACAO_ESTOQUE_CRU,
    N.STATUS_PECA_CRU,
    N.NUMERO_OB,
    O.STATUS_OB,
    O.COD_PRODUTO_ACABADO,
    O.DESCR_PRODUTO_ACABADO,
    CASE
        WHEN O.STATUS_OB = 'Encerrada' THEN 'PRODUCAO CONCLUIDA'
        ELSE O.FASE_ATUAL || ' (' || O.STATUS_FASE_ATUAL || ')'
    END AS ETAPA_PRODUCAO,
    O.MAQUINA_ATUAL,
    O.STATUS_CQ_DEP AS STATUS_CQ_OB,
    O.CLASSIFICACAO_QUALIDADE_OB,
    O.DEFEITOS_OB,
    O.GRUPOS_DEFEITO_OB,
    O.DESTINOS_NC_OB,
    O.USOS_ALTERNATIVOS_OB,
    O.FASES_DEFEITO_OB,
    O.USUARIOS_NC_OB AS INSPETOR_QUALIDADE_NC,
    -- Contabilizacao exata pela movimentacao da fase da OB
    O.DATA_HORA_MOVTO_FASE,
    O.ORIGEM_MOVTO_FASE,
    O.DIAS_PARADO_NA_FASE,
    O.HORAS_PARADO_NA_FASE,
    -- Rastreabilidade de Movimento de Baixa e Alertas Historicos
    UM.NRTIPOMOVIMENTO AS COD_ULT_MOVTO_ESTOQUE,
    UM.DESCR_TIPO_MOVIMENTO AS DESCR_ULT_MOVTO_ESTOQUE,
    UM.DATA_HORA_MOV AS DATA_ULT_MOVTO_ESTOQUE,
    NVL(HAP.TEVE_BAIXA_NC, 'NAO') AS HISTORICO_BAIXA_NC,
    NVL(HAP.TEVE_DIVISAO_ORDEM, 'NAO') AS HISTORICO_DIVISAO_ORDEM,
    NVL(DRO.TEVE_BAIXA_RETALHO, 'NAO') AS TEVE_BAIXA_RETALHO_OB,
    DRO.DATA_BAIXA_RETALHO AS DATA_BAIXA_RETALHO_OB,
    CASE
        WHEN UM.NRTIPOMOVIMENTO = 20 THEN 'Baixada por Requisicao Avulsa (Consumo)'
        WHEN UM.NRTIPOMOVIMENTO = 51 THEN 'Baixada e Consumida na Ordem (OB)'
        WHEN UM.NRTIPOMOVIMENTO = 82 THEN 'Baixada por Nao Conformidade / Refugo na OB'
        WHEN UM.NRTIPOMOVIMENTO = 36 THEN 'Baixada por Ajuste de Balanco / Inventario'
        WHEN UM.NRTIPOMOVIMENTO = 670 THEN 'Baixada para Venda como Retalho'
        WHEN UM.NRTIPOMOVIMENTO IN (4, 42, 75) THEN 'Baixada por Devolucao / Desmembramento'
        WHEN N.COD_SIT_ESTOQUE_CRU = 1 THEN 'Em Processo na OB (Indisponivel)'
        WHEN N.COD_SIT_ESTOQUE_CRU = 0 THEN 'Disponivel em Estoque'
        ELSE 'Status ' || N.COD_SIT_ESTOQUE_CRU
    END AS SITUACAO_MOVIMENTACAO_PECA,
    CASE
        WHEN DRO.TEVE_BAIXA_RETALHO = 'SIM'
            THEN 'Baixada para Venda como Retalho (Dep. 110)'
        WHEN UM.NRTIPOMOVIMENTO = 82
            THEN 'Baixada por Nao Conformidade / Refugo na OB (Dep. 100)'
        WHEN HAP.TEVE_BAIXA_NC = 'SIM' AND O.CLASSIFICACAO_QUALIDADE_OB LIKE '%Reprocesso%' AND O.STATUS_OB <> 'Encerrada'
            THEN 'Em Reprocesso por Defeito na OB (Refugo Anterior Tratado: ' || O.DEFEITOS_OB || ')'
        WHEN HAP.TEVE_BAIXA_NC = 'SIM' AND UM.NRTIPOMOVIMENTO <> 51
            THEN 'Baixada por Nao Conformidade / Refugo na OB (Dep. 100)'
        WHEN HAP.TEVE_REQUISICAO_AVULSA = 'SIM' AND UM.NRTIPOMOVIMENTO <> 51
            THEN 'Baixada por Requisicao Avulsa de Consumo'
        WHEN O.STATUS_OB = 'Emitida' 
            THEN 'Em Processo no Chao de Fabrica (Dep. 100)'
        WHEN DRO.TEVE_DESTINO_LD = 'SIM' 
            THEN 'Destinado para LD (' || DRO.CLIENTE_LD || ' - Ped. ' || DRO.PEDIDO_LD || ')'
        WHEN O.STATUS_OB = 'Encerrada' AND (O.CLASSIFICACAO_QUALIDADE_OB LIKE '%LD%' OR O.USOS_ALTERNATIVOS_OB LIKE '%LD%')
            THEN 'Estoque Acabado LD (Dep. 110 - Aguardando Alocacao Comercial LD)'
        WHEN DRO.PEDIDO_NORMAL IS NOT NULL 
            THEN 'Liberado Normal (' || DRO.CLIENTE_NORMAL || ' - Ped. ' || DRO.PEDIDO_NORMAL || ')'
        WHEN O.STATUS_OB = 'Encerrada' AND O.CLASSIFICACAO_QUALIDADE_OB LIKE '%Reprocesso%'
            THEN 'Estoque Acabado (Reprocesso Concluido / Recuperado)'
        WHEN O.STATUS_OB = 'Encerrada'
            THEN 'Estoque Acabado 1a Qualidade (Dep. 110 - Reservado Romaneio)'
        ELSE 'Disponivel em Estoque Cru'
    END AS DESTINACAO_FINAL_PECA
FROM NF_CRU N
LEFT JOIN SGTPRD.BOX BX_CRU ON TRIM(BX_CRU.CDBOX) = N.BOX_ATUAL_CRU AND BX_CRU.CDDEPOSITO = N.DEPOSITO_CRU
LEFT JOIN ULTIMO_MOV_PECA UM ON UM.IDPECASPRODUTO = N.ID_PECA_CRU AND UM.RN = 1
LEFT JOIN HISTORICO_ALERTAS_PECA HAP ON HAP.IDPECASPRODUTO = N.ID_PECA_CRU
LEFT JOIN OB_INFO O ON O.NUMERO_OB = N.NUMERO_OB
LEFT JOIN DESTINO_RESUMO_OB DRO ON DRO.NUMERO_OB = N.NUMERO_OB
ORDER BY N.NUMERO_OB, N.ID_PECA_CRU
