/* =============================================================================
OBJETIVO: Auditoria analítica da linhagem física e motivos de exclusão ancestral de ordens candidatas da Rama
DOMÍNIO: 06_qualidade_auditoria_obs
TIPO: Auditoria/Sentinela
GRÃO: NUMERO_OB, MOTIVO, OB_ANCESTRAL, NIVEL, TIPO_LIGACAO
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_BNF_PRODUCAO_FASE, SGTPRD.OB, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAORIGEM
CUIDADOS OPERACIONAIS: Consulta analítica para rastreabilidade de causas-raiz de exclusão de material (tingimento em ancestral direto ou de salto N2/N3, ou dupla passagem por Rama).
============================================================================= */

WITH
CandidatasRama AS (
    SELECT /*+ MATERIALIZE */ DISTINCT VPF.NUMERO_OB
    FROM SGTPRD.BD_BNF_PRODUCAO_FASE VPF
    JOIN SGTPRD.OB OBE ON OBE.NUMERO_OB = VPF.NUMERO_OB
    WHERE VPF.TIPO_MAQUINA = 6 
      AND VPF.STATUS = 0 
      AND VPF.TIPO_DESTINO = 0
      AND OBE.CODIGO_FLUXO IN (204, 302, 304, 305, 409, 412)
),
CadeiaAncestralOrdens (NUMERO_OB, NIVEL_GERACAO) AS (
    SELECT NUMERO_OB, 0 AS NIVEL_GERACAO
    FROM CandidatasRama
    UNION ALL
    SELECT 
        GEN.OB_MAE,
        C.NIVEL_GERACAO + 1
    FROM CadeiaAncestralOrdens C
    JOIN (
        SELECT 
            O.NUMERO_OB  AS OB_FILHO, 
            DO.NUMERO_OB AS OB_MAE
        FROM SGTPRD.GERAPECAORIGEMOB O
        JOIN SGTPRD.GERAPECADESTINOOB DO 
          ON DO.IDPECASPRODUTO = O.IDPECASPRODUTO 
         AND DO.NUMERO_OB <> O.NUMERO_OB
        UNION
        SELECT 
            O.NUMERO_OB  AS OB_FILHO, 
            DO.NUMERO_OB AS OB_MAE
        FROM SGTPRD.GERAPECAORIGEMOB O
        JOIN SGTPRD.GERAPECAORIGEM GO ON GO.IDPECASPRODUTO = O.IDPECASPRODUTO
        JOIN SGTPRD.GERAPECADESTINOOB DO 
          ON DO.IDPECASPRODUTO = GO.IDPECASPRODUTOORIGEM 
         AND DO.NUMERO_OB <> O.NUMERO_OB
    ) GEN ON GEN.OB_FILHO = C.NUMERO_OB
)
CYCLE NUMERO_OB SET IS_CYCLE TO 1 DEFAULT 0,
UniversoOrdens AS (
    SELECT /*+ MATERIALIZE */ DISTINCT NUMERO_OB
    FROM CadeiaAncestralOrdens
    WHERE IS_CYCLE = 0
),
ArestasFisicasPeca AS (
    SELECT /*+ MATERIALIZE LEADING(UO O DO) USE_NL(O) USE_NL(DO) */
        DO.NUMERO_OB        AS OB_ORIGEM,
        DO.IDPECASPRODUTO   AS PECA_ORIGEM,
        O.NUMERO_OB         AS OB_DESTINO,
        O.IDPECASPRODUTO    AS PECA_DESTINO,
        'CONTINUIDADE'      AS TIPO_LIGACAO
    FROM UniversoOrdens UO
    JOIN SGTPRD.GERAPECAORIGEMOB O ON O.NUMERO_OB = UO.NUMERO_OB
    JOIN SGTPRD.GERAPECADESTINOOB DO 
      ON DO.IDPECASPRODUTO = O.IDPECASPRODUTO 
     AND DO.NUMERO_OB <> O.NUMERO_OB
    UNION ALL
    SELECT /*+ MATERIALIZE LEADING(UO O GO DO) USE_NL(O) USE_NL(GO) USE_NL(DO) */
        DO.NUMERO_OB        AS OB_ORIGEM,
        DO.IDPECASPRODUTO   AS PECA_ORIGEM,
        O.NUMERO_OB         AS OB_DESTINO,
        GO.IDPECASPRODUTO   AS PECA_DESTINO,
        'TRANSFORMACAO'     AS TIPO_LIGACAO
    FROM UniversoOrdens UO
    JOIN SGTPRD.GERAPECAORIGEMOB O ON O.NUMERO_OB = UO.NUMERO_OB
    JOIN SGTPRD.GERAPECAORIGEM GO ON GO.IDPECASPRODUTO = O.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECADESTINOOB DO ON DO.IDPECASPRODUTO = GO.IDPECASPRODUTOORIGEM 
     AND DO.NUMERO_OB <> O.NUMERO_OB
),
GenealogiaCompleta AS (
    SELECT 
        CONNECT_BY_ROOT AF.OB_DESTINO   AS OB_FINAL,
        CONNECT_BY_ROOT AF.PECA_DESTINO AS PECA_FINAL,
        AF.OB_ORIGEM                    AS OB_ANCESTRAL,
        AF.PECA_ORIGEM                  AS PECA_ANCESTRAL,
        LEVEL                           AS NIVEL,
        AF.TIPO_LIGACAO
    FROM ArestasFisicasPeca AF
    START WITH AF.OB_DESTINO IN (SELECT NUMERO_OB FROM CandidatasRama)
    CONNECT BY NOCYCLE PRIOR AF.OB_ORIGEM = AF.OB_DESTINO 
                   AND PRIOR AF.PECA_ORIGEM = AF.PECA_DESTINO
),
ExclusoesAncestrais AS (
    SELECT DISTINCT GC.OB_FINAL AS NUMERO_OB, GC.OB_ANCESTRAL, 'TINGIMENTO_ANCESTRAL' AS MOTIVO
    FROM GenealogiaCompleta GC
    JOIN SGTPRD.BD_BNF_PRODUCAO_FASE TIN 
      ON TIN.NUMERO_OB = GC.OB_ANCESTRAL AND TIN.STATUS = 0
    WHERE TIN.CODIGO_FASE IN (40, 45, 210) 
       OR TIN.PI_REC IN (401, 451, 2101, 5001, 5002, 5003, 5004, 5005, 5006)
    UNION
    SELECT DISTINCT GC.OB_FINAL AS NUMERO_OB, GC.OB_ANCESTRAL, 'RAMA_ANCESTRAL' AS MOTIVO
    FROM GenealogiaCompleta GC
    JOIN SGTPRD.BD_BNF_PRODUCAO_FASE RM 
      ON RM.NUMERO_OB = GC.OB_ANCESTRAL AND RM.STATUS = 0 AND RM.TIPO_MAQUINA = 6 AND RM.TIPO_DESTINO = 0
)
SELECT EA.NUMERO_OB,
       EA.MOTIVO,
       EA.OB_ANCESTRAL,
       GC.NIVEL,
       GC.TIPO_LIGACAO,
       COUNT(*) AS QTD_PECAS
FROM ExclusoesAncestrais EA
JOIN GenealogiaCompleta GC 
  ON GC.OB_FINAL = EA.NUMERO_OB 
 AND GC.OB_ANCESTRAL = EA.OB_ANCESTRAL
GROUP BY EA.NUMERO_OB, EA.MOTIVO, EA.OB_ANCESTRAL, GC.NIVEL, GC.TIPO_LIGACAO
ORDER BY EA.NUMERO_OB, GC.NIVEL;
