-- =============================================================================
-- OBJETIVO: Conferência - OB montada (conferir se usaram as peças com restrição)
-- DOMÍNIO: 06_qualidade_auditoria_obs
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - OB montada (conferir se usaram as peças com restrição).sql
-- TIPO: SELECT (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (janela: últimos 60 dias via TRUNC(SYSDATE - 60))
-- TABELAS PRINCIPAIS: SGTPRD.COR, SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTOCOR,
--                     SGTPRD.FASES_FLUXO, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECAORIGEMOB,
--                     SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OBSERVACAO,
--                     SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OPERADOR
-- CUIDADOS OPERACIONAIS: Pushdown inicial materializado em OBS_ALVO filtrando as OBs
--                        com fase 10 confirmada e emissão nos últimos 60 dias.
--                        Elimina full scan de 2M de linhas em OB_FASES e GERAPECAORIGEMOB.
-- =============================================================================

WITH OBS_ALVO AS (
    /*+ MATERIALIZE */
    SELECT OB.NUMERO_OB,
           OB.CODIGO_REDUZIDO,
           OB.CODIGO_REDUZIDO_CRU,
           OB.CODIGO_OBSERVACAO,
           OB.DTEMISSAORDEM
      FROM SGTPRD.OB OB
      JOIN SGTPRD.OB_FASES OBF
        ON OBF.NUMERO_OB = OB.NUMERO_OB
       AND OBF.CODIGO_FASE = 10
       AND OBF.STATUS = 4
      JOIN SGTPRD.ENGEITEMESTOCOR COR
        ON COR.CDREDUZIDO = OB.CODIGO_REDUZIDO
      JOIN SGTPRD.COR CORX
        ON CORX.CODIGO_COR = COR.CDCOR
     WHERE OB.TIPO_ORDEM = 0
       AND OB.TIPO_GERACAO = 0
       AND OB.DTEMISSAORDEM >= TRUNC(SYSDATE - 60)
       AND CORX.CODIGO_CLASSIFICACAO IN (6, 9)
),
FASE_ATUAL AS (
    SELECT NUMERO_OB, DESCRICAO_FASE
      FROM (
            SELECT OBF.NUMERO_OB,
                   TRIM(FFL.DESCRICAO_FASE) AS DESCRICAO_FASE,
                   ROW_NUMBER() OVER (
                       PARTITION BY OBF.NUMERO_OB
                       ORDER BY OBF.SEQUENCIA DESC
                   ) AS RN
              FROM SGTPRD.OB_FASES OBF
              JOIN OBS_ALVO OA
                ON OA.NUMERO_OB = OBF.NUMERO_OB
              JOIN SGTPRD.FASES_FLUXO FFL
                ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
           )
     WHERE RN = 1
),
OPERADOR_FASE AS (
    SELECT OBF.NUMERO_OB,
           MAX(TRIM(OPE.NOME)) AS OPERADOR
      FROM SGTPRD.OB_FASES OBF
      JOIN OBS_ALVO OA
        ON OA.NUMERO_OB = OBF.NUMERO_OB
      JOIN SGTPRD.OPERADOR OPE
        ON OPE.CODIGO = OBF.OPERADOR_FINAL
     WHERE OBF.CODIGO_FASE = 10
     GROUP BY OBF.NUMERO_OB
),
PECAS_QUALIDADE AS (
    SELECT ORI.NUMERO_OB,
           COUNT(CASE WHEN GPC.FINALIDADE NOT IN (1, 8) THEN ORI.IDPECASPRODUTO END) AS PECAS_COM_RESTRICAO,
           COUNT(CASE WHEN GPC.FINALIDADE IN (1, 8) THEN ORI.IDPECASPRODUTO END) AS PECAS_SEM_RESTRICAO
      FROM SGTPRD.GERAPECAORIGEMOB ORI
      JOIN OBS_ALVO OA
        ON OA.NUMERO_OB = ORI.NUMERO_OB
      JOIN SGTPRD.GERAPECASPRODUTO GPP
        ON GPP.IDPECASPRODUTO = ORI.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECACOMPLPECA GPC
        ON GPC.IDPECASPRODUTO = ORI.IDPECASPRODUTO
     WHERE GPP.PADRAO_QUALIDADE_SIN = 1
       AND GPP.TIDOCUMENTOENTRADA <> 8
     GROUP BY ORI.NUMERO_OB
)
SELECT OA.NUMERO_OB                                          AS NUMERO_OB,
       OA.CODIGO_REDUZIDO_CRU,
       TRIM(ART.CDARTIGOCRU)                                 AS ARTIGO,
       TRIM(ITE.DESCRICAO)                                   AS DESCRICAO_ITEM,
       OBP.TOTAL_PECAS_CONFIRM                               AS PECAS_CONFIRMADAS,
       NVL(PQ.PECAS_COM_RESTRICAO, 0)                        AS PECAS_COM_RESTRICAO,
       NVL(PQ.PECAS_SEM_RESTRICAO, 0)                        AS PECAS_SEM_RESTRICAO,
       FA.DESCRICAO_FASE                                     AS FASE_ATUAL,
       'CONFIRMADA'                                          AS ST_FASE,
       OPF.OPERADOR                                          AS OPERADOR,
       OA.DTEMISSAORDEM                                      AS DATA_EMISSAO_ORDEM,
       OBS.TEXTO                                             AS OBSERVACAO_OB
  FROM OBS_ALVO OA
  JOIN SGTPRD.OB_PRODUTO OBP
    ON OBP.NUMERO_OB = OA.NUMERO_OB
  JOIN SGTPRD.ENGEITEMESTOARTCRU ART
    ON ART.CDREDUZIDO = OA.CODIGO_REDUZIDO
  JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON ITE.CODIGO_REDUZIDO = OA.CODIGO_REDUZIDO
  LEFT JOIN FASE_ATUAL FA
    ON FA.NUMERO_OB = OA.NUMERO_OB
  LEFT JOIN OPERADOR_FASE OPF
    ON OPF.NUMERO_OB = OA.NUMERO_OB
  LEFT JOIN PECAS_QUALIDADE PQ
    ON PQ.NUMERO_OB = OA.NUMERO_OB
  LEFT JOIN SGTPRD.OBSERVACAO OBS
    ON OBS.CODIGO = OA.CODIGO_OBSERVACAO
 WHERE NVL(PQ.PECAS_COM_RESTRICAO, PQ.PECAS_SEM_RESTRICAO) > 0
 ORDER BY OA.DTEMISSAORDEM DESC
 FETCH FIRST 500 ROWS ONLY
