/* =============================================================================
OBJETIVO: Testes de qualidade laboratoriais agrupados por artigo cru
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: 06_qualidade_auditoria_obs/qld_conferencia_testes_de_qualidade.sql (Query #2)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.ITENS_ESTOQUE, SGTPRD.LABOGRUPOPADROESQUAL, SGTPRD.LABOPADROESPRODUTO, SGTPRD.LABOPADROESQUALIDADE
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
REVISÃO (20/09/2026 - Onda 4): (+) de LBP migrado para LEFT JOIN ANSI.
  guard_sql.py: exit 0.
============================================================================= */

SELECT GRP.CDITEMARTIGOCRU,
       (SELECT SUBSTR(ITE2.CODIGO,4,5) FROM SGTPRD.ITENS_ESTOQUE ITE2 WHERE ITE2.CODIGO_REDUZIDO = LBP.CODIGO_REDUZIDO) CODIGO_ARTIGO_CRU,
       ITE.CODIGO AS CODIGO_ITEM,
       (SELECT TRIM(ITE2.DESCRICAO) FROM SGTPRD.ITENS_ESTOQUE ITE2 WHERE ITE2.CODIGO_REDUZIDO = LBP.CODIGO_REDUZIDO) DESCRIAO,
       DECODE(LPQ.IDITEMTESTE,1, 'GRAMATURA',8,'LARGURA ACABADA') TESTE,
       LPQ.VALOR_PADRAO_GRAFICO,
       LPQ.VALOR_PADRAO_MAXIMO,
       LPQ.VALOR_PADRAO_MINIMO
  FROM SGTPRD.LABOGRUPOPADROESQUAL GRP
  JOIN SGTPRD.LABOPADROESQUALIDADE LPQ ON LPQ.IDLABOGRUPOPADROESQU = GRP.IDLABOGRUPOPADROESQU
  LEFT JOIN SGTPRD.LABOPADROESPRODUTO LBP ON LBP.IDLABOGRUPOPADROESQU = LPQ.IDLABOGRUPOPADROESQU
  JOIN SGTPRD.ITENS_ESTOQUE        ITE ON ITE.CODIGO_REDUZIDO = LBP.CODIGO_REDUZIDO
 WHERE ITE.IDMASCARATIPOINSUMO = 'BNF  '
   AND LPQ.IDITEMTESTE IN (1, 8)
   AND TRIM(GRP.CDITEMARTIGOCRU) <> (SELECT SUBSTR(ITE2.CODIGO,4,5) FROM SGTPRD.ITENS_ESTOQUE ITE2 WHERE ITE2.CODIGO_REDUZIDO = LBP.CODIGO_REDUZIDO)
 GROUP BY LBP.CODIGO_REDUZIDO,
          ITE.CODIGO,
          GRP.CDITEMARTIGOCRU,
          LPQ.IDITEMTESTE,
          LPQ.VALOR_PADRAO_GRAFICO,
          LPQ.VALOR_PADRAO_MAXIMO,
          LPQ.VALOR_PADRAO_MINIMO
 ORDER BY 2;
