/* =============================================================================
OBJETIVO: Conferência de tubetes e plásticos por código reduzido (por nota fiscal)
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: 06_qualidade_auditoria_obs/qld_notas_fiscais_conferencia_tubetes_e_plasticos.sql (Query #2)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (NUMERO_NF fixo em 49416)
TABELAS PRINCIPAIS: SGTPRD.BD_FAT_FATURAMENTO, SGTPRD.GERAPECAROMSAIDA,
                    SGTPRD.GERAPECASPRODUTO, SGTPRD.NOTAFISCALCAPA,
                    SGTPRD.NOTAFISCALITENS, SGTPRD.PRODUTO_ROMANEIO,
                    SGTPRD.TIPO_ACONDICIONAMENT
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
OTIMIZAÇÃO: Predicado pushdown da NF e filial na CTE FATURAMENTO antes do join com
  peças de saída, reduzindo tempo de timeout para ~2.3s.
============================================================================= */

WITH FATURAMENTO AS (
    SELECT VFA.FILIALNOTA AS FILIAL,
           VFA.NUMERONOTA AS NUMERO_NF,
           VFA.NUMERO_ROMANEIO,
           VFA.CODIGO_REDUZIDO AS REDUZ,
           TRIM(ITE.DESCRICAO) AS DESCR_ITEM,
           VFA.QUANT,
           PRO.PESOBRUTO AS PESO_BRUTO,
           VFA.TIOPERNATUREZA,
           NSA.STNOTAFATURAMENTO AS STATUS_NF
      FROM SGTPRD.BD_FAT_FATURAMENTO VFA
      JOIN SGTPRD.NOTAFISCALITENS PNS
        ON PNS.ID = VFA.IDPNS
      JOIN SGTPRD.NOTAFISCALCAPA NSA
        ON NSA.ID = PNS.IDNOTAFISCALCAPA
      JOIN SGTPRD.PRODUTO_ROMANEIO PRO
        ON PRO.IDPRODUTO_ROMANEIO = VFA.IDPRODUTO_ROMANEIO
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = VFA.CODIGO_REDUZIDO
     WHERE VFA.FILIALNOTA IN (1)
       AND VFA.TIOPERNATUREZA IN (2)
       AND NSA.STNOTAFATURAMENTO IN (3)
       AND VFA.NUMERONOTA IN (49416)
),
PECAS_ROMANEIO AS (
    SELECT GPEC.NUMERO_ROMANEIO_SAID AS NUMERO_ROMANEIO,
           GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
           GPEC.IDPECASPRODUTO,
           GPP.IDACONDICIONAMENTO
      FROM SGTPRD.GERAPECAROMSAIDA GPEC
      JOIN SGTPRD.GERAPECASPRODUTO GPP
        ON GPP.IDPECASPRODUTO = GPEC.IDPECASPRODUTO
     WHERE GPEC.NUMERO_ROMANEIO_SAID IN (SELECT NUMERO_ROMANEIO FROM FATURAMENTO)
)
SELECT VPF.REDUZ AS ARTIGO,
       SUM(VPF.PESO_BRUTO) AS PESO_BRUTO,
       COUNT(PR.IDPECASPRODUTO) AS PECAS,
       ACO.PESO AS TUBETE_KG_UND,
       SUM(ACO.PESO) AS TUBETE_KG_TOTAL,
       CASE WHEN UPPER(ACO.DESCRICAO) LIKE '%SEM PL%STICO%' THEN 0 ELSE 1 END AS USA_PLASTICO_UND,
       SUM(CASE WHEN UPPER(ACO.DESCRICAO) LIKE '%SEM PL%STICO%' THEN 0 ELSE 1 END) AS QTD_SACOS_PLASTICO
  FROM FATURAMENTO VPF
  JOIN PECAS_ROMANEIO PR
    ON PR.NUMERO_ROMANEIO = VPF.NUMERO_ROMANEIO
   AND PR.REDUZ = VPF.REDUZ
  LEFT JOIN SGTPRD.TIPO_ACONDICIONAMENT ACO
    ON ACO.IDACONDICIONAMENTO = PR.IDACONDICIONAMENTO
 GROUP BY VPF.REDUZ, ACO.PESO, ACO.DESCRICAO
 ORDER BY SUM(ACO.PESO) DESC
