/* =============================================================================
OBJETIVO: OB_s com peso menor que 8kg
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s com peso menor que 8kg.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (janela: últimos 60 dias de encerramento)
TABELAS PRINCIPAIS: SGTPRD.OB, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAORIGEM, SGTPRD.GERAPECASPRODUTO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO: Janela dinâmica nos últimos 60 dias de encerramento de OB em CTE materializada,
  restringindo a verificação de divergências de pesagem para execução em ~2.2s.
============================================================================= */

WITH OBS_RECENTES AS (
    SELECT /*+ MATERIALIZE */
           OBE.NUMERO_OB,
           OBE.TIPO_ORDEM,
           DATE '1996-01-01' + OBE.TEMPO_ENCERRAMENTO_O / 1440 AS DT_ENCERRAMENTO
      FROM SGTPRD.OB OBE
     WHERE OBE.STATUS = 0
       AND OBE.TEMPO_ENCERRAMENTO_O >= (TRUNC(SYSDATE) - 60 - DATE '1996-01-01') * 1440
),
DELTA_OBS AS (
    SELECT /*+ MATERIALIZE */ DISTINCT DES.NUMERO_OB
      FROM SGTPRD.GERAPECADESTINOOB DES
      JOIN SGTPRD.GERAPECAORIGEM LIG ON LIG.IDPECASPRODUTO = DES.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = DES.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECASPRODUTO GPC ON GPC.IDPECASPRODUTO = LIG.IDPECASPRODUTOORIGEM
     WHERE DES.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_RECENTES)
       AND GPP.TISITUACAOESTOQUE IS NOT NULL
       AND GPC.QTLIQUIDA <> 0
       AND (100 - (GPP.QTLIQUIDA / NULLIF(GPC.QTLIQUIDA, 0) * 100) >= 20
         OR 100 - (GPP.QTLIQUIDA / NULLIF(GPC.QTLIQUIDA, 0) * 100) <= -20)
),
PEC AS (
    SELECT DES.NUMERO_OB, COUNT(GPP.IDPECASPRODUTO) AS NR_PEC_MENOR_8
      FROM SGTPRD.GERAPECADESTINOOB DES
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = DES.IDPECASPRODUTO
     WHERE DES.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_RECENTES)
       AND GPP.QTLIQUIDA <= 8
     GROUP BY DES.NUMERO_OB
),
CRU AS (
    SELECT ORI.NUMERO_OB, COUNT(GPP.IDPECASPRODUTO) AS NR_PEC_MENOR_8
      FROM SGTPRD.GERAPECAORIGEMOB ORI
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = ORI.IDPECASPRODUTO
     WHERE ORI.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_RECENTES)
       AND GPP.QTLIQUIDA <= 8
     GROUP BY ORI.NUMERO_OB
)
SELECT OBR.TIPO_ORDEM,
       OBR.DT_ENCERRAMENTO,
       OBR.NUMERO_OB,
       PEC.NR_PEC_MENOR_8 AS PEC_ACAB_M8,
       NVL(CRU.NR_PEC_MENOR_8, 0) AS PEC_CRU_M8
  FROM OBS_RECENTES OBR
  JOIN PEC ON PEC.NUMERO_OB = OBR.NUMERO_OB
  LEFT JOIN CRU ON CRU.NUMERO_OB = OBR.NUMERO_OB
 WHERE EXISTS (SELECT 1 FROM DELTA_OBS DLT WHERE DLT.NUMERO_OB = OBR.NUMERO_OB)
   AND PEC.NR_PEC_MENOR_8 <> NVL(CRU.NR_PEC_MENOR_8, 0)
 ORDER BY 2 DESC
 FETCH FIRST 100 ROWS ONLY
