/* =============================================================================
OBJETIVO: Auditoria e Investigação de Coerência dos Grupos de Máquinas com Foco no Campo Nome do Layout
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: qld_auditoria_grupos_maquinas_layout.sql
TIPO: Auditoria e Qualidade de Grupos e Cadastros Industriais
PARÂMETROS / BINDS: Nenhum (auditoria global multi-setorial)
TABELAS PRINCIPAIS: SGTPRD.GRUPO_MAQUINAS, SGTPRD.MAQUINA, SGTPRD.SECAO, SGTPRD.UNIDADE_FABRIL
CUIDADOS OPERACIONAIS: Consulta somente leitura de cobertura integral (108 grupos).
                       Avalia a arquitetura híbrida de layout:
                       1) NMLAYOUTOPFGRUPO (campo canônico moderno de 100 posições)
                       2) NOME_RTM_ORDEM_PROD (campo legado operacional de 30 posições)
                       3) STLAYOUTOPFGRUPO (flag indicadora de status do layout)
                       4) NOME_RTM_ETIQUETAS (layout de etiquetas da OP)
                       Cruza métricas reais de máquinas ativas/inativas por setor,
                       apura saldos de divergência entre a quantidade declarada no texto
                       do layout (ex.: 25 MÁQUINAS) e o parque fabril ativo, e audita
                       truncamentos de strings e layouts multisetoriais.
============================================================================= */

WITH GRUPO_BASE AS (
    SELECT G.SETOR,
           G.GRUPO,
           TRIM(G.DESCRICAO) AS DESCRICAO_GRUPO,
           TRIM(G.NMLAYOUTOPFGRUPO) AS NMLAYOUTOPFGRUPO,
           TRIM(G.NOME_RTM_ORDEM_PROD) AS NOME_RTM_ORDEM_PROD,
           G.STLAYOUTOPFGRUPO,
           TRIM(G.NOME_RTM_ETIQUETAS) AS NOME_RTM_ETIQUETAS,
           TRIM(G.SECAO) AS SECAO,
           G.CDFILIAL,
           TRIM(G.UNIDADE_FABRIL) AS UNIDADE_FABRIL,
           COALESCE(TRIM(G.NMLAYOUTOPFGRUPO), TRIM(G.NOME_RTM_ORDEM_PROD)) AS LAYOUT_EFETIVO,
           CASE
             WHEN TRIM(G.NMLAYOUTOPFGRUPO) IS NOT NULL AND TRIM(G.NOME_RTM_ORDEM_PROD) IS NOT NULL 
                  AND TRIM(G.NMLAYOUTOPFGRUPO) = TRIM(G.NOME_RTM_ORDEM_PROD) THEN 'CAMPOS_CONVERGENTES'
             WHEN TRIM(G.NMLAYOUTOPFGRUPO) IS NOT NULL AND TRIM(G.NOME_RTM_ORDEM_PROD) IS NOT NULL 
                  AND TRIM(G.NMLAYOUTOPFGRUPO) <> TRIM(G.NOME_RTM_ORDEM_PROD) THEN 'DIVERGENCIA_CAMPOS'
             WHEN TRIM(G.NMLAYOUTOPFGRUPO) IS NOT NULL THEN 'CANONICO_MODERNO'
             WHEN TRIM(G.NOME_RTM_ORDEM_PROD) IS NOT NULL THEN 'LEGADO_OPERACIONAL'
             ELSE 'SEM_LAYOUT'
           END AS ORIGEM_LAYOUT
      FROM SGTPRD.GRUPO_MAQUINAS G
),
GRUPO_MAQ_METRICAS AS (
    SELECT M.SETOR,
           M.GRUPO,
           COUNT(*) AS TOTAL_MAQUINAS,
           COUNT(CASE WHEN M.MAQUINA_ATIVA = '1' THEN 1 END) AS QTD_MAQUINAS_ATIVAS,
           COUNT(CASE WHEN NVL(M.MAQUINA_ATIVA, '0') <> '1' THEN 1 END) AS QTD_MAQUINAS_INATIVAS,
           COUNT(DISTINCT M.CDFILIAL) AS QTD_FILIAIS_MAQS,
           COUNT(DISTINCT M.CODIGO_UNIDADE_FABRI) AS QTD_UNIDADES_MAQS
      FROM SGTPRD.MAQUINA M
     GROUP BY M.SETOR, M.GRUPO
),
LAYOUT_TOTAIS AS (
    SELECT GB.SETOR,
           GB.LAYOUT_EFETIVO,
           COUNT(DISTINCT GB.GRUPO) AS QTD_GRUPOS_LAYOUT,
           SUM(NVL(GMM.TOTAL_MAQUINAS, 0)) AS TOTAL_MAQUINAS_LAYOUT,
           SUM(NVL(GMM.QTD_MAQUINAS_ATIVAS, 0)) AS TOTAL_MAQUINAS_ATIVAS_LAYOUT,
           SUM(NVL(GMM.QTD_MAQUINAS_INATIVAS, 0)) AS TOTAL_MAQUINAS_INATIVAS_LAYOUT,
           TO_NUMBER(REGEXP_SUBSTR(GB.LAYOUT_EFETIVO, '\(([0-9]+)\s*M', 1, 1, 'i', 1)) AS QTD_DECLARADA_NO_LAYOUT
      FROM GRUPO_BASE GB
      LEFT JOIN GRUPO_MAQ_METRICAS GMM
        ON GMM.SETOR = GB.SETOR
       AND GMM.GRUPO = GB.GRUPO
     WHERE GB.LAYOUT_EFETIVO IS NOT NULL
     GROUP BY GB.SETOR, GB.LAYOUT_EFETIVO
),
LAYOUT_SETORES AS (
    SELECT GB.LAYOUT_EFETIVO,
           COUNT(DISTINCT GB.SETOR) AS QTD_SETORES_LAYOUT
      FROM GRUPO_BASE GB
     WHERE GB.LAYOUT_EFETIVO IS NOT NULL
     GROUP BY GB.LAYOUT_EFETIVO
)
SELECT CASE
         WHEN LT.QTD_DECLARADA_NO_LAYOUT IS NOT NULL 
              AND LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT <> LT.QTD_DECLARADA_NO_LAYOUT THEN 'INCONSISTENTE'
         WHEN GB.ORIGEM_LAYOUT = 'DIVERGENCIA_CAMPOS' THEN 'INCONSISTENTE'
         WHEN GB.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN 'INCONSISTENTE'
         WHEN LS.QTD_SETORES_LAYOUT > 1 THEN 'ALERTA'
         WHEN GB.NOME_RTM_ORDEM_PROD IS NOT NULL 
              AND (LENGTH(GB.NOME_RTM_ORDEM_PROD) >= 29 OR (GB.NOME_RTM_ORDEM_PROD LIKE '%(%' AND GB.NOME_RTM_ORDEM_PROD NOT LIKE '%)%')) THEN 'ALERTA'
         WHEN NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) > 0 
              AND GB.LAYOUT_EFETIVO IS NULL THEN 'ALERTA'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) = 0 THEN 'ALERTA'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND (GB.STLAYOUTOPFGRUPO = '0' OR GB.STLAYOUTOPFGRUPO IS NULL) THEN 'ALERTA'
         WHEN GB.ORIGEM_LAYOUT = 'LEGADO_OPERACIONAL' THEN 'ALERTA'
         WHEN NVL(GMM.TOTAL_MAQUINAS, 0) = 0 THEN 'ALERTA'
         ELSE 'CONFORME'
       END AS STATUS_COERENCIA,
       CASE
         WHEN LT.QTD_DECLARADA_NO_LAYOUT IS NOT NULL 
              AND LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT <> LT.QTD_DECLARADA_NO_LAYOUT THEN 'CRITICA'
         WHEN GB.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN 'CRITICA'
         WHEN GB.ORIGEM_LAYOUT = 'DIVERGENCIA_CAMPOS' THEN 'MEDIA'
         WHEN LS.QTD_SETORES_LAYOUT > 1 THEN 'MEDIA'
         WHEN GB.NOME_RTM_ORDEM_PROD IS NOT NULL 
              AND (LENGTH(GB.NOME_RTM_ORDEM_PROD) >= 29 OR (GB.NOME_RTM_ORDEM_PROD LIKE '%(%' AND GB.NOME_RTM_ORDEM_PROD NOT LIKE '%)%')) THEN 'MEDIA'
         WHEN NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) > 0 
              AND GB.LAYOUT_EFETIVO IS NULL 
              AND GB.SETOR IN (4, 5, 2) THEN 'MEDIA'
         WHEN NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) > 0 
              AND GB.LAYOUT_EFETIVO IS NULL THEN 'BAIXA'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) = 0 THEN 'BAIXA'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND (GB.STLAYOUTOPFGRUPO = '0' OR GB.STLAYOUTOPFGRUPO IS NULL) THEN 'BAIXA'
         WHEN GB.ORIGEM_LAYOUT = 'LEGADO_OPERACIONAL' THEN 'BAIXA'
         WHEN NVL(GMM.TOTAL_MAQUINAS, 0) = 0 THEN 'BAIXA'
         ELSE 'OK'
       END AS GRAVIDADE,
       NVL(
         RTRIM(
           CASE WHEN LT.QTD_DECLARADA_NO_LAYOUT IS NOT NULL AND LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT <> LT.QTD_DECLARADA_NO_LAYOUT THEN '[QTD_MAQS_DIVERGENTE_DO_LAYOUT] ' END ||
           CASE WHEN GB.ORIGEM_LAYOUT = 'DIVERGENCIA_CAMPOS' THEN '[DIVERGENCIA_ENTRE_CAMPOS_LAYOUT] ' END ||
           CASE WHEN LS.QTD_SETORES_LAYOUT > 1 THEN '[LAYOUT_COMPARTILHADO_MULTISETOR] ' END ||
           CASE WHEN GB.NOME_RTM_ORDEM_PROD IS NOT NULL AND (LENGTH(GB.NOME_RTM_ORDEM_PROD) >= 29 OR (GB.NOME_RTM_ORDEM_PROD LIKE '%(%' AND GB.NOME_RTM_ORDEM_PROD NOT LIKE '%)%')) THEN '[LAYOUT_LEGADO_TRUNCADO_OU_ABREVIADO] ' END ||
           CASE WHEN NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) > 0 AND GB.LAYOUT_EFETIVO IS NULL THEN '[GRUPO_ATIVO_SEM_LAYOUT] ' END ||
           CASE WHEN GB.LAYOUT_EFETIVO IS NOT NULL AND NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) = 0 THEN '[LAYOUT_CONFIGURADO_SEM_MAQ_ATIVA] ' END ||
           CASE WHEN GB.LAYOUT_EFETIVO IS NOT NULL AND (GB.STLAYOUTOPFGRUPO = '0' OR GB.STLAYOUTOPFGRUPO IS NULL) THEN '[FLAG_STATUS_LAYOUT_DESATIVADA] ' END ||
           CASE WHEN GB.ORIGEM_LAYOUT = 'LEGADO_OPERACIONAL' THEN '[CAMPO_CANONICO_NMLAYOUT_PENDENTE] ' END ||
           CASE WHEN NVL(GMM.TOTAL_MAQUINAS, 0) = 0 THEN '[GRUPO_ORFAO_SEM_MAQUINAS] ' END ||
           CASE WHEN GB.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN '[SECAO_INEXISTENTE_NO_CADASTRO] ' END
         ),
         '[LAYOUT_CONFORME]'
       ) AS MOTIVOS_INCONSISTENCIA,
       GB.SETOR AS SETOR_COD,
       CASE GB.SETOR
         WHEN 1 THEN 'Algodão'
         WHEN 2 THEN 'Fiação'
         WHEN 3 THEN 'Tecelagem'
         WHEN 4 THEN 'Malharia Circular'
         WHEN 5 THEN 'Beneficiamento'
         WHEN 6 THEN 'Acabamento'
         WHEN 7 THEN 'Malharia Retilínea'
         WHEN 8 THEN 'Bordado'
         WHEN 9 THEN 'Confecção'
         WHEN 10 THEN 'Laboratório'
         ELSE 'Setor ' || TO_CHAR(GB.SETOR)
       END AS SETOR_NOME,
       GB.GRUPO AS GRUPO_COD,
       GB.DESCRICAO_GRUPO,
       GB.LAYOUT_EFETIVO,
       GB.ORIGEM_LAYOUT,
       GB.NMLAYOUTOPFGRUPO AS NMLAYOUTOPFGRUPO_CANONICO,
       GB.NOME_RTM_ORDEM_PROD AS NOME_RTM_ORDEM_PROD_LEGADO,
       GB.STLAYOUTOPFGRUPO,
       GB.NOME_RTM_ETIQUETAS,
       LT.QTD_DECLARADA_NO_LAYOUT,
       NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) AS QTD_MAQUINAS_ATIVAS_GRUPO,
       NVL(GMM.QTD_MAQUINAS_INATIVAS, 0) AS QTD_MAQUINAS_INATIVAS_GRUPO,
       NVL(GMM.TOTAL_MAQUINAS, 0) AS TOTAL_MAQUINAS_GRUPO,
       NVL(LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT, 0) AS TOTAL_MAQS_ATIVAS_LAYOUT,
       NVL(LT.TOTAL_MAQUINAS_INATIVAS_LAYOUT, 0) AS TOTAL_MAQS_INATIVAS_LAYOUT,
       NVL(LT.TOTAL_MAQUINAS_LAYOUT, 0) AS TOTAL_MAQS_PARQUE_LAYOUT,
       CASE
         WHEN LT.QTD_DECLARADA_NO_LAYOUT IS NOT NULL 
         THEN NVL(LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT, 0) - LT.QTD_DECLARADA_NO_LAYOUT
         ELSE NULL
       END AS SALDO_DIVERGENCIA_QTD,
       NVL(LT.QTD_GRUPOS_LAYOUT, 0) AS QTD_GRUPOS_COMPARTILHADOS,
       NVL(LS.QTD_SETORES_LAYOUT, 0) AS QTD_SETORES_COMPARTILHADOS,
       GB.SECAO AS SECAO_GRUPO,
       TRIM(SEC.DESSEC) AS DESCRICAO_SECAO,
       GB.CDFILIAL AS FILIAL_COD,
       GB.UNIDADE_FABRIL AS UNIDADE_FABRIL_COD,
       TRIM(UFA.NOME_UNIDADE_FABRIL) AS NOME_UNIDADE_FABRIL,
       CASE
         WHEN LT.QTD_DECLARADA_NO_LAYOUT IS NOT NULL 
              AND LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT <> LT.QTD_DECLARADA_NO_LAYOUT THEN 'Revisar saldo de máquinas no texto do layout (Saldo: ' || TO_CHAR(NVL(LT.TOTAL_MAQUINAS_ATIVAS_LAYOUT, 0) - LT.QTD_DECLARADA_NO_LAYOUT) || ' maqs)'
         WHEN GB.ORIGEM_LAYOUT = 'DIVERGENCIA_CAMPOS' THEN 'Unificar campos de layout: NMLAYOUTOPFGRUPO diverge de NOME_RTM_ORDEM_PROD'
         WHEN LS.QTD_SETORES_LAYOUT > 1 THEN 'Isolar layouts por setor fabril: mesmo layout compartilhado entre setores distintos'
         WHEN GB.NOME_RTM_ORDEM_PROD IS NOT NULL 
              AND (LENGTH(GB.NOME_RTM_ORDEM_PROD) >= 29 OR (GB.NOME_RTM_ORDEM_PROD LIKE '%(%' AND GB.NOME_RTM_ORDEM_PROD NOT LIKE '%)%')) THEN 'Migrar descrição para NMLAYOUTOPFGRUPO (100 posições) para eliminar truncamento'
         WHEN NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) > 0 
              AND GB.LAYOUT_EFETIVO IS NULL THEN 'Definir layout padrão de OP/RTM para o grupo produtivo ativo'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND NVL(GMM.QTD_MAQUINAS_ATIVAS, 0) = 0 THEN 'Grupo sem máquinas ativas: avaliar inativação ou limpeza do layout associado'
         WHEN GB.LAYOUT_EFETIVO IS NOT NULL 
              AND (GB.STLAYOUTOPFGRUPO = '0' OR GB.STLAYOUTOPFGRUPO IS NULL) THEN 'Ativar flag STLAYOUTOPFGRUPO = 1 ou alinhar regra de habilitação do ERP'
         WHEN GB.ORIGEM_LAYOUT = 'LEGADO_OPERACIONAL' THEN 'Copiar layout do campo legado para o campo canônico NMLAYOUTOPFGRUPO'
         WHEN NVL(GMM.TOTAL_MAQUINAS, 0) = 0 THEN 'Cadastrar máquinas no grupo ou inativar registro órfão'
         ELSE 'Cadastro em conformidade operacional'
       END AS SUGESTAO_ACAO
  FROM GRUPO_BASE GB
  LEFT JOIN GRUPO_MAQ_METRICAS GMM
    ON GMM.SETOR = GB.SETOR
   AND GMM.GRUPO = GB.GRUPO
  LEFT JOIN LAYOUT_TOTAIS LT
    ON LT.SETOR = GB.SETOR
   AND LT.LAYOUT_EFETIVO = GB.LAYOUT_EFETIVO
  LEFT JOIN LAYOUT_SETORES LS
    ON LS.LAYOUT_EFETIVO = GB.LAYOUT_EFETIVO
  LEFT JOIN SGTPRD.SECAO SEC
    ON SEC.SECAO = GB.SECAO
   AND SEC.CDFILIAL = GB.CDFILIAL
  LEFT JOIN SGTPRD.UNIDADE_FABRIL UFA
    ON UFA.CODIGO_UNIDADE_FABRI = GB.UNIDADE_FABRIL
 ORDER BY CASE STATUS_COERENCIA WHEN 'INCONSISTENTE' THEN 1 WHEN 'ALERTA' THEN 2 ELSE 3 END,
          CASE GRAVIDADE WHEN 'CRITICA' THEN 1 WHEN 'MEDIA' THEN 2 WHEN 'BAIXA' THEN 3 ELSE 4 END,
          SETOR_COD,
          GRUPO_COD
