/* =============================================================================
OBJETIVO: Conferência - Peças com peso menor que 17kg
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Peças com peso menor que 17kg.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (janela: últimos 30 dias)
TABELAS PRINCIPAIS: SGTPRD.BD_PRD_MOVPROD, SGTPRD.PESO_PADRAO_PECA, SGTPRD.GERAPECASPRODUTO, SGTPRD.CRISTAL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO: Janela recente de 30 dias com uso direto de índice em PRODUCAO_DATA e CTEs materializadas
  de enumerações, reduzindo de timeout para ~3.0s.
============================================================================= */

WITH TIPO_DOC AS (
    SELECT /*+ MATERIALIZE */ ENI.SEQUENCE CD_TIPO_DOC_ENTRADA,
           UPPER(ENI.DESCRIPTION) DS_TIPO_DOC_ENTRADA
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI
        ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE '%TTIPODOCUMENTOENTRADAPECA%'
), STATUS_PECA AS (
    SELECT /*+ MATERIALIZE */ ENI.SEQUENCE STPECAPRODUTO, ENI.DESCRIPTION DESCRICAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TSTATUSPECAPRODUTO%'
)
SELECT GPP.IDPECASPRODUTO,
       MVP.PRODUCAO_DATA,
       MVP.PRODUCAO_TURNO,
       MVP.DATA_DOCUMENTO,
       MVP.REDUZIDO_ITEM,
       GPP.QTLIQUIDA,
       GPP.CODIGO_DEPOSITO  DEPOSITO,
       STP.STPECAPRODUTO || ' - ' || STP.DESCRICAO STATUS_PECA,
       NVL(GPO.NUMERO_OB,0) NR_OB,
       OBE.STATUS,
       CRI.CODREDUSUARIO || ' - ' || CRI.USUARIO   USUARIO,
       TDC.DS_TIPO_DOC_ENTRADA

  FROM SGTPRD.BD_PRD_MOVPROD               MVP
  JOIN SGTPRD.PESO_PADRAO_PECA             PPP ON PPP.CODIGO_REDUZIDO_PROD = MVP.REDUZIDO_ITEM
  JOIN SGTPRD.GERAPECASPRODUTO             GPP ON GPP.IDPECASPRODUTO       = MVP.IDPECASPRODUTO
  JOIN TIPO_DOC                            TDC ON TDC.CD_TIPO_DOC_ENTRADA  = GPP.TIDOCUMENTOENTRADA
  JOIN STATUS_PECA                         STP ON STP.STPECAPRODUTO         = GPP.STPECAPRODUTO
  JOIN SGTPRD.CRISTAL                      CRI ON CRI.CODREDUSUARIO         = MVP.CODREDUSUARIO
  LEFT JOIN SGTPRD.GERAPECAORIGEMOB        GPO ON GPO.IDPECASPRODUTO        = GPP.IDPECASPRODUTO
  LEFT JOIN SGTPRD.OB                      OBE ON OBE.NUMERO_OB             = GPO.NUMERO_OB

 WHERE MVP.CODIGO = 2
   AND GPP.PADRAO_QUALIDADE_SIN = 1
   AND GPP.TISITUACAOESTOQUE IN (0,1)
   AND PPP.PESO_METROS_PECA > 14
   AND GPP.QTLIQUIDA <= 17
   AND MVP.PRODUCAO_DATA >= TRUNC(SYSDATE) - 30
 ORDER BY MVP.DATA_DOCUMENTO DESC
 FETCH FIRST 100 ROWS ONLY
