/* =============================================================================
OBJETIVO: Conferência - Reduzidos que faltam incluir no contrato de industrialização
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Reduzidos que faltam incluir no contrato de industrialização.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.FLUXO_FASES, SGTPRD.FLUXO_FASE_MAQUINAS, SGTPRD.GRUPO_FLUXO, SGTPRD.GRUPO_FLUXO_FASES, SGTPRD.GRUPO_MAQUINAS, SGTPRD.GRUPO_PRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.PESSOASFJ, SGTPRD.SUPRCONTITEM, SGTPRD.SUPRCONTITEMENTR, SGTPRD.SUPRCONTRATO, SGTPRD.UNIDADE_FABRIL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT
    ART.CDARTIGOCRU AS ARTIGO,
    TRIM(ITE.CODIGO_ALTERNATIVO) AS ALTERNATIVO,
    ITE.CODIGO_REDUZIDO AS REDUZ,
    TRIM(ITE.DESCRICAO) AS DESCR_ITEM,
    UFA.CODIGO_UNIDADE_FABRI || ' - ' || TRIM(UFA.NOME_UNIDADE_FABRIL) AS UND_FABRIL,
    UFA.IDPESSOAFJ AS IDPESSOAFJ_UNIDADE,
    MAQ.TIPO_MAQUINA AS TP_MQ,
    LTRIM(MAQ.NUMERO_MAQUINA, 0) AS MQ,
    TRIM(MAQ.NOME_MAQUINA) AS NOME_MAQUINA,
    GPR.GRUPO AS GRUPO,
    GPR.DESCRICAO AS DESCR_GRUPO,
    CTT.CDCONTRATO,
    CTT.IDPESSOAFJ AS IDPESSOAFJ_CONTRATO,
    CTT.NOME_FORNECEDOR,
    CTT.SQITEMCONT,
    CTT.CDREDUZIDO,
    CTT.DESCR_ITEM_CTT,
    CTT.QTORIGINAL,
    CTT.IDFASEOB
FROM
    SGTPRD.ITENS_ESTOQUE ITE
JOIN SGTPRD.ENGEITEMESTOARTCRU  ART ON ART.CDREDUZIDO           = ITE.CODIGO_REDUZIDO
JOIN SGTPRD.GRUPO_PRODUTO       GPO ON GPO.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
JOIN SGTPRD.GRUPO_FLUXO         GF  ON GF.NUMERO_GRUPO_PROGRAM  = GPO.NUMERO_GRUPO_PROGRAM
JOIN SGTPRD.GRUPO_FLUXO_FASES   GFF ON GFF.IDGRUPOFLUXO         = GF.IDGRUPOFLUXO
JOIN SGTPRD.FLUXO_FASES         FFA ON FFA.CODIGO_FASE          = GFF.CODIGO_FASE   AND FFA.CODIGO_FLUXO = GF.CODIGO_FLUXO AND FFA.SEQUENCIA = GFF.SEQUENCIA
JOIN SGTPRD.FLUXO_FASE_MAQUINAS FFM ON FFM.CODIGO_FLUXO         = FFA.CODIGO_FLUXO  AND FFM.SEQUENCIA    = FFA.SEQUENCIA 
JOIN SGTPRD.MAQUINA             MAQ ON MAQ.NUMERO_MAQUINA       = FFM.NUMERO_MAQUINA
JOIN SGTPRD.GRUPO_MAQUINAS      GPR ON GPR.GRUPO                = MAQ.GRUPO         AND GPR.SETOR        = MAQ.SETOR
JOIN SGTPRD.UNIDADE_FABRIL      UFA ON UFA.CODIGO_UNIDADE_FABRI = GPR.UNIDADE_FABRIL
LEFT JOIN
    (
        SELECT
            CT.CDCONTRATO,
            CT.IDPESSOAFJ,
            TRIM(PJ.NOME) AS NOME_FORNECEDOR,
            CTI.SQITEMCONT,
            CTI.CDREDUZIDO,
            TRIM(ITE.DESCRICAO) AS DESCR_ITEM_CTT,
            CTI.QTORIGINAL,
            CTI.IDFASEOB
        FROM SGTPRD.SUPRCONTITEM     CTI
        JOIN SGTPRD.SUPRCONTITEMENTR CTE ON CTE.IDCONTITEM      = CTI.ID
        JOIN SGTPRD.SUPRCONTRATO     CT  ON CT.ID               = CTI.IDCONTRATO
        JOIN SGTPRD.PESSOASFJ        PJ  ON PJ.IDPESSOAFJ       = CT.IDPESSOAFJ
        JOIN SGTPRD.ITENS_ESTOQUE    ITE ON ITE.CODIGO_REDUZIDO = CTI.CDREDUZIDO
    ) CTT 
        ON CTT.CDREDUZIDO = ITE.CODIGO_REDUZIDO AND CTT.IDPESSOAFJ = UFA.IDPESSOAFJ
WHERE UFA.EH_FACCAO  = 'S'
AND   ITE.TIPO_ITEM  = 10
AND   GF.STATUS      IN (0, 1)
AND   UFA.IDPESSOAFJ = 8391
--AND TRIM(ART.CDARTIGOCRU) = '00056'
ORDER BY 12, 1;
