/* =============================================================================
OBJETIVO: Conferência de SKU TOTVS com composição detalhada
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: 06_qualidade_auditoria_obs/qld_conferencia_sku_totvs.sql (Query #3)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.CLASSIFICACAO_COR, SGTPRD.COML_GRUPOSPRECOSITE,
                     SGTPRD.COML_ITEMPORGRUPODEP, SGTPRD.COML_PRECOSARTIGOS,
                     SGTPRD.COML_TABELAPRECOS, SGTPRD.COML_TIPOSCOR,
                     SGTPRD.COR, SGTPRD.ENGEITEMARTIGOCRU,
                     SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTOCOR,
                     SGTPRD.ITENS_ESTOQUE, SGTPRD.TCLI_ITENS_TOTVS
CUIDADOS OPERACIONAIS: Consulta atômica somente leitura; o recorte da tabela
                        de preços é aplicado dentro da CTE de base.
REVISÃO (21/09/2026 - frente cirúrgica): composição de preço inlinada em
  tabelas-base; projeção e filtros de conferência mantidos.
============================================================================= */

WITH TAB_POR_ITEM AS (
    SELECT
        IGP.ITEM AS CD_REDUZIDO,
        PA.PRECO AS PR_TABELA
    FROM SGTPRD.COML_GRUPOSPRECOSITE GPI
    JOIN SGTPRD.COML_ITEMPORGRUPODEP IGP
      ON IGP.GRUPOPRECOSITEM = GPI.GRUPOPRECOSITEM
    JOIN SGTPRD.ITENS_ESTOQUE IE
      ON IE.CODIGO_REDUZIDO = IGP.ITEM
    JOIN SGTPRD.COML_PRECOSARTIGOS PA
      ON PA.GRUPOPRECOSITEM = GPI.GRUPOPRECOSITEM
    JOIN SGTPRD.COML_TABELAPRECOS TP
      ON TP.TABELAPRECO = PA.TABELAPRECO
    LEFT JOIN SGTPRD.TCLI_ITENS_TOTVS TT
      ON TT.CODIGO_REDUZIDO = IGP.ITEM
    WHERE TP.TABELAPRECO = 3002
)
SELECT ITE.CODIGO_REDUZIDO AS CD_REDUZIDO,
       TRIM(ENG.CDARTIGOCRU) AS CD_ARTIGO,
       TRIM(COR.DESCRICAO) AS DS_COR,
       TRIM(CCO.DESCRICAO) AS DS_CLASSIF_COR,
       TRIM(ITE.DESCRICAO) AS DS_PRODUTO,
       TCL.SKU_TOTVS AS CD_SKU_TOTVS,
       TAB.PR_TABELA
FROM SGTPRD.ITENS_ESTOQUE ITE
LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU ENG
  ON ENG.CDREDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.ENGEITEMARTIGOCRU ART
  ON ART.CDITEMARTIGOCRU = ENG.CDARTIGOCRU
LEFT JOIN SGTPRD.ENGEITEMESTOCOR ECO
  ON ECO.CDREDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.COR COR
  ON COR.CODIGO_COR = ECO.CDCOR
LEFT JOIN SGTPRD.CLASSIFICACAO_COR CCO
  ON CCO.CODIGO_CLASSIFICACAO = COR.CODIGO_CLASSIFICACAO
LEFT JOIN SGTPRD.COML_TIPOSCOR TCO
  ON TCO.TIPOCOR = COR.TIPOCOR
LEFT JOIN TAB_POR_ITEM TAB
  ON TAB.CD_REDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.TCLI_ITENS_TOTVS TCL
  ON TCL.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
WHERE ITE.INSUMO_COM_MOVIMENTO = '1'
  AND ITE.STATUS_ATIVACAO <> 1
  AND ITE.IDMASCARATIPOINSUMO IN ('BNF  ', 'BNR  ')
  AND TRIM(ENG.CDARTIGOCRU) NOT IN ('00000', 'OLINX')
ORDER BY ENG.CDREDUZIDO DESC, TRIM(ENG.CDARTIGOCRU), CCO.DESCRICAO;
