/* =============================================================================
OBJETIVO: Conferência de tubetes e plásticos por romaneio
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: 06_qualidade_auditoria_obs/qld_notas_fiscais_conferencia_tubetes_e_plasticos.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.BD_FAT_FATURAMENTO, SGTPRD.ITENS_ESTOQUE,
                     SGTPRD.NOTAFISCALCAPA, SGTPRD.NOTAFISCALITENS,
                     SGTPRD.PRODUTO_ROMANEIO, SGTPRD.TIPO_ACONDICIONAMENT,
                     SGTPRD.TTIPOACONITEMESTO, SGTPRD.UNIDADE_MEDIDA
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

WITH PECAS_ROMANEIO AS (
    SELECT GPEC.NUMERO_ROMANEIO_SAID AS NUMERO_ROMANEIO,
           GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
           GPP.IDACONDICIONAMENTO,
           COUNT(GPEC.IDPECASPRODUTO) AS NRO_PECAS
      FROM SGTPRD.GERAPECAROMSAIDA GPEC
      JOIN SGTPRD.GERAPECASPRODUTO GPP
        ON GPP.IDPECASPRODUTO = GPEC.IDPECASPRODUTO
     GROUP BY GPEC.NUMERO_ROMANEIO_SAID,
              GPP.CODIGO_REDUZIDO_PROD,
              GPP.IDACONDICIONAMENTO
), FATURAMENTO AS (
    SELECT VFA.FILIALNOTA AS FILIAL,
           VFA.NUMERONOTA AS NUMERO_NF,
           VFA.NUMERO_ROMANEIO,
           VFA.CODIGO_REDUZIDO AS REDUZ,
           TRIM(ITE.DESCRICAO) AS DESCR_ITEM,
           VFA.QUANT,
           PR.IDACONDICIONAMENTO,
           PR.NRO_PECAS,
           VFA.TIOPERNATUREZA,
           NSA.STNOTAFATURAMENTO AS STATUS_NF
      FROM SGTPRD.BD_FAT_FATURAMENTO VFA
      JOIN SGTPRD.NOTAFISCALITENS PNS
        ON PNS.ID = VFA.IDPNS
      JOIN SGTPRD.NOTAFISCALCAPA NSA
        ON NSA.ID = PNS.IDNOTAFISCALCAPA
      JOIN SGTPRD.PRODUTO_ROMANEIO PRO
        ON PRO.IDPRODUTO_ROMANEIO = VFA.IDPRODUTO_ROMANEIO
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = VFA.CODIGO_REDUZIDO
      JOIN PECAS_ROMANEIO PR
        ON PR.NUMERO_ROMANEIO = VFA.NUMERO_ROMANEIO
       AND PR.REDUZ = VFA.CODIGO_REDUZIDO
)
SELECT VPF.NUMERO_ROMANEIO,
       VPF.REDUZ,
       VPF.DESCR_ITEM,
       VPF.QUANT,
       VPF.NRO_PECAS,
       IAC.IDACONDICIONAMENTO,
       ACO.DESCRICAO AS DESCR_ACONDICIONAMENTO,
       ITE.DESCRICAO AS DESCR_ITEM_TUBETE,
       ACO.PESO,
       IAC.QUANTIDADE,
       IAC.QUANTIDADE * VPF.NRO_PECAS PLASTICO,
       UME.TPUNIDADEMEDIDA,
       UME.DSUNIDMED,
       (IAC.QUANTIDADE * VPF.NRO_PECAS) / VPF.NRO_PECAS MED_PLSTICO
  FROM FATURAMENTO                  VPF
  JOIN SGTPRD.TIPO_ACONDICIONAMENT   ACO
    ON ACO.IDACONDICIONAMENTO = VPF.IDACONDICIONAMENTO
  JOIN SGTPRD.TTIPOACONITEMESTO      IAC
    ON IAC.IDACONDICIONAMENTO = ACO.IDACONDICIONAMENTO
   AND IAC.CDREDUZIDO = VPF.REDUZ
  JOIN SGTPRD.ITENS_ESTOQUE           ITE
    ON ITE.CODIGO_REDUZIDO = IAC.CDREDUZIDO
  JOIN SGTPRD.UNIDADE_MEDIDA          UME
    ON UME.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
 WHERE IAC.IDACONDICIONAMENTO = ACO.IDACONDICIONAMENTO
   AND IAC.CDREDUZIDO = ITE.CODIGO_REDUZIDO
   AND UME.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
   AND UME.TPUNIDADEMEDIDA = 1
   AND VPF.FILIAL IN (1)
   AND VPF.TIOPERNATUREZA IN (2)
   AND VPF.STATUS_NF IN (3)
   AND VPF.NUMERO_NF IN (27659);
