/* =============================================================================
OBJETIVO: Conferência - Peças faturadas acima do padrão (ZIMMERMANN)
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Peças faturadas acima do padrão (ZIMMERMANN).sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAORIGEM, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.PECAS_ROMANEIO_SAIDA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT TRIM(ITE.CODIGO_ALTERNATIVO)                            ALTERNATIVO,
       TRIM(ITE.DESCRICAO)                                     DESCRICAO_ITEM,
       GPC.PESO_BRUTO,
       GPP.QTLIQUIDA,
       GPP.IDPECASPRODUTO,
       GPO.IDPECASPRODUTOORIGEM,
       GPD.NUMERO_OB,
       GPC.PESO_BRUTO - GPC.PESO_PECA                          ACOND,
       
       (SELECT GPCX.PESO_PECA
          FROM SGTPRD.GERAPECACOMPLPECA GPCX
         WHERE GPCX.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM) PESO_CRU,
         
       ((SELECT GPCX.PESO_PECA
           FROM SGTPRD.GERAPECACOMPLPECA GPCX
          WHERE GPCX.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM) - GPP.QTLIQUIDA) /
       (SELECT GPCX.PESO_PECA
          FROM SGTPRD.GERAPECACOMPLPECA GPCX
         WHERE GPCX.IDPECASPRODUTO = GPO.IDPECASPRODUTOORIGEM) PERC_QUEBRA
         
  FROM SGTPRD.GERAPECASPRODUTO     GPP,
       SGTPRD.GERAPECADESTINOOB    GPD,
       SGTPRD.PECAS_ROMANEIO_SAIDA PRS,
       SGTPRD.GERAPECACOMPLPECA    GPC,
       SGTPRD.ITENS_ESTOQUE        ITE,
       SGTPRD.GERAPECAORIGEM       GPO
 WHERE GPD.IDPECASPRODUTO       = GPP.IDPECASPRODUTO
   AND PRS.IDPECASPRODUTO       = GPP.IDPECASPRODUTO
   AND GPC.IDPECASPRODUTO       = GPP.IDPECASPRODUTO
   AND ITE.CODIGO_REDUZIDO      = GPP.CODIGO_REDUZIDO_PROD
   AND GPO.IDPECASPRODUTO       = GPP.IDPECASPRODUTO
   AND PRS.NUMERO_PEDIDO_COMERC = 6907
   AND ITE.LINHAPRODUTOCOMERCIA = 4
 ORDER BY 1 DESC
