/* =============================================================================
OBJETIVO: Conferência - Peças usadas atender pedido comercial (peças alocadas no pedido)
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Peças usadas atender pedido comercial (peças alocadas no pedido).sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMDATAS, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT GPA.NUMERO_OB,
       GPP.IDPECASPRODUTO,
       GPP.CODIGO_REDUZIDO_PROD,
       GPP.LOTE_PRODUTO,
       GPP.QTLIQUIDA,
       GPP.PADRAO_QUALIDADE_SIN,
       GPC.FINALIDADE,
       GPC.PESO_PECA,
       GPC.METROS_PECA
  FROM SGTPRD.GERAPECASPRODUTO  GPP,
       SGTPRD.GERAPECACOMPLPECA GPC,
       SGTPRD.GERAPECAORIGEMOB  GPA
 WHERE GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
   AND GPA.IDPECASPRODUTO = GPP.IDPECASPRODUTO
   AND GPP.CODIGO_REDUZIDO_PROD = 133
   AND GPP.PADRAO_QUALIDADE_SIN = 1
   AND GPP.LOTE_PRODUTO = 'MOLINARI  '
   AND GPA.NUMERO_OB IN
       (SELECT PPOB.NUMEROOB NR_OB
          FROM SGTPRD.OFPEDIDO OFP
         INNER JOIN SGTPRD.ITENSPEDIDOQTDES IPQ
            ON OFP.IDITENSPEDIDOQTDES = IPQ.IDITENSPEDIDOQTDES
         INNER JOIN SGTPRD.ITENSPEDIDOGRADE IPG
            ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
         INNER JOIN SGTPRD.OFORDENS OFO
            ON OFO.NUMEROOF = OFP.NUMEROOF
         INNER JOIN SGTPRD.PEDPRODUCAO PP
            ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
         INNER JOIN SGTPRD.PEDPRODUCAOOB PPOB
            ON PPOB.NUMERO = PP.NUMERO
         INNER JOIN SGTPRD.PEDIDOCOMDATAS PCD
            ON PCD.PEDIDO = IPG.PEDIDO
         INNER JOIN SGTPRD.PEDIDOCOMERCIAL PED
            ON PED.PEDIDO = IPG.PEDIDO
         INNER JOIN SGTPRD.ITENSPEDIDOCOMERCIAL ITP
            ON ITP.PEDIDO = IPG.PEDIDO
           AND ITP.ITEMPEDIDO = IPG.ITEMPEDIDO
           AND PCD.ITEMPEDIDO = IPG.ITEMPEDIDO
           AND PPOB.NUMERO = OFO.NUMEROPEDPRODUCAO
           AND OFP.NIVEL = OFO.NIVEL
           AND OFP.REDUZIDO = OFO.REDUZIDO
           AND IPG.PEDIDO = 7007)
