/* =============================================================================
OBJETIVO: OB_s com peso maior que a carga máquina
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s com peso maior que a carga máquina.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.FASES_FLUXO, SGTPRD.GRUPO_FLUXO, SGTPRD.GRUPO_FLUXO_FASES, SGTPRD.GRUPO_FLUXO_MAQUINAS, SGTPRD.GRUPO_PRODUTO, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
OTIMIZAÇÃO (20/09/2026): Eliminadas as views VW_BNF_FASEATUALOB e VW_ENU_STATUS_OB_FASES, substituídas por CTEs nativas e tabela de enumeração. Junções convertidas para padrão ANSI.
============================================================================= */

WITH FASE_ATUAL_CTE AS (
    SELECT
        OBF.NUMERO_OB,
        MIN(OBF.SEQUENCIA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS SEQUENCIA,
        MIN(OBF.NUMERO_MAQUINA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS NUMERO_MAQUINA,
        MIN(FFL.CODIGO_GRUPO) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS GRUPO_FASE,
        MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS DESCR_FASE,
        MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS STATUS
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    WHERE OBF.STATUS <> 4
    GROUP BY OBF.NUMERO_OB
),
PED_OB_CTE AS (
    SELECT
        PPOB.NUMEROOB AS NR_OB,
        IPG.PEDIDO AS NR_PEDIDO,
        IPG.ITEMPEDIDO AS ITEM_PEDIDO,
        TRIM(PED.PEDIDOCLIENTE) AS P_CLIENTE
    FROM SGTPRD.PEDPRODUCAOOB PPOB
    JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
)
SELECT ROUND((OP.KILOS - OBF.CARGA_MAXIMA) / OBF.CARGA_MAXIMA * 100, 2)         AS PERC_MQ,
       FA.NUMERO_OB                                                             AS NR_OB,
       PDC.NR_PEDIDO                                                            AS PEDIDO,
       PDC.P_CLIENTE                                                            AS PROGR,
       OP.CODPRO_REDUZIDO                                                       AS REDUZIDO,
       TRIM(ITE.DESCRICAO)                                                      AS DESCRIO_ITEM,
       OP.TOTAL_PECAS_CONFIRM                                                   AS PEAS_CONF,
       OP.KILOS_PROGRAMADOS                                                     AS KG_PROG,
       OP.KILOS                                                                 AS KG_CONF,
       NVL(OBF.CARGA_MAXIMA, GFM.CARGA_MAXIMA)                                  AS CARGA_MQ,
       OBF.NUMERO_MAQUINA                                                       AS MAQUINA,
       FA.DESCR_FASE                                                            AS DESCRIO_FASE,
       TRIM(ENI.DESCRIPTION)                                                    AS DESCRIO_ST,
       ROUND((OP.KILOS - OP.KILOS_PROGRAMADOS) / OP.KILOS_PROGRAMADOS * 100, 2) AS PERC_OB
  FROM FASE_ATUAL_CTE FA
 INNER JOIN SGTPRD.OB_PRODUTO OP
    ON OP.NUMERO_OB = FA.NUMERO_OB
 INNER JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON ITE.CODIGO_REDUZIDO = OP.CODPRO_REDUZIDO
 INNER JOIN SGTPRD.GRUPO_PRODUTO GP
    ON GP.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
 INNER JOIN SGTPRD.GRUPO_FLUXO GF
    ON GF.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
   AND GF.STATUS = 1
 INNER JOIN SGTPRD.GRUPO_FLUXO_FASES GFF
    ON GFF.IDGRUPOFLUXO = GF.IDGRUPOFLUXO
 INNER JOIN SGTPRD.GRUPO_FLUXO_MAQUINAS GFM
    ON GFM.IDGRUPOFLUXOFASE = GFF.IDGRUPOFLUXOFASE
   AND GFM.NUMERO_MAQUINA = FA.NUMERO_MAQUINA
 INNER JOIN SGTPRD.OB_FASES OBF
    ON OBF.NUMERO_OB = FA.NUMERO_OB
   AND OBF.DESTINO_RECEITA = 1
   AND OBF.NUMERO_MAQUINA LIKE '000000MQ%'
 INNER JOIN PED_OB_CTE PDC
    ON PDC.NR_OB = FA.NUMERO_OB
  LEFT JOIN SGTPRD.XX2_ENUMERATES ENU
    ON ENU.NAME LIKE 'TOBFASESSTATUS%'
  LEFT JOIN SGTPRD.XX2_ENUMITEM ENI
    ON ENI.IDENUMERATE = ENU.ID
   AND ENI.SEQUENCE = FA.STATUS
 WHERE FA.GRUPO_FASE IN (1, 2)
   AND OP.KILOS_PROGRAMADOS < OP.KILOS
   AND ROUND((OP.KILOS - OBF.CARGA_MAXIMA) / OBF.CARGA_MAXIMA * 100, 2) > 4
 ORDER BY ROUND((OP.KILOS - OBF.CARGA_MAXIMA) / OBF.CARGA_MAXIMA * 100, 2) DESC;
