/* =============================================================================
OBJETIVO: Testes de qualidade laboratoriais por OB e lote
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: 06_qualidade_auditoria_obs/qld_conferencia_testes_de_qualidade.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.ITENS_ESTOQUE, SGTPRD.LABOGRUPOPADROESQUAL, SGTPRD.LABOPADROESPRODUTO, SGTPRD.LABOPADROESQUALIDADE
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT --(SELECT ITE.CODIGO FROM SGTPRD.ITENS_ESTOQUE ITE WHERE ITE.CODIGO_REDUZIDO = LBP.CODIGO_REDUZIDO) CODIGO,
       DECODE(LPQ.IDITEMTESTE,1, 'GRAMATURA',8,'LARGURA ACABADA') TESTE,
       LPQ.VALOR_PADRAO_GRAFICO,
       LPQ.VALOR_PADRAO_MAXIMO,
       LPQ.VALOR_PADRAO_MINIMO
  FROM SGTPRD.LABOGRUPOPADROESQUAL GRP,
       SGTPRD.LABOPADROESQUALIDADE LPQ,
       SGTPRD.LABOPADROESPRODUTO   LBP
 WHERE LPQ.IDLABOGRUPOPADROESQU = GRP.IDLABOGRUPOPADROESQU
   AND LBP.IDLABOGRUPOPADROESQU = LPQ.IDLABOGRUPOPADROESQU
   AND TRIM(GRP.CDITEMARTIGOCRU) = '00187'
   AND LPQ.IDITEMTESTE IN (1, 8)
 GROUP BY --LBP.CODIGO_REDUZIDO,
          LPQ.IDITEMTESTE,
          LPQ.VALOR_PADRAO_GRAFICO,
          LPQ.VALOR_PADRAO_MAXIMO,
          LPQ.VALOR_PADRAO_MINIMO
 ORDER BY 2,3;
