/* =============================================================================
OBJETIVO: Conferência - OB montada (status peça e OB_s alocadas, por NF)
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - OB montada (status peça e OB_s alocadas, por NF).sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECANOTAENTRADA, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.OB, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
OTIMIZAÇÃO (20/09/2026): Views VW_ENU_PECAS_STPECAPRODUTO e VW_ESP_OBPEDIDO substituídas por tabelas físicas nativas indexadas.
============================================================================= */

WITH PED_OB_CTE AS (
    SELECT
        PPOB.NUMEROOB AS NUMEROOB,
        IPG.PEDIDO AS PEDIDO,
        TRIM(PED.PEDIDOCLIENTE) AS PEDIDOCLIENTE,
        OB.STATUS AS STATUS_OB
    FROM SGTPRD.PEDPRODUCAOOB PPOB
    JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = OFP.IDITENSPEDIDOQTDES
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
    LEFT JOIN SGTPRD.OB OB ON OB.NUMERO_OB = PPOB.NUMEROOB
    GROUP BY PPOB.NUMEROOB, IPG.PEDIDO, TRIM(PED.PEDIDOCLIENTE), OB.STATUS
)
SELECT
    COUNT(GPP.IDPECASPRODUTO) AS QT_PECAS,
    TRIM(ENI.DESCRIPTION) AS STATUS_PECA,
    GPO.NUMERO_OB,
    GPP.CODIGO_DEPOSITO,
    OBP.PEDIDO,
    OBP.PEDIDOCLIENTE AS PROGRAMACAO,
    OBP.STATUS_OB
FROM SGTPRD.GERAPECASPRODUTO         GPP
     JOIN SGTPRD.GERAPECAORIGEMOB    GPO ON GPO.IDPECASPRODUTO = GPP.IDPECASPRODUTO
     JOIN SGTPRD.GERAPECANOTAENTRADA GPN ON GPN.IDPECASPRODUTO = GPP.IDPECASPRODUTO
LEFT JOIN SGTPRD.XX2_ENUMERATES ENU ON ENU.NAME LIKE 'TSTATUSPECAPRODUTO%'
LEFT JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID AND ENI.SEQUENCE = GPP.STPECAPRODUTO
LEFT JOIN PED_OB_CTE OBP ON OBP.NUMEROOB = GPO.NUMERO_OB
WHERE GPN.NUMERO_NOTA = 3571
GROUP BY
    TRIM(ENI.DESCRIPTION),
    GPO.NUMERO_OB,
    GPP.CODIGO_DEPOSITO,
    OBP.PEDIDO,
    OBP.PEDIDOCLIENTE,
    OBP.STATUS_OB
ORDER BY GPO.NUMERO_OB;
