/* =============================================================================
OBJETIVO: Conferência - Composição (acabado x cru)
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Composição (acabado x cru).sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.COMPOSICAO_FIBRAS, SGTPRD.COMPOSICAO_ITEM, SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ITENS_COMPLEMENTO, SGTPRD.ITENS_DESCENDENCIA, SGTPRD.ITENS_ESTOQUE
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT 
    (SELECT TRIM(ART.CDARTIGOCRU) 
     FROM SGTPRD.ENGEITEMESTOARTCRU ART
     WHERE ART.CDREDUZIDO = DES.CODIGO_REDUZIDO) AS ARTIGO,

    (SELECT TRIM(ITEX.DESCRICAO)
     FROM SGTPRD.ITENS_ESTOQUE ITEX
     WHERE DES.CODIGO_REDUZIDO_DESC = ITEX.CODIGO_REDUZIDO) AS DESCR_CRU,

    DES.CODIGO_REDUZIDO AS REDZ_ACABADO,
    TRIM(ITE.DESCRICAO) AS DESCRICAO,
    TRIM(ITE.NOME_DETALHADO1) AS NOME_DETALHADO1,
    ITC.LARGURA AS LARGURA_ACABADO,

    (SELECT ITCX.LARGURA
     FROM SGTPRD.ITENS_COMPLEMENTO ITCX
     WHERE ITCX.CODIGO_REDUZIDO = DES.CODIGO_REDUZIDO_DESC) AS LARGURA_CRU,

    ITC.RENDIMENTOACABADO,
    ITC.GRAMATURA,
    LISTAGG(CPS.COMPOSICAO || '% ' || TRIM(CPF.DESCRICAO), '; ') WITHIN GROUP (ORDER BY CPS.COMPOSICAO DESC) AS COMPOSICAO_ACABADO,

    (SELECT LISTAGG(CPSX.COMPOSICAO || '% ' || TRIM(CPFX.DESCRICAO), '; ') WITHIN GROUP (ORDER BY CPSX.COMPOSICAO DESC)
     FROM SGTPRD.COMPOSICAO_ITEM CPSX
     JOIN SGTPRD.COMPOSICAO_FIBRAS CPFX ON CPFX.CODIGO = CPSX.CODIGO_DA_COMPOSICAO
     WHERE CPSX.CODIGO_REDUZIDO = DES.CODIGO_REDUZIDO_DESC) AS COMPOSICAO_CRU

FROM SGTPRD.ITENS_DESCENDENCIA DES
   JOIN SGTPRD.ITENS_ESTOQUE ITE ON DES.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   JOIN SGTPRD.ITENS_COMPLEMENTO ITC ON ITC.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   JOIN SGTPRD.COMPOSICAO_ITEM CPS ON CPS.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   JOIN SGTPRD.COMPOSICAO_FIBRAS CPF ON CPF.CODIGO = CPS.CODIGO_DA_COMPOSICAO
-- WHERE DES.CODIGO_REDUZIDO_DESC = 9320
GROUP BY DES.CODIGO_REDUZIDO, ITE.DESCRICAO, ITE.NOME_DETALHADO1, ITC.LARGURA, ITC.RENDIMENTOACABADO, ITC.GRAMATURA, DES.CODIGO_REDUZIDO_DESC;
