/* =============================================================================
OBJETIVO: Conferência - Reduzidos que faltam SKU
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Reduzidos que faltam SKU.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.CLASSIFICACAO_COR, SGTPRD.COLECOES,
                     SGTPRD.COML_TIPOSCOR, SGTPRD.COR,
                     SGTPRD.ENGEITEMARTIGOCRU, SGTPRD.ENGEITEMESTOARTCRU,
                     SGTPRD.ENGEITEMESTOCOR, SGTPRD.ITENS_ESTOQUE,
                     SGTPRD.LINHA_PRODUTO, SGTPRD.TCLI_ITENS_TOTVS
CUIDADOS OPERACIONAIS: Consulta somente leitura; as descrições e códigos
                        comerciais são compostos diretamente das tabelas-base.
REVISÃO (21/09/2026 - frente cirúrgica): composição inlinada em tabelas;
  projeção e filtros de conferência mantidos.
============================================================================= */

SELECT
    T.CODIGO_REDUZIDO,
    T.SKU_TOTVS,
    ITE.CODIGO_REDUZIDO AS COD_REDUZ,
    ITE.DESCRICAO AS DESCR_PRODUTO,
    ITE.REDUZIDOFIGURA,
    LP.CODIGOLINHA AS COD_LINHA_PRODUTO,
    LP.DESCRICAOLINHA AS DESCR_LINHA_PRODUTO,
    CO.ID_COLECAO AS IDCOLECAO,
    CO.NOME AS DESCR_COLECAO,
    TRIM(ITE.IDMASCARATIPOINSUMO) AS IDMASCARA,
    SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 6) AS COD_ARTIGO,
    SUBSTR(ITE.CODIGO, 1, 3) || '.' || SUBSTR(ITE.CODIGO, 4, 6) || '.' ||
        SUBSTR(ITE.CODIGO, 10, 2) AS COD_ARTIGO_VAR,
    ART.DSITEMARTIGOCRU AS DESCR_ARTIGO,
    TRIM(COR.CODIGO_COR) AS COD_COR,
    TC.DESCRICAO AS DESCR_TIPOCOR,
    COR.DESCRICAO AS DESCR_COR,
    COR.CODIGO_RGB,
    ITE.CODIGO_ALTERNATIVO,
    SUBSTR(ITE.CODIGO, 1, 3) || '.' ||
        SUBSTR(ITE.CODIGO, 4, 6) ||
        SUBSTR(ITE.CODIGO, 10, 2) || '.' ||
        SUBSTR(ITE.CODIGO, 12, 3) || '.' ||
        SUBSTR(ITE.CODIGO, 15, 5) || '.' ||
        SUBSTR(ITE.CODIGO, 20, 5) || '.' ||
        SUBSTR(ITE.CODIGO, 25, 3) || '.' ||
        SUBSTR(ITE.CODIGO, 28, 3) AS COD_COMERCIAL
FROM SGTPRD.TCLI_ITENS_TOTVS T
JOIN SGTPRD.ITENS_ESTOQUE ITE
  ON ITE.CODIGO_REDUZIDO = T.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU ENG
  ON ENG.CDREDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.ENGEITEMARTIGOCRU ART
  ON ART.CDITEMARTIGOCRU = ENG.CDARTIGOCRU
LEFT JOIN SGTPRD.ENGEITEMESTOCOR ECO
  ON ECO.CDREDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.COR COR
  ON COR.CODIGO_COR = ECO.CDCOR
LEFT JOIN SGTPRD.LINHA_PRODUTO LP
  ON LP.CODIGOLINHA = ITE.LINHA_PRODUTO
LEFT JOIN SGTPRD.COML_TIPOSCOR TC
  ON TC.TIPOCOR = COR.TIPOCOR
LEFT JOIN SGTPRD.COLECOES CO
  ON CO.COLECAO = ITE.COLECAO
WHERE ITE.TIPO_ITEM = 10
  AND TRIM(ITE.IDMASCARATIPOINSUMO) = 'BNF'
  AND T.SKU_TOTVS = 0
ORDER BY T.CODIGO_REDUZIDO DESC;
