/* =============================================================================
OBJETIVO: Auditoria e Investigação de Coerência dos Cadastros de Máquinas e Famílias
DOMÍNIO: 06_qualidade_auditoria_obs
ARQUIVO ORIGINAL: qld_auditoria_cadastros_maquinas_familias.sql
TIPO: Auditoria e Qualidade de OBs
PARÂMETROS / BINDS: Nenhum (auditoria global multi-setorial)
TABELAS PRINCIPAIS: SGTPRD.MAQUINA, SGTPRD.FAMILIA_MAQUINA, SGTPRD.GRUPO_MAQUINAS,
                    SGTPRD.TIPOSMAQUINAS, SGTPRD.UNIDADE_FABRIL, SGTPRD.SECAO
CUIDADOS OPERACIONAIS: Consulta somente leitura de cobertura integral. Realiza
                       FULL OUTER JOIN entre MAQUINA e FAMILIA_MAQUINA para
                       identificar tanto máquinas órfãs/sem família quanto famílias
                       sem máquinas no chão de fábrica.
============================================================================= */

WITH FAM_METRICAS AS (
    SELECT M.ID_FAMILIA_MAQUINA,
           COUNT(*) AS QTD_MAQUINAS_FAMILIA,
           COUNT(DISTINCT M.SETOR) AS QTD_SETORES_FAMILIA,
           MIN(M.CARGA_MAXIMA) AS MIN_CARGA_FAMILIA,
           MAX(M.CARGA_MAXIMA) AS MAX_CARGA_FAMILIA
      FROM SGTPRD.MAQUINA M
     WHERE M.ID_FAMILIA_MAQUINA > 0
     GROUP BY M.ID_FAMILIA_MAQUINA
),
PATR_DUPLICADOS AS (
    SELECT TRIM(M.NUMERO_PATRIMONIO) AS NUMERO_PATRIMONIO,
           COUNT(*) AS QTD_MAQUINAS
      FROM SGTPRD.MAQUINA M
     WHERE M.NUMERO_PATRIMONIO IS NOT NULL
       AND TRIM(M.NUMERO_PATRIMONIO) NOT IN ('0', '-', '.')
     GROUP BY TRIM(M.NUMERO_PATRIMONIO)
    HAVING COUNT(*) > 1
)
SELECT CASE
         WHEN M.NUMERO_MAQUINA IS NULL THEN 'INCONSISTENTE'
         WHEN M.ID_FAMILIA_MAQUINA = 0 OR FM.ID_FAMILIA IS NULL THEN 'INCONSISTENTE'
         WHEN M.CARGA_MINIMA > M.CARGA_MAXIMA THEN 'INCONSISTENTE'
         WHEN PD.QTD_MAQUINAS > 1 THEN 'INCONSISTENTE'
         WHEN TM.SETOR IS NOT NULL AND TM.SETOR <> M.SETOR THEN 'INCONSISTENTE'
         WHEN M.SETOR = 5 AND TRIM(TM.DESCRICAO) IN ('Flow', 'Jet') AND NVL(M.CARGA_MAXIMA, 0) <= 0 THEN 'INCONSISTENTE'
         WHEN FMET.QTD_SETORES_FAMILIA > 1 THEN 'ALERTA'
         WHEN FMET.MAX_CARGA_FAMILIA > 0 AND (FMET.MAX_CARGA_FAMILIA - FMET.MIN_CARGA_FAMILIA) > 500 THEN 'ALERTA'
         WHEN M.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN 'ALERTA'
         ELSE 'CONFORME'
       END AS STATUS_COERENCIA,
       CASE
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.MAQUINA_ATIVA = '1' AND (M.ID_FAMILIA_MAQUINA = 0 OR M.ID_FAMILIA_MAQUINA IS NULL OR FM.ID_FAMILIA IS NULL) THEN 'CRITICA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.CARGA_MINIMA > M.CARGA_MAXIMA THEN 'CRITICA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.MAQUINA_ATIVA = '1' AND PD.QTD_MAQUINAS > 1 THEN 'CRITICA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.MAQUINA_ATIVA = '1' AND M.SETOR = 5 AND TRIM(TM.DESCRICAO) IN ('Flow', 'Jet') AND NVL(M.CARGA_MAXIMA, 0) <= 0 THEN 'CRITICA'
         WHEN M.NUMERO_MAQUINA IS NULL THEN 'MEDIA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND (M.ID_FAMILIA_MAQUINA = 0 OR M.ID_FAMILIA_MAQUINA IS NULL) THEN 'MEDIA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND TM.SETOR IS NOT NULL AND TM.SETOR <> M.SETOR THEN 'MEDIA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.SETOR = 5 AND TRIM(TM.DESCRICAO) IN ('Flow', 'Jet') AND NVL(M.CARGA_MAXIMA, 0) <= 0 THEN 'MEDIA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND FMET.QTD_SETORES_FAMILIA > 1 THEN 'BAIXA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND PD.QTD_MAQUINAS > 1 THEN 'BAIXA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND FMET.MAX_CARGA_FAMILIA > 0 AND (FMET.MAX_CARGA_FAMILIA - FMET.MIN_CARGA_FAMILIA) > 500 THEN 'BAIXA'
         WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN 'BAIXA'
         ELSE 'OK'
       END AS GRAVIDADE,
       CASE
         WHEN M.NUMERO_MAQUINA IS NULL THEN 'FAMILIA_ORFA'
         WHEN FM.ID_FAMILIA IS NULL OR M.ID_FAMILIA_MAQUINA = 0 THEN 'MAQUINA_SEM_FAMILIA'
         ELSE 'MAQUINA_VINCULADA'
       END AS TIPO_REGISTRO,
       NVL(
         RTRIM(
           CASE WHEN M.NUMERO_MAQUINA IS NULL THEN '[FAMILIA_SEM_MAQUINAS_VINCULADAS] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND (M.ID_FAMILIA_MAQUINA = 0 OR M.ID_FAMILIA_MAQUINA IS NULL) THEN '[MAQUINA_SEM_FAMILIA] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.ID_FAMILIA_MAQUINA > 0 AND FM.ID_FAMILIA IS NULL THEN '[FAMILIA_INEXISTENTE_FK_ORFA] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.GRUPO IS NOT NULL AND GPR.GRUPO IS NULL THEN '[GRUPO_INEXISTENTE_NO_SETOR] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.IDTIPOSMAQUINA IS NOT NULL AND TM.IDTIPOSMAQUINA IS NULL THEN '[TIPO_MAQUINA_INEXISTENTE] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND TM.SETOR IS NOT NULL AND TM.SETOR <> M.SETOR THEN '[SETOR_DIVERGENTE_MAQ_X_TIPO] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.CARGA_MINIMA > M.CARGA_MAXIMA THEN '[CARGA_MIN_MAIOR_QUE_MAX] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.SETOR = 5 AND TRIM(TM.DESCRICAO) IN ('Flow', 'Jet') AND NVL(M.CARGA_MAXIMA, 0) <= 0 THEN '[BNF_TINGIMENTO_SEM_CARGA_MAX] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND PD.QTD_MAQUINAS > 1 THEN '[PATRIMONIO_DUPLICADO] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND FMET.QTD_SETORES_FAMILIA > 1 THEN '[FAMILIA_MULTISETOR] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND FMET.MAX_CARGA_FAMILIA > 0 AND (FMET.MAX_CARGA_FAMILIA - FMET.MIN_CARGA_FAMILIA) > 500 THEN '[DISPERSAO_CARGA_FAMILIA] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND M.SECAO IS NOT NULL AND SEC.SECAO IS NULL THEN '[SECAO_INEXISTENTE_NO_CADASTRO] ' END ||
           CASE WHEN M.NUMERO_MAQUINA IS NOT NULL AND (M.NOME_MAQUINA IS NULL OR TRIM(M.NOME_MAQUINA) IS NULL) THEN '[NOME_MAQUINA_EM_BRANCO] ' END
         ),
         '[CADASTRO_CONFORME]'
       ) AS MOTIVOS_INCONSISTENCIA,
       M.SETOR AS SETOR_COD,
       CASE M.SETOR
         WHEN 1 THEN 'Algodão'
         WHEN 2 THEN 'Fiação'
         WHEN 3 THEN 'Tecelagem'
         WHEN 4 THEN 'Malharia Circular'
         WHEN 5 THEN 'Beneficiamento'
         WHEN 6 THEN 'Acabamento'
         WHEN 7 THEN 'Malharia Retilínea'
         WHEN 8 THEN 'Bordado'
         WHEN 9 THEN 'Confecção'
         WHEN 10 THEN 'Laboratório'
         ELSE CASE WHEN M.NUMERO_MAQUINA IS NULL THEN 'Não Definido (Família Órfã)' ELSE 'Setor ' || TO_CHAR(M.SETOR) END
       END AS SETOR_NOME,
       LTRIM(M.NUMERO_MAQUINA, '0') AS NUMERO_MAQUINA,
       M.NUMERO_MAQUINA AS CODIGO_MAQUINA_RAW,
       TRIM(M.NOME_MAQUINA) AS NOME_MAQUINA,
       CASE WHEN M.MAQUINA_ATIVA = '1' THEN 'SIM' WHEN M.NUMERO_MAQUINA IS NULL THEN '-' ELSE 'NAO' END AS MAQUINA_ATIVA,
       NVL(FM.ID_FAMILIA, M.ID_FAMILIA_MAQUINA) AS ID_FAMILIA,
       TRIM(FM.COD_FAMILIA) AS COD_FAMILIA,
       TRIM(FM.DESCRICAO) AS DESCR_FAMILIA,
       NVL(FMET.QTD_MAQUINAS_FAMILIA, 0) AS QTD_MAQS_NA_FAMILIA,
       FMET.MIN_CARGA_FAMILIA,
       FMET.MAX_CARGA_FAMILIA,
       M.GRUPO AS GRUPO_COD,
       TRIM(GPR.DESCRICAO) AS DESCR_GRUPO,
       M.IDTIPOSMAQUINA AS TIPO_MAQUINA_COD,
       TRIM(TM.DESCRICAO) AS DESCR_TIPO_MAQUINA,
       M.CARGA_MINIMA,
       M.CARGA_MAXIMA,
       M.VELOCIDADE_MAQUINA AS VELOCIDADE,
       M.PERC_EFICIENCIA AS EFICIENCIA,
       M.CDFILIAL AS FILIAL,
       LTRIM(M.CODIGO_UNIDADE_FABRI, '0') AS UNIDADE_FABRIL,
       TRIM(UFA.NOME_UNIDADE_FABRIL) AS NOME_UNIDADE_FABRIL,
       M.SECAO,
       TRIM(SEC.DESSEC) AS NOME_SECAO,
       TRIM(M.NUMERO_PATRIMONIO) AS NUMERO_PATRIMONIO,
       TRIM(M.NUMERO_SERIE) AS NUMERO_SERIE
  FROM SGTPRD.MAQUINA M
  FULL OUTER JOIN SGTPRD.FAMILIA_MAQUINA FM
    ON FM.ID_FAMILIA = M.ID_FAMILIA_MAQUINA
   AND M.ID_FAMILIA_MAQUINA <> 0
  LEFT JOIN SGTPRD.GRUPO_MAQUINAS GPR
    ON GPR.SETOR = M.SETOR
   AND GPR.GRUPO = M.GRUPO
  LEFT JOIN SGTPRD.TIPOSMAQUINAS TM
    ON TM.IDTIPOSMAQUINA = M.IDTIPOSMAQUINA
  LEFT JOIN SGTPRD.UNIDADE_FABRIL UFA
    ON UFA.CODIGO_UNIDADE_FABRI = M.CODIGO_UNIDADE_FABRI
  LEFT JOIN SGTPRD.SECAO SEC
    ON SEC.SECAO = M.SECAO
   AND SEC.CDFILIAL = M.CDFILIAL
  LEFT JOIN FAM_METRICAS FMET
    ON FMET.ID_FAMILIA_MAQUINA = FM.ID_FAMILIA
  LEFT JOIN PATR_DUPLICADOS PD
    ON PD.NUMERO_PATRIMONIO = TRIM(M.NUMERO_PATRIMONIO)
 ORDER BY CASE STATUS_COERENCIA WHEN 'INCONSISTENTE' THEN 1 WHEN 'ALERTA' THEN 2 ELSE 3 END,
          CASE GRAVIDADE WHEN 'CRITICA' THEN 1 WHEN 'MEDIA' THEN 2 WHEN 'BAIXA' THEN 3 ELSE 4 END,
          SETOR_COD NULLS LAST,
          NUMERO_MAQUINA NULLS LAST,
          ID_FAMILIA
