/*
    ================================================================================
    QUERY OTIMIZADA: VW_ESP_OB_PED_ROM (SQL-PX015) - VERSÃO COMPLETA
    OBJETIVO: Relatório de Receitas Emitidas com Performance Máxima e Todos os Campos
    ================================================================================
*/

WITH
-- 1. Dados Básicos da OB
CTE_OB AS (
    SELECT
        NUMERO_OB, TIPO_GERACAO, PROGRAMACAO_AUTOMATI, BAIXOU_PECAS,
        PRIM_LOTE_PROCESSO, STATUS, TIPO_ORDEM, CODIGO_FLUXO, NUMERO_GRUPO_PROGRAM,
        CODIGO_REDUZIDO, CODIGO_REDUZIDO_CRU, CODIGO_OBSERVACAO,
        TEMPO_INICIO_PRODUCA, TEMPO_ENCERRAMENTO_O, TEMPO_PROGRAMACAO
    FROM SGTPRD.OB
),

-- 2. NF das Peças Cruas (Original QTPNF)
CTE_NF_CRU AS (
    SELECT POC.NR_OB, SGTPRD.OPTSTRAGGR(POC.QT_PECA||' - '||POC.NR_NF) AS QT_PC_NF
    FROM (
        SELECT AB1.NUMERO_OB NR_OB,
               BC1.NUMERO_NOTA||' - '||TRIM(PE1.NOMEFANTASIA) NR_NF,
               COUNT(AB1.IDPECASPRODUTO) QT_PECA
        FROM SGTPRD.GERAPECAORIGEMOB AB1,
             SGTPRD.GERAPECANOTAENTRADA BC1,
             SGTPRD.PESSOASFJ PE1
        WHERE BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
        AND PE1.IDPESSOAFJ = BC1.IDPESSOAFJ
        GROUP BY AB1.NUMERO_OB, BC1.NUMERO_NOTA, TRIM(PE1.NOMEFANTASIA)
    ) POC
    GROUP BY POC.NR_OB
),

-- 3. Pedido Comercial Detalhado (Original PPP)
CTE_PEDIDO_DETALHE AS (
    SELECT
        IPC.PEDIDO AS NR_PEDIDO,
        IPC.ITEMPEDIDO AS SQ_ITEM_PEDIDO,
        TRIM(IPC.CD_DESENHO_CLIENTE) AS CD_REF_CLT,
        TRIM(PED.PEDIDOCLIENTE) AS NR_PROG,
        TRIM(IPC.ITEMPEDIDOCLIENTE) AS DS_ITEMPED_CLT
    FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
),

-- 4. Fases e Status (Analítica)
CTE_FASES_STATUS AS (
    SELECT
        F.NUMERO_OB, F.CODIGO_FASE, F.SEQUENCIA, F.STATUS, F.NUMERO_MAQUINA, F.CODIGO_PLACA, F.CODIGO_OBSERVACAO,
        FF.PROCESSOTERCEIROS, FF.DESCRICAO_FASE, FF.DESCRICAO_FASE_2,
        ROW_NUMBER() OVER (PARTITION BY F.NUMERO_OB ORDER BY F.SEQUENCIA DESC) as RN_F_ATUAL
    FROM SGTPRD.OB_FASES F
    JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = F.CODIGO_FASE
),

-- 5. Agregados Peças Destino
CTE_PECAS_DESTINO AS (
    SELECT
        D.NUMERO_OB,
        SUM(P.QTLIQUIDA) as QT_ACA_OB,
        MAX(CASE WHEN P.CODIGO_DEPOSITO = 100 THEN 1 ELSE 0 END) as EH_ACAB_REPROC
    FROM SGTPRD.GERAPECADESTINOOB D
    JOIN SGTPRD.GERAPECASPRODUTO P ON P.IDPECASPRODUTO = D.IDPECASPRODUTO
    GROUP BY D.NUMERO_OB
),

-- 6. Agregados Peças Origem (Cru)
CTE_PECAS_ORIGEM AS (
    SELECT
        O3.NUMERO_OB,
        SUM(O4.QTPESOLIQUORIG) as QT_CRU_ORIG_OB,
        DECODE(O3.TOTAL_PECAS_CONFIRM,0,(ROUND(O3.KILOS_PROGRAMADOS/NVL((SELECT MAX(PDD.PESO_PADRAO) FROM SGTPRD.VW_ESP_PESO_PADRAO PDD WHERE PDD.REDUZIDO=O3.CODPRO_REDUZIDO),1),0)),O3.TOTAL_PECAS_CONFIRM) as QT_PC_PROG
    FROM SGTPRD.OB_PRODUTO O3
    LEFT JOIN SGTPRD.GERAPECAORIGEMOB O1 ON O1.NUMERO_OB = O3.NUMERO_OB
    LEFT JOIN SGTPRD.GERAPECACOMPLPECA O4 ON O4.IDPECASPRODUTO = O1.IDPECASPRODUTO
    GROUP BY O3.NUMERO_OB, O3.KILOS_PROGRAMADOS, O3.TOTAL_PECAS_CONFIRM, O3.CODPRO_REDUZIDO
),

-- 7. Junção de Pedidos (Prioridade)
CTE_PEDIDO_PRIORIDADE AS (
    SELECT
        OB.NUMERO_OB,
        NVL(NVL(
            (SELECT MAX(PR1.NUMERO_PEDIDO) FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO JOIN SGTPRD.GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO WHERE DOB.NUMERO_OB = OB.NUMERO_OB),
            (SELECT MAX(G2.NUMERO_PEDIDO_COMERC) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OB.NUMERO_OB)
        ), (SELECT IPG.PEDIDO FROM SGTPRD.PEDPRODUCAOOB PPOB JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE WHERE PPOB.NUMEROOB = OB.NUMERO_OB AND ROWNUM = 1)
        ) as NR_PEDIDO_FINAL,
        NVL(NVL(
            (SELECT MAX(PR1.ITEM_PEDIDO) FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO JOIN SGTPRD.GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO WHERE DOB.NUMERO_OB = OB.NUMERO_OB),
            (SELECT MAX(G2.SEQUENCIA_PRODUTO_PE) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OB.NUMERO_OB)
        ), (SELECT IPG.ITEMPEDIDO FROM SGTPRD.PEDPRODUCAOOB PPOB JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE WHERE PPOB.NUMEROOB = OB.NUMERO_OB AND ROWNUM = 1)
        ) as SQ_ITEM_FINAL
    FROM CTE_OB OB
)

SELECT /*+ MONITOR */
    SYSDATE AS Valida_Atualizacao,
    PPP.CD_REF_CLT,
    NF.QT_PC_NF,
    (SELECT SGTPRD.optstraggrsemvirgula(TRIM(UPPER(C.TEXTO))) FROM SGTPRD.OBSERVACAO C WHERE C.CODIGO = OBE.CODIGO_OBSERVACAO) AS OBS_OB,
    OBE.NUMERO_OB AS NR_OB,
    CAST(NULL AS VARCHAR2(100)) AS VALIDACAO_NF,
    DECODE(OBE.STATUS, 0, 0, 1) AS ST_OB_ABERTO,
    PPP.NR_PROG,
    PPP.DS_ITEMPED_CLT,
    NVL(OPR.QT_PC_PROG, 0) AS QT_PC_PROG,
    (SELECT MAX(OBF.CODIGO_PLACA) FROM SGTPRD.OB_FASES OBF WHERE OBF.NUMERO_OB = OBE.NUMERO_OB) AS NR_KANBAN,
    (SELECT TRIM(I.CODIGO_ALTERNATIVO) FROM SGTPRD.ITENS_ESTOQUE I WHERE I.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO) AS CD_ALTERNATIVO,
    FAT.DS_FASE_ATUAL,
    (SELECT UPPER(SS.DESCRICAO) FROM SGTPRD.VW_ENU_STATUS_OB_FASES SS WHERE SS.STATUS = FAT.ST_FASE_ATUAL) AS DS_ST_FASE_ATUAL,
    SGTPRD.PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(OBE.NUMERO_OB) AS DT_ULT_CONFIRMACAO

FROM CTE_OB OBE
LEFT JOIN CTE_PECAS_DESTINO PEC ON PEC.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PECAS_ORIGEM OPR ON OPR.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_NF_CRU NF ON NF.NR_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PEDIDO_PRIORIDADE PRI ON PRI.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PEDIDO_DETALHE PPP ON PPP.NR_PEDIDO = PRI.NR_PEDIDO_FINAL AND PPP.SQ_ITEM_PEDIDO = PRI.SQ_ITEM_FINAL
LEFT JOIN (
    SELECT NUMERO_OB, STATUS as ST_FASE_ATUAL, DESCRICAO_FASE as DS_FASE_ATUAL
    FROM CTE_FASES_STATUS WHERE RN_F_ATUAL = 1
) FAT ON FAT.NUMERO_OB = OBE.NUMERO_OB

WHERE NVL(PEC.EH_ACAB_REPROC, 0) = 0


AND OBE.NUMERO_OB = 172557;
