/*
================================================================================
QUERY OTIMIZADA FINAL: Relatório de Receitas Emitidas (Ref: SQL-PX015)
ESTRATÉGIA: Arquitetura de CTEs para Performance Máxima e Fidelidade Total
OBJETIVO: Identidade Funcional de 100% dos campos com otimização corporativa
================================================================================
*/

WITH
-- 1. Dados Base da OB e Item (Driving Table)
CTE_OB AS (
    SELECT /*+ MATERIALIZE */
        OB.NUMERO_OB, OB.STATUS, OB.TIPO_ORDEM, OB.CODIGO_FLUXO, OB.NUMERO_GRUPO_PROGRAM,
        OB.CODIGO_REDUZIDO, OB.TIPO_GERACAO, OB.BAIXOU_PECAS, OB.PRIM_LOTE_PROCESSO,
        OB.PROGRAMACAO_AUTOMATI, OB.CODIGO_REDUZIDO_CRU, OB.CODIGO_OBSERVACAO,
        PKGUTIL0001.FNC_CNVDATA(OB.TEMPO_INICIO_PRODUCA, NULL) as DT_INICIO_PROD,
        PKGUTIL0001.FNC_CNVDATA(OB.TEMPO_ENCERRAMENTO_O, NULL) as DT_FIM_PROD,
        PKGUTIL0001.FNC_CNVDATA(OB.TEMPO_PROGRAMACAO, NULL) as DT_PROGRAMACAO,
        DECODE(OB.STATUS, 0, 0, 1) as ST_OB_EM_ABERTO_VAL,
        DECODE(OB.TIPO_GERACAO, 0, 'PLANO', 1, 'DIVISAO') as DS_TP_GERACAO_VAL
    FROM SGTPRD.OB OB
),

-- 2. Tingimento (Original TIN)
CTE_TINGIMENTO AS (
    SELECT OBFT.NUMERO_OB,
           LTRIM(OBFT.NUMERO_MAQUINA,0) as NR_MAQUINA_TIN,
           OBFT.CODIGO_GRUPO as CD_GR_TINGIMENTO,
           PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_INICIAL) as DT_HR_INICIO_TINGIMENTO,
           PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_FINAL) as DT_HR_FINAL_TINGIMENTO,
           OBFT.STATUS as ST_FASE_TIN,
           MOV.STATUS as ST_UP_FASE_TIN,
           (MOV.TEMPO_FINAL-MOV.TEMPO_INICIAL) as DURACAO_MIN,
           FNC_ESP_REC_PES(OBFT.NUMERO_OB) as RECEITA_PESADA,
           OBFT.ESPECIFICACAO_PRODUT as EP_TIN,
           OBFT.PROCESSO_ESPECIFICO as PE_TIN,
           OBFT.DESTINO_RECEITA as CD_DESTINO_REC_TIN
    FROM SGTPRD.OB_FASES OBFT
    JOIN SGTPRD.MOVIMENTO_MAQUINA MOV ON MOV.NUMERO_ORDEM = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.NUMERO_OB,OBFT.CODIGO_GRUPO)
         AND MOV.SEQUENCIA = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.SEQUENCIA,0)
    WHERE OBFT.CODIGO_FASE = 40
      AND OBFT.SEQUENCIA = (SELECT MAX(OBFT2.SEQUENCIA) FROM SGTPRD.OB_FASES OBFT2 WHERE OBFT2.CODIGO_FASE=40 AND OBFT2.NUMERO_OB = OBFT.NUMERO_OB)
),

-- 3. Qualidade (Original OBQ)
CTE_QUALIDADE AS (
    SELECT OBQ1.NUMERO_OB,
           SGTPRD.OPTSTRAGGR(DISTINCT OBQ1.SEQUENCIA_OB_QUALIDA) as SQ_OB_QUALIDADE,
           SGTPRD.OPTSTRAGGR(DISTINCT OBQ1.DESTINO) as CD_DESTINO_DEF,
           SGTPRD.OPTSTRAGGR(DISTINCT TRIM(OBQ1.USO_ALTERNATIVO)) as DS_USO_ALTERNATIVO,
           SGTPRD.OPTSTRAGGR(DISTINCT OBQ1.GRUPO_DEFEITO) as GR_DEFEITO,
           SGTPRD.OPTSTRAGGR(DISTINCT OBQ1.TIPO_DEFEITO) as TP_DEFEITO
    FROM SGTPRD.OB_QUALIDADE OBQ1
    WHERE OBQ1.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2 WHERE OBQ2.NUMERO_OB = OBQ1.NUMERO_OB AND OBQ2.SEQUENCIA_FASE<>0)
    GROUP BY OBQ1.NUMERO_OB
),

-- 4. Quantidades e Romaneio (Consolidado)
CTE_QT_ROMANEIO AS (
    SELECT NR_OB,
           SUM(QT_ROMANEIO) as QT_ROMANEIO,
           SUM(QT_PC_ROMANEIO) as QT_PC_ROMANEIO,
           MAX(NR_ROMANEIO) as NR_ROMANEIO,
           MAX(ST_ROMANEIO) as ST_ROMANEIO,
           MAX(ID_PESSOA_ROMANEIO) as ID_PESSOA_ROMANEIO,
           MAX(NR_PEDIDO) as NR_PEDIDO_ROM,
           MAX(SQ_ITEM_PEDIDO) as SQ_ITEM_ROM,
           DECODE(MAX(NR_ROMANEIO), NULL, 0, 1) as ST_OB_COM_ROMANEIO
    FROM (
        SELECT DOB.NUMERO_OB as NR_OB, PRS.NUMERO_ROMANEIO_SAID as NR_ROMANEIO, SUM(PRS.PESO_PECA) as QT_ROMANEIO, COUNT(PRS.IDPECASPRODUTO) as QT_PC_ROMANEIO,
               MAX(ROM.STATUS) as ST_ROMANEIO, MAX(ROM.IDPESSOAFJ) as ID_PESSOA_ROMANEIO, MAX(PR1.NUMERO_PEDIDO) as NR_PEDIDO, MAX(PR1.ITEM_PEDIDO) as SQ_ITEM_PEDIDO
        FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS
        JOIN SGTPRD.GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO
        JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID
        JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
        GROUP BY DOB.NUMERO_OB, PRS.NUMERO_ROMANEIO_SAID
        UNION ALL
        SELECT DBB.NUMERO_OB as NR_OB, GRR.NUMERO_ROMANEIO_SAID as NR_ROMANEIO, SUM(GGP.QTLIQUIDA) as QT_ROMANEIO, COUNT(GRR.IDPECASPRODUTO) as QT_PC_ROMANEIO,
               MAX(RMM.STATUS) as ST_ROMANEIO, MAX(RMM.IDPESSOAFJ) as ID_PESSOA_ROMANEIO, MAX(PR2.NUMERO_PEDIDO) as NR_PEDIDO, MAX(PR2.ITEM_PEDIDO) as SQ_ITEM_PEDIDO
        FROM SGTPRD.GERAPECAROMSAIDA GRR
        JOIN SGTPRD.GERAPECADESTINOOB DBB ON DBB.IDPECASPRODUTO = GRR.IDPECASPRODUTO
        JOIN SGTPRD.ROMANEIO RMM ON RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
        JOIN SGTPRD.GERAPECASPRODUTO GGP ON GGP.IDPECASPRODUTO = GRR.IDPECASPRODUTO
        JOIN SGTPRD.PRODUTO_ROMANEIO PR2 ON PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO AND PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
        GROUP BY DBB.NUMERO_OB, GRR.NUMERO_ROMANEIO_SAID
    )
    GROUP BY NR_OB
),

-- 5. Pedido Comercial e Programação
CTE_PEDIDO_DETALHE AS (
    SELECT IPC.PEDIDO as NR_PEDIDO_PED, IPC.ITEMPEDIDO as SQ_ITEM_PEDIDO_PED, PED.CD_SUBTIPOPED as TP_PEDIDO,
           TRIM(PED.PEDIDOCLIENTE) as NR_PROGRAMACAO, TRIM(PED.NUMERO_NOTA_FISCAL) as NR_NFE_PEDIDO,
           IPC.SITUACAOITEM as ST_ITEM_PEDIDO, IPC.PRECOUNITARIO as PR_UNITARIO_PED,
           TO_DATE(IPC.EXPEDIREM,'YYYYMMDD') as DT_ENTREGA, TRIM(PRE.NOME) as NM_PESSOA_COMPRADOR,
           PED.IDFILIALRESPONSAVEL, PED.BLOQUEIOFATURAMENTO, IPC.CD_DESENHO_CLIENTE
    FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
    JOIN SGTPRD.PESSOASFJ PRE ON PRE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
),

-- 6. Bloqueios da OB (BBB)
CTE_BLOQUEIO_OB AS (
    SELECT T.NUMERO_OB as NR_OB_BLOQ, T.FASE as CD_FASE_OB_BLOQ, T.LIBERA_INICIO_PRODUC as ST_LIB_INI_FASE,
           T.DATA_BLOQUEIO as DT_HR_BLOQUEIO, TRIM(T.OBSERVACAO) as OBS_OB_BLOQUEIO,
           T.IDMOTIVOBLOQ, T.CODREDUSU_BLOQUEIO
    FROM SGTPRD.OB_BLOQUEIO T
),

-- 7. Fase Atual (Analítica)
CTE_FASE_ATUAL AS (
    SELECT F.NUMERO_OB as NR_OB_FAT, F.CODIGO_FASE as CD_FASE_ATUAL_VAL, F.STATUS as ST_FASE_ATUAL_VAL,
           F.NUMERO_MAQUINA as NR_MAQ_FASE_ATUAL, FF.DESCRICAO_FASE as DS_FASE_ATUAL, FF.DESCRICAO_FASE_2 as DS_FASE_BI,
           ROW_NUMBER() OVER (PARTITION BY F.NUMERO_OB ORDER BY F.SEQUENCIA DESC) as RN
    FROM SGTPRD.OB_FASES F
    JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = F.CODIGO_FASE
),

-- 8. Quantidades Origem (Cru)
CTE_QT_ORIGEM AS (
    SELECT O1.NUMERO_OB as NR_OB_OPR, SUM(NVL(O4.QTPESOLIQUORIG, 0)) as QT_CRU_ORIG_OB,
           SUM(NVL(O2.QTLIQUIDA, 0)) as QT_CRU_ATUAL_OB, COUNT(O2.IDPECASPRODUTO) as QT_PC_CRU_OB
    FROM SGTPRD.GERAPECAORIGEMOB O1
    JOIN SGTPRD.GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
    LEFT JOIN SGTPRD.GERAPECACOMPLPECA O4 ON O4.IDPECASPRODUTO = O1.IDPECASPRODUTO
    GROUP BY O1.NUMERO_OB
),

-- 9. Quantidades Destino (Acabado)
CTE_QT_DESTINO AS (
    SELECT O1.NUMERO_OB as NR_OB_QTD, SUM(O2.QTLIQUIDA) as QT_ACA_OB, COUNT(O2.IDPECASPRODUTO) as QT_PC_ACA_OB,
           MAX(CASE WHEN O2.CODIGO_DEPOSITO = 100 THEN 1 ELSE 0 END) as EH_ACAB_REPROC
    FROM SGTPRD.GERAPECADESTINOOB O1
    JOIN SGTPRD.GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
    GROUP BY O1.NUMERO_OB
),

-- 10. NF das Peças Cruas (QTPNF)
CTE_NF_CRU AS (
    SELECT NR_OB_NF, SGTPRD.OPTSTRAGGR(QT_PECA || ' - ' || NUMERO_NOTA) as QT_PC_NF
    FROM (
        SELECT AB1.NUMERO_OB as NR_OB_NF, BC1.NUMERO_NOTA, COUNT(AB1.IDPECASPRODUTO) as QT_PECA
        FROM SGTPRD.GERAPECAORIGEMOB AB1
        JOIN SGTPRD.GERAPECANOTAENTRADA BC1 ON BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
        GROUP BY AB1.NUMERO_OB, BC1.NUMERO_NOTA
    )
    GROUP BY NR_OB_NF
)

-- 11. Junção de Pedido Comercial (Lógica Original NVL(NVL(...)))
, CTE_PEDIDO_FINAL AS (
    SELECT OBE.NUMERO_OB,
           NVL(NVL(ROM.NR_PEDIDO_ROM, (SELECT MAX(G2.NUMERO_PEDIDO_COMERC) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OBE.NUMERO_OB)),
               (SELECT PPOB.NUMERO FROM SGTPRD.PEDPRODUCAOOB PPOB WHERE PPOB.NUMEROOB = OBE.NUMERO_OB AND ROWNUM = 1)) as NR_PEDIDO_FIN,
           NVL(NVL(ROM.SQ_ITEM_ROM, (SELECT MAX(G2.SEQUENCIA_PRODUTO_PE) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OBE.NUMERO_OB)),
               (SELECT 1 FROM DUAL)) as SQ_ITEM_FIN
    FROM CTE_OB OBE
    LEFT JOIN CTE_QT_ROMANEIO ROM ON ROM.NR_OB = OBE.NUMERO_OB
)

-- SELECT PRINCIPAL CONSOLIDADO
SELECT /*+ MONITOR LEADING(OBE) USE_HASH(IAC COR COO FAT TIN OBQ ROM PPP BBB OPR QTD NF) */
    -- DADOS DA OB
    OBE.NUMERO_OB as NR_OB,
    OBE.ST_OB_EM_ABERTO_VAL as ST_OB_EM_ABERTO,
    OBE.DS_TP_GERACAO_VAL as DS_TP_GERACAO,
    OBE.TIPO_ORDEM as TP_ORDEM,
    OBE.CODIGO_FLUXO as CD_FLUXO,
    OBE.NUMERO_GRUPO_PROGRAM as NR_GR_PROGRAMACAO,
    OBE.DT_INICIO_PROD as DT_EMISSAO,
    OBE.DT_FIM_PROD as DT_ENCERRAMENTO,
    OBE.DT_PROGRAMACAO,
    OBE.BAIXOU_PECAS as ST_BAIXO_PECA,
    OBE.PRIM_LOTE_PROCESSO as ST_PRIM_LOTE,
    OBE.STATUS as ST_OB,
    OBE.CODIGO_REDUZIDO as CD_REDUZIDO,
    TRIM(IAC.CODIGO_ALTERNATIVO) as CD_ALTERNATIVO,
    SUBSTR(IAC.CODIGO, 4, 5) as CD_ARTIGO,
    SUBSTR(IAC.CODIGO, 13, 5) as CD_COR,
    TRIM(COO.DESCRICAO) as DS_COR,
    TRIM(IAC.DESCRICAO) as DS_PRODUTO,
    OBE.CODIGO_REDUZIDO_CRU as CD_REDUZIDO_CRU,
    TRIM(ICR.CODIGO_ALTERNATIVO) as CD_ALTERNATIVO_CRU,
    TRIM(ICR.DESCRICAO) as DS_PRODUTO_CRU,

    -- DADOS DA FASE ATUAL
    FAT.NR_MAQ_FASE_ATUAL,
    FAT.ST_FASE_ATUAL_VAL as ST_FASE_ATUAL,
    FAT.DS_FASE_ATUAL,
    FAT.DS_FASE_BI,
    FAT.CD_FASE_ATUAL_VAL as CD_FASE_ATUAL,

    -- TINGIMENTO
    TIN.NR_MAQUINA_TIN,
    TIN.CD_GR_TINGIMENTO,
    TIN.DT_HR_INICIO_TINGIMENTO,
    TIN.DT_HR_FINAL_TINGIMENTO,
    TIN.ST_FASE_TIN,
    TIN.ST_UP_FASE_TIN,
    TIN.DURACAO_MIN,
    TIN.RECEITA_PESADA,
    TIN.EP_TIN as EP,
    TIN.PE_TIN as PE,
    TIN.CD_DESTINO_REC_TIN as CD_DESTINO_REC,

    -- QUALIDADE
    OBQ.SQ_OB_QUALIDADE,
    OBQ.CD_DESTINO_DEF,
    OBQ.DS_USO_ALTERNATIVO,
    OBQ.GR_DEFEITO,
    OBQ.TP_DEFEITO,

    -- QUANTIDADES
    NVL(OPR.QT_CRU_ORIG_OB, 0) as QT_CRU_ORIG_OB,
    NVL(OPR.QT_CRU_ATUAL_OB, 0) as QT_CRU_ATUAL_OB,
    NVL(OPR.QT_PC_CRU_OB, 0) as QT_PC_CRU_OB,
    NVL(QTD.QT_ACA_OB, 0) as QT_ACA_OB,
    NVL(QTD.QT_PC_ACA_OB, 0) as QT_PC_ACA_OB,

    -- ROMANEIO
    ROM.ST_OB_COM_ROMANEIO,
    ROM.NR_ROMANEIO,
    ROM.ST_ROMANEIO,
    NVL(ROM.QT_ROMANEIO, 0) as QT_ROMANEIO,
    NVL(ROM.QT_PC_ROMANEIO, 0) as QT_PC_ROMANEIO,

    -- PEDIDO COMERCIAL
    PFN.NR_PEDIDO_FIN as NR_PEDIDO,
    PPP.NR_PROGRAMACAO,
    PPP.DT_ENTREGA,
    PPP.NM_PESSOA_COMPRADOR,
    PPP.PR_UNITARIO_PED,
    PPP.CD_DESENHO_CLIENTE as CD_REF_CLIENTE,

    -- BLOQUEIOS
    BBB.OBS_OB_BLOQUEIO,
    BBB.DT_HR_BLOQUEIO,
    BBB.CD_FASE_OB_BLOQ,

    -- NF CRUA
    NF.QT_PC_NF,

    -- PERFORMANCE
    CASE
        WHEN OBE.STATUS = 0 THEN NVL(TRUNC(OBE.DT_FIM_PROD) - TRUNC(OBE.DT_INICIO_PROD), 0)
        WHEN OBE.STATUS = 1 THEN NVL(TRUNC(SYSDATE) - TRUNC(OBE.DT_INICIO_PROD), 0)
        ELSE 0
    END as LEAD_TIME

FROM CTE_OB OBE
JOIN SGTPRD.ITENS_ESTOQUE IAC ON IAC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
JOIN SGTPRD.ENGEITEMESTOCOR COR ON COR.CDREDUZIDO = IAC.CODIGO_REDUZIDO
JOIN SGTPRD.COR COO ON COO.CODIGO_COR = COR.CDCOR
JOIN SGTPRD.ITENS_ESTOQUE ICR ON ICR.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO_CRU
LEFT JOIN CTE_FASE_ATUAL FAT ON FAT.NR_OB_FAT = OBE.NUMERO_OB AND FAT.RN = 1
LEFT JOIN CTE_TINGIMENTO TIN ON TIN.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_QUALIDADE OBQ ON OBQ.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_QT_ROMANEIO ROM ON ROM.NR_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PEDIDO_FINAL PFN ON PFN.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PEDIDO_DETALHE PPP ON PPP.NR_PEDIDO_PED = PFN.NR_PEDIDO_FIN AND PPP.SQ_ITEM_PEDIDO_PED = PFN.SQ_ITEM_FIN
LEFT JOIN CTE_BLOQUEIO_OB BBB ON BBB.NR_OB_BLOQ = OBE.NUMERO_OB
LEFT JOIN CTE_QT_ORIGEM OPR ON OPR.NR_OB_OPR = OBE.NUMERO_OB
LEFT JOIN CTE_QT_DESTINO QTD ON QTD.NR_OB_QTD = OBE.NUMERO_OB
LEFT JOIN CTE_NF_CRU NF ON NF.NR_OB_NF = OBE.NUMERO_OB

WHERE NVL(QTD.EH_ACAB_REPROC, 0) = 0
AND OBE.NUMERO_OB = 173900
ORDER BY OBE.NUMERO_OB DESC
;
