  SELECT  /*DADOS DA OB*/
        OBE.NUMERO_OB NR_OB
      , OOO.NR_OF
      , DECODE(OBE.STATUS,0,0,1) ST_OB_EM_ABERTO
      , NVL((SELECT O.OBMONTADA FROM PEDPRODUCAOOB O WHERE O.SETOR = 5 AND O.NUMEROOB = OBE.NUMERO_OB),0) ST_OB_MONTADA
      ,(SELECT TRIM(MAX(OBF.CODIGO_PLACA)) FROM OB_FASES OBF WHERE OBF.NUMERO_OB = OBE.NUMERO_OB) NR_KANBAN
      , OBE.TIPO_GERACAO TP_GERACAO
      , DECODE(OBE.TIPO_GERACAO,0,'PLANO',1,'DIVISAO')DS_TP_GERACAO
      , OBE.PROGRAMACAO_AUTOMATI  ST_PROG_AUTOMATICA
      , OBE.BAIXOU_PECAS ST_BAIXO_PECA
      , OBE.PRIM_LOTE_PROCESSO ST_PRIM_LOTE
      , OBE.STATUS ST_OB
      ,(SELECT UPPER(A.DESCRICAO) FROM VW_ENU_STATUS_OB A WHERE A.STATUS = OBE.STATUS) DS_ST_OB
      , OBE.TIPO_ORDEM TP_ORDEM
      , OBE.CODIGO_FLUXO CD_FLUXO
      , OBE.NUMERO_GRUPO_PROGRAM  NR_GR_PROGRAMACAO
      ,(SELECT SEI.SETOR_SEQUENCIA||' - '||TRIM(SEI.DESCRICAO)
        FROM   GRUPO_FASES GFA
             , FASES_FLUXO FFL
             , SETOR_INDUSTRIAL SEI
        WHERE FFL.CODIGO_GRUPO = GFA.CODIGO
        AND   FFL.CODIGO_FASE = FAT.CD_FASE_ATUAL
        AND   SEI.SETOR_SEQUENCIA = GFA.SETOR_SEQUENCIA
       ) DS_SETOR_INDUSTRIAL
      , NVL((SELECT ENU.SEQENUMVALUE
             FROM  SYSENUMERATE ENU
                 , OB_FASES OBFX
                 , FASES_FLUXO FF
             WHERE ENU.SEQENUMVALUE = OBFX.STATUS
             AND OBFX.CODIGO_FASE = FF.CODIGO_FASE
             AND TRIM(ENU.ENUMERATE)  = 'TOBFASESSTATUS'
             AND FF.PROCESSOTERCEIROS = '1'
             AND OBFX.SEQUENCIA       = (SELECT MAX(OBFX2.SEQUENCIA) FROM OB_FASES OBFX2 WHERE OBFX2.NUMERO_OB = OBE.NUMERO_OB AND OBFX.NUMERO_OB = OBE.NUMERO_OB AND OBFX2.CODIGO_FASE = OBFX.CODIGO_FASE)
             AND OBFX.NUMERO_OB       = OBE.NUMERO_OB)
         ,5)ST_TERCEIROS
       , NVL((SELECT DECODE(ENU.SEQENUMVALUE,0,'PENDENTE',3,'EM PROCESSO',4,'CONCLUIDO') STATUS_TERC
              FROM SYSENUMERATE ENU, OB_FASES OBFX, FASES_FLUXO FF
              WHERE ENU.SEQENUMVALUE = OBFX.STATUS
              AND OBFX.CODIGO_FASE = FF.CODIGO_FASE
              AND TRIM(ENU.ENUMERATE)  = 'TOBFASESSTATUS'
              AND FF.PROCESSOTERCEIROS = '1'
              AND OBFX.SEQUENCIA       = (SELECT MAX(OBFX2.SEQUENCIA) FROM OB_FASES OBFX2 WHERE OBFX2.NUMERO_OB = OBE.NUMERO_OB AND OBFX.NUMERO_OB = OBE.NUMERO_OB AND OBFX2.CODIGO_FASE = OBFX.CODIGO_FASE)
              AND OBFX.NUMERO_OB       = OBE.NUMERO_OB)
         ,'SEM TERCEIROS') DS_ST_TERCEIROS
         ,(SELECT MAX(UFA.CODIGO_UNIDADE_FABRI)||' - '||TRIM(UFA.NOME_UNIDADE_FABRIL)
           FROM SGTPRD.OB_FASES VPF, SGTPRD.MAQUINA MAQ, SGTPRD.GRUPO_MAQUINAS GPR, SGTPRD.UNIDADE_FABRIL UFA
           WHERE VPF.NUMERO_OB = OBE.NUMERO_OB
           AND MAQ.NUMERO_MAQUINA = VPF.NUMERO_MAQUINA
           AND GPR.GRUPO = MAQ.GRUPO
           AND GPR.SETOR = MAQ.SETOR
           AND UFA.CODIGO_UNIDADE_FABRI = GPR.UNIDADE_FABRIL
           AND UFA.EH_FACCAO            ='S'
           GROUP BY UFA.NOME_UNIDADE_FABRIL
          ) DS_FACCAO
      ,(SELECT UPPER(B.DESCRICAO) FROM VW_ENU_OB_TIPO_ORDEM B WHERE B.TIPO_ORDEM = OBE.TIPO_ORDEM) DS_TP_ORDEM
      , PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_INICIO_PRODUCA,NULL) DT_EMISSAO
      , PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_ENCERRAMENTO_O,NULL) DT_ENCERRAMENTO
      , PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_PROGRAMACAO,NULL) DT_PROGRAMACAO
      ,(SELECT optstraggrsemvirgula(TRIM(UPPER(C.TEXTO))) FROM OBSERVACAO C WHERE C.CODIGO = OBE.CODIGO_OBSERVACAO) OBS_OB
      , OBE.CODIGO_REDUZIDO CD_REDUZIDO
      , TRIM(IAC.CODIGO_ALTERNATIVO) CD_ALTERNATIVO
      , SUBSTR(IAC.CODIGO,4,5) CD_ARTIGO
      , SUBSTR(IAC.CODIGO,13,5) CD_COR
      , TRIM(COO.DESCRICAO) DS_COR
      , COO.TIPOCOR TP_COR
      , TRIM(TCO.DESCRICAO) DS_TP_COR
      , SUBSTR(IAC.CODIGO,1,3)||'.'||SUBSTR(IAC.CODIGO,4,5)||'.'||SUBSTR(IAC.CODIGO,9,1)||'.'||SUBSTR(IAC.CODIGO,10,3)||'.'||SUBSTR(IAC.CODIGO,13,5)||'.'||SUBSTR(IAC.CODIGO,18,6)||'.'||SUBSTR(IAC.CODIGO,24,2)||'.'||SUBSTR(IAC.CODIGO,26,2) CD_INDUSTRIAL
      , TRIM(IAC.DESCRICAO) DS_PRODUTO
      , DECODE(TRIM(NV9.CDNIVELGENERICO),'T', 1,'R', 2) CD_PROCESSO
      , DECODE(TRIM(NV9.CDNIVELGENERICO),'T', 'TUBULAR','R', 'RAMADO')DS_PROCESSO
      , OBE.CODIGO_REDUZIDO_CRU CD_REDUZIDO_CRU
      , TRIM(ICR.CODIGO_ALTERNATIVO) CD_ALTERNATIVO_CRU
      , TRIM(ICR.DESCRICAO) DS_PRODUTO_CRU
      , CAST(NVL((SELECT MAX(FFL.PROCESSOTERCEIROS)
                  FROM OB_FASES OBF
                      ,FASES_FLUXO FFL
                 WHERE OBF.NUMERO_OB = OBE.NUMERO_OB
                 AND   FFL.CODIGO_FASE = OBF.CODIGO_FASE),0) AS NUMBER(10)
            ) PROD_EXTERNA
      ,(SELECT MAX(MPA.DATA_DOCUMENTO)
        FROM SGTPRD.BD_PRD_MOVPROD MPA
        WHERE MPA.CODIGO = 1
        AND MPA.OPERACAO = 1
        AND MPA.REDUZIDO_ITEM = IAC.CODIGO_REDUZIDO
       ) DT_ULT_PROD_ITEM_ACA
      ,(SELECT MAX(FAT.DATA_DA_EMISSAO)
        FROM SGTPRD.BD_FAT_FATURAMENTO FAT
        WHERE FAT.CODIGO_REDUZIDO = IAC.CODIGO_REDUZIDO
       ) DT_ULT_FAT_ITEM_ACA
      , CASE WHEN OBE.STATUS = 0 THEN NVL(PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_ENCERRAMENTO_O,NULL) - PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_INICIO_PRODUCA,NULL),0)
             WHEN OBE.STATUS = 1 THEN NVL(SYSDATE - PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_INICIO_PRODUCA,NULL),0)
        ELSE 0 END LEAD_TIME
      ,(SELECT TRIM(LPC.DECRICAO)
        FROM LINHAPRODUTOCOMERCIA LPC
        WHERE LPC.LINHAPRODUTOCOMERCIA = IAC.LINHAPRODUTOCOMERCIA
      ) DS_LINHA_COMERCIAL
      ,(SELECT TRIM(TO_CHAR(ENG.LARGURA, '999G999G990D00') || ' m')
        FROM SGTPRD.ENG_PRODG_ACABADO ENG
        WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR
      ) LARGURA_ACA
      ,(SELECT ENG.GRAMATURA || ' g/m²'
        FROM SGTPRD.ENG_PRODG_ACABADO ENG
        WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR
       ) GRAMATURA_ACA

      /*DADOS DAS FASES DA OB*/
      , PKGBENF0001.FNC_RETORNA_PRI_CONF_OB (obe.numero_ob) DT_PRI_CONFIRMACAO
      , PKGBENF0001.FNC_RETORNA_ULT_CONF_OB (obe.numero_ob) DT_ULT_CONFIRMACAO
      , CASE WHEN PKGBENF0001.FNC_RETORNA_ULT_CONF_OB (obe.numero_ob) = NULL THEN NULL ELSE SYSDATE - PKGBENF0001.FNC_RETORNA_ULT_CONF_OB (obe.numero_ob) END DIAS_PARADO
      ,(SELECT OPTSTRAGGR(DISTINCT 'FASE '||E.CODIGO_FASE||' -> '||TRIM(UPPER(D.TEXTO))) FROM OBSERVACAO D, OB_FASES E WHERE D.CODIGO = E.CODIGO_OBSERVACAO AND E.NUMERO_OB = OBE.NUMERO_OB) OBS_FASE_OB
      , TIN.NR_MAQUINA_TIN
      , TIN.CD_GR_TINGIMENTO
      , TIN.DT_HR_INICIO_TINGIMENTO
      , TIN.DT_HR_FINAL_TINGIMENTO
      , TIN.ST_FASE_TIN
      , TIN.ST_UP_FASE_TIN
      ,(SELECT UPPER(SUP.DESCRICAO) FROM VW_ENU_STATUS_UP SUP WHERE SUP.STATUS=TIN.ST_UP_FASE_TIN) DS_ST_UP_FASE_TIN
      , TIN.DURACAO_MIN
      , TIN.RECEITA_PESADA ST_REC_PESADA
      , DECODE(TIN.RECEITA_PESADA,0,'NAO',1,'SIM') DS_REC_PESADA
      , TIN.EP
      , TIN.PE
      , TIN.CD_DESTINO_REC
      , TIN.DS_DESTINO_REC
      , NVL(REC.ST_BLOQ_REC,2) ST_BLOQ_REC
      , NVL(REC.DS_BLOQ_REC,'SEM RECEITA') DS_BLOQ_REC
      , FAT.NR_MAQ_FASE_ATUAL
      , FAT.ST_FASE_ATUAL
      , FAT.CD_FASE_ATUAL
      , FAT.DS_ST_FAS_ATUAL
      , FAT.DS_FASE_ATUAL
      ,(SELECT F1.DESCRICAO_FASE_2 FROM FASES_FLUXO F1 WHERE F1.CODIGO_FASE = FAT.CD_FASE_ATUAL) DS_FASE_BI

      /*DADOS DAS QUANTIDADES DA OB*/
      , NVL(QT1.QT_CRU_PROG_OB,0) QT_CRU_PROG_OB
      , NVL(QT1.QT_PC_CRU_PROG_OB,0) QT_PC_CRU_PROG_OB
      , NVL(QT1.QT_CRU_ORIG_OB,0) QT_CRU_ORIG_OB
      , NVL(QT1.QT_CRU_ATUAL_OB,0) QT_CRU_ATUAL_OB
      , NVL(QT1.QT_PC_CRU_OB,0) QT_PC_CRU_OB

      ,(SELECT OPTSTRAGGR(DISTINCT TRIM(LTRIM(XX2.LOTE_PRODUTO, '0')))
        FROM GERAPECAORIGEMOB XX1
            ,GERAPECASPRODUTO XX2
        WHERE XX2.IDPECASPRODUTO = XX1.IDPECASPRODUTO
        AND   XX1.NUMERO_OB = OBE.NUMERO_OB
       ) LOTE_CRU

      ,(SELECT SGTPRD.OPTSTRAGGR(DISTINCT(TRIM(LTRIM(LOTE_FIO,'0'))))
        FROM (SELECT DISTINCT GPO.NUMERO_OB, LFP.LOTE_FIO
                FROM GERAPECAORIGEMOB     GPO,
                     GERAPECASPRODUTO     GPP,
                     LOTES_FIO_PRODUTO    LFP
               WHERE GPP.IDPECASPRODUTO   = GPO.IDPECASPRODUTO
                 AND LFP.LOTE_PRODUTO_CRU = GPP.LOTE_PRODUTO)
        WHERE NUMERO_OB = OBE.NUMERO_OB
       ) LOTE_FIO

      ,(SELECT SGTPRD.OPTSTRAGGR(DISTINCT(TRIM(LTRIM(NUMERO_MAQUINA,'0'))))
        FROM (SELECT DISTINCT GPO.NUMERO_OB, OPM.NUMERO_MAQUINA
              FROM SGTPRD.GERAPECAORIGEMOB     GPO,
                      SGTPRD.GERAPECAORDEMMALHA   GOM,
                      SGTPRD.ORDEM_PRODUCAO_MALHA OPM
              WHERE GOM.IDPECASPRODUTO = GPO.IDPECASPRODUTO
              AND OPM.NUMERO_ORDEM = GOM.NUMERO_ORDEM_MALHA)
        WHERE NUMERO_OB = OBE.NUMERO_OB
       ) NR_TEAR

      , NVL(QT2.QT_ACA_OB,0) QT_ACA_OB
      , NVL(QT2.EH_ACAB_REPROC,0) EH_ACAB_REPROC
      , NVL(QT2.QT_PC_ACA_OB,0) QT_PC_ACA_OB

      , NVL(CASE WHEN (SELECT H.STATUS
                       FROM OB_FASES H
                       WHERE H.NUMERO_OB=OBE.NUMERO_OB
                       AND H.CODIGO_FASE=150
                       AND H.SEQUENCIA =  (SELECT MAX(HH.SEQUENCIA)
                                           FROM OB_FASES HH
                                           WHERE HH.NUMERO_OB = H.NUMERO_OB
                                           AND   HH.CODIGO_FASE = H.CODIGO_FASE
                                          )
                      ) <> 4 THEN NULL
                  ELSE ROUND(100 - (QT2.QT_ACA_OB / QT1.QT_CRU_ORIG_OB * 100),2) END
        ,0 ) PC_QUEBRA

      , NVL(QT3.QT_ACA_DISP_OB,0) QT_ACA_DISP_OB
      , NVL(QT3.QT_PC_ACA_DISP_OB,0) QT_PC_ACA_DISP_OB
      , NVL(QT3.QT_ACA_RES_OB,0) QT_ACA_RES_OB
      , NVL(QT3.QT_PC_ACA_RES_OB,0) QT_PC_ACA_RES_OB

      , NVL(RRR.QT_ROMANEIO,0) QT_ACA_ROM_OB
      , NVL(RRR.QT_PC_ROMANEIO,0) QT_PC_ACA_ROM_OB

      /*DADOS DEFEITO DA OB*/
      , OBQ.SQ_OB_QUALIDADE
      , OBQ.CD_DESTINO_DEF
      , OBQ.DS_USO_ALTERNATIVO
      , OBQ.DS_GR_DEFEITO
      , OBQ.DS_TP_DEFEITO

      /*DADOS DO ROMANEIO*/
      , DECODE(ROO.NR_ROMANEIO,NULL,0,1) ST_OB_COM_ROMANEIO
      , ROO.NR_ROMANEIO
      , ROO.ID_PESSOA_ROMANEIO
      ,(SELECT TRIM(PSS.NOME) FROM PESSOASFJ PSS WHERE PSS.IDPESSOAFJ = ROO.ID_PESSOA_ROMANEIO) DS_PESSOA_ROMANEIO
      , ROO.ST_ROMANEIO
      ,(SELECT UPPER(ERR.DESCRICAO) FROM VW_ENU_STATUS_ROM_SAIDA ERR WHERE ERR.STATUS = ROO.ST_ROMANEIO) DS_ST_ROMANEIO
      , NVL(ROO.ST_ROM_EM_ABERTO,1) ST_ROM_EM_ABERTO
      , NVL(ROO.QT_ROMANEIO,0) QT_ROMANEIO
      , NVL(ROO.QT_PC_ROMANEIO,0) QT_PC_ROMANEIO

      /*DADOS DO PEDIDO COMERCIAL*/
      , NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO) NR_PEDIDO
      , PPP.TP_PEDIDO
      , PPP.DS_TP_PEDIDO
      , PPP.NR_PROGRAMACAO
      , PPP.NR_NFE_PEDIDO
      , PPP.DS_ITEM_PEDIDO_CLIENTE
      , NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO),OOO.SQ_ITEM_PEDIDO) SQ_ITEM_PEDIDO
      , PPP.ST_ITEM_PEDIDO
      , PPP.DS_ST_ITEM_PEDIDO
      , PPP.OBS_ITEM_PEDIDO
      , PPP.CD_REF_CLIENTE
      , NVL(PPP.ST_BLOQUEIO_FAT,0) ST_BLOQUEIO_FAT
      , NVL(PPP.DS_ST_BLOQUEIO_FAT,'NORMAL') DS_ST_BLOQUEIO_FAT
      , NVL(PPP.ST_PEDIDO_EM_ABERTO,(DECODE(OBE.STATUS,0,NULL,1))) ST_PEDIDO_EM_ABERTO
      , PPP.ID_PESSOA_COMPRADOR
      , PPP.NM_PESSOA_COMPRADOR
      , PPP.NM_PESSOA_COMPRADOR_F
      , PPP.ID_PESSOA_FATURA
      , PPP.NM_PESSOA_FATURA
      , PPP.ID_PESSOA_ENTREGA
      , PPP.NM_PESSOA_ENTREGA
      , NVL(PPP.ST_PESCOM_DIF_PESFAT,0) ST_PESCOM_DIF_PESFAT --NVL PARA PEGAR OBS SEM PEDIDO
      , NVL(PPP.DS_ST_PESCOM_DIF_PESFAT,'NAO') DS_ST_PESCOM_DIF_PESFAT
      , NVL(PPP.ST_TRANSF_LOJAS,0) ST_TRANSF_LOJAS
      , NVL(PPP.DS_ST_TRANSF_LOJAS,'NAO') DS_ST_TRANSF_LOJAS
      , PPP.DT_ENTREGA
      , NVL(GGG.QT_PC_ACA_RES_PEDIDO,0) QT_PC_ACA_RES_PEDIDO
      , NVL(GGG.QT_ACA_RES_PED,0) QT_ACA_RES_PED
      , PPP.PR_UNITARIO_PED
      , PPP.CD_TAB_PRECO

     /*DADOS FATURAMENTO*/
      , DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') ST_FATURAMENTO
      , DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'NAO',0,'SIM') DS_ST_FATURAMENTO
      , CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO  = QT2.QT_ACA_OB THEN 2
             WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 1
                                                                                                           ELSE 0
        END AS ST_OB_VARIOS_FAT
      , CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO  = QT2.QT_ACA_OB THEN 'NAO'
             WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 'SIM'
                                                                                                           ELSE 'AGUARDANDO'
        END AS DS_ST_OB_VARIOS_FAT
      , NFF.NR_NF
      , NFF.DT_EMISSAO_NF
      , DECODE(NVL(OB_FAT_TOTAL.NR_OB,0),0,0,1)  OB_FAT_TOTAL

      /*DADOS OB BLOQUEIO*/
      , BBB.CD_FASE_OB_BLOQ
      , BBB.DS_FASE_OB_BLOQ
      , BBB.ST_OB_BLOQUEIO
      , BBB.DS_ST_OB_BLOQUEIO
      , BBB.ST_LIB_INI_FASE
      , BBB.DS_ST_LIB_INI_FASE
      , BBB.OBS_OB_BLOQUEIO
      , BBB.DS_MOTIVO_BLOQUEIO
      , BBB.DT_HR_BLOQUEIO
      , BBB.NM_USU_BLOQUEIO
      , BBB.DT_H_LIBERACAO
      , BBB.NM_USU_LIBERACAO

      /*DADOS DEFEITO PEÇA CRUA*/
      ,DEFP.DS_GR_DEFEITO DS_GR_DEFEITO_CRU
      ,DEFP.DS_TP_DEFEITO DS_TP_DEFEITO_CRU

      /*NF DAS PEÇAS CRUAS*/
      ,QTPNF.QT_PC_NF

FROM   OB OBE
     , ITENS_ESTOQUE IAC
     , ENGEITEMESTOCOR COR
     , COR COO
     , COML_TIPOSCOR TCO
     , ENGEITEMESTONIVELGE9 NV9
     , ITENS_ESTOQUE ICR

     ,(SELECT  OBFT.NUMERO_OB
             , OBFT.CODIGO_GRUPO CD_GR_TINGIMENTO
             , LTRIM(OBFT.NUMERO_MAQUINA,0) NR_MAQUINA_TIN
             , PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_INICIAL) DT_HR_INICIO_TINGIMENTO
             , PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_FINAL) DT_HR_FINAL_TINGIMENTO
             , MOV.TEMPO_FINAL-MOV.TEMPO_INICIAL DURACAO_MIN
             ,(MOV.TEMPO_FINAL-MOV.TEMPO_INICIAL)/60/24 DURACAO_DIAS
             , OBFT.STATUS ST_FASE_TIN
             , DECODE(OBFT.STATUS,1,FNC_ESP_REC_PES(OBFT.NUMERO_OB),2,FNC_ESP_REC_PES(OBFT.NUMERO_OB),NULL) RECEITA_PESADA --MOSTRAR O VALOR DESTA SOMENTE PARA RECEITAS EMITIDAS E PESADAS.
             --, FNC_ESP_REC_PES(OBFT.NUMERO_OB) RECEITA_PESADA
             , OBFT.ESPECIFICACAO_PRODUT EP
             , OBFT.PROCESSO_ESPECIFICO  PE
             , OBFT.DESTINO_RECEITA CD_DESTINO_REC
             ,(SELECT TRIM(DDD.DESCRICAO) FROM DESTINO DDD WHERE DDD.DESTINO = OBFT.DESTINO_RECEITA) DS_DESTINO_REC
             , MOV.STATUS ST_UP_FASE_TIN
             ,DECODE(OBFT.CODIGO_GRUPO,0,OBFT.SEQUENCIA,0)
        FROM  OB_FASES          OBFT
             ,MOVIMENTO_MAQUINA MOV
        WHERE OBFT.CODIGO_FASE = 40
        AND   MOV.NUMERO_ORDEM = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.NUMERO_OB,OBFT.CODIGO_GRUPO)
        AND   MOV.SEQUENCIA    = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.SEQUENCIA,0)
        AND   OBFT.SEQUENCIA   = (SELECT MAX(OBFT2.SEQUENCIA) FROM OB_FASES OBFT2 WHERE OBFT2.CODIGO_FASE=40 AND OBFT2.NUMERO_OB = OBFT.NUMERO_OB)
      ) TIN

      ,(SELECT OBQ1.NUMERO_OB NR_OB
              ,OPTSTRAGGR(DISTINCT OBQ1.SEQUENCIA_OB_QUALIDA)  SQ_OB_QUALIDADE
              ,OPTSTRAGGR(DISTINCT OBQ1.DESTINO) CD_DESTINO_DEF
              ,OPTSTRAGGR(DISTINCT TRIM(OBQ1.USO_ALTERNATIVO)) DS_USO_ALTERNATIVO
              ,OPTSTRAGGR(DISTINCT OBQ1.GRUPO_DEFEITO) GR_DEFEITO
              ,OPTSTRAGGR(DISTINCT OBQ1.TIPO_DEFEITO) TP_DEFEITO
              ,OPTSTRAGGR(DISTINCT (SELECT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) FROM SGTPRD.GRUPO_DEFEITO_QUALID GDQ WHERE GDQ.CODIGO_GRUPO = OBQ1.GRUPO_DEFEITO)) DS_GR_DEFEITO
              ,OPTSTRAGGR(DISTINCT (SELECT TDQ.CODIGO_TIPO || ' - ' || TRIM(TDQ.DESCRICAO_TIPO) FROM SGTPRD.TIPO_DEFEITO_QUALIDA TDQ WHERE TDQ.CODIGO_GRUPO = OBQ1.GRUPO_DEFEITO AND TDQ.CODIGO_TIPO = OBQ1.TIPO_DEFEITO)) DS_TP_DEFEITO
        FROM   SGTPRD.OB_QUALIDADE OBQ1
        WHERE  OBQ1.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2 WHERE OBQ2.NUMERO_OB = OBQ1.NUMERO_OB AND OBQ2.SEQUENCIA_FASE<>0)
        GROUP BY OBQ1.NUMERO_OB
       ) OBQ

      ,(SELECT ITEX.CODIGO_REDUZIDO
              ,LRB.BLOQUEIO_RECEITA ST_BLOQ_REC
              ,DECODE(LRB.BLOQUEIO_RECEITA,0,'BLOQUEADA',1,'LIBERADA') DS_BLOQ_REC
          FROM CADASTRO_RECEITAS    CRE,
               LIGA_CADREC_ITEMREC  LCR,
               LABRECEITA_BLOQUEADA LRB,
               ITENS_ESTOQUE        ITEX,
               ENGEITEMESTOCOR      EGC
         WHERE LCR.CODIGO_REDUZIDO_RECE = CRE.CODIGO_REDUZIDO_RECE
           AND LRB.ID_LABRECEITA_BLOQ   = LCR.ID_LABRECEITA_BLOQ
           AND EGC.CDREDUZIDO           = ITEX.CODIGO_REDUZIDO
           AND TRIM(CRE.CODCOR)         = TRIM(EGC.CDCOR)
           AND CRE.ESPECIFICACAO_PRODUT = ITEX.ESPECIFICACAOPRODUTO
           AND ITEX.TIPO_ITEM           = 10
           AND CRE.PROCESSOINDUSTRIAL   = 401
           AND CRE.PROCESSO_ATIVO_PRODU = 1
        ) REC

       ,(SELECT OBF.NUMERO_OB
               ,OBF.SEQUENCIA
               ,LTRIM(OBF.NUMERO_MAQUINA,0) NR_MAQ_FASE_ATUAL
               ,OBF.STATUS ST_FASE_ATUAL
               ,(SELECT UPPER(SS.DESCRICAO) FROM VW_ENU_STATUS_OB_FASES SS WHERE SS.STATUS = OBF.STATUS) DS_ST_FAS_ATUAL
               ,OBF.CODIGO_FASE CD_FASE_ATUAL
               ,FFL.DESCRICAO_FASE AS DS_FASE_ATUAL
         FROM OB_FASES    OBF
            ,FASES_FLUXO FFL
            ,OB          OBE
         WHERE FFL.CODIGO_FASE = OBF.CODIGO_FASE
         AND   OBE.NUMERO_OB   = OBF.NUMERO_OB
         AND   OBE.STATUS <> 0
       ) FAT

      ,(SELECT DOB.NUMERO_OB NR_OB
             , PRS.NUMERO_ROMANEIO_SAID NR_ROMANEIO
             , ROM.STATUS ST_ROMANEIO
             , DECODE(ROM.STATUS,4,0,5,0,6,0,1) ST_ROM_EM_ABERTO
             , DECODE(PR1.NUMERO_PEDIDO,0,NULL,PR1.NUMERO_PEDIDO) NR_PEDIDO
             , DECODE(PR1.ITEM_PEDIDO,0,NULL,PR1.ITEM_PEDIDO) SQ_ITEM_PEDIDO
             , ROM.IDPESSOAFJ ID_PESSOA_ROMANEIO
             , SUM(PRS.PESO_PECA) QT_ROMANEIO
             , COUNT(PRS.IDPECASPRODUTO) QT_PC_ROMANEIO
        FROM   PECAS_ROMANEIO_SAIDA PRS
              ,GERAPECADESTINOOB    DOB
              ,ROMANEIO             ROM
              ,PRODUTO_ROMANEIO     PR1
              ,GERAPECASPRODUTO     GPP
        WHERE  DOB.IDPECASPRODUTO    = PRS.IDPECASPRODUTO
        AND    ROM.NUMERO_ROMANEIO   = PRS.NUMERO_ROMANEIO_SAID
        AND    PR1.NUMERO_ROMANEIO   = ROM.NUMERO_ROMANEIO
        AND    PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
        AND    GPP.IDPECASPRODUTO     = PRS.IDPECASPRODUTO
        AND    GPP.STPECAPRODUTO NOT IN (13)
        GROUP BY DOB.NUMERO_OB
               , PRS.NUMERO_ROMANEIO_SAID
               , PR1.NUMERO_PEDIDO
               , PR1.ITEM_PEDIDO
               , ROM.STATUS
               , DECODE(ROM.STATUS,4,0,5,0,6,0,1)
               , ROM.IDPESSOAFJ

        UNION

        SELECT DBB.NUMERO_OB NR_OB
             , GRR.NUMERO_ROMANEIO_SAID NR_ROMANEIO
             , RMM.STATUS ST_ROMANEIO
             , DECODE(RMM.STATUS,4,0,5,0,6,0,1) ST_ROM_EM_ABERTO
             , DECODE(PR2.NUMERO_PEDIDO,0,NULL,PR2.NUMERO_PEDIDO) NR_PEDIDO
             , DECODE(PR2.ITEM_PEDIDO,0,NULL,PR2.ITEM_PEDIDO) SQ_ITEM_PEDIDO
             , RMM.IDPESSOAFJ ID_PESSOA_ROMANEIO
             , SUM(GGP.QTLIQUIDA) QT_ROMANEIO
             , COUNT(GRR.IDPECASPRODUTO) QT_PC_ROMANEIO
        FROM   GERAPECAROMSAIDA  GRR
              ,GERAPECADESTINOOB DBB
              ,ROMANEIO          RMM
              ,GERAPECASPRODUTO  GGP
              ,PRODUTO_ROMANEIO  PR2
        WHERE  DBB.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
        AND    RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
        AND    GGP.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
        AND    PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO
        AND    PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
        GROUP BY DBB.NUMERO_OB
               , GRR.NUMERO_ROMANEIO_SAID
               , PR2.NUMERO_PEDIDO
               , PR2.ITEM_PEDIDO
               , RMM.STATUS
               , DECODE(RMM.STATUS,4,0,5,0,6,0,1)
               , RMM.IDPESSOAFJ
       ) ROO

      ,(SELECT RRRR.NR_OB, SUM(RRRR.QT_ROMANEIO) QT_ROMANEIO, SUM(RRRR.QT_PC_ROMANEIO) QT_PC_ROMANEIO
        FROM (
                SELECT DOB.NUMERO_OB NR_OB
                     , SUM(PRS.PESO_PECA) QT_ROMANEIO
                     , COUNT(PRS.IDPECASPRODUTO) QT_PC_ROMANEIO
                FROM   PECAS_ROMANEIO_SAIDA PRS
                      ,GERAPECADESTINOOB    DOB
                      ,ROMANEIO             ROM
                      ,PRODUTO_ROMANEIO     PR1
                WHERE  DOB.IDPECASPRODUTO    = PRS.IDPECASPRODUTO
                AND    ROM.NUMERO_ROMANEIO   = PRS.NUMERO_ROMANEIO_SAID
                AND    PR1.NUMERO_ROMANEIO   = ROM.NUMERO_ROMANEIO
                AND    PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
                AND    ROM.STATUS IN (0,1,3,8)
                GROUP BY DOB.NUMERO_OB

                UNION

                SELECT DBB.NUMERO_OB NR_OB
                     , SUM(GGP.QTLIQUIDA) QT_ROMANEIO
                     , COUNT(GRR.IDPECASPRODUTO) QT_PC_ROMANEIO
                FROM   GERAPECAROMSAIDA  GRR
                      ,GERAPECADESTINOOB DBB
                      ,ROMANEIO          RMM
                      ,GERAPECASPRODUTO  GGP
                      ,PRODUTO_ROMANEIO  PR2
                WHERE  DBB.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
                AND    RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
                AND    GGP.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
                AND    PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO
                AND    PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
                AND    GRR.IDPECASPRODUTO NOT IN (SELECT PRS.IDPECASPRODUTO FROM PECAS_ROMANEIO_SAIDA PRS)
                AND    RMM.STATUS IN (0,1,3,8)
                GROUP BY DBB.NUMERO_OB
             ) RRRR
        GROUP BY  RRRR.NR_OB
      ) RRR

      ,(SELECT PPOB.NUMEROOB NR_OB
              ,IPG.PEDIDO NR_PEDIDO
              ,IPG.ITEMPEDIDO SQ_ITEM_PEDIDO
              ,OFP.NUMEROOF NR_OF
        FROM PEDPRODUCAOOB PPOB
            ,PEDPRODUCAO PP
            ,OFORDENS OFO
            ,OFPEDIDO OFP
            ,ITENSPEDIDOQTDES IPQ
            ,ITENSPEDIDOGRADE IPG
        WHERE PP.NUMERO = PPOB.NUMERO
         AND  OFO.NUMEROPEDPRODUCAO = PP.NUMERO
         AND  OFO.REDUZIDO = PPOB.REDUZIDO
         AND  OFP.NUMEROOF = OFO.NUMEROOF
         AND  OFP.NIVEL = OFO.NIVEL
         AND  OFP.REDUZIDO = OFO.REDUZIDO
         AND  IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
         AND  IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
         AND  OFP.QUANTIDADE_ATUAL <> 0
    ) OOO

   ,(SELECT  PED.CD_SUBTIPOPED TP_PEDIDO
           ,(SELECT TRIM(STT.DS_SUBTIPOPED) FROM COML_SUBTIPOPED STT WHERE STT.CD_SUBTIPOPED = PED.CD_SUBTIPOPED) DS_TP_PEDIDO
           , IPC.PEDIDO NR_PEDIDO
           , TRIM(PED.PEDIDOCLIENTE) NR_PROGRAMACAO
           , TRIM(PED.NUMERO_NOTA_FISCAL) NR_NFE_PEDIDO
           , TRIM(IPC.ITEMPEDIDOCLIENTE) DS_ITEM_PEDIDO_CLIENTE
           , TRIM(IPC.OBS) OBS_ITEM_PEDIDO
           , TRIM(IPC.CD_DESENHO_CLIENTE) CD_REF_CLIENTE
           , PED.BLOQUEIOFATURAMENTO ST_BLOQUEIO_FAT
           , DECODE(PED.BLOQUEIOFATURAMENTO,0,'NORMAL',1,'BLOQUEADO',2,'LIBERADO') DS_ST_BLOQUEIO_FAT
           , IPC.ITEMPEDIDO SQ_ITEM_PEDIDO
           , IPC.SITUACAOITEM ST_ITEM_PEDIDO
           ,(SELECT UPPER(SII.DESCRICAO) FROM COML_SITUACOESITEM SII WHERE SII.SITUACAOITEM = IPC.SITUACAOITEM) DS_ST_ITEM_PEDIDO
           , CASE WHEN IPC.SITUACAOITEM IN (6,10,12,13,14,18) THEN 0 ELSE 1 END ST_PEDIDO_EM_ABERTO
           , PED.IDFILIALRESPONSAVEL ID_PESSOA_COMPRADOR
           , TRIM(PRE.NOME) NM_PESSOA_COMPRADOR
           , TRIM(PRE.NOMEFANTASIA) NM_PESSOA_COMPRADOR_F
           , PED.IDFILIALCOBRANCA ID_PESSOA_FATURA
           , TRIM(PFA.NOME) NM_PESSOA_FATURA
           , PED.IDFILIALENTREGA ID_PESSOA_ENTREGA
           , TRIM(PEN.NOME) NM_PESSOA_ENTREGA
           , IPC.PRECOUNITARIO PR_UNITARIO_PED
           , IPC.PRECODIGITADO PR_DIGITADO_PED
           , PED.TABELAPRECO   CD_TAB_PRECO
           --,(SELECT TTT.DT_ENTREGA FROM VW_ESP_DT_ENTR_PEDCOM TTT WHERE TTT.NR_PEDIDO = PED.PEDIDO) DT_ENTREGA
           --, FNC_ESP_DT_ENT_PED(PED.PEDIDO) DT_ENTREGA --MAIOR
           , TO_DATE(IPC.EXPEDIREM,'YYYYMMDD') DT_ENTREGA
           , CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 1 ELSE 0 END ST_PESCOM_DIF_PESFAT
           , CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 'SIM' ELSE 'NAO' END DS_ST_PESCOM_DIF_PESFAT
           , CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM PESSOASFJ FIL WHERE FIL.EMPRESA='02944599  ' AND FIL.IDPESSOAFJ NOT IN (1,2,3)) THEN 1 ELSE 0 END ST_TRANSF_LOJAS
           , CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM PESSOASFJ FIL WHERE FIL.EMPRESA='02944599  ' AND FIL.IDPESSOAFJ NOT IN (1,2,3)) THEN 'SIM' ELSE 'NAO' END DS_ST_TRANSF_LOJAS
     FROM ITENSPEDIDOCOMERCIAL IPC
         ,PEDIDOCOMERCIAL PED
         ,PESSOASFJ PRE
         ,PESSOASFJ PFA
         ,PESSOASFJ PEN
     WHERE PED.PEDIDO = IPC.PEDIDO
     AND   PRE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
     AND   PFA.IDPESSOAFJ = PED.IDFILIALCOBRANCA
     AND   PEN.IDPESSOAFJ = PED.IDFILIALENTREGA
    ) PPP

   ,(SELECT O3.NUMERO_OB NR_OB
           ,O3.KILOS_PROGRAMADOS QT_CRU_PROG_OB
           ,DECODE(O3.TOTAL_PECAS_CONFIRM,0,(ROUND(O3.KILOS_PROGRAMADOS/(SELECT MAX(PDD.PESO_PADRAO) FROM VW_ESP_PESO_PADRAO PDD WHERE PDD.REDUZIDO=O3.CODPRO_REDUZIDO),0)),O3.TOTAL_PECAS_CONFIRM) QT_PC_CRU_PROG_OB
           ,SUM(NVL(O4.QTPESOLIQUORIG,0)) QT_CRU_ORIG_OB
           ,SUM(NVL(O2.QTLIQUIDA,0)) QT_CRU_ATUAL_OB
           ,COUNT(O2.IDPECASPRODUTO) QT_PC_CRU_OB
           --,O3.KILOS_PROGRAMADOS/(SELECT PDD.PESO_PADRAO FROM VW_ESP_PESO_PADRAO PDD WHERE PDD.REDUZIDO=O3.CODPRO_REDUZIDO) QT_PC_CRU_PROG_OB
     FROM   OB_PRODUTO O3
           ,GERAPECAORIGEMOB O1
           ,GERAPECASPRODUTO O2
           ,GERAPECACOMPLPECA O4
     WHERE  O1.NUMERO_OB(+) = O3.NUMERO_OB
     AND    O2.IDPECASPRODUTO(+) = O1.IDPECASPRODUTO
     AND    O4.IDPECASPRODUTO(+) = O1.IDPECASPRODUTO
     --AND    O3.NUMERO_OB=113968
     GROUP BY O3.NUMERO_OB, O3.KILOS_PROGRAMADOS, O3.TOTAL_PECAS, O3.TOTAL_PECAS_CONFIRM,O3.CODPRO_REDUZIDO
    ) QT1

    ,(SELECT O1.NUMERO_OB NR_OB
            ,SUM(O2.QTLIQUIDA) QT_ACA_OB
            ,COUNT(O2.IDPECASPRODUTO) QT_PC_ACA_OB
            ,CASE WHEN MAX(O2.CODIGO_DEPOSITO) = 100 THEN 1 ELSE 0 END AS EH_ACAB_REPROC
      FROM  GERAPECADESTINOOB O1
           ,GERAPECASPRODUTO O2
     WHERE  O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
     GROUP BY O1.NUMERO_OB
    ) QT2

    ,(SELECT A1.NR_OB
            ,SUM(QT_ACA_DISP_OB) QT_ACA_DISP_OB
            ,SUM(QT_PC_ACA_DISP_OB) QT_PC_ACA_DISP_OB
            ,SUM(QT_ACA_RES_OB) QT_ACA_RES_OB
            ,SUM(QT_PC_RES_OB) QT_PC_ACA_RES_OB
      FROM (
            SELECT O1.NUMERO_OB NR_OB
                  ,CASE WHEN O2.STPECAPRODUTO = 0 THEN SUM(O2.QTLIQUIDA) ELSE 0 END QT_ACA_DISP_OB
                  ,CASE WHEN O2.STPECAPRODUTO = 0 THEN COUNT(O2.IDPECASPRODUTO) ELSE 0 END QT_PC_ACA_DISP_OB
                  ,CASE WHEN O2.STPECAPRODUTO = 14 THEN SUM(O2.QTLIQUIDA) ELSE 0 END QT_ACA_RES_OB
                  ,CASE WHEN O2.STPECAPRODUTO = 14 THEN COUNT(O2.IDPECASPRODUTO) ELSE 0 END QT_PC_RES_OB
            FROM  GERAPECADESTINOOB O1
                 ,GERAPECASPRODUTO O2
           WHERE  O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
           AND    O2.STPECAPRODUTO IN (0,14)--DISP E RES.PED
           GROUP BY O1.NUMERO_OB, O2.STPECAPRODUTO
          ) A1
      GROUP BY A1.NR_OB
    ) QT3

   ,(SELECT PRO.NUMERO_ROMANEIO NR_ROMANEIO
           ,NFC.NRNOTA NR_NF
           ,NFC.DTEMISSAO DT_EMISSAO_NF
     FROM   GERAREQUESTOITEMNOTA   GQI
           ,PRODUTO_ROMANEIO       PRO
           ,NOTAFISCALITENS        NFI
           ,NOTAFISCALCAPA         NFC
     WHERE  PRO.IDPRODUTO_ROMANEIO(+) = GQI.IDPRODUTO_ROMANEIO
     AND    NFI.ID(+) = GQI.IDNOTAFISCALITENS
     AND    NFC.ID(+) = NFI.IDNOTAFISCALCAPA
     AND    NFC.STNOTAFATURAMENTO <> 2
     AND    NFC.NRNOTA IS NOT NULL
     AND    NFC.IDFILIAL = 1
     GROUP BY PRO.NUMERO_ROMANEIO,NFC.NRNOTA,NFC.DTEMISSAO
    ) NFF

   ,(SELECT G1.NUMERO_OB NR_OB
           ,G2.NUMERO_PEDIDO_COMERC NR_PEDIDO
           ,G2.SEQUENCIA_PRODUTO_PE SQ_ITEM_PEDIDO
      FROM  GERAPECADESTINOOB G1
           ,OB G4
           ,GERAPECAPEDCOMERCIAL G2
           ,GERAPECASPRODUTO G3
     WHERE  G4.NUMERO_OB = G1.NUMERO_OB
     AND    G2.IDPECASPRODUTO = G1.IDPECASPRODUTO
     AND    G3.IDPECASPRODUTO = G2.IDPECASPRODUTO
     AND    G3.CODIGO_REDUZIDO_PROD = G4.CODIGO_REDUZIDO
     GROUP BY G1.NUMERO_OB,G2.NUMERO_PEDIDO_COMERC, G2.SEQUENCIA_PRODUTO_PE
    ) XXX

   ,(SELECT T.NUMERO_OB NR_OB,
           T.FASE CD_FASE_OB_BLOQ,
           DECODE(T.FASE,0,'TODAS AS FASES',(SELECT TRIM(FFL.DESCRICAO_FASE) FROM FASES_FLUXO FFL WHERE FFL.CODIGO_FASE = T.FASE)) DS_FASE_OB_BLOQ,
           CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 1 ELSE 0 END ST_OB_BLOQUEIO,
           CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 'SIM' ELSE 'NAO' END DS_ST_OB_BLOQUEIO,
           T.LIBERA_INICIO_PRODUC ST_LIB_INI_FASE,
           DECODE(T.LIBERA_INICIO_PRODUC,0,'NAO','SIM') DS_ST_LIB_INI_FASE,
           TRIM(T.OBSERVACAO) OBS_OB_BLOQUEIO,
          (SELECT TRIM(TM.DESCRICAO) FROM MOTIVO_BLOQ_OB TM WHERE TM.ID = T.IDMOTIVOBLOQ) DS_MOTIVO_BLOQUEIO,
           T.DATA_BLOQUEIO DT_HR_BLOQUEIO,
          (SELECT TRIM(VSU.NOME) FROM VW_SIS_SENHA_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) NM_USU_BLOQUEIO,
           DECODE(T.DATA_DESBLOQUEIO,TO_DATE('30/01/1900','DD/MM/YYYY'),NULL,TO_CHAR(T.DATA_DESBLOQUEIO,'DD/MM/YYYY HH24:MI:SS')) DT_H_LIBERACAO,
         (SELECT TRIM(VSU.NOME) FROM VW_SIS_SENHA_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) NM_USU_LIBERACAO
      FROM OB_BLOQUEIO T, OB OBE, VW_BNF_FASEATUALOB VFA
      WHERE OBE.NUMERO_OB = T.NUMERO_OB
      AND OBE.STATUS <> 0
      AND VFA.NUMERO_OB = T.NUMERO_OB
    ) BBB
   ,( SELECT DE1.NUMERO_OB NR_OB, COUNT(DE1.IDPECASPRODUTO) QT_PC_OB, DE5.QT_PC_ROM_FAT

      FROM  GERAPECADESTINOOB    DE1,

            (SELECT DE4.NUMERO_OB NR_OB, COUNT(DE2.IDPECASPRODUTO) QT_PC_ROM_FAT
             FROM   PECAS_ROMANEIO_SAIDA DE2,
                    ROMANEIO             DE3,
                    GERAPECADESTINOOB    DE4
             WHERE  DE3.NUMERO_ROMANEIO = DE2.NUMERO_ROMANEIO_SAID
             AND    DE4.IDPECASPRODUTO  = DE2.IDPECASPRODUTO
             AND    DE3.STATUS IN (4,6)--FATURADO/EXPEDIDO
             GROUP BY DE4.NUMERO_OB
            ) DE5

      WHERE DE5.NR_OB = DE1.NUMERO_OB
      GROUP BY DE1.NUMERO_OB, DE5.QT_PC_ROM_FAT
      HAVING COUNT(DE1.IDPECASPRODUTO)= DE5.QT_PC_ROM_FAT
    ) OB_FAT_TOTAL


   ,(SELECT G5.NUMERO_PEDIDO_COMERC NR_PEDIDO,
            G5.SEQUENCIA_PRODUTO_PE SQ_ITEM_PEDIDO,
            G7.NUMERO_OB NR_OB,
            SUM(G6.QTLIQUIDA) QT_ACA_RES_PED,
            COUNT(G6.IDPECASPRODUTO) QT_PC_ACA_RES_PEDIDO
     FROM  GERAPECAPEDCOMERCIAL G5,
           GERAPECASPRODUTO     G6,
           GERAPECADESTINOOB    G7
     WHERE G6.IDPECASPRODUTO = G5.IDPECASPRODUTO
     AND   G7.IDPECASPRODUTO = G5.IDPECASPRODUTO
     --AND  G5.NUMERO_PEDIDO_COMERC=10645
     --AND   G5.SEQUENCIA_PRODUTO_PE=1
     GROUP BY G5.NUMERO_PEDIDO_COMERC,
              G5.SEQUENCIA_PRODUTO_PE,
              G7.NUMERO_OB
    ) GGG

   ,(SELECT OBQ9.NUMERO_OB NR_OB
              ,OPTSTRAGGR(DISTINCT GPR9.GRUPO_DEFEITO) GR_DEFEITO
              ,OPTSTRAGGR(DISTINCT GPR9.TIPO_DEFEITO) TP_DEFEITO
              ,OPTSTRAGGR(DISTINCT (SELECT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) FROM SGTPRD.GRUPO_DEFEITO_QUALID GDQ WHERE GDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO)) DS_GR_DEFEITO
              ,OPTSTRAGGR(DISTINCT (SELECT TDQ.CODIGO_TIPO  || ' - ' || TRIM(TDQ.DESCRICAO_TIPO)  FROM SGTPRD.TIPO_DEFEITO_QUALIDA TDQ WHERE TDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO AND TDQ.CODIGO_TIPO = GPR9.TIPO_DEFEITO)) DS_TP_DEFEITO
        FROM   SGTPRD.GERAPECAORIGEMOB OBQ9,
               GERAPECAREVISAO         GPR9
        WHERE  GPR9.IDPECASPRODUTO = OBQ9.IDPECASPRODUTO
        GROUP BY OBQ9.NUMERO_OB
    ) DEFP

   ,(SELECT POC.NR_OB, optstraggr(POC.QT_PECA||' - '||POC.NR_NF) AS QT_PC_NF
      FROM (
      SELECT AB1.NUMERO_OB NR_OB,
             BC1.NUMERO_NOTA||' - '||TRIM(PE1.NOMEFANTASIA) NR_NF,
             COUNT(AB1.IDPECASPRODUTO) QT_PECA
      FROM GERAPECAORIGEMOB    AB1,
           GERAPECANOTAENTRADA BC1,
           PESSOASFJ           PE1
      WHERE BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
      AND  PE1.IDPESSOAFJ = BC1.IDPESSOAFJ
      GROUP BY AB1.NUMERO_OB,BC1.NUMERO_NOTA,TRIM(PE1.NOMEFANTASIA)
          ) POC
      GROUP BY POC.NR_OB
    ) QTPNF

WHERE  IAC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
AND    COR.CDREDUZIDO = IAC.CODIGO_REDUZIDO
AND    COO.CODIGO_COR = COR.CDCOR
AND    TCO.TIPOCOR = COO.TIPOCOR
AND    NV9.CDREDUZIDO = IAC.CODIGO_REDUZIDO
AND    ICR.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO_CRU
AND    TIN.NUMERO_OB(+) = OBE.NUMERO_OB
AND    OBQ.NR_OB(+) = OBE.NUMERO_OB
AND    REC.CODIGO_REDUZIDO(+) = OBE.CODIGO_REDUZIDO
AND    FAT.NUMERO_OB(+)       = OBE.NUMERO_OB
AND    FAT.SEQUENCIA(+)       = DECODE(OBE.STATUS,0,0,PKGBENF0001.FNC_RETORNA_SEQUENCIA_OB(OBE.NUMERO_OB,0))
AND    ROO.NR_OB(+)           = OBE.NUMERO_OB
AND    RRR.NR_OB(+)           = OBE.NUMERO_OB
AND    OOO.NR_OB(+)           = OBE.NUMERO_OB
/*REGRA PARA O PEDIDO COMERCIAL, PRIMEIRO DO ROMANEIO, SEGUNDO DAS PEÇAS RESERVADAS DA OB, TERCEIRO DA OB-PEDIDO(OF)*/
AND    PPP.NR_PEDIDO(+)       = NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO)
AND    PPP.SQ_ITEM_PEDIDO(+)  = NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO),OOO.SQ_ITEM_PEDIDO)
--
AND    QT1.NR_OB(+)           = OBE.NUMERO_OB
AND    QT2.NR_OB(+)           = OBE.NUMERO_OB
AND    QT3.NR_OB(+)           = OBE.NUMERO_OB
AND    NFF.NR_ROMANEIO(+)     = ROO.NR_ROMANEIO
AND    XXX.NR_OB(+)           = OBE.NUMERO_OB
AND    BBB.NR_OB(+)           = OBE.NUMERO_OB
AND    OB_FAT_TOTAL.NR_OB(+)  = OBE.NUMERO_OB
AND    DEFP.NR_OB(+)          = OBE.NUMERO_OB
AND    QTPNF.NR_OB(+)         = OBE.NUMERO_OB
--
AND    GGG.NR_PEDIDO(+)       = NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO)
AND    GGG.SQ_ITEM_PEDIDO(+)  = NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO),OOO.SQ_ITEM_PEDIDO)
AND    GGG.NR_OB(+)           = OBE.NUMERO_OB
--
AND    NVL(QT2.EH_ACAB_REPROC,0)     = 0

--AND NVL(PPP.ST_PEDIDO_EM_ABERTO,(DECODE(OBE.STATUS,0,NULL,1))) = 1 --ITENS DE PEDIDOS EM ABERTO
--AND    NVL(ROO.ST_ROM_EM_ABERTO,1) = 1 --PARA NÃO TRAZER ROMANEIOS FATURADOS

--AND  OBE.NUMERO_OB IN (174026)
--AND PPP.NR_PROGRAMACAO='0'

--AND NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO) = 13071
AND OBE.NUMERO_OB = 172557
