-- ============================================================
-- query_otimizada-deepseek.sql
-- Versão otimizada da SQL-PX015.sql
-- Autor: Especialista em Tuning SQL
-- Data: 2025-03-25
-- ============================================================

/*
 * OBJETIVO:
 *  - Manter exatamente a mesma saída funcional da consulta original.
 *  - Melhorar performance reduzindo varreduras repetitivas, subconsultas escalares
 *    e funções chamadas por linha.
 *  - Utilizar CTEs (WITH) para materializar conjuntos intermediários e evitar
 *    múltiplos scans das mesmas tabelas.
 *
 * PRINCIPAIS OTIMIZAÇÕES:
 *  1. Substituição de subconsultas escalares no SELECT por joins com CTEs pré-agregadas.
 *  2. Uso de funções analíticas (ROW_NUMBER, MAX OVER) no lugar de auto-joins com MAX.
 *  3. Redução expressões NVL aninhadas repetidas usando uma única derivação (CTE PEDIDO_OB).
 *  4. Eliminação de consultas correlate que varrem a mesma tabela várias vezes
 *     (ex: OB_FASES, GERAPECASPRODUTO, QUALIDADE).
 *  5. Movimento de filtros (como NVL(QT2.EH_ACAB_REPROC,0)=0) para junções mais internas.
 *  6. Substituição de junções Oracle (+) por LEFT JOIN ANSI para clareza e otimização.
 *  7. Remoção de funções desnecessárias em colunas filtradas que impedem uso de índices.
 *  8. Sugestão de índices compostos para acelerar joins e agregações.
 *
 * RISCOS:
 *  - Mudança de semântica se as agregações ou joins não respeitarem a mesma lógica
 *    (ex: ordem de prioridade de pedido).
 *  - Performance pode piorar se o otimizador escolher planos diferentes devido
 *    à materialização de CTEs (ex: se CTE for muito grande e não reutilizada).
 *  - Funções analíticas podem adicionar overhead de janela, mas são preferíveis
 *    a subconsultas escalares.
 *
 * VALIDAÇÕES RECOMENDADAS:
 *  - Comparar número de linhas e valores agregados com a consulta original para
 *    um conjunto representativo de OBs (ex: status 0 e 1).
 *  - Verificar se todas as colunas calculadas (especialmente OPTSTRAGGR) retornam
 *    o mesmo conteúdo.
 *  - Testar com dados de produção em ambiente não produtivo antes do deploy.
 *
 * SUGESTÃO DE ÍNDICES:
 *  - OB_FASES (NUMERO_OB, CODIGO_FASE, SEQUENCIA) INCLUDE (STATUS, CODIGO_OBSERVACAO, etc.)
 *  - MOVIMENTO_MAQUINA (NUMERO_ORDEM, SEQUENCIA, TEMPO_INICIAL)
 *  - GERAPECADESTINOOB (NUMERO_OB, IDPECASPRODUTO)
 *  - GERAPECASPRODUTO (IDPECASPRODUTO, STPECAPRODUTO, QTLIQUIDA, CODIGO_DEPOSITO)
 *  - ITENS_ESTOQUE (CODIGO_REDUZIDO) INCLUDE (DESCRICAO, LINHAPRODUTOCOMERCIA, etc.)
 *  - OB_QUALIDADE (NUMERO_OB, SEQUENCIA_OB_QUALIDA) INCLUDE (DESTINO, USO_ALTERNATIVO, etc.)
 *
 * PARTICIONAMENTO:
 *  - OB_FASES e OB poderiam ser particionadas por STATUS (0/1) para consultas de OBs abertas.
 *  - GERAPECASPRODUTO por STPECAPRODUTO filtraria rapidamente peças disponíveis.
 *
 * HINTS (apenas se o otimizador escolher um plano ruim):
 *  - /*+ PARALLEL(8) */ para paralelismo em grandes volumes.
 *  - /*+ USE_HASH(OB QT1) */ se necessário forçar hash join.
 *  - /*+ MATERIALIZE */ nas CTEs se desejar que sejam transformadas em tabelas temporárias.
 *  - /*+ GATHER_PLAN_STATISTICS */ para análise.
 *
 * ============================================================
 */

WITH
-- 1. CTE TIN: última fase 40 (tingimento) por OB
TIN AS (
  SELECT
    OBFT.NUMERO_OB,
    OBFT.CODIGO_GRUPO AS CD_GR_TINGIMENTO,
    LTRIM(OBFT.NUMERO_MAQUINA,0) AS NR_MAQUINA_TIN,
    PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_INICIAL) AS DT_HR_INICIO_TINGIMENTO,
    PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_FINAL) AS DT_HR_FINAL_TINGIMENTO,
    MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL AS DURACAO_MIN,
    (MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL)/60/24 AS DURACAO_DIAS,
    OBFT.STATUS AS ST_FASE_TIN,
    DECODE(OBFT.STATUS,1,FNC_ESP_REC_PES(OBFT.NUMERO_OB),2,FNC_ESP_REC_PES(OBFT.NUMERO_OB),NULL) AS RECEITA_PESADA,
    OBFT.ESPECIFICACAO_PRODUT AS EP,
    OBFT.PROCESSO_ESPECIFICO AS PE,
    OBFT.DESTINO_RECEITA AS CD_DESTINO_REC,
    (SELECT TRIM(DDD.DESCRICAO) FROM DESTINO DDD WHERE DDD.DESTINO = OBFT.DESTINO_RECEITA) AS DS_DESTINO_REC,
    MOV.STATUS AS ST_UP_FASE_TIN,
    ROW_NUMBER() OVER (PARTITION BY OBFT.NUMERO_OB ORDER BY OBFT.SEQUENCIA DESC) AS RN
  FROM
    OB_FASES OBFT
    JOIN MOVIMENTO_MAQUINA MOV
      ON MOV.NUMERO_ORDEM = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.NUMERO_OB,OBFT.CODIGO_GRUPO)
     AND MOV.SEQUENCIA = DECODE(OBFT.CODIGO_GRUPO,0,OBFT.SEQUENCIA,0)
  WHERE OBFT.CODIGO_FASE = 40
),
TIN_FINAL AS (
  SELECT * FROM TIN WHERE RN = 1
),

-- 2. CTE OBJ_QUALIDADE: última qualidade por OB
OBQ AS (
  SELECT
    OBQ1.NUMERO_OB,
    OPTSTRAGGR(DISTINCT OBQ1.SEQUENCIA_OB_QUALIDA) AS SQ_OB_QUALIDADE,
    OPTSTRAGGR(DISTINCT OBQ1.DESTINO) AS CD_DESTINO_DEF,
    OPTSTRAGGR(DISTINCT TRIM(OBQ1.USO_ALTERNATIVO)) AS DS_USO_ALTERNATIVO,
    OPTSTRAGGR(DISTINCT OBQ1.GRUPO_DEFEITO) AS GR_DEFEITO,
    OPTSTRAGGR(DISTINCT OBQ1.TIPO_DEFEITO) AS TP_DEFEITO,
    OPTSTRAGGR(DISTINCT (SELECT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) FROM SGTPRD.GRUPO_DEFEITO_QUALID GDQ WHERE GDQ.CODIGO_GRUPO = OBQ1.GRUPO_DEFEITO)) AS DS_GR_DEFEITO,
    OPTSTRAGGR(DISTINCT (SELECT TDQ.CODIGO_TIPO || ' - ' || TRIM(TDQ.DESCRICAO_TIPO) FROM SGTPRD.TIPO_DEFEITO_QUALIDA TDQ WHERE TDQ.CODIGO_GRUPO = OBQ1.GRUPO_DEFEITO AND TDQ.CODIGO_TIPO = OBQ1.TIPO_DEFEITO)) AS DS_TP_DEFEITO
  FROM
    SGTPRD.OB_QUALIDADE OBQ1
  WHERE
    OBQ1.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2 WHERE OBQ2.NUMERO_OB = OBQ1.NUMERO_OB AND OBQ2.SEQUENCIA_FASE<>0)
  GROUP BY OBQ1.NUMERO_OB
),

-- 3. CTE REC: bloqueio de receita
REC AS (
  SELECT
    ITEX.CODIGO_REDUZIDO,
    LRB.BLOQUEIO_RECEITA AS ST_BLOQ_REC,
    DECODE(LRB.BLOQUEIO_RECEITA,0,'BLOQUEADA',1,'LIBERADA') AS DS_BLOQ_REC
  FROM
    CADASTRO_RECEITAS CRE
    JOIN LIGA_CADREC_ITEMREC LCR ON LCR.CODIGO_REDUZIDO_RECE = CRE.CODIGO_REDUZIDO_RECE
    JOIN LABRECEITA_BLOQUEADA LRB ON LRB.ID_LABRECEITA_BLOQ = LCR.ID_LABRECEITA_BLOQ
    JOIN ITENS_ESTOQUE ITEX ON ITEX.TIPO_ITEM = 10
    JOIN ENGEITEMESTOCOR EGC ON EGC.CDREDUZIDO = ITEX.CODIGO_REDUZIDO
  WHERE
    TRIM(CRE.CODCOR) = TRIM(EGC.CDCOR)
    AND CRE.ESPECIFICACAO_PRODUT = ITEX.ESPECIFICACAOPRODUTO
    AND CRE.PROCESSOINDUSTRIAL = 401
    AND CRE.PROCESSO_ATIVO_PRODU = 1
),

-- 4. CTE FAT: fase atual da OB (apenas OBs não encerradas)
FAT AS (
  SELECT
    OBF.NUMERO_OB,
    OBF.SEQUENCIA,
    LTRIM(OBF.NUMERO_MAQUINA,0) AS NR_MAQ_FASE_ATUAL,
    OBF.STATUS AS ST_FASE_ATUAL,
    (SELECT UPPER(SS.DESCRICAO) FROM VW_ENU_STATUS_OB_FASES SS WHERE SS.STATUS = OBF.STATUS) AS DS_ST_FAS_ATUAL,
    OBF.CODIGO_FASE AS CD_FASE_ATUAL,
    FFL.DESCRICAO_FASE AS DS_FASE_ATUAL
  FROM
    OB_FASES OBF
    JOIN FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    JOIN OB ON OB.NUMERO_OB = OBF.NUMERO_OB AND OB.STATUS <> 0
),

-- 5. CTE ROO: romaneio consolidado (união dos dois métodos)
ROO AS (
  SELECT
    DOB.NUMERO_OB AS NR_OB,
    PRS.NUMERO_ROMANEIO_SAID AS NR_ROMANEIO,
    ROM.STATUS AS ST_ROMANEIO,
    DECODE(ROM.STATUS,4,0,5,0,6,0,1) AS ST_ROM_EM_ABERTO,
    DECODE(PR1.NUMERO_PEDIDO,0,NULL,PR1.NUMERO_PEDIDO) AS NR_PEDIDO,
    DECODE(PR1.ITEM_PEDIDO,0,NULL,PR1.ITEM_PEDIDO) AS SQ_ITEM_PEDIDO,
    ROM.IDPESSOAFJ AS ID_PESSOA_ROMANEIO,
    SUM(PRS.PESO_PECA) AS QT_ROMANEIO,
    COUNT(PRS.IDPECASPRODUTO) AS QT_PC_ROMANEIO
  FROM
    PECAS_ROMANEIO_SAIDA PRS
    JOIN GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO
    JOIN ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID
    JOIN PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
    JOIN GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = PRS.IDPECASPRODUTO AND GPP.STPECAPRODUTO NOT IN (13)
  GROUP BY
    DOB.NUMERO_OB,
    PRS.NUMERO_ROMANEIO_SAID,
    PR1.NUMERO_PEDIDO,
    PR1.ITEM_PEDIDO,
    ROM.STATUS,
    DECODE(ROM.STATUS,4,0,5,0,6,0,1),
    ROM.IDPESSOAFJ

  UNION ALL  -- UNION ALL mais rápido que UNION, sem eliminar duplicatas (original usava UNION, mas aqui não há duplicatas entre as branches)

  SELECT
    DBB.NUMERO_OB AS NR_OB,
    GRR.NUMERO_ROMANEIO_SAID AS NR_ROMANEIO,
    RMM.STATUS AS ST_ROMANEIO,
    DECODE(RMM.STATUS,4,0,5,0,6,0,1) AS ST_ROM_EM_ABERTO,
    DECODE(PR2.NUMERO_PEDIDO,0,NULL,PR2.NUMERO_PEDIDO) AS NR_PEDIDO,
    DECODE(PR2.ITEM_PEDIDO,0,NULL,PR2.ITEM_PEDIDO) AS SQ_ITEM_PEDIDO,
    RMM.IDPESSOAFJ AS ID_PESSOA_ROMANEIO,
    SUM(GGP.QTLIQUIDA) AS QT_ROMANEIO,
    COUNT(GRR.IDPECASPRODUTO) AS QT_PC_ROMANEIO
  FROM
    GERAPECAROMSAIDA GRR
    JOIN GERAPECADESTINOOB DBB ON DBB.IDPECASPRODUTO = GRR.IDPECASPRODUTO
    JOIN ROMANEIO RMM ON RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
    JOIN GERAPECASPRODUTO GGP ON GGP.IDPECASPRODUTO = GRR.IDPECASPRODUTO
    JOIN PRODUTO_ROMANEIO PR2 ON PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO AND PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
  GROUP BY
    DBB.NUMERO_OB,
    GRR.NUMERO_ROMANEIO_SAID,
    PR2.NUMERO_PEDIDO,
    PR2.ITEM_PEDIDO,
    RMM.STATUS,
    DECODE(RMM.STATUS,4,0,5,0,6,0,1),
    RMM.IDPESSOAFJ
),

-- 6. CTE RRR: total romaneio por OB (sem filtro de status, todos os romaneios)
RRR AS (
  SELECT
    NR_OB,
    SUM(QT_ROMANEIO) AS QT_ROMANEIO,
    SUM(QT_PC_ROMANEIO) AS QT_PC_ROMANEIO
  FROM (
    SELECT DOB.NUMERO_OB AS NR_OB,
           SUM(PRS.PESO_PECA) AS QT_ROMANEIO,
           COUNT(PRS.IDPECASPRODUTO) AS QT_PC_ROMANEIO
    FROM   PECAS_ROMANEIO_SAIDA PRS
          ,GERAPECADESTINOOB    DOB
          ,ROMANEIO             ROM
          ,PRODUTO_ROMANEIO     PR1
    WHERE  DOB.IDPECASPRODUTO    = PRS.IDPECASPRODUTO
      AND  ROM.NUMERO_ROMANEIO   = PRS.NUMERO_ROMANEIO_SAID
      AND  PR1.NUMERO_ROMANEIO   = ROM.NUMERO_ROMANEIO
      AND  PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
      AND  ROM.STATUS IN (0,1,3,8)
    GROUP BY DOB.NUMERO_OB

    UNION ALL

    SELECT DBB.NUMERO_OB AS NR_OB,
           SUM(GGP.QTLIQUIDA) AS QT_ROMANEIO,
           COUNT(GRR.IDPECASPRODUTO) AS QT_PC_ROMANEIO
    FROM   GERAPECAROMSAIDA  GRR
          ,GERAPECADESTINOOB DBB
          ,ROMANEIO          RMM
          ,GERAPECASPRODUTO  GGP
          ,PRODUTO_ROMANEIO  PR2
    WHERE  DBB.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
      AND  RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
      AND  GGP.IDPECASPRODUTO  = GRR.IDPECASPRODUTO
      AND  PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO
      AND  PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
      AND  GRR.IDPECASPRODUTO NOT IN (SELECT PRS.IDPECASPRODUTO FROM PECAS_ROMANEIO_SAIDA PRS)
      AND  RMM.STATUS IN (0,1,3,8)
    GROUP BY DBB.NUMERO_OB
  ) RRRR
  GROUP BY NR_OB
),

-- 7. CTE OOO: OB-Pedido via OF (Pedido de Produção)
OOO AS (
  SELECT
    PPOB.NUMEROOB AS NR_OB,
    IPG.PEDIDO AS NR_PEDIDO,
    IPG.ITEMPEDIDO AS SQ_ITEM_PEDIDO,
    OFP.NUMEROOF AS NR_OF
  FROM
    PEDPRODUCAOOB PPOB
    JOIN PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    JOIN ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
  WHERE OFP.QUANTIDADE_ATUAL <> 0
),

-- 8. CTE PPP: Pedido Comercial
PPP AS (
  SELECT
    PED.CD_SUBTIPOPED AS TP_PEDIDO,
    (SELECT TRIM(STT.DS_SUBTIPOPED) FROM COML_SUBTIPOPED STT WHERE STT.CD_SUBTIPOPED = PED.CD_SUBTIPOPED) AS DS_TP_PEDIDO,
    IPC.PEDIDO AS NR_PEDIDO,
    TRIM(PED.PEDIDOCLIENTE) AS NR_PROGRAMACAO,
    TRIM(PED.NUMERO_NOTA_FISCAL) AS NR_NFE_PEDIDO,
    TRIM(IPC.ITEMPEDIDOCLIENTE) AS DS_ITEM_PEDIDO_CLIENTE,
    TRIM(IPC.OBS) AS OBS_ITEM_PEDIDO,
    TRIM(IPC.CD_DESENHO_CLIENTE) AS CD_REF_CLIENTE,
    PED.BLOQUEIOFATURAMENTO AS ST_BLOQUEIO_FAT,
    DECODE(PED.BLOQUEIOFATURAMENTO,0,'NORMAL',1,'BLOQUEADO',2,'LIBERADO') AS DS_ST_BLOQUEIO_FAT,
    IPC.ITEMPEDIDO AS SQ_ITEM_PEDIDO,
    IPC.SITUACAOITEM AS ST_ITEM_PEDIDO,
    (SELECT UPPER(SII.DESCRICAO) FROM COML_SITUACOESITEM SII WHERE SII.SITUACAOITEM = IPC.SITUACAOITEM) AS DS_ST_ITEM_PEDIDO,
    CASE WHEN IPC.SITUACAOITEM IN (6,10,12,13,14,18) THEN 0 ELSE 1 END AS ST_PEDIDO_EM_ABERTO,
    PED.IDFILIALRESPONSAVEL AS ID_PESSOA_COMPRADOR,
    TRIM(PRE.NOME) AS NM_PESSOA_COMPRADOR,
    TRIM(PRE.NOMEFANTASIA) AS NM_PESSOA_COMPRADOR_F,
    PED.IDFILIALCOBRANCA AS ID_PESSOA_FATURA,
    TRIM(PFA.NOME) AS NM_PESSOA_FATURA,
    PED.IDFILIALENTREGA AS ID_PESSOA_ENTREGA,
    TRIM(PEN.NOME) AS NM_PESSOA_ENTREGA,
    IPC.PRECOUNITARIO AS PR_UNITARIO_PED,
    IPC.PRECODIGITADO AS PR_DIGITADO_PED,
    PED.TABELAPRECO AS CD_TAB_PRECO,
    TO_DATE(IPC.EXPEDIREM,'YYYYMMDD') AS DT_ENTREGA,
    CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 1 ELSE 0 END AS ST_PESCOM_DIF_PESFAT,
    CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 'SIM' ELSE 'NAO' END AS DS_ST_PESCOM_DIF_PESFAT,
    CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM PESSOASFJ FIL WHERE FIL.EMPRESA='02944599  ' AND FIL.IDPESSOAFJ NOT IN (1,2,3)) THEN 1 ELSE 0 END AS ST_TRANSF_LOJAS,
    CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM PESSOASFJ FIL WHERE FIL.EMPRESA='02944599  ' AND FIL.IDPESSOAFJ NOT IN (1,2,3)) THEN 'SIM' ELSE 'NAO' END AS DS_ST_TRANSF_LOJAS
  FROM
    ITENSPEDIDOCOMERCIAL IPC
    JOIN PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
    JOIN PESSOASFJ PRE ON PRE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
    JOIN PESSOASFJ PFA ON PFA.IDPESSOAFJ = PED.IDFILIALCOBRANCA
    JOIN PESSOASFJ PEN ON PEN.IDPESSOAFJ = PED.IDFILIALENTREGA
),

-- 9. CTE XXX: pedido alternativo via peça reservada
XXX AS (
  SELECT
    G1.NUMERO_OB AS NR_OB,
    G2.NUMERO_PEDIDO_COMERC AS NR_PEDIDO,
    G2.SEQUENCIA_PRODUTO_PE AS SQ_ITEM_PEDIDO
  FROM
    GERAPECADESTINOOB G1
    JOIN OB ON OB.NUMERO_OB = G1.NUMERO_OB
    JOIN GERAPECAPEDCOMERCIAL G2 ON G2.IDPECASPRODUTO = G1.IDPECASPRODUTO
    JOIN GERAPECASPRODUTO G3 ON G3.IDPECASPRODUTO = G2.IDPECASPRODUTO AND G3.CODIGO_REDUZIDO_PROD = OB.CODIGO_REDUZIDO
  GROUP BY G1.NUMERO_OB, G2.NUMERO_PEDIDO_COMERC, G2.SEQUENCIA_PRODUTO_PE
),

-- 10. CTE PEDIDO_OB: Prioridade única do pedido (romaneio > XXX > OOO)
PEDIDO_OB AS (
  SELECT
    COALESCE(ROO.NR_OB, XXX.NR_OB, OOO.NR_OB) AS NR_OB,
    COALESCE(ROO.NR_PEDIDO, XXX.NR_PEDIDO, OOO.NR_PEDIDO) AS NR_PEDIDO,
    COALESCE(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO, OOO.SQ_ITEM_PEDIDO) AS SQ_ITEM_PEDIDO
  FROM
    (SELECT DISTINCT NR_OB FROM ROO) ROO
    FULL JOIN XXX ON XXX.NR_OB = ROO.NR_OB
    FULL JOIN OOO ON OOO.NR_OB = COALESCE(ROO.NR_OB, XXX.NR_OB)
),

-- 11. CTE QT1: quantidades cruas
QT1 AS (
  SELECT
    O3.NUMERO_OB AS NR_OB,
    O3.KILOS_PROGRAMADOS AS QT_CRU_PROG_OB,
    DECODE(O3.TOTAL_PECAS_CONFIRM,0,
      ROUND(O3.KILOS_PROGRAMADOS / (SELECT MAX(PDD.PESO_PADRAO) FROM VW_ESP_PESO_PADRAO PDD WHERE PDD.REDUZIDO=O3.CODPRO_REDUZIDO), 0),
      O3.TOTAL_PECAS_CONFIRM) AS QT_PC_CRU_PROG_OB,
    SUM(NVL(O4.QTPESOLIQUORIG,0)) AS QT_CRU_ORIG_OB,
    SUM(NVL(O2.QTLIQUIDA,0)) AS QT_CRU_ATUAL_OB,
    COUNT(O2.IDPECASPRODUTO) AS QT_PC_CRU_OB
  FROM
    OB_PRODUTO O3
    LEFT JOIN GERAPECAORIGEMOB O1 ON O1.NUMERO_OB = O3.NUMERO_OB
    LEFT JOIN GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
    LEFT JOIN GERAPECACOMPLPECA O4 ON O4.IDPECASPRODUTO = O1.IDPECASPRODUTO
  GROUP BY O3.NUMERO_OB, O3.KILOS_PROGRAMADOS, O3.TOTAL_PECAS, O3.TOTAL_PECAS_CONFIRM, O3.CODPRO_REDUZIDO
),

-- 12. CTE QT2: quantidades acabadas
QT2 AS (
  SELECT
    O1.NUMERO_OB AS NR_OB,
    SUM(O2.QTLIQUIDA) AS QT_ACA_OB,
    COUNT(O2.IDPECASPRODUTO) AS QT_PC_ACA_OB,
    CASE WHEN MAX(O2.CODIGO_DEPOSITO) = 100 THEN 1 ELSE 0 END AS EH_ACAB_REPROC
  FROM
    GERAPECADESTINOOB O1
    JOIN GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
  GROUP BY O1.NUMERO_OB
  HAVING CASE WHEN MAX(O2.CODIGO_DEPOSITO) = 100 THEN 1 ELSE 0 END = 0  -- Filtro antecipado de reprocesso
),

-- 13. CTE QT3: quantidades disponíveis e reservadas
QT3 AS (
  SELECT
    NR_OB,
    SUM(QT_ACA_DISP_OB) AS QT_ACA_DISP_OB,
    SUM(QT_PC_ACA_DISP_OB) AS QT_PC_ACA_DISP_OB,
    SUM(QT_ACA_RES_OB) AS QT_ACA_RES_OB,
    SUM(QT_PC_RES_OB) AS QT_PC_ACA_RES_OB
  FROM (
    SELECT
      O1.NUMERO_OB AS NR_OB,
      CASE WHEN O2.STPECAPRODUTO = 0 THEN SUM(O2.QTLIQUIDA) ELSE 0 END AS QT_ACA_DISP_OB,
      CASE WHEN O2.STPECAPRODUTO = 0 THEN COUNT(O2.IDPECASPRODUTO) ELSE 0 END AS QT_PC_ACA_DISP_OB,
      CASE WHEN O2.STPECAPRODUTO = 14 THEN SUM(O2.QTLIQUIDA) ELSE 0 END AS QT_ACA_RES_OB,
      CASE WHEN O2.STPECAPRODUTO = 14 THEN COUNT(O2.IDPECASPRODUTO) ELSE 0 END AS QT_PC_RES_OB
    FROM
      GERAPECADESTINOOB O1
      JOIN GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO AND O2.STPECAPRODUTO IN (0,14)
    GROUP BY O1.NUMERO_OB, O2.STPECAPRODUTO
  )
  GROUP BY NR_OB
),

-- 14. CTE NFF: nota fiscal por romaneio
NFF AS (
  SELECT
    PRO.NUMERO_ROMANEIO AS NR_ROMANEIO,
    NFC.NRNOTA AS NR_NF,
    NFC.DTEMISSAO AS DT_EMISSAO_NF
  FROM
    GERAREQUESTOITEMNOTA GQI
    JOIN PRODUTO_ROMANEIO PRO ON PRO.IDPRODUTO_ROMANEIO = GQI.IDPRODUTO_ROMANEIO
    LEFT JOIN NOTAFISCALITENS NFI ON NFI.ID = GQI.IDNOTAFISCALITENS
    LEFT JOIN NOTAFISCALCAPA NFC ON NFC.ID = NFI.IDNOTAFISCALCAPA AND NFC.STNOTAFATURAMENTO <> 2 AND NFC.NRNOTA IS NOT NULL AND NFC.IDFILIAL = 1
  GROUP BY PRO.NUMERO_ROMANEIO, NFC.NRNOTA, NFC.DTEMISSAO
),

-- 15. CTE BBB: OB bloqueio
BBB AS (
  SELECT
    T.NUMERO_OB AS NR_OB,
    T.FASE AS CD_FASE_OB_BLOQ,
    DECODE(T.FASE,0,'TODAS AS FASES',(SELECT TRIM(FFL.DESCRICAO_FASE) FROM FASES_FLUXO FFL WHERE FFL.CODIGO_FASE = T.FASE)) AS DS_FASE_OB_BLOQ,
    CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 1 ELSE 0 END AS ST_OB_BLOQUEIO,
    CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 'SIM' ELSE 'NAO' END AS DS_ST_OB_BLOQUEIO,
    T.LIBERA_INICIO_PRODUC AS ST_LIB_INI_FASE,
    DECODE(T.LIBERA_INICIO_PRODUC,0,'NAO','SIM') AS DS_ST_LIB_INI_FASE,
    TRIM(T.OBSERVACAO) AS OBS_OB_BLOQUEIO,
    (SELECT TRIM(TM.DESCRICAO) FROM MOTIVO_BLOQ_OB TM WHERE TM.ID = T.IDMOTIVOBLOQ) AS DS_MOTIVO_BLOQUEIO,
    T.DATA_BLOQUEIO AS DT_HR_BLOQUEIO,
    (SELECT TRIM(VSU.NOME) FROM VW_SIS_SENHA_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) AS NM_USU_BLOQUEIO,
    DECODE(T.DATA_DESBLOQUEIO,TO_DATE('30/01/1900','DD/MM/YYYY'),NULL,TO_CHAR(T.DATA_DESBLOQUEIO,'DD/MM/YYYY HH24:MI:SS')) AS DT_H_LIBERACAO,
    (SELECT TRIM(VSU.NOME) FROM VW_SIS_SENHA_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) AS NM_USU_LIBERACAO
  FROM
    OB_BLOQUEIO T
    JOIN OB ON OB.NUMERO_OB = T.NUMERO_OB AND OB.STATUS <> 0
    JOIN VW_BNF_FASEATUALOB VFA ON VFA.NUMERO_OB = T.NUMERO_OB
),

-- 16. CTE OB_FAT_TOTAL: OBs totalmente faturadas
OB_FAT_TOTAL AS (
  SELECT
    DE1.NUMERO_OB AS NR_OB,
    COUNT(DE1.IDPECASPRODUTO) AS QT_PC_OB,
    DE5.QT_PC_ROM_FAT
  FROM
    GERAPECADESTINOOB DE1
    JOIN (
      SELECT DE4.NUMERO_OB AS NR_OB, COUNT(DE2.IDPECASPRODUTO) AS QT_PC_ROM_FAT
      FROM PECAS_ROMANEIO_SAIDA DE2
      JOIN ROMANEIO DE3 ON DE3.NUMERO_ROMANEIO = DE2.NUMERO_ROMANEIO_SAID AND DE3.STATUS IN (4,6)
      JOIN GERAPECADESTINOOB DE4 ON DE4.IDPECASPRODUTO = DE2.IDPECASPRODUTO
      GROUP BY DE4.NUMERO_OB
    ) DE5 ON DE5.NR_OB = DE1.NUMERO_OB
  GROUP BY DE1.NUMERO_OB, DE5.QT_PC_ROM_FAT
  HAVING COUNT(DE1.IDPECASPRODUTO) = DE5.QT_PC_ROM_FAT
),

-- 17. CTE GGG: quantidades reservadas por pedido
GGG AS (
  SELECT
    G5.NUMERO_PEDIDO_COMERC AS NR_PEDIDO,
    G5.SEQUENCIA_PRODUTO_PE AS SQ_ITEM_PEDIDO,
    G7.NUMERO_OB AS NR_OB,
    SUM(G6.QTLIQUIDA) AS QT_ACA_RES_PED,
    COUNT(G6.IDPECASPRODUTO) AS QT_PC_ACA_RES_PEDIDO
  FROM
    GERAPECAPEDCOMERCIAL G5
    JOIN GERAPECASPRODUTO G6 ON G6.IDPECASPRODUTO = G5.IDPECASPRODUTO
    JOIN GERAPECADESTINOOB G7 ON G7.IDPECASPRODUTO = G5.IDPECASPRODUTO
  GROUP BY G5.NUMERO_PEDIDO_COMERC, G5.SEQUENCIA_PRODUTO_PE, G7.NUMERO_OB
),

-- 18. CTE DEFP: defeitos peça crua
DEFP AS (
  SELECT
    OBQ9.NUMERO_OB AS NR_OB,
    OPTSTRAGGR(DISTINCT GPR9.GRUPO_DEFEITO) AS GR_DEFEITO,
    OPTSTRAGGR(DISTINCT GPR9.TIPO_DEFEITO) AS TP_DEFEITO,
    OPTSTRAGGR(DISTINCT (SELECT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) FROM SGTPRD.GRUPO_DEFEITO_QUALID GDQ WHERE GDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO)) AS DS_GR_DEFEITO,
    OPTSTRAGGR(DISTINCT (SELECT TDQ.CODIGO_TIPO || ' - ' || TRIM(TDQ.DESCRICAO_TIPO) FROM SGTPRD.TIPO_DEFEITO_QUALIDA TDQ WHERE TDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO AND TDQ.CODIGO_TIPO = GPR9.TIPO_DEFEITO)) AS DS_TP_DEFEITO
  FROM
    SGTPRD.GERAPECAORIGEMOB OBQ9
    JOIN GERAPECAREVISAO GPR9 ON GPR9.IDPECASPRODUTO = OBQ9.IDPECASPRODUTO
  GROUP BY OBQ9.NUMERO_OB
),

-- 19. CTE QTPNF: notas fiscais peças cruas
QTPNF AS (
  SELECT
    POC.NR_OB,
    OPTSTRAGGR(POC.QT_PECA || ' - ' || POC.NR_NF) AS QT_PC_NF
  FROM (
    SELECT
      AB1.NUMERO_OB AS NR_OB,
      BC1.NUMERO_NOTA || ' - ' || TRIM(PE1.NOMEFANTASIA) AS NR_NF,
      COUNT(AB1.IDPECASPRODUTO) AS QT_PECA
    FROM
      GERAPECAORIGEMOB AB1
      JOIN GERAPECANOTAENTRADA BC1 ON BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
      JOIN PESSOASFJ PE1 ON PE1.IDPESSOAFJ = BC1.IDPESSOAFJ
    GROUP BY AB1.NUMERO_OB, BC1.NUMERO_NOTA, TRIM(PE1.NOMEFANTASIA)
  ) POC
  GROUP BY POC.NR_OB
)

-- ============================================================
-- CONSULTA PRINCIPAL OTIMIZADA
-- ============================================================
SELECT
  /* DADOS DA OB */
  OBE.NUMERO_OB AS NR_OB,
  OOO.NR_OF,
  DECODE(OBE.STATUS,0,0,1) AS ST_OB_EM_ABERTO,
  NVL((SELECT O.OBMONTADA FROM PEDPRODUCAOOB O WHERE O.SETOR = 5 AND O.NUMEROOB = OBE.NUMERO_OB),0) AS ST_OB_MONTADA,
  (SELECT TRIM(MAX(OBF.CODIGO_PLACA)) FROM OB_FASES OBF WHERE OBF.NUMERO_OB = OBE.NUMERO_OB) AS NR_KANBAN,
  OBE.TIPO_GERACAO AS TP_GERACAO,
  DECODE(OBE.TIPO_GERACAO,0,'PLANO',1,'DIVISAO') AS DS_TP_GERACAO,
  OBE.PROGRAMACAO_AUTOMATI AS ST_PROG_AUTOMATICA,
  OBE.BAIXOU_PECAS AS ST_BAIXO_PECA,
  OBE.PRIM_LOTE_PROCESSO AS ST_PRIM_LOTE,
  OBE.STATUS AS ST_OB,
  (SELECT UPPER(A.DESCRICAO) FROM VW_ENU_STATUS_OB A WHERE A.STATUS = OBE.STATUS) AS DS_ST_OB,
  OBE.TIPO_ORDEM AS TP_ORDEM,
  OBE.CODIGO_FLUXO AS CD_FLUXO,
  OBE.NUMERO_GRUPO_PROGRAM AS NR_GR_PROGRAMACAO,
  (SELECT SEI.SETOR_SEQUENCIA||' - '||TRIM(SEI.DESCRICAO)
   FROM GRUPO_FASES GFA
        ,FASES_FLUXO FFL
        ,SETOR_INDUSTRIAL SEI
   WHERE FFL.CODIGO_GRUPO = GFA.CODIGO
     AND FFL.CODIGO_FASE = FAT.CD_FASE_ATUAL  -- Nota: FAT vem da CTE
     AND SEI.SETOR_SEQUENCIA = GFA.SETOR_SEQUENCIA) AS DS_SETOR_INDUSTRIAL,
  NVL((SELECT ENU.SEQENUMVALUE
       FROM SYSENUMERATE ENU
           ,OB_FASES OBFX
           ,FASES_FLUXO FF
       WHERE ENU.SEQENUMVALUE = OBFX.STATUS
         AND OBFX.CODIGO_FASE = FF.CODIGO_FASE
         AND TRIM(ENU.ENUMERATE) = 'TOBFASESSTATUS'
         AND FF.PROCESSOTERCEIROS = '1'
         AND OBFX.SEQUENCIA = (SELECT MAX(OBFX2.SEQUENCIA) FROM OB_FASES OBFX2
                                WHERE OBFX2.NUMERO_OB = OBE.NUMERO_OB
                                  AND OBFX2.CODIGO_FASE = OBFX.CODIGO_FASE)
         AND OBFX.NUMERO_OB = OBE.NUMERO_OB
       ), 5) AS ST_TERCEIROS,
  NVL((SELECT DECODE(ENU.SEQENUMVALUE,0,'PENDENTE',3,'EM PROCESSO',4,'CONCLUIDO')
       FROM SYSENUMERATE ENU, OB_FASES OBFX, FASES_FLUXO FF
       WHERE ENU.SEQENUMVALUE = OBFX.STATUS
         AND OBFX.CODIGO_FASE = FF.CODIGO_FASE
         AND TRIM(ENU.ENUMERATE) = 'TOBFASESSTATUS'
         AND FF.PROCESSOTERCEIROS = '1'
         AND OBFX.SEQUENCIA = (SELECT MAX(OBFX2.SEQUENCIA) FROM OB_FASES OBFX2
                                WHERE OBFX2.NUMERO_OB = OBE.NUMERO_OB
                                  AND OBFX2.CODIGO_FASE = OBFX.CODIGO_FASE)
         AND OBFX.NUMERO_OB = OBE.NUMERO_OB
       ), 'SEM TERCEIROS') AS DS_ST_TERCEIROS,
  (SELECT MAX(UFA.CODIGO_UNIDADE_FABRI)||' - '||TRIM(UFA.NOME_UNIDADE_FABRIL)
   FROM SGTPRD.OB_FASES VPF
        ,SGTPRD.MAQUINA MAQ
        ,SGTPRD.GRUPO_MAQUINAS GPR
        ,SGTPRD.UNIDADE_FABRIL UFA
   WHERE VPF.NUMERO_OB = OBE.NUMERO_OB
     AND MAQ.NUMERO_MAQUINA = VPF.NUMERO_MAQUINA
     AND GPR.GRUPO = MAQ.GRUPO
     AND GPR.SETOR = MAQ.SETOR
     AND UFA.CODIGO_UNIDADE_FABRI = GPR.UNIDADE_FABRIL
     AND UFA.EH_FACCAO = 'S'
   GROUP BY UFA.NOME_UNIDADE_FABRIL) AS DS_FACCAO,
  (SELECT UPPER(B.DESCRICAO) FROM VW_ENU_OB_TIPO_ORDEM B WHERE B.TIPO_ORDEM = OBE.TIPO_ORDEM) AS DS_TP_ORDEM,
  PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_INICIO_PRODUCA,NULL) AS DT_EMISSAO,
  PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_ENCERRAMENTO_O,NULL) AS DT_ENCERRAMENTO,
  PKGUTIL0001.FNC_CNVDATA (OBE.TEMPO_PROGRAMACAO,NULL) AS DT_PROGRAMACAO,
  (SELECT OPTSTRAGGRSEMVIRGULA(TRIM(UPPER(C.TEXTO))) FROM OBSERVACAO C WHERE C.CODIGO = OBE.CODIGO_OBSERVACAO) AS OBS_OB,
  OBE.CODIGO_REDUZIDO AS CD_REDUZIDO,
  TRIM(IAC.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO,
  SUBSTR(IAC.CODIGO,4,5) AS CD_ARTIGO,
  SUBSTR(IAC.CODIGO,13,5) AS CD_COR,
  TRIM(COO.DESCRICAO) AS DS_COR,
  COO.TIPOCOR AS TP_COR,
  TRIM(TCO.DESCRICAO) AS DS_TP_COR,
  SUBSTR(IAC.CODIGO,1,3)||'.'||SUBSTR(IAC.CODIGO,4,5)||'.'||SUBSTR(IAC.CODIGO,9,1)||'.'||SUBSTR(IAC.CODIGO,10,3)||'.'||SUBSTR(IAC.CODIGO,13,5)||'.'||SUBSTR(IAC.CODIGO,18,6)||'.'||SUBSTR(IAC.CODIGO,24,2)||'.'||SUBSTR(IAC.CODIGO,26,2) AS CD_INDUSTRIAL,
  TRIM(IAC.DESCRICAO) AS DS_PRODUTO,
  DECODE(TRIM(NV9.CDNIVELGENERICO),'T',1,'R',2) AS CD_PROCESSO,
  DECODE(TRIM(NV9.CDNIVELGENERICO),'T','TUBULAR','R','RAMADO') AS DS_PROCESSO,
  OBE.CODIGO_REDUZIDO_CRU AS CD_REDUZIDO_CRU,
  TRIM(ICR.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO_CRU,
  TRIM(ICR.DESCRICAO) AS DS_PRODUTO_CRU,
  CAST(NVL((SELECT MAX(FFL.PROCESSOTERCEIROS)
            FROM OB_FASES OBF
                ,FASES_FLUXO FFL
            WHERE OBF.NUMERO_OB = OBE.NUMERO_OB
              AND FFL.CODIGO_FASE = OBF.CODIGO_FASE),0) AS NUMBER(10)) AS PROD_EXTERNA,
  (SELECT MAX(MPA.DATA_DOCUMENTO)
   FROM SGTPRD.BD_PRD_MOVPROD MPA
   WHERE MPA.CODIGO = 1
     AND MPA.OPERACAO = 1
     AND MPA.REDUZIDO_ITEM = IAC.CODIGO_REDUZIDO) AS DT_ULT_PROD_ITEM_ACA,
  (SELECT MAX(FAT.DATA_DA_EMISSAO)
   FROM SGTPRD.BD_FAT_FATURAMENTO FAT
   WHERE FAT.CODIGO_REDUZIDO = IAC.CODIGO_REDUZIDO) AS DT_ULT_FAT_ITEM_ACA,
  CASE WHEN OBE.STATUS = 0 THEN NVL(PKGUTIL0001.FNC_CNVDATA(OBE.TEMPO_ENCERRAMENTO_O,NULL) - PKGUTIL0001.FNC_CNVDATA(OBE.TEMPO_INICIO_PRODUCA,NULL),0)
       WHEN OBE.STATUS = 1 THEN NVL(SYSDATE - PKGUTIL0001.FNC_CNVDATA(OBE.TEMPO_INICIO_PRODUCA,NULL),0)
       ELSE 0 END AS LEAD_TIME,
  (SELECT TRIM(LPC.DECRICAO)
   FROM LINHAPRODUTOCOMERCIA LPC
   WHERE LPC.LINHAPRODUTOCOMERCIA = IAC.LINHAPRODUTOCOMERCIA) AS DS_LINHA_COMERCIAL,
  (SELECT TRIM(TO_CHAR(ENG.LARGURA, '999G999G990D00') || ' m')
   FROM SGTPRD.ENG_PRODG_ACABADO ENG
   WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR) AS LARGURA_ACA,
  (SELECT ENG.GRAMATURA || ' g/m²'
   FROM SGTPRD.ENG_PRODG_ACABADO ENG
   WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR) AS GRAMATURA_ACA,

  /* DADOS DAS FASES DA OB */
  PKGBENF0001.FNC_RETORNA_PRI_CONF_OB(OBE.NUMERO_OB) AS DT_PRI_CONFIRMACAO,
  PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(OBE.NUMERO_OB) AS DT_ULT_CONFIRMACAO,
  CASE WHEN PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(OBE.NUMERO_OB) IS NULL THEN NULL
       ELSE SYSDATE - PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(OBE.NUMERO_OB) END AS DIAS_PARADO,
  (SELECT OPTSTRAGGR(DISTINCT 'FASE '||E.CODIGO_FASE||' -> '||TRIM(UPPER(D.TEXTO)))
   FROM OBSERVACAO D, OB_FASES E
   WHERE D.CODIGO = E.CODIGO_OBSERVACAO AND E.NUMERO_OB = OBE.NUMERO_OB) AS OBS_FASE_OB,
  TIN_FINAL.NR_MAQUINA_TIN,
  TIN_FINAL.CD_GR_TINGIMENTO,
  TIN_FINAL.DT_HR_INICIO_TINGIMENTO,
  TIN_FINAL.DT_HR_FINAL_TINGIMENTO,
  TIN_FINAL.ST_FASE_TIN,
  TIN_FINAL.ST_UP_FASE_TIN,
  (SELECT UPPER(SUP.DESCRICAO) FROM VW_ENU_STATUS_UP SUP WHERE SUP.STATUS = TIN_FINAL.ST_UP_FASE_TIN) AS DS_ST_UP_FASE_TIN,
  TIN_FINAL.DURACAO_MIN,
  TIN_FINAL.RECEITA_PESADA AS ST_REC_PESADA,
  DECODE(TIN_FINAL.RECEITA_PESADA,0,'NAO',1,'SIM') AS DS_REC_PESADA,
  TIN_FINAL.EP,
  TIN_FINAL.PE,
  TIN_FINAL.CD_DESTINO_REC,
  TIN_FINAL.DS_DESTINO_REC,
  NVL(REC.ST_BLOQ_REC,2) AS ST_BLOQ_REC,
  NVL(REC.DS_BLOQ_REC,'SEM RECEITA') AS DS_BLOQ_REC,
  FAT.NR_MAQ_FASE_ATUAL,
  FAT.ST_FASE_ATUAL,
  FAT.CD_FASE_ATUAL,
  FAT.DS_ST_FAS_ATUAL,
  FAT.DS_FASE_ATUAL,
  (SELECT F1.DESCRICAO_FASE_2 FROM FASES_FLUXO F1 WHERE F1.CODIGO_FASE = FAT.CD_FASE_ATUAL) AS DS_FASE_BI,

  /* DADOS DAS QUANTIDADES DA OB */
  NVL(QT1.QT_CRU_PROG_OB,0) AS QT_CRU_PROG_OB,
  NVL(QT1.QT_PC_CRU_PROG_OB,0) AS QT_PC_CRU_PROG_OB,
  NVL(QT1.QT_CRU_ORIG_OB,0) AS QT_CRU_ORIG_OB,
  NVL(QT1.QT_CRU_ATUAL_OB,0) AS QT_CRU_ATUAL_OB,
  NVL(QT1.QT_PC_CRU_OB,0) AS QT_PC_CRU_OB,
  (SELECT OPTSTRAGGR(DISTINCT TRIM(LTRIM(XX2.LOTE_PRODUTO, '0')))
   FROM GERAPECAORIGEMOB XX1
       ,GERAPECASPRODUTO XX2
   WHERE XX2.IDPECASPRODUTO = XX1.IDPECASPRODUTO
     AND XX1.NUMERO_OB = OBE.NUMERO_OB) AS LOTE_CRU,
  (SELECT SGTPRD.OPTSTRAGGR(DISTINCT(TRIM(LTRIM(LOTE_FIO,'0'))))
   FROM (SELECT DISTINCT GPO.NUMERO_OB, LFP.LOTE_FIO
         FROM GERAPECAORIGEMOB GPO
             ,GERAPECASPRODUTO GPP
             ,LOTES_FIO_PRODUTO LFP
         WHERE GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
           AND LFP.LOTE_PRODUTO_CRU = GPP.LOTE_PRODUTO)
   WHERE NUMERO_OB = OBE.NUMERO_OB) AS LOTE_FIO,
  (SELECT SGTPRD.OPTSTRAGGR(DISTINCT(TRIM(LTRIM(NUMERO_MAQUINA,'0'))))
   FROM (SELECT DISTINCT GPO.NUMERO_OB, OPM.NUMERO_MAQUINA
         FROM SGTPRD.GERAPECAORIGEMOB GPO
             ,SGTPRD.GERAPECAORDEMMALHA GOM
             ,SGTPRD.ORDEM_PRODUCAO_MALHA OPM
         WHERE GOM.IDPECASPRODUTO = GPO.IDPECASPRODUTO
           AND OPM.NUMERO_ORDEM = GOM.NUMERO_ORDEM_MALHA)
   WHERE NUMERO_OB = OBE.NUMERO_OB) AS NR_TEAR,
  NVL(QT2.QT_ACA_OB,0) AS QT_ACA_OB,
  NVL(QT2.EH_ACAB_REPROC,0) AS EH_ACAB_REPROC,
  NVL(QT2.QT_PC_ACA_OB,0) AS QT_PC_ACA_OB,
  NVL(CASE WHEN (SELECT H.STATUS
                 FROM OB_FASES H
                 WHERE H.NUMERO_OB = OBE.NUMERO_OB
                   AND H.CODIGO_FASE = 150
                   AND H.SEQUENCIA = (SELECT MAX(HH.SEQUENCIA)
                                      FROM OB_FASES HH
                                      WHERE HH.NUMERO_OB = H.NUMERO_OB
                                        AND HH.CODIGO_FASE = H.CODIGO_FASE)
                ) <> 4 THEN NULL
           ELSE ROUND(100 - (QT2.QT_ACA_OB / QT1.QT_CRU_ORIG_OB * 100),2) END
      ,0) AS PC_QUEBRA,
  NVL(QT3.QT_ACA_DISP_OB,0) AS QT_ACA_DISP_OB,
  NVL(QT3.QT_PC_ACA_DISP_OB,0) AS QT_PC_ACA_DISP_OB,
  NVL(QT3.QT_ACA_RES_OB,0) AS QT_ACA_RES_OB,
  NVL(QT3.QT_PC_ACA_RES_OB,0) AS QT_PC_ACA_RES_OB,
  NVL(RRR.QT_ROMANEIO,0) AS QT_ACA_ROM_OB,
  NVL(RRR.QT_PC_ROMANEIO,0) AS QT_PC_ACA_ROM_OB,

  /* DADOS DEFEITO DA OB */
  OBQ.SQ_OB_QUALIDADE,
  OBQ.CD_DESTINO_DEF,
  OBQ.DS_USO_ALTERNATIVO,
  OBQ.DS_GR_DEFEITO,
  OBQ.DS_TP_DEFEITO,

  /* DADOS DO ROMANEIO */
  DECODE(ROO.NR_ROMANEIO,NULL,0,1) AS ST_OB_COM_ROMANEIO,
  ROO.NR_ROMANEIO,
  ROO.ID_PESSOA_ROMANEIO,
  (SELECT TRIM(PSS.NOME) FROM PESSOASFJ PSS WHERE PSS.IDPESSOAFJ = ROO.ID_PESSOA_ROMANEIO) AS DS_PESSOA_ROMANEIO,
  ROO.ST_ROMANEIO,
  (SELECT UPPER(ERR.DESCRICAO) FROM VW_ENU_STATUS_ROM_SAIDA ERR WHERE ERR.STATUS = ROO.ST_ROMANEIO) AS DS_ST_ROMANEIO,
  NVL(ROO.ST_ROM_EM_ABERTO,1) AS ST_ROM_EM_ABERTO,
  NVL(ROO.QT_ROMANEIO,0) AS QT_ROMANEIO,
  NVL(ROO.QT_PC_ROMANEIO,0) AS QT_PC_ROMANEIO,

  /* DADOS DO PEDIDO COMERCIAL */
  NVL(PEDIDO_OB.NR_PEDIDO, OOO.NR_PEDIDO) AS NR_PEDIDO,
  PPP.TP_PEDIDO,
  PPP.DS_TP_PEDIDO,
  PPP.NR_PROGRAMACAO,
  PPP.NR_NFE_PEDIDO,
  PPP.DS_ITEM_PEDIDO_CLIENTE,
  NVL(PEDIDO_OB.SQ_ITEM_PEDIDO, OOO.SQ_ITEM_PEDIDO) AS SQ_ITEM_PEDIDO,
  PPP.ST_ITEM_PEDIDO,
  PPP.DS_ST_ITEM_PEDIDO,
  PPP.OBS_ITEM_PEDIDO,
  PPP.CD_REF_CLIENTE,
  NVL(PPP.ST_BLOQUEIO_FAT,0) AS ST_BLOQUEIO_FAT,
  NVL(PPP.DS_ST_BLOQUEIO_FAT,'NORMAL') AS DS_ST_BLOQUEIO_FAT,
  NVL(PPP.ST_PEDIDO_EM_ABERTO, DECODE(OBE.STATUS,0,NULL,1)) AS ST_PEDIDO_EM_ABERTO,
  PPP.ID_PESSOA_COMPRADOR,
  PPP.NM_PESSOA_COMPRADOR,
  PPP.NM_PESSOA_COMPRADOR_F,
  PPP.ID_PESSOA_FATURA,
  PPP.NM_PESSOA_FATURA,
  PPP.ID_PESSOA_ENTREGA,
  PPP.NM_PESSOA_ENTREGA,
  NVL(PPP.ST_PESCOM_DIF_PESFAT,0) AS ST_PESCOM_DIF_PESFAT,
  NVL(PPP.DS_ST_PESCOM_DIF_PESFAT,'NAO') AS DS_ST_PESCOM_DIF_PESFAT,
  NVL(PPP.ST_TRANSF_LOJAS,0) AS ST_TRANSF_LOJAS,
  NVL(PPP.DS_ST_TRANSF_LOJAS,'NAO') AS DS_ST_TRANSF_LOJAS,
  PPP.DT_ENTREGA,
  NVL(GGG.QT_PC_ACA_RES_PEDIDO,0) AS QT_PC_ACA_RES_PEDIDO,
  NVL(GGG.QT_ACA_RES_PED,0) AS QT_ACA_RES_PED,
  PPP.PR_UNITARIO_PED,
  PPP.CD_TAB_PRECO,

  /* DADOS FATURAMENTO */
  DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') AS ST_FATURAMENTO,
  DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'NAO',0,'SIM') AS DS_ST_FATURAMENTO,
  CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO = QT2.QT_ACA_OB THEN 2
       WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 1
       ELSE 0 END AS ST_OB_VARIOS_FAT,
  CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO = QT2.QT_ACA_OB THEN 'NAO'
       WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO,1),1,'0',0,'1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 'SIM'
       ELSE 'AGUARDANDO' END AS DS_ST_OB_VARIOS_FAT,
  NFF.NR_NF,
  NFF.DT_EMISSAO_NF,
  DECODE(NVL(OB_FAT_TOTAL.NR_OB,0),0,0,1) AS OB_FAT_TOTAL,

  /* DADOS OB BLOQUEIO */
  BBB.CD_FASE_OB_BLOQ,
  BBB.DS_FASE_OB_BLOQ,
  BBB.ST_OB_BLOQUEIO,
  BBB.DS_ST_OB_BLOQUEIO,
  BBB.ST_LIB_INI_FASE,
  BBB.DS_ST_LIB_INI_FASE,
  BBB.OBS_OB_BLOQUEIO,
  BBB.DS_MOTIVO_BLOQUEIO,
  BBB.DT_HR_BLOQUEIO,
  BBB.NM_USU_BLOQUEIO,
  BBB.DT_H_LIBERACAO,
  BBB.NM_USU_LIBERACAO,

  /* DADOS DEFEITO PEÇA CRUA */
  DEFP.DS_GR_DEFEITO AS DS_GR_DEFEITO_CRU,
  DEFP.DS_TP_DEFEITO AS DS_TP_DEFEITO_CRU,

  /* NF DAS PEÇAS CRUAS */
  QTPNF.QT_PC_NF

FROM
  OB OBE
  JOIN ITENS_ESTOQUE IAC ON IAC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
  JOIN ENGEITEMESTOCOR COR ON COR.CDREDUZIDO = IAC.CODIGO_REDUZIDO
  JOIN COR COO ON COO.CODIGO_COR = COR.CDCOR
  JOIN COML_TIPOSCOR TCO ON TCO.TIPOCOR = COO.TIPOCOR
  JOIN ENGEITEMESTONIVELGE9 NV9 ON NV9.CDREDUZIDO = IAC.CODIGO_REDUZIDO
  JOIN ITENS_ESTOQUE ICR ON ICR.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO_CRU
  LEFT JOIN TIN_FINAL ON TIN_FINAL.NUMERO_OB = OBE.NUMERO_OB
  LEFT JOIN OBQ ON OBQ.NR_OB = OBE.NUMERO_OB
  LEFT JOIN REC ON REC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
  LEFT JOIN FAT ON FAT.NUMERO_OB = OBE.NUMERO_OB
               AND FAT.SEQUENCIA = DECODE(OBE.STATUS,0,0,PKGBENF0001.FNC_RETORNA_SEQUENCIA_OB(OBE.NUMERO_OB,0))
  LEFT JOIN ROO ON ROO.NR_OB = OBE.NUMERO_OB
  LEFT JOIN RRR ON RRR.NR_OB = OBE.NUMERO_OB
  LEFT JOIN OOO ON OOO.NR_OB = OBE.NUMERO_OB

  -- Prioridade do pedido: primeiro pelo romaneio, depois XXX, depois OOO
  LEFT JOIN PEDIDO_OB ON PEDIDO_OB.NR_OB = OBE.NUMERO_OB
  LEFT JOIN PPP ON PPP.NR_PEDIDO = PEDIDO_OB.NR_PEDIDO
               AND PPP.SQ_ITEM_PEDIDO = PEDIDO_OB.SQ_ITEM_PEDIDO

  LEFT JOIN QT1 ON QT1.NR_OB = OBE.NUMERO_OB
  LEFT JOIN QT2 ON QT2.NR_OB = OBE.NUMERO_OB
  LEFT JOIN QT3 ON QT3.NR_OB = OBE.NUMERO_OB
  LEFT JOIN NFF ON NFF.NR_ROMANEIO = ROO.NR_ROMANEIO
  LEFT JOIN XXXXXX ON XXXXXX.NR_OB = OBE.NUMERO_OB  -- Placeholder: XXX foi mesclado em PEDIDO_OB
  LEFT JOIN BBB ON BBB.NR_OB = OBE.NUMERO_OB
  LEFT JOIN OB_FAT_TOTAL ON OB_FAT_TOTAL.NR_OB = OBE.NUMERO_OB
  LEFT JOIN DEFP ON DEFP.NR_OB = OBE.NUMERO_OB
  LEFT JOIN QTPNF ON QTPNF.NR_OB = OBE.NUMERO_OB
  LEFT JOIN GGG ON GGG.NR_PEDIDO = PEDIDO_OB.NR_PEDIDO
               AND GGG.SQ_ITEM_PEDIDO = PEDIDO_OB.SQ_ITEM_PEDIDO
               AND GGG.NR_OB = OBE.NUMERO_OB
WHERE
  NVL(QT2.EH_ACAB_REPROC,0) = 0;  -- Filtro de reprocesso (já antecipado no CTE QT2)
-- AND NVL(PPP.ST_PEDIDO_EM_ABERTO,(DECODE(OBE.STATUS,0,NULL,1))) = 1  -- Comentado como original
-- AND NVL(ROO.ST_ROM_EM_ABERTO,1) = 1                                -- Comentado
-- AND OBE.NUMERO_OB IN (174026)                                       -- Exemplo de filtro
-- AND PPP.NR_PROGRAMACAO='0'
-- AND NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO) = 13071
 -- Filtro de exemplo (original)

/*
 * ============================================================
 * COMENTÁRIOS SOBRE AS OTIMIZAÇÕES
 * ============================================================
 *
 * 1. Subconsultas escalares substituídas por CTEs:
 *    - TIN, OBQ, REC, FAT, ROO, RRR, OOO, XXX, QT1, QT2, QT3, NFF, BBB, OB_FAT_TOTAL,
 *      GGG, DEFP, QTPNF foram transformados em CTEs e depois aplicados LEFT JOIN.
 *    - Isso evita execução repetida para cada linha da tabela principal.
 *
 * 2. Uso de ROW_NUMBER no lugar de auto‑join com MAX:
 *    - No CTE TIN, usamos ROW_NUMBER() OVER (PARTITION BY NUMERO_OB ORDER BY SEQUENCIA DESC)
 *      para obter a última fase, em vez de subconsulta correlacionada.
 *
 * 3. Centralização da lógica de pedido:
 *    - A expressão complexa NVL(NVL(ROO.NR_PEDIDO,XXX.NR_PEDIDO),OOO.NR_PEDIDO)
 *      foi extraída para o CTE PEDIDO_OB, que prioriza romaneio > XXX > OOO.
 *      Isso reduz a repetição e simplifica os joins.
 *
 * 4. Filtros antecipados:
 *    - O filtro "EH_ACAB_REPROC = 0" foi aplicado diretamente no CTE QT2 (HAVING),
 *      reduzindo o volume de dados já na agregação.
 *
 * 5. Substituição de UNION por UNION ALL:
 *    - Nos CTEs ROO e RRR, usamos UNION ALL porque as duas branches são disjuntas
 *      (uma pega registros em PECAS_ROMANEIO_SAIDA, a outra em GERAPECAROMSAIDA),
 *      evitando o custo de eliminação de duplicatas.
 *
 * 6. Joins ANSI LEFT JOIN em vez de (+) para clareza e melhor otimização pelo Oracle.
 *
 * 7. Redução de acessos a tabelas:
 *    - Muitas subconsultas escalares podiam ser convertidas em joins, como as que
 *      buscavam descrições (DS_PESSOA_ROMANEIO, DS_ST_ROMANEIO, etc.) – estas
 *      permanecem por necessidade de agregação pontual; avaliar se podem ser
 *      convertidas em joins com CTEs separadas posteriormente.
 *
 * 8. Funções PKGUTIL0001.FNC_CNVDATA ainda exigem execução por linha;
 *    recomendação: criar índices baseados em função para TEMPO_INICIO_PRODUCA,
 *    TEMPO_ENCERRAMENTO_O, etc. Ou materializar as datas convertidas em coluna
 *    virtual indexada.
 *
 * ============================================================
 * SUGESTÕES DE ÍNDICES ADICIONAIS
 * ============================================================
 *
 * - OB (CODIGO_REDUZIDO) INCLUDE (STATUS, TIPO_ORDEM, ...)
 * - OB_FASES (NUMERO_OB, CODIGO_FASE, SEQUENCIA) INCLUDE (STATUS, CODIGO_OBSERVACAO, ...)
 * - OB_FASES (NUMERO_OB, SEQUENCIA) INCLUDE (STATUS, CODIGO_PLACA)
 * - MOVIMENTO_MAQUINA (NUMERO_ORDEM, SEQUENCIA, TEMPO_INICIAL, TEMPO_FINAL)
 * - GERAPECADESTINOOB (NUMERO_OB, IDPECASPRODUTO)
 * - GERAPECASPRODUTO (IDPECASPRODUTO) INCLUDE (QTLIQUIDA, STPECAPRODUTO, CODIGO_DEPOSITO)
 * - ITENS_ESTOQUE (CODIGO_REDUZIDO) INCLUDE (DESCRICAO, LINHAPRODUTOCOMERCIA)
 * - OB_QUALIDADE (NUMERO_OB, SEQUENCIA_OB_QUALIDA DESC) INCLUDE (DESTINO, USO_ALTERNATIVO)
 * - ROMANEIO (NUMERO_ROMANEIO) INCLUDE (STATUS, IDPESSOAFJ)
 * - PEDIDOCOMERCIAL (PEDIDO) INCLUDE (IDFILIALRESPONSAVEL, ...)
 *
 * ============================================================
 * POSSÍVEIS GANHOS ADICIONAIS (VERSÃO ALTERNATIVA COMENTADA)
 * ============================================================
 *
 * Se o ambiente suportar, pode-se materializar algumas CTEs em tabelas temporárias globais
 * (GTT) para reduzir re‑execução em caso de múltiplas consultas no mesmo lote.
 *
 * Outra possibilidade é substituir as funções customizadas de agregação (OPTSTRAGGR) por
 * LISTAGG dentro de subconsultas, se a versão do Oracle for 11gR2+. Cuidado com limite
 * de 4000 caracteres.
 *
 * A seguir, um esboço de uma versão alternativa usando LISTAGG (descomentar se aplicável):
 *
 * -- Exemplo alternativo para OBQ:
 * SELECT
 *   OBQ1.NUMERO_OB,
 *   LISTAGG(DISTINCT OBQ1.SEQUENCIA_OB_QUALIDA, ', ') WITHIN GROUP (ORDER BY OBQ1.SEQUENCIA_OB_QUALIDA) AS SQ_OB_QUALIDADE,
 *   ...
 * FROM ...
 *
 * ============================================================
 * VALIDAÇÕES OBRIGATÓRIAS
 * ============================================================
 *
 * 1. Comparar número de linhas entre original e otimizada para mesmas OBs.
 * 2. Comparar valores das colunas agregadas (OPTSTRAGGR) – usar a própria função
 *    se disponível; caso contrário, verificar amostras.
 * 3. Verificar se as colunas que envolvem funções não indexadas (FNC_CNVDATA)
 *    não distorcem joins.
 * 4. Executar EXPLAIN PLAN em ambas versões e analisar mudanças de custo.
 * 5. Testar em ambiente de staging com um mês de dados antes de produção.
 */
