/* =============================================================================
OBJETIVO: Consulta de usuários por ID de grupo de segurança
DOMÍNIO: 13_utilitarios_snippets
ARQUIVO ORIGINAL: 13_utilitarios_snippets/util_usuarios_consulta_grupos_ativos.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.CRISTAL, SGTPRD.SENHA_GRUPOS, SGTPRD.SETOR_USUARIO, SGTPRD.PARAMETROS_SISTEMA
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT
    U.FILIAL,
    U.ID,
    U.USUARIO,
    U.NOME,
    U.IDSETOR,
    TRIM(SUS.DESCRICAO) AS DESCR_SETOR,
    U.SITUACAO,
    (SELECT COUNT(*)
       FROM SGTPRD.SENHA_GRUPOS SG_COUNT
      WHERE SG_COUNT.CODREDUSUARIO = U.ID) AS TOT_GRUPOS,
    G.CODRED_GRUPOUSUARIO AS IDGRUPO,
    TRIM(UGR.NOME_USERLITERAL) AS DESCR_GRUPO,
    UGR.ID_SETOR_USUARIO AS IDSECTORGRP,
    TRIM(SGR.DESCRICAO) AS DESCR_SECTOR_GRP
FROM (
    SELECT
        CRI.FILIAL,
        CRI.CODREDUSUARIO AS ID,
        TRIM(CRI.USUARIO) AS USUARIO,
        UPPER(CRI.NOME_USERLITERAL) AS NOME,
        CRI.ID_SETOR_USUARIO AS IDSETOR,
        CASE
            WHEN CRI.TIPO_USUARIO = 0
             AND CRI.LIMITE_DATA_SENHA <> 0
             AND PSI.USA_LOGIN_AD <> 1
             AND TO_DATE(TO_CHAR(CRI.LIMITE_DATA_SENHA), 'YYYYMMDD') < SYSDATE
                THEN 'INACTIVO'
            ELSE 'ACTIVO'
        END AS SITUACAO
    FROM SGTPRD.CRISTAL CRI
    CROSS JOIN SGTPRD.PARAMETROS_SISTEMA PSI
    WHERE CRI.TIPO_USUARIO = 0
) U
LEFT JOIN SGTPRD.SETOR_USUARIO SUS
    ON SUS.ID = U.IDSETOR
LEFT JOIN SGTPRD.SENHA_GRUPOS G
    ON G.CODREDUSUARIO = U.ID
LEFT JOIN SGTPRD.CRISTAL UGR
    ON UGR.CODREDUSUARIO = G.CODRED_GRUPOUSUARIO
LEFT JOIN SGTPRD.SETOR_USUARIO SGR
    ON SGR.ID = UGR.ID_SETOR_USUARIO
WHERE U.ID = 563;
