-- =============================================================================
-- OBJETIVO: Custo Real da Matéria-Prima dos produtos (fechamento do mês)
-- DOMÍNIO: 10_engenharia_custos
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Custo Real da Matéria-Prima dos produtos (fechamento do mês).sql
-- TIPO: Engenharia e Ficha Técnica (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (janela dinâmica: último fechamento disponível via MAX(DATA))
-- TABELAS PRINCIPAIS: SGTPRD.CLASSE_INSUMO, SGTPRD.COML_GRUPOSPRECOSITE,
--                     SGTPRD.COML_ITEMPORGRUPODEP, SGTPRD.COML_PRECOSARTIGOS,
--                     SGTPRD.CUSTO_PROD_MPGGF_QT, SGTPRD.CUSTO_PROD_MPGGF_VL,
--                     SGTPRD.CUSTO_PRODUCAO_QUANT, SGTPRD.ENGEITEMESTOCLASSE,
--                     SGTPRD.GRUPO_INSUMO, SGTPRD.ITENS_ESTOQUE, SGTPRD.SUBGRUPO_INSUMO
-- CUIDADOS OPERACIONAIS: Substituído filtro estático de março de 2022 pela CTE
--                        materializada ULTIMO_FECHAMENTO e pré-agregação de PRECOS_VENDA.
--                        Elimina subqueries correlacionadas por linha e resolve timeout.
-- =============================================================================

WITH ULTIMO_FECHAMENTO AS (
    SELECT /*+ MATERIALIZE */ MAX(DATA) AS DATA_FECHAMENTO
      FROM SGTPRD.CUSTO_PROD_MPGGF_QT
     WHERE SETOR_PRODUTIVO = 9
),
PRECOS_VENDA AS (
    SELECT /*+ MATERIALIZE */
           R.ITEM AS CDREDUZIDO_PRODUTO,
           MAX(PAR.PRECO) AS PRECO_VENDA
      FROM SGTPRD.COML_PRECOSARTIGOS PAR
      JOIN SGTPRD.COML_ITEMPORGRUPODEP R 
        ON R.GRUPOPRECOSITEM = PAR.GRUPOPRECOSITEM
     WHERE PAR.TABELAPRECO = 9000
     GROUP BY R.ITEM
),
ITENS_INSUMO AS (
    SELECT /*+ MATERIALIZE */
           ITE.CODIGO_REDUZIDO,
           TRIM(ITE.DESCRICAO) AS DESCRICAO,
           ENG.CDGRUPO,
           TRIM(GRU.DESCRICAO_GRUPO) AS DESCRICAO_GRUPO,
           ENG.CDSUBGRUPO,
           TRIM(SUB.DESCRICAO_SUBGRUPO) AS DESCRICAO_SUBGRUPO,
           ENG.CDCLASSE,
           TRIM(CLI.DESCRICAO_CLASSE) AS DESCRICAO_CLASSE
      FROM SGTPRD.ITENS_ESTOQUE      ITE
      JOIN SGTPRD.ENGEITEMESTOCLASSE ENG ON ENG.CDREDUZIDO = ITE.CODIGO_REDUZIDO
      JOIN SGTPRD.CLASSE_INSUMO      CLI ON CLI.CODIGO_GRUPO = ENG.CDGRUPO AND CLI.CODIGO_SUBGRUPO = ENG.CDSUBGRUPO AND CLI.CODIGO_CLASSE = ENG.CDCLASSE
      JOIN SGTPRD.SUBGRUPO_INSUMO    SUB ON SUB.CODIGO_GRUPO = ENG.CDGRUPO AND SUB.CODIGO_SUBGRUPO = ENG.CDSUBGRUPO
      JOIN SGTPRD.GRUPO_INSUMO       GRU ON GRU.CODIGO_GRUPO = ENG.CDGRUPO
)
SELECT A.SETOR_PRODUTIVO,
       A.TIPO_MP,
       A.DATA,
       INS.CDGRUPO,
       INS.DESCRICAO_GRUPO,
       INS.CDSUBGRUPO,
       INS.DESCRICAO_SUBGRUPO,
       INS.CDCLASSE,
       INS.DESCRICAO_CLASSE,
       A.CDREDUZIDO_PRODUTO,
       C.QTPRODUZIDA,
       TRIM(PROD.DESCRICAO)                                  AS DESCRICAO_PRODUTO,
       A.CDREDUZIDO_MP,
       INS.DESCRICAO                                         AS DESCRICAO_QUIMICO,
       ROUND(A.QTCONSUMIDA, 4)                               AS QTCONSUMIDA,
       ROUND(B.VALOR_FICHA / NULLIF(A.QTCONSUMIDA, 0), 4)    AS VALOR_UNITARIO,
       ROUND(B.VALOR_FICHA, 4)                               AS VALOR_TOTAL,
       ROUND(B.VALOR_FICHA / NULLIF(C.QTPRODUZIDA, 0), 4)   AS CUSTO_QUIMICO,
       PV.PRECO_VENDA,
       ROUND((B.VALOR_FICHA / NULLIF(C.QTPRODUZIDA, 0)) / NULLIF(PV.PRECO_VENDA, 0) * 100, 2) AS PERC_SOBRE_PRECO
  FROM SGTPRD.CUSTO_PROD_MPGGF_QT  A
  JOIN ULTIMO_FECHAMENTO UF ON UF.DATA_FECHAMENTO = A.DATA
  JOIN SGTPRD.CUSTO_PROD_MPGGF_VL  B ON B.IDCUSTO_PROD_MPGGF_Q = A.IDCUSTO_PROD_MPGGF_Q
  JOIN SGTPRD.CUSTO_PRODUCAO_QUANT C 
    ON C.CDFILIAL = A.CDFILIAL
   AND C.DATA = A.DATA
   AND C.SETOR_PRODUTIVO = A.SETOR_PRODUTIVO
   AND C.CDREDUZIDO = A.CDREDUZIDO_PRODUTO
  JOIN ITENS_INSUMO INS ON INS.CODIGO_REDUZIDO = A.CDREDUZIDO_MP
  LEFT JOIN SGTPRD.ITENS_ESTOQUE PROD ON PROD.CODIGO_REDUZIDO = A.CDREDUZIDO_PRODUTO
  LEFT JOIN PRECOS_VENDA PV ON PV.CDREDUZIDO_PRODUTO = A.CDREDUZIDO_PRODUTO
 WHERE A.TIPO_MPGGF = 0
   AND A.SETOR_PRODUTIVO = 9
 ORDER BY INS.DESCRICAO_GRUPO DESC
 FETCH FIRST 500 ROWS ONLY
