-- =============================================================================
-- ORB-07 — diagnóstico somente leitura das classificações do universo elegível
--
-- Não alimenta o envio. Serve para a simulação pré-ativação demonstrar, por
-- classificação, quantas OBs seriam aceitas ou rejeitadas pela regra final.
-- COUNT(DISTINCT) neutraliza eventual fan-out dos vínculos comerciais.
-- =============================================================================
WITH CLASSIFICACAO_OB AS (
    SELECT V.NR_OB,
           MAX(V.CD_CLASSIFICACAO_COR)
               KEEP (DENSE_RANK LAST ORDER BY V.CD_CLASSIFICACAO_COR)
               AS CD_CLASSIFICACAO_COR,
           MAX(TRIM(V.DS_CLASSIFICACAO_COR))
               KEEP (DENSE_RANK LAST ORDER BY V.CD_CLASSIFICACAO_COR)
               AS DS_CLASSIFICACAO_COR,
           COUNT(DISTINCT V.CD_CLASSIFICACAO_COR) AS QTD_CLASSIFICACOES_COR
      FROM SGTPRD.VW_EXC_OB_PROD_CLASS_COR V
     GROUP BY V.NR_OB
)
SELECT CLS.CD_CLASSIFICACAO_COR,
       NVL(CLS.DS_CLASSIFICACAO_COR, 'SEM CLASSIFICACAO')
           AS DS_CLASSIFICACAO_COR,
       NVL(CLS.QTD_CLASSIFICACOES_COR, 0) AS QTD_CLASSIFICACOES_COR,
       CASE
           WHEN CLS.CD_CLASSIFICACAO_COR IN (6, 9)
            AND CLS.QTD_CLASSIFICACOES_COR = 1
           THEN 'ACEITA'
           ELSE 'REJEITA'
       END AS DECISAO,
       COUNT(DISTINCT OB.NUMERO_OB) AS TOTAL_OBS
  FROM SGTPRD.OB OB
 INNER JOIN SGTPRD.PEDPRODUCAOOB PPOB
    ON PPOB.NUMEROOB = OB.NUMERO_OB
  LEFT JOIN CLASSIFICACAO_OB CLS
    ON CLS.NR_OB = OB.NUMERO_OB
  LEFT JOIN SGTPRD.OFORDENS OFO
    ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO
   AND OFO.REDUZIDO = PPOB.REDUZIDO
  LEFT JOIN SGTPRD.OFPEDIDO OFP
    ON OFP.NUMEROOF = OFO.NUMEROOF
   AND OFP.NIVEL = OFO.NIVEL
   AND OFP.REDUZIDO = OFO.REDUZIDO
   AND OFP.QUANTIDADE_ATUAL <> 0
  LEFT JOIN SGTPRD.ITENSPEDIDOQTDES IPQ
    ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
  LEFT JOIN SGTPRD.ITENSPEDIDOGRADE IPG
    ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
  LEFT JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC
    ON IPC.PEDIDO = IPG.PEDIDO
   AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
  LEFT JOIN SGTPRD.PEDIDOCOMERCIAL PED
    ON PED.PEDIDO = IPC.PEDIDO
 WHERE OB.STATUS = 1
   AND PPOB.OBMONTADA = '0'
   AND (
        PED.PEDIDOCLIENTE IS NULL
     OR (PED.PEDIDOCLIENTE NOT LIKE '%R' AND PED.PEDIDOCLIENTE NOT LIKE '%S')
   )
 GROUP BY CLS.CD_CLASSIFICACAO_COR,
          NVL(CLS.DS_CLASSIFICACAO_COR, 'SEM CLASSIFICACAO'),
          NVL(CLS.QTD_CLASSIFICACOES_COR, 0),
          CASE
              WHEN CLS.CD_CLASSIFICACAO_COR IN (6, 9)
               AND CLS.QTD_CLASSIFICACOES_COR = 1
              THEN 'ACEITA'
              ELSE 'REJEITA'
          END
 ORDER BY DECISAO, CLS.CD_CLASSIFICACAO_COR NULLS LAST
