/* =============================================================================
OBJETIVO: MIX PROGRAMAÇÕES
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\MIX PROGRAMAÇÕES.sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.CADASTRO_RECEITAS, SGTPRD.COML_TIPOSCOR, SGTPRD.COR, SGTPRD.ENGEITEMESTONIVELGE9, SGTPRD.ITENS_CADASTRO_RECEI, SGTPRD.ITENS_ESTOQUE, SGTPRD.LIGA_CADREC_ITEMREC, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.PROCESSO_INDUSTRIAL, SGTPRD.UNIDADE_MEDIDA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
REVISÃO (21/09/2026): junção opcional de COML_TIPOSCOR migrada para LEFT JOIN
  ANSI e parse Oracle atual aprovado. Equivalência formal do controle legado
  permanece pendente; não homologar como equivalência 100% sem fixture não vazio.
============================================================================= */

WITH RECEITAS_CORANTE AS (
      SELECT CR.CODCOR AS RECEITA,
             TRIM(CR.DESCOR) AS DESCR_RECEITA,
             CR.ESPECIFICACAO_PRODUT AS EP,
             CR.PROCESSO_ESPECIFICO AS PE,
             CR.PROCESSO_ATIVO_PRODU AS RECEITA_ATIVA,
              TRIM(PI.DESCRICAO_PI) AS PROCESSO,
              1 AS CORANTE
        FROM SGTPRD.CADASTRO_RECEITAS CR
        JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR ON LCR.CODIGO_REDUZIDO_RECE = CR.CODIGO_REDUZIDO_RECE
        JOIN SGTPRD.ITENS_CADASTRO_RECEI ICR ON ICR.ID_LIGA_CADREC_ITEMR = LCR.ID_LIGA_CADREC_ITEMR
        JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = ICR.CODINSREDUZIDO_PADRA
        LEFT JOIN SGTPRD.PROCESSO_INDUSTRIAL PI ON PI.PROCESSO_INDUSTRIAL = CR.PROCESSOINDUSTRIAL
       WHERE CR.PROCESSO_ATIVO_PRODU = 1
         AND UPPER(TRIM(ITE.GRUPO_ESTOQUE)) LIKE 'CORANTE%'
),
RECEITAS AS (
       SELECT RECEITA, DESCR_RECEITA, EP, PE, RECEITA_ATIVA, CORANTE,
              LISTAGG(PROCESSO, ',' ON OVERFLOW TRUNCATE)
                  WITHIN GROUP (ORDER BY PROCESSO) AS PROCESSO
         FROM (SELECT DISTINCT RECEITA, DESCR_RECEITA, EP, PE, RECEITA_ATIVA, CORANTE, PROCESSO
                FROM RECEITAS_CORANTE)
        GROUP BY RECEITA, DESCR_RECEITA, EP, PE, RECEITA_ATIVA, CORANTE
),
ITENS_PEDIDO AS (
      SELECT IPC.PEDIDO AS NRPEDIDO,
             IPC.ITEMPEDIDO,
             IPC.ITEMPEDIDOCLIENTE AS ITEMCLIENTE,
             IPC.CD_DESENHO_CLIENTE AS CAD_CLIENTE,
             TRIM(ITE.CODIGO_ALTERNATIVO) AS CODALTERNATIVO,
             IPC.REDUZIDOITEM AS CODREDUZIDO,
             TRIM(ITE.CODIGO) AS CODINDUSTRIAL,
             TRIM(ITE.DESCRICAO) AS DESCPRODUTO,
             TRIM(COR.CODIGO_COR) AS CODCOR,
             TRIM(COR.DESCRICAO) AS DESCCOR,
              COR.TIPOCOR,
             IPC.QUANTIDADE_DIGITACAO AS QTDEDIGITADA,
             IPC.IDUMDIGITACAO AS IDUNIMEDDIG,
             TRIM(UMD.DSSIGLA) AS SIGLAUNIMEDDIG,
             IPC.QUANTIDADE AS QTDEPADRAO,
             TRIM(UMP.DSSIGLA) AS SIGLAUNIMEDPADRAO,
             IPC.SITUACAOITEM AS STATUS,
             ITE.TIPO_ITEM,
             CAST(DECODE(NVL(IPC.DTEMISSAO, 0), 0, DATE '1899-12-30', TO_DATE(TO_CHAR(IPC.DTEMISSAO), 'YYYYMMDD')) AS DATE) AS DATAEMISSAO
        FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
        JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
        JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = IPC.REDUZIDOITEM
        LEFT JOIN SGTPRD.ENGEITEMESTOCOR EIC ON EIC.CDREDUZIDO = IPC.REDUZIDOITEM
        LEFT JOIN SGTPRD.COR COR ON COR.CODIGO_COR = EIC.CDCOR
        LEFT JOIN SGTPRD.UNIDADE_MEDIDA UMD ON UMD.IDUNIDADEMEDIDA = IPC.IDUMDIGITACAO
        LEFT JOIN SGTPRD.UNIDADE_MEDIDA UMP ON UMP.IDUNIDADEMEDIDA = IPC.IDUNIDADEMEDIDA
       WHERE IPC.SITUACAOITEM <> 6
         AND IPC.IDUMDIGITACAO <> 1
         AND ITE.TIPO_ITEM = 10
)
SELECT 
     CASE WHEN REC.PROCESSO IS NULL AND PD.TIPOCOR = 1               THEN 'PRÉ ALVEJADO (MARFIM)'
          WHEN REC.PROCESSO IS NULL AND PD.TIPOCOR = 7               THEN 'LAVAÇÃO'
          WHEN REC.PROCESSO IS NULL AND PD.TIPOCOR = 16              THEN 'DIRETO EM RAMA'
          WHEN REC.PROCESSO IS NULL AND PD.TIPOCOR = 17              THEN 'DIRETO EM RAMA'
          WHEN REC.PROCESSO = 'OTICO'                                THEN 'BRANCO'
          WHEN REC.PROCESSO = 'ENXOFRE'                              THEN 'PRETO ENXOFRE'
     ELSE REC.PROCESSO
     END PROCESSO,
     PD.*
FROM (
      -- Subconsulta para obter os dados da receita
      SELECT CDR.RECEITA,
             CDR.DESCR_RECEITA,
             CDR.EP,
             CDR.PE,
             CDR.RECEITA_ATIVA,
             MAX(CDR.PROCESSO) PROCESSO
        FROM RECEITAS CDR
       WHERE CDR.RECEITA_ATIVA = 1
         AND CDR.CORANTE       = 1
       GROUP BY CDR.RECEITA,
                CDR.DESCR_RECEITA,
                CDR.EP,
                CDR.PE,
                CDR.RECEITA_ATIVA
     ) REC
     RIGHT JOIN
     (
      -- Subconsulta para obter os dados do pedido
      SELECT ITP.NRPEDIDO,
             ITP.ITEMPEDIDO,
             PED.PEDIDOCLIENTE,
             ITP.ITEMCLIENTE,
             ITP.CAD_CLIENTE,
             ITP.DATAEMISSAO,
             ITP.CODALTERNATIVO,
             ITP.CODREDUZIDO,
             ITP.CODINDUSTRIAL,
             ITP.DESCPRODUTO,
             (SELECT DECODE(TRIM(ENG.CDNIVELGENERICO),
                            'T',
                            'TUBULAR',
                            'R',
                            'RAMADO')
                FROM SGTPRD.ENGEITEMESTONIVELGE9 ENG
               WHERE ENG.CDREDUZIDO = ITP.CODREDUZIDO) FLUXO,                              
             ITE.ESPECIFICACAOPRODUTO EP,
             ITP.CODCOR,
             ITP.DESCCOR,
             TPC.TIPOCOR,
             ITP.TIPOCOR AS DESCR_TPCOR,
             ITP.QTDEDIGITADA,
             ITP.SIGLAUNIMEDDIG,
             ITP.QTDEPADRAO,
             ITP.SIGLAUNIMEDPADRAO
        FROM ITENS_PEDIDO ITP
        JOIN SGTPRD.COR                       COR
          ON TRIM(COR.CODIGO_COR) = ITP.CODCOR
        LEFT JOIN SGTPRD.COML_TIPOSCOR        TPC
          ON TPC.TIPOCOR = COR.TIPOCOR
        JOIN SGTPRD.PEDIDOCOMERCIAL           PED
          ON PED.PEDIDO = ITP.NRPEDIDO
        JOIN SGTPRD.ITENS_ESTOQUE             ITE
          ON ITE.CODIGO_REDUZIDO = ITP.CODREDUZIDO
       WHERE ITP.STATUS          <> 6
         AND ITP.IDUNIMEDDIG     <> 1
         AND ITP.TIPO_ITEM       = 10
      ) PD
     ON REC.RECEITA = PD.CODCOR 
     AND REC.EP      = PD.EP
     
WHERE TRUNC(PD.DATAEMISSAO) >= TRUNC(SYSDATE, 'IW') - 7 --filtrar os pedidos emitidos na semana atual
