/* =============================================================================
OBJETIVO: Entrada de NFs dos terceirizados (passar a programação da semana)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Entrada de NFs dos terceirizados (passar a programação da semana).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.DEPOSITO, SGTPRD.GERAPECANOTAENTRADA, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.ITENS_NOTA_ENTRADA, SGTPRD.LOTE_ITENS_NOTA_ENTR, SGTPRD.MESTRE_NOTA_ENTRADA, SGTPRD.PESSOASFJ
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH PEC AS (
              SELECT LIN.NUMERO_NOTA,
                     LIN.SERIE_NOTA,
                     LIN.IDPESSOAFJ,
                     LIN.CODINSREDUZIDO,
                     LIN.SEQUENCIA_DIGITACAO,
                     LIN.QUALIDADE,
                     DECODE(SUM(GPN.QTPESOLIQORIGPECANFE), 0, SUM(GPP.QTLIQUIDA), SUM(GPN.QTPESOLIQORIGPECANFE)) QT_TOTAL,
                     COUNT(GPP.IDPECASPRODUTO) QT_VOL_PESADO
              FROM SGTPRD.LOTE_ITENS_NOTA_ENTR LIN
              LEFT JOIN SGTPRD.GERAPECANOTAENTRADA GPN
                  ON GPN.NUMERO_NOTA = LIN.NUMERO_NOTA
                  AND GPN.SERIE_NOTA = LIN.SERIE_NOTA
                  AND GPN.IDPESSOAFJ = LIN.IDPESSOAFJ
                  AND GPN.CODINSREDUZIDO = LIN.CODINSREDUZIDO
                  AND GPN.SEQUENCIA_DIGITACAO = LIN.SEQUENCIA_DIGITACAO
                  AND GPN.LOTE = LIN.LOTE
                  AND GPN.QUALIDADE = LIN.QUALIDADE
              LEFT JOIN SGTPRD.GERAPECASPRODUTO GPP
                  ON GPP.IDPECASPRODUTO = GPN.IDPECASPRODUTO
              WHERE LIN.STFINALIZACAO = 2 --LOTE FINALIZADO
              GROUP BY LIN.NUMERO_NOTA,
                       LIN.SERIE_NOTA,
                       LIN.IDPESSOAFJ,
                       LIN.CODINSREDUZIDO,
                       LIN.SEQUENCIA_DIGITACAO,
                       LIN.QUALIDADE
               )
SELECT MNE.CDFILIAL                                      AS CD_FILIAL,
       TO_DATE(MNE.DATA_DA_ENTRADA, 'YYYYMMDD')          AS DT_ENTRADA,
       MNE.NUMERO_NOTA                                   AS NR_NOTA,
       --TRIM(MNE.NATOPERACAO)                             AS CFOP,
       MNE.IDPESSOAFJ_CLIENTE                            AS ID_FORNECEDOR,
       --TRIM(PES.NOME)                                    AS NM_FORNECEDOR,
       TRIM(PES.NOMEFANTASIA)                            AS NM_FANTASIA,
       --PES.IDCATEGORIFORNECEDOR                          AS ID_CAT_FORNECEDOR,
       ITE.TIPO_ITEM                                     AS TP_ITEM,
       INE.CODINSREDUZIDO                                AS CD_REDUZIDO,
       SUBSTR(ITE.CODIGO,6,3)                            AS ARTIGO,
       TRIM(ITE.DESCRICAO)                               AS DS_PRODUTO,
       --INE.PRECO_UNITARIO                                AS PR_NF_LIQ,
       --INE.PRECO                                         AS PR_NF_BRT,
       LTI.QUALIDADE                                     AS QS,
       LTI.VOLUMES                                       AS QT_VOL_NF,
       SUM(LTI.QUANTIDADE)                               AS QT_TOTAL_NF,
       PEC.QT_VOL_PESADO                                 AS QT_VOL_PESADO,
       NVL(PEC.QT_TOTAL, 0)                              AS QT_TOTAL_BALANCA,
       SUM(LTI.QUANTIDADE) * INE.PRECO                   AS VL_TOTAL_NF,
       -1 * (SUM(LTI.QUANTIDADE) - NVL(PEC.QT_TOTAL, 0)) AS DIF_NF_PESAGEM,
       CASE
           WHEN NVL(PEC.QT_TOTAL, 0) = 0 THEN 'AGUARDANDO PESAGEM'
           WHEN (NVL(PEC.QT_TOTAL, 0) <> 0 AND SUM(LTI.QUANTIDADE) - NVL(PEC.QT_TOTAL, 0) < 0) THEN 'GANHO'
           WHEN (NVL(PEC.QT_TOTAL, 0) <> 0 AND SUM(LTI.QUANTIDADE) - NVL(PEC.QT_TOTAL, 0) = 0) THEN 'EQUIVALENTE'
           WHEN (NVL(PEC.QT_TOTAL, 0) <> 0 AND SUM(LTI.QUANTIDADE) - NVL(PEC.QT_TOTAL, 0) > 0) THEN 'PERDA'
           ELSE ''
       END AS DS_ANALISE_PESAGEM,
       -1 * (100 - (ROUND(NVL(PEC.QT_TOTAL, 0) / NULLIF(SUM(LTI.QUANTIDADE), 0) * 100, 2))) AS PERC_QUEBRA_PESAGEM
       
FROM SGTPRD.MESTRE_NOTA_ENTRADA MNE
INNER JOIN SGTPRD.ITENS_NOTA_ENTRADA INE
    ON INE.NUMERO_NOTA = MNE.NUMERO_NOTA
    AND INE.SERIE_NOTA = MNE.SERIE_NOTA
    AND INE.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
LEFT JOIN SGTPRD.LOTE_ITENS_NOTA_ENTR LTI
    ON LTI.NUMERO_NOTA = INE.NUMERO_NOTA
    AND LTI.SERIE_NOTA = INE.SERIE_NOTA
    AND LTI.IDPESSOAFJ = INE.IDPESSOAFJ
    AND LTI.SEQUENCIA_DIGITACAO = INE.SEQUENCIA_DIGITACAO
    AND LTI.CODINSREDUZIDO = INE.CODINSREDUZIDO
LEFT JOIN PEC
    ON PEC.NUMERO_NOTA = INE.NUMERO_NOTA
    AND PEC.SERIE_NOTA = INE.SERIE_NOTA
    AND PEC.IDPESSOAFJ = INE.IDPESSOAFJ
    AND PEC.CODINSREDUZIDO = INE.CODINSREDUZIDO
    AND PEC.SEQUENCIA_DIGITACAO = INE.SEQUENCIA_DIGITACAO
    AND PEC.QUALIDADE = LTI.QUALIDADE
INNER JOIN SGTPRD.PESSOASFJ PES
    ON PES.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
INNER JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON ITE.CODIGO_REDUZIDO = INE.CODINSREDUZIDO
WHERE TO_CHAR(TO_DATE(MNE.DATA_DA_ENTRADA, 'YYYYMMDD'), 'IW') = TO_CHAR(CURRENT_DATE, 'IW') - 1 --APENAS A SEMANA ANTERIOR
  AND TO_CHAR(TO_DATE(MNE.DATA_DA_ENTRADA, 'YYYYMMDD'), 'YYYY') = TO_CHAR(CURRENT_DATE, 'YYYY') --APENAS O ANO ATUAL
  AND INE.DEPOSITO IN (SELECT DEP.CODIGO_DEPOSITO FROM SGTPRD.DEPOSITO DEP WHERE DEP.SOCONTROLAQUILOS = '0') --DEPOSITOS CONTROLADOS EM KG
  AND MNE.STATUS               = 5 --NOTA CONFIRMADA
  --AND NVL(PEC.QT_TOTAL, 0)     = 0 --AGUARDANDO PESAGEM
  AND LTI.QUALIDADE            = 1 --PRIMEIRA QUALIDADE
  AND ITE.TIPO_ITEM            = 9 --MALHA CRUA
  AND PES.IDCATEGORIFORNECEDOR = 1 --FACO
GROUP BY MNE.CDFILIAL,
         TO_DATE(MNE.DATA_DA_ENTRADA, 'YYYYMMDD'),
         MNE.NUMERO_NOTA,
         TRIM(MNE.NATOPERACAO),
         MNE.IDPESSOAFJ_CLIENTE,
         PES.NOME,
         PES.NOMEFANTASIA,
         PES.IDCATEGORIFORNECEDOR,
         ITE.TIPO_ITEM,
         INE.CODINSREDUZIDO,
         SUBSTR(ITE.CODIGO,6,3), 
         ITE.DESCRICAO,
         INE.PRECO_UNITARIO,
         INE.PRECO,
         LTI.QUALIDADE,
         LTI.VOLUMES,
         PEC.QT_TOTAL,
         QT_VOL_PESADO
ORDER BY TO_DATE(MNE.DATA_DA_ENTRADA, 'YYYYMMDD'), PES.NOMEFANTASIA, SUBSTR(ITE.CODIGO,6,3), ITE.DESCRICAO
