/* =============================================================================
OBJETIVO: Conferência - Peças (EMBALADEIRA)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - Peças (EMBALADEIRA).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.PEDPRODUCAOOB, SGTPRD.PEDPRODUCAO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.PEDIDOCOMERCIAL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH ORIGEM AS (
                SELECT O.NUMERO_OB, COUNT(O.IDPECASPRODUTO) AS PS_ORI
                  FROM SGTPRD.GERAPECAORIGEMOB O
                GROUP BY O.NUMERO_OB
                ),
     DESTINO AS (
                 SELECT D.NUMERO_OB, COUNT(D.IDPECASPRODUTO) AS PS_DES
                   FROM SGTPRD.GERAPECADESTINOOB D
                 INNER JOIN SGTPRD.GERAPECASPRODUTO GPP ON D.IDPECASPRODUTO = GPP.IDPECASPRODUTO
                  WHERE GPP.STPECAPRODUTO IN (13, 14, 4, 0)
                 GROUP BY D.NUMERO_OB
                  ),
     FASES_UP AS (
                SELECT UOM.NUMEROORDEMREAL AS NUMERO_OB,
                       UOM.SEQUENCIAORDEMREAL AS SEQ,
                       UPR.DTTEMPOFINAL AS DATA_HORA_FINAL
                  FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
                  JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
                 WHERE UPR.SETOR = 5
                   AND UPR.EXCLUIDA = 0
                   AND UPR.TIPOUP = 0
                  ),
     PEDIDO_OB AS (
                SELECT IPG.PEDIDO,
                       PC.PEDIDOCLIENTE,
                       IPG.ITEMPEDIDO,
                       PPOB.NUMEROOB
                  FROM SGTPRD.PEDPRODUCAOOB PPOB
                  JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
                  JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO
                                          AND OFO.REDUZIDO = PPOB.REDUZIDO
                  JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF
                                           AND OFP.NIVEL = OFO.NIVEL
                                           AND OFP.REDUZIDO = OFO.REDUZIDO
                  JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
                  JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
                  JOIN SGTPRD.PEDIDOCOMERCIAL PC ON PC.PEDIDO = IPG.PEDIDO
                  JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = IPG.PEDIDO
                                                       AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
                 WHERE OFP.QUANTIDADE_ATUAL <> 0
                  )
SELECT
    OBP.PEDIDO                            AS PEDIDO,
    OBP.PEDIDOCLIENTE                     AS PROG,
    OBE.NUMERO_OB                         AS NR_OB,
    OBFX.DATA_HORA_FINAL                  AS DT_HR_FINAL,
    TRIM(ITE.CODIGO_ALTERNATIVO)          AS ALTERNATIVO,
    DES.PS_DES - ORI.PS_ORI             AS DIF,
    ORI.PS_ORI                           AS PS_ORI,
    DES.PS_DES                           AS PS_DES
FROM
    SGTPRD.OB OBE
INNER JOIN
    SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
INNER JOIN
    SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = OBE.NUMERO_OB
INNER JOIN
    FASES_UP OBFX ON OBFX.NUMERO_OB = OBE.NUMERO_OB AND OBFX.SEQ = OBF.SEQUENCIA
INNER JOIN
    PEDIDO_OB OBP ON OBP.NUMEROOB = OBE.NUMERO_OB
INNER JOIN
    SGTPRD.ITENSPEDIDOCOMERCIAL ITP ON ITP.PEDIDO = OBP.PEDIDO AND ITP.ITEMPEDIDO = OBP.ITEMPEDIDO
INNER JOIN
    ORIGEM ORI ON ORI.NUMERO_OB = OBE.NUMERO_OB
INNER JOIN
    DESTINO DES ON DES.NUMERO_OB = OBE.NUMERO_OB
WHERE
    OBF.CODIGO_FASE = 150
    AND (TRIM(OBP.PEDIDOCLIENTE) NOT LIKE '%S' AND TRIM(OBP.PEDIDOCLIENTE) NOT LIKE '%R')
    AND OBF.STATUS = 4
    AND TRUNC(OBFX.DATA_HORA_FINAL) >= TRUNC(SYSDATE, 'MONTH')
    AND ORI.PS_ORI <> DES.PS_DES
ORDER BY
    OBFX.DATA_HORA_FINAL
