/* =============================================================================
OBJETIVO: Consulta - produção de artigos ramados de acordo configuração malharia
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta - produção de artigos ramados de acordo configuração malharia.sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTONIVELGE, SGTPRD.ENG_PRODG_ACABADO, SGTPRD.FICHA_MALHA, SGTPRD.FICHA_RETILINEA, SGTPRD.FIOS_FICHA_MALHARIA_, SGTPRD.ITENS_COMPLEMENTO, SGTPRD.ITENS_COMPLEMENTO_FI, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.ORDEM_PRODUCAO_MALHA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH OPM_REL AS (
    SELECT M.NUMERO_MAQUINA,
           COALESCE(MIN(CASE WHEN O.STATUS = 3 THEN O.NUMERO_ORDEM END),
                    MIN(CASE WHEN O.STATUS = 1 THEN O.NUMERO_ORDEM END),
                    MIN(CASE WHEN O.STATUS = 2 THEN O.NUMERO_ORDEM END)) AS NUMERO_ORDEM
      FROM SGTPRD.MAQUINA M
      LEFT JOIN SGTPRD.ORDEM_PRODUCAO_MALHA O ON O.NUMERO_MAQUINA = M.NUMERO_MAQUINA
                                              AND O.STATUS IN (1, 2, 3)
     WHERE M.SETOR IN (4, 7)
       AND M.CODIGO_UNIDADE_FABRI = '00005'
       AND M.TIPO_MAQUINA IN (145, 146)
     GROUP BY M.NUMERO_MAQUINA
 ), OPM_ALVO AS (
     SELECT DISTINCT OPM.CODIGO_REDUZIDO_PROD,
                     MAQ.GRUPO
       FROM SGTPRD.ORDEM_PRODUCAO_MALHA OPM
       JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OPM.NUMERO_MAQUINA
       JOIN OPM_REL R ON R.NUMERO_ORDEM = OPM.NUMERO_ORDEM
      WHERE OPM.STATUS <> 0
 ), PRODUCAO_CALC_RAW AS (
    SELECT FMA.CODPROREDUZIDO AS CODIGO_REDUZIDO,
           FMA.GRUPO,
           SUM((453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 * FFI.CONES /
               (DECODE(NVL(ICF.TITULO_FIO_NE, 0), 0, 0.00001, ICF.TITULO_FIO_NE) *
                DECODE(NVL(FFI.INDIESTITITULO, 0), 0, 1, FFI.INDIESTITITULO)) *
                FMA.RPM * 60 / 1000)) AS KG_HORA,
           SUM((453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 * FFI.CONES /
               (DECODE(NVL(ICF.TITULO_FIO_NE, 0), 0, 0.00001, ICF.TITULO_FIO_NE) *
                DECODE(NVL(FFI.INDIESTITITULO, 0), 0, 1, FFI.INDIESTITITULO)) *
                DECODE(NVL(FFI.NUMERO_CABOS, 0), 0, 1, FFI.NUMERO_CABOS) *
                FMA.RPM * 60 / 1000)) AS KG_HORA_EFIC
       FROM SGTPRD.FICHA_MALHA FMA
       JOIN OPM_ALVO ALV ON ALV.CODIGO_REDUZIDO_PROD = FMA.CODPROREDUZIDO
                         AND ALV.GRUPO = FMA.GRUPO
       LEFT JOIN SGTPRD.FIOS_FICHA_MALHARIA_ FFI ON FFI.GRUPO_MAQUINA = FMA.GRUPO
                                               AND FFI.CODIGO_PRODUTO = FMA.CODPROREDUZIDO
      LEFT JOIN SGTPRD.ITENS_COMPLEMENTO_FI ICF ON ICF.CODIGO_REDUZIDO = FFI.CODIGO_FIO
     GROUP BY FMA.CODPROREDUZIDO, FMA.GRUPO, FMA.RPM
    UNION ALL
    SELECT FMA.CODIGO_PRODUTO,
           FMA.GRUPO_MAQUINA,
           (FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60) /
             ((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS) * 1000),
           ((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60) /
             ((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS) * 1000)) * (FMA.EFICIENCIA_ESTIMADA / 100)
       FROM SGTPRD.FICHA_RETILINEA FMA
       JOIN OPM_ALVO ALV ON ALV.CODIGO_REDUZIDO_PROD = FMA.CODIGO_PRODUTO
                         AND ALV.GRUPO = FMA.GRUPO_MAQUINA
       LEFT JOIN SGTPRD.ITENS_ESTOQUE EAI ON EAI.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO
       LEFT JOIN SGTPRD.ENG_PRODG_CRU EPC ON EPC.REDUZIDO_AGRUPADOR = EAI.REDUZIDO_AGRUPADOR
 ), PRODUCAO_CALC AS (
     SELECT CALC.CODIGO_REDUZIDO,
            CALC.GRUPO,
            SUM(CALC.KG_HORA) AS KG_HORA,
            SUM(CALC.KG_HORA_EFIC) AS KG_HORA_EFIC
       FROM PRODUCAO_CALC_RAW CALC
      GROUP BY CALC.CODIGO_REDUZIDO, CALC.GRUPO
 ), PROD_MALHARIA AS (
    SELECT TRIM(ART.CDARTIGOCRU) AS ARTIGO,
           OPM.CODIGO_REDUZIDO_PROD AS REDUZIDO,
           TRIM(ITE.DESCRICAO) AS DESCRICAO_PRODUTO,
           TRIM(FX.CDNIVELGENERICO) AS FLUXO,
           ROUND(SUM(PRO.KG_HORA * 24), 2) AS KG_DIA_EFIC100,
           ROUND((SUM(PRO.KG_HORA * 24) / NULLIF(SUM(SUM(PRO.KG_HORA * 24)) OVER(), 0)) * 100, 2) AS PERCENTUAL,
           ROUND(SUM(PRO.KG_HORA_EFIC * 24), 2) AS KG_DIA_EFIC,
           COUNT(OPM.NUMERO_ORDEM) AS QT_ORD_ABERTO,
           ROUND(SUM(PRO.KG_HORA_EFIC * 24) / NULLIF(COUNT(OPM.NUMERO_ORDEM), 0), 2) AS KG_DIA_EFIC_POR_MQ
      FROM SGTPRD.ORDEM_PRODUCAO_MALHA OPM
      JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OPM.NUMERO_MAQUINA
      JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = OPM.CODIGO_REDUZIDO_PROD
      JOIN SGTPRD.ENGEITEMESTONIVELGE FX ON FX.CDREDUZIDO = OPM.CODIGO_REDUZIDO_PROD
      JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OPM.CODIGO_REDUZIDO_PROD
      LEFT JOIN PRODUCAO_CALC PRO ON PRO.CODIGO_REDUZIDO = OPM.CODIGO_REDUZIDO_PROD
                                 AND PRO.GRUPO = MAQ.GRUPO
     WHERE OPM.STATUS <> 0
       AND EXISTS (SELECT 1 FROM OPM_REL R WHERE R.NUMERO_ORDEM = OPM.NUMERO_ORDEM)
     GROUP BY TRIM(ART.CDARTIGOCRU), OPM.CODIGO_REDUZIDO_PROD, TRIM(ITE.DESCRICAO), TRIM(FX.CDNIVELGENERICO)
),
  
  RENDIMENTO AS
  (
    SELECT
      SUBSTR(ITE.CODIGO, 4, 5) AS ARTIGO,
      TRIM(FX.CDNIVELGENERICO) AS FLUXO,
      1000 / (ENG.GRAMATURA * CASE WHEN TRIM(FX.CDNIVELGENERICO) = 'R' THEN ENG.LARGURA ELSE ENG.LARGURA * 2 END) AS REND_MTS_KG
    FROM 
      SGTPRD.ENG_PRODG_ACABADO ENG 
      JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.REDUZIDO_AGRUPADOR = ENG.REDUZIDO_AGRUPADOR
      JOIN SGTPRD.ENGEITEMESTONIVELGE9 FX ON FX.CDREDUZIDO = ITE.CODIGO_REDUZIDO
    WHERE 
      ITE.STATUS_ENGENHARIA = 3
      AND TRIM(FX.CDNIVELGENERICO) = 'R'
      AND ITE.IDPESSOAFJPROPRIETAR = 2
    GROUP BY 
      SUBSTR(ITE.CODIGO, 4, 5),
      TRIM(FX.CDNIVELGENERICO),
      ENG.GRAMATURA,
      CASE WHEN TRIM(FX.CDNIVELGENERICO) = 'R' THEN ENG.LARGURA ELSE ENG.LARGURA * 2 END
  )

-- Os campos ARTIGO e FLUXO vêm de PM; RD só fornece o rendimento da chave já
-- confrontada no JOIN. Projetar RD.ARTIGO/RD.FLUXO novamente gerava nomes
-- duplicados quando a consulta era consumida como uma visão inline.
SELECT
  PM.ARTIGO,
  PM.REDUZIDO,
  PM.DESCRICAO_PRODUTO,
  PM.FLUXO,
  PM.KG_DIA_EFIC100,
  PM.PERCENTUAL,
  PM.KG_DIA_EFIC,
  PM.QT_ORD_ABERTO,
  PM.KG_DIA_EFIC_POR_MQ,
  ROUND(PM.KG_DIA_EFIC / NULLIF(SUM(PM.KG_DIA_EFIC) OVER(), 0), 4) AS PERCENT_KG_DIA_EFIC,
  RD.REND_MTS_KG,
  PM.KG_DIA_EFIC * RD.REND_MTS_KG AS METROS_TOTAIS
FROM
  PROD_MALHARIA PM
  JOIN RENDIMENTO RD ON PM.ARTIGO = RD.ARTIGO AND PM.FLUXO = RD.FLUXO;
