-- =============================================================================
-- OBJETIVO: Monitora - Rama (quanto precisa fazer para fechar o mês)
-- DOMÍNIO: 02_acabamento_preparacao
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Monitora - Rama (quanto precisa fazer para fechar o mês).sql
-- TIPO: Acabamento e Preparação
-- PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
-- TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTONIVELGE9, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.PEDPRODUCAOOB, SGTPRD.PEDPRODUCAO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOCOMERCIAL
-- CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
-- REVISÃO (23/09/2026): Cobertura integral de todas as ramas ativas da fábrica (RM01 e RM02 / grupo RM001 no setor 5), eliminando distorção de mais de 50% na meta do mês e trazendo visão discriminada por máquina e total consolidado via ROLLUP.
-- REVISÃO (24/09/2026): total calculado sobre OBs distintas (UNION ALL no lugar do ROLLUP, que somava duas vezes uma OB pendente nas duas ramas); tempo disponível até o fim do mês (antes excluía o último dia, inflando kg/h e kg/dia em ~1/N).
-- =============================================================================

WITH OBS_RAMA AS (
    -- Pré-filtro cirúrgico das ordens ativas em TODAS as máquinas de Rama da fábrica (RM01 e RM02 / GRUPO RM001)
    -- com fase pendente (STATUS <> 4), eliminando o full table scan histórico de 165k ordens
    SELECT /*+ MATERIALIZE */ DISTINCT OBF.NUMERO_OB
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OBF.NUMERO_MAQUINA
    WHERE (MAQ.GRUPO = 'RM001' OR UPPER(MAQ.NOME_MAQUINA) LIKE '%RAMA%')
      AND MAQ.SETOR = 5
      AND OBF.STATUS <> 4
),
PEDIDO_ENTREGA AS (
    SELECT /*+ MATERIALIZE */
           PPOB.NUMEROOB,
           MIN(CASE WHEN NVL(IPC.EXPEDIREM, 0) = 0 THEN NULL
                    ELSE TO_DATE(TO_CHAR(IPC.EXPEDIREM), 'YYYYMMDD') END) DATA_ENTREGA
      FROM SGTPRD.PEDPRODUCAOOB PPOB
      JOIN OBS_RAMA obr ON obr.NUMERO_OB = PPOB.NUMEROOB
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
      JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = IPG.PEDIDO AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
     GROUP BY PPOB.NUMEROOB
), PROCESSO_ITEM AS (
    SELECT /*+ MATERIALIZE */ CDREDUZIDO, MAX(TRIM(CDNIVELGENERICO)) CDNIVELGENERICO
      FROM SGTPRD.ENGEITEMESTONIVELGE9
     GROUP BY CDREDUZIDO
), OB_BASE AS (
    SELECT /*+ MATERIALIZE */
           O.CDFILIAL FILIAL,
           O.NUMERO_OB,
           O.CODIGO_FLUXO FLUXO,
           PE.DATA_ENTREGA,
           PI.CDNIVELGENERICO,
           NVL(OP.METROS_PROGRAMADOS, 0) METROS_PROG,
           CASE WHEN U.TPUNIDADEMEDIDA = 1 THEN NVL(OP.KILOS_PROGRAMADOS, 0)
                ELSE NVL(OP.METROS_PROGRAMADOS, 0) END QUANT_PROG,
           CASE WHEN U.TPUNIDADEMEDIDA = 1 THEN NVL(OP.KILOS, 0)
                ELSE NVL(OP.METROS, 0) END QUANT_ORIG,
           NVL(PPOB.OBMONTADA, 0) MONTADA
      FROM SGTPRD.OB O
      JOIN OBS_RAMA obr ON obr.NUMERO_OB = O.NUMERO_OB
      JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = O.CODIGO_REDUZIDO
      LEFT JOIN SGTPRD.UNIDADE_MEDIDA U ON U.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
      LEFT JOIN PROCESSO_ITEM PI ON PI.CDREDUZIDO = O.CODIGO_REDUZIDO
      LEFT JOIN SGTPRD.OB_PRODUTO OP ON OP.NUMERO_OB = O.NUMERO_OB
      LEFT JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMEROOB = O.NUMERO_OB AND PPOB.SETOR = 5
      LEFT JOIN PEDIDO_ENTREGA PE ON PE.NUMEROOB = O.NUMERO_OB
), OB_RAMA_PENDENTE AS (
    -- Um par (OB, rama) por OB com fase de rama pendente e entrega no mês.
    -- DISTINCT: duas fases pendentes da mesma OB na mesma rama não somam a OB duas vezes.
    SELECT /*+ MATERIALIZE */ DISTINCT
      OBA.NUMERO_OB,
      LTRIM(OBF.NUMERO_MAQUINA, '0') AS RAMA
    FROM OB_BASE OBA
    INNER JOIN SGTPRD.OB_FASES OBF ON OBA.NUMERO_OB = OBF.NUMERO_OB
    JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OBF.NUMERO_MAQUINA
    WHERE
      OBA.FILIAL = 1
      AND OBA.DATA_ENTREGA >= TRUNC(SYSDATE, 'MM')
      AND OBA.DATA_ENTREGA < ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
      AND OBA.CDNIVELGENERICO = 'R'
      AND (MAQ.GRUPO = 'RM001' OR UPPER(MAQ.NOME_MAQUINA) LIKE '%RAMA%')
      AND MAQ.SETOR = 5
      AND OBF.STATUS <> 4
), QUANTIDADE_RESTANTES AS (
    SELECT
      1 AS ORDEM,
      P.RAMA,
      ROUND(SUM(OBA.METROS_PROG), 3) AS METROS_RESTANTES,
      SUM(DECODE(OBA.MONTADA, 0, OBA.QUANT_PROG, 1, OBA.QUANT_ORIG, 0)) AS QUANTIDADE_QUILOS
    FROM OB_RAMA_PENDENTE P
    JOIN OB_BASE OBA ON OBA.NUMERO_OB = P.NUMERO_OB
    GROUP BY P.RAMA
    UNION ALL
    -- Total sobre OBs distintas (não é a soma das linhas por rama: uma OB com
    -- fase pendente nas duas ramas entraria duas vezes). Substitui o ROLLUP.
    SELECT
      2 AS ORDEM,
      'TOTAL RAMAS' AS RAMA,
      ROUND(SUM(OBA.METROS_PROG), 3) AS METROS_RESTANTES,
      SUM(DECODE(OBA.MONTADA, 0, OBA.QUANT_PROG, 1, OBA.QUANT_ORIG, 0)) AS QUANTIDADE_QUILOS
    FROM OB_BASE OBA
    WHERE OBA.NUMERO_OB IN (SELECT P.NUMERO_OB FROM OB_RAMA_PENDENTE P)
),
TEMPO_DISPONIVEL AS (
    -- Até o fim do mês (00:00 do dia 1 seguinte). A versão anterior usava
    -- TRUNC(LAST_DAY(SYSDATE)), que exclui o último dia inteiro: subestimava o
    -- tempo em 1 dia (inflando kg/h e kg/dia) e ficava negativa no último dia.
    SELECT
      ROUND((ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) - SYSDATE) * 24 * 60, 3) AS MINUTOS_DISPONIVEIS,
      ROUND(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) - SYSDATE, 3) AS DIAS_DISPONIVEIS
    FROM DUAL
)
SELECT
  QR.RAMA,
  QR.METROS_RESTANTES,
  ROUND(QR.QUANTIDADE_QUILOS, 3) AS QUILOS_RESTANTES,
  ROUND(TD.MINUTOS_DISPONIVEIS / 60, 3) AS HORAS_DISPONIVEIS,
  TD.MINUTOS_DISPONIVEIS,
  TD.DIAS_DISPONIVEIS,
  ROUND(QR.QUANTIDADE_QUILOS / NULLIF(TD.MINUTOS_DISPONIVEIS / 60, 0), 3) AS QUILOS_POR_HORA,
  ROUND(QR.QUANTIDADE_QUILOS / NULLIF(TD.MINUTOS_DISPONIVEIS / 60, 0) * 24, 3) AS QUILOS_POR_DIA
FROM QUANTIDADE_RESTANTES QR
CROSS JOIN TEMPO_DISPONIVEL TD
ORDER BY QR.ORDEM, QR.RAMA
