/* =============================================================================
OBJETIVO: Programações em aberto
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Programações em aberto.sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.OB, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAOOB
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
OTIMIZAÇÃO (20/09/2026): Eliminação da view VW_PI_CBPAP01_PROCBENEF e VW_BNF_OBMONTADA,
  substituindo por CTEs nativas de pedidos exclusivos (PEDPRODUCAOOB + PEDIDOCOMERCIAL)
  e cálculo nativo de montagem e peso por OB (OB + OB_PRODUTO + GERAPECAORIGEMOB).
============================================================================= */

WITH PED_EXCLUSIVO AS (
    SELECT /*+ MATERIALIZE */
           PPO.NUMEROOB AS NUMERO_OB,
           COUNT(DISTINCT PCO.PEDIDO) AS NRO_PEDIDOS,
           MIN(PCO.PEDIDO) AS PEDIDO,
           MAX(TRIM(PCO.PEDIDOCLIENTE)) AS PEDIDO_CLIENTE,
           MIN(CASE WHEN NVL(IPC.EXPEDIREM, 0) = 0
                    THEN DATE '1899-12-30'
                    ELSE TO_DATE(TO_CHAR(IPC.EXPEDIREM), 'YYYYMMDD')
               END) AS DATA_ENTREGA
      FROM SGTPRD.PEDPRODUCAOOB    PPO
      JOIN SGTPRD.OFORDENS         OFO ON OFO.NUMEROPEDPRODUCAO  = PPO.NUMERO
      JOIN SGTPRD.OFPEDIDO         OFP ON OFP.NUMEROOF           = OFO.NUMEROOF
      JOIN SGTPRD.ITENSPEDIDOQTDES IPX ON IPX.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPX.IDITEMPEDGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL  PCO ON PCO.PEDIDO             = IPG.PEDIDO
      JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = PCO.PEDIDO AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
     WHERE PPO.SETOR = 5
       AND PCO.TIPOPEDIDO = 2
     GROUP BY PPO.NUMEROOB
),
OB_BASE AS (
    SELECT /*+ MATERIALIZE */
           OBE.NUMERO_OB,
           PED.PEDIDO AS PEDIDO_EXCLUSIVO,
           PED.PEDIDO_CLIENTE AS PEDIDO_CLIENTE_EXCLUSIVO,
           PED.DATA_ENTREGA,
           CASE 
               WHEN EXISTS (
                   SELECT 1 
                     FROM SGTPRD.PEDPRODUCAOOB POB 
                    WHERE POB.NUMEROOB = OBE.NUMERO_OB 
                      AND POB.SETOR = 5 
                      AND POB.OBMONTADA = 1
               ) THEN 1 
               ELSE 0 
           END AS MONTADA,
           NVL(OBP.KILOS_PROGRAMADOS, 0) AS QUANT_PROG,
           NVL((
                 SELECT ROUND(SUM(NVL(GPP.QTLIQUIDA, 0)), 2)
                 FROM SGTPRD.GERAPECAORIGEMOB GPO
                 JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
                WHERE GPO.NUMERO_OB = OBE.NUMERO_OB
           ), 0) AS QUANT_ORIG
      FROM SGTPRD.OB OBE
      JOIN PED_EXCLUSIVO PED ON PED.NUMERO_OB = OBE.NUMERO_OB
      LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBE.NUMERO_OB
     WHERE OBE.STATUS <> 0
       AND OBE.TIPO_ORDEM IN (0, 6)
       AND PED.NRO_PEDIDOS <> 0
)
SELECT
    V.PEDIDO_EXCLUSIVO                AS PEDIDO,
    V.PEDIDO_CLIENTE_EXCLUSIVO        AS PROG,
    MAX(V.DATA_ENTREGA)               AS ENTREGA,
    COUNT(V.NUMERO_OB)                AS OBS,
    SUM(CASE WHEN V.MONTADA = 0 THEN V.QUANT_PROG ELSE V.QUANT_ORIG END) AS QT_KG,
    TO_CHAR(
            (SUM(CASE WHEN V.MONTADA = 0 THEN V.QUANT_PROG ELSE V.QUANT_ORIG END) /
            (SELECT SUM(ITP.QUANTIDADE) - SUM(ITP.QTDECANCELADAITEMPED)
               FROM SGTPRD.ITENSPEDIDOCOMERCIAL ITP
              WHERE ITP.PEDIDO = V.PEDIDO_EXCLUSIVO)) * 100, '999G999G990D00'
            ) || '%' AS FALTA
FROM OB_BASE V
GROUP BY V.PEDIDO_EXCLUSIVO, V.PEDIDO_CLIENTE_EXCLUSIVO
ORDER BY V.PEDIDO_CLIENTE_EXCLUSIVO, MAX(V.DATA_ENTREGA);
