/* =============================================================================
OBJETIVO: Ordens de Manutenção - Programadas e Planejadas
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Ordens de Manutenção - Programadas e Planejadas.sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.MANUTENCAO, SGTPRD.MANUTENCAO_MAQUINA, SGTPRD.MAN_CALENDARIO, SGTPRD.MAQUINA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT MANUTENCAO_MAQUINA.NUMERO_MAQUINA, 
       MAQUINA.NOME_MAQUINA, 
       MANUTENCAO_MAQUINA.COMPONENTE, 
       MANUTENCAO_MAQUINA.CODIGOMANUTENCAO, 
       MANUTENCAO.DESCRICAOMANUTENCAO, 
       MANUTENCAO_MAQUINA.INTERVALO_ENTRE_MANU, 
       MANUTENCAO_MAQUINA.TEMPO_MANUTENCAO, 
       MANUTENCAO_MAQUINA.TEMPO_PREVISAO_PARAD, 
       MANUTENCAO_MAQUINA.DATAULTIMAMANUTENCAO AS DATA_ULTIMA_MANUTENCAO, 
       MANUTENCAO_MAQUINA.DATA_PROXIMA_MANUTEN AS DATA_PROXIMA_MANUTENCAO, 
       MANUTENCAO_MAQUINA.HOMENS_ALOCADOS, 
       MAN_CALENDARIO.DATA_PROGRAMADA, 
       MAN_CALENDARIO.DATA_PLANEJADA,
       MAN_CALENDARIO.IDPLANO,
       MANUTENCAO_MAQUINA.REMANEJAR_DATA,
       MANUTENCAO_MAQUINA.PLANO_ATIVO
FROM SGTPRD.MANUTENCAO_MAQUINA MANUTENCAO_MAQUINA
      LEFT OUTER JOIN SGTPRD.MAQUINA MAQUINA ON 
     (MAQUINA.NUMERO_MAQUINA = SGTPRD.MANUTENCAO_MAQUINA.NUMERO_MAQUINA)
      LEFT OUTER JOIN SGTPRD.MANUTENCAO MANUTENCAO ON 
     (MANUTENCAO.CODIGOMANUTENCAO = MANUTENCAO_MAQUINA.CODIGOMANUTENCAO)
      LEFT OUTER JOIN SGTPRD.MAN_CALENDARIO MAN_CALENDARIO ON 
     (MAN_CALENDARIO.NUMERO_MAQUINA = MANUTENCAO_MAQUINA.NUMERO_MAQUINA)
      AND (MAN_CALENDARIO.COMPONENTE = MANUTENCAO_MAQUINA.COMPONENTE)
      AND (MAN_CALENDARIO.CODIGO_MANUTENCAO = MANUTENCAO_MAQUINA.CODIGOMANUTENCAO)
WHERE 
      ( MANUTENCAO_MAQUINA.CODIGOMANUTENCAO LIKE '1TMC%' )
       AND ( MAN_CALENDARIO.DATA_PROGRAMADA >= TRUNC(SYSDATE) )
       AND ( MAN_CALENDARIO.DATA_PROGRAMADA <= TRUNC(SYSDATE+30) )
       AND ( MANUTENCAO_MAQUINA.NUMERO_MAQUINA LIKE '000000MQ%' )
ORDER BY MAN_CALENDARIO.DATA_PROGRAMADA, 
         MANUTENCAO_MAQUINA.NUMERO_MAQUINA, 
         MANUTENCAO_MAQUINA.COMPONENTE, 
         MANUTENCAO_MAQUINA.CODIGOMANUTENCAO;
