/* =============================================================================
OBJETIVO: Risco de Atraso de Pedidos e Clientes por OB Pendente nas Ramas
DOMÍNIO: 02_acabamento_preparacao
TIPO: Monitoramento operacional
GRÃO: NUMERO_OB (uma linha por OB com fase pendente em rama; hoje cada OB tem uma única fase de rama pendente)
PARÂMETROS / BINDS: Nenhum (avalia todas as ordens pendentes nas ramas)
TABELAS PRINCIPAIS: SGTPRD.OB_FASES, SGTPRD.MAQUINA, SGTPRD.OB_PRODUTO, SGTPRD.PEDPRODUCAOOB, SGTPRD.PEDPRODUCAO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PESSOASFJ
CUIDADOS OPERACIONAIS: Somente leitura. Rastreamento estrito via cadeia física de pedidos comerciais com filtro PPOB.SETOR = 5.
  Sem teto de linhas: a fila tem poucas centenas de OBs e o teto anterior (100) cortava OBs de alto risco e
  todas as de atenção e regulares, porque o resultado é ordenado por urgência. Cliente = IDFILIALRESPONSAVEL
  (cliente comprador, conforme o dicionário); quando a OB atende mais de um cliente, aparece VÁRIOS CLIENTES
  em vez de um nome arbitrário, e QTD_CLIENTES/QTD_PEDIDOS mostram o tamanho do vínculo. A data prometida é a
  mais próxima entre os itens de pedido da OB (visão conservadora). SEM PEDIDO VINCULADO = a cadeia de
  pedidos não devolveu nenhum item para a OB (programação interna ou vínculo ausente).
  Classes de risco: medem a distância até a DATA DE EXPEDIÇÃO do item (ITENSPEDIDOCOMERCIAL.EXPEDIREM),
  não a data de entrega ao cliente (SOLICITADOPARA). A numeração segue a ordem das linhas: as datas mais
  urgentes primeiro e, por último, a OB sem data. A classe olha só o calendário: não considera em que
  fase a OB está, então uma OB longe da rama e uma pronta para ela pesam igual com a mesma data.
============================================================================= */

WITH FILA_RAMA AS (
    SELECT /*+ MATERIALIZE */ DISTINCT
        OBF.NUMERO_OB,
        LTRIM(OBF.NUMERO_MAQUINA, '0') AS RAMA,
        OBF.CODIGO_FASE,
        NVL(OP.KILOS_PROGRAMADOS, 0) AS KG_OB,
        NVL(OP.METROS_PROGRAMADOS, 0) AS METROS_OB
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OBF.NUMERO_MAQUINA
    LEFT JOIN SGTPRD.OB_PRODUTO OP ON OP.NUMERO_OB = OBF.NUMERO_OB
    WHERE OBF.STATUS <> 4
      AND MAQ.GRUPO = 'RM001'
      AND MAQ.SETOR = 5
),
PEDIDOS_VINCULADOS AS (
    SELECT /*+ MATERIALIZE LEADING(FR PPOB) USE_NL(PPOB) */
        PPOB.NUMEROOB,
        MIN(CASE
                WHEN NVL(IPC.EXPEDIREM, 0) > 0 THEN TO_DATE(TO_CHAR(IPC.EXPEDIREM), 'YYYYMMDD')
                ELSE NULL
            END) AS DATA_EXPEDICAO_PROMETIDA,
        CASE
            WHEN COUNT(DISTINCT PED.IDFILIALRESPONSAVEL) > 1 THEN 'VÁRIOS CLIENTES'
            ELSE SUBSTR(TRIM(MAX(PFJ.NOMEFANTASIA)), 1, 35)
        END AS NOME_CLIENTE,
        COUNT(DISTINCT PED.IDFILIALRESPONSAVEL) AS QTD_CLIENTES,
        COUNT(DISTINCT PED.PEDIDO) AS QTD_PEDIDOS
    FROM FILA_RAMA FR
    JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMEROOB = FR.NUMERO_OB AND PPOB.SETOR = 5
    JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
    JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = IPG.PEDIDO AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
    LEFT JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
    GROUP BY PPOB.NUMEROOB
)
SELECT
    FR.RAMA,
    FR.CODIGO_FASE,
    FR.NUMERO_OB,
    NVL(PV.NOME_CLIENTE, 'SEM PEDIDO VINCULADO') AS CLIENTE,
    PV.QTD_CLIENTES,
    PV.QTD_PEDIDOS,
    FR.KG_OB,
    FR.METROS_OB,
    PV.DATA_EXPEDICAO_PROMETIDA,
    ROUND(PV.DATA_EXPEDICAO_PROMETIDA - TRUNC(SYSDATE), 0) AS DIAS_ATE_EXPEDICAO,
    CASE
        WHEN PV.DATA_EXPEDICAO_PROMETIDA IS NULL THEN '5. SEM DATA DE EXPEDIÇÃO'
        WHEN PV.DATA_EXPEDICAO_PROMETIDA < TRUNC(SYSDATE) THEN '1. CRÍTICO: DATA DE EXPEDIÇÃO JÁ VENCIDA'
        WHEN PV.DATA_EXPEDICAO_PROMETIDA <= TRUNC(SYSDATE) + 5 THEN '2. ALTO RISCO: EXPEDIÇÃO EM ATÉ 5 DIAS'
        WHEN PV.DATA_EXPEDICAO_PROMETIDA <= TRUNC(SYSDATE) + 12 THEN '3. ATENÇÃO: EXPEDIÇÃO EM 6 A 12 DIAS'
        ELSE '4. REGULAR: EXPEDIÇÃO EM MAIS DE 12 DIAS'
    END AS CLASSIFICACAO_RISCO
FROM FILA_RAMA FR
LEFT JOIN PEDIDOS_VINCULADOS PV ON PV.NUMEROOB = FR.NUMERO_OB
ORDER BY
    CASE WHEN PV.DATA_EXPEDICAO_PROMETIDA IS NULL THEN 999 ELSE PV.DATA_EXPEDICAO_PROMETIDA - TRUNC(SYSDATE) END ASC,
    FR.NUMERO_OB;
