/* =============================================================================
OBJETIVO: Alterar grupo de programação (engenharia)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Alterar grupo de programação (engenharia).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOCOR, SGTPRD.ENGEITEMESTODESENHO, SGTPRD.ENGEITEMESTONIVELGE9, SGTPRD.ENG_AGRUPAITENSESTOQ, SGTPRD.GRUPO_PRODUTO, SGTPRD.ITENS_ESTOQUE
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

--16
SELECT AGP.REDUZIDO_AGRUPADOR,
       TMA.CDNIVELGENERICO FLUXO,
       DES.CDDESENHO,
       COR.CDCOR,
       ITE.CODIGO,
       ITE.CODIGO_ALTERNATIVO,
       ITE.NUMERO_GRUPO_PROGRAM,
       GP.DESCRICAO
  FROM SGTPRD.ENGEITEMESTOCOR      COR,
       SGTPRD.ITENS_ESTOQUE        ITE,
       SGTPRD.ENGEITEMESTODESENHO  DES,
       SGTPRD.ENGEITEMESTONIVELGE9 TMA,
       SGTPRD.ENG_AGRUPAITENSESTOQ AGP,
       SGTPRD.GRUPO_PRODUTO        GP
 WHERE ITE.CODIGO_REDUZIDO = COR.CDREDUZIDO
   AND DES.CDREDUZIDO = ITE.CODIGO_REDUZIDO
   AND TMA.CDREDUZIDO = ITE.CODIGO_REDUZIDO
   AND AGP.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   AND GP.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
   AND TRIM(COR.CDCOR) BETWEEN '00052' AND '00084'
   AND TRIM(COR.CDCOR) <> '00051'
   AND SUBSTR(ITE.CODIGO, 6, 3) = '046'
   --AND SUBSTR(ITE.CODIGO, 26, 2) = 'MN'
   --AND TRIM(DES.CDDESENHO) = '000000'
   --AND TRIM(TMA.CDNIVELGENERICO) = 'R'
   
 ORDER BY 5
