/* =============================================================================
OBJETIVO: Acumulado (RAMA)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Acumulado (RAMA).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_BNF_PRODUCAO_FASE, SGTPRD.BD_PRD_MOVPROD, SGTPRD.ENGEITEMESTONIVELGE, SGTPRD.GERAPECASPRODUTO, SGTPRD.TABELA_DATAS
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH PERIODO AS (
    SELECT MIN(DAT.DATA) AS DATA_INICIO,
           MAX(DAT.DATA) + 1 AS DATA_FIM
      FROM SGTPRD.TABELA_DATAS DAT
     WHERE DAT.ANO_MES = 202203
),
MAL_SUBQUERY AS (
    SELECT 
        PRD.PRODUCAO_DATA AS DATA_ENTRADA,
        SUM(PRD.QUANTIDADE_REAL) AS QUANTIDADE_KG
    FROM 
        SGTPRD.BD_PRD_MOVPROD PRD
    INNER JOIN 
        SGTPRD.ENGEITEMESTONIVELGE MAS ON MAS.CDREDUZIDO = PRD.REDUZIDO_ITEM
    CROSS JOIN PERIODO P
    WHERE 
        PRD.NUM_TIPO_MOVIMENTO = 37
        AND PRD.TIPO_ITEM = 9
        AND TRIM(MAS.CDNIVELGENERICO) = 'R'
        AND PRD.QUALIDADE = 1
        AND PRD.PRODUCAO_DATA >= P.DATA_INICIO
        AND PRD.PRODUCAO_DATA < P.DATA_FIM
    GROUP BY 
        PRD.PRODUCAO_DATA 
), 
TERC_SUBQUERY AS (
    SELECT 
        TO_DATE(E.DATA_DA_ENTRADA_PECA, 'YYYY/MM/DD') AS DATA_ENTRADA,
        SUM(E.QTLIQUIDA) AS QUANTIDADE_KG
    FROM 
        SGTPRD.GERAPECASPRODUTO E
    INNER JOIN 
        SGTPRD.ENGEITEMESTONIVELGE MAS ON E.CODIGO_REDUZIDO_PROD = MAS.CDREDUZIDO
    CROSS JOIN PERIODO P
    WHERE 
        E.PADRAO_QUALIDADE_SIN = 1
        AND E.TIDOCUMENTOENTRADA IN (8)
        AND TRIM(MAS.IDMASCARATIPOINSUMO) IN ('MCP', 'MCR', 'MCT')
        AND TRIM(MAS.CDNIVELGENERICO) = 'R'
        AND E.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(P.DATA_INICIO, 'YYYYMMDD'))
        AND E.DATA_DA_ENTRADA_PECA < TO_NUMBER(TO_CHAR(P.DATA_FIM, 'YYYYMMDD'))
    GROUP BY 
        E.DATA_DA_ENTRADA_PECA
),
TIN_OB_ALVO AS (
    SELECT DISTINCT PR.NUMERO_OB
      FROM SGTPRD.BD_BNF_PRODUCAO_FASE PR
      CROSS JOIN PERIODO P
     WHERE PR.NUMERO_MAQUINA = '000000RM01'
       AND PR.TIPO_DESTINO = 0
       AND PR.DATA_FIM >= P.DATA_INICIO
       AND PR.DATA_FIM < P.DATA_FIM
),
TIN_CANDIDATOS AS (
    SELECT /*+ MATERIALIZE */
           PR.DATA_FIM,
           PR.KILOS,
           PR.NUMERO_OB,
           PR.SEQUENCIA,
           MIN(PR.SEQUENCIA) OVER (
               PARTITION BY PR.NUMERO_MAQUINA,
                            PR.TIPO_DESTINO,
                            PR.NUMERO_OB
           ) AS SEQUENCIA_MIN
      FROM SGTPRD.BD_BNF_PRODUCAO_FASE PR
      JOIN TIN_OB_ALVO A ON A.NUMERO_OB = PR.NUMERO_OB
     WHERE PR.NUMERO_MAQUINA = '000000RM01'
       AND PR.TIPO_DESTINO = 0
),
TIN_SUBQUERY AS (
    SELECT T.DATA_FIM,
           SUM(T.KILOS) AS QUANTIDADE_KG
      FROM TIN_CANDIDATOS T
      CROSS JOIN PERIODO P
     WHERE T.SEQUENCIA = T.SEQUENCIA_MIN
       AND T.DATA_FIM >= P.DATA_INICIO
       AND T.DATA_FIM < P.DATA_FIM
     GROUP BY T.DATA_FIM
)
SELECT 
    DAT.DATA AS DT_PROD,
    DAT.DIA_SEM AS DIA_SEM,
    NVL(MAL.QUANTIDADE_KG, 0) AS QT_MAL,
    NVL(TERC.QUANTIDADE_KG, 0) AS QT_TERC,
    NVL(TIN.QUANTIDADE_KG, 0) AS QT_TIN,
    NVL(NVL(MAL.QUANTIDADE_KG, 0) + NVL(TERC.QUANTIDADE_KG, 0), 0) - ROUND(NVL(TIN.QUANTIDADE_KG, 0), 2) AS DIFERENCA,
    ROUND(SUM(NVL(NVL(MAL.QUANTIDADE_KG, 0) + NVL(TERC.QUANTIDADE_KG, 0), 0) - NVL(TIN.QUANTIDADE_KG, 0)) 
        OVER(ORDER BY DAT.DATA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS ACUMULADO
FROM 
    SGTPRD.TABELA_DATAS DAT
LEFT JOIN MAL_SUBQUERY MAL ON MAL.DATA_ENTRADA = DAT.DATA
LEFT JOIN TERC_SUBQUERY TERC ON TERC.DATA_ENTRADA = DAT.DATA
LEFT JOIN TIN_SUBQUERY TIN ON TIN.DATA_FIM = DAT.DATA
WHERE 
    DAT.DATA >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH') -- Primeiro dia do ms anterior
    AND DAT.DATA < TRUNC(SYSDATE, 'MONTH')              -- ltimo dia do ms anterior
ORDER BY 
    DAT.DATA;
