/* =============================================================================
OBJETIVO: Monitora - Felpadeira (quanto precisa fazer para fechar o mês)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Monitora - Felpadeira (quanto precisa fazer para fechar o mês).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.PEDPRODUCAOOB, SGTPRD.PEDPRODUCAO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOCOMERCIAL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH PEDIDO_ENTREGA AS (
       SELECT PPOB.NUMEROOB,
              MIN(CASE WHEN NVL(IPC.EXPEDIREM, 0) = 0 THEN NULL
                       ELSE TO_DATE(TO_CHAR(IPC.EXPEDIREM), 'YYYYMMDD') END) DATA_ENTREGA
         FROM SGTPRD.PEDPRODUCAOOB PPOB
         JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
         JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
         JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
         JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
         JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
         JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = IPG.PEDIDO AND IPC.ITEMPEDIDO = IPG.ITEMPEDIDO
        GROUP BY PPOB.NUMEROOB
), PROCESSO_ITEM AS (
       SELECT CDREDUZIDO, MAX(TRIM(CDNIVELGENERICO)) CDNIVELGENERICO
         FROM SGTPRD.ENGEITEMESTONIVELGE9
        GROUP BY CDREDUZIDO
), OB_BASE AS (
       SELECT O.CDFILIAL FILIAL,
              O.NUMERO_OB,
              O.CODIGO_FLUXO FLUXO,
              PE.DATA_ENTREGA,
              NVL(OP.METROS_PROGRAMADOS, 0) METROS_PROG,
              CASE WHEN U.TPUNIDADEMEDIDA = 1 THEN NVL(OP.KILOS_PROGRAMADOS, 0)
                   ELSE NVL(OP.METROS_PROGRAMADOS, 0) END QUANT_PROG,
              CASE WHEN U.TPUNIDADEMEDIDA = 1 THEN NVL(OP.KILOS, 0)
                   ELSE NVL(OP.METROS, 0) END QUANT_ORIG,
              NVL(PPOB.OBMONTADA, 0) MONTADA
         FROM SGTPRD.OB O
         JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = O.CODIGO_REDUZIDO
         LEFT JOIN SGTPRD.UNIDADE_MEDIDA U ON U.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
         LEFT JOIN SGTPRD.OB_PRODUTO OP ON OP.NUMERO_OB = O.NUMERO_OB
         LEFT JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMEROOB = O.NUMERO_OB AND PPOB.SETOR = 5
         LEFT JOIN PEDIDO_ENTREGA PE ON PE.NUMEROOB = O.NUMERO_OB
), QUANTIDADE_RESTANTES AS (
                              SELECT
                                ROUND(SUM(OBA.METROS_PROG), 3) AS METROS_RESTANTES,
                                SUM(OBA.QUANT_PROG) AS QUANTIDADE_PROG,
                                SUM(OBA.QUANT_ORIG) AS QUANTIDADE_ORIG,
                                SUM(DECODE(OBA.MONTADA, 0, OBA.QUANT_PROG, 1, OBA.QUANT_ORIG, '')) QUANTIDADE_QUILOS
                              FROM OB_BASE OBA
                              INNER JOIN SGTPRD.OB_FASES OBF ON OBA.NUMERO_OB = OBF.NUMERO_OB
                              WHERE
                                OBA.FILIAL = 1
                                AND OBA.FLUXO IN (103, 203)
                                --AND EXTRACT(MONTH FROM OBA.DATA_ENTREGA) = EXTRACT(MONTH FROM SYSDATE)
                                AND OBA.DATA_ENTREGA >= TRUNC(SYSDATE, 'MM')
                                AND OBA.DATA_ENTREGA < ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
                                AND OBF.CODIGO_FASE = 65
                                AND OBF.STATUS <> 4
                              ),
      TEMPO_DISPONIVEL AS (
                            SELECT
                              ROUND((ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) - SYSDATE) * 24 * 60, 3) AS MINUTOS_DISPONIVEIS,
                              ROUND(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) - SYSDATE, 3) AS DIAS_DISPONIVEIS
                            FROM
                              DUAL
                           )
SELECT
  QR.METROS_RESTANTES,
  ROUND(QR.QUANTIDADE_QUILOS, 3)                                      AS QUILOS_RESTANTES,
  ROUND(TD.MINUTOS_DISPONIVEIS / 60, 3)                               AS HORAS_DISPONIVEIS,
  TD.MINUTOS_DISPONIVEIS                                              AS MINUTOS_DISPONIVEIS,
  TD.DIAS_DISPONIVEIS                                                 AS DIAS_DISPONIVEIS,
  ROUND(QR.QUANTIDADE_QUILOS / NULLIF(TD.MINUTOS_DISPONIVEIS / 60, 0), 3)      AS QUILOS_POR_HORA,
  ROUND(QR.QUANTIDADE_QUILOS / NULLIF(TD.MINUTOS_DISPONIVEIS / 60, 0) * 24, 3) AS QUILOS_POR_DIA
FROM QUANTIDADE_RESTANTES QR
CROSS JOIN TEMPO_DISPONIVEL TD;
