/* =============================================================================
OBJETIVO: Acumulado (TUBULAR)
DOMÍNIO: 02_acabamento_preparacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Acumulado (TUBULAR).sql
TIPO: Acabamento e Preparação
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_BNF_PRODUCAO_FASE, SGTPRD.BD_PRD_MOVPROD, SGTPRD.ENGEITEMESTONIVELGE, SGTPRD.ENGEITEMESTONIVELGE9, SGTPRD.GERAPECASPRODUTO, SGTPRD.TABELA_DATAS
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

-- Desempenho: as janelas de data entram em cada CTE (antes cada uma agregava o
-- histórico inteiro, ~56 mi linhas só em BD_PRD_MOVPROD, e o mês só era cortado
-- no calendário). Equivalente: cada CTE liga ao calendário por igualdade de data
-- e o acumulado é calculado só sobre as datas do mês.
WITH MAL_SUBQUERY AS (
    SELECT /*+ MATERIALIZE */ 
        PRD.PRODUCAO_DATA AS DATA_ENTRADA,
        SUM(PRD.QUANTIDADE_REAL) AS QUANTIDADE_KG
    FROM 
        SGTPRD.BD_PRD_MOVPROD PRD
    INNER JOIN 
        SGTPRD.ENGEITEMESTONIVELGE MAS ON MAS.CDREDUZIDO = PRD.REDUZIDO_ITEM
    WHERE 
        PRD.PRODUCAO_DATA >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH')
        AND PRD.PRODUCAO_DATA < TRUNC(SYSDATE, 'MONTH')
        AND PRD.NUM_TIPO_MOVIMENTO = 37
        AND PRD.TIPO_ITEM = 9
        AND TRIM(MAS.CDNIVELGENERICO) = 'T'
        AND PRD.QUALIDADE = 1
    GROUP BY 
        PRD.PRODUCAO_DATA 
), 
TERC_SUBQUERY AS (
    SELECT /*+ MATERIALIZE */ 
        TO_DATE(E.DATA_DA_ENTRADA_PECA, 'YYYY/MM/DD') AS DATA_ENTRADA,
        SUM(E.QTLIQUIDA) AS QUANTIDADE_KG
    FROM 
        SGTPRD.GERAPECASPRODUTO E
    INNER JOIN 
        SGTPRD.ENGEITEMESTONIVELGE MAS ON E.CODIGO_REDUZIDO_PROD = MAS.CDREDUZIDO
    WHERE 
        -- DATA_DA_ENTRADA_PECA é NUMBER YYYYMMDD (índice GRPCPROD_INDIDATAENTRPECA).
        E.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), 'YYYYMMDD'))
        AND E.DATA_DA_ENTRADA_PECA < TO_NUMBER(TO_CHAR(TRUNC(SYSDATE, 'MONTH'), 'YYYYMMDD'))
        AND E.PADRAO_QUALIDADE_SIN = 1
        AND E.TIDOCUMENTOENTRADA IN (8)
        AND TRIM(MAS.IDMASCARATIPOINSUMO) IN ('MCP', 'MCR', 'MCT')
        AND TRIM(MAS.CDNIVELGENERICO) = 'T'
    GROUP BY 
        E.DATA_DA_ENTRADA_PECA
),
TIN_SUBQUERY AS (
    SELECT /*+ MATERIALIZE */ 
        PR.DATA_FIM, 
        SUM(PR.KILOS) AS QUANTIDADE_KG
    FROM 
        SGTPRD.BD_BNF_PRODUCAO_FASE PR
    INNER JOIN 
        SGTPRD.ENGEITEMESTONIVELGE9 MAC ON PR.CODPRO_REDUZIDO = MAC.CDREDUZIDO
    WHERE 
        PR.DATA_FIM >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH')
        AND PR.DATA_FIM < TRUNC(SYSDATE, 'MONTH')
        AND PR.PI_REC IN (701, 801)
        AND PR.TIPO_DESTINO = 0
        AND PR.SEQUENCIA = (
            SELECT 
                MIN(PR2.SEQUENCIA)
            FROM 
                SGTPRD.BD_BNF_PRODUCAO_FASE PR2
            WHERE 
                PR2.NUMERO_MAQUINA = PR.NUMERO_MAQUINA
                AND PR2.TIPO_DESTINO = PR.TIPO_DESTINO
                AND PR2.NUMERO_OB = PR.NUMERO_OB
        )
    GROUP BY 
        PR.DATA_FIM
)
SELECT 
    DAT.DATA AS DT_PROD,
    DAT.DIA_SEM AS DIA_SEM,
    NVL(MAL.QUANTIDADE_KG, 0) AS QT_MAL,
    NVL(TERC.QUANTIDADE_KG, 0) AS QT_TERC,
    NVL(TIN.QUANTIDADE_KG, 0) AS QT_TIN,
    NVL(NVL(MAL.QUANTIDADE_KG, 0) + NVL(TERC.QUANTIDADE_KG, 0), 0) - ROUND(NVL(TIN.QUANTIDADE_KG, 0), 2) AS DIFERENCA,
    ROUND(SUM(NVL(NVL(MAL.QUANTIDADE_KG, 0) + NVL(TERC.QUANTIDADE_KG, 0), 0) - NVL(TIN.QUANTIDADE_KG, 0)) 
        OVER(ORDER BY DAT.DATA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS ACUMULADO
FROM 
    SGTPRD.TABELA_DATAS DAT
LEFT JOIN MAL_SUBQUERY MAL ON MAL.DATA_ENTRADA = DAT.DATA
LEFT JOIN TERC_SUBQUERY TERC ON TERC.DATA_ENTRADA = DAT.DATA
LEFT JOIN TIN_SUBQUERY TIN ON TIN.DATA_FIM = DAT.DATA
WHERE 
    DAT.DATA >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH') -- Primeiro dia do ms anterior
    AND DAT.DATA < TRUNC(SYSDATE, 'MONTH') -- ltimo dia do ms anterior
ORDER BY 
    DAT.DATA;
