WITH
    TINGIMENTO_TEMPOS AS (
        SELECT
            UPO.NUMEROORDEMREAL AS NUMERO_OB,
            MAX(UNP.DTTEMPOINICIAL) AS INICIO_TING,
            MAX(UNP.DTTEMPOFINAL) AS FINAL_TING
        FROM SGTPRD.UP_ORDEM_MVTO UPO
        JOIN SGTPRD.UNIDADE_PROGRAMACAO UNP ON UPO.NUMEROUP = UNP.NUMEROUP
        WHERE UNP.TIPO_MAQUINA = 19 
        AND UNP.EXCLUIDA = 0 
        GROUP BY UPO.NUMEROORDEMREAL
    ),
    MAQUINAS_TINGIMENTO AS (
        SELECT 
            NUMERO_OB,
            MAX(LTRIM(NUMERO_MAQUINA, '0')) AS MQ_TING
        FROM SGTPRD.OB_FASES 
        WHERE CODIGO_FASE = 40
        GROUP BY NUMERO_OB
    ),
    DADOS_AGREGADOS AS (
        SELECT
            OBF.NUMERO_OB, M.NUMEROORDEM, OBF.CODIGO_GRUPO, OBP.CODPRO_REDUZIDO,
            MAX(TRIM(OPE.NOME)) AS USUARIO,
            MAX(M.DT_PESAGEM) AS HORARIO_PESADO,
            SUM(M.QUANTIDADEPESADA) AS QUANT_PESADA
        FROM SGTPRD.OB_FASES OBF
        JOIN SGTPRD.VW_BNF_FASEATUALOB OB ON OB.NUMERO_OB = OBF.NUMERO_OB       
        JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBF.NUMERO_OB
        JOIN SGTPRD.MOVTO_RECEITA M ON M.NUMEROORDEM = OBF.NUMEROORDEMMOVIMENTO 
            AND M.SEQUENCIAFASEOB = OBF.SEQUENCIAORDEMMOVIME
        LEFT JOIN SGTPRD.OPERADOR OPE ON OPE.IDOPERADOR = M.IDOPE_PESAGEM
        WHERE OBF.CODIGO_FASE = 40 AND OBF.STATUS IN (1, 2, 3)
        GROUP BY OBF.NUMERO_OB, M.NUMEROORDEM, OBF.CODIGO_GRUPO, OBP.CODPRO_REDUZIDO
    )

SELECT /*+ FIRST_ROWS(1000) */
    GRUPO,
    NUMERO_OB,
    PESADA,
    MQ_TING,
    INICIO_TING,
    FINAL_TING,
    ARTIGO,
    REDUZIDO,
    DESCRICAO,
    FASE_ATUAL,
    STATUS_FASE,
    USUARIO,
    HORARIO_PESADO,
    QUANT_PESADA
FROM (
    SELECT
        BASE.CODIGO_GRUPO AS GRUPO, BASE.NUMERO_OB,
        CASE WHEN SGTPRD.FNC_ESP_REC_PES(BASE.NUMERO_OB) = 0 THEN 'NAO' ELSE 'SIM' END AS PESADA,
        MT.MQ_TING, TT.INICIO_TING, TT.FINAL_TING,
        ART.CDARTIGOCRU AS ARTIGO, BASE.CODPRO_REDUZIDO AS REDUZIDO,
        TRIM(ITE.DESCRICAO) AS DESCRICAO, FAS.DESCR_FASE AS FASE_ATUAL,
        CASE FAS.STATUS
            WHEN 0 THEN 'PROGRAMADA' WHEN 1 THEN 'EMITIDA'
            WHEN 2 THEN 'PESADA' WHEN 3 THEN 'EM EXECUCAO'
        END AS STATUS_FASE,
        BASE.USUARIO, BASE.HORARIO_PESADO,
        BASE.QUANT_PESADA
    FROM DADOS_AGREGADOS BASE
    LEFT JOIN TINGIMENTO_TEMPOS TT ON TT.NUMERO_OB = BASE.NUMERO_OB
    LEFT JOIN MAQUINAS_TINGIMENTO MT ON MT.NUMERO_OB = BASE.NUMERO_OB
    LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = BASE.CODPRO_REDUZIDO
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = BASE.CODPRO_REDUZIDO
    LEFT JOIN SGTPRD.VW_BNF_FASEATUALOB FAS ON FAS.NUMERO_OB = BASE.NUMERO_OB
)
WHERE PESADA = 'NAO'
ORDER BY INICIO_TING NULLS LAST, NUMERO_OB ASC
