/* =============================================================================
OBJETIVO: vw_pi_cenga03_prodaca
DOMÍNIO: 11_views_referencia_sgt
ARQUIVO ORIGINAL: Comandos SQL - CR\vw_pi_cenga03_prodaca.sql
TIPO: DDL / Definição de View
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: Não identificadas explicitamente
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

--CREATE OR REPLACE VIEW VW_PI_CENGA03_PRODACA AS
SELECT ITE.CODIGO_REDUZIDO REDUZ,
       TRIM(ITE.DESCRICAO) DESCR_ITEM,
       TRIM(ITE.NOME_DETALHADO1) DESCR_ITEM1,
       TRIM(ITE.NOME_DETALHADO2) DESCR_ITEM2,
       VMA.TIPO,
       TRIM(VMA.ARTIGO) ARTIGO,
       VMA.DESCR_ARTIGO,
       VMA.COR,
       VMA.DESCR_COR,
       (SELECT MAX(C.CODIGO_RGB)
          FROM COR C
         WHERE TRIM(C.CODIGO_COR) = TRIM(VMA.COR)) RGB_COR,
       TRIM(VMA.DESCR_CLASSIF_COR) DESCR_CLASSIFICACAO_COR,
       VMA.DESENHO,
       VMA.ACABAMENTO,
       VMA.PROCESSO,
       VMA.VARIANTE,
       VMA.CODIND,
       VMA.CODCOM,
       EPA.GRAMATURA,
       DECODE(EPA.TIPO_DA_GRAMATURA, 1, 'g/m2', 'g/m L') DESCR_TIPO_GRAMATURA,
       EPA.VARIACAOGRAMATURAMIN || '%' VAR_MIN_GRAM,
       EPA.VARIACAOGRAMATURAMAX || '%' VAR_MAX_GRAM,
       EPA.GRAMATURA * (1 - EPA.VARIACAOGRAMATURAMIN / 100) GRAMATURA_MIN,
       EPA.GRAMATURA * (1 + EPA.VARIACAOGRAMATURAMAX / 100) GRAMATURA_MAX,
       CASE
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / EPA.GRAMATURA
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA * 2)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / (EPA.GRAMATURA * 2)
         ELSE
          0
       END RENDIMENTO,
       CASE
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA) *
          (1 - EPA.VARIACAOGRAMATURAMAX / 100)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / EPA.GRAMATURA * (1 - EPA.VARIACAOGRAMATURAMAX / 100)
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA * 2) *
          (1 - EPA.VARIACAOGRAMATURAMAX / 100)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / (EPA.GRAMATURA * 2) * (1 - EPA.VARIACAOGRAMATURAMAX / 100)
         ELSE
          0
       END RENDIMENTO_MIN,
       CASE
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA) *
          (1 + EPA.VARIACAOGRAMATURAMIN / 100)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO NOT IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / EPA.GRAMATURA * (1 + EPA.VARIACAOGRAMATURAMIN / 100)
         WHEN EPA.TIPO_DA_GRAMATURA = 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              (EPA.GRAMATURA * EPA.LARGURA) <> 0 THEN
          1000 / (EPA.GRAMATURA * EPA.LARGURA * 2) *
          (1 + EPA.VARIACAOGRAMATURAMIN / 100)
         WHEN EPA.TIPO_DA_GRAMATURA <> 1 AND ICO.TIPOPRODUTO IN (4,9) AND
              EPA.GRAMATURA <> 0 THEN
          1000 / (EPA.GRAMATURA * 2) * (1 + EPA.VARIACAOGRAMATURAMIN / 100)
         ELSE
          0
       END RENDIMENTO_MAX,
       EPA.LARGURATOTAL LARG_UTIL,
       EPA.LARGURA LARG,
       EPA.LARGURA - ICO.VARIACAO_MIN_LARGURA / 100 LARGURA_MIN,
       EPA.LARGURA + ICO.VARIACAO_MAX_LARGURA / 100 LARGURA_MAX,
       (SELECT TRIM(VAP.DESCRICAO)
          FROM VW_ENU_STATUS_ATIV_PROD VAP
         WHERE VAP.STATUS_AT = ITE.STATUS_ATIVACAO) DESCR_STATUS,
       (SELECT TRIM(VEX.DESCRICAO)
          FROM VW_ENU_STATUS_ENGENHARIA VEX
         WHERE VEX.STATUS_ENGENHARIA = ITE.STATUS_ENGENHARIA) DESCR_STATUS_ENGENHARIA,
       ITE.FILIAL_IDEAL_PRODUC FILIAL_IDEAL_PRODUCAO,
       ITE.LINHA_PRODUTO,
       (SELECT TRIM(LPR.DESCRICAOLINHA)
          FROM LINHA_PRODUTO LPR
         WHERE LPR.CODIGOLINHA = ITE.LINHA_PRODUTO) DESCR_LINHA_PRODUTO,
       (SELECT TRIM(LPC.DECRICAO)
          FROM LINHAPRODUTOCOMERCIA LPC
         WHERE LPC.LINHAPRODUTOCOMERCIA = ITE.LINHAPRODUTOCOMERCIA) DESCR_LINHA_PROD_COMERCIAL,
       TRIM(UND.DSSIGLA) UM,
       (SELECT TRIM(VD.DESCRICAO)
          FROM VW_ENU_UM_DIMENSIONAL VD
         WHERE VD.SEQ = EPA.UNIMED_DIMENSIONAL) UM_DIM,
       CASE
         WHEN EPA.UNIMED_DIMENSIONAL = 1 THEN
          1
         WHEN EPA.UNIMED_DIMENSIONAL = 2 THEN
          100
         WHEN EPA.UNIMED_DIMENSIONAL = 3 THEN
          2.528
         WHEN EPA.UNIMED_DIMENSIONAL = 4 THEN
          1000
         ELSE
          0
       END FATOR_UM_DIM,
       EPA.LARGURA * (CASE
         WHEN EPA.UNIMED_DIMENSIONAL = 1 THEN
          1
         WHEN EPA.UNIMED_DIMENSIONAL = 2 THEN
          100
         WHEN EPA.UNIMED_DIMENSIONAL = 3 THEN
          2.528
         WHEN EPA.UNIMED_DIMENSIONAL = 4 THEN
          1000
         ELSE
          0
       END) LARG_UM_DIM,
       (EPA.LARGURA - ICO.VARIACAO_MIN_LARGURA / 100) * (CASE
         WHEN EPA.UNIMED_DIMENSIONAL = 1 THEN
          1
         WHEN EPA.UNIMED_DIMENSIONAL = 2 THEN
          100
         WHEN EPA.UNIMED_DIMENSIONAL = 3 THEN
          2.528
         WHEN EPA.UNIMED_DIMENSIONAL = 4 THEN
          1000
         ELSE
          0
       END) LARGURA_MIN_UM_DIM,
       (EPA.LARGURA + ICO.VARIACAO_MAX_LARGURA / 100) * (CASE
         WHEN EPA.UNIMED_DIMENSIONAL = 1 THEN
          1
         WHEN EPA.UNIMED_DIMENSIONAL = 2 THEN
          100
         WHEN EPA.UNIMED_DIMENSIONAL = 3 THEN
          2.528
         WHEN EPA.UNIMED_DIMENSIONAL = 4 THEN
          1000
         ELSE
          0
       END) LARGURA_MAX_UM_DIM,
       CASE
         WHEN SCA.STALT_RAPORT = 1 THEN
          NULL
         ELSE
          EPA.LARGURA_RAPORT
       END LARG_RAPORT_CM,
       CASE
         WHEN SCA.STLARG_RAPORT = 1 THEN
          NULL
         ELSE
          EPA.ALTURA_RAPORT
       END ALTURA_RAPORT_CM,
       EPA.VLPESO_METROS_PECA QUILOS_PECA,
       EPA.COMPRIMENTO_DA_PECA METROS_PECA,
       EPA.PESO_UNIT_RETILINEO PESO_UNIDADE_GRAMAS,
       (SELECT TRIM(VTI.DESCRICAO)
          FROM VW_ENU_TIPO_PRODUTO VTI
         WHERE VTI.SEQ = EPA.TIPOPRODUTO) DESCR_TIPO_PRODUTO,
       PKGUTIL0001.FNC_CNVDATA(ITE.DATA_CADASTRAMENTO, NULL) DATA_CAD,
       ITE.NOME_QUEM_CADASTROU USUARIO_CAD,
       VMA.CODPROG,
       VMA.CODIGO_PROGRAMACAO,
       (SELECT TRIM(GPR.DESCRICAO)
          FROM GRUPO_PRODUTO GPR
         WHERE GPR.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM) DESCR_GRUPO_PROGRAMACAO, --LEONARDO S. KREUSCH T-89685
       ITE.NUMERO_GRUPO_PROGRAM NUM_GP,
       CAST(PKGBASI0001.FNC_DESC_COMPOSICAO_FIBRA(ITE.CODIGO_REDUZIDO) AS
            VARCHAR2(150)) COMPOSICAO,
       EPA.PERC_ENCOLH_COMPR,
       EPA.PERC_ENCOLH_LARGURA,
       DECODE(EPA.INDICEPRIMEIRAQUALID, 0, 100, EPA.INDICEPRIMEIRAQUALID) INDICE_PRI,
       (SELECT COUNT(*)
          FROM OB OBE
         WHERE OBE.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
           AND OBE.STATUS IN (1, 2, 3)) ORDENS_ABERTO,
       (SELECT MAX(MPA.PRODUCAO_DATA)
          FROM BD_PRD_MOVPROD MPA
         WHERE MPA.CODIGO = 1
           AND MPA.REDUZIDO_ITEM = ITE.CODIGO_REDUZIDO) ULT_PROD,
       ITE.STATUS_ATIVACAO STATUS,
       EPA.TIPOPRODUTO TIPO_PRODUTO,
       ITE.CODIGO,
       TRIM(ITE.CODIGO_ALTERNATIVO) CODIGO_ALTERNATIVO,
       (SELECT CFX.CODCLASFISCAL
          FROM CODIGO_FISCAL CFX
         WHERE CFX.CODCLASFISCAL = ITE.CODCLASFISCAL) CLASSIF_FISCAL,
       (SELECT TRIM(CFX.DESCRICAO)
          FROM CODIGO_FISCAL CFX
         WHERE CFX.CODCLASFISCAL = ITE.CODCLASFISCAL) DESCR_CLASSIF_FISCAL,
       ITE.COLECAO,
       (SELECT TRIM(COX.NOME)
          FROM COLECOES COX
         WHERE COX.COLECAO = ITE.COLECAO) DESCR_COLECAO,
       ITE.ESPECIFICACAOPRODUTO EP,
       TRIM(EPE.DESCRICAO) DESCR_ESPECIFICACAO_PRODUTO,
       EPE.IDTIPOEP,
       (SELECT TRIM(BTE.DESCR_TIPO_EP) FROM BENE_TIPO_EP BTE WHERE BTE.ID = EPE.IDTIPOEP) DESCR_TIPO_EP,
       ITE.STATUS_ENGENHARIA,
       CASE
          WHEN ITE.STATUS_ENGENHARIA = 0 THEN 9181951 -- CADASTRADO / ROSA
          WHEN ITE.STATUS_ENGENHARIA = 1 THEN 1381887 -- BLOQUEADO / VERMELHO
          WHEN ITE.STATUS_ENGENHARIA = 3 THEN 1769471 -- LIB COM RESTRIAÇÃO / AMARELO
          ELSE 0
       END RGB_STATUS_ENGENHARIA,
       (SELECT TRIM(VGI.DESCR_GRUPO_ITEM)
          FROM VW_F7_GRUPO_ITEM VGI
         WHERE VGI.IDGI = MTI.IDGRUPOITEM) DESCR_GRUPO_ITEM,
       MTI.IDGRUPOITEM IDGI,
       ITE.LINHAPRODUTOCOMERCIA LINHA_PROD_COMERCIAL,
       VMA.ESTAMPADO,
       VMA.ESTAMPADO ESTAMP,
       ITE.IDLEPROJETO,
       ITE.TESITUACAOPRODUTO,
       (SELECT TRIM(VSP.DESCRICAO)
          FROM VW_ENU_SITUACAO_PRODUTO VSP
         WHERE VSP.TESITUACAOPRODUTO = ITE.TESITUACAOPRODUTO) DESCR_SITUACAO_PRODUTO,
       (SELECT TRIM(EGD.DSGRUPODIMENSAO)
          FROM ENG_GRUPODIMENSAO EGD
         WHERE EGD.IDGRUPODIMENSAO = EPA.IDGRUPODIMENSAO) DESCR_GRUPO_DIMENSAO,
       Case
          When psi.cbusaaconddimensao = '1' then (SELECT MAX(CDI.DESCRICAO) FROM ENG_GRUPO_DIME_ACOND EDI, COML_DIMENSOES CDI
            WHERE EDI.IDGRUPODIMENSAO = EPA.IDGRUPODIMENSAO AND EDI.CBACONDPADRAODIMGRUP = '1' AND CDI.DIMENSAO = EDI.DIMENSAO)
          Else null
       end DESCR_DIMENSAO,
       Case
          When psi.cbusaaconddimensao = '1' then (SELECT MAX(TIA.DESCRICAO) FROM ENG_GRUPO_DIME_ACOND EDI, TIPO_ACONDICIONAMENT TIA
            WHERE EDI.IDGRUPODIMENSAO = EPA.IDGRUPODIMENSAO AND EDI.CBACONDPADRAODIMGRUP = '1' AND TIA.IDACONDICIONAMENTO = EDI.IDACONDICIONAMENTO)
          Else (SELECT MAX(TIA.DESCRICAO) FROM TIPO_ACONDICIONAMENT TIA WHERE TIA.IDACONDICIONAMENTO = ITE.COD_ACONDICIONAMENTO)
       end DESCR_ACONDICIONAMENTO,
       Case
          When psi.cbusaaconddimensao = '1' then (SELECT MAX(EDI.IDACONDICIONAMENTO) FROM ENG_GRUPO_DIME_ACOND EDI
            WHERE EDI.IDGRUPODIMENSAO = EPA.IDGRUPODIMENSAO AND EDI.CBACONDPADRAODIMGRUP = '1')
          Else ITE.COD_ACONDICIONAMENTO
       end IDACONDICIONAMENTO,
       ITE.CODIGO_COMERCIAL,
       ITE.IDUNIDADEMEDIDA,
       TRIM(ITE.IDMASCARATIPOINSUMO) IDMASCARA,
       TRIM(MTI.DSPRIMEIRONIVEMASCAR) DESCR_MASCARA,
       DECODE(NVL((SELECT GPR.STCORTEORELA
                    FROM GRUPO_PRODUTO GPR
                   WHERE GPR.NUMERO_GRUPO_PROGRAM =
                         ITE.NUMERO_GRUPO_PROGRAM),
                  0),
              1,
              'SIM',
              'NÃO') DESCR_CORTE_OURELA, --LEONARDO S. KREUSCH T-89685
       (SELECT TRIM(MAX(FEX.DESCRICAO))
          FROM FAMILIA_ESTOQUE FEX
         WHERE FEX.FAMILIA_ESTOQUE = ITE.FAMILIA_ESTOQUE) DESCR_FAMILIA_ESTOQUE,
       TRIM(ITE.FAMILIA_ESTOQUE) FAMILIA_ESTOQUE,
       CAST((SELECT UTL_RAW.CAST_TO_VARCHAR2(E.BLOBSERVACAOENG)
               FROM ENG_OBSERVACOES E
              WHERE E.IDOBSERVACAOENG = ITE.IDOBSERVACAOENG) AS
            VARCHAR2(500)) OBSERVACAO_ENG_PRODUTO,
       (SELECT NVL(GPR.STCORTEORELA, 0)
          FROM GRUPO_PRODUTO GPR
         WHERE GPR.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM) CORTE_OURELA, --LEONARDO S. KREUSCH T-89685
       EPA.IDGRUPODIMENSAO,
       ITE.TIPO_ITEM,
       VMA.TIPO_PROD,
       VMA.INTERMEDIARIO,
       UND.TPUNIDADEMEDIDA,
       TRIM(ICO.GRUPO_SIMBOLOGIA) GRUPO_SIMBOLOGIA,
       (SELECT TRIM(GPS.DESCRICAO)
          FROM GRUPO_SIMBOLOGIA GPS
         WHERE GPS.CODIGO = ICO.GRUPO_SIMBOLOGIA) DESCR_GRUPO_SIMBOLOGIA,
       ITE.INSUMO_COM_MOVIMENTO ITEM_ATIVO,
       NVL((SELECT FAM.IDFAMILIAACABADO
             FROM FAMILIA_ACABADO FAM
            WHERE FAM.CODIGO_FAMILIA = ITE.CODIGO_FAMILIA
              AND ITE.CODIGO_REGISTRO = FAM.CODIGO_REGISTRO),
           0) IDFAMILIA,
       (SELECT TRIM(FAM.DESCRICAO_FAMILIA)
          FROM FAMILIA_ACABADO FAM
         WHERE FAM.CODIGO_FAMILIA = ITE.CODIGO_FAMILIA
           AND ITE.CODIGO_REGISTRO = FAM.CODIGO_REGISTRO) DESCR_FAMILIA,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ACABAMENTO,
                                                 2) AS VARCHAR2(30)) DESCR_ACABAMENTO,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.VAR_ARTIGO,
                                                 1) AS VARCHAR2(30)) VAR_ARTIGO,
       CAST(DECODE(TRIM(REPLACE(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                                     NV.VAR_ARTIGO,
                                                                     1),
                                '0',
                                '')),
                   NULL,
                   PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                        NV.ARTIGO,
                                                        1),
                   PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                        NV.ARTIGO,
                                                        1) || '/' ||
                   PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                        NV.VAR_ARTIGO,
                                                        1)) AS VARCHAR2(30)) ARTIGO_VAR,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.DIMENSAO,
                                                 1) AS VARCHAR2(30)) DIMENSAO_COD,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ESTRUTURA,
                                                 2) AS VARCHAR2(30)) DESCR_ESTRUTURA,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.DESENHO,
                                                 2) AS VARCHAR2(30)) DESCR_DESENHO,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.VARIANTE,
                                                 2) AS VARCHAR2(30)) DESCR_VARIANTE,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.PROCESSO,
                                                 2) AS VARCHAR2(30)) DESCR_PROCESSO,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB1,
                                                 1) AS VARCHAR2(10)) ATRIB1,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB2,
                                                 1) AS VARCHAR2(10)) ATRIB2,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB3,
                                                 1) AS VARCHAR2(10)) ATRIB3,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB1,
                                                 2) AS VARCHAR2(30)) DESCR_ATRIB1,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB2,
                                                 2) AS VARCHAR2(30)) DESCR_ATRIB2,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.ATRIB3,
                                                 2) AS VARCHAR2(30)) DESCR_ATRIB3,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.VAR_ARTIGO,
                                                 2) AS VARCHAR2(30)) DESCR_VAR_ARTIGO,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.DIMENSAO,
                                                 2) AS VARCHAR2(30)) DESCR_DIMENSAO_COD,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.CLIENTE,
                                                 1) AS VARCHAR2(30)) CLIENTE_ITEM,
       CAST(PKGPROD0001.FNC_RETORNA_NIVEL_CODIND(ITE.CODIGO_REDUZIDO,
                                                 NV.CLIENTE,
                                                 2) AS VARCHAR2(30)) DESCR_CLIENTE_ITEM,
       DECODE(VMA.ESTAMPADO,
              1,
              (SELECT MAX(TRIM(TVR.DESCRICAO))
                 FROM ENGEITEMESTOVARDESEN EID,
                      VARIANTE_DESENHO     VDE,
                      TIPOSVARIANTE        TVR
                WHERE EID.CDREDUZIDO = VMA.CODIGO_REDUZIDO
                  AND TRIM(VDE.CODIGO_DESENHO) = TRIM(EID.CDDESENHO)
                  AND TRIM(VDE.CODIGO_VARIANTE) = TRIM(EID.CDVARIANTE)
                  AND TVR.IDTIPOVARIANTE = VDE.IDTIPOVARIANTE),
              '') DESCR_TIPO_VARIANTE,
       DECODE(PLM.REDUZIDO, NULL, 0, 1) APROG_PLANO,
       DECODE(ITE.NUMERO_GRUPO_PROGRAM, NULL, 0, 1) TEM_GP,
       TRIM((SELECT GPC.CODIGO
              FROM GRUPO_CUSTO GPC
             WHERE GPC.ID = ITE.IDGRUPO_CUSTO)) GRUPO_CUSTO,
       (SELECT GPC.DESCRICAO
          FROM GRUPO_CUSTO GPC
         WHERE GPC.ID = ITE.IDGRUPO_CUSTO) DESCR_GRUPO_CUSTO,
       ITE.IDPESSOAFJ_EXCLUSIVO,
       DECODE(ITE.IDPESSOAFJ_EXCLUSIVO,
              NULL,
              '',
              (SELECT TRIM(PFJ.NOME)
                 FROM PESSOASFJ PFJ
                WHERE PFJ.IDPESSOAFJ = ITE.IDPESSOAFJ_EXCLUSIVO)) NOME_CLIENTE_EXCLUSIVO,
       --       DECODE(ITE.IDPESSOAFJ_EXCLUSIVO,NULL,0,1) ITEM_EXCLUSIVO,
       DECODE(NVL((SELECT COUNT(CPE.IDPESSOAFJ)
                    FROM COML_PRODEXCLUSIVO CPE
                   WHERE CPE.REDUZIDO = ITE.CODIGO_REDUZIDO),
                  0),
              0,
              0,
              1) ITEM_EXCLUSIVO,
       (SELECT TRIM(VTR.DESCRICAO)
          FROM VW_ENU_TIPOREPOSICAOESTOQUE VTR
         WHERE VTR.SEQ = ITE.TIPOREPOSICAO) DESCR_TIPO_REPOSICAO,
       (SELECT TRIM(GPA.DESCRICAO)
          FROM POVITEMESTOGRUPOARTI POVGA, GRUPO_ARTIGO GPA
         WHERE POVGA.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
           AND GPA.IDGRUPOARTIGO = POVGA.IDGRUPOARTIGO) DESCR_GRUPO_ARTIGO,
       (SELECT TRIM(GPC.DESCRICAO)
          FROM POVITEMESTOGRUPOCOML POVGC, GRUPO_COMERCIAL GPC
         WHERE POVGC.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
           AND GPC.IDGRUPOCOMERCIAL = POVGC.IDGRUPOCOMERCIAL) DESCR_GRUPO_COMERCIAL,
       ITE.TIPOREPOSICAO,
       ITE.IDCAMA_SUBTIPOPROD,
       (SELECT TRIM(ECS.DESCRICAO)
          FROM ENG_CAMA_SUBTIPOPROD ECS
         WHERE ECS.ID = ITE.IDCAMA_SUBTIPOPROD) DESCR_SUB_TIPO_PRODUTO,
       ITE.USAENGEQUALIDADE USA_QUAL,
       ITE.REDUZIDO_AGRUPADOR ID_ENG_PRODUTO,
       (SELECT TRIM(GPE.DESCRICAO) FROM eng_grupo_produto GPE WHERE GPE.ID = ITE.REDUZIDO_AGRUPADOR) DESCR_ENG_PRODUTO,
       (SELECT TRIM(GPE.CODIGO) FROM eng_grupo_produto GPE WHERE GPE.ID = ITE.REDUZIDO_AGRUPADOR) COD_ENG_PRODUTO,
       ITE.REDUZIDO_AGRUPADOR
  FROM ITENS_ESTOQUE ITE,
       PARAMETROS_SISTEMA PSI,
       ENG_PRODG_ACABADO EPA,
       BD_BAS_MASCPRODACAB VMA,
       ITENS_COMPLEMENTO ICO,
       MASCARA_TIPO_INSUMO MTI,
       ESPECIFICACAO_PRODUT EPE,
       UNIDADE_MEDIDA UND,
       (SELECT MAX(DECODE(TRIM(PCO.ITEM), 'ARTIGO', PCO.TPNIVELMASCARA, 0)) ARTIGO,
               MAX(DECODE(TRIM(PCO.ITEM),
                          'VAR_ARTIGO',
                          PCO.TPNIVELMASCARA,
                          0)) VAR_ARTIGO,
               MAX(DECODE(TRIM(PCO.ITEM), 'COR', PCO.TPNIVELMASCARA, 0)) COR,
               MAX(DECODE(TRIM(PCO.ITEM), 'DESENHO', PCO.TPNIVELMASCARA, 0)) DESENHO,
               MAX(DECODE(TRIM(PCO.ITEM), 'VARIANTE', PCO.TPNIVELMASCARA, 0)) VARIANTE,
               MAX(DECODE(TRIM(PCO.ITEM), 'PROCESSO', PCO.TPNIVELMASCARA, 0)) PROCESSO,
               MAX(DECODE(TRIM(PCO.ITEM),
                          'ACABAMENTO',
                          PCO.TPNIVELMASCARA,
                          0)) ACABAMENTO,
               MAX(DECODE(TRIM(PCO.ITEM), 'ESTRUTURA', PCO.TPNIVELMASCARA, 0)) ESTRUTURA,
               MAX(DECODE(TRIM(PCO.ITEM), 'DIMENSAO', PCO.TPNIVELMASCARA, 0)) DIMENSAO,
               MAX(DECODE(TRIM(PCO.ITEM), 'CLIENTE', PCO.TPNIVELMASCARA, 0)) CLIENTE,
               MAX(DECODE(TRIM(PCO.ITEM), 'ATRIB1', PCO.TPNIVELMASCARA, 0)) ATRIB1,
               MAX(DECODE(TRIM(PCO.ITEM), 'ATRIB2', PCO.TPNIVELMASCARA, 0)) ATRIB2,
               MAX(DECODE(TRIM(PCO.ITEM), 'ATRIB3', PCO.TPNIVELMASCARA, 0)) ATRIB3
          FROM PARAMETROS_CODIGO PCO
         WHERE PCO.CODIGO LIKE 'PROD_ACA%'
         GROUP BY TRIM(PCO.CODIGO)) NV,
         /*
       (SELECT REDUZIDO
          FROM (SELECT (IP.REDUZIDOITEM) AS REDUZIDO
                  FROM ITENSPEDIDOCOMERCIAL IP
                 WHERE IP.SITUACAOITEM IN
                       (0, 1, 2, 3, 7, 8, 9, 10, 11, 16, 18)
                   AND IP.QUALIDADE_SINTETICA = 1
                   AND IP.ESTOQUE <> 'S'
                UNION ALL
                SELECT (IDE.CODIGO_REDUZIDO_DESC) AS REDUZIDO
                  FROM ITENSPEDIDOCOMERCIAL IP,
                       ITENS_DESCENDENCIA   IDE,
                       GRUPO_FLUXO          GFL
                 WHERE IP.SITUACAOITEM IN
                       (0, 1, 2, 3, 7, 8, 9, 10, 11, 16, 18)
                   AND IP.QUALIDADE_SINTETICA = 1
                   AND IP.ESTOQUE <> 'S'
                   AND IDE.CODIGO_REDUZIDO = IP.REDUZIDOITEM
                   AND GFL.IDGRUPOFLUXO = IDE.IDGRUPOFLUXO
                   AND GFL.STATUS IN (0, 1)
                UNION ALL
                SELECT (ID2.CODIGO_REDUZIDO_DESC) AS REDUZIDO
                  FROM ITENSPEDIDOCOMERCIAL IP,
                       ITENS_DESCENDENCIA   IDE,
                       GRUPO_FLUXO          GFL,
                       ITENS_DESCENDENCIA   ID2,
                       GRUPO_FLUXO          GF2
                 WHERE IP.SITUACAOITEM IN
                       (0, 1, 2, 3, 7, 8, 9, 10, 11, 16, 18)
                   AND IP.QUALIDADE_SINTETICA = 1
                   AND IP.ESTOQUE <> 'S'
                   AND IDE.CODIGO_REDUZIDO = IP.REDUZIDOITEM
                   AND GFL.IDGRUPOFLUXO = IDE.IDGRUPOFLUXO
                   AND GFL.STATUS IN (0, 1)
                   AND ID2.CODIGO_REDUZIDO = IDE.CODIGO_REDUZIDO_DESC
                   AND GF2.IDGRUPOFLUXO = ID2.IDGRUPOFLUXO
                   AND GF2.STATUS IN (0, 1)
                UNION ALL
                SELECT (PLP.REDUZIDO) AS REDUZIDO
                  FROM PLPLANOMENSAL PLP
                 WHERE PLP.STATUS IN (0, 1, 2)
                UNION ALL
                SELECT (OFI.REDUZIDO) AS REDUZIDO
                  FROM OFITENS OFI
                 WHERE OFI.STATUS > 1
                UNION ALL
                SELECT (OFO.REDUZIDOORIGEM) AS REDUZIDO
                  FROM OFORIGENS OFO, OFITENS OFI
                 WHERE OFI.STATUS > 1
                   AND OFO.NUMEROOF = OFI.NUMEROOF)
         GROUP BY REDUZIDO) PLM,
         */
         VW_ENG_ITEM_APROG PLM,
       (SELECT TO_NUMBER(SUBSTR(TRIM(SCAX.CHAVE),
                        1,
                        INSTR(TRIM(SCAX.CHAVE), ';', 1) - 1)) REDUZIDO_AGRUPADOR,
       MAX(CASE WHEN trim(SCAX.CAMPO) = 'ALTURA_RAPORT'  THEN 1 ELSE 0 END) STALT_RAPORT,
       MAX(CASE WHEN trim(SCAX.CAMPO) = 'LARGURA_RAPORT' THEN 1 ELSE 0 END) STLARG_RAPORT
  FROM ENGSTATUSCAMPOS SCAX
 WHERE trim(SCAX.TABELA) = 'ENG_PRODG_ACABADO'
 GROUP BY TRIM(SCAX.CHAVE)) SCA
 WHERE ITE.TIPO_ITEM = 10
   AND EPA.REDUZIDO_AGRUPADOR = ITE.REDUZIDO_AGRUPADOR
   AND VMA.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   AND ICO.CODIGO_REDUZIDO = ITE.CODIGO_REDUZIDO
   AND MTI.IDMASCARATIPOINSUMO = ITE.IDMASCARATIPOINSUMO
   AND UND.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
   AND PLM.REDUZIDO(+) = ITE.CODIGO_REDUZIDO
   AND SCA.REDUZIDO_AGRUPADOR(+) = EPA.REDUZIDO_AGRUPADOR
   AND EPE.ESPECIFICACAOPRODUTO (+) = ITE.ESPECIFICACAOPRODUTO

