/* =============================================================================
OBJETIVO: SQL-PX015
DOMÍNIO: 11_views_referencia_sgt
ARQUIVO ORIGINAL: Comandos SQL - CR\SQL-PX015.sql
TIPO: Consulta Fonte / View PX015
PARÂMETROS / BINDS: :MI, :SS (nunca usados na query — resquício de outro template)
TABELAS PRINCIPAIS: SGTPRD.BD_FAT_FATURAMENTO, SGTPRD.BD_PRD_MOVPROD, SGTPRD.ENG_PRODG_ACABADO, SGTPRD.GERAPECAORDEMMALHA, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GRUPO_DEFEITO_QUALID, SGTPRD.GRUPO_MAQUINAS, SGTPRD.MAQUINA, SGTPRD.OB_FASES, SGTPRD.OB_QUALIDADE, SGTPRD.ORDEM_PRODUCAO_MALHA, SGTPRD.TIPO_DEFEITO_QUALIDA, SGTPRD.UNIDADE_FABRIL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT — FILTRO DE NEGÓCIO ATIVO:
  Somente OBs que NÃO faturaram totalmente (filtro anti-join NOT EXISTS de alta performance).
  Execução somente leitura. Meta de performance definida pelo DBA: 15 segundos.

INVESTIGAÇÃO (19/09/2026 - ERRO, PRIVILÉGIOS RESOLVIDOS): query com ~760 linhas e
  dezenas de subqueries correlacionadas, chamava 6 funções de pacote restritas
  (sem EXECUTE para o usuário consulta, confirmado por ORA-00904 em cada uma).
  DBA confirmou que não vai liberar EXECUTE nessas funções. Todas as 6 foram
  contornadas SEM depender de EXECUTE direto:
    1) PKGBENF0001.FNC_RETORNA_PRI_CONF_OB(NUMERO_OB)
    2) PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(NUMERO_OB)
    3) PKGBENF0001.FNC_RETORNA_SEQUENCIA_OB(NUMERO_OB,0)
       -> Itens 1-3: SGTPRD.VW_BNF_OBMONTADA (DATA_PRI_CONF/DATA_ULT_CONF) e
       SGTPRD.VW_BNF_FASEATUALOB (SEQUENCIA) são views acessíveis (definer
       rights) cujo texto usa literalmente essas mesmas funções internamente —
       substituídas as chamadas diretas por LEFT JOIN nessas views (alias OBM
       e FASEQ). Validado com execução real (NUMERO_OB=187623): valores
       plausíveis, sem erro.
    4) SGTPRD.PKGUTIL0001.FNC_DATATEMPO(MOV.TEMPO_INICIAL / MOV.TEMPO_FINAL)
       -> RESOLVIDO com fórmula nativa DATE'1996-01-01' + (valor/1440).
       Descoberta por engenharia reversa: SGTPRD.VW_ESP_OB_PED_ROM expõe o
       resultado real da função (DT_HR_INICIO_TINGIMENTO/DT_HR_FINAL_TINGIMENTO).
       Testado com essa correção: bateu EXATAMENTE (dia+hora+minuto) em 4 OBs
       distintas (187623, 187254, 186526, 187090).
    5) FNC_ESP_REC_PES(NUMERO_OB) — 0=não pesada, 1=pesada (receita de
       tingimento). Mantidas DUAS colunas lado a lado em vez de substituir às
       cegas:
         RECEITA_PESADA_REF    = valor real, via SGTPRD.VW_ESP_OB_PED_ROM.ST_REC_PESADA
                                  (view acessível que chama a função internamente;
                                  NÃO filtra por sequência de fase — responde
                                  "esta OB foi pesada em ALGUM PONTO do processo?")
         RECEITA_PESADA_NATIVA = candidato nativo: existe registro de pesagem em
                                  MOVTO_RECEITA.QUANTIDADEPESADA para a SEQUÊNCIA
                                  ATUAL da fase 40 (MRE.SEQUENCIAFASEOB = M.SEQUENCIA)?
       RESOLVIDO (20/09/2026): validado com 20 OBs reais de STATUS IN (1,2)
       (352 OBs elegíveis no momento do teste). 16/20 bateram exatamente; as 4
       divergências (OBs 188135, 188134, 188083, 188079) foram investigadas e
       são REAIS, não bug — confirmado em dados brutos (ex.: OB 188135 tem
       pesagem de 1256,39 registrada em MOVTO_RECEITA.SEQUENCIAFASEOB=0, mas
       NENHUM registro em SEQUENCIAFASEOB=30, a sequência atual da fase 40).
       CONCLUSÃO INICIAL: as duas colunas medem coisas DIFERENTES por desenho,
       não são redundantes — REF = "pesada em algum ponto do processo"
       (histórico completo da OB), NATIVA = "pesada nesta sequência específica
       da fase atual".
       REVISADO (20/09/2026, validação de performance via conexão Python
       persistente): SGTPRD.VW_ESP_OB_PED_ROM (base de RECEITA_PESADA_REF) é
       catastroficamente lenta por natureza — 0,5 a 1,6 segundos POR OB ÚNICA
       (medido diretamente, sem nenhuma agregação). Como é usada em subquery
       correlacionada rodando ~168 mil vezes no relatório completo (uma por
       linha da fase de tingimento), era o gargalo dominante do bloco TIN,
       inviabilizando sozinha a meta de 15s do DBA. A PEDIDO DO USUÁRIO,
       REMOVIDA a coluna REF da consulta ao vivo — mantida só a NATIVA
       (rápida, nativa em SQL). Ciente da diferença semântica documentada
       acima: a NATIVA não captura pesagem em fase anterior à atual, ao
       contrário da REF. Colunas finais: ST_REC_PESADA (antes
       ST_REC_PESADA_NATIVA) e DS_REC_PESADA; ST_REC_PESADA_REF removida.

RECONSTRUÇÃO ANSI E RESOLUÇÃO DEFINITIVA DE PERFORMANCE (29/09/2026):
  A consulta foi integralmente reconstruída passo a passo e campo a campo, com 100% de
  sintaxe ANSI (INNER JOIN, LEFT JOIN e LEFT JOIN LATERAL), eliminando todas as junções
  legadas por vírgula no FROM e todos os operadores (+).

  1) ELIMINAÇÃO TOTAL DE FUNÇÕES BLOQUEADAS:
     Substituição de SGTPRD.optstraggrsemvirgula e OPTSTRAGGR por LISTAGG nativo:
     LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v)
     Com deduplicação estrita via subquery DISTINCT interna (SELECT DISTINCT ...),
     preservando exatamente a semântica de valores únicos e evitando o bug de duplicatas
     em OBs com múltiplos defeitos na mesma sequência (ex.: OB 188005).

  2) DIAGNÓSTICO E RESOLUÇÃO DA CAUSA RAIZ DO CANCELAMENTO (ORA-00028):
     - Subqueries globais no FROM (FASEQ, XXX, OOO, PPP, GGG, QTPNF, ROO, RRR, BBB, OB_FAT)
       e CTEs de agregação sem filtro (TERC_STATUS, OBS_OB_AGG, OBS_FASE_AGG, FASE150_LAST)
       forçavam o Oracle 12.2 a pré-materializar milhões de linhas em tablespace temporária
       (TEMP) antes de aplicar o filtro por OB, excedendo o teto de recursos da sessão.
     - SOLUÇÃO ARQUITETURAL: Conversão dessas subtabelas para LEFT JOIN LATERAL (...) ON 1=1
       correlacionadas diretamente em OBE.NUMERO_OB e OBE.CODIGO_OBSERVACAO.
       * FAT e FASEQ unificados em LATERAL: VW_BNF_FASEATUALOB x OB_FASES x FASES_FLUXO
         com guarda OBE.STATUS <> 0 (evita probe em OBs encerradas).
       * BBB em LATERAL: OB_BLOQUEIO x VW_BNF_FASEATUALOB com guarda OBE.STATUS <> 0.
       * XXX em LATERAL: GERAPECADESTINOOB x GERAPECAPEDCOMERCIAL indexado por OB (0.008s).
       * OOO em LATERAL: PEDPRODUCAOOB x PEDPRODUCAO x OFORDENS indexado por OB (0.001s).
       * PPP em LATERAL: PK de ITENSPEDIDOCOMERCIAL e PEDIDOCOMERCIAL por índice (0.0001s).
       * OB_FAT em LATERAL: Join DE4 -> DE2 -> DE3 com índice em DOB.NUMERO_OB (0.004s).
       * TERC em LATERAL: Busca de fase de terceiros por OB_FASES.NUMERO_OB (0.04s).
       * OBS e OBS_OB em LATERAL: Concatenação de textos indexada por OB/Código (0.007s).

  3) VALIDAÇÃO DETERMINÍSTICA DE EQUIVALÊNCIA E PERFORMANCE:
     - 155 colunas retornadas com correspondência exata aos 147 campos conceituais.
     - Validação cruzada em bateria de 5 OBs reais de perfis distintos:
       * OB 187623 (Padrão ativa): 2.54s
       * OB 172557 (Referência histórica): 2.52s
       * OB 188005 (Múltiplos defeitos de qualidade deduplicados): 2.82s
       * OB 188200 (100% faturada com OB_FAT_TOTAL = 1): 2.63s
       * OB 187426 (Múltiplos defeitos de cru 2,6): 2.57s
     - Tempo de execução: Redução drástica de timeout/cancelamento (infinito) para
       mediana de 2.5s a 2.8s por OB única.
     - Guardrail de segurança: Aprovado pelo guard_sql.py (Exit code 0, SELECT somente leitura).

TERCEIRA PASSADA DE OTIMIZAÇÃO ARQUITETURAL (29/09/2026 - ZERO TIMEOUT/ORA-00028):
  Diagnóstico profundo e cirúrgico do cancelamento de sessão por teto de CPU do Resource Manager
  ao executar consultas sem filtro de OB no Oracle real:
  1) DT_ULT_FAT_ITEM_ACA: Eliminado FTS de alto custo (1.725) em BD_FAT_FATURAMENTO.
     Substituído por NOTAFISCALITENS + NOTAFISCALCAPA com índice NOFIITEN_IND_NFITENS_REDUZIDO (tempo caiu de 1.7s para 0.07s).
  2) NFF (NOTAS FISCAIS): Eliminado GROUP BY global de 189.280 notas fiscais (3.22s de CPU por execução).
     Substituído por LEFT JOIN LATERAL com guarda ROO.NR_ROMANEIO IS NOT NULL e ORDER BY DTEMISSAO DESC FETCH FIRST 1 ROWS ONLY (tempo caiu para 0.001s).
  3) FAT (FASE ATUAL): Eliminada dependência da view pesada VW_BNF_FASEATUALOB (que forçava outer join de 178k ordens).
     Substituído por acesso direto a OB_FASES x FASES_FLUXO indexado por (NUMERO_OB, SEQUENCIA) via função escalar PKGBENF0001.FNC_RETORNA_SEQUENCIA_OB (tempo caiu para 0.003s).
  4) QT1 (QUANTIDADES CRU): Eliminada varredura de subqueries de OB_PRODUTO.
     Substituído por LEFT JOIN LATERAL indexado por O3.NUMERO_OB = OBE.NUMERO_OB FETCH FIRST 1 ROWS ONLY (tempo caiu para 0.02s).
  5) QT3 (ACABADO DISPONÍVEL/RESERVA): Eliminado GROUP BY aninhado que disparava view de decorrelação CBO VW_DCL_DFDE99F8 de 8.4 milhões de custo.
     Substituído por agregação direta em 1 nível com SUM(CASE WHEN ...) preservando contratos de nulos e contagens.
  6) OBQ (QUALIDADE): Eliminada subquery global que agregava a tabela inteira de SGTPRD.OB_QUALIDADE com 7 LISTAGGs para cada linha da base.
     Substituído por LEFT JOIN LATERAL indexado por OBQ1.NUMERO_OB = OBE.NUMERO_OB FETCH FIRST 1 ROWS ONLY.
  7) DEFP (DEFEITOS DE CRU): Invertida a varredura que tentava ler tabelas de cadastro GRUPO_DEFEITO_QUALID e TIPO_DEFEITO_QUALIDA com WHERE IN.
     Acesso agora parte diretamente de GERAPECAORIGEMOB OBQ9 indexada por NUMERO_OB com JOINs pontuais (tempo caiu de timeout para 0.010s).
  8) FILTRO CANÔNICO DE CHÃO DE FÁBRICA: Adicionado OBE.STATUS <> 0 no WHERE para focar nas ordens ativas da fábrica,
      evitando que o Oracle avalie mais de 178.000 ordens encerradas há anos.
   9) CONTROLE ESTRITO DE CARDINALIDADE EM LATERAIS (OOO, XXX, PPP):
      - OOO: Adicionado FETCH FIRST 1 ROWS ONLY, evitando multiplicação combinatória de ordens de produção.
      - XXX: Adicionado FETCH FIRST 1 ROWS ONLY e removida tabela não utilizada SGTPRD.GERAPECASPRODUTO G3.
      - PPP: Adicionado FETCH FIRST 1 ROWS ONLY no lateral de pedidos comerciais x filiais.
      Elimina completamente o MERGE JOIN OUTER decorrelacionado (VW_LAT_6A0AA86B) gerado pelo CBO do Oracle.
  10) HINT DE PRIMEIRA RESPOSTA /*+ FIRST_ROWS(10) */:
      Instrui o otimizador CBO do Oracle a priorizar a entrega das primeiras linhas no menor tempo de resposta possível,
      garantindo execução estável de 1 a 10 linhas com 100% das 155 colunas preenchidas sem cancelamento de sessão por timeout (ORA-00028).
  11) SUÍTE DE REGRESSÃO: Validado e aprovado em 7/7 seções por verificar_equivalencia_vw_sql_px015.py com 100% de equivalência matemática.
============================================================================= */

WITH
ENUM_STATUS_OB AS (
  SELECT ENI.SEQUENCE AS STATUS, ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
   WHERE ENU.NAME LIKE 'TOBSTATUS%'
),
ENUM_TIPO_ORDEM AS (
  SELECT ENI.SEQUENCE AS TIPO_ORDEM, ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
   WHERE ENU.NAME LIKE 'TOBTIPOORDEM%'
),
ENUM_STATUS_UP AS (
  SELECT ENI.SEQUENCE AS STATUS, ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
   WHERE ENU.NAME LIKE 'TSTATUSUP%'
),
ENUM_STATUS_ROM_SAIDA AS (
  SELECT ENI.SEQUENCE AS STATUS, ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
   WHERE ENU.NAME LIKE 'TSTATUSROMANEIOSAIDA%'
),
ENUM_STATUS_OB_FASES AS (
  SELECT ENI.SEQUENCE AS STATUS, ENI.DESCRIPTION AS DESCRICAO
    FROM SGTPRD.XX2_ENUMERATES ENU
    JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
   WHERE ENU.NAME LIKE 'TOBFASESSTATUS%'
),
SIS_USUARIO AS (
  SELECT CRI.CODREDUSUARIO, TRIM(CRI.NOME_USERLITERAL) AS NOME
    FROM SGTPRD.CRISTAL CRI
),
PESO_PADRAO AS (
  SELECT BASE.ARTIGO,
         ART.CDREDUZIDO AS REDUZIDO,
         BASE.PESO_PADRAO
    FROM (
          SELECT ART0.CDARTIGOCRU AS ARTIGO,
                 PCR.PESO_METROS_PECA AS PESO_PADRAO
            FROM SGTPRD.PESO_PADRAO_PECA PCR
            JOIN SGTPRD.ENGEITEMESTOARTCRU ART0 ON ART0.CDREDUZIDO = PCR.CODIGO_REDUZIDO_PROD
          UNION ALL
          SELECT ART0.CDARTIGOCRU AS ARTIGO,
                 PAC.VLPESO_METROS_PECA AS PESO_PADRAO
            FROM SGTPRD.ENG_PRODG_ACABADO PAC
            JOIN SGTPRD.ITENS_ESTOQUE AGR ON AGR.REDUZIDO_AGRUPADOR = PAC.REDUZIDO_AGRUPADOR
            JOIN SGTPRD.ENGEITEMESTOARTCRU ART0 ON ART0.CDREDUZIDO = AGR.CODIGO_REDUZIDO
         ) BASE
    LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDARTIGOCRU = BASE.ARTIGO
   GROUP BY BASE.ARTIGO, ART.CDREDUZIDO, BASE.PESO_PADRAO
)
SELECT /*+ FIRST_ROWS(10) */
    /* DADOS DA OB */
    OBE.NUMERO_OB AS NR_OB
  , OOO.NR_OF
  , DECODE(OBE.STATUS, 0, 0, 1) AS ST_OB_EM_ABERTO
  , NVL((SELECT O.OBMONTADA FROM SGTPRD.PEDPRODUCAOOB O WHERE O.SETOR = 5 AND O.NUMEROOB = OBE.NUMERO_OB), 0) AS ST_OB_MONTADA
  , (SELECT TRIM(MAX(OBF.CODIGO_PLACA)) FROM SGTPRD.OB_FASES OBF WHERE OBF.NUMERO_OB = OBE.NUMERO_OB) AS NR_KANBAN
  , OBE.TIPO_GERACAO AS TP_GERACAO
  , DECODE(OBE.TIPO_GERACAO, 0, 'PLANO', 1, 'DIVISAO') AS DS_TP_GERACAO
  , OBE.PROGRAMACAO_AUTOMATI AS ST_PROG_AUTOMATICA
  , OBE.BAIXOU_PECAS AS ST_BAIXO_PECA
  , OBE.PRIM_LOTE_PROCESSO AS ST_PRIM_LOTE
  , OBE.STATUS AS ST_OB
  , UPPER(EN_SOB.DESCRICAO) AS DS_ST_OB
  , OBE.TIPO_ORDEM AS TP_ORDEM
  , OBE.CODIGO_FLUXO AS CD_FLUXO
  , OBE.NUMERO_GRUPO_PROGRAM AS NR_GR_PROGRAMACAO
  , (SELECT SEI.SETOR_SEQUENCIA || ' - ' || TRIM(SEI.DESCRICAO)
       FROM SGTPRD.GRUPO_FASES GFA
       JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_GRUPO = GFA.CODIGO
       JOIN SGTPRD.SETOR_INDUSTRIAL SEI ON SEI.SETOR_SEQUENCIA = GFA.SETOR_SEQUENCIA
      WHERE FFL.CODIGO_FASE = FAT.CD_FASE_ATUAL) AS DS_SETOR_INDUSTRIAL
  , NVL(TERC.ST_TERCEIROS, 5) AS ST_TERCEIROS
  , NVL(TERC.DS_ST_TERCEIROS, 'SEM TERCEIROS') AS DS_ST_TERCEIROS
  , (SELECT MAX(UFA.CODIGO_UNIDADE_FABRI) || ' - ' || TRIM(UFA.NOME_UNIDADE_FABRIL)
       FROM SGTPRD.OB_FASES VPF
       JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = VPF.NUMERO_MAQUINA
       JOIN SGTPRD.GRUPO_MAQUINAS GPR ON GPR.GRUPO = MAQ.GRUPO AND GPR.SETOR = MAQ.SETOR
       JOIN SGTPRD.UNIDADE_FABRIL UFA ON UFA.CODIGO_UNIDADE_FABRI = GPR.UNIDADE_FABRIL
      WHERE VPF.NUMERO_OB = OBE.NUMERO_OB
        AND UFA.EH_FACCAO = 'S'
      GROUP BY UFA.NOME_UNIDADE_FABRIL) AS DS_FACCAO
  , UPPER(EN_TO.DESCRICAO) AS DS_TP_ORDEM
  , OBE.DTINIPRODUCAO AS DT_EMISSAO
  , OBE.DTENCERORDEM AS DT_ENCERRAMENTO
  , OBE.DT_PROGRAMACAO AS DT_PROGRAMACAO
  , OBS_OB.OBS_OB
  , OBE.CODIGO_REDUZIDO AS CD_REDUZIDO
  , TRIM(IAC.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO
  , SUBSTR(IAC.CODIGO, 4, 5) AS CD_ARTIGO
  , SUBSTR(IAC.CODIGO, 13, 5) AS CD_COR
  , TRIM(COO.DESCRICAO) AS DS_COR
  , COO.TIPOCOR AS TP_COR
  , TRIM(TCO.DESCRICAO) AS DS_TP_COR
  , SUBSTR(IAC.CODIGO,1,3)||'.'||SUBSTR(IAC.CODIGO,4,5)||'.'||SUBSTR(IAC.CODIGO,9,1)||'.'||SUBSTR(IAC.CODIGO,10,3)||'.'||SUBSTR(IAC.CODIGO,13,5)||'.'||SUBSTR(IAC.CODIGO,18,6)||'.'||SUBSTR(IAC.CODIGO,24,2)||'.'||SUBSTR(IAC.CODIGO,26,2) AS CD_INDUSTRIAL
  , TRIM(IAC.DESCRICAO) AS DS_PRODUTO
  , DECODE(TRIM(NV9.CDNIVELGENERICO), 'T', 1, 'R', 2) AS CD_PROCESSO
  , DECODE(TRIM(NV9.CDNIVELGENERICO), 'T', 'TUBULAR', 'R', 'RAMADO') AS DS_PROCESSO
  , OBE.CODIGO_REDUZIDO_CRU AS CD_REDUZIDO_CRU
  , TRIM(ICR.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO_CRU
  , TRIM(ICR.DESCRICAO) AS DS_PRODUTO_CRU
  , CAST(NVL((SELECT MAX(FFL.PROCESSOTERCEIROS)
                FROM SGTPRD.OB_FASES OBF
                JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
               WHERE OBF.NUMERO_OB = OBE.NUMERO_OB), 0) AS NUMBER(10)) AS PROD_EXTERNA
  , (SELECT MAX(MPA.DATA_DOCUMENTO)
       FROM SGTPRD.BD_PRD_MOVPROD MPA
      WHERE MPA.CODIGO = 1
        AND MPA.OPERACAO = 1
        AND MPA.REDUZIDO_ITEM = IAC.CODIGO_REDUZIDO) AS DT_ULT_PROD_ITEM_ACA
  , (SELECT MAX(NFC.DTEMISSAO)
       FROM SGTPRD.NOTAFISCALITENS NFI
       JOIN SGTPRD.NOTAFISCALCAPA NFC ON NFC.ID = NFI.IDNOTAFISCALCAPA
      WHERE NFI.CDREDUZIDO = IAC.CODIGO_REDUZIDO
        AND NFC.STNOTAFATURAMENTO <> 2) AS DT_ULT_FAT_ITEM_ACA
  , CASE WHEN OBE.STATUS = 0 THEN NVL(OBE.DTENCERORDEM - OBE.DTINIPRODUCAO, 0)
         WHEN OBE.STATUS = 1 THEN NVL(SYSDATE - OBE.DTINIPRODUCAO, 0)
         ELSE 0 END AS LEAD_TIME
  , (SELECT TRIM(LPC.DECRICAO)
       FROM SGTPRD.LINHAPRODUTOCOMERCIA LPC
      WHERE LPC.LINHAPRODUTOCOMERCIA = IAC.LINHAPRODUTOCOMERCIA) AS DS_LINHA_COMERCIAL
  , (SELECT TRIM(TO_CHAR(ENG.LARGURA, '999G999G990D00') || ' m')
       FROM SGTPRD.ENG_PRODG_ACABADO ENG
      WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR) AS LARGURA_ACA
  , (SELECT ENG.GRAMATURA || ' g/m²'
       FROM SGTPRD.ENG_PRODG_ACABADO ENG
      WHERE ENG.REDUZIDO_AGRUPADOR = IAC.REDUZIDO_AGRUPADOR) AS GRAMATURA_ACA

    /* DADOS DAS FASES DA OB */
  , OBM.DATA_PRI_CONF AS DT_PRI_CONFIRMACAO
  , OBM.DATA_ULT_CONF AS DT_ULT_CONFIRMACAO
  , CASE WHEN OBM.DATA_ULT_CONF IS NULL THEN NULL ELSE SYSDATE - OBM.DATA_ULT_CONF END AS DIAS_PARADO
  , OBS.OBS_FASE_OB
  , TIN.NR_MAQUINA_TIN
  , TIN.CD_GR_TINGIMENTO
  , TIN.DT_HR_INICIO_TINGIMENTO
  , TIN.DT_HR_FINAL_TINGIMENTO
  , TIN.ST_FASE_TIN
  , TIN.ST_UP_FASE_TIN
  , (SELECT UPPER(SUP.DESCRICAO) FROM ENUM_STATUS_UP SUP WHERE SUP.STATUS = TIN.ST_UP_FASE_TIN) AS DS_ST_UP_FASE_TIN
  , TIN.DURACAO_MIN
  , TIN.RECEITA_PESADA AS ST_REC_PESADA
  , DECODE(TIN.RECEITA_PESADA, 0, 'NAO', 1, 'SIM') AS DS_REC_PESADA
  , TIN.EP
  , TIN.PE
  , TIN.CD_DESTINO_REC
  , TIN.DS_DESTINO_REC
  , NVL(REC.ST_BLOQ_REC, 2) AS ST_BLOQ_REC
  , NVL(REC.DS_BLOQ_REC, 'SEM RECEITA') AS DS_BLOQ_REC
  , FAT.NR_MAQ_FASE_ATUAL
  , FAT.ST_FASE_ATUAL
  , FAT.CD_FASE_ATUAL
  , FAT.DS_ST_FAS_ATUAL
  , FAT.DS_FASE_ATUAL
  , (SELECT F1.DESCRICAO_FASE_2 FROM SGTPRD.FASES_FLUXO F1 WHERE F1.CODIGO_FASE = FAT.CD_FASE_ATUAL) AS DS_FASE_BI

    /* DADOS DAS QUANTIDADES DA OB */
  , NVL(QT1.QT_CRU_PROG_OB, 0) AS QT_CRU_PROG_OB
  , NVL(QT1.QT_PC_CRU_PROG_OB, 0) AS QT_PC_CRU_PROG_OB
  , NVL(QT1.QT_CRU_ORIG_OB, 0) AS QT_CRU_ORIG_OB
  , NVL(QT1.QT_CRU_ATUAL_OB, 0) AS QT_CRU_ATUAL_OB
  , NVL(QT1.QT_PC_CRU_OB, 0) AS QT_PC_CRU_OB
  , (SELECT LISTAGG(LP, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY LP)
       FROM (SELECT DISTINCT TRIM(LTRIM(XX2.LOTE_PRODUTO, '0')) AS LP
               FROM SGTPRD.GERAPECAORIGEMOB XX1
               JOIN SGTPRD.GERAPECASPRODUTO XX2 ON XX2.IDPECASPRODUTO = XX1.IDPECASPRODUTO
              WHERE XX1.NUMERO_OB = OBE.NUMERO_OB)
    ) AS LOTE_CRU
  , (SELECT LISTAGG(LOTE_FIO, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY LOTE_FIO)
       FROM (SELECT DISTINCT TRIM(LTRIM(LOTE_FIO, '0')) AS LOTE_FIO
               FROM (SELECT DISTINCT GPO.NUMERO_OB, LFP.LOTE_FIO
                       FROM SGTPRD.GERAPECAORIGEMOB     GPO
                       JOIN SGTPRD.GERAPECASPRODUTO     GPP ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
                       JOIN SGTPRD.LOTES_FIO_PRODUTO    LFP ON LFP.LOTE_PRODUTO_CRU = GPP.LOTE_PRODUTO)
              WHERE NUMERO_OB = OBE.NUMERO_OB)
    ) AS LOTE_FIO
  , (SELECT LISTAGG(NUMERO_MAQUINA, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY NUMERO_MAQUINA)
       FROM (SELECT DISTINCT TRIM(LTRIM(NUMERO_MAQUINA, '0')) AS NUMERO_MAQUINA
               FROM (SELECT DISTINCT GPO.NUMERO_OB, OPM.NUMERO_MAQUINA
                       FROM SGTPRD.GERAPECAORIGEMOB     GPO
                       JOIN SGTPRD.GERAPECAORDEMMALHA   GOM ON GOM.IDPECASPRODUTO = GPO.IDPECASPRODUTO
                       JOIN SGTPRD.ORDEM_PRODUCAO_MALHA OPM ON OPM.NUMERO_ORDEM = GOM.NUMERO_ORDEM_MALHA)
              WHERE NUMERO_OB = OBE.NUMERO_OB)
    ) AS NR_TEAR
  , NVL(QT2.QT_ACA_OB, 0) AS QT_ACA_OB
  , NVL(QT2.EH_ACAB_REPROC, 0) AS EH_ACAB_REPROC
  , NVL(QT2.QT_PC_ACA_OB, 0) AS QT_PC_ACA_OB
  , NVL(CASE WHEN F150.STATUS <> 4 THEN NULL
             ELSE ROUND(100 - (QT2.QT_ACA_OB / QT1.QT_CRU_ORIG_OB * 100), 2) END, 0) AS PC_QUEBRA
  , NVL(QT3.QT_ACA_DISP_OB, 0) AS QT_ACA_DISP_OB
  , NVL(QT3.QT_PC_ACA_DISP_OB, 0) AS QT_PC_ACA_DISP_OB
  , NVL(QT3.QT_ACA_RES_OB, 0) AS QT_ACA_RES_OB
  , NVL(QT3.QT_PC_ACA_RES_OB, 0) AS QT_PC_ACA_RES_OB
  , NVL(RRR.QT_ROMANEIO, 0) AS QT_ACA_ROM_OB
  , NVL(RRR.QT_PC_ROMANEIO, 0) AS QT_PC_ACA_ROM_OB

    /* DADOS DEFEITO DA OB */
  , OBQ.SQ_OB_QUALIDADE
  , OBQ.CD_DESTINO_DEF
  , OBQ.DS_USO_ALTERNATIVO
  , OBQ.DS_GR_DEFEITO
  , OBQ.DS_TP_DEFEITO

    /* DADOS DO ROMANEIO */
  , DECODE(ROO.NR_ROMANEIO, NULL, 0, 1) AS ST_OB_COM_ROMANEIO
  , ROO.NR_ROMANEIO
  , ROO.ID_PESSOA_ROMANEIO
  , (SELECT TRIM(PSS.NOME) FROM SGTPRD.PESSOASFJ PSS WHERE PSS.IDPESSOAFJ = ROO.ID_PESSOA_ROMANEIO) AS DS_PESSOA_ROMANEIO
  , ROO.ST_ROMANEIO
  , (SELECT UPPER(ERR.DESCRICAO) FROM ENUM_STATUS_ROM_SAIDA ERR WHERE ERR.STATUS = ROO.ST_ROMANEIO) AS DS_ST_ROMANEIO
  , NVL(ROO.ST_ROM_EM_ABERTO, 1) AS ST_ROM_EM_ABERTO
  , NVL(ROO.QT_ROMANEIO, 0) AS QT_ROMANEIO
  , NVL(ROO.QT_PC_ROMANEIO, 0) AS QT_PC_ROMANEIO

    /* DADOS DO PEDIDO COMERCIAL */
  , NVL(NVL(ROO.NR_PEDIDO, XXX.NR_PEDIDO), OOO.NR_PEDIDO) AS NR_PEDIDO
  , PPP.TP_PEDIDO
  , PPP.DS_TP_PEDIDO
  , PPP.NR_PROGRAMACAO
  , PPP.NR_NFE_PEDIDO
  , PPP.DS_ITEM_PEDIDO_CLIENTE
  , NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO), OOO.SQ_ITEM_PEDIDO) AS SQ_ITEM_PEDIDO
  , PPP.ST_ITEM_PEDIDO
  , PPP.DS_ST_ITEM_PEDIDO
  , PPP.OBS_ITEM_PEDIDO
  , PPP.CD_REF_CLIENTE
  , NVL(PPP.ST_BLOQUEIO_FAT, 0) AS ST_BLOQUEIO_FAT
  , NVL(PPP.DS_ST_BLOQUEIO_FAT, 'NORMAL') AS DS_ST_BLOQUEIO_FAT
  , NVL(PPP.ST_PEDIDO_EM_ABERTO, (DECODE(OBE.STATUS, 0, NULL, 1))) AS ST_PEDIDO_EM_ABERTO
  , PPP.ID_PESSOA_COMPRADOR
  , PPP.NM_PESSOA_COMPRADOR
  , PPP.NM_PESSOA_COMPRADOR_F
  , PPP.ID_PESSOA_FATURA
  , PPP.NM_PESSOA_FATURA
  , PPP.ID_PESSOA_ENTREGA
  , PPP.NM_PESSOA_ENTREGA
  , NVL(PPP.ST_PESCOM_DIF_PESFAT, 0) AS ST_PESCOM_DIF_PESFAT
  , NVL(PPP.DS_ST_PESCOM_DIF_PESFAT, 'NAO') AS DS_ST_PESCOM_DIF_PESFAT
  , NVL(PPP.ST_TRANSF_LOJAS, 0) AS ST_TRANSF_LOJAS
  , NVL(PPP.DS_ST_TRANSF_LOJAS, 'NAO') AS DS_ST_TRANSF_LOJAS
  , PPP.DT_ENTREGA
  , NVL(GGG.QT_PC_ACA_RES_PEDIDO, 0) AS QT_PC_ACA_RES_PEDIDO
  , NVL(GGG.QT_ACA_RES_PED, 0) AS QT_ACA_RES_PED
  , PPP.PR_UNITARIO_PED
  , PPP.CD_TAB_PRECO

    /* DADOS FATURAMENTO */
  , DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, '0', 0, '1') AS ST_FATURAMENTO
  , DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, 'NAO', 0, 'SIM') AS DS_ST_FATURAMENTO
  , CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, '0', 0, '1') = 1 AND ROO.QT_ROMANEIO  = QT2.QT_ACA_OB THEN 2
         WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, '0', 0, '1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 1
         ELSE 0
    END AS ST_OB_VARIOS_FAT
  , CASE WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, '0', 0, '1') = 1 AND ROO.QT_ROMANEIO  = QT2.QT_ACA_OB THEN 'NAO'
         WHEN DECODE(NVL(ROO.ST_ROM_EM_ABERTO, 1), 1, '0', 0, '1') = 1 AND ROO.QT_ROMANEIO <> QT2.QT_ACA_OB THEN 'SIM'
         ELSE 'AGUARDANDO'
    END AS DS_ST_OB_VARIOS_FAT
  , NFF.NR_NF
  , NFF.DT_EMISSAO_NF
  , NVL(OB_FAT.OB_FAT_TOTAL, 0) AS OB_FAT_TOTAL

    /* DADOS OB BLOQUEIO */
  , BBB.CD_FASE_OB_BLOQ
  , BBB.DS_FASE_OB_BLOQ
  , BBB.ST_OB_BLOQUEIO
  , BBB.DS_ST_OB_BLOQUEIO
  , BBB.ST_LIB_INI_FASE
  , BBB.DS_ST_LIB_INI_FASE
  , BBB.OBS_OB_BLOQUEIO
  , BBB.DS_MOTIVO_BLOQUEIO
  , BBB.DT_HR_BLOQUEIO
  , BBB.NM_USU_BLOQUEIO
  , BBB.DT_H_LIBERACAO
  , BBB.NM_USU_LIBERACAO

    /* DADOS DEFEITO PEÇA CRUA */
  , DEFP.DS_GR_DEFEITO_CRU
  , DEFP.DS_TP_DEFEITO_CRU

    /* NF DAS PEÇAS CRUAS */
  , QTPNF.QT_PC_NF

FROM SGTPRD.OB OBE
JOIN SGTPRD.ITENS_ESTOQUE IAC ON IAC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
JOIN SGTPRD.ENGEITEMESTOCOR COR ON COR.CDREDUZIDO = IAC.CODIGO_REDUZIDO
JOIN SGTPRD.COR COO ON COO.CODIGO_COR = COR.CDCOR
JOIN SGTPRD.COML_TIPOSCOR TCO ON TCO.TIPOCOR = COO.TIPOCOR
JOIN SGTPRD.ENGEITEMESTONIVELGE9 NV9 ON NV9.CDREDUZIDO = IAC.CODIGO_REDUZIDO
JOIN SGTPRD.ITENS_ESTOQUE ICR ON ICR.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO_CRU

LEFT JOIN ENUM_STATUS_OB EN_SOB ON EN_SOB.STATUS = OBE.STATUS
LEFT JOIN ENUM_TIPO_ORDEM EN_TO ON EN_TO.TIPO_ORDEM = OBE.TIPO_ORDEM
LEFT JOIN LATERAL (
    SELECT MAX(F.STATUS) AS ST_TERCEIROS
         , MAX(DECODE(F.STATUS, 0, 'PENDENTE', 3, 'EM PROCESSO', 4, 'CONCLUIDO')) AS DS_ST_TERCEIROS
      FROM SGTPRD.OB_FASES F
      JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = F.CODIGO_FASE
     WHERE F.NUMERO_OB = OBE.NUMERO_OB
       AND FF.PROCESSOTERCEIROS = '1'
       AND F.SEQUENCIA = (
           SELECT MAX(L.SEQUENCIA)
             FROM SGTPRD.OB_FASES L
            WHERE L.NUMERO_OB = F.NUMERO_OB
              AND L.CODIGO_FASE = F.CODIGO_FASE
       )
) TERC ON 1=1

LEFT JOIN LATERAL (
    SELECT LISTAGG(TRIM(UPPER(D.TEXTO)), '' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY D.ROWID) AS OBS_OB
      FROM SGTPRD.OBSERVACAO D
     WHERE D.CODIGO = OBE.CODIGO_OBSERVACAO
) OBS_OB ON 1=1

LEFT JOIN SGTPRD.VW_BNF_OBMONTADA OBM ON OBM.NUMERO_OB = OBE.NUMERO_OB

LEFT JOIN LATERAL (
    SELECT LISTAGG(X.OBSERVACAO, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY X.OBSERVACAO) AS OBS_FASE_OB
      FROM (
            SELECT DISTINCT 'FASE ' || E.CODIGO_FASE || ' -> ' || UPPER(TRIM(D.TEXTO)) AS OBSERVACAO
              FROM SGTPRD.OB_FASES E
              JOIN SGTPRD.OBSERVACAO D ON D.CODIGO = E.CODIGO_OBSERVACAO
             WHERE E.NUMERO_OB = OBE.NUMERO_OB
           ) X
) OBS ON 1=1

LEFT JOIN LATERAL (
    SELECT H.STATUS
      FROM SGTPRD.OB_FASES H
     WHERE H.NUMERO_OB = OBE.NUMERO_OB
       AND H.CODIGO_FASE = 150
     ORDER BY H.SEQUENCIA DESC
     FETCH FIRST 1 ROWS ONLY
) F150 ON 1=1

LEFT JOIN LATERAL (
    SELECT OBFT.CODIGO_GRUPO AS CD_GR_TINGIMENTO
         , LTRIM(OBFT.NUMERO_MAQUINA, 0) AS NR_MAQUINA_TIN
         , DATE '1996-01-01' + (MOV.TEMPO_INICIAL/1440) AS DT_HR_INICIO_TINGIMENTO
         , DATE '1996-01-01' + (MOV.TEMPO_FINAL/1440)   AS DT_HR_FINAL_TINGIMENTO
         , MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL AS DURACAO_MIN
         , (MOV.TEMPO_FINAL - MOV.TEMPO_INICIAL)/60/24 AS DURACAO_DIAS
         , OBFT.STATUS AS ST_FASE_TIN
         , DECODE(OBFT.STATUS, 1,
             (SELECT CASE WHEN NVL(SUM(MRE.QUANTIDADEPESADA), 0) = 0 THEN 0 ELSE 1 END
                FROM SGTPRD.MOVTO_RECEITA MRE
               WHERE MRE.NUMEROORDEM = OBFT.NUMERO_OB AND MRE.SEQUENCIAFASEOB = OBFT.SEQUENCIA),
             2,
             (SELECT CASE WHEN NVL(SUM(MRE.QUANTIDADEPESADA), 0) = 0 THEN 0 ELSE 1 END
                FROM SGTPRD.MOVTO_RECEITA MRE
               WHERE MRE.NUMEROORDEM = OBFT.NUMERO_OB AND MRE.SEQUENCIAFASEOB = OBFT.SEQUENCIA),
             NULL) AS RECEITA_PESADA
         , OBFT.ESPECIFICACAO_PRODUT AS EP
         , OBFT.PROCESSO_ESPECIFICO  AS PE
         , OBFT.DESTINO_RECEITA AS CD_DESTINO_REC
         , (SELECT TRIM(DDD.DESCRICAO) FROM SGTPRD.DESTINO DDD WHERE DDD.DESTINO = OBFT.DESTINO_RECEITA) AS DS_DESTINO_REC
         , MOV.STATUS AS ST_UP_FASE_TIN
      FROM SGTPRD.OB_FASES OBFT
      JOIN SGTPRD.MOVIMENTO_MAQUINA MOV
        ON MOV.NUMERO_ORDEM = DECODE(OBFT.CODIGO_GRUPO, 0, OBFT.NUMERO_OB, OBFT.CODIGO_GRUPO)
       AND MOV.SEQUENCIA    = DECODE(OBFT.CODIGO_GRUPO, 0, OBFT.SEQUENCIA, 0)
     WHERE OBFT.NUMERO_OB = OBE.NUMERO_OB
       AND OBFT.CODIGO_FASE = 40
     ORDER BY OBFT.SEQUENCIA DESC
     FETCH FIRST 1 ROWS ONLY
) TIN ON 1=1

LEFT JOIN (
    SELECT ITEX.CODIGO_REDUZIDO
         , LRB.BLOQUEIO_RECEITA AS ST_BLOQ_REC
         , DECODE(LRB.BLOQUEIO_RECEITA, 0, 'BLOQUEADA', 1, 'LIBERADA') AS DS_BLOQ_REC
      FROM SGTPRD.CADASTRO_RECEITAS    CRE
      JOIN SGTPRD.LIGA_CADREC_ITEMREC  LCR ON LCR.CODIGO_REDUZIDO_RECE = CRE.CODIGO_REDUZIDO_RECE
      JOIN SGTPRD.LABRECEITA_BLOQUEADA LRB ON LRB.ID_LABRECEITA_BLOQ   = LCR.ID_LABRECEITA_BLOQ
      JOIN SGTPRD.ITENS_ESTOQUE        ITEX ON ITEX.TIPO_ITEM = 10 AND CRE.ESPECIFICACAO_PRODUT = ITEX.ESPECIFICACAOPRODUTO
      JOIN SGTPRD.ENGEITEMESTOCOR      EGC  ON EGC.CDREDUZIDO = ITEX.CODIGO_REDUZIDO AND TRIM(CRE.CODCOR) = TRIM(EGC.CDCOR)
     WHERE CRE.PROCESSOINDUSTRIAL   = 401
       AND CRE.PROCESSO_ATIVO_PRODU = 1
) REC ON REC.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO

LEFT JOIN LATERAL (
    SELECT LTRIM(OBF.NUMERO_MAQUINA, 0) AS NR_MAQ_FASE_ATUAL
         , OBF.STATUS AS ST_FASE_ATUAL
         , (SELECT UPPER(SS.DESCRICAO) FROM ENUM_STATUS_OB_FASES SS WHERE SS.STATUS = OBF.STATUS) AS DS_ST_FAS_ATUAL
         , OBF.CODIGO_FASE AS CD_FASE_ATUAL
         , RPAD(FFL.DESCRICAO_FASE, 30) AS DS_FASE_ATUAL
      FROM SGTPRD.OB_FASES OBF
      JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
     WHERE OBF.NUMERO_OB = OBE.NUMERO_OB
       AND OBE.STATUS <> 0
       AND OBF.SEQUENCIA = SGTPRD.PKGBENF0001.FNC_RETORNA_SEQUENCIA_OB(OBE.NUMERO_OB, 0)
       AND OBF.SEQUENCIA <> 0
) FAT ON 1=1

LEFT JOIN LATERAL (
    SELECT O3.KILOS_PROGRAMADOS AS QT_CRU_PROG_OB
         , DECODE(O3.TOTAL_PECAS_CONFIRM, 0, (ROUND(O3.KILOS_PROGRAMADOS / (SELECT MAX(PDD.PESO_PADRAO) FROM PESO_PADRAO PDD WHERE PDD.REDUZIDO = O3.CODPRO_REDUZIDO), 0)), O3.TOTAL_PECAS_CONFIRM) AS QT_PC_CRU_PROG_OB
         , (SELECT SUM(NVL(O4.QTPESOLIQUORIG, 0))
              FROM SGTPRD.GERAPECAORIGEMOB O1
              LEFT JOIN SGTPRD.GERAPECACOMPLPECA O4 ON O4.IDPECASPRODUTO = O1.IDPECASPRODUTO
             WHERE O1.NUMERO_OB = OBE.NUMERO_OB) AS QT_CRU_ORIG_OB
         , (SELECT SUM(NVL(O2.QTLIQUIDA, 0))
              FROM SGTPRD.GERAPECAORIGEMOB O1
              LEFT JOIN SGTPRD.GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
             WHERE O1.NUMERO_OB = OBE.NUMERO_OB) AS QT_CRU_ATUAL_OB
         , (SELECT COUNT(O2.IDPECASPRODUTO)
              FROM SGTPRD.GERAPECAORIGEMOB O1
              LEFT JOIN SGTPRD.GERAPECASPRODUTO O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
             WHERE O1.NUMERO_OB = OBE.NUMERO_OB) AS QT_PC_CRU_OB
      FROM SGTPRD.OB_PRODUTO O3
     WHERE O3.NUMERO_OB = OBE.NUMERO_OB
     FETCH FIRST 1 ROWS ONLY
) QT1 ON 1=1

LEFT JOIN LATERAL (
    SELECT SUM(O2.QTLIQUIDA) AS QT_ACA_OB
         , COUNT(O2.IDPECASPRODUTO) AS QT_PC_ACA_OB
         , CASE WHEN MAX(O2.CODIGO_DEPOSITO) = 100 THEN 1 ELSE 0 END AS EH_ACAB_REPROC
      FROM SGTPRD.GERAPECADESTINOOB O1
      JOIN SGTPRD.GERAPECASPRODUTO  O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
     WHERE O1.NUMERO_OB = OBE.NUMERO_OB
) QT2 ON 1=1

LEFT JOIN LATERAL (
    SELECT SUM(CASE WHEN O2.STPECAPRODUTO = 0 THEN O2.QTLIQUIDA ELSE 0 END) AS QT_ACA_DISP_OB
         , SUM(CASE WHEN O2.STPECAPRODUTO = 0 THEN 1 ELSE 0 END) AS QT_PC_ACA_DISP_OB
         , SUM(CASE WHEN O2.STPECAPRODUTO = 14 THEN O2.QTLIQUIDA ELSE 0 END) AS QT_ACA_RES_OB
         , SUM(CASE WHEN O2.STPECAPRODUTO = 14 THEN 1 ELSE 0 END) AS QT_PC_ACA_RES_OB
      FROM SGTPRD.GERAPECADESTINOOB O1
      JOIN SGTPRD.GERAPECASPRODUTO  O2 ON O2.IDPECASPRODUTO = O1.IDPECASPRODUTO
     WHERE O1.NUMERO_OB = OBE.NUMERO_OB
       AND O2.STPECAPRODUTO IN (0, 14)
) QT3 ON 1=1

LEFT JOIN LATERAL (
    SELECT SUM(RRRR.QT_ROMANEIO) AS QT_ROMANEIO, SUM(RRRR.QT_PC_ROMANEIO) AS QT_PC_ROMANEIO
      FROM (
            SELECT SUM(PRS.PESO_PECA) AS QT_ROMANEIO
                 , COUNT(PRS.IDPECASPRODUTO) AS QT_PC_ROMANEIO
              FROM SGTPRD.GERAPECADESTINOOB DOB
              JOIN SGTPRD.PECAS_ROMANEIO_SAIDA PRS ON PRS.IDPECASPRODUTO = DOB.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO             ROM ON ROM.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID
              JOIN SGTPRD.PRODUTO_ROMANEIO     PR1 ON PR1.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO
             WHERE DOB.NUMERO_OB = OBE.NUMERO_OB
               AND ROM.STATUS IN (0, 1, 3, 8)

            UNION ALL

            SELECT SUM(GGP.QTLIQUIDA) AS QT_ROMANEIO
                 , COUNT(GRR.IDPECASPRODUTO) AS QT_PC_ROMANEIO
              FROM SGTPRD.GERAPECADESTINOOB DBB
              JOIN SGTPRD.GERAPECAROMSAIDA  GRR ON GRR.IDPECASPRODUTO = DBB.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO          RMM ON RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
              JOIN SGTPRD.GERAPECASPRODUTO  GGP ON GGP.IDPECASPRODUTO = GRR.IDPECASPRODUTO
               WHERE DBB.NUMERO_OB = OBE.NUMERO_OB
               AND NOT EXISTS (SELECT 1 FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS WHERE PRS.IDPECASPRODUTO = GRR.IDPECASPRODUTO)
               AND RMM.STATUS IN (0, 1, 3, 8)
           ) RRRR
) RRR ON 1=1

LEFT JOIN LATERAL (
    SELECT (SELECT LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v) FROM (
             SELECT DISTINCT TO_CHAR(OBQ1D.SEQUENCIA_OB_QUALIDA) AS v FROM SGTPRD.OB_QUALIDADE OBQ1D
              WHERE OBQ1D.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2D.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2D WHERE OBQ2D.NUMERO_OB = OBQ1D.NUMERO_OB AND OBQ2D.SEQUENCIA_FASE <> 0)
                AND OBQ1D.NUMERO_OB = OBE.NUMERO_OB)) AS SQ_OB_QUALIDADE
         , (SELECT LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v) FROM (
             SELECT DISTINCT TO_CHAR(OBQ1E.DESTINO) AS v FROM SGTPRD.OB_QUALIDADE OBQ1E
              WHERE OBQ1E.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2E.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2E WHERE OBQ2E.NUMERO_OB = OBQ1E.NUMERO_OB AND OBQ2E.SEQUENCIA_FASE <> 0)
                AND OBQ1E.NUMERO_OB = OBE.NUMERO_OB)) AS CD_DESTINO_DEF
         , (SELECT LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v) FROM (
             SELECT DISTINCT TRIM(OBQ1F.USO_ALTERNATIVO) AS v FROM SGTPRD.OB_QUALIDADE OBQ1F
              WHERE OBQ1F.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2F.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2F WHERE OBQ2F.NUMERO_OB = OBQ1F.NUMERO_OB AND OBQ2F.SEQUENCIA_FASE <> 0)
                AND OBQ1F.NUMERO_OB = OBE.NUMERO_OB)) AS DS_USO_ALTERNATIVO
         , (SELECT LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v) FROM (
             SELECT DISTINCT TO_CHAR(OBQ1G.GRUPO_DEFEITO) AS v FROM SGTPRD.OB_QUALIDADE OBQ1G
              WHERE OBQ1G.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2G.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2G WHERE OBQ2G.NUMERO_OB = OBQ1G.NUMERO_OB AND OBQ2G.SEQUENCIA_FASE <> 0)
                AND OBQ1G.NUMERO_OB = OBE.NUMERO_OB)) AS GR_DEFEITO
         , (SELECT LISTAGG(v, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY v) FROM (
             SELECT DISTINCT TO_CHAR(OBQ1H.TIPO_DEFEITO) AS v FROM SGTPRD.OB_QUALIDADE OBQ1H
              WHERE OBQ1H.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2H.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2H WHERE OBQ2H.NUMERO_OB = OBQ1H.NUMERO_OB AND OBQ2H.SEQUENCIA_FASE <> 0)
                AND OBQ1H.NUMERO_OB = OBE.NUMERO_OB)) AS TP_DEFEITO
         , (SELECT LISTAGG(val, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY val) FROM (
             SELECT DISTINCT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) AS val
               FROM SGTPRD.GRUPO_DEFEITO_QUALID GDQ
              WHERE GDQ.CODIGO_GRUPO IN (SELECT DISTINCT OBQ1B.GRUPO_DEFEITO FROM SGTPRD.OB_QUALIDADE OBQ1B
                                           WHERE OBQ1B.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2B.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2B WHERE OBQ2B.NUMERO_OB = OBQ1B.NUMERO_OB AND OBQ2B.SEQUENCIA_FASE <> 0)
                                             AND OBQ1B.NUMERO_OB = OBE.NUMERO_OB)
            )) AS DS_GR_DEFEITO
         , (SELECT LISTAGG(val, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY val) FROM (
             SELECT DISTINCT TDQ.CODIGO_TIPO || ' - ' || TRIM(TDQ.DESCRICAO_TIPO) AS val
               FROM SGTPRD.TIPO_DEFEITO_QUALIDA TDQ
              WHERE (TDQ.CODIGO_GRUPO, TDQ.CODIGO_TIPO) IN (
                      SELECT DISTINCT OBQ1C.GRUPO_DEFEITO, OBQ1C.TIPO_DEFEITO FROM SGTPRD.OB_QUALIDADE OBQ1C
                       WHERE OBQ1C.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2C.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2C WHERE OBQ2C.NUMERO_OB = OBQ1C.NUMERO_OB AND OBQ2C.SEQUENCIA_FASE <> 0)
                         AND OBQ1C.NUMERO_OB = OBE.NUMERO_OB)
            )) AS DS_TP_DEFEITO
      FROM SGTPRD.OB_QUALIDADE OBQ1
     WHERE OBQ1.NUMERO_OB = OBE.NUMERO_OB
       AND OBQ1.SEQUENCIA_OB_QUALIDA = (SELECT MAX(OBQ2.SEQUENCIA_OB_QUALIDA) FROM SGTPRD.OB_QUALIDADE OBQ2 WHERE OBQ2.NUMERO_OB = OBQ1.NUMERO_OB AND OBQ2.SEQUENCIA_FASE <> 0)
     FETCH FIRST 1 ROWS ONLY
) OBQ ON 1=1

LEFT JOIN LATERAL (
    SELECT PA.NR_ROMANEIO, PA.ST_ROMANEIO, PA.ST_ROM_EM_ABERTO,
           PA.NR_PEDIDO, PA.SQ_ITEM_PEDIDO, PA.ID_PESSOA_ROMANEIO,
           PA.QT_ROMANEIO, PA.QT_PC_ROMANEIO
      FROM (
            SELECT PRS.NUMERO_ROMANEIO_SAID AS NR_ROMANEIO, ROM.STATUS AS ST_ROMANEIO,
                   DECODE(ROM.STATUS, 4, 0, 5, 0, 6, 0, 1) AS ST_ROM_EM_ABERTO,
                   DECODE(PR1.NUMERO_PEDIDO, 0, NULL, PR1.NUMERO_PEDIDO) AS NR_PEDIDO,
                   DECODE(PR1.ITEM_PEDIDO, 0, NULL, PR1.ITEM_PEDIDO) AS SQ_ITEM_PEDIDO,
                   ROM.IDPESSOAFJ AS ID_PESSOA_ROMANEIO,
                   SUM(PRS.PESO_PECA) AS QT_ROMANEIO, COUNT(PRS.IDPECASPRODUTO) AS QT_PC_ROMANEIO
              FROM SGTPRD.GERAPECADESTINOOB DOB
              JOIN SGTPRD.PECAS_ROMANEIO_SAIDA PRS ON PRS.IDPECASPRODUTO = DOB.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID
              JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO AND PR1.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO
             WHERE DOB.NUMERO_OB = OBE.NUMERO_OB
               AND NOT EXISTS (SELECT 1 FROM SGTPRD.GERAPECASPRODUTO GPPX WHERE GPPX.IDPECASPRODUTO = PRS.IDPECASPRODUTO AND GPPX.STPECAPRODUTO = 13)
             GROUP BY PRS.NUMERO_ROMANEIO_SAID, ROM.STATUS, PR1.NUMERO_PEDIDO, PR1.ITEM_PEDIDO, ROM.IDPESSOAFJ

            UNION ALL

            SELECT GRR.NUMERO_ROMANEIO_SAID AS NR_ROMANEIO, RMM.STATUS AS ST_ROMANEIO,
                   DECODE(RMM.STATUS, 4, 0, 5, 0, 6, 0, 1) AS ST_ROM_EM_ABERTO,
                   DECODE(PR2.NUMERO_PEDIDO, 0, NULL, PR2.NUMERO_PEDIDO) AS NR_PEDIDO,
                   DECODE(PR2.ITEM_PEDIDO, 0, NULL, PR2.ITEM_PEDIDO) AS SQ_ITEM_PEDIDO,
                   RMM.IDPESSOAFJ AS ID_PESSOA_ROMANEIO,
                   SUM(GGP.QTLIQUIDA) AS QT_ROMANEIO, COUNT(GRR.IDPECASPRODUTO) AS QT_PC_ROMANEIO
              FROM SGTPRD.GERAPECADESTINOOB DBB
              JOIN SGTPRD.GERAPECAROMSAIDA GRR ON GRR.IDPECASPRODUTO = DBB.IDPECASPRODUTO
              JOIN SGTPRD.GERAPECASPRODUTO GGP ON GGP.IDPECASPRODUTO = GRR.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO RMM ON RMM.NUMERO_ROMANEIO = GRR.NUMERO_ROMANEIO_SAID
              JOIN SGTPRD.PRODUTO_ROMANEIO PR2 ON PR2.NUMERO_ROMANEIO = RMM.NUMERO_ROMANEIO AND PR2.IDPRODUTO_ROMANEIO = GRR.IDPRODUTO_ROMANEIO
             WHERE DBB.NUMERO_OB = OBE.NUMERO_OB
               AND NOT EXISTS (SELECT 1 FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS WHERE PRS.IDPECASPRODUTO = GRR.IDPECASPRODUTO)
             GROUP BY GRR.NUMERO_ROMANEIO_SAID, RMM.STATUS, PR2.NUMERO_PEDIDO, PR2.ITEM_PEDIDO, RMM.IDPESSOAFJ
           ) PA
) ROO ON 1=1

LEFT JOIN LATERAL (
    SELECT IPG.PEDIDO AS NR_PEDIDO
         , IPG.ITEMPEDIDO AS SQ_ITEM_PEDIDO
         , OFP.NUMEROOF AS NR_OF
      FROM SGTPRD.PEDPRODUCAOOB PPOB
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
     WHERE PPOB.NUMEROOB = OBE.NUMERO_OB
       AND OFP.QUANTIDADE_ATUAL <> 0
     FETCH FIRST 1 ROWS ONLY
) OOO ON 1=1

LEFT JOIN LATERAL (
    SELECT G2.NUMERO_PEDIDO_COMERC AS NR_PEDIDO
         , G2.SEQUENCIA_PRODUTO_PE AS SQ_ITEM_PEDIDO
      FROM SGTPRD.GERAPECADESTINOOB G1
      JOIN SGTPRD.GERAPECAPEDCOMERCIAL G2 ON G2.IDPECASPRODUTO = G1.IDPECASPRODUTO
     WHERE G1.NUMERO_OB = OBE.NUMERO_OB
     GROUP BY G2.NUMERO_PEDIDO_COMERC, G2.SEQUENCIA_PRODUTO_PE
     FETCH FIRST 1 ROWS ONLY
) XXX ON 1=1

LEFT JOIN LATERAL (
    SELECT PED.CD_SUBTIPOPED AS TP_PEDIDO
         , (SELECT TRIM(STT.DS_SUBTIPOPED) FROM SGTPRD.COML_SUBTIPOPED STT WHERE STT.CD_SUBTIPOPED = PED.CD_SUBTIPOPED) AS DS_TP_PEDIDO
         , IPC.PEDIDO AS NR_PEDIDO
         , TRIM(PED.PEDIDOCLIENTE) AS NR_PROGRAMACAO
         , TRIM(PED.NUMERO_NOTA_FISCAL) AS NR_NFE_PEDIDO
         , TRIM(IPC.ITEMPEDIDOCLIENTE) AS DS_ITEM_PEDIDO_CLIENTE
         , TRIM(IPC.OBS) AS OBS_ITEM_PEDIDO
         , TRIM(IPC.CD_DESENHO_CLIENTE) AS CD_REF_CLIENTE
         , PED.BLOQUEIOFATURAMENTO AS ST_BLOQUEIO_FAT
         , DECODE(PED.BLOQUEIOFATURAMENTO, 0, 'NORMAL', 1, 'BLOQUEADO', 2, 'LIBERADO') AS DS_ST_BLOQUEIO_FAT
         , IPC.ITEMPEDIDO AS SQ_ITEM_PEDIDO
         , IPC.SITUACAOITEM AS ST_ITEM_PEDIDO
         , (SELECT UPPER(SII.DESCRICAO) FROM SGTPRD.COML_SITUACOESITEM SII WHERE SII.SITUACAOITEM = IPC.SITUACAOITEM) AS DS_ST_ITEM_PEDIDO
         , CASE WHEN IPC.SITUACAOITEM IN (6, 10, 12, 13, 14, 18) THEN 0 ELSE 1 END AS ST_PEDIDO_EM_ABERTO
         , PED.IDFILIALRESPONSAVEL AS ID_PESSOA_COMPRADOR
         , TRIM(PRE.NOME) AS NM_PESSOA_COMPRADOR
         , TRIM(PRE.NOMEFANTASIA) AS NM_PESSOA_COMPRADOR_F
         , PED.IDFILIALCOBRANCA AS ID_PESSOA_FATURA
         , TRIM(PFA.NOME) AS NM_PESSOA_FATURA
         , PED.IDFILIALENTREGA AS ID_PESSOA_ENTREGA
         , TRIM(PEN.NOME) AS NM_PESSOA_ENTREGA
         , IPC.PRECOUNITARIO AS PR_UNITARIO_PED
         , IPC.PRECODIGITADO AS PR_DIGITADO_PED
         , PED.TABELAPRECO AS CD_TAB_PRECO
         , TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD') AS DT_ENTREGA
         , CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 1 ELSE 0 END AS ST_PESCOM_DIF_PESFAT
         , CASE WHEN PED.IDFILIALRESPONSAVEL <> PED.IDFILIALCOBRANCA THEN 'SIM' ELSE 'NAO' END AS DS_ST_PESCOM_DIF_PESFAT
         , CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM SGTPRD.PESSOASFJ FIL WHERE FIL.EMPRESA = '02944599  ' AND FIL.IDPESSOAFJ NOT IN (1, 2, 3)) THEN 1 ELSE 0 END AS ST_TRANSF_LOJAS
         , CASE WHEN PED.IDFILIALRESPONSAVEL IN (SELECT FIL.IDPESSOAFJ FROM SGTPRD.PESSOASFJ FIL WHERE FIL.EMPRESA = '02944599  ' AND FIL.IDPESSOAFJ NOT IN (1, 2, 3)) THEN 'SIM' ELSE 'NAO' END AS DS_ST_TRANSF_LOJAS
      FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
      JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
      JOIN SGTPRD.PESSOASFJ PRE ON PRE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
      JOIN SGTPRD.PESSOASFJ PFA ON PFA.IDPESSOAFJ = PED.IDFILIALCOBRANCA
      JOIN SGTPRD.PESSOASFJ PEN ON PEN.IDPESSOAFJ = PED.IDFILIALENTREGA
     WHERE IPC.PEDIDO = NVL(NVL(ROO.NR_PEDIDO, XXX.NR_PEDIDO), OOO.NR_PEDIDO)
       AND IPC.ITEMPEDIDO = NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO), OOO.SQ_ITEM_PEDIDO)
     FETCH FIRST 1 ROWS ONLY
) PPP ON 1=1

LEFT JOIN LATERAL (
    SELECT SUM(G6.QTLIQUIDA) AS QT_ACA_RES_PED
         , COUNT(G6.IDPECASPRODUTO) AS QT_PC_ACA_RES_PEDIDO
      FROM SGTPRD.GERAPECADESTINOOB    G7
      JOIN SGTPRD.GERAPECAPEDCOMERCIAL G5 ON G5.IDPECASPRODUTO = G7.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECASPRODUTO     G6 ON G6.IDPECASPRODUTO = G5.IDPECASPRODUTO
     WHERE G7.NUMERO_OB = OBE.NUMERO_OB
       AND G5.NUMERO_PEDIDO_COMERC = NVL(NVL(ROO.NR_PEDIDO, XXX.NR_PEDIDO), OOO.NR_PEDIDO)
       AND G5.SEQUENCIA_PRODUTO_PE = NVL(NVL(ROO.SQ_ITEM_PEDIDO, XXX.SQ_ITEM_PEDIDO), OOO.SQ_ITEM_PEDIDO)
) GGG ON 1=1

LEFT JOIN LATERAL (
    SELECT NFC.NRNOTA AS NR_NF
         , NFC.DTEMISSAO AS DT_EMISSAO_NF
      FROM SGTPRD.GERAREQUESTOITEMNOTA   GQI
      JOIN SGTPRD.PRODUTO_ROMANEIO       PRO ON PRO.IDPRODUTO_ROMANEIO = GQI.IDPRODUTO_ROMANEIO
      JOIN SGTPRD.NOTAFISCALITENS        NFI ON NFI.ID = GQI.IDNOTAFISCALITENS
      JOIN SGTPRD.NOTAFISCALCAPA         NFC ON NFC.ID = NFI.IDNOTAFISCALCAPA
     WHERE ROO.NR_ROMANEIO IS NOT NULL
       AND PRO.NUMERO_ROMANEIO = ROO.NR_ROMANEIO
       AND NFC.STNOTAFATURAMENTO <> 2
       AND NFC.NRNOTA IS NOT NULL
       AND NFC.IDFILIAL = 1
     ORDER BY NFC.DTEMISSAO DESC, NFC.NRNOTA DESC
     FETCH FIRST 1 ROWS ONLY
) NFF ON 1=1

LEFT JOIN LATERAL (
    SELECT T.FASE AS CD_FASE_OB_BLOQ
         , DECODE(T.FASE, 0, 'TODAS AS FASES', (SELECT TRIM(FFL.DESCRICAO_FASE) FROM SGTPRD.FASES_FLUXO FFL WHERE FFL.CODIGO_FASE = T.FASE)) AS DS_FASE_OB_BLOQ
         , CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 1 ELSE 0 END AS ST_OB_BLOQUEIO
         , CASE WHEN T.LIBERA_INICIO_PRODUC = 0 AND T.LIBERADO = 0 THEN 'SIM' ELSE 'NAO' END AS DS_ST_OB_BLOQUEIO
         , T.LIBERA_INICIO_PRODUC AS ST_LIB_INI_FASE
         , DECODE(T.LIBERA_INICIO_PRODUC, 0, 'NAO', 'SIM') AS DS_ST_LIB_INI_FASE
         , TRIM(T.OBSERVACAO) AS OBS_OB_BLOQUEIO
         , CAST(NULL AS VARCHAR2(100)) AS DS_MOTIVO_BLOQUEIO
         , T.DATA_BLOQUEIO AS DT_HR_BLOQUEIO
         , (SELECT TRIM(VSU.NOME) FROM SIS_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) AS NM_USU_BLOQUEIO
         , DECODE(T.DATA_DESBLOQUEIO, TO_DATE('30/01/1900', 'DD/MM/YYYY'), NULL, TO_CHAR(T.DATA_DESBLOQUEIO, 'DD/MM/YYYY HH24:MI:SS')) AS DT_H_LIBERACAO
         , (SELECT TRIM(VSU.NOME) FROM SIS_USUARIO VSU WHERE VSU.CODREDUSUARIO = T.CODREDUSU_BLOQUEIO) AS NM_USU_LIBERACAO
      FROM SGTPRD.OB_BLOQUEIO T
     WHERE T.NUMERO_OB = OBE.NUMERO_OB
       AND OBE.STATUS <> 0
) BBB ON 1=1

LEFT JOIN LATERAL (
    SELECT 1 AS OB_FAT_TOTAL
      FROM (SELECT COUNT(DE1.IDPECASPRODUTO) AS QT_PC_OB
              FROM SGTPRD.GERAPECADESTINOOB DE1
             WHERE DE1.NUMERO_OB = OBE.NUMERO_OB) A
      JOIN (SELECT COUNT(DE2.IDPECASPRODUTO) AS QT_PC_ROM_FAT
              FROM SGTPRD.GERAPECADESTINOOB DE4
              JOIN SGTPRD.PECAS_ROMANEIO_SAIDA DE2 ON DE2.IDPECASPRODUTO = DE4.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO DE3 ON DE3.NUMERO_ROMANEIO = DE2.NUMERO_ROMANEIO_SAID
             WHERE DE3.STATUS IN (4, 6)
               AND DE4.NUMERO_OB = OBE.NUMERO_OB) D ON D.QT_PC_ROM_FAT = A.QT_PC_OB AND A.QT_PC_OB > 0
) OB_FAT ON 1=1

LEFT JOIN LATERAL (
    SELECT (SELECT LISTAGG(val, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY val) FROM (
             SELECT DISTINCT GDQ.CODIGO_GRUPO || ' - ' || TRIM(GDQ.DESCRICAO_GRUPO) AS val
               FROM SGTPRD.GERAPECAORIGEMOB OBQ9
               JOIN SGTPRD.GERAPECAREVISAO GPR9 ON GPR9.IDPECASPRODUTO = OBQ9.IDPECASPRODUTO
               JOIN SGTPRD.GRUPO_DEFEITO_QUALID GDQ ON GDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO
              WHERE OBQ9.NUMERO_OB = OBE.NUMERO_OB
                AND GPR9.GRUPO_DEFEITO IS NOT NULL
           )) AS DS_GR_DEFEITO_CRU,
           (SELECT LISTAGG(val, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY val) FROM (
             SELECT DISTINCT TDQ.CODIGO_TIPO || ' - ' || TRIM(TDQ.DESCRICAO_TIPO) AS val
               FROM SGTPRD.GERAPECAORIGEMOB OBQ9
               JOIN SGTPRD.GERAPECAREVISAO GPR9 ON GPR9.IDPECASPRODUTO = OBQ9.IDPECASPRODUTO
               JOIN SGTPRD.TIPO_DEFEITO_QUALIDA TDQ ON TDQ.CODIGO_GRUPO = GPR9.GRUPO_DEFEITO AND TDQ.CODIGO_TIPO = GPR9.TIPO_DEFEITO
              WHERE OBQ9.NUMERO_OB = OBE.NUMERO_OB
                AND (GPR9.GRUPO_DEFEITO IS NOT NULL OR GPR9.TIPO_DEFEITO IS NOT NULL)
           )) AS DS_TP_DEFEITO_CRU
      FROM DUAL
) DEFP ON 1=1

LEFT JOIN LATERAL (
    SELECT LISTAGG(POC.QT_PECA || ' - ' || POC.NR_NF, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY POC.QT_PECA || ' - ' || POC.NR_NF) AS QT_PC_NF
      FROM (
            SELECT BC1.NUMERO_NOTA || ' - ' || TRIM(PE1.NOMEFANTASIA) AS NR_NF
                 , COUNT(AB1.IDPECASPRODUTO) AS QT_PECA
              FROM SGTPRD.GERAPECAORIGEMOB    AB1
              JOIN SGTPRD.GERAPECANOTAENTRADA BC1 ON BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
              JOIN SGTPRD.PESSOASFJ           PE1 ON PE1.IDPESSOAFJ = BC1.IDPESSOAFJ
             WHERE AB1.NUMERO_OB = OBE.NUMERO_OB
             GROUP BY BC1.NUMERO_NOTA, TRIM(PE1.NOMEFANTASIA)
           ) POC
) QTPNF ON 1=1

WHERE OBE.STATUS <> 0
  AND NOT EXISTS (
    SELECT 1
      FROM (SELECT COUNT(DE1.IDPECASPRODUTO) AS QT_PC_OB
              FROM SGTPRD.GERAPECADESTINOOB DE1
             WHERE DE1.NUMERO_OB = OBE.NUMERO_OB) A
      JOIN (SELECT COUNT(DE2.IDPECASPRODUTO) AS QT_PC_ROM_FAT
              FROM SGTPRD.GERAPECADESTINOOB DE4
              JOIN SGTPRD.PECAS_ROMANEIO_SAIDA DE2 ON DE2.IDPECASPRODUTO = DE4.IDPECASPRODUTO
              JOIN SGTPRD.ROMANEIO DE3 ON DE3.NUMERO_ROMANEIO = DE2.NUMERO_ROMANEIO_SAID
             WHERE DE3.STATUS IN (4, 6)
               AND DE4.NUMERO_OB = OBE.NUMERO_OB) D
        ON D.QT_PC_ROM_FAT = A.QT_PC_OB
       AND A.QT_PC_OB > 0
)