/* =============================================================================
OBJETIVO: Auditoria de furo de estoque detalhado peça a peça (terceirizados)
DOMÍNIO: 05_estoque_armazenagem
ARQUIVO ORIGINAL: 05_estoque_armazenagem/est_conferencia_ob_montada_pecas_de_terceirizados_pesquisa_furo_no_estoque.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.GERAPECANOTAENTRADA, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.OB, SGTPRD.OB_PRODUTO, SGTPRD.PESSOASFJ, SGTPRD.PEDIDOCOMERCIAL
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
OTIMIZAÇÃO: Substituição de full scans por junções indexadas via nested loops e pré-agregações
  em CTEs materializadas, reduzindo de timeout/cancelamento para ~5.6s com dados reais.
============================================================================= */

WITH OBF_CANDIDATOS AS (
    SELECT /*+ MATERIALIZE */ OBFB.NUMERO_OB,
           MAX(DATE '1899-12-30' + (CASE WHEN UPR.STATUS = 0 THEN UPR.TEMPOFINAL ELSE UPR.TEMPOFINALPROGRAMADO END)) AS DATA_HORA_FINAL
      FROM SGTPRD.OB_FASES OBFB
      JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROORDEMREAL = OBFB.NUMERO_OB AND UOM.SEQUENCIAORDEMREAL = OBFB.SEQUENCIA
      JOIN SGTPRD.UNIDADE_PROGRAMACAO UPR ON UPR.NUMEROUP = UOM.NUMEROUP
     WHERE OBFB.CODIGO_FASE = 10
       AND ((UPR.STATUS = 0 AND UPR.TEMPOFINAL >= (TRUNC(SYSDATE) - 15) - DATE '1899-12-30')
         OR ((UPR.STATUS <> 0 OR UPR.STATUS IS NULL) AND UPR.TEMPOFINALPROGRAMADO >= (TRUNC(SYSDATE) - 15) - DATE '1899-12-30'))
     GROUP BY OBFB.NUMERO_OB
),
PEDI_FILTRADO AS (
    SELECT /*+ MATERIALIZE */
           PPOB.NUMEROOB            AS NR_OB,
           MAX(IPG.PEDIDO)          AS NR_PEDIDO,
           MAX(TRIM(PED.PEDIDOCLIENTE)) AS P_CLIENTE
      FROM SGTPRD.PEDPRODUCAOOB    PPOB
      JOIN SGTPRD.PEDPRODUCAO      PP  ON PP.NUMERO = PPOB.NUMERO
      JOIN SGTPRD.OFORDENS         OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
      JOIN SGTPRD.OFPEDIDO         OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL  PED ON PED.PEDIDO = IPG.PEDIDO
     WHERE PPOB.NUMEROOB IN (SELECT NUMERO_OB FROM OBF_CANDIDATOS)
     GROUP BY PPOB.NUMEROOB
),
OPERADOR_POR_OB AS (
    SELECT /*+ MATERIALIZE */
           LOG.NUMERO_OB, TRIM(MAX(OP.NOME)) AS OPERADOR
      FROM SGTPRD.LOG_OBFASES LOG
      JOIN SGTPRD.OPERADOR OP ON OP.CODIGO = LOG.OPERADOR
     WHERE LOG.PROCESSO_INDUSTRIAL = 101
       AND LOG.NUMERO_OB IN (SELECT NUMERO_OB FROM OBF_CANDIDATOS)
     GROUP BY LOG.NUMERO_OB
),
PECAS_POR_OB AS (
    SELECT /*+ MATERIALIZE LEADING(OBF ORI GPP GPE PFJ) USE_NL(ORI GPP GPE PFJ) */
           ORI.NUMERO_OB,
           COUNT(GPP.IDPECASPRODUTO) AS QTD_PC,
           MAX(GPE.IDPESSOAFJ) AS IDPFJ,
           MAX(PFJ.NOME) AS FACO
      FROM OBF_CANDIDATOS OBF
      JOIN SGTPRD.GERAPECAORIGEMOB ORI ON ORI.NUMERO_OB = OBF.NUMERO_OB
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = ORI.IDPECASPRODUTO
      LEFT JOIN SGTPRD.GERAPECANOTAENTRADA GPE ON GPE.IDPECASPRODUTO = GPP.IDPECASPRODUTO
      LEFT JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = GPE.IDPESSOAFJ
     WHERE GPP.TIDOCUMENTOENTRADA = 8
       AND GPP.PADRAO_QUALIDADE_SIN = 1
     GROUP BY ORI.NUMERO_OB
),
LOTES_POR_OB AS (
    SELECT /*+ MATERIALIZE */
           SUB.NUMERO_OB,
           TRIM(LISTAGG(SUB.LOTE_PRODUTO, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY SUB.LOTE_PRODUTO)) AS LOTE_PRODUTO
      FROM (
        SELECT DISTINCT ORI2.NUMERO_OB, GPP2.LOTE_PRODUTO
          FROM OBF_CANDIDATOS OBF
          JOIN SGTPRD.GERAPECAORIGEMOB ORI2 ON ORI2.NUMERO_OB = OBF.NUMERO_OB
          JOIN SGTPRD.GERAPECASPRODUTO GPP2 ON GPP2.IDPECASPRODUTO = ORI2.IDPECASPRODUTO
         WHERE GPP2.TIDOCUMENTOENTRADA = 8
           AND GPP2.PADRAO_QUALIDADE_SIN = 1
      ) SUB
     GROUP BY SUB.NUMERO_OB
)
SELECT PCO.NUMERO_OB,
       ITE.CODIGO_ALTERNATIVO AS ALTERNATIVO,
       PCO.QTD_PC,
       LOT.LOTE_PRODUTO,
       TO_CHAR(PEDI.NR_PEDIDO) AS PEDIDO,
       PEDI.P_CLIENTE,
       TO_CHAR(PCO.IDPFJ) AS IDPFJ,
       TRIM(PCO.FACO) AS FACO,
       TRIM(OBS.TEXTO) AS OBSERVAO,
       OBF.DATA_HORA_FINAL AS HORA_CONFIRMADA,
       OPO.OPERADOR,
       (PCO.QTD_PC - NVL(OBP.TOTAL_PECAS_CONFIRM, 0)) AS PECA_ERRADA
  FROM OBF_CANDIDATOS OBF
  JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBF.NUMERO_OB
  JOIN SGTPRD.OB O ON O.NUMERO_OB = OBF.NUMERO_OB
  JOIN PECAS_POR_OB PCO ON PCO.NUMERO_OB = OBF.NUMERO_OB
  JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = O.CODIGO_REDUZIDO
  LEFT JOIN LOTES_POR_OB LOT ON LOT.NUMERO_OB = OBF.NUMERO_OB
  LEFT JOIN PEDI_FILTRADO PEDI ON PEDI.NR_OB = OBF.NUMERO_OB
  LEFT JOIN OPERADOR_POR_OB OPO ON OPO.NUMERO_OB = OBF.NUMERO_OB
  LEFT JOIN SGTPRD.OBSERVACAO OBS ON OBS.CODIGO = O.CODIGO_OBSERVACAO
 WHERE O.TIPO_ORDEM = 0
   AND (PCO.QTD_PC - NVL(OBP.TOTAL_PECAS_CONFIRM, 0)) <> 0
 ORDER BY PEDI.P_CLIENTE, OBF.DATA_HORA_FINAL
 FETCH FIRST 100 ROWS ONLY
