/* =============================================================================
OBJETIVO: Peças com restrições - Estoque
DOMÍNIO: 05_estoque_armazenagem
ARQUIVO ORIGINAL: Comandos SQL - CR\Peças com restrições - Estoque.sql
TIPO: Estoque e Depósitos
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
       ART.CDARTIGOCRU AS ARTIGO,
       COUNT(GPP.IDPECASPRODUTO) AS PEAS,
       TFF.NUMERO_FINALIDADE || ' - ' || TRIM(TFF.DESCRICAO) AS FINALIDADE,
       SUM(GPP.QTLIQUIDA) AS QTD_KG
FROM SGTPRD.GERAPECASPRODUTO GPP
INNER JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
INNER JOIN SGTPRD.GERAPECACRU GCR ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
INNER JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF ON GPC.FINALIDADE = TFF.NUMERO_FINALIDADE
INNER JOIN SGTPRD.ITENS_ESTOQUE ITE ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
INNER JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = GPP.CODIGO_REDUZIDO_PROD
WHERE GPP.CODIGO_REGISTRO = 1
  AND GPP.STPECAPRODUTO IN (0, 18, 16)
  AND GPP.IDPESSOAFJESTOQUE = 2
  AND GPP.PADRAO_QUALIDADE_SIN = 1
  AND GPP.CODIGO_DEPOSITO IN (90,95)
  AND GPC.FINALIDADE NOT IN (1, 8)
  AND GPP.TIDOCUMENTOENTRADA <> 8
GROUP BY GPP.CODIGO_REDUZIDO_PROD, TFF.NUMERO_FINALIDADE, TFF.DESCRICAO, ART.CDARTIGOCRU
ORDER BY ART.CDARTIGOCRU;

