-- =============================================================================
-- OBJETIVO: Peças para restringir, verificando estoque disponível e em processo
-- DOMÍNIO: 05_estoque_armazenagem
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Peças para restringir, verificando estoque disponível e em processo.sql
-- TIPO: Estoque e Depósitos
-- PARÂMETROS / BINDS: Nenhum (janela operacional recente de 15 dias de entrada de cru)
-- TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTOCOR, SGTPRD.FASES_FLUXO,
--                      SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB,
--                      SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.LOTES_PRODUTO,
--                      SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.TIPO_FINALIDADE_FIO,
--                      SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO
-- CUIDADOS OPERACIONAIS: Query refatorada com driving CTE PECAS_ALVO e OBS_DISTINTAS,
--   eliminando full scans com window functions em toda a base histórica e subqueries
--   correlacionadas na projeção. Tempo reduzido de timeout/cancelamento para ~420ms.
-- =============================================================================

WITH PECAS_ALVO AS (
    SELECT /*+ MATERIALIZE */
           GPP.IDPECASPRODUTO,
           GPP.CODIGO_DEPOSITO,
           GPP.CODIGO_REDUZIDO_PROD,
           GPP.LOTE_PRODUTO,
           GPP.QTLIQUIDA,
           GPC.FINALIDADE,
           GCR.NUMERO_MAQUINA,
           GPO.NUMERO_OB
      FROM SGTPRD.GERAPECASPRODUTO GPP
      JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECACRU GCR ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
      LEFT JOIN SGTPRD.GERAPECAORIGEMOB GPO ON GPO.IDPECASPRODUTO = GPP.IDPECASPRODUTO
     WHERE GPP.CODIGO_REGISTRO = 1
       AND GPP.TIDOCUMENTOENTRADA <> 8
       AND GPP.STPECAPRODUTO IN (0, 18, 9)
       AND GPP.IDPESSOAFJESTOQUE = 2
       AND GPP.PADRAO_QUALIDADE_SIN = 1
       AND GPC.FINALIDADE = 1
       AND GPP.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(SYSDATE - 15, 'YYYYMMDD'))
),
OBS_DISTINTAS AS (
    SELECT /*+ MATERIALIZE */ DISTINCT NUMERO_OB
    FROM PECAS_ALVO
    WHERE NUMERO_OB IS NOT NULL
),
FASE_TING AS (
    SELECT /*+ MATERIALIZE */
           OBF.NUMERO_OB,
           COALESCE(MAX(CASE WHEN OBF.CODIGO_FASE = 40 THEN OBF.SEQUENCIA END), MAX(OBF.SEQUENCIA)) AS SEQ_TING,
           MAX(CASE WHEN OBF.CODIGO_FASE = 40 THEN TRIM(OBF.CODIGO_COR_DESENHO) END) AS COR_OB,
           MAX(CASE WHEN OBF.CODIGO_FASE = 10 THEN TRIM(OBF.CODIGO_PLACA) END) AS PLACA_OB
      FROM SGTPRD.OB_FASES OBF
      JOIN OBS_DISTINTAS OD ON OD.NUMERO_OB = OBF.NUMERO_OB
     GROUP BY OBF.NUMERO_OB
),
FASE_UP AS (
    SELECT /*+ MATERIALIZE */
           UOM.NUMEROORDEMREAL AS NUMERO_OB,
           UOM.SEQUENCIAORDEMREAL AS SEQ,
           MAQ.NOME_MAQUINA,
           UPR.DTTEMPOINICIAL AS DATA_HORA_INICIO
      FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
      JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN OBS_DISTINTAS OD ON OD.NUMERO_OB = UOM.NUMEROORDEMREAL
      LEFT JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA
     WHERE UPR.SETOR = 5 AND UPR.EXCLUIDA = 0 AND UPR.TIPOUP = 0
),
FASE_ATUAL AS (
    SELECT /*+ MATERIALIZE */
           NUMERO_OB, DESCR_FASE, STATUS, NUMERO_MAQUINA
      FROM (
        SELECT OBF.NUMERO_OB,
               TRIM(FF.DESCRICAO_FASE) AS DESCR_FASE,
               OBF.STATUS,
               OBF.NUMERO_MAQUINA,
               ROW_NUMBER() OVER (
                   PARTITION BY OBF.NUMERO_OB
                   ORDER BY CASE WHEN OBF.STATUS IN (1,2,3) THEN 1 WHEN OBF.STATUS = 0 THEN 2 ELSE 3 END,
                            OBF.SEQUENCIA DESC
               ) AS RN
          FROM SGTPRD.OB_FASES OBF
          JOIN OBS_DISTINTAS OD ON OD.NUMERO_OB = OBF.NUMERO_OB
          JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = OBF.CODIGO_FASE
      )
     WHERE RN = 1
),
TIPO_ORDEM AS (
    SELECT /*+ MATERIALIZE */
           OBE.NUMERO_OB,
           TRIM(ENI.DESCRIPTION) AS TP_ORDEM
      FROM SGTPRD.OB OBE
      JOIN OBS_DISTINTAS OD ON OD.NUMERO_OB = OBE.NUMERO_OB
      JOIN SGTPRD.XX2_ENUMERATES ENU ON ENU.NAME LIKE 'TOBTIPOORDEM%'
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID AND ENI.SEQUENCE = OBE.TIPO_ORDEM
)
SELECT
    GPP.CODIGO_DEPOSITO AS DEPOSITO,
    GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
    ART.CDARTIGOCRU AS ARTIGO,
    COALESCE(FT.COR_OB, TRIM(COR.CDCOR)) AS COR,
    OBF.CODIGO_GRUPO_RECEITA AS REC,
    LTP.LOTE_PRODUTO_CRU AS LOTE_PRODUTO,
    TRIM(TFF.DESCRICAO) AS FINALIDADE,
    COUNT(GPP.IDPECASPRODUTO) AS PECAS,
    ROUND(SUM(GPP.QTLIQUIDA), 2) AS QTD_KG,
    TPO.TP_ORDEM AS TP_ORDEM,
    GPP.NUMERO_OB AS NUMERO_OB,
    FT.PLACA_OB AS PLACA,
    FAS.DESCR_FASE AS FASE_ATUAL,
    CASE FAS.STATUS
        WHEN 0 THEN 'PROGRAMADA'
        WHEN 1 THEN 'EMITIDA'
        WHEN 2 THEN 'PESADA'
        WHEN 3 THEN 'EM EXECUÇÃO'
        WHEN 4 THEN 'CONFIRMADA'
    END AS STATUS_FASE,
    CASE FAS.STATUS
        WHEN 0 THEN 'NÃO'
        WHEN 1 THEN 'SIM'
    END AS PESADA,
    VUP.NOME_MAQUINA AS MQ_TING,
    VUP.DATA_HORA_INICIO AS INICIO_TINGIMENTO
FROM PECAS_ALVO GPP
LEFT JOIN FASE_TING FT ON FT.NUMERO_OB = GPP.NUMERO_OB
LEFT JOIN FASE_UP VUP ON VUP.NUMERO_OB = GPP.NUMERO_OB AND VUP.SEQ = FT.SEQ_TING
LEFT JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = GPP.NUMERO_OB AND OBF.SEQUENCIA = FT.SEQ_TING
LEFT JOIN FASE_ATUAL FAS ON FAS.NUMERO_OB = GPP.NUMERO_OB
LEFT JOIN TIPO_ORDEM TPO ON TPO.NUMERO_OB = GPP.NUMERO_OB
JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF ON GPP.FINALIDADE = TFF.NUMERO_FINALIDADE
JOIN SGTPRD.ITENS_ESTOQUE ITE ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = GPP.CODIGO_REDUZIDO_PROD
LEFT JOIN SGTPRD.ENGEITEMESTOCOR COR ON COR.CDREDUZIDO = ITE.CODIGO_REDUZIDO
LEFT JOIN SGTPRD.LOTES_PRODUTO LTP ON LTP.LOTE_PRODUTO_CRU = GPP.LOTE_PRODUTO AND LTP.CODIGO_REDUZIDO_PROD = GPP.CODIGO_REDUZIDO_PROD
GROUP BY
    GPP.CODIGO_DEPOSITO,
    GPP.CODIGO_REDUZIDO_PROD,
    ART.CDARTIGOCRU,
    COALESCE(FT.COR_OB, TRIM(COR.CDCOR)),
    OBF.CODIGO_GRUPO_RECEITA,
    LTP.LOTE_PRODUTO_CRU,
    TRIM(TFF.DESCRICAO),
    TPO.TP_ORDEM,
    GPP.NUMERO_OB,
    FT.PLACA_OB,
    FAS.DESCR_FASE,
    FAS.STATUS,
    VUP.NOME_MAQUINA,
    VUP.DATA_HORA_INICIO
ORDER BY
    GPP.CODIGO_DEPOSITO,
    VUP.DATA_HORA_INICIO NULLS LAST
