/*
    ================================================================================
    QUERY OTIMIZADA: MONTAGEM DE TERCEIRIZADOS (VERSÃO ESTÁVEL)
    FOCO: Filtros Programação %T, Montagem, Destino Receita e Status OB
    ================================================================================
*/

WITH 
-- 1. Dados Básicos da OB (Filtro Status)
CTE_OB AS (
    SELECT 
        NUMERO_OB, STATUS, CODIGO_REDUZIDO, CODIGO_OBSERVACAO
    FROM SGTPRD.OB
    WHERE STATUS <> 0
),

-- 2. NF das Peças Cruas
CTE_NF_CRU AS (
    SELECT POC.NR_OB, SGTPRD.OPTSTRAGGR(POC.QT_PECA||' - '||POC.NR_NF) AS QT_PC_NF
    FROM (
        SELECT AB1.NUMERO_OB NR_OB, BC1.NUMERO_NOTA NR_NF, COUNT(AB1.IDPECASPRODUTO) QT_PECA
        FROM SGTPRD.GERAPECAORIGEMOB AB1
        JOIN SGTPRD.GERAPECANOTAENTRADA BC1 ON BC1.IDPECASPRODUTO = AB1.IDPECASPRODUTO
        GROUP BY AB1.NUMERO_OB, BC1.NUMERO_NOTA
    ) POC
    GROUP BY POC.NR_OB
),

-- 3. Pedido Comercial (Hierarquia Original para obter NR_PROG)
CTE_PEDIDO_PRIORIDADE AS (
    SELECT 
        OB.NUMERO_OB,
        NVL(NVL(
            (SELECT MAX(PR1.NUMERO_PEDIDO) FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO JOIN SGTPRD.GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO WHERE DOB.NUMERO_OB = OB.NUMERO_OB),
            (SELECT MAX(G2.NUMERO_PEDIDO_COMERC) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OB.NUMERO_OB)
        ), (SELECT IPG.PEDIDO FROM SGTPRD.PEDPRODUCAOOB PPOB JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE WHERE PPOB.NUMEROOB = OB.NUMERO_OB AND ROWNUM = 1)
        ) as NR_PEDIDO,
        NVL(NVL(
            (SELECT MAX(PR1.ITEM_PEDIDO) FROM SGTPRD.PECAS_ROMANEIO_SAIDA PRS JOIN SGTPRD.PRODUTO_ROMANEIO PR1 ON PR1.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID AND PR1.IDPRODUTO_ROMANEIO = PRS.IDPRODUTO_ROMANEIO JOIN SGTPRD.GERAPECADESTINOOB DOB ON DOB.IDPECASPRODUTO = PRS.IDPECASPRODUTO WHERE DOB.NUMERO_OB = OB.NUMERO_OB),
            (SELECT MAX(G2.SEQUENCIA_PRODUTO_PE) FROM SGTPRD.GERAPECAPEDCOMERCIAL G2 JOIN SGTPRD.GERAPECADESTINOOB G1 ON G1.IDPECASPRODUTO = G2.IDPECASPRODUTO WHERE G1.NUMERO_OB = OB.NUMERO_OB)
        ), (SELECT IPG.ITEMPEDIDO FROM SGTPRD.PEDPRODUCAOOB PPOB JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE WHERE PPOB.NUMEROOB = OB.NUMERO_OB AND ROWNUM = 1)
        ) as SQ_ITEM
    FROM CTE_OB OB
),

-- 4. Detalhe do Pedido (NR_PROG)
CTE_PED_DET AS (
    SELECT 
        IPC.PEDIDO, IPC.ITEMPEDIDO, TRIM(IPC.CD_DESENHO_CLIENTE) AS CD_REF_CLT,
        TRIM(PED.PEDIDOCLIENTE) AS NR_PROG, TRIM(IPC.ITEMPEDIDOCLIENTE) AS DS_ITEMPED_CLT
    FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPC.PEDIDO
)

SELECT /*+ MONITOR */
    SYSDATE AS Valida_Atualizacao,
    PDET.CD_REF_CLT,
    NF.QT_PC_NF,
    (SELECT SGTPRD.optstraggrsemvirgula(TRIM(UPPER(C.TEXTO))) FROM SGTPRD.OBSERVACAO C WHERE C.CODIGO = OBE.CODIGO_OBSERVACAO) AS OBS_OB,
    OBE.NUMERO_OB AS NR_OB,
    CAST(NULL AS VARCHAR2(100)) AS VALIDACAO_NF,
    DECODE(OBE.STATUS, 0, 0, 1) AS ST_OB_ABERTO,
    PDET.NR_PROG,
    PDET.DS_ITEMPED_CLT,
    (SELECT DECODE(O3.TOTAL_PECAS_CONFIRM,0,(ROUND(O3.KILOS_PROGRAMADOS/NVL((SELECT MAX(PDD.PESO_PADRAO) FROM SGTPRD.VW_ESP_PESO_PADRAO PDD WHERE PDD.REDUZIDO=O3.CODPRO_REDUZIDO),1),0)),O3.TOTAL_PECAS_CONFIRM) FROM SGTPRD.OB_PRODUTO O3 WHERE O3.NUMERO_OB = OBE.NUMERO_OB) AS QT_PC_PROG,
    (SELECT MAX(OBF.CODIGO_PLACA) FROM SGTPRD.OB_FASES OBF WHERE OBF.NUMERO_OB = OBE.NUMERO_OB) AS NR_KANBAN,
    (SELECT TRIM(I.CODIGO_ALTERNATIVO) FROM SGTPRD.ITENS_ESTOQUE I WHERE I.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO) AS CD_ALTERNATIVO,
    (SELECT FF.DESCRICAO_FASE FROM SGTPRD.OB_FASES OBF JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = OBF.CODIGO_FASE WHERE OBF.NUMERO_OB = OBE.NUMERO_OB AND OBF.SEQUENCIA = (SELECT MAX(SEQUENCIA) FROM SGTPRD.OB_FASES WHERE NUMERO_OB = OBE.NUMERO_OB)) as DS_FASE_ATUAL,
    (SELECT UPPER(SS.DESCRICAO) FROM SGTPRD.VW_ENU_STATUS_OB_FASES SS WHERE SS.STATUS = (SELECT STATUS FROM SGTPRD.OB_FASES WHERE NUMERO_OB = OBE.NUMERO_OB AND SEQUENCIA = (SELECT MAX(SEQUENCIA) FROM SGTPRD.OB_FASES WHERE NUMERO_OB = OBE.NUMERO_OB))) as DS_ST_FASE_ATUAL,
    SGTPRD.PKGBENF0001.FNC_RETORNA_ULT_CONF_OB(OBE.NUMERO_OB) AS DT_ULT_CONFIRMACAO

FROM CTE_OB OBE
LEFT JOIN CTE_NF_CRU NF ON NF.NR_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PEDIDO_PRIORIDADE PRI ON PRI.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN CTE_PED_DET PDET ON PDET.PEDIDO = PRI.NR_PEDIDO AND PDET.ITEMPEDIDO = PRI.SQ_ITEM

WHERE OBE.STATUS <> 0
  -- 1. Filtro Montagem (Setor 5)
  AND (SELECT MAX(OBMONTADA) FROM SGTPRD.PEDPRODUCAOOB WHERE NUMEROOB = OBE.NUMERO_OB AND SETOR = 5) = 1
  -- 2. Filtro Destino Receita 1 (Fase 40)
  AND (SELECT MAX(DESTINO_RECEITA) FROM SGTPRD.OB_FASES WHERE NUMERO_OB = OBE.NUMERO_OB AND CODIGO_FASE = 40) = 1
  -- 3. Filtro Programação LIKE %T
  AND PDET.NR_PROG LIKE '%T'
ORDER BY PDET.NR_PROG, PDET.DS_ITEMPED_CLT, OBE.NUMERO_OB
