"""create_initial_schema

Revision ID: a5b212d4418f
Revises: 
Create Date: 2026-05-20 09:07:32.350964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b212d4418f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_ts', ['action', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('script_path', sa.String(length=500), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('max_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('sla_minutes', sa.Integer(), nullable=True),
    sa.Column('queue_group', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automations_name'), ['name'], unique=True)

    op.create_table('worker_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('uptime_seconds', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_failed', sa.Integer(), nullable=True),
    sa.Column('active_tasks', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('queue_group', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('recovery_action', sa.String(length=200), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('artifacts', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_exec_auto_status', ['automation_id', 'status'], unique=False)
        batch_op.create_index('ix_exec_priority_status', ['priority', 'status', 'started_at'], unique=False)
        batch_op.create_index('ix_exec_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_automation_id'), ['automation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_id'))
        batch_op.drop_index(batch_op.f('ix_executions_automation_id'))
        batch_op.drop_index('ix_exec_status_started')
        batch_op.drop_index('ix_exec_priority_status')
        batch_op.drop_index('ix_exec_auto_status')

    op.drop_table('executions')
    op.drop_table('worker_heartbeat')
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_name'))
        batch_op.drop_index(batch_op.f('ix_automations_id'))

    op.drop_table('automations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index('ix_audit_action_ts')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
