/* =============================================================================
OBJETIVO: Desenho Estamparia
DOMÍNIO: 08_faccao_terceirizacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Desenho Estamparia.sql
TIPO: Facção e Serviços Terceiros
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.FASES_FLUXO, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAREQUESTOITEMNOTA, SGTPRD.ITENS_ESTOQUE, SGTPRD.NOTAFISCALCAPA, SGTPRD.NOTAFISCALITENS, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.PECAS_ROMANEIO_SAIDA, SGTPRD.PRODUTO_ROMANEIO, SGTPRD.TERCITEMORDESERVOBFA, SGTPRD.TERCITENSORDEMSERV, SGTPRD.TERCORDEMSERVICO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */


SELECT ROM.NUMERO_ROMANEIO_SAID ROMANEIO,
       NFS.NRNOTA               NOTA_FISCAL,
       SUBSTR(ITE.CODIGO,18,4)||'-'||SUBSTR(ITE.CODIGO,22,4) DESENHO_VARIANTE,
       FFL.DESCRICAO_FASE       DS_FASE_TERCEIRO,
       OBF.CODIGO_FASE          CD_FASE_TERCEIRO,
       OBF.NUMERO_OB            NR_OB,
       OBP.CODPRO_REDUZIDO      CD_RED_ACA,
       ITE.DESCRICAO            DS_PRODUTO,
       ROM.QTDE                 QT_NF,
       --SUBSTR(ITE.CODIGO,18,6)  DESENHO, '000000'
       --SUBSTR(ITE.CODIGO,24,2)  VARIANTE, '00'
       --SUBSTR(ITE.CODIGO,18,6)||'-'||SUBSTR(ITE.CODIGO,24,2) CD_DESENHO_VAR, '000000-00'
       TOS.ID                   NR_OS

FROM   SGTPRD.OB_FASES             OBF,
       SGTPRD.FASES_FLUXO          FFL,
       SGTPRD.OB_PRODUTO           OBP,
       SGTPRD.ITENS_ESTOQUE        ITE,
       SGTPRD.TERCITEMORDESERVOBFA SOV,
       SGTPRD.TERCITENSORDEMSERV   OSV,
       SGTPRD.TERCORDEMSERVICO     TOS,
      (SELECT ORI.NUMERO_OB, PRS.NUMERO_ROMANEIO_SAID, SUM(PRS.PESO_PECA) QTDE
       FROM  SGTPRD.GERAPECAORIGEMOB ORI,
             SGTPRD.PECAS_ROMANEIO_SAIDA PRS
       WHERE PRS.IDPECASPRODUTO = ORI.IDPECASPRODUTO
       GROUP BY ORI.NUMERO_OB, PRS.NUMERO_ROMANEIO_SAID
      ) ROM,
      (SELECT PRO.NUMERO_ROMANEIO, NFC.NRNOTA
       FROM   SGTPRD.GERAREQUESTOITEMNOTA   GQI,
              SGTPRD.PRODUTO_ROMANEIO       PRO,
              SGTPRD.NOTAFISCALITENS        NFI,
              SGTPRD.NOTAFISCALCAPA         NFC
       WHERE  PRO.IDPRODUTO_ROMANEIO = GQI.IDPRODUTO_ROMANEIO
       AND    NFI.ID                 = GQI.IDNOTAFISCALITENS
       AND    NFC.ID                 = NFI.IDNOTAFISCALCAPA
       GROUP BY PRO.NUMERO_ROMANEIO, NFC.NRNOTA
      ) NFS
WHERE  FFL.CODIGO_FASE     = OBF.CODIGO_FASE
AND    OBP.NUMERO_OB       = OBF.NUMERO_OB
AND    ITE.CODIGO_REDUZIDO = OBP.CODPRO_REDUZIDO
AND    SOV.NUMERO_OB       = OBF.NUMERO_OB
AND    SOV.SEQUENCIA       = OBF.SEQUENCIA
AND    OSV.ID              = SOV.IDTERCITENSORDEMSERV
AND    TOS.ID              = OSV.IDTERCORDEMSERVICO
AND    ROM.NUMERO_OB       = OBF.NUMERO_OB
AND    NFS.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO_SAID
AND    OBF.STATUS = 3 --EM EXECUÇÃO
AND    FFL.PROCESSOTERCEIROS = '1'
AND    OBF.CODIGO_FASE <> 140

ORDER BY 2
