-- =============================================================================
-- OBJETIVO: Faltas e Sobras (Facção)
-- DOMÍNIO: 08_faccao_terceirizacao
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Faltas e Sobras (Facção).sql
-- TIPO: Facção e Serviços Terceiros (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (janela de 6 meses para notas de facção)
-- TABELAS PRINCIPAIS: SGTPRD.DEPOSITO, SGTPRD.ENGEITEMARTIGOCRU,
--                     SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENG_PRODG_ACABADO,
--                     SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU,
--                     SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECANOTAENTRADA,
--                     SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOGRADE,
--                     SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE,
--                     SGTPRD.ITENS_NOTA_ENTRADA, SGTPRD.LOTE_ITENS_NOTA_ENTR,
--                     SGTPRD.MESTRE_NOTA_ENTRADA, SGTPRD.OB, SGTPRD.OB_PRODUTO,
--                     SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL,
--                     SGTPRD.PEDPRODUCAOOB, SGTPRD.PESO_PADRAO_PECA, SGTPRD.PESSOASFJ
-- CUIDADOS OPERACIONAIS: Pushdown de fornecedor de facção (IDCATEGORIFORNECEDOR=1) e janela
--                        de 6 meses em PESAGEM_ENTRADA e FPES_FISICO. Filtro de OBs abertas
--                        em OB_ABERTO_BASE e unificação de produtos em ITENS_ATIVOS.
--                        Elimina timeout crítico e ORA-00028.
-- =============================================================================

WITH
    PESAGEM_ENTRADA AS (
        SELECT /*+ MATERIALIZE */
               LIN.NUMERO_NOTA,
               LIN.SERIE_NOTA,
               LIN.IDPESSOAFJ,
               LIN.CODINSREDUZIDO,
               LIN.SEQUENCIA_DIGITACAO,
               DECODE(
                   SUM(NVL(GPN.QTPESOLIQORIGPECANFE, 0)),
                   0,
                   SUM(NVL(GPP.QTLIQUIDA, 0)),
                   SUM(NVL(GPN.QTPESOLIQORIGPECANFE, 0))
               ) AS QT_TOTAL
          FROM SGTPRD.MESTRE_NOTA_ENTRADA MNE
          JOIN SGTPRD.PESSOASFJ PES
            ON PES.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
           AND PES.IDCATEGORIFORNECEDOR = 1
          JOIN SGTPRD.LOTE_ITENS_NOTA_ENTR LIN
            ON LIN.NUMERO_NOTA = MNE.NUMERO_NOTA
           AND LIN.SERIE_NOTA = MNE.SERIE_NOTA
           AND LIN.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
          JOIN SGTPRD.GERAPECANOTAENTRADA GPN
            ON GPN.NUMERO_NOTA = LIN.NUMERO_NOTA
           AND GPN.SERIE_NOTA = LIN.SERIE_NOTA
           AND GPN.IDPESSOAFJ = LIN.IDPESSOAFJ
           AND GPN.CODINSREDUZIDO = LIN.CODINSREDUZIDO
           AND GPN.SEQUENCIA_DIGITACAO = LIN.SEQUENCIA_DIGITACAO
           AND GPN.LOTE = LIN.LOTE
           AND GPN.QUALIDADE = LIN.QUALIDADE
          JOIN SGTPRD.GERAPECASPRODUTO GPP
            ON GPP.IDPECASPRODUTO = GPN.IDPECASPRODUTO
         WHERE MNE.CDFILIAL = 1
           AND MNE.STATUS = 5
           AND MNE.DTENTRADA >= ADD_MONTHS(TRUNC(SYSDATE), -6)
           AND LIN.STFINALIZACAO IN (2, 3)
         GROUP BY LIN.NUMERO_NOTA,
                  LIN.SERIE_NOTA,
                  LIN.IDPESSOAFJ,
                  LIN.CODINSREDUZIDO,
                  LIN.SEQUENCIA_DIGITACAO
    ),
    PESO_PADRAO AS (
        SELECT /*+ MATERIALIZE */
               REDUZIDO, MAX(PESO_PADRAO) AS PESO_PADRAO
          FROM (
                SELECT ART.CDREDUZIDO AS REDUZIDO,
                       PCR.PESO_METROS_PECA AS PESO_PADRAO
                  FROM SGTPRD.PESO_PADRAO_PECA PCR
                  JOIN SGTPRD.ENGEITEMESTOARTCRU ART
                    ON ART.CDREDUZIDO = PCR.CODIGO_REDUZIDO_PROD
                UNION ALL
                SELECT ART.CDREDUZIDO AS REDUZIDO,
                       PAC.VLPESO_METROS_PECA AS PESO_PADRAO
                  FROM SGTPRD.ENG_PRODG_ACABADO PAC
                  JOIN SGTPRD.ITENS_ESTOQUE AGR
                    ON AGR.REDUZIDO_AGRUPADOR = PAC.REDUZIDO_AGRUPADOR
                  JOIN SGTPRD.ENGEITEMESTOARTCRU ART
                    ON ART.CDREDUZIDO = AGR.CODIGO_REDUZIDO
               ) BASE
         GROUP BY REDUZIDO
    ),
    FPES_FISICO AS (
        SELECT /*+ MATERIALIZE */
               INE.CODINSREDUZIDO AS CD_REDUZIDO,
               SUM(NVL(LTI.VOLUMES, 0)) AS QT_PC_FALTA_PESAR
          FROM SGTPRD.MESTRE_NOTA_ENTRADA MNE
          JOIN SGTPRD.ITENS_NOTA_ENTRADA INE
            ON INE.NUMERO_NOTA = MNE.NUMERO_NOTA
           AND INE.SERIE_NOTA = MNE.SERIE_NOTA
           AND INE.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
          JOIN SGTPRD.LOTE_ITENS_NOTA_ENTR LTI
            ON LTI.NUMERO_NOTA = INE.NUMERO_NOTA
           AND LTI.SERIE_NOTA = INE.SERIE_NOTA
           AND LTI.IDPESSOAFJ = INE.IDPESSOAFJ
           AND LTI.SEQUENCIA_DIGITACAO = INE.SEQUENCIA_DIGITACAO
           AND LTI.CODINSREDUZIDO = INE.CODINSREDUZIDO
          JOIN SGTPRD.PESSOASFJ PES
            ON PES.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
          LEFT JOIN PESAGEM_ENTRADA PESO
            ON PESO.NUMERO_NOTA = LTI.NUMERO_NOTA
           AND PESO.SERIE_NOTA = LTI.SERIE_NOTA
           AND PESO.IDPESSOAFJ = LTI.IDPESSOAFJ
           AND PESO.CODINSREDUZIDO = LTI.CODINSREDUZIDO
           AND PESO.SEQUENCIA_DIGITACAO = LTI.SEQUENCIA_DIGITACAO
         WHERE MNE.CDFILIAL = 1
           AND MNE.STATUS = 5
           AND MNE.DTENTRADA >= ADD_MONTHS(TRUNC(SYSDATE), -6)
           AND PES.IDCATEGORIFORNECEDOR = 1
           AND LTI.QUALIDADE = 1
           AND LTI.STFINALIZACAO <> 3
           AND INE.GERA_ESTOQUE_BLOQUEA <> '0'
           AND INE.DEPOSITO IN (
                 SELECT DEP.CODIGO_DEPOSITO
                   FROM SGTPRD.DEPOSITO DEP
                  WHERE DEP.SOCONTROLAQUILOS = '0'
               )
           AND NVL(PESO.QT_TOTAL, 0) = 0
         GROUP BY INE.CODINSREDUZIDO
    ),
    OB_ABERTO_BASE AS (
        SELECT /*+ MATERIALIZE */
            OB.NUMERO_OB,
            OB.CODIGO_REDUZIDO,
            OB.CODIGO_REDUZIDO_CRU,
            NVL(OBP.KILOS_PROGRAMADOS, 0) AS KILOS_PROGRAMADOS
        FROM SGTPRD.OB OB
        JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OB.NUMERO_OB
        WHERE OB.STATUS IN (1, 2, 3)
          AND OB.DTENCERORDEM IS NULL
          AND NOT EXISTS (
              SELECT 1 FROM SGTPRD.GERAPECAORIGEMOB ORI WHERE ORI.NUMERO_OB = OB.NUMERO_OB
          )
    ),
    PDC_SUB AS (
        SELECT DISTINCT
            PPOB.NUMEROOB AS NR_OB
        FROM SGTPRD.PEDPRODUCAOOB PPOB
        JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PPOB.NUMERO
        JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
        JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON OFP.IDITENSPEDIDOQTDES = IPQ.IDITENSPEDIDOQTDES
        JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
        JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
        JOIN OB_ABERTO_BASE OAB ON OAB.NUMERO_OB = PPOB.NUMEROOB
        WHERE PED.CD_SUBTIPOPED NOT IN (2, 3)
          AND PED.PEDIDOCLIENTE LIKE '%T'
    ),
    OB_ABERTO_CTE AS (
        SELECT /*+ MATERIALIZE */
            OAB.CODIGO_REDUZIDO_CRU AS REDUZ_DESC,
            E.CDARTIGOCRU AS ARTIGO,
            SUM(OAB.KILOS_PROGRAMADOS) AS QTD_PROG,
            CASE
                WHEN NVL(PP.PESO_PADRAO, 0) <> 0 THEN ROUND(SUM(OAB.KILOS_PROGRAMADOS) / NVL(PP.PESO_PADRAO, 0), 0)
                ELSE 0
            END AS QTD_PECAS,
            NVL(PP.PESO_PADRAO, 0) AS PESO_PADRAO
        FROM OB_ABERTO_BASE OAB
        JOIN PDC_SUB PDC ON PDC.NR_OB = OAB.NUMERO_OB
        LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU E ON E.CDREDUZIDO = OAB.CODIGO_REDUZIDO
        LEFT JOIN PESO_PADRAO PP ON PP.REDUZIDO = OAB.CODIGO_REDUZIDO_CRU
        GROUP BY
            E.CDARTIGOCRU,
            OAB.CODIGO_REDUZIDO_CRU,
            NVL(PP.PESO_PADRAO, 0)
    ),
    EST_TINTURARIA_CTE AS (
        SELECT /*+ MATERIALIZE */
            GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
            ART.CDARTIGOCRU AS ARTIGO,
            COUNT(GPP.IDPECASPRODUTO) AS QTD_PECAS,
            SUM(NVL(GPP.QTLIQUIDA,0)) AS QTD_KG
        FROM SGTPRD.GERAPECASPRODUTO GPP
        INNER JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
        INNER JOIN SGTPRD.GERAPECACRU GCR ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
        INNER JOIN SGTPRD.ITENS_ESTOQUE ITE ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
        INNER JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ITE.CODIGO_REDUZIDO = ART.CDREDUZIDO
        WHERE GPP.CODIGO_REGISTRO = 1
          AND GPP.STPECAPRODUTO IN (0, 16, 18)
          AND GPP.PADRAO_QUALIDADE_SIN = 1
          AND GPP.CODIGO_DEPOSITO = 95
          AND GPP.TIDOCUMENTOENTRADA = 8
        GROUP BY
            GPP.CODIGO_REDUZIDO_PROD,
            ART.CDARTIGOCRU
    ),
    ITENS_ATIVOS AS (
        SELECT REDUZ_DESC AS CD_REDUZIDO FROM OB_ABERTO_CTE
        UNION
        SELECT REDUZ AS CD_REDUZIDO FROM EST_TINTURARIA_CTE
        UNION
        SELECT CD_REDUZIDO FROM FPES_FISICO
    )
SELECT
    IFAC.CODIGO_REDUZIDO AS CD_REDUZIDO,
    TRIM(IFAC.CODIGO_ALTERNATIVO) AS CD_ARTIGO,
    NVL(OB_A.QTD_PECAS, 0) AS QT_PC_PROGRAMADA,
    NVL(EST_T.QTD_PECAS, 0) AS QT_PC_TINTURARIA,
    NVL(FPES.QT_PC_FALTA_PESAR, 0) AS QT_PC_FALTA_PESAR,
    LEAST(0, (NVL(EST_T.QTD_PECAS, 0) + NVL(FPES.QT_PC_FALTA_PESAR, 0)) - NVL(OB_A.QTD_PECAS, 0)) AS QT_PC_FALTA_PRODUZIR,
    GREATEST(0, (NVL(EST_T.QTD_PECAS, 0) + NVL(FPES.QT_PC_FALTA_PESAR, 0)) - NVL(OB_A.QTD_PECAS, 0)) AS QT_PC_SOBRA
FROM ITENS_ATIVOS IA
JOIN SGTPRD.ITENS_ESTOQUE IFAC ON IFAC.CODIGO_REDUZIDO = IA.CD_REDUZIDO
LEFT JOIN OB_ABERTO_CTE OB_A ON OB_A.REDUZ_DESC = IFAC.CODIGO_REDUZIDO
LEFT JOIN EST_TINTURARIA_CTE EST_T ON EST_T.REDUZ = IFAC.CODIGO_REDUZIDO
LEFT JOIN FPES_FISICO FPES ON FPES.CD_REDUZIDO = IFAC.CODIGO_REDUZIDO
WHERE (NVL(OB_A.QTD_PECAS, 0) + NVL(EST_T.QTD_PECAS, 0) + NVL(FPES.QT_PC_FALTA_PESAR, 0)) > 0
  AND IFAC.TIPO_ITEM = 9
ORDER BY TRIM(IFAC.CODIGO_ALTERNATIVO), IFAC.CODIGO_REDUZIDO
