/* =============================================================================
OBJETIVO: Tabela - Reduzidos com serviços em terceiros
DOMÍNIO: 08_faccao_terceirizacao
ARQUIVO ORIGINAL: Comandos SQL - CR\Tabela - Reduzidos com serviços em terceiros.sql
TIPO: Facção e Serviços Terceiros
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.FLUXO_FASES, SGTPRD.FLUXO_FASE_MAQUINAS, SGTPRD.GRUPO_FLUXO, SGTPRD.GRUPO_FLUXO_FASES, SGTPRD.GRUPO_MAQUINAS, SGTPRD.GRUPO_PRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.UNIDADE_FABRIL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT ART.CDARTIGOCRU              ARTIGO,
       TRIM(ITE.CODIGO_ALTERNATIVO) ALTERNATIVO,
       ITE.CODIGO_REDUZIDO          REDUZ,
       TRIM(ITE.DESCRICAO)          DESCR_ITEM1,
       
       (UFA.CODIGO_UNIDADE_FABRI)
       ||' - '||
       TRIM(UFA.NOME_UNIDADE_FABRIL)UND_FABRIL,
       
       MAQ.TIPO_MAQUINA             TP_MQ,
       LTRIM(MAQ.NUMERO_MAQUINA,0)  MQ,
       TRIM(MAQ.NOME_MAQUINA)       NOME_MAQUINA,
       GPR.GRUPO                    GRUPO,
       GPR.DESCRICAO                DESCR_GRUPO
  FROM SGTPRD.ITENS_ESTOQUE        ITE,
       SGTPRD.ENGEITEMESTOARTCRU   ART,
       SGTPRD.MAQUINA              MAQ,
       SGTPRD.GRUPO_MAQUINAS       GPR,
       SGTPRD.UNIDADE_FABRIL       UFA,
       SGTPRD.GRUPO_PRODUTO        GPO,
       SGTPRD.GRUPO_FLUXO          GF,
       SGTPRD.FLUXO_FASE_MAQUINAS  FFM,
       SGTPRD.GRUPO_FLUXO_FASES    GFF,
       SGTPRD.FLUXO_FASES          FFA   
 WHERE UFA.EH_FACCAO = 'S'
   AND GFF.IDGRUPOFLUXO = GF.IDGRUPOFLUXO
   AND GFF.CODIGO_FASE = FFA.CODIGO_FASE  
   AND GF.CODIGO_FLUXO = FFA.CODIGO_FLUXO 
   AND GFF.SEQUENCIA   = FFA.SEQUENCIA    
   AND FFM.SEQUENCIA   = FFA.SEQUENCIA
   AND FFM.CODIGO_FLUXO = FFA.CODIGO_FLUXO
   AND FFM.NUMERO_MAQUINA = MAQ.NUMERO_MAQUINA
   AND GF.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
   AND GF.NUMERO_GRUPO_PROGRAM = GPO.NUMERO_GRUPO_PROGRAM
   AND GPO.NUMERO_GRUPO_PROGRAM = ITE.NUMERO_GRUPO_PROGRAM
   AND UFA.CODIGO_UNIDADE_FABRI = GPR.UNIDADE_FABRIL
   AND ART.CDREDUZIDO = ITE.CODIGO_REDUZIDO
   AND GPR.GRUPO = MAQ.GRUPO
   AND GPR.SETOR = MAQ.SETOR
   --AND TRIM(ART.CDARTIGOCRU) = '00056'
   AND ITE.TIPO_ITEM = 10
   AND GF.STATUS IN (0,1)
 ORDER BY 5, ITE.CODIGO_ALTERNATIVO;
