/* =============================================================================
OBJETIVO: OB_s com finalidade, lotes ou teares misturados
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s com finalidade, lotes ou teares misturados.sql
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTOCOR, SGTPRD.FASES_FLUXO, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.GRUPO_MAQUINAS, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OBSERVACAO, SGTPRD.OB_FASES, SGTPRD.OPERADOR
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH TP_ORDEM_CTE AS (
    SELECT 
        OBFXX.NUMERO_OB,
        DECODE(MAX(OBFXX.DESTINO_RECEITA),
               1, 'Produo',
               2, 'Reprocesso',
               4, 'Reclassificao',
               0) AS TP_ORDEM
    FROM SGTPRD.OB_FASES OBFXX
    GROUP BY OBFXX.NUMERO_OB
),
ARTIGO_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        ART.CDARTIGOCRU AS ARTIGO
    FROM SGTPRD.OB OBE
    JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = OBE.CODIGO_REDUZIDO_CRU
),
COR_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        COALESCE(
            (SELECT 
                TRIM(MAX(OBZ.CODIGO_COR_DESENHO))
             FROM SGTPRD.OB_FASES OBZ
             WHERE OBZ.NUMERO_OB = OBE.NUMERO_OB
             AND OBZ.CODIGO_FASE = 40
             GROUP BY OBZ.NUMERO_OB),
            (SELECT
                TRIM(COR.CDCOR)
             FROM SGTPRD.ENGEITEMESTOCOR COR
             WHERE COR.CDREDUZIDO = OBE.CODIGO_REDUZIDO)
        ) AS COR
    FROM SGTPRD.OB OBE
),
FASE_ATUAL_CTE AS (
    SELECT 
        OBF.NUMERO_OB,
        MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS FASE_ATUAL,
        DECODE(MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA),
               0, 'PROGRAMADA',
               1, 'EMITIDA',
               2, 'PESADA',
               3, 'EM EXECUÇÃO') AS ST_FASE
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    WHERE OBF.STATUS <> 4
    GROUP BY OBF.NUMERO_OB
),
OPERADOR_CTE AS (
    SELECT 
        OBF.NUMERO_OB,
        LISTAGG(TRIM(OPE.NOME), ', ') WITHIN GROUP (ORDER BY TRIM(OPE.NOME)) AS OPERADOR,
        MIN(DATE '1996-01-01' + OBF.TEMPO_FINAL_CONFIRMA / 1440) AS HORARIO_CONFIRMADO
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.OPERADOR OPE ON OPE.CODIGO = OBF.OPERADOR_FINAL
    WHERE OBF.CODIGO_FASE = 10
    GROUP BY OBF.NUMERO_OB
),
ANALISE_CTE AS (
    SELECT 
        GPO.NUMERO_OB,
        GPP.CODIGO_REDUZIDO_PROD,
        CASE
            WHEN COUNT(DISTINCT GPC.FINALIDADE) > 1 THEN 1
            ELSE 0
        END AS FINALIDADE,
        CASE
            WHEN COUNT(DISTINCT GPP.LOTE_PRODUTO) > 1 THEN 1
            ELSE 0
        END AS LOTE_PRODUTO,
        CASE
            WHEN COUNT(DISTINCT GRP.FABRICANTE_MODELO) > 1 OR COUNT(DISTINCT GRP.NUMERO_AGULHAS_CILIN) > 1 THEN 1
            ELSE 0
        END AS TEARES_SIMILARES,
        
        /*CASE
            WHEN COUNT(DISTINCT GRP.FABRICANTE_MODELO) > 1 THEN 1
            ELSE 0
        END AS TEARES_SIMILARES,
        */
        CASE
            WHEN COUNT(DISTINCT GPR.NUMERO_MAQUINA) > 1 THEN 1
            ELSE 0
        END AS TEARES_UNICOS
    FROM SGTPRD.GERAPECAORIGEMOB GPO
    JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPC.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN SGTPRD.OB OB ON GPO.NUMERO_OB = OB.NUMERO_OB
    JOIN SGTPRD.GERAPECACRU GPR ON GPR.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN (
        SELECT 
            MQ.NUMERO_MAQUINA,
            GRM.NUMERO_AGULHAS_CILIN,
            GRM.NUMERO_AGULHAS_DISCO,
            TRIM(MQ.FABRICANTE)||' - '||TRIM(MQ.MODELO) FABRICANTE_MODELO
        FROM SGTPRD.MAQUINA MQ
        JOIN SGTPRD.GRUPO_MAQUINAS GRM ON MQ.GRUPO = GRM.GRUPO
        WHERE MQ.TIPO_MAQUINA = 145
        AND MQ.CODIGO_UNIDADE_FABRI = '00005'
        GROUP BY MQ.NUMERO_MAQUINA, GRM.NUMERO_AGULHAS_CILIN, GRM.NUMERO_AGULHAS_DISCO, TRIM(MQ.FABRICANTE)||' - '||TRIM(MQ.MODELO)
    ) GRP ON GPR.NUMERO_MAQUINA = GRP.NUMERO_MAQUINA
    WHERE GPP.TIDOCUMENTOENTRADA <> 8
    AND GPP.PADRAO_QUALIDADE_SIN = 1
    GROUP BY GPO.NUMERO_OB, GPP.CODIGO_REDUZIDO_PROD
),
OBE_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        OBE.CODIGO_REDUZIDO,
        OBE.CODIGO_REDUZIDO_CRU,
        OBE.STATUS,
        OBE.TIPO_ORDEM,
        OBS.TEXTO AS OBSERVACAO_OB
    FROM SGTPRD.OB OBE
    LEFT JOIN SGTPRD.OBSERVACAO OBS ON OBS.CODIGO = OBE.CODIGO_OBSERVACAO
    WHERE OBE.STATUS <> 0
    AND OBE.TIPO_ORDEM = 0
    AND OBE.CODIGO_REDUZIDO IN (SELECT ENG.CDREDUZIDO FROM SGTPRD.ENGEITEMESTOCOR ENG WHERE TRIM(ENG.CDCOR) <> '99999')
    AND OBE.CODIGO_REDUZIDO_CRU IN (1563, 1655, 48, 47, 11852,152)
)
SELECT
    OBE.NUMERO_OB,
    TP.TP_ORDEM,
    ART.ARTIGO,
    COR.COR,
    A.FINALIDADE,
    A.LOTE_PRODUTO,
    A.TEARES_SIMILARES,
    A.TEARES_UNICOS,
    FASE.FASE_ATUAL,
    FASE.ST_FASE,
    OPE.OPERADOR,
    OPE.HORARIO_CONFIRMADO,
    OBE.OBSERVACAO_OB
FROM OBE_CTE OBE
LEFT JOIN TP_ORDEM_CTE TP ON TP.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN ARTIGO_CTE ART ON ART.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN COR_CTE COR ON COR.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN FASE_ATUAL_CTE FASE ON FASE.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN OPERADOR_CTE OPE ON OPE.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN ANALISE_CTE A ON A.NUMERO_OB = OBE.NUMERO_OB
WHERE (A.LOTE_PRODUTO + A.TEARES_SIMILARES) <> 0
ORDER BY OPE.HORARIO_CONFIRMADO
