/* =============================================================================
OBJETIVO: Estoque de malha crua agrupado por número do tear
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: 03_malharia_teares/mal_estoque_agrupado_por_tear_e_lote_produto.sql (Query #2)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT LTRIM(GCR.NUMERO_MAQUINA,0) TEAR,
       COUNT(GPP.IDPECASPRODUTO) PEAS
  FROM SGTPRD.GERAPECASPRODUTO GPP
 INNER JOIN SGTPRD.GERAPECACOMPLPECA GPC
    ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
 INNER JOIN SGTPRD.GERAPECACRU GCR
    ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
 INNER JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF
    ON GPC.FINALIDADE = TFF.NUMERO_FINALIDADE
 INNER JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
   AND GPP.CODIGO_REGISTRO = 1
   AND GPP.STPECAPRODUTO IN (0, 16, 18)
   AND GPP.IDPESSOAFJESTOQUE = 2
   AND GPP.PADRAO_QUALIDADE_SIN = 1
   AND GPP.CODIGO_DEPOSITO IN (95)
   AND GPC.FINALIDADE = 1
   AND GPP.TIDOCUMENTOENTRADA <> 8
   AND ITE.CODIGO_REDUZIDO IN (11852)
 GROUP BY LTRIM(GCR.NUMERO_MAQUINA,0)
 ORDER BY LTRIM(GCR.NUMERO_MAQUINA,0);
