/* =============================================================================
OBJETIVO: Produção e Eficiência da Malharia (Engenharia) ordens em aberto
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: Comandos SQL - CR\Produção e Eficiência da Malharia (Engenharia) ordens em aberto.sql
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENG_AGRUPAITENSESTOQ, SGTPRD.ENG_PRODG_CRU, SGTPRD.FICHA_MALHA, SGTPRD.FICHA_RETILINEA, SGTPRD.FIOS_FICHA_MALHARIA_, SGTPRD.ITENS_COMPLEMENTO, SGTPRD.ITENS_COMPLEMENTO_FI, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.ORDEM_PRODUCAO_MALHA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
REVISÃO (20/09/2026 - Onda 3): cadeia de ficha/produção e relação externa
  migradas para LEFT/INNER JOIN ANSI; cardinalidade deve ser confirmada no Oracle.
============================================================================= */

-- PRODUÇÃO COM ORDEM EM ABERTO NA MALHARIA ATUALMENTE (68% DE EFICIÊNCIA)
WITH OPM_REL AS (
    SELECT M.NUMERO_MAQUINA,
           COALESCE(
               MIN(CASE WHEN O.STATUS = 3 THEN O.NUMERO_ORDEM END),
               MIN(CASE WHEN O.STATUS = 1 THEN O.NUMERO_ORDEM END),
               MIN(CASE WHEN O.STATUS = 2 THEN O.NUMERO_ORDEM END)
           ) AS NUMERO_ORDEM
      FROM SGTPRD.MAQUINA M
      LEFT JOIN SGTPRD.ORDEM_PRODUCAO_MALHA O
        ON O.NUMERO_MAQUINA = M.NUMERO_MAQUINA
       AND O.STATUS IN (1, 2, 3)
     WHERE M.SETOR IN (4, 7)
       AND M.CODIGO_UNIDADE_FABRI = '00005'
       AND M.TIPO_MAQUINA IN (145, 146)
     GROUP BY M.NUMERO_MAQUINA
)
SELECT OPM.CODIGO_REDUZIDO_PROD REDUZIDO,
 
       (SELECT TRIM(ITE.DESCRICAO) 
          FROM SGTPRD.ITENS_ESTOQUE ITE 
         WHERE ITE.CODIGO_REDUZIDO = OPM.CODIGO_REDUZIDO_PROD) DESCRICAO_PRODUTO,
       
       ROUND(SUM(PRO.KG_HORA*24),2) KG_DIA_EFIC100,        
       ROUND(SUM(PRO.KG_HORA_EFIC*24),2) KG_DIA_EFIC68, 
       COUNT(OPM.NUMERO_ORDEM) QT_ORDENS_ABERTO, 
       ROUND(SUM(PRO.KG_HORA_EFIC*24)/COUNT(OPM.NUMERO_ORDEM),2) KG_DIA_EFIC68_POR_MQ
       
  FROM   SGTPRD.ORDEM_PRODUCAO_MALHA OPM
  JOIN   SGTPRD.MAQUINA              MAQ
    ON   MAQ.NUMERO_MAQUINA = OPM.NUMERO_MAQUINA
  LEFT JOIN (
         SELECT  FMA.CODPROREDUZIDO CODIGO_REDUZIDO,
                 FMA.GRUPO GRUPO, 
                 FMA.PRIORIDADE,
                 SUM(453.6/768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                     FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE,0),0,0.00001,ICF.TITULO_FIO_NE)*DECODE(NVL(FFI.INDIESTITITULO,0),0,1,FFI.INDIESTITITULO))) PESO_FIO_VOLTA,
                 SUM((453.6/768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                     FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE,0),0,0.00001,ICF.TITULO_FIO_NE)*DECODE(NVL(FFI.INDIESTITITULO,0),0,1,FFI.INDIESTITITULO))*DECODE(NVL(FFI.NUMERO_CABOS,0),0,1,FFI.NUMERO_CABOS)) * FMA.RPM * 60 / 1000) KG_HORA,
                 SUM((453.6/768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                     FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE,0),0,0.00001,ICF.TITULO_FIO_NE)*DECODE(NVL(FFI.INDIESTITITULO,0),0,1,FFI.INDIESTITITULO))*DECODE(NVL(FFI.NUMERO_CABOS,0),0,1,FFI.NUMERO_CABOS)) * FMA.RPM * 60 *
                     (68 / 100) / 1000) KG_HORA_EFIC
            FROM SGTPRD.FICHA_MALHA FMA
            LEFT JOIN SGTPRD.FIOS_FICHA_MALHARIA_ FFI
              ON FFI.GRUPO_MAQUINA = FMA.GRUPO
             AND FFI.CODIGO_PRODUTO = FMA.CODPROREDUZIDO
            LEFT JOIN SGTPRD.ITENS_COMPLEMENTO_FI ICF
              ON ICF.CODIGO_REDUZIDO = FFI.CODIGO_FIO
           GROUP BY FMA.CODPROREDUZIDO, FMA.GRUPO, FMA.PRIORIDADE
               
           UNION ALL
               
           SELECT FMA.CODIGO_PRODUTO CODIGO_REDUZIDO,
                 FMA.GRUPO_MAQUINA  GRUPO,
                 FMA.PRIORIDADE,
                 0 PESO_FIO_VOLTA,
                 ROUND((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60)/((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS)*1000),2) KG_HORA,
                 ROUND(((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60)/((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS)*1000)),2) * (68 / 100) KG_HORA_EFIC
            FROM SGTPRD.FICHA_RETILINEA  FMA
            LEFT JOIN SGTPRD.ITENS_COMPLEMENTO ICO
              ON ICO.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO
            LEFT JOIN SGTPRD.ENG_AGRUPAITENSESTOQ EAI
              ON EAI.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO
            LEFT JOIN SGTPRD.ENG_PRODG_CRU EPC
              ON EPC.REDUZIDO_AGRUPADOR = EAI.REDUZIDO_AGRUPADOR
        ) PRO
    ON PRO.CODIGO_REDUZIDO = OPM.CODIGO_REDUZIDO_PROD
   AND PRO.GRUPO = MAQ.GRUPO
  WHERE OPM.STATUS <> 0
  AND    OPM.NUMERO_ORDEM IN (SELECT R.NUMERO_ORDEM FROM OPM_REL R)
  GROUP BY OPM.CODIGO_REDUZIDO_PROD
  ORDER BY OPM.CODIGO_REDUZIDO_PROD;   
