/* =============================================================================
OBJETIVO: Conferência - OB montada (teares e lotes alocados)
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: Comandos SQL - CR\Conferência - OB montada (teares e lotes alocados).sql
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.GRUPO_MAQUINAS, SGTPRD.LOTES_FIO_PRODUTO, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OBSERVACAO, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
REVISÃO (21/09/2026): junções legadas migradas para ANSI JOIN, preservando OBS
  como relação opcional, com parse Oracle atual aprovado. Equivalência formal
  do controle legado permanece pendente; não homologar como 100% sem fixture.
REVISÃO (08/10/2026): GRUPO_MAQUINAS é único por (SETOR, GRUPO). Sem o SETOR, os grupos 0G020 e 0G021
  (existem no setor 4 e no setor 7) duplicavam as peças das máquinas TC066-TC067, TC076-TC077, TC082-TC083
  e TC088-TC089: a mesma peça aparecia também com QT_AGULHAS = 0. Junção corrigida por (SETOR, GRUPO).
  'Validada' no catálogo = guard SELECT-only + parse + execução limitada a 1 linha; NÃO é homologação da regra de negócio.
============================================================================= */

SELECT GPO.NUMERO_OB,
       (SELECT ART.CDARTIGOCRU FROM SGTPRD.ENGEITEMESTOARTCRU ART WHERE ART.CDREDUZIDO = GPP.CODIGO_REDUZIDO_PROD) ARTIGO,
       (SELECT MAX(OBF.CODIGO_COR_DESENHO) 
          FROM SGTPRD.OB_FASES OBF 
         WHERE OBF.CODIGO_FASE = 40 
           AND OBF.NUMERO_OB = GPO.NUMERO_OB) COR,
           
       (SELECT TRIM(TPF.DESCRICAO) 
          FROM SGTPRD.TIPO_FINALIDADE_FIO TPF 
         WHERE TPF.NUMERO_FINALIDADE = GPC.FINALIDADE) FINALIDADE, 
       GPP.LOTE_PRODUTO,
       
       (SELECT LISTAGG(TRIM(LFP.LOTE_FIO), ', ') WITHIN GROUP (ORDER BY TRIM(LFP.LOTE_FIO))
          FROM SGTPRD.LOTES_FIO_PRODUTO LFP 
         WHERE LFP.LOTE_PRODUTO_CRU = GPP.LOTE_PRODUTO) LOTE_FIO,
          
       GPR.NUMERO_MAQUINA, 
       GRP.NUMERO_AGULHAS_CILIN QT_AGULHAS,
       COUNT(GPP.IDPECASPRODUTO) QT_PC,
       SUM(GPP.QTLIQUIDA) QT_LIQUIDA,
       (SELECT OBP.TOTAL_PECAS_CONFIRM FROM SGTPRD.OB_PRODUTO OBP WHERE OBP.NUMERO_OB = GPO.NUMERO_OB) QT_PC_OB,
       TRIM(OBS.TEXTO) OBSERVACAO_OB
       
  FROM SGTPRD.GERAPECAORIGEMOB  GPO
  JOIN SGTPRD.GERAPECASPRODUTO  GPP
    ON GPO.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  JOIN SGTPRD.GERAPECACOMPLPECA GPC
    ON GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  JOIN SGTPRD.GERAPECACRU       GPR
    ON GPR.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  JOIN (
       SELECT MQ.NUMERO_MAQUINA,
              GRM.NUMERO_AGULHAS_CILIN,
              GRM.NUMERO_AGULHAS_DISCO
         FROM SGTPRD.MAQUINA MQ
         JOIN SGTPRD.GRUPO_MAQUINAS GRM ON GRM.SETOR = MQ.SETOR AND GRM.GRUPO = MQ.GRUPO
        WHERE MQ.TIPO_MAQUINA = 145
          AND MQ.CODIGO_UNIDADE_FABRI = '00005'
        GROUP BY MQ.NUMERO_MAQUINA,
                 GRM.NUMERO_AGULHAS_CILIN,
                 GRM.NUMERO_AGULHAS_DISCO
       ) GRP
    ON GPR.NUMERO_MAQUINA = GRP.NUMERO_MAQUINA
  JOIN SGTPRD.OB                OBE
    ON OBE.NUMERO_OB = GPO.NUMERO_OB
  LEFT JOIN SGTPRD.OBSERVACAO   OBS
    ON OBS.CODIGO = OBE.CODIGO_OBSERVACAO
 WHERE 1 = 1
   --AND GPP.PADRAO_QUALIDADE_SIN = 1
   --AND OBE.Codigo_Reduzido_Cru = 32
   --AND GPO.NUMERO_OB IN (SELECT O.NUMERO_OB FROM SGTPRD.OB O WHERE O.STATUS <> 0 AND O.TIPO_ORDEM = 0)
   --AND GPO.NUMERO_OB IN (SELECT FAS.NUMERO_OB FROM SGTPRD.OB_FASES FAS WHERE FAS.CODIGO_FASE IN (10,20,40) AND FAS.STATUS <> 4)
   --AND GPP.CODIGO_REDUZIDO_PROD IN (1563,1655,48,47,11852,42)
   AND GPO.NUMERO_OB IN (97199)
   --AND GPR.NUMERO_MAQUINA = '00000TC071'
   --AND GPP.LOTE_PRODUTO = '0100023121'
   
 GROUP BY GPO.NUMERO_OB, GPP.LOTE_PRODUTO, GPR.NUMERO_MAQUINA, GRP.NUMERO_AGULHAS_CILIN, GPC.FINALIDADE, GPP.CODIGO_REDUZIDO_PROD, OBS.TEXTO
 
 --HAVING COUNT(GPR.NUMERO_MAQUINA) > 1
 
 ORDER BY GPO.NUMERO_OB, GPP.LOTE_PRODUTO, GRP.NUMERO_AGULHAS_CILIN, GPR.NUMERO_MAQUINA, GPC.FINALIDADE
