/* =============================================================================
OBJETIVO: Produção e Eficiência da Malharia (Engenharia) por grupo de máquinas
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: Comandos SQL - CR\Produção e Eficiência da Malharia (Engenharia) por grupo de máquinas.sql
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENG_AGRUPAITENSESTOQ, SGTPRD.ENG_PRODG_CRU, SGTPRD.FICHA_MALHA, SGTPRD.FICHA_RETILINEA, SGTPRD.FIOS_FICHA_MALHARIA_, SGTPRD.ITENS_COMPLEMENTO, SGTPRD.ITENS_COMPLEMENTO_FI
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

WITH FICHA_MALHA_PRO AS (
    SELECT
        FMA.CODPROREDUZIDO AS CODIGO_REDUZIDO,
        FMA.GRUPO AS GRUPO,
        FMA.PRIORIDADE,
        ROUND(SUM(453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                  FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE, 0), 0, 0.00001, ICF.TITULO_FIO_NE) * 
                  DECODE(NVL(FFI.INDIESTITITULO, 0), 0, 1, FFI.INDIESTITITULO))), 2) AS PESO_FIO_VOLTA,
        ROUND(SUM((453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                   FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE, 0), 0, 0.00001, ICF.TITULO_FIO_NE) * 
                   DECODE(NVL(FFI.INDIESTITITULO, 0), 0, 1, FFI.INDIESTITITULO)) * 
                   DECODE(NVL(FFI.NUMERO_CABOS, 0), 0, 1, FFI.NUMERO_CABOS)) * FMA.RPM * 60 / 1000), 2) AS KG_HORA,
        ROUND(SUM((453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 *
                   FFI.CONES / (DECODE(NVL(ICF.TITULO_FIO_NE, 0), 0, 0.00001, ICF.TITULO_FIO_NE) * 
                   DECODE(NVL(FFI.INDIESTITITULO, 0), 0, 1, FFI.INDIESTITITULO)) * 
                   DECODE(NVL(FFI.NUMERO_CABOS, 0), 0, 1, FFI.NUMERO_CABOS)) * FMA.RPM * 60 * 
                   (FMA.PERCPRODUCAOPREVISTO / 100) / 1000), 2) AS KG_HORA_EFIC
    FROM
        SGTPRD.FICHA_MALHA FMA
        LEFT JOIN SGTPRD.FIOS_FICHA_MALHARIA_ FFI ON FFI.GRUPO_MAQUINA = FMA.GRUPO
        AND FFI.CODIGO_PRODUTO = FMA.CODPROREDUZIDO
        LEFT JOIN SGTPRD.ITENS_COMPLEMENTO_FI ICF ON ICF.CODIGO_REDUZIDO = FFI.CODIGO_FIO
    GROUP BY
        FMA.CODPROREDUZIDO,
        FMA.GRUPO,
        FMA.PRIORIDADE
),

FICHA_RETILINEA_PRO AS (
    SELECT
        FMA.CODIGO_PRODUTO AS CODIGO_REDUZIDO,
        FMA.GRUPO_MAQUINA AS GRUPO,
        FMA.PRIORIDADE,
        0 AS PESO_FIO_VOLTA,
        ROUND((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60) /
              ((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS) * 1000), 2) AS KG_HORA,
        ROUND(((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60) /
               ((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS) * 1000)), 2) * (FMA.EFICIENCIA_ESTIMADA / 100) AS KG_HORA_EFIC
    FROM
        SGTPRD.FICHA_RETILINEA FMA
        LEFT JOIN SGTPRD.ITENS_COMPLEMENTO ICO ON ICO.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO
        LEFT JOIN SGTPRD.ENG_AGRUPAITENSESTOQ EAI ON EAI.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO
        LEFT JOIN SGTPRD.ENG_PRODG_CRU EPC ON EPC.REDUZIDO_AGRUPADOR = EAI.REDUZIDO_AGRUPADOR
)

SELECT
    CODIGO_REDUZIDO,
    GRUPO,
    PRIORIDADE,
    PESO_FIO_VOLTA,
    KG_HORA,
    KG_HORA_EFIC
FROM FICHA_MALHA_PRO
UNION ALL
SELECT
    CODIGO_REDUZIDO,
    GRUPO,
    PRIORIDADE,
    PESO_FIO_VOLTA,
    KG_HORA,
    KG_HORA_EFIC
FROM FICHA_RETILINEA_PRO;
