/* =============================================================================
OBJETIVO: OB_s com finalidade, lotes ou teares misturados
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: (referência histórica) arquivo de origem fora deste repositório, não versionado aqui.
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTOCOR, SGTPRD.FASES_FLUXO, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.GRUPO_MAQUINAS, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OBSERVACAO, SGTPRD.OB_FASES, SGTPRD.OPERADOR
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views. Execução somente leitura salvo se DML restrito.
============================================================================= */

-- TP_ORDEM: rótulos de saída. OB_FASES.DESTINO_RECEITA é numérico; o cadastro do ERP
--   (SGTPRD.DESTINO) define: 1 PRODUCAO, 2 REPROCESSOS FORA DE COR, 3 LIMPEZA DE MAQUINA,
--   4 REPROCESSOS PARA RECLASSIFICACAO, 10 CONSUMO. Valores distintos em OB_FASES, lidos em
--   08/10/2026: 0, 1, 2, 3, 4 e 10. O valor 0 não existe no cadastro: 0 e NULO (via NVL) saem como
--   'Sem destino cadastrado'; qualquer outro valor sai como 'Não mapeado'.
--   REVISÃO (08/10/2026): antes, 3 e 10 caíam em 0 e os rótulos tinham grafia errada ('Produo',
--   'Reclassificao'). Medido em 08/10/2026: a consulta retorna 27 linhas, todas com DESTINO = 1
--   (rótulo 'Produção'); a mudança de TP_ORDEM nessas linhas é só a grafia.
--   REVISÃO (09/10/2026): OB sem nenhuma linha em OB_FASES não entra em TP_ORDEM_CTE e saía com
--   TP_ORDEM NULL (LEFT JOIN). O SELECT final agora usa NVL(TP.TP_ORDEM, 'Sem destino cadastrado'),
--   o mesmo rótulo de destino 0. Medido em 09/10/2026 (04:37): 140 OBs no universo desta consulta,
--   0 sem linha em OB_FASES; a saída (23 linhas) não muda.
--   REVISÃO (08/10/2026), GRP: a subconsulta GRP juntava GRUPO_MAQUINAS só por GRUPO. A chave é (SETOR, GRUPO),
--   e os grupos 0G020 e 0G021 existem nos setores 4 e 7. Join corrigido com GRM.SETOR = MQ.SETOR
--   (GRP 95 -> 87 linhas). Medido: a saída final (27 linhas) não muda.
--   ATENÇÃO: outras consultas do acervo (ex.: bnf_maiores_producoes_tingimento.sql) leem o mesmo
--   OB_FASES.DESTINO_RECEITA e tratam 0 e NULO (sem linha em SGTPRD.DESTINO) como Produção Normal, via
--   NVL(GDX.TIPO_DESTINO, 0). Esta consulta rotula 0 e NULO como 'Sem destino cadastrado'. Divergência
--   pendente de decisão (REGRAS_NEGOCIO.md, seção 4, item 10).
WITH TP_ORDEM_CTE AS (
    SELECT 
        OBFXX.NUMERO_OB,
        DECODE(NVL(MAX(OBFXX.DESTINO_RECEITA), 0),
               0, 'Sem destino cadastrado',
               1, 'Produção',
               2, 'Reprocesso',
               3, 'Limpeza de máquina',
               4, 'Reclassificação',
               10, 'Consumo',
               'Não mapeado') AS TP_ORDEM
    FROM SGTPRD.OB_FASES OBFXX
    GROUP BY OBFXX.NUMERO_OB
),
ARTIGO_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        ART.CDARTIGOCRU AS ARTIGO
    FROM SGTPRD.OB OBE
    JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = OBE.CODIGO_REDUZIDO_CRU
),
COR_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        COALESCE(
            (SELECT 
                TRIM(MAX(OBZ.CODIGO_COR_DESENHO))
             FROM SGTPRD.OB_FASES OBZ
             WHERE OBZ.NUMERO_OB = OBE.NUMERO_OB
             AND OBZ.CODIGO_FASE = 40
             GROUP BY OBZ.NUMERO_OB),
            (SELECT
                TRIM(COR.CDCOR)
             FROM SGTPRD.ENGEITEMESTOCOR COR
             WHERE COR.CDREDUZIDO = OBE.CODIGO_REDUZIDO)
        ) AS COR
    FROM SGTPRD.OB OBE
),
FASE_ATUAL_CTE AS (
    SELECT 
        OBF.NUMERO_OB,
        MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS FASE_ATUAL,
        DECODE(MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA),
               0, 'PROGRAMADA',
               1, 'EMITIDA',
               2, 'PESADA',
               3, 'EM EXECUÇÃO') AS ST_FASE
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    WHERE OBF.STATUS <> 4
    GROUP BY OBF.NUMERO_OB
),
OPERADOR_CTE AS (
    SELECT 
        OBF.NUMERO_OB,
        LISTAGG(TRIM(OPE.NOME), ', ') WITHIN GROUP (ORDER BY TRIM(OPE.NOME)) AS OPERADOR,
        MIN(DATE '1996-01-01' + OBF.TEMPO_FINAL_CONFIRMA / 1440) AS HORARIO_CONFIRMADO
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.OPERADOR OPE ON OPE.CODIGO = OBF.OPERADOR_FINAL
    WHERE OBF.CODIGO_FASE = 10
    GROUP BY OBF.NUMERO_OB
),
ANALISE_CTE AS (
    SELECT 
        GPO.NUMERO_OB,
        GPP.CODIGO_REDUZIDO_PROD,
        CASE
            WHEN COUNT(DISTINCT GPC.FINALIDADE) > 1 THEN 1
            ELSE 0
        END AS FINALIDADE,
        CASE
            WHEN COUNT(DISTINCT GPP.LOTE_PRODUTO) > 1 THEN 1
            ELSE 0
        END AS LOTE_PRODUTO,
        CASE
            WHEN COUNT(DISTINCT GRP.FABRICANTE_MODELO) > 1 OR COUNT(DISTINCT GRP.NUMERO_AGULHAS_CILIN) > 1 THEN 1
            ELSE 0
        END AS TEARES_SIMILARES,
        
        /*CASE
            WHEN COUNT(DISTINCT GRP.FABRICANTE_MODELO) > 1 THEN 1
            ELSE 0
        END AS TEARES_SIMILARES,
        */
        CASE
            WHEN COUNT(DISTINCT GPR.NUMERO_MAQUINA) > 1 THEN 1
            ELSE 0
        END AS TEARES_UNICOS
    FROM SGTPRD.GERAPECAORIGEMOB GPO
    JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPC.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN SGTPRD.OB OB ON GPO.NUMERO_OB = OB.NUMERO_OB
    JOIN SGTPRD.GERAPECACRU GPR ON GPR.IDPECASPRODUTO = GPO.IDPECASPRODUTO
    JOIN (
        SELECT 
            MQ.NUMERO_MAQUINA,
            GRM.NUMERO_AGULHAS_CILIN,
            GRM.NUMERO_AGULHAS_DISCO,
            TRIM(MQ.FABRICANTE)||' - '||TRIM(MQ.MODELO) FABRICANTE_MODELO
        FROM SGTPRD.MAQUINA MQ
        JOIN SGTPRD.GRUPO_MAQUINAS GRM ON MQ.GRUPO = GRM.GRUPO AND GRM.SETOR = MQ.SETOR
        WHERE MQ.TIPO_MAQUINA = 145
        AND MQ.CODIGO_UNIDADE_FABRI = '00005'
        GROUP BY MQ.NUMERO_MAQUINA, GRM.NUMERO_AGULHAS_CILIN, GRM.NUMERO_AGULHAS_DISCO, TRIM(MQ.FABRICANTE)||' - '||TRIM(MQ.MODELO)
    ) GRP ON GPR.NUMERO_MAQUINA = GRP.NUMERO_MAQUINA
    WHERE GPP.TIDOCUMENTOENTRADA <> 8
    AND GPP.PADRAO_QUALIDADE_SIN = 1
    GROUP BY GPO.NUMERO_OB, GPP.CODIGO_REDUZIDO_PROD
),
OBE_CTE AS (
    SELECT 
        OBE.NUMERO_OB,
        OBE.CODIGO_REDUZIDO,
        OBE.CODIGO_REDUZIDO_CRU,
        OBE.STATUS,
        OBE.TIPO_ORDEM,
        OBS.TEXTO AS OBSERVACAO_OB
    FROM SGTPRD.OB OBE
    LEFT JOIN SGTPRD.OBSERVACAO OBS ON OBS.CODIGO = OBE.CODIGO_OBSERVACAO
    WHERE OBE.STATUS <> 0
    AND OBE.TIPO_ORDEM = 0
    AND OBE.CODIGO_REDUZIDO IN (SELECT ENG.CDREDUZIDO FROM SGTPRD.ENGEITEMESTOCOR ENG WHERE TRIM(ENG.CDCOR) <> '99999')
    AND OBE.CODIGO_REDUZIDO_CRU IN (1563, 1655, 48, 47, 11852,152)
)
SELECT
    OBE.NUMERO_OB,
    NVL(TP.TP_ORDEM, 'Sem destino cadastrado') AS TP_ORDEM,
    ART.ARTIGO,
    COR.COR,
    A.FINALIDADE,
    A.LOTE_PRODUTO,
    A.TEARES_SIMILARES,
    A.TEARES_UNICOS,
    FASE.FASE_ATUAL,
    FASE.ST_FASE,
    OPE.OPERADOR,
    OPE.HORARIO_CONFIRMADO,
    OBE.OBSERVACAO_OB
FROM OBE_CTE OBE
LEFT JOIN TP_ORDEM_CTE TP ON TP.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN ARTIGO_CTE ART ON ART.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN COR_CTE COR ON COR.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN FASE_ATUAL_CTE FASE ON FASE.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN OPERADOR_CTE OPE ON OPE.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN ANALISE_CTE A ON A.NUMERO_OB = OBE.NUMERO_OB
WHERE (A.LOTE_PRODUTO + A.TEARES_SIMILARES) <> 0
ORDER BY OPE.HORARIO_CONFIRMADO
