/* =============================================================================
OBJETIVO: Estoque de malha crua agrupado por número de agulhas do tear
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: 03_malharia_teares/mal_estoque_agrupado_por_tear_e_lote_produto.sql (Query #3)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECASPRODUTO, SGTPRD.GRUPO_MAQUINAS, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

WITH BASE AS (
    SELECT GPM.NUMERO_AGULHAS_CILIN AS AGULHAS_TEAR,
           GPP.IDPECASPRODUTO,
           LTRIM(GCR.NUMERO_MAQUINA, 0) AS TEAR
      FROM SGTPRD.GERAPECASPRODUTO GPP
      JOIN SGTPRD.GERAPECACOMPLPECA GPC
        ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECACRU GCR
        ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
      JOIN SGTPRD.MAQUINA MQ
        ON MQ.NUMERO_MAQUINA = GCR.NUMERO_MAQUINA
      JOIN SGTPRD.GRUPO_MAQUINAS GPM
        ON GPM.GRUPO = MQ.GRUPO
      JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF
        ON GPC.FINALIDADE = TFF.NUMERO_FINALIDADE
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
     WHERE GPP.CODIGO_REGISTRO = 1
       AND GPP.STPECAPRODUTO IN (0, 16, 18)
       AND GPP.IDPESSOAFJESTOQUE = 2
       AND GPP.PADRAO_QUALIDADE_SIN = 1
       AND GPP.CODIGO_DEPOSITO = 95
       AND GPC.FINALIDADE = 1
       AND GPP.TIDOCUMENTOENTRADA <> 8
       AND ITE.CODIGO_REDUZIDO = 133
), TEARES AS (
    SELECT AGULHAS_TEAR,
           LISTAGG(TEAR, ', ') WITHIN GROUP (ORDER BY TEAR) AS TEAR
      FROM (SELECT DISTINCT AGULHAS_TEAR, TEAR FROM BASE)
     GROUP BY AGULHAS_TEAR
)
SELECT B.AGULHAS_TEAR,
       COUNT(B.IDPECASPRODUTO) AS PEAS,
       T.TEAR
  FROM BASE B
  JOIN TEARES T ON T.AGULHAS_TEAR = B.AGULHAS_TEAR
 GROUP BY B.AGULHAS_TEAR, T.TEAR
 ORDER BY B.AGULHAS_TEAR;
