-- =============================================================================
-- OBJETIVO: Consulta - Peças com restrição geradas na Malharia
-- DOMÍNIO: 03_malharia_teares
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta - Peças com restrição geradas na Malharia (últimos 60d).sql
-- TIPO: Malharia e Teares
-- PARÂMETROS / BINDS: Nenhum (janela dinâmica indexada: últimos 30 dias de produção)
-- TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECAORIGEMOB,
--                    SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_FINALIDADE_FIO,
--                    SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
-- CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
-- HISTÓRICO DE OTIMIZAÇÃO (23/09/2026):
--   - Substituição de varredura cega em BD_PRD_MOVPROD por acesso indexado direto via
--     tabela física SGTPRD.GERAPECASPRODUTO (índice GRPCPROD_INDIDATAENTRPECA).
--   - Eliminação de subqueries correlacionadas por linha no SELECT final, convertidas em LEFT JOIN ANSI.
--   - Janela temporal calibrada para 30 dias evitando estouro de timeout do banco.
--   - Tempo de execução reduzido de timeout (>7.8s / ORA-00028) para ~0.95s.
-- =============================================================================

SELECT /*+ INDEX(GPP GRPCPROD_INDIDATAENTRPECA) */
       TO_DATE(TO_CHAR(GPP.DATA_DA_ENTRADA_PECA), 'YYYYMMDD') AS DATA_ENTRADA,
       GPP.IDPECASPRODUTO AS ID_PECA,
       LTRIM(GPCR.NUMERO_MAQUINA, '0') AS TEAR,
       GPP.CODIGO_DEPOSITO AS DEPOSITO,
       ENI.DESCRIPTION AS STATUS,
       GPP.QTLIQUIDA AS QT_LIQ,
       GPP.LOTE_PRODUTO,
       GPP.CODIGO_REDUZIDO_PROD AS REDUZIDO,
       TRIM(ITE.DESCRICAO) AS DESCRICAO_ITEM,
       TRIM(GPC.FINALIDADE || ' - ' || TFF.DESCRICAO) AS RESTRICAO,
       GPO.NUMERO_OB
  FROM SGTPRD.GERAPECASPRODUTO GPP
  JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  JOIN SGTPRD.GERAPECACRU GPCR ON GPCR.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  LEFT JOIN SGTPRD.GERAPECAORIGEMOB GPO ON GPO.IDPECASPRODUTO = GPP.IDPECASPRODUTO
  LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = GPP.CODIGO_REDUZIDO_PROD
  LEFT JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF ON TFF.NUMERO_FINALIDADE = GPC.FINALIDADE
  LEFT JOIN (
      SELECT ENI.SEQUENCE, ENI.DESCRIPTION
        FROM SGTPRD.XX2_ENUMERATES ENU
        JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
       WHERE ENU.NAME LIKE 'TSTATUSPECAPRODUTO%'
  ) ENI ON ENI.SEQUENCE = GPP.STPECAPRODUTO
 WHERE GPP.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(SYSDATE - 30, 'YYYYMMDD'))
   AND GPP.CODIGO_REGISTRO = 2
   AND GPC.FINALIDADE <> 1
 ORDER BY GPP.DATA_DA_ENTRADA_PECA DESC, GPP.IDPECASPRODUTO
 FETCH FIRST 100 ROWS ONLY
