/* =============================================================================
OBJETIVO: Necessidade Malharia (Somente Faltas)
DOMÍNIO: 03_malharia_teares
ARQUIVO ORIGINAL: Comandos SQL - CR\Necessidade Malharia (Somente Faltas).sql
TIPO: Malharia e Teares
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENG_PRODG_ACABADO, SGTPRD.ENG_PRODG_CRU, SGTPRD.FICHA_MALHA, SGTPRD.FICHA_RETILINEA, SGTPRD.FIOS_FICHA_MALHARIA_, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_COMPLEMENTO_FI, SGTPRD.ITENS_ESTOQUE, SGTPRD.MAQUINA, SGTPRD.OB, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ORDEM_PRODUCAO_MALHA, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.PESO_PADRAO_PECA
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. 100% nativa sem views.
============================================================================= */

WITH
OPM_REL AS (
    SELECT M.NUMERO_MAQUINA,
           COALESCE(
               MIN(CASE WHEN O.STATUS = 3 THEN O.NUMERO_ORDEM END),
               MIN(CASE WHEN O.STATUS = 1 THEN O.NUMERO_ORDEM END),
               MIN(CASE WHEN O.STATUS = 2 THEN O.NUMERO_ORDEM END)
           ) AS NUMERO_ORDEM
      FROM SGTPRD.MAQUINA M
      LEFT JOIN SGTPRD.ORDEM_PRODUCAO_MALHA O
        ON O.NUMERO_MAQUINA = M.NUMERO_MAQUINA
       AND O.STATUS IN (1, 2, 3)
     WHERE M.SETOR IN (4, 7)
       AND M.CODIGO_UNIDADE_FABRI = '00005'
       AND M.TIPO_MAQUINA IN (145, 146)
     GROUP BY M.NUMERO_MAQUINA
),
-- CTE 0: VARIÁVEIS DE CÁLCULO DIAS
VARIAVEIS_CALCULO AS (
    SELECT
        CASE
            WHEN MOD(TO_NUMBER(TO_CHAR(SYSDATE, 'IW')), 2) = 1 THEN 5 + (6.5 / 24)
            ELSE 5 + (6.5 / 24) + ((8.5 * 2) / 24)
        END AS FATOR_DIAS_PRODUCAO
    FROM DUAL
),

-- CTE 1: PESO PADRÃO
PESO_PADRAO_CTE AS (
    SELECT
        ART.CDREDUZIDO AS REDUZIDO, ART.CDARTIGOCRU AS ARTIGO,
        COALESCE(AVG(BASE.PESO_PADRAO), 0) AS PESO_PADRAO
    FROM (
        SELECT ART.CDARTIGOCRU AS ARTIGO, PCR.PESO_METROS_PECA AS PESO_PADRAO FROM SGTPRD.PESO_PADRAO_PECA PCR JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = PCR.CODIGO_REDUZIDO_PROD
        UNION ALL
        SELECT ART.CDARTIGOCRU AS ARTIGO, PAC.VLPESO_METROS_PECA AS PESO_PADRAO FROM SGTPRD.ENG_PRODG_ACABADO PAC JOIN SGTPRD.ITENS_ESTOQUE AGR ON AGR.REDUZIDO_AGRUPADOR = PAC.REDUZIDO_AGRUPADOR JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = AGR.CODIGO_REDUZIDO
    ) BASE JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDARTIGOCRU = BASE.ARTIGO
    GROUP BY ART.CDREDUZIDO, ART.CDARTIGOCRU
),

-- CTE 2: FILTRO DE PEDIDOS
PDC_SUB AS (
    SELECT
        PED.CD_SUBTIPOPED AS TIPOPEDIDO, PED.PEDIDOCLIENTE AS P_CLIENTE, PPOB.NUMEROOB AS NR_OB
    FROM SGTPRD.OFPEDIDO OFP
    JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON OFP.IDITENSPEDIDOQTDES = IPQ.IDITENSPEDIDOQTDES JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROOF = OFP.NUMEROOF JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
    JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMERO = PP.NUMERO JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
),

-- CTE 3: DEMANDA
OB_ABERTO AS (
    SELECT
        OB.CODIGO_REDUZIDO_CRU AS REDUZ_DESC, E.CDARTIGOCRU AS ARTIGO,
        CASE WHEN COALESCE(PP.PESO_PADRAO, 0) = 0 THEN 0 ELSE ROUND(COALESCE(SUM(OBP.KILOS_PROGRAMADOS), 0) / PP.PESO_PADRAO, 0) END AS QTD_PECAS
    FROM SGTPRD.OB OB
    LEFT JOIN SGTPRD.ENGEITEMESTOARTCRU E ON E.CDREDUZIDO = OB.CODIGO_REDUZIDO 
    LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OB.NUMERO_OB
    LEFT JOIN PESO_PADRAO_CTE PP ON PP.REDUZIDO = OB.CODIGO_REDUZIDO_CRU
    LEFT JOIN PDC_SUB PDC ON PDC.NR_OB = OB.NUMERO_OB
    WHERE OB.STATUS <> 0 
      AND NOT EXISTS (
          SELECT 1 
            FROM SGTPRD.PEDPRODUCAOOB POB 
           WHERE POB.NUMEROOB = OB.NUMERO_OB 
             AND POB.SETOR = 5 
             AND POB.OBMONTADA = 1
      )
      AND COALESCE(PDC.TIPOPEDIDO, 0) NOT IN (2, 3)
      AND (PDC.P_CLIENTE IS NULL OR (TRIM(PDC.P_CLIENTE) NOT LIKE '%T' AND TRIM(PDC.P_CLIENTE) NOT LIKE '%S' AND TRIM(PDC.P_CLIENTE) NOT LIKE '%R'))
    GROUP BY E.CDARTIGOCRU, OB.CODIGO_REDUZIDO_CRU, PP.PESO_PADRAO
),

-- CTE 4: ESTOQUE UNIFICADO
ESTOQUE_UNIFICADO_CTE AS (
    SELECT
        GPP.CODIGO_REDUZIDO_PROD AS REDUZ,
        COUNT(CASE WHEN GPP.CODIGO_DEPOSITO = 95 THEN GPP.IDPECASPRODUTO END) AS QTD_PECAS_TINTURARIA,
        COUNT(CASE WHEN GPP.CODIGO_DEPOSITO = 90 THEN GPP.IDPECASPRODUTO END) AS QTD_PECAS_MALHARIA
    FROM SGTPRD.GERAPECASPRODUTO GPP
    JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
    WHERE GPP.CODIGO_REGISTRO = 1
      AND GPP.STPECAPRODUTO IN (0, 16, 18)
      AND GPP.IDPESSOAFJESTOQUE = 2
      AND GPP.PADRAO_QUALIDADE_SIN = 1
      AND GPP.CODIGO_DEPOSITO IN (90, 95)
      AND GPC.FINALIDADE IN (1, 8)
      AND GPP.TIDOCUMENTOENTRADA <> 8
    GROUP BY GPP.CODIGO_REDUZIDO_PROD
),

-- CTEs 5 & 6: CAPACIDADE DE PRODUÇÃO
PRODUCAO_CALC AS (
    SELECT FMA.CODPROREDUZIDO AS CODIGO_REDUZIDO, FMA.GRUPO, SUM((453.6 / 768.096 * (FFI.AGULHAS * FFI.PONTOS_GRAMA_RAPORT) / 100 * FFI.CONES / (COALESCE(NULLIF(ICF.TITULO_FIO_NE, 0), 1) * COALESCE(NULLIF(FFI.INDIESTITITULO, 0), 1)) * COALESCE(NULLIF(FFI.NUMERO_CABOS, 0), 1)) * FMA.RPM * 60 * (FMA.PERCPRODUCAOPREVISTO / 100) / 1000) AS KG_HORA_EFIC
    FROM SGTPRD.FICHA_MALHA FMA JOIN SGTPRD.FIOS_FICHA_MALHARIA_ FFI ON FFI.GRUPO_MAQUINA = FMA.GRUPO AND FFI.CODIGO_PRODUTO = FMA.CODPROREDUZIDO LEFT JOIN SGTPRD.ITENS_COMPLEMENTO_FI ICF ON ICF.CODIGO_REDUZIDO = FFI.CODIGO_FIO
    GROUP BY FMA.CODPROREDUZIDO, FMA.GRUPO
    UNION ALL
    SELECT FMA.CODIGO_PRODUTO AS CODIGO_REDUZIDO, FMA.GRUPO_MAQUINA AS GRUPO, ROUND(((FMA.PASSADAS_MINUTO * FMA.QUANTIDADE_CARROS * FMA.NUMERO_PISTAS * EPC.PESO_PECA * 60) / COALESCE(NULLIF((FMA.NUMERO_PASSADAS + FMA.NRPASSADAS_VAZIAS) * 1000, 0), 1)) * (FMA.EFICIENCIA_ESTIMADA / 100), 2) AS KG_HORA_EFIC
    FROM SGTPRD.FICHA_RETILINEA FMA JOIN SGTPRD.ITENS_ESTOQUE EAI ON EAI.CODIGO_REDUZIDO = FMA.CODIGO_PRODUTO JOIN SGTPRD.ENG_PRODG_CRU EPC ON EPC.REDUZIDO_AGRUPADOR = EAI.REDUZIDO_AGRUPADOR
),
PROD_CAPACIDADE AS (
    SELECT OPM.CODIGO_REDUZIDO_PROD AS CD_REDUZIDO, ROUND(COALESCE(SUM(PRO.KG_HORA_EFIC), 0) * 24, 2) AS KG_DIA_EFIC, COUNT(OPM.NUMERO_ORDEM) AS QTD_ORDENS
    FROM SGTPRD.ORDEM_PRODUCAO_MALHA OPM JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = OPM.NUMERO_MAQUINA
    LEFT JOIN PRODUCAO_CALC PRO ON PRO.CODIGO_REDUZIDO = OPM.CODIGO_REDUZIDO_PROD AND PRO.GRUPO = MAQ.GRUPO
    WHERE OPM.STATUS <> 0 AND EXISTS (SELECT 1 FROM OPM_REL R WHERE R.NUMERO_ORDEM = OPM.NUMERO_ORDEM)
    GROUP BY OPM.CODIGO_REDUZIDO_PROD
),

-- CTE 7: CONSOLIDADO
DADOS_CONSOLIDADOS AS (
    SELECT
        ITE.CODIGO_REDUZIDO, ITE.CODIGO, TRIM(ITE.DESCRICAO) AS DESCRICAO_PRODUTO,
        OB.ARTIGO,
        COALESCE(OB.QTD_PECAS, 0) AS QT_PC_PROGRAMADA,
        COALESCE(EST.QTD_PECAS_TINTURARIA, 0) AS QT_PC_TINTURARIA_ORIGINAL,
        COALESCE(EST.QTD_PECAS_MALHARIA, 0) AS QT_PC_MALHARIA_ORIGINAL,
        PROD.KG_DIA_EFIC, PROD.QTD_ORDENS, PPP.PESO_PADRAO,
        VC.FATOR_DIAS_PRODUCAO,
        SUM(COALESCE(OB.QTD_PECAS, 0)) OVER (PARTITION BY ITE.CODIGO_REDUZIDO) as TOTAL_DEMANDA_PRODUTO,
        MIN(COALESCE(OB.QTD_PECAS, 0)) OVER (PARTITION BY ITE.CODIGO_REDUZIDO) as MIN_DEMANDA_PRODUTO,
        COUNT(*) OVER (PARTITION BY ITE.CODIGO_REDUZIDO) as CONTAGEM_ARTIGOS_PRODUTO,
        ROW_NUMBER() OVER (PARTITION BY ITE.CODIGO_REDUZIDO ORDER BY COALESCE(OB.QTD_PECAS, 0) DESC) as RN_PRINCIPAL
    FROM SGTPRD.ITENS_ESTOQUE ITE
    CROSS JOIN VARIAVEIS_CALCULO VC
    LEFT JOIN OB_ABERTO OB ON OB.REDUZ_DESC = ITE.CODIGO_REDUZIDO
    LEFT JOIN ESTOQUE_UNIFICADO_CTE EST ON EST.REDUZ = ITE.CODIGO_REDUZIDO
    LEFT JOIN PROD_CAPACIDADE PROD ON PROD.CD_REDUZIDO = ITE.CODIGO_REDUZIDO
    LEFT JOIN PESO_PADRAO_CTE PPP ON PPP.REDUZIDO = ITE.CODIGO_REDUZIDO
    WHERE COALESCE(OB.QTD_PECAS, 0) > 0
),

-- CTE 8: APLICAÇÃO DA LÓGICA DE NEGÓCIO
CALCULOS_FINAIS AS (
    SELECT
        D.*,
        -- Alocação de Estoque em Cascata e Priorizada
        CASE
            -- Cenário 1: Se o produto tem apenas um artigo, ele recebe todo o estoque da tinturaria.
            WHEN D.CONTAGEM_ARTIGOS_PRODUTO = 1 THEN D.QT_PC_TINTURARIA_ORIGINAL
            -- Cenário 2: Se este é o artigo com a MENOR demanda, aloca-se o mínimo entre sua demanda e o estoque.
            WHEN D.QT_PC_PROGRAMADA = D.MIN_DEMANDA_PRODUTO THEN LEAST(D.QT_PC_PROGRAMADA, D.QT_PC_TINTURARIA_ORIGINAL)
            -- Cenário 3: Para os demais artigos (maior demanda), aloca-se o que sobrou do estoque após atender o de menor demanda.
            ELSE GREATEST(0, D.QT_PC_TINTURARIA_ORIGINAL - D.MIN_DEMANDA_PRODUTO)
        END AS QT_PC_TINTURARIA_ALOCADO,
        CASE
            -- Cenário 1: Se o produto tem apenas um artigo, ele recebe todo o estoque da malharia.
            WHEN D.CONTAGEM_ARTIGOS_PRODUTO = 1 THEN D.QT_PC_MALHARIA_ORIGINAL
            -- Cenário 2: Se este é o artigo com a MENOR demanda, aloca-se o que for necessário da malharia após esgotar a tinturaria.
            WHEN D.QT_PC_PROGRAMADA = D.MIN_DEMANDA_PRODUTO THEN LEAST(GREATEST(0, D.QT_PC_PROGRAMADA - D.QT_PC_TINTURARIA_ORIGINAL), D.QT_PC_MALHARIA_ORIGINAL)
            -- Cenário 3: Para os demais artigos, aloca-se o que sobrou do estoque da malharia após atender o de menor demanda.
            ELSE GREATEST(0, D.QT_PC_MALHARIA_ORIGINAL - LEAST(GREATEST(0, D.MIN_DEMANDA_PRODUTO - D.QT_PC_TINTURARIA_ORIGINAL), D.QT_PC_MALHARIA_ORIGINAL))
        END AS QT_PC_MALHARIA_ALOCADO,
        -- Saldo Final do Produto
        (D.QT_PC_TINTURARIA_ORIGINAL + D.QT_PC_MALHARIA_ORIGINAL) - D.TOTAL_DEMANDA_PRODUTO AS SALDO_FINAL_PRODUTO
    FROM DADOS_CONSOLIDADOS D
)

-- CONSULTA FINAL
SELECT
    C.CODIGO_REDUZIDO AS REDUZIDO_CRU,
    TRIM(C.CODIGO) AS CODIGO_INDUSTRIAL,
    COALESCE(C.ARTIGO, SUBSTR(C.CODIGO, 4, 5)) AS CD_ARTIGO,
    C.DESCRICAO_PRODUTO,
    C.QT_PC_PROGRAMADA,
    C.QT_PC_TINTURARIA_ALOCADO AS QT_PC_TINTURARIA,
    LEAST(0, C.QT_PC_TINTURARIA_ALOCADO - C.QT_PC_PROGRAMADA) AS QT_PC_FALTA_TINTURARIA,
    C.QT_PC_MALHARIA_ALOCADO AS QT_PC_MALHARIA,
    LEAST(0, (C.QT_PC_TINTURARIA_ALOCADO + C.QT_PC_MALHARIA_ALOCADO) - C.QT_PC_PROGRAMADA) AS QT_PC_FALTA_MALHARIA,
    GREATEST(0, (C.QT_PC_TINTURARIA_ALOCADO + C.QT_PC_MALHARIA_ALOCADO) - C.QT_PC_PROGRAMADA) AS QT_PC_SOBRANDO,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN C.SALDO_FINAL_PRODUTO ELSE 0 END AS SALDO_FINAL,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN
        CASE WHEN COALESCE(C.KG_DIA_EFIC, 0) = 0 OR COALESCE(C.PESO_PADRAO, 0) = 0 THEN 0
             ELSE ROUND(GREATEST(0, C.TOTAL_DEMANDA_PRODUTO - (C.QT_PC_TINTURARIA_ORIGINAL + C.QT_PC_MALHARIA_ORIGINAL)) / COALESCE(NULLIF(C.KG_DIA_EFIC / C.PESO_PADRAO, 0), 1), 0)
        END
    ELSE 0 END AS DIAS_NEC_EFIC,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN TRUNC(COALESCE(C.KG_DIA_EFIC, 0) / COALESCE(NULLIF(C.PESO_PADRAO, 0), 1)) ELSE 0 END AS QT_PC_PROD_DIA,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN COALESCE(C.QTD_ORDENS, 0) ELSE 0 END AS QT_ORDENS_ABERTO,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN TRUNC(COALESCE(C.KG_DIA_EFIC, 0) / COALESCE(NULLIF(C.PESO_PADRAO, 0), 1) / COALESCE(NULLIF(C.QTD_ORDENS, 0), 1)) ELSE 0 END AS QT_PC_PROD_MAQUINA,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN ROUND(COALESCE(C.KG_DIA_EFIC, 0) / COALESCE(NULLIF(C.QTD_ORDENS, 0), 1), 2) ELSE 0 END AS QT_KG_PROD_DIA,
    C.FATOR_DIAS_PRODUCAO AS DIAS_TRABALHO,
    CASE WHEN C.RN_PRINCIPAL = 1 THEN TRUNC(C.FATOR_DIAS_PRODUCAO * COALESCE(C.KG_DIA_EFIC, 0) / COALESCE(NULLIF(C.PESO_PADRAO, 0), 1) + C.SALDO_FINAL_PRODUTO) ELSE 0 END AS QT_PC_PROGRAMAR
FROM CALCULOS_FINAIS C
ORDER BY CD_ARTIGO, REDUZIDO_CRU
