/* =============================================================================
OBJETIVO: Consulta de pedidos em atraso com OBs vinculadas e status de produção
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta Pedidos Atrasados.sql
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (filtros fixos por filial 1, tipos de pedido (1,2,3) e OBs ativas STATUS <> 0)
TABELAS PRINCIPAIS: SGTPRD.FASES_FLUXO, SGTPRD.GERAPECAORIGEMOB, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDODATAS, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.UNIDADE_MEDIDA, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO (22/09/2026): Eliminação de subqueries correlacionadas por linha e desmontagem de views legadas. O filtro OB.STATUS <> 0 na driving CTE restringe a varredura para as ~700 ordens em chão de fábrica. Redução de timeout para ~4.4s.
AUDITORIA (29/09/2026): removido o teto FETCH FIRST 100 ROWS ONLY. Em 29/09 a consulta devolve 669 linhas;
  com o teto a auditoria mostrava só 100 (14%) e escondia o resto sem aviso.
============================================================================= */

WITH PEDIDO_OB AS (
    SELECT /*+ MATERIALIZE */
           IPG.PEDIDO,
           IPG.ITEMPEDIDO,
           PPOB.NUMEROOB,
           TRIM(PED.PEDIDOCLIENTE) AS PEDIDOCLIENTE,
           OB.STATUS
      FROM SGTPRD.PEDIDOCOMERCIAL PED
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.PEDIDO = PED.PEDIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITEMPEDGRADE = IPG.IDITENSPEDIDOGRADE
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.IDITENSPEDIDOQTDES = IPQ.IDITENSPEDIDOQTDES
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROOF = OFP.NUMEROOF AND OFO.NIVEL = OFP.NIVEL AND OFO.REDUZIDO = OFP.REDUZIDO
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
      JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMERO = PP.NUMERO AND PPOB.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.OB OB ON OB.NUMERO_OB = PPOB.NUMEROOB
     WHERE PED.TIPOPEDIDO IN (1, 2, 3)
       AND PED.IDFILIALCOBRANCA = 1
       AND PED.PEDIDO <> 1649
       AND OB.STATUS <> 0
       AND OFP.QUANTIDADE_ATUAL <> 0
),
OB_ALVO AS (
    SELECT /*+ MATERIALIZE */ DISTINCT NUMEROOB
      FROM PEDIDO_OB
),
FASE_ATUAL AS (
    SELECT NUMERO_OB,
           CODIGO_FASE,
           DESCR_FASE,
           STATUS
      FROM (
            SELECT OBF.NUMERO_OB,
                   OBF.CODIGO_FASE,
                   FFL.DESCRICAO_FASE AS DESCR_FASE,
                   OBF.STATUS,
                   ROW_NUMBER() OVER (
                       PARTITION BY OBF.NUMERO_OB
                       ORDER BY OBF.SEQUENCIA
                   ) AS RN
              FROM SGTPRD.OB_FASES OBF
              JOIN SGTPRD.FASES_FLUXO FFL
                ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
              JOIN OB_ALVO ALV
                ON ALV.NUMEROOB = OBF.NUMERO_OB
             WHERE OBF.STATUS <> 4
           )
     WHERE RN = 1
),
STATUS_FASE AS (
    SELECT /*+ MATERIALIZE */ ENI.SEQUENCE AS STATUS,
           TRIM(ENI.DESCRIPTION) AS DESCRICAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI
        ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TOBFASESSTATUS%'
),
ORIGEM_OB AS (
    SELECT ORI.NUMERO_OB,
           SUM(NVL(GPP.QTLIQUIDA, 0)) AS ORIG_QTD
      FROM SGTPRD.GERAPECAORIGEMOB ORI
      JOIN SGTPRD.GERAPECASPRODUTO GPP
        ON GPP.IDPECASPRODUTO = ORI.IDPECASPRODUTO
      JOIN OB_ALVO ALV
        ON ALV.NUMEROOB = ORI.NUMERO_OB
     GROUP BY ORI.NUMERO_OB
),
ULTIMA_FASE AS (
     SELECT OBF.NUMERO_OB,
            MAX(TEMPO_FINAL_CONFIRMA) KEEP (DENSE_RANK LAST ORDER BY SEQUENCIA) AS TEMPO_FINAL_CONFIRMA
       FROM SGTPRD.OB_FASES OBF
       JOIN OB_ALVO ALV
         ON ALV.NUMEROOB = OBF.NUMERO_OB
      WHERE OBF.TEMPO_FINAL_CONFIRMA IS NOT NULL
      GROUP BY OBF.NUMERO_OB
),
OB_MONTADA AS (
    SELECT OBE.NUMERO_OB,
           NVL(ORG.ORIG_QTD, 0) AS ORIG_QTD,
           CASE WHEN UND.TPUNIDADEMEDIDA = 1
                THEN NVL(OBP.KILOS_PROGRAMADOS, 0)
                ELSE NVL(OBP.METROS_PROGRAMADOS, 0)
           END AS PROG_QTD,
           CASE WHEN OBE.TEMPO_INICIO_PRODUCA > 0
                THEN DATE '1996-01-01' + OBE.TEMPO_INICIO_PRODUCA / 1440
           END AS DATA_EMISSAO,
           CASE WHEN UF.TEMPO_FINAL_CONFIRMA IS NULL THEN NULL
                ELSE DATE '1996-01-01' + UF.TEMPO_FINAL_CONFIRMA / 1440
           END AS DATA_ULT_CONF
      FROM SGTPRD.OB OBE
      JOIN OB_ALVO ALV
        ON ALV.NUMEROOB = OBE.NUMERO_OB
      JOIN SGTPRD.OB_PRODUTO OBP
        ON OBP.NUMERO_OB = OBE.NUMERO_OB
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
      JOIN SGTPRD.UNIDADE_MEDIDA UND
        ON UND.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
      LEFT JOIN ORIGEM_OB ORG
        ON ORG.NUMERO_OB = OBE.NUMERO_OB
      LEFT JOIN ULTIMA_FASE UF
        ON UF.NUMERO_OB = OBE.NUMERO_OB
),
PLANO_RESUMO AS (
    SELECT PO.NUMEROOB,
           MIN(IPD.DTPROGRAMADOPARA) AS DATA_PLANO,
           MIN(IPC2.DATAEXPEDIREM) AS DATA_ENTREGA
      FROM PEDIDO_OB PO
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG
        ON IPG.PEDIDO = PO.PEDIDO
       AND IPG.ITEMPEDIDO = PO.ITEMPEDIDO
      LEFT JOIN SGTPRD.ITENSPEDIDODATAS IPD
        ON IPD.PEDIDO = PO.PEDIDO
       AND IPD.ITEMPEDIDO = PO.ITEMPEDIDO
      LEFT JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC2
        ON IPC2.PEDIDO = PO.PEDIDO
       AND IPC2.ITEMPEDIDO = PO.ITEMPEDIDO
     WHERE IPG.SITUACAOITEM = 1
     GROUP BY PO.NUMEROOB
)
SELECT PED.PEDIDOCLIENTE                                            AS P_CLIENTE,
       IPC.PEDIDO                                                   AS PEDIDO,
       IPC.ITEMPEDIDO                                               AS ITEM,
       CASE
         WHEN TRUNC(SYSDATE) - TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD') > 0
           THEN LPAD(TRUNC(SYSDATE) - TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD'), 2, '0') || ' DIA(S) ATRASADO'
         ELSE 'DENTRO DO PRAZO'
       END                                                          AS ANALISE_ENTREGA,
       TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD')                           AS DT_ENTREGA,
       OBP.NUMEROOB                                                 AS OB,
       SUBSTR(ITE.CODIGO, 6, 3)                                     AS ARTIGO,
       IPC.REDUZIDOITEM                                             AS REDUZ,
       TRIM(ITE.DESCRICAO)                                          AS DESCRICAO_ITEM,
       OBF.CODIGO_FASE                                              AS CD_FASE,
       OBF.DESCR_FASE                                               AS DESCRICAO_FASE,
       OBF.STATUS                                                   AS STATUS,
       SF.DESCRICAO                                                AS STATUS_FASE,
       OP.TOTAL_PECAS                                               AS PEAS,
       DECODE(OBM.ORIG_QTD, 0, OBM.PROG_QTD, OBM.ORIG_QTD)           AS PESO_KG,
       TRUNC(
           CASE WHEN NVL(OBM.DATA_ULT_CONF, OBM.DATA_EMISSAO) IS NULL THEN 0
                WHEN SYSDATE - NVL(OBM.DATA_ULT_CONF, OBM.DATA_EMISSAO) < 0 THEN 0
                ELSE SYSDATE - NVL(OBM.DATA_ULT_CONF, OBM.DATA_EMISSAO)
           END, 2)                                                  AS DIAS_PARADOS,
        (PLANO.DATA_PLANO - PLANO.DATA_ENTREGA) || ' DIA(S)'          AS ATRASO_PREVISTO
  FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
  JOIN SGTPRD.PEDIDOCOMERCIAL PED
    ON PED.PEDIDO = IPC.PEDIDO
  JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON ITE.CODIGO_REDUZIDO = IPC.REDUZIDOITEM
  JOIN PEDIDO_OB OBP
    ON OBP.PEDIDO = IPC.PEDIDO
   AND OBP.ITEMPEDIDO = IPC.ITEMPEDIDO
  LEFT JOIN FASE_ATUAL OBF
    ON OBF.NUMERO_OB = OBP.NUMEROOB
  LEFT JOIN STATUS_FASE SF
    ON SF.STATUS = OBF.STATUS
  LEFT JOIN SGTPRD.OB_PRODUTO OP
    ON OP.NUMERO_OB = OBP.NUMEROOB
   LEFT JOIN OB_MONTADA OBM
     ON OBM.NUMERO_OB = OBP.NUMEROOB
   LEFT JOIN PLANO_RESUMO PLANO
     ON PLANO.NUMEROOB = OBP.NUMEROOB
 WHERE IPC.SITUACAOITEM NOT IN (6, 10, 12, 13, 14, 18)
 ORDER BY ANALISE_ENTREGA DESC,
          DT_ENTREGA,
          P_CLIENTE,
          ITEM
