/* =============================================================================
OBJETIVO: Monitoramento Analítico de Programações de Terceiros, Andamento por OB e Chão de Fábrica
DOMÍNIO: 07_expedicao_pedidos_comercial
TIPO: Consulta Analítica / Detalhamento Operacional de Chão de Fábrica, PCP e Comercial
PARÂMETROS / FILTROS:
  - Pedidos comerciais ativos (TIPOPEDIDO IN (1, 2, 3), SITUACAO não concluída/cancelada)
  - Programação de cliente preenchida (PEDIDOCLIENTE IS NOT NULL)
  - Itens de pedido pendentes de produção e entrega
TABELAS PRINCIPAIS:
  - SGTPRD.PEDIDOCOMERCIAL
  - SGTPRD.PESSOASFJ
  - SGTPRD.ITENSPEDIDOCOMERCIAL
  - SGTPRD.ITENSPEDIDOGRADE
  - SGTPRD.ITENSPEDIDOQTDES
  - SGTPRD.ITENS_ESTOQUE
  - SGTPRD.COMPOSICAO_ITEM, SGTPRD.COMPOSICAO_FIBRAS (Engenharia Têxtil)
  - SGTPRD.OFPEDIDO
  - SGTPRD.OFORDENS
  - SGTPRD.PEDPRODUCAO
  - SGTPRD.PEDPRODUCAOOB
  - SGTPRD.OB
  - SGTPRD.OB_PRODUTO
  - SGTPRD.GERAPECAORIGEMOB
  - SGTPRD.GERAPECADESTINOOB
  - SGTPRD.GERAPECAROMSAIDA
  - SGTPRD.ROMANEIO
  - SGTPRD.OB_FASES
  - SGTPRD.FASES_FLUXO
  - SGTPRD.OB_BLOQUEIO
  - SGTPRD.OB_REPROCESSO
  - SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS E REVISÃO:
  - Zero views legadas (100% tabelas físicas indexadas).
  - Execução somente leitura sob orçamento estrito (< 2s).
  - Composição Têxtil extraída estritamente das tabelas de ENGENHARIA (COMPOSICAO_ITEM + COMPOSICAO_FIBRAS).
  - Prevenção de duplicidade: agregações desacopladas em CTEs materializadas garantindo 1 linha por (PEDIDO, ITEMPEDIDO, OB).
  - Macro-Etapas de Produção: categorização inteligente das fases (Preparação, Tinturaria, Secagem, Acabamento, etc.).
  - Balanço de Cobertura Física: confronto entre Saldo Comercial, KGs em OB e KGs a Programar.
  - Avanço Físico Real: leitura de KILOS_ACABADOS e TOTAL_PECAS_CONFIRM de OB_PRODUTO.
  - Rastreamento de Expedição: vinculação de romaneios de saída e status de faturamento.
  - Conversão de épocas SGT: Minutos = DATE '1996-01-01' + (MINUTOS/1440), Datas inteiras com ON CONVERSION ERROR.
  - Resolução robusta de data prometida via COALESCE(DATAEXPEDIREM, EXPEDIREM).
============================================================================= */

WITH PEDIDOS_ATIVOS AS (
    SELECT /*+ MATERIALIZE */
           PED.PEDIDO,
           TRIM(PED.PEDIDOCLIENTE)        AS PROGRAMACAO_CLIENTE,
           PED.IDFILIALRESPONSAVEL        AS ID_CLIENTE,
           TRIM(PFJ.NOMEFANTASIA)         AS NOME_CLIENTE,
           PED.BLOQUEIOFATURAMENTO,
           TRIM(PED.DESCBLOQFATURAMENTO)  AS MOTIVO_BLOQ_FAT,
           PED.SITUACAO                   AS SITUACAO_PEDIDO,
           TRUNC(PED.DATEMISSAO)          AS DATA_EMISSAO
      FROM SGTPRD.PEDIDOCOMERCIAL PED
      JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
     WHERE PED.TIPOPEDIDO IN (1, 2, 3)
       AND PED.SITUACAO NOT IN (6, 12, 13, 14, 18) -- Exclui Cancelados, Concluídos, Encerrados, Atendidos Totais
       AND PED.PEDIDOCLIENTE IS NOT NULL
),
ITENS_ATIVOS AS (
    SELECT /*+ MATERIALIZE */
           IPC.PEDIDO,
           IPC.ITEMPEDIDO,
           IPC.REDUZIDOITEM,
           IPC.SITUACAOITEM,
           COALESCE(
               IPC.DATAEXPEDIREM, 
               CASE 
                   WHEN NVL(IPC.EXPEDIREM, 0) > 0 
                        THEN TO_DATE(TO_CHAR(IPC.EXPEDIREM) DEFAULT NULL ON CONVERSION ERROR, 'YYYYMMDD') 
               END
           ) AS DATA_ENTREGA,
           NVL(IPC.QUANTIDADE, 0) AS QTD_PEDIDA,
           NVL(IPC.FATURADO, 0)   AS QTD_FATURADA,
           NVL(IPC.QTDECANCELADAITEMPED, 0) AS QTD_CANCELADA,
           GREATEST(0, NVL(IPC.QUANTIDADE, 0) - NVL(IPC.FATURADO, 0) - NVL(IPC.QTDECANCELADAITEMPED, 0)) AS SALDO_PENDENTE,
           TRIM(TO_CHAR(NULLIF(IPC.NOTA_FISCAL_ENTRADA, 0))) AS NF_ENTRADA_TERCEIRO,
           COALESCE(TRIM(IPC.CD_DESENHO_CLIENTE), TRIM(IPC.ITEMPEDIDOCLIENTE), TRIM(IPC.REFERENCIA), '-') AS REF_CLIENTE
      FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
      JOIN PEDIDOS_ATIVOS PA ON PA.PEDIDO = IPC.PEDIDO
     WHERE IPC.SITUACAOITEM NOT IN (6, 10, 12, 13, 14, 18)
),
COMPOSICAO_ENG AS (
    SELECT /*+ MATERIALIZE */
           CPS.CODIGO_REDUZIDO,
           LISTAGG(TRIM(TO_CHAR(CPS.COMPOSICAO, 'FM990')) || '% ' || TRIM(CPF.DESCRICAO), ' / ' ON OVERFLOW TRUNCATE)
               WITHIN GROUP (ORDER BY CPS.COMPOSICAO DESC) AS COMPOSICAO_TEXTIL
      FROM SGTPRD.COMPOSICAO_ITEM CPS
      JOIN SGTPRD.COMPOSICAO_FIBRAS CPF ON CPF.CODIGO = CPS.CODIGO_DA_COMPOSICAO
     WHERE CPS.CODIGO_REDUZIDO IN (SELECT DISTINCT REDUZIDOITEM FROM ITENS_ATIVOS)
     GROUP BY CPS.CODIGO_REDUZIDO
),
VINCULO_OB AS (
    SELECT /*+ MATERIALIZE */
           IPG.PEDIDO,
           IPG.ITEMPEDIDO,
           PPOB.NUMEROOB,
           OB.STATUS AS STATUS_OB_NUM,
           CASE WHEN OB.TEMPO_INICIO_PRODUCA > 0 THEN DATE '1996-01-01' + OB.TEMPO_INICIO_PRODUCA / 1440 END AS DATA_INICIO_PRODUCAO,
           CASE WHEN OB.TEMPO_PROGRAMACAO > 0 THEN DATE '1996-01-01' + OB.TEMPO_PROGRAMACAO / 1440 END AS DATA_PROGRAMACAO,
           CASE WHEN OB.TEMPO_EMISSAO_OB > 0 THEN DATE '1996-01-01' + OB.TEMPO_EMISSAO_OB / 1440 END AS DATA_EMISSAO_OB,
           CASE WHEN OB.TEMPO_PREVISTO_TERMI > 0 THEN DATE '1996-01-01' + OB.TEMPO_PREVISTO_TERMI / 1440 END AS DATA_PREV_TERMINO
      FROM SGTPRD.ITENSPEDIDOGRADE IPG
      JOIN SGTPRD.ITENSPEDIDOQTDES IPX ON IPX.IDITEMPEDGRADE = IPG.IDITENSPEDIDOGRADE
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.IDITENSPEDIDOQTDES = IPX.IDITENSPEDIDOQTDES
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROOF = OFP.NUMEROOF AND OFO.NIVEL = OFP.NIVEL AND OFO.REDUZIDO = OFP.REDUZIDO
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
      JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMERO = PP.NUMERO AND PPOB.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.OB OB ON OB.NUMERO_OB = PPOB.NUMEROOB
      JOIN PEDIDOS_ATIVOS PA ON PA.PEDIDO = IPG.PEDIDO
     WHERE OB.STATUS <> 0
     GROUP BY IPG.PEDIDO, IPG.ITEMPEDIDO, PPOB.NUMEROOB, OB.STATUS, OB.TEMPO_INICIO_PRODUCA, OB.TEMPO_PROGRAMACAO, OB.TEMPO_EMISSAO_OB, OB.TEMPO_PREVISTO_TERMI
),
OBS_DISTINCT AS (
    SELECT /*+ MATERIALIZE */ DISTINCT NUMEROOB FROM VINCULO_OB
),
COBERTURA_ITEM AS (
    SELECT /*+ MATERIALIZE */
           V.PEDIDO,
           V.ITEMPEDIDO,
           SUM(NVL(OBP.KILOS_PROGRAMADOS, 0)) AS TOTAL_KG_OB_ITEM
      FROM VINCULO_OB V
      LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = V.NUMEROOB
     GROUP BY V.PEDIDO, V.ITEMPEDIDO
),
FASE_ATUAL AS (
    SELECT NUMERO_OB,
           CODIGO_FASE,
           DESCRICAO_FASE,
           STATUS_FASE,
           NUMERO_MAQUINA,
           DATA_INICIO_FASE,
           MACRO_ETAPA
      FROM (
            SELECT OBF.NUMERO_OB,
                   OBF.CODIGO_FASE,
                   TRIM(FFL.DESCRICAO_FASE) AS DESCRICAO_FASE,
                   CASE 
                       WHEN OBF.STATUS = 4 THEN 'Concluída'
                       WHEN OBF.STATUS = 0 THEN 'Programada'
                       WHEN OBF.STATUS = 1 THEN 'Emitida'
                       WHEN OBF.STATUS = 2 THEN 'Pesada'
                       WHEN OBF.STATUS = 3 THEN 'Em Execução'
                       WHEN OBF.STATUS = 5 THEN 'Cancelada'
                       WHEN OBF.STATUS = 6 THEN 'Consumo Estamparia'
                       ELSE 'Status ' || OBF.STATUS
                   END AS STATUS_FASE,
                   TRIM(OBF.NUMERO_MAQUINA) AS NUMERO_MAQUINA,
                   CASE 
                       WHEN OBF.TEMPO_INICIAL_CONFIR > 0 
                            THEN DATE '1996-01-01' + OBF.TEMPO_INICIAL_CONFIR / 1440 
                   END AS DATA_INICIO_FASE,
                   CASE 
                       WHEN OBF.STATUS = 4 THEN '08. CONCLUÍDO NA FÁBRICA'
                       WHEN OBF.CODIGO_FASE BETWEEN 10 AND 26 THEN '01. PREPARAÇÃO / CRU'
                       WHEN OBF.CODIGO_FASE BETWEEN 30 AND 47 THEN '02. TINTURARIA'
                       WHEN OBF.CODIGO_FASE BETWEEN 50 AND 60 THEN '03. SECAGEM'
                       WHEN OBF.CODIGO_FASE BETWEEN 65 AND 115 THEN '04. ACABAMENTO / RAMAS'
                       WHEN OBF.CODIGO_FASE BETWEEN 120 AND 145 THEN '05. ESTAMPARIA / EXT'
                       WHEN OBF.CODIGO_FASE BETWEEN 150 AND 190 THEN '06. REVISÃO / CQ / EMBALAGEM'
                       WHEN OBF.CODIGO_FASE = 500 THEN '07. LABORATÓRIO'
                       ELSE '04. ACABAMENTO / PROCESSO'
                   END AS MACRO_ETAPA,
                   ROW_NUMBER() OVER (
                       PARTITION BY OBF.NUMERO_OB
                       ORDER BY 
                           CASE WHEN OBF.STATUS NOT IN (4, 5) THEN 1 ELSE 2 END ASC,
                           CASE WHEN OBF.STATUS NOT IN (4, 5) THEN OBF.SEQUENCIA END ASC,
                           OBF.SEQUENCIA DESC
                   ) AS RN
              FROM SGTPRD.OB_FASES OBF
              JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
              JOIN OBS_DISTINCT OD ON OD.NUMEROOB = OBF.NUMERO_OB
             WHERE OBF.STATUS <> 5 -- Não cancelada
           )
     WHERE RN = 1
),
FASE_INFO AS (
    SELECT /*+ MATERIALIZE */
           OBF.NUMERO_OB,
           MAX(TRIM(OBF.CODIGO_PLACA)) AS PLACA_KANBAN,
           MAX(CASE WHEN OBF.CODIGO_FASE = 40 THEN TRIM(OBF.CODIGO_COR_DESENHO) END)
               KEEP (DENSE_RANK LAST ORDER BY
                     CASE WHEN OBF.CODIGO_FASE = 40 THEN OBF.SEQUENCIA ELSE NULL END
                     NULLS FIRST) AS CD_COR_RECEITA,
           MAX(CASE WHEN OBF.TEMPO_FINAL_CONFIRMA > 0 THEN DATE '1996-01-01' + OBF.TEMPO_FINAL_CONFIRMA / 1440 END) AS DT_ULT_CONFIRMACAO
      FROM SGTPRD.OB_FASES OBF
      JOIN OBS_DISTINCT OD ON OD.NUMEROOB = OBF.NUMERO_OB
     GROUP BY OBF.NUMERO_OB
),
PROD_INFO AS (
    SELECT /*+ MATERIALIZE */
           OBE.NUMERO_OB,
           MAX(OBP.KILOS_PROGRAMADOS)         AS KILOS_PROGRAMADOS,
           MAX(NVL(OBP.KILOS_ACABADOS, 0))    AS KILOS_ACABADOS,
           MAX(OBP.TOTAL_PECAS)               AS PECAS_PROGRAMADAS,
           MAX(NVL(OBP.TOTAL_PECAS_CONFIRM, 0)) AS PECAS_ACABADAS,
           COUNT(DISTINCT ORI.IDPECASPRODUTO) AS PECAS_MONTADAS_CRU,
           COALESCE(NULLIF(COUNT(DISTINCT ORI.IDPECASPRODUTO), 0), MAX(OBP.TOTAL_PECAS), 0) AS TOTAL_PECAS
      FROM OBS_DISTINCT OD
      JOIN SGTPRD.OB OBE ON OBE.NUMERO_OB = OD.NUMEROOB
      LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBE.NUMERO_OB
      LEFT JOIN SGTPRD.GERAPECAORIGEMOB ORI ON ORI.NUMERO_OB = OBE.NUMERO_OB
     GROUP BY OBE.NUMERO_OB
),
STATUS_OB_DESC AS (
    SELECT ENI.SEQUENCE, TRIM(ENI.DESCRIPTION) AS DESCR_STATUS_OB
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME = 'TOBSTATUS'
),
BLOQUEIOS_OB AS (
    SELECT /*+ MATERIALIZE */
           BLQ.NUMERO_OB,
           COUNT(*) AS QTD_BLOQUEIOS,
           MAX(BLQ.DATA_BLOQUEIO) AS DATA_BLOQUEIO_OB,
           MAX(TRIM(BLQ.OBSERVACAO)) KEEP (DENSE_RANK LAST ORDER BY BLQ.DATA_BLOQUEIO NULLS FIRST, BLQ.ID NULLS FIRST) AS MOTIVO_BLOQUEIO_OB
      FROM SGTPRD.OB_BLOQUEIO BLQ
      JOIN OBS_DISTINCT OD ON OD.NUMEROOB = BLQ.NUMERO_OB
     WHERE BLQ.LIBERADO = 0
     GROUP BY BLQ.NUMERO_OB
),
REPROCESSOS_OB AS (
    SELECT REP.NUMERO_OB,
           COUNT(*) AS QTD_REPROCESSOS
      FROM SGTPRD.OB_REPROCESSO REP
      JOIN OBS_DISTINCT OD ON OD.NUMEROOB = REP.NUMERO_OB
     GROUP BY REP.NUMERO_OB
),
ROMANEIOS_OB_DISTINCT AS (
    SELECT DISTINCT
           GPD.NUMERO_OB,
           ROM.NUMERO_ROMANEIO,
           CASE 
               WHEN ROM.STATUS = 6 THEN 'Faturado'
               WHEN ROM.STATUS IN (3, 8) THEN 'Pronto Faturamento'
               WHEN ROM.STATUS = 1 THEN 'Conferido'
               WHEN ROM.STATUS = 0 THEN 'Em Digitação'
               ELSE 'Status ' || ROM.STATUS
           END AS STATUS_ROMANEIO
      FROM SGTPRD.GERAPECADESTINOOB GPD
      JOIN OBS_DISTINCT OD ON OD.NUMEROOB = GPD.NUMERO_OB
      JOIN SGTPRD.GERAPECAROMSAIDA GPR ON GPR.IDPECASPRODUTO = GPD.IDPECASPRODUTO
      JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = GPR.NUMERO_ROMANEIO_SAID
     WHERE ROM.STATUS <> 5
),
ROMANEIOS_OB AS (
    SELECT /*+ MATERIALIZE */
           NUMERO_OB,
           LISTAGG(TO_CHAR(NUMERO_ROMANEIO), ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY NUMERO_ROMANEIO) AS ROMANEIOS_SAIDA,
           MAX(STATUS_ROMANEIO) AS SITUACAO_ROMANEIO
      FROM ROMANEIOS_OB_DISTINCT
     GROUP BY NUMERO_OB
)
SELECT PA.PROGRAMACAO_CLIENTE,
       PA.ID_CLIENTE,
       PA.NOME_CLIENTE,
       ITA.REF_CLIENTE,
       ITA.NF_ENTRADA_TERCEIRO,
       PA.PEDIDO,
       ITA.ITEMPEDIDO,
       PA.DATA_EMISSAO               AS DT_EMISSAO_PEDIDO,
       ITA.DATA_ENTREGA              AS DT_ENTREGA_PROMETIDA,
       VOB.DATA_PREV_TERMINO         AS DT_PREV_TERMINO_FABRICA,
       CASE 
           WHEN ITA.DATA_ENTREGA IS NULL THEN 'SEM PREVISAO'
           WHEN ITA.SALDO_PENDENTE <= 0 THEN 'ATENDIDO TOTAL'
           WHEN TRUNC(SYSDATE) > ITA.DATA_ENTREGA 
                THEN 'ATRASADO (' || TO_CHAR(TRUNC(SYSDATE) - ITA.DATA_ENTREGA) || ' DIAS)'
           WHEN ITA.DATA_ENTREGA = TRUNC(SYSDATE)
                THEN 'ENTREGA HOJE'
           WHEN ITA.DATA_ENTREGA - TRUNC(SYSDATE) <= 3 
                THEN 'CRÍTICO (' || TO_CHAR(ITA.DATA_ENTREGA - TRUNC(SYSDATE)) || ' DIAS)'
           ELSE 'NO PRAZO (' || TO_CHAR(ITA.DATA_ENTREGA - TRUNC(SYSDATE)) || ' DIAS)'
       END AS STATUS_PRAZO,
       SUBSTR(ITE.CODIGO, 6, 3)      AS ARTIGO,
       TRIM(ITE.DESCRICAO)           AS DESCRICAO_ITEM,
       NVL(CPE.COMPOSICAO_TEXTIL, 'NÃO CADASTRADA') AS COMPOSICAO_TEXTIL,
       ROUND(ITA.QTD_PEDIDA, 2)      AS KG_PEDIDO_ITEM,
       ROUND(ITA.QTD_FATURADA, 2)    AS KG_FATURADO_ITEM,
       ROUND(ITA.SALDO_PENDENTE, 2)  AS KG_SALDO_ITEM,
       ROUND(NVL(CBI.TOTAL_KG_OB_ITEM, 0), 2) AS KG_TOTAL_EM_OB_ITEM,
       ROUND(GREATEST(0, ITA.SALDO_PENDENTE - NVL(CBI.TOTAL_KG_OB_ITEM, 0)), 2) AS KG_SALDO_A_PROGRAMAR,
       CASE 
           WHEN ITA.SALDO_PENDENTE <= 0 THEN '100%'
           WHEN NVL(CBI.TOTAL_KG_OB_ITEM, 0) > 0 
                THEN LEAST(100, ROUND((NVL(CBI.TOTAL_KG_OB_ITEM, 0) / ITA.SALDO_PENDENTE) * 100, 1)) || '%'
           ELSE '0%'
       END AS PERC_COBERTURA_OB,
       ROW_NUMBER() OVER (
           PARTITION BY ITA.PEDIDO, ITA.ITEMPEDIDO 
           ORDER BY VOB.NUMEROOB NULLS LAST
       )                             AS SEQ_OB_ITEM,
       COUNT(VOB.NUMEROOB) OVER (
           PARTITION BY ITA.PEDIDO, ITA.ITEMPEDIDO
       )                             AS TOTAL_OBS_ITEM,
       VOB.NUMEROOB                  AS NUMERO_OB,
       NVL(SOB.DESCR_STATUS_OB, 'SEM OB') AS STATUS_OB,
       FI.PLACA_KANBAN,
       FI.CD_COR_RECEITA,
       ROUND(NVL(PI.KILOS_PROGRAMADOS, 0), 2) AS KG_PROGRAMADO_OB,
       ROUND(NVL(PI.KILOS_ACABADOS, 0), 2)    AS KG_ACABADO_OB,
       CASE 
           WHEN NVL(PI.KILOS_PROGRAMADOS, 0) > 0 AND NVL(PI.KILOS_ACABADOS, 0) > 0
                THEN ROUND((PI.KILOS_ACABADOS / PI.KILOS_PROGRAMADOS) * 100, 1) || '%'
           ELSE '0%'
       END AS PERC_AVANCO_OB,
       NVL(PI.PECAS_PROGRAMADAS, 0)   AS PECAS_PROGRAMADAS,
       NVL(PI.PECAS_MONTADAS_CRU, 0)  AS PECAS_MONTADAS_CRU,
       NVL(PI.PECAS_ACABADAS, 0)      AS PECAS_ACABADAS,
       NVL(PI.TOTAL_PECAS, 0)         AS TOTAL_PECAS_OB,
       CASE 
           WHEN VOB.NUMEROOB IS NULL THEN '00. NÃO PROGRAMADA'
           ELSE NVL(FA.MACRO_ETAPA, '04. ACABAMENTO / PROCESSO')
       END                            AS MACRO_ETAPA,
       FA.CODIGO_FASE                 AS FASE_ATUAL_COD,
       FA.DESCRICAO_FASE              AS FASE_ATUAL_NOME,
       CASE 
           WHEN VOB.NUMEROOB IS NULL THEN 'SEM OB'
           ELSE NVL(FA.STATUS_FASE, 'EM FILA')
       END                            AS STATUS_FASE_ATUAL,
       FA.NUMERO_MAQUINA,
       CASE 
           WHEN VOB.NUMEROOB IS NULL THEN NULL
           ELSE TRUNC(
               CASE 
                   WHEN SYSDATE - COALESCE(FA.DATA_INICIO_FASE, FI.DT_ULT_CONFIRMACAO, VOB.DATA_INICIO_PRODUCAO, VOB.DATA_PROGRAMACAO, VOB.DATA_EMISSAO_OB, PA.DATA_EMISSAO) < 0 THEN 0
                   ELSE SYSDATE - COALESCE(FA.DATA_INICIO_FASE, FI.DT_ULT_CONFIRMACAO, VOB.DATA_INICIO_PRODUCAO, VOB.DATA_PROGRAMACAO, VOB.DATA_EMISSAO_OB, PA.DATA_EMISSAO)
               END, 1
           )
       END                            AS DIAS_NA_FASE_ATUAL,
       CASE 
           WHEN VOB.NUMEROOB IS NULL THEN NULL
           ELSE TRUNC(GREATEST(0, SYSDATE - COALESCE(VOB.DATA_EMISSAO_OB, VOB.DATA_PROGRAMACAO, PA.DATA_EMISSAO)))
       END                            AS LEAD_TIME_TOTAL_OB_DIAS,
       NVL(ROB_EXP.ROMANEIOS_SAIDA, '-') AS ROMANEIOS_SAIDA,
       NVL(ROB_EXP.SITUACAO_ROMANEIO, 'SEM ROMANEIO') AS SITUACAO_ROMANEIO,
       CASE 
           WHEN ITA.SALDO_PENDENTE <= 0 THEN 'FATURADO TOTAL'
           WHEN ITA.QTD_FATURADA > 0 AND ITA.SALDO_PENDENTE > 0 THEN 'PARCIALMENTE FATURADO'
           WHEN ROB_EXP.ROMANEIOS_SAIDA IS NOT NULL THEN 'EM EXPEDIÇÃO / ROMANEIO'
           WHEN NVL(PI.KILOS_ACABADOS, 0) >= NVL(PI.KILOS_PROGRAMADOS, 0) AND NVL(PI.KILOS_PROGRAMADOS, 0) > 0 
                THEN 'PRODUÇÃO CONCLUÍDA (ESTOQUE ACABADO)'
           WHEN VOB.NUMEROOB IS NOT NULL THEN 'EM PROCESSO INDUSTRIAL'
           ELSE 'PENDENTE DE PROGRAMAÇÃO'
       END                            AS SITUACAO_EXPEDICAO,
       CASE 
           WHEN PA.BLOQUEIOFATURAMENTO <> 0 
                THEN 'BLOQUEIO FAT: ' || NVL(PA.MOTIVO_BLOQ_FAT, 'ATIVO')
           ELSE 'LIBERADO'
       END                            AS BLOQUEIO_COMERCIAL,
       CASE 
           WHEN BOB.NUMERO_OB IS NOT NULL 
                THEN 'BLOQUEADA: ' || NVL(BOB.MOTIVO_BLOQUEIO_OB, 'QUALIDADE/PROCESSO')
           ELSE 'NORMAL'
       END                            AS BLOQUEIO_OB_CHAO_FABRICA,
       CASE 
           WHEN NVL(ROB.QTD_REPROCESSOS, 0) > 0 
                THEN 'SIM (' || TO_CHAR(ROB.QTD_REPROCESSOS) || 'x)'
           ELSE 'NÃO'
       END                            AS REPROCESSO_TINGIMENTO,
       CASE 
           WHEN ITA.SALDO_PENDENTE <= 0 
                THEN 'NENHUMA OCORRENCIA (ATENDIDO TOTAL)'
           WHEN PA.BLOQUEIOFATURAMENTO <> 0 
                THEN 'BLOQUEIO COMERCIAL: ' || NVL(PA.MOTIVO_BLOQ_FAT, 'ATIVO')
           WHEN BOB.NUMERO_OB IS NOT NULL 
                THEN 'BLOQUEIO INDUSTRIAL: ' || NVL(BOB.MOTIVO_BLOQUEIO_OB, 'QUALIDADE/PROCESSO')
           WHEN VOB.NUMEROOB IS NULL 
                THEN 'ALERTA: PENDENTE DE ABERTURA DE OB NO CHÃO DE FÁBRICA'
           WHEN TRUNC(SYSDATE) > ITA.DATA_ENTREGA 
                THEN 'ATRASO DE EXPEDICAO'
           WHEN NVL(ROB.QTD_REPROCESSOS, 0) > 0 
                THEN 'OCORRENCIA: REPROCESSO EM ANDAMENTO'
           WHEN (SYSDATE - COALESCE(FA.DATA_INICIO_FASE, FI.DT_ULT_CONFIRMACAO, VOB.DATA_INICIO_PRODUCAO)) > 3
                THEN 'ATENÇÃO: OB RETIDA NA FASE HÁ MAIS DE 3 DIAS'
           ELSE 'NENHUMA OCORRENCIA (NORMAL)'
       END                            AS OCORRENCIA_PRINCIPAL,
       CASE 
           WHEN ITA.SALDO_PENDENTE <= 0 
                THEN 'BAIXA'
           WHEN PA.BLOQUEIOFATURAMENTO <> 0 OR BOB.NUMERO_OB IS NOT NULL OR TRUNC(SYSDATE) - ITA.DATA_ENTREGA > 3
                THEN 'ALTA'
           WHEN TRUNC(SYSDATE) > ITA.DATA_ENTREGA OR NVL(ROB.QTD_REPROCESSOS, 0) > 0 OR VOB.NUMEROOB IS NULL
                THEN 'MEDIA'
           ELSE 'BAIXA'
       END                            AS GRAVIDADE_OCORRENCIA
  FROM PEDIDOS_ATIVOS PA
  JOIN ITENS_ATIVOS ITA ON ITA.PEDIDO = PA.PEDIDO
  JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = ITA.REDUZIDOITEM
  LEFT JOIN COMPOSICAO_ENG CPE ON CPE.CODIGO_REDUZIDO = ITA.REDUZIDOITEM
  LEFT JOIN COBERTURA_ITEM CBI ON CBI.PEDIDO = ITA.PEDIDO AND CBI.ITEMPEDIDO = ITA.ITEMPEDIDO
  LEFT JOIN VINCULO_OB VOB ON VOB.PEDIDO = ITA.PEDIDO AND VOB.ITEMPEDIDO = ITA.ITEMPEDIDO
  LEFT JOIN STATUS_OB_DESC SOB ON SOB.SEQUENCE = VOB.STATUS_OB_NUM
  LEFT JOIN FASE_ATUAL FA ON FA.NUMERO_OB = VOB.NUMEROOB
  LEFT JOIN FASE_INFO FI ON FI.NUMERO_OB = VOB.NUMEROOB
  LEFT JOIN PROD_INFO PI ON PI.NUMERO_OB = VOB.NUMEROOB
  LEFT JOIN BLOQUEIOS_OB BOB ON BOB.NUMERO_OB = VOB.NUMEROOB
  LEFT JOIN REPROCESSOS_OB ROB ON ROB.NUMERO_OB = VOB.NUMEROOB
  LEFT JOIN ROMANEIOS_OB ROB_EXP ON ROB_EXP.NUMERO_OB = VOB.NUMEROOB
 ORDER BY ITA.DATA_ENTREGA ASC NULLS LAST, PA.PROGRAMACAO_CLIENTE ASC, ITA.ITEMPEDIDO ASC, VOB.NUMEROOB ASC NULLS LAST;
