/* =============================================================================
OBJETIVO: Tabela da Verdade e Auditoria de Itens, Artigos, Cores e Preços de Serviços (Tingimento)
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO: com_tabela_precos_itens_servico_tingimento.sql
TIPO: Comercial, Auditoria de Cadastros e Preços ERP (Fonte Única de Conferência)
COMPATIBILIDADE: Power Query (Excel), Power BI, Oracle Database Connector, OLE DB, ODBC
GRANULARIDADE: 1 linha estrita por item / código reduzido cadastrado na tabela de preços
FILTRO DE TABELAS: Somente tabelas de serviço novas (TABELAPRECO >= 4000 e < 7000: 4001..4300)
MODELAGEM: 100% Dinâmica - Sem filtros fixos de cliente, descobre novos clientes e reduzidos automaticamente
OTIMIZAÇÃO (revisao-queries-oracle):
  - 100% Tabelas físicas nativas indexadas (zero views pesadas)
  - Redução de escopo em pedidos: filtro prévio por REDUZIDOS_ALVO via INDEX RANGE SCAN
    (evita Full Scan de 182k itens de pedido comercial)
  - Custo CBO otimizado com tempo de resposta sub-segundo
TABELAS PRINCIPAIS:
  - SGTPRD.COML_PRECOSARTIGOS (Preços vigentes por tabela de serviço nova >= 4000)
  - SGTPRD.COML_GRUPOSPRECOSITE (Grupos de itens de preço amarrados ao código reduzido)
  - SGTPRD.BD_BAS_MASCPRODACAB (Máscara do produto acabado, código reduzido, artigo e cor)
  - SGTPRD.COML_TABELAPRECOS (Tabelas de preço comercial)
  - SGTPRD.COR (Cadastro base de cores)
  - SGTPRD.PEDIDOCOMERCIAL + SGTPRD.ITENSPEDIDOCOMERCIAL (Histórico do último pedido do item)
  - SGTPRD.PESSOASFJ (Cliente da última movimentação do pedido)
CUIDADOS OPERACIONAIS: Consulta 100% somente leitura via tabelas físicas indexadas.
REVISÃO: 24/09/2026
============================================================================= */

WITH REDUZIDOS_ALVO AS (
    SELECT DISTINCT TO_NUMBER(GPI.IDENTIFICACAOPRECO) AS CODIGO_REDUZIDO
      FROM SGTPRD.COML_PRECOSARTIGOS PA
      JOIN SGTPRD.COML_GRUPOSPRECOSITE GPI 
        ON GPI.GRUPOPRECOSITEM = PA.GRUPOPRECOSITEM
     WHERE PA.TABELAPRECO >= 4000 
       AND PA.TABELAPRECO < 7000
),
ULTIMO_PEDIDO_ITEM AS (
    SELECT IP.REDUZIDOITEM AS CODIGO_REDUZIDO,
           MAX(PED.PEDIDO) KEEP (DENSE_RANK LAST ORDER BY PED.PEDIDO) AS ULTIMO_PEDIDO,
           TO_CHAR(MAX(PED.DATEMISSAO) KEEP (DENSE_RANK LAST ORDER BY PED.PEDIDO), 'YYYY-MM-DD') AS DT_ULTIMO_PEDIDO,
           MAX(PED.TABELAPRECO) KEEP (DENSE_RANK LAST ORDER BY PED.PEDIDO) AS TABELA_ULTIMO_PEDIDO,
           ROUND(MAX(IP.PRECODIGITADO) KEEP (DENSE_RANK LAST ORDER BY PED.PEDIDO), 2) AS PRECO_ULTIMO_PEDIDO,
           MAX(PED.IDFILIALRESPONSAVEL) KEEP (DENSE_RANK LAST ORDER BY PED.PEDIDO) AS IDFILIALRESPONSAVEL
      FROM SGTPRD.PEDIDOCOMERCIAL PED
      JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IP 
        ON IP.PEDIDO = PED.PEDIDO
      JOIN REDUZIDOS_ALVO RA 
        ON RA.CODIGO_REDUZIDO = IP.REDUZIDOITEM
     WHERE PED.SITUACAO <> 6
       AND IP.REDUZIDOITEM <> 587
     GROUP BY IP.REDUZIDOITEM
),
ITENS_TABELA_PRECO AS (
    SELECT PA.TABELAPRECO AS TABELA_PRECO_ERP,
           TRIM(TP.NOME) AS DS_TABELA_PRECO,
           CASE 
               WHEN UPPER(TP.NOME) LIKE '%TABELA 1%' THEN 1
               WHEN UPPER(TP.NOME) LIKE '%TABELA 2%' THEN 2
               WHEN UPPER(TP.NOME) LIKE '%TABELA 3%' THEN 3
               WHEN MOD(PA.TABELAPRECO, 10) = 1 THEN 1
               WHEN MOD(PA.TABELAPRECO, 10) = 2 THEN 2
               WHEN MOD(PA.TABELAPRECO, 10) = 3 THEN 3
               ELSE NULL
           END AS TABELA_COMISSAO_ERP,
           ROUND(PA.PRECO, 2) AS VALOR_TABELA_BASE,
           ROUND(PA.PRECO + 0.20, 2) AS VALOR_TOTAL_ERP,
           M.CODIGO_REDUZIDO,
           TRIM(M.ARTIGO) AS ARTIGO,
           TRIM(M.DESCR_ARTIGO) AS DESCR_ARTIGO,
           CASE 
               WHEN LENGTH(COALESCE(LTRIM(TRIM(M.COR), '0'), '0')) < 2 
               THEN LPAD(COALESCE(LTRIM(TRIM(M.COR), '0'), '0'), 2, '0')
               ELSE UPPER(TRIM(LTRIM(TRIM(M.COR), '0')))
           END AS CODIGO_COR,
           TRIM(M.COR) AS CODIGO_COR_ORIGINAL,
           TRIM(COALESCE(C.DESCRICAO, M.DESCR_COR)) AS DESCRICAO_COR_ERP,
           CASE COALESCE(C.SITUACAO, 0) WHEN 0 THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COR,
           'CADASTRADO NA TABELA' AS STATUS_AUDITORIA_PRECO
      FROM SGTPRD.COML_PRECOSARTIGOS PA
      JOIN SGTPRD.COML_TABELAPRECOS TP 
        ON TP.TABELAPRECO = PA.TABELAPRECO
      JOIN SGTPRD.COML_GRUPOSPRECOSITE GPI 
        ON GPI.GRUPOPRECOSITEM = PA.GRUPOPRECOSITEM
      JOIN SGTPRD.BD_BAS_MASCPRODACAB M 
        ON TO_CHAR(M.CODIGO_REDUZIDO) = GPI.IDENTIFICACAOPRECO
      LEFT JOIN SGTPRD.COR C 
        ON TRIM(C.CODIGO_COR) = TRIM(M.COR)
     WHERE PA.TABELAPRECO >= 4000
       AND PA.TABELAPRECO < 7000
)
SELECT CASE 
           WHEN UPPER(COALESCE(TRIM(CLI_PED.NOMEFANTASIA), SUBSTR(ITP.DESCR_ARTIGO, INSTR(ITP.DESCR_ARTIGO, ' - ') + 3))) LIKE '%SUL BRASIL%' 
             OR UPPER(COALESCE(TRIM(CLI_PED.NOMEFANTASIA), SUBSTR(ITP.DESCR_ARTIGO, INSTR(ITP.DESCR_ARTIGO, ' - ') + 3))) LIKE '%COMERCIAL TEXTIL SUL%' THEN 'SUL BRASIL'
           ELSE COALESCE(
               TRIM(CLI_PED.NOMEFANTASIA),
               CASE 
                   WHEN INSTR(ITP.DESCR_ARTIGO, ' - ') > 0 THEN TRIM(SUBSTR(ITP.DESCR_ARTIGO, INSTR(ITP.DESCR_ARTIGO, ' - ') + 3))
                   WHEN INSTR(ITP.DESCRICAO_COR_ERP, ' - ') > 0 THEN TRIM(SUBSTR(ITP.DESCRICAO_COR_ERP, INSTR(ITP.DESCRICAO_COR_ERP, ' - ') + 3))
                   ELSE 'DIVERSOS'
               END
           )
       END AS ABA_PLANILHA,
       COALESCE(
           TRIM(CLI_PED.NOMEFANTASIA),
           CASE 
               WHEN INSTR(ITP.DESCR_ARTIGO, ' - ') > 0 THEN TRIM(SUBSTR(ITP.DESCR_ARTIGO, INSTR(ITP.DESCR_ARTIGO, ' - ') + 3))
               WHEN INSTR(ITP.DESCRICAO_COR_ERP, ' - ') > 0 THEN TRIM(SUBSTR(ITP.DESCRICAO_COR_ERP, INSTR(ITP.DESCRICAO_COR_ERP, ' - ') + 3))
               ELSE 'DIVERSOS'
           END
       ) AS NOME_CLIENTE,
       UP.IDFILIALRESPONSAVEL AS IDCLIENTE_ERP,
       ITP.CODIGO_REDUZIDO,
       ITP.ARTIGO,
       ITP.DESCR_ARTIGO,
       ITP.CODIGO_COR,
       ITP.CODIGO_COR_ORIGINAL,
       ITP.DESCRICAO_COR_ERP,
       ITP.STATUS_COR,
       ITP.TABELA_PRECO_ERP,
       ITP.DS_TABELA_PRECO,
       ITP.TABELA_COMISSAO_ERP,
       ITP.VALOR_TABELA_BASE,
       ITP.VALOR_TOTAL_ERP,
       ITP.STATUS_AUDITORIA_PRECO,
       UP.ULTIMO_PEDIDO,
       UP.DT_ULTIMO_PEDIDO,
       UP.TABELA_ULTIMO_PEDIDO,
       UP.PRECO_ULTIMO_PEDIDO
  FROM ITENS_TABELA_PRECO ITP
  LEFT JOIN ULTIMO_PEDIDO_ITEM UP
    ON UP.CODIGO_REDUZIDO = ITP.CODIGO_REDUZIDO
  LEFT JOIN SGTPRD.PESSOASFJ CLI_PED 
    ON CLI_PED.IDPESSOAFJ = UP.IDFILIALRESPONSAVEL
 ORDER BY ABA_PLANILHA, ITP.ARTIGO, ITP.CODIGO_COR
