/* =============================================================================
OBJETIVO: Quantidade de KGs acabados (não faturados ainda)
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\Quantidade de KGs acabados (não faturados ainda).sql
TIPO: Comercial, Pedidos e Expedição
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECACRU, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENS_ESTOQUE, SGTPRD.PRODUTO_ROMANEIO, SGTPRD.ROMANEIO, SGTPRD.TIPO_FINALIDADE_FIO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

  SELECT COUNT(GPP.IDPECASPRODUTO) PS, SUM(GPP.QTLIQUIDA) PESO
    FROM SGTPRD.GERAPECASPRODUTO GPP
    LEFT JOIN SGTPRD.GERAPECACOMPLPECA GPC
      ON GPP.IDPECASPRODUTO = GPC.IDPECASPRODUTO
    LEFT JOIN SGTPRD.GERAPECACRU GCR
      ON GPC.IDPECASPRODUTO = GCR.IDPECASPRODUTO
    LEFT JOIN SGTPRD.TIPO_FINALIDADE_FIO TFF
      ON GPC.FINALIDADE = TFF.NUMERO_FINALIDADE
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE
      ON GPP.CODIGO_REDUZIDO_PROD = ITE.CODIGO_REDUZIDO
   WHERE GPP.STPECAPRODUTO IN (13,14)
  UNION ALL
  SELECT SUM(PRO.PECAS_ORIGINAIS) PS, SUM(PRO.QUILOS_ORIGINAIS) PESO
    FROM SGTPRD.ROMANEIO             ROM,
         SGTPRD.PRODUTO_ROMANEIO     PRO,
         SGTPRD.ITENSPEDIDOCOMERCIAL ITP,
         SGTPRD.ITENS_ESTOQUE        ITE
   WHERE PRO.NUMERO_ROMANEIO = ROM.NUMERO_ROMANEIO
     AND ITP.PEDIDO = PRO.NUMERO_PEDIDO
     AND ITP.ITEMPEDIDO = PRO.ITEM_PEDIDO
     AND ITE.CODIGO_REDUZIDO = PRO.CODIGO_PRODUTO_REDUZ
     AND ROM.IDTIPOROMA IN (1000)
     AND ROM.STATUS IN (3, 8)
     AND ITE.CODIGO_REDUZIDO IN
         (SELECT IT.CODIGO_REDUZIDO
            FROM SGTPRD.ITENS_ESTOQUE IT
           WHERE IT.TIPO_ITEM = 10
             AND TRIM(IT.IDMASCARATIPOINSUMO) IN ('BNF', 'BNR')
             AND ITE.LINHAPRODUTOCOMERCIA <> 4)
