/* =============================================================================
OBJETIVO: Cadastro de Preços (Informar pro e-mail)
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\Cadastro de Preços (Informar pro e-mail).sql
TIPO: Comercial, Pedidos e Expedição
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_BAS_MASCPRODACAB, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENS_ESTOQUE, SGTPRD.FILIAIS, SGTPRD.PESSOASFJ e tabelas auxiliares comerciais
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
REVISÃO (21/09/2026): Preços derivados diretamente das tabelas-base catalogadas, sem view, DML ou função customizada.
============================================================================= */

WITH PRECOS_PEDIDOS AS (
SELECT ITP.REDUZIDOITEM  CDREDUZIDO,
       ITP.PRECODIGITADO VLDIGITACAO,
       ITP.PRECOLISTA    VLPADRAO
  FROM SGTPRD.PEDIDOCOMERCIAL PED
  JOIN SGTPRD.FILIAIS FIL
    ON FIL.FILIAL = PED.CDFILIAL
  JOIN SGTPRD.PESSOASFJ CLIENTE
    ON CLIENTE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
  LEFT JOIN SGTPRD.REPRESENTANTES REP
    ON REP.IDREPRESENTANTE = PED.IDREPRESENTANTE
  LEFT JOIN SGTPRD.COML_CONDICOESPAGAME COND_PRECO
    ON COND_PRECO.CONDICAO = PED.CONDICAO_PRECO
  LEFT JOIN SGTPRD.COML_CONDICOESPAGAME COND_PAGAMENTO
    ON COND_PAGAMENTO.CONDICAO = PED.CONDICAO_PAGAMENTO
  LEFT JOIN SGTPRD.QUALIDADECOMERCIAL QUAL
    ON QUAL.QUALIDADECOMERCIAL = PED.QUALIDADE_COMERCIAL
  JOIN SGTPRD.ITENSPEDIDOCOMERCIAL ITP
    ON ITP.PEDIDO = PED.PEDIDO
  JOIN SGTPRD.ITENS_ESTOQUE ITE
    ON ITE.CODIGO_REDUZIDO = ITP.REDUZIDOITEM
  LEFT JOIN SGTPRD.UNIDADE_MEDIDA UM_DIGITACAO
    ON UM_DIGITACAO.IDUNIDADEMEDIDA = ITP.IDUMDIGITACAO
  LEFT JOIN SGTPRD.UNIDADE_MEDIDA UM_FATURAMENTO
    ON UM_FATURAMENTO.IDUNIDADEMEDIDA = ITP.IDUMFATURAMENTO
  LEFT JOIN SGTPRD.UNIDADE_MEDIDA UM_PADRAO
    ON UM_PADRAO.IDUNIDADEMEDIDA = ITP.IDUNIDADEMEDIDA
 WHERE PED.SITUACAO <> 6
   AND ITP.SITUACAOITEM <> 6
)
SELECT M.CODIND           CODIGO_INDUSTRIAL,
       M.ARTIGO,
       M.COR,
       M.CODIGO_REDUZIDO  REDUZIDO,
       TRIM(M.DESCRICAO)  DESCRICAO_ITEM,
       (SELECT MAX(PR.VLDIGITACAO + 0.2)
          FROM PRECOS_PEDIDOS PR
         WHERE PR.CDREDUZIDO = M.CODIGO_REDUZIDO) VL_DIGITACAO,
       (SELECT MAX(PR.VLPADRAO + 0.2)
          FROM PRECOS_PEDIDOS PR
         WHERE PR.CDREDUZIDO = M.CODIGO_REDUZIDO) VL_PADRAO
  FROM SGTPRD.BD_BAS_MASCPRODACAB M
 WHERE TRIM(M.ARTIGO) IN ('0A210', '0A211')
 ORDER BY M.ID
