-- =============================================================================
-- OBJETIVO: Preços dos Pedidos em Aberto (Sentinela de Integridade de Preço R$ 0,01)
-- DOMÍNIO: 07_expedicao_pedidos_comercial
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Preços dos Pedidos em Aberto.sql
-- TIPO: Comercial, Pedidos e Expedição (Auditoria / Sentinela de Preços)
-- PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
-- TABELAS PRINCIPAIS: SGTPRD.PEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE,
--                      SGTPRD.ITENS_ESTOQUE, SGTPRD.FILIAIS, SGTPRD.PESSOASFJ,
--                      SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
-- CUIDADOS OPERACIONAIS: Query sentinela que audita pedidos em aberto com preço simbólico
--   de R$ 0,01 para clientes externos (CDCLIENTE <> 1). Retorno de 0 linhas confirma
--   que não existem pedidos de clientes com preço indevido. Pushdown precoce de
--   PRECODIGITADO = 0.01 reduz o tempo de timeout (>10s) para 0.35s.
-- =============================================================================

WITH ENUM_SITUACAO AS (
    SELECT /*+ MATERIALIZE */ EI.SEQUENCE, UPPER(EI.DESCRIPTION) AS DSSITUACAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM EI ON EI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME = 'TSITUACAOPEDCOM'
),
PRECOS_PEDIDOS AS (
    SELECT ITP.PEDIDO          CDPEDIDO,
           PED.PEDIDOCLIENTE,
           PED.IDFILIALCOBRANCA,
           CLIENTE.IDPESSOAFJ  CDCLIENTE,
           ITP.ITEMPEDIDO      CDITEMPEDIDO,
           ITP.SITUACAOITEM    CDSITUACAO,
           ENS.DSSITUACAO,
           ITE.CODIGO_REDUZIDO CDREDUZIDO,
           TRIM(ITE.DESCRICAO) DSPRODUTO,
           ITP.PRECODIGITADO   VLDIGITACAO,
           ITP.PRECOLISTA      VLPADRAO
      FROM SGTPRD.ITENSPEDIDOCOMERCIAL ITP
      JOIN SGTPRD.PEDIDOCOMERCIAL PED
        ON PED.PEDIDO = ITP.PEDIDO
      JOIN SGTPRD.FILIAIS FIL
        ON FIL.FILIAL = PED.CDFILIAL
      JOIN SGTPRD.PESSOASFJ CLIENTE
        ON CLIENTE.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = ITP.REDUZIDOITEM
      LEFT JOIN ENUM_SITUACAO ENS
        ON ENS.SEQUENCE = ITP.SITUACAOITEM
     WHERE ITP.PRECODIGITADO = 0.01
       AND ITP.SITUACAOITEM <> 6
       AND ITP.SITUACAOITEM NOT IN (12, 13, 14)
       AND PED.SITUACAO <> 6
       AND PED.CD_SUBTIPOPED = 1
       AND CLIENTE.IDPESSOAFJ <> 1
       AND ITE.CODIGO_REDUZIDO <> 587
)
SELECT PR.CDPEDIDO,
       PR.PEDIDOCLIENTE,
       TRIM(PFJ.NOMEFANTASIA) AS NOME_FANTASIA,
       PR.CDITEMPEDIDO,
       PR.CDSITUACAO,
       PR.DSSITUACAO,
       PR.CDREDUZIDO,
       PR.DSPRODUTO,
       PR.VLDIGITACAO,
       PR.VLPADRAO
  FROM PRECOS_PEDIDOS PR
  JOIN SGTPRD.ITENSPEDIDOGRADE IPG
    ON IPG.PEDIDO = PR.CDPEDIDO
   AND IPG.ITEMPEDIDO = PR.CDITEMPEDIDO
   AND IPG.REDUZIDOITEM = PR.CDREDUZIDO
  LEFT JOIN SGTPRD.PESSOASFJ PFJ
    ON PFJ.IDPESSOAFJ = PR.IDFILIALCOBRANCA
 ORDER BY PR.CDPEDIDO, PR.CDITEMPEDIDO
