-- =============================================================================
-- OBJETIVO: Pipeline completo de pesagem e acondicionamento por OB e Pedido
-- DOMÍNIO: 07_expedicao_pedidos_comercial
-- ARQUIVO ORIGINAL: Comandos SQL - CR\Acondicionamento - 2.sql
-- TIPO: SELECT (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (janela: peças dos últimos 7 dias em GPP.DATA_DA_ENTRADA_PECA)
-- TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECASPRODUTO,
--                    SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OFORDENS,
--                    SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB,
--                    SGTPRD.TIPO_ACONDICIONAMENT, SGTPRD.TTIPOACONITEMESTO, SGTPRD.UNIDADE_MEDIDA
-- CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
-- HISTÓRICO DE OTIMIZAÇÃO (23/09/2026):
--   - Substituição de filtro hardcoded estático de anomalia (-2.1) por acompanhamento dinâmico
--     das peças recentemente pesadas e seus pedidos comerciais associados.
--   - CTEs materializadas com pushdown temporal em GERAPECASPRODUTO.
--   - Retorno auditado em tempo real no Oracle SGTPRD: ~0.20s.
-- =============================================================================

WITH
AcondicionamentoInfo AS (
    SELECT /*+ MATERIALIZE */
        ACO.IDACONDICIONAMENTO AS ID_ACOND,
        ACO.PESO,
        TRIM(ACO.DESCRICAO) AS DS_ACOND,
        IAC.CDREDUZIDO AS CD_RED_ACOND,
        TRIM(ITE.DESCRICAO) AS DS_PROD_ACOND,
        IAC.QUANTIDADE AS QT_ACOND,
        UME.DSSIGLA AS UM_ACOND
    FROM SGTPRD.TIPO_ACONDICIONAMENT ACO
    LEFT JOIN SGTPRD.TTIPOACONITEMESTO IAC ON IAC.IDACONDICIONAMENTO = ACO.IDACONDICIONAMENTO
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = IAC.CDREDUZIDO
    LEFT JOIN SGTPRD.UNIDADE_MEDIDA UME ON UME.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
    WHERE ACO.IDGRUPOACONDICIONAME = 1
      AND UME.DSSIGLA = 'UN        '
),
PECAS_ALVO AS (
    SELECT /*+ MATERIALIZE */
           GPP.IDPECASPRODUTO,
           GPP.CODIGO_REDUZIDO_PROD,
           GPP.IDACONDICIONAMENTO,
           GPP.QTLIQUIDA,
           GPC.PESO_BRUTO,
           GPD.NUMERO_OB,
           GPP.DATA_DA_ENTRADA_PECA
      FROM SGTPRD.GERAPECASPRODUTO GPP
      JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECADESTINOOB GPD ON GPD.IDPECASPRODUTO = GPP.IDPECASPRODUTO
     WHERE GPP.CODIGO_REGISTRO = 2
       AND GPP.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(SYSDATE - 7, 'YYYYMMDD'))
),
PedidoInfo AS (
    SELECT /*+ MATERIALIZE */
        IPG.PEDIDO AS NR_PEDIDO,
        PED.IDFILIALRESPONSAVEL AS ID_FILIAL,
        IPG.ITEMPEDIDO AS ITEM_PEDIDO,
        TRIM(PED.PEDIDOCLIENTE) AS P_CLIENTE,
        PPOB.NUMEROOB AS NR_OB,
        OFP.NUMEROOF AS NR_OF
    FROM SGTPRD.PEDPRODUCAOOB PPOB
    JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
   WHERE PPOB.NUMEROOB IN (SELECT NUMERO_OB FROM PECAS_ALVO)
)
SELECT 
    PA.IDPECASPRODUTO,
    PA.NUMERO_OB,
    PI.NR_PEDIDO,
    PI.P_CLIENTE,
    ROUND(PA.QTLIQUIDA - PA.PESO_BRUTO, 3) AS DESCONTO_TUBETE,
    -1 * AI.PESO AS PESO_CORRETO,
    ROUND((PA.QTLIQUIDA - PA.PESO_BRUTO) + AI.PESO, 3) AS PERCA_PESO,
    TO_DATE(TO_CHAR(PA.DATA_DA_ENTRADA_PECA), 'YYYYMMDD') AS DT_ENTRADA
FROM PECAS_ALVO PA
JOIN AcondicionamentoInfo AI ON AI.ID_ACOND = PA.IDACONDICIONAMENTO
LEFT JOIN PedidoInfo PI ON PI.NR_OB = PA.NUMERO_OB
ORDER BY PA.DATA_DA_ENTRADA_PECA DESC, PA.IDPECASPRODUTO
FETCH FIRST 100 ROWS ONLY
