/* =============================================================================
OBJETIVO: Acondicionamento e embalagem de itens consumidos em pedidos
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: 07_expedicao_pedidos_comercial/com_acondicionamentos_itens_consumidos.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum
TABELAS PRINCIPAIS: SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_ACONDICIONAMENT, SGTPRD.TTIPOACONITEMESTO, SGTPRD.UNIDADE_MEDIDA
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
============================================================================= */

SELECT 
    ACO.IDACONDICIONAMENTO AS ID_ACOND,
    ACO.PESO,
    TRIM(ACO.DESCRICAO) AS DS_ACOND,
    IAC.CDREDUZIDO AS CD_RED_ACOND,
    TRIM(ITE.DESCRICAO) AS DS_PROD_ACOND,
    IAC.QUANTIDADE AS QT_ACOND,
    UME.DSSIGLA AS UM_ACOND
FROM SGTPRD.TIPO_ACONDICIONAMENT ACO
LEFT JOIN SGTPRD.TTIPOACONITEMESTO IAC 
    ON IAC.IDACONDICIONAMENTO = ACO.IDACONDICIONAMENTO
LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE 
    ON ITE.CODIGO_REDUZIDO = IAC.CDREDUZIDO
LEFT JOIN SGTPRD.UNIDADE_MEDIDA UME 
    ON UME.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
WHERE ACO.IDGRUPOACONDICIONAME = 1
ORDER BY DS_ACOND, DS_PROD_ACOND DESC;
