/* =============================================================================
OBJETIVO: Rastreabilidade ponta-a-ponta entre OB, Romaneio e Nota Fiscal
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: 07_expedicao_pedidos_comercial/com_liga_ob_romaneio_e_nota_fiscal.sql (Query #1)
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (janela: últimos 30 dias de RO.DATAEMISSAO)
TABELAS PRINCIPAIS: SGTPRD.BD_FAT_FATURAMENTO, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAROMSAIDA, SGTPRD.NOTAFISCALCAPA, SGTPRD.PRODUTO_ROMANEIO, SGTPRD.ROMANEIO, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual.
OTIMIZAÇÃO (22/09/2026): Substituição de GERAREQUESTOITEMNOTA por BD_FAT_FATURAMENTO com pré-agregação de notas por IDPRODUTO_ROMANEIO e CTE materializada de status, reduzindo timeout para ~3.0s.
============================================================================= */

WITH ROM_BASE AS (
    SELECT /*+ MATERIALIZE */
           RO.NUMERO_ROMANEIO,
           RO.STATUS
      FROM SGTPRD.ROMANEIO RO
     WHERE RO.STATUS <> 5
       AND RO.DATAEMISSAO >= TO_NUMBER(TO_CHAR(SYSDATE - 30, 'YYYYMMDD'))
),
ENUM_STATUS AS (
    SELECT /*+ MATERIALIZE */
           ENI.SEQUENCE AS STATUS,
           TRIM(ENI.DESCRIPTION) AS STATUS_ROM
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TSTATUSROMANEIO%'
),
FAT_ROM AS (
    SELECT /*+ MATERIALIZE */
           FAT.IDPRODUTO_ROMANEIO,
           MAX(FAT.NUMERONOTA) AS NOTA_FISCAL
      FROM SGTPRD.BD_FAT_FATURAMENTO FAT
      JOIN SGTPRD.NOTAFISCALCAPA NFC ON NFC.NRNOTA = FAT.NUMERONOTA
     WHERE NFC.STNOTAFATURAMENTO <> 2
       AND NFC.IDFILIAL = 1
       AND NFC.ID = DECODE(NFC.CDGRUPONOTA, NULL, NFC.ID, NFC.CDGRUPONOTA)
     GROUP BY FAT.IDPRODUTO_ROMANEIO
)
SELECT DES.NUMERO_OB,
       PRO.NUMERO_ROMANEIO AS ROMANEIO,
       RO.STATUS,
       ENS.STATUS_ROM,
       PRO.NUMERO_PECAS AS PECAS_LIDAS,
       ROUND(PRO.QUANTIDADE_KILOS, 2) AS QT_LIQUIDA,
       FAT.NOTA_FISCAL
  FROM ROM_BASE RO
  JOIN SGTPRD.PRODUTO_ROMANEIO PRO ON PRO.NUMERO_ROMANEIO = RO.NUMERO_ROMANEIO
  JOIN SGTPRD.GERAPECAROMSAIDA ROP ON ROP.NUMERO_ROMANEIO_SAID = RO.NUMERO_ROMANEIO
  JOIN SGTPRD.GERAPECADESTINOOB DES ON DES.IDPECASPRODUTO = ROP.IDPECASPRODUTO
  LEFT JOIN ENUM_STATUS ENS ON ENS.STATUS = RO.STATUS
  LEFT JOIN FAT_ROM FAT ON FAT.IDPRODUTO_ROMANEIO = PRO.IDPRODUTO_ROMANEIO
 GROUP BY DES.NUMERO_OB,
          PRO.NUMERO_ROMANEIO,
          RO.STATUS,
          ENS.STATUS_ROM,
          PRO.NUMERO_PECAS,
          PRO.QUANTIDADE_KILOS,
          FAT.NOTA_FISCAL
 ORDER BY PRO.NUMERO_ROMANEIO DESC
 FETCH FIRST 100 ROWS ONLY
