/* =============================================================================
OBJETIVO: Liga OB no Pedido Comercial
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\Liga OB no Pedido Comercial.sql
TIPO: Comercial, Pedidos e Expedição
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMDATAS, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

--CREATE OR REPLACE VIEW SGTPRD.VW_GAB_LIGA_OBPEDIDO AS
SELECT PED.CD_SUBTIPOPED                           AS SUB_TIPO,
       PED.SITUACAO                                AS SIT_PED,
       PED.BLOQUEIOFATURAMENTO                     AS BLQ_FAT,
       PED.DESCBLOQFATURAMENTO                     AS DESCR_BLQ,
       TRIM(PED.PEDIDOCLIENTE)                     AS P_CLIENTE,
       PED.NUMERO_NOTA_FISCAL                      AS NFE,
       ITP.ITEMPEDIDOCLIENTE                       AS CD_CLIENTE,
       ITP.CD_DESENHO_CLIENTE                      AS REF_CLIENTE,
       TRIM(ITP.OBS)                               AS OBS_ITEM,
       IPG.PEDIDO                                  AS PEDIDO,
       IPG.ITEMPEDIDO                              AS ITEM_PEDIDO,
       IPG.SITUACAOITEM                            AS SIT_ITEM,
       IPG.REDUZIDOITEM                            AS REDUZ,
       ITP.CD_DESENHO_CLIENTE                      AS REF_CLT,
       ITP.QUALIDADE_SINTETICA                     AS QS,
       TO_DATE(IPQ.EXPEDIREM, 'YYYY/MM/DD')        AS DT_ENTREGA,
       PED.IDFILIALRESPONSAVEL                     AS ID_CLT,
       PPOB.NUMEROOB                               AS NR_OB,
       OFP.NUMEROOF                                AS NR_OF,
       OFP.QUANTIDADE                              AS QUANTIDADE,
       OFP.QUANTIDADE_ATUAL                        AS QUANTIDADE_ATUAL,
       ROUND(DECODE(OFP.QUANTIDADE, 0, OFO.QUANTIDADE, OFP.QUANTIDADE), 2) AS QT_PROGRAMADA
FROM SGTPRD.OFPEDIDO OFP
INNER JOIN SGTPRD.ITENSPEDIDOQTDES IPQ
    ON OFP.IDITENSPEDIDOQTDES = IPQ.IDITENSPEDIDOQTDES
INNER JOIN SGTPRD.ITENSPEDIDOGRADE IPG
    ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
INNER JOIN SGTPRD.OFORDENS OFO
    ON OFO.NUMEROOF = OFP.NUMEROOF
INNER JOIN SGTPRD.PEDPRODUCAO PP
    ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
INNER JOIN SGTPRD.PEDPRODUCAOOB PPOB
    ON PPOB.NUMERO = PP.NUMERO
INNER JOIN SGTPRD.PEDIDOCOMDATAS PCD
    ON PCD.PEDIDO = IPG.PEDIDO
INNER JOIN SGTPRD.PEDIDOCOMERCIAL PED
    ON PED.PEDIDO = IPG.PEDIDO
INNER JOIN SGTPRD.ITENSPEDIDOCOMERCIAL ITP
    ON ITP.PEDIDO = IPG.PEDIDO
    AND ITP.ITEMPEDIDO = IPG.ITEMPEDIDO
    AND PCD.ITEMPEDIDO = IPG.ITEMPEDIDO
    AND PPOB.NUMERO = OFO.NUMEROPEDPRODUCAO
    AND OFP.NIVEL = OFO.NIVEL
    AND OFP.REDUZIDO = OFO.REDUZIDO
WHERE IPG.PEDIDO = 9250
--AND PPOB.NUMEROOB = 76764
--AND OFP.NUMEROOF = 91571
--AND IPG.PEDIDO BETWEEN 7340 AND 7347;

