/* =============================================================================
OBJETIVO: Romaneios e status de expedição para OBs em aberto no processo
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s e Romaneios - Em Aberto.sql
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (escopo restrito a ordens ativas em chão de fábrica: OB.STATUS <> 0)
TABELAS PRINCIPAIS: SGTPRD.FASES_FLUXO, SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAROMSAIDA, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.ROMANEIO, SGTPRD.TIPO_ACONDICIONAMENT, SGTPRD.UNIDADE_MEDIDA, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO (22/09/2026): Restrição cirúrgica em OB_ALVO para ordens ativas (STATUS <> 0), desmontagem de subqueries correlacionadas em favor de CTEs materializadas com hints LEADING e USE_NL pelos índices de NUMERO_OB. Redução de timeout para ~2.8s.
AUDITORIA (29/09/2026): removido o teto FETCH FIRST 100 ROWS ONLY. Em 29/09 a consulta devolve 712 linhas;
  com o teto a auditoria mostrava só 100 (14%) e escondia o resto sem aviso.
============================================================================= */

WITH
  OB_ALVO AS (
    SELECT /*+ MATERIALIZE */
           OB.NUMERO_OB,
           OB.CODIGO_REDUZIDO,
           OB.STATUS,
           OB.TIPO_ORDEM,
           OB.DATA_ENTREGA_PEDIDO,
           OB.TEMPO_INICIO_PRODUCA
      FROM SGTPRD.OB OB
     WHERE OB.TIPO_ORDEM IN (0, 6)
       AND OB.STATUS <> 0
  ),
  FASE_ATUAL_CTE AS (
    SELECT /*+ MATERIALIZE LEADING(ALV OBF FFL) USE_NL(OBF FFL) */
           OBF.NUMERO_OB,
           MIN(OBF.SEQUENCIA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS SEQUENCIA,
           MIN(OBF.CODIGO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS CODIGO_FASE,
           MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS DESCR_FASE,
           MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS STATUS
      FROM OB_ALVO ALV
      JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = ALV.NUMERO_OB
      JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
     WHERE OBF.STATUS <> 4
     GROUP BY OBF.NUMERO_OB
  ),
  ULTIMA_CONF_CTE AS (
    SELECT /*+ MATERIALIZE LEADING(ALV OBF) USE_NL(OBF) */
           OBF.NUMERO_OB,
           MAX(OBF.TEMPO_FINAL_CONFIRMA) KEEP (DENSE_RANK LAST ORDER BY OBF.SEQUENCIA) AS TEMPO_FINAL_CONFIRMA
      FROM OB_ALVO ALV
      JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = ALV.NUMERO_OB
     WHERE OBF.TEMPO_FINAL_CONFIRMA IS NOT NULL
     GROUP BY OBF.NUMERO_OB
  ),
  PECAS_RESUMO AS (
    SELECT /*+ MATERIALIZE LEADING(ALV GPD GPP GPC ACO) USE_NL(GPD GPP GPC ACO) */
           GPD.NUMERO_OB,
           COUNT(GPP.IDPECASPRODUTO) AS TOTAL_PECAS,
           SUM(GPP.QTLIQUIDA) AS TOTAL_LIQUIDO,
           SUM(GPC.PESO_BRUTO) AS TOTAL_BRUTO,
           SUM(ACO.PESO) AS TOTAL_TARA
      FROM OB_ALVO ALV
      JOIN SGTPRD.GERAPECADESTINOOB GPD ON GPD.NUMERO_OB = ALV.NUMERO_OB
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPD.IDPECASPRODUTO
      LEFT JOIN SGTPRD.GERAPECACOMPLPECA GPC ON GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
      LEFT JOIN SGTPRD.TIPO_ACONDICIONAMENT ACO ON ACO.IDACONDICIONAMENTO = GPP.IDACONDICIONAMENTO
     WHERE GPP.CODIGO_REGISTRO = 2
     GROUP BY GPD.NUMERO_OB
  ),
  ROMANEIO_DISTINCT AS (
    SELECT DISTINCT
           ALV.NUMERO_OB,
           ROM.NUMERO_ROMANEIO,
           ROM.STATUS AS STATUS_ROMANEIO
      FROM OB_ALVO ALV
      JOIN SGTPRD.GERAPECADESTINOOB GPD ON GPD.NUMERO_OB = ALV.NUMERO_OB
      JOIN SGTPRD.GERAPECAROMSAIDA GPR ON GPR.IDPECASPRODUTO = GPD.IDPECASPRODUTO
      JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = GPR.NUMERO_ROMANEIO_SAID
     WHERE ROM.STATUS <> 5
  ),
  ROMANEIO_RESUMO AS (
    SELECT /*+ MATERIALIZE */
           NUMERO_OB,
           LISTAGG(NUMERO_ROMANEIO, ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY NUMERO_ROMANEIO) AS ROMANEIOS,
           MAX(STATUS_ROMANEIO) AS STATUS_ROMANEIO
      FROM ROMANEIO_DISTINCT
     GROUP BY NUMERO_OB
  ),
  STATUS_OB_CTE AS (
    SELECT /*+ MATERIALIZE */ ENI.SEQUENCE AS STATUS, TRIM(ENI.DESCRIPTION) AS DESCRICAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TSTATUSOB%'
  ),
  STATUS_FASE_CTE AS (
    SELECT /*+ MATERIALIZE */ ENI.SEQUENCE AS STATUS, TRIM(ENI.DESCRIPTION) AS DESCRICAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TOBFASESSTATUS%'
  ),
  PEDIDO_RESUMO AS (
    SELECT /*+ MATERIALIZE LEADING(ALV PPOB PP OFO OFP IPQ IPG PED) USE_NL(PPOB PP OFO OFP IPQ IPG PED) */
           PPOB.NUMEROOB,
           MIN(PED.PEDIDO) AS PEDIDO,
           MIN(TRIM(PED.PEDIDOCLIENTE)) AS PEDIDOCLIENTE,
           MIN(TO_DATE(IPQ.EXPEDIREM, 'YYYYMMDD')) AS DATA_ENTREGA
      FROM OB_ALVO ALV
      JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMEROOB = ALV.NUMERO_OB
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
     WHERE PED.IDFILIALRESPONSAVEL = 1
     GROUP BY PPOB.NUMEROOB
  )
SELECT ALV.NUMERO_OB AS NR_OB,
       PED.PEDIDO AS NR_PEDIDO,
       PED.PEDIDOCLIENTE AS NR_PROGRAMACAO,
       ITE.CODIGO_REDUZIDO AS CD_REDUZIDO,
       TRIM(ITE.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO,
       TRIM(ITE.DESCRICAO) AS DS_PRODUTO,
       SOB.DESCRICAO AS ST_OB,
       FAS.CODIGO_FASE AS CD_FASE_ATUAL,
       FAS.DESCR_FASE AS DS_FASE_ATUAL,
       SFA.DESCRICAO AS ST_FASE_ATUAL,
       NVL(PEC.TOTAL_PECAS, 0) AS QT_PECAS,
       NVL(PEC.TOTAL_LIQUIDO, 0) AS PESO_LIQUIDO,
       NVL(PEC.TOTAL_BRUTO, 0) AS PESO_BRUTO,
       ROM.ROMANEIOS AS ROMANEIOS_SAIDA,
       PED.DATA_ENTREGA AS DT_ENTREGA,
       CASE WHEN UC.TEMPO_FINAL_CONFIRMA IS NOT NULL
            THEN DATE '1996-01-01' + UC.TEMPO_FINAL_CONFIRMA / 1440
            WHEN ALV.TEMPO_INICIO_PRODUCA > 0
            THEN DATE '1996-01-01' + ALV.TEMPO_INICIO_PRODUCA / 1440
       END AS DATA_ULT_MOVIMENTO
  FROM OB_ALVO ALV
  JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = ALV.CODIGO_REDUZIDO
  LEFT JOIN PEDIDO_RESUMO PED ON PED.NUMEROOB = ALV.NUMERO_OB
  LEFT JOIN FASE_ATUAL_CTE FAS ON FAS.NUMERO_OB = ALV.NUMERO_OB
  LEFT JOIN ULTIMA_CONF_CTE UC ON UC.NUMERO_OB = ALV.NUMERO_OB
  LEFT JOIN PECAS_RESUMO PEC ON PEC.NUMERO_OB = ALV.NUMERO_OB
  LEFT JOIN ROMANEIO_RESUMO ROM ON ROM.NUMERO_OB = ALV.NUMERO_OB
  LEFT JOIN STATUS_OB_CTE SOB ON SOB.STATUS = ALV.STATUS
  LEFT JOIN STATUS_FASE_CTE SFA ON SFA.STATUS = FAS.STATUS
 ORDER BY ALV.NUMERO_OB DESC
