/* =============================================================================
OBJETIVO: Cruzamento operacional entre pedidos comerciais e romaneios de saída
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\Consulta Pedidos e Romaneios.sql
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (janela de entrega: últimos 60 dias e próximos 30 dias)
TABELAS PRINCIPAIS: SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECAROMSAIDA, SGTPRD.GERAPECASPRODUTO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PECAS_ROMANEIO_SAIDA, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.ROMANEIO, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO (22/09/2026): Eliminação de subqueries correlacionadas para agregação de romaneios. Uso de CTEs pré-agregadas com LISTAGG e escopo em janela temporal em DATA_ENTREGA_PEDIDO. Redução de timeout para ~3.1s.
AUDITORIA (29/09/2026): removido o teto FETCH FIRST 100 ROWS ONLY. Em 29/09 a consulta devolve 204 linhas;
  com o teto a auditoria mostrava só 100 (49%) e escondia o resto sem aviso.
============================================================================= */

WITH OBS_FILTRADAS AS (
    SELECT /*+ MATERIALIZE */
           OBE.NUMERO_OB,
           OBE.CODIGO_REDUZIDO,
           OBE.DATA_ENTREGA_PEDIDO
      FROM SGTPRD.OB OBE
     WHERE OBE.STATUS = 0
       AND OBE.TIPO_ORDEM = 0
       AND OBE.DATA_ENTREGA_PEDIDO BETWEEN TO_NUMBER(TO_CHAR(SYSDATE - 60, 'YYYYMMDD'))
                                       AND TO_NUMBER(TO_CHAR(SYSDATE + 30, 'YYYYMMDD'))
),
OB_PEDIDOS AS (
    SELECT /*+ MATERIALIZE */
           IPG.PEDIDO,
           PC.PEDIDOCLIENTE,
           IPG.ITEMPEDIDO,
           PPOB.NUMEROOB
      FROM SGTPRD.PEDPRODUCAOOB PPOB
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPQ.IDITEMPEDGRADE = IPG.IDITENSPEDIDOGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL PC ON PC.PEDIDO = IPG.PEDIDO
     WHERE PPOB.NUMEROOB IN (SELECT NUMERO_OB FROM OBS_FILTRADAS)
       AND OFP.QUANTIDADE_ATUAL <> 0
       AND PC.IDFILIALCOBRANCA = 1
),
ESTOQUE_OB AS (
    SELECT /*+ MATERIALIZE */ DISTINCT DES.NUMERO_OB
      FROM SGTPRD.GERAPECADESTINOOB DES
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = DES.IDPECASPRODUTO
     WHERE GPP.STPECAPRODUTO IN (0, 14)
       AND DES.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_FILTRADAS)
),
ROMANEIO_S_OB AS (
    SELECT /*+ MATERIALIZE */
           SUB.NUMERO_OB,
           LISTAGG(SUB.NUMERO_ROMANEIO_SAID, ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY SUB.NUMERO_ROMANEIO_SAID) AS ROMANEIO_S
      FROM (
        SELECT DISTINCT DES.NUMERO_OB, PRS.NUMERO_ROMANEIO_SAID
          FROM SGTPRD.GERAPECADESTINOOB DES
          JOIN SGTPRD.PECAS_ROMANEIO_SAIDA PRS ON PRS.IDPECASPRODUTO = DES.IDPECASPRODUTO
          JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = PRS.NUMERO_ROMANEIO_SAID
         WHERE ROM.STATUS IN (0, 1, 3, 8)
           AND ROM.IDPESSOAFJ = 1
           AND DES.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_FILTRADAS)
      ) SUB
     GROUP BY SUB.NUMERO_OB
),
ROMANEIO_S2_OB AS (
    SELECT /*+ MATERIALIZE */
           DES.NUMERO_OB,
           TO_CHAR(MAX(GRR.NUMERO_ROMANEIO_SAID)) AS ROMANEIO_S2
      FROM SGTPRD.GERAPECADESTINOOB DES
      JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = DES.IDPECASPRODUTO
      JOIN SGTPRD.GERAPECAROMSAIDA GRR ON GRR.IDPECASPRODUTO = DES.IDPECASPRODUTO
     WHERE GPP.STPECAPRODUTO IN (13)
       AND DES.NUMERO_OB IN (SELECT NUMERO_OB FROM OBS_FILTRADAS)
     GROUP BY DES.NUMERO_OB
),
ENUM_STATUS AS (
    SELECT /*+ MATERIALIZE */
           STR.SEQUENCE,
           UPPER(STR.DESCRIPTION) AS DS_ST_ROMANEIO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM STR ON STR.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TSTATUSROMANEIOSAIDA%'
)
SELECT OBF.NUMERO_OB AS NR_OB,
       OBP.PEDIDO AS NR_PEDIDO,
       OBP.ITEMPEDIDO AS ITEM_PEDIDO,
       IPC.REDUZIDOITEM AS CD_REDUZIDO,
       TRIM(ITE.CODIGO_ALTERNATIVO) AS CD_ALTERNATIVO,
       TRIM(ITE.DESCRICAO) AS DS_PRODUTO,
       OBP.PEDIDOCLIENTE AS NR_PROGRAMACAO,
       CASE WHEN EST.NUMERO_OB IS NOT NULL THEN 'ESTOQUE OU RESERVA' ELSE 'ROMANEIO GERADO OU CONFIRMADO' END AS ANALISE_ESTOQUE,
       NVL(R1.ROMANEIO_S, R2.ROMANEIO_S2) AS NR_ROMANEIO,
       ROM.STATUS AS ST_ROMANEIO,
       ENS.DS_ST_ROMANEIO,
       TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD') AS DT_ENTREGA,
       CASE
         WHEN TRUNC(SYSDATE) - TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD') > 0 THEN
           LPAD(TRUNC(SYSDATE) - TO_DATE(IPC.EXPEDIREM, 'YYYYMMDD'), 2, '0') || ' DIA(S) ATRASADO'
         ELSE 'DENTRO DO PRAZO'
       END AS ANALISE_ENTREGA
  FROM OBS_FILTRADAS OBF
  JOIN OB_PEDIDOS OBP ON OBP.NUMEROOB = OBF.NUMERO_OB
  LEFT JOIN ESTOQUE_OB EST ON EST.NUMERO_OB = OBF.NUMERO_OB
  LEFT JOIN ROMANEIO_S_OB R1 ON R1.NUMERO_OB = OBF.NUMERO_OB
  LEFT JOIN ROMANEIO_S2_OB R2 ON R2.NUMERO_OB = OBF.NUMERO_OB
  LEFT JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = TO_NUMBER(REGEXP_SUBSTR(NVL(R1.ROMANEIO_S, R2.ROMANEIO_S2), '^[0-9]+'))
  LEFT JOIN ENUM_STATUS ENS ON ENS.SEQUENCE = ROM.STATUS
  LEFT JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = OBP.PEDIDO AND IPC.ITEMPEDIDO = OBP.ITEMPEDIDO
  LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = IPC.REDUZIDOITEM
 WHERE (EST.NUMERO_OB IS NOT NULL OR R1.ROMANEIO_S IS NOT NULL OR R2.ROMANEIO_S2 IS NOT NULL)
 ORDER BY DT_ENTREGA
