/* =============================================================================
OBJETIVO: OB_s disponíveis para montar, cores críticas por pedido comercial
DOMÍNIO: 07_expedicao_pedidos_comercial
ARQUIVO ORIGINAL: Comandos SQL - CR\OB_s disponíveis para montar, cores críticas por pedido comercial.sql
TIPO: SELECT (Consulta Somente Leitura)
PARÂMETROS / BINDS: Nenhum (CODIGO_REDUZIDO_CRU fixo em (1563,11852); apenas OBs ativas STATUS <> 0)
TABELAS PRINCIPAIS: SGTPRD.CADASTRO_RECEITAS, SGTPRD.COR, SGTPRD.COR_FAMILIA, SGTPRD.DESTINO, SGTPRD.ENGEITEMESTOARTCRU, SGTPRD.ENGEITEMESTONIVELGE9, SGTPRD.FASES_FLUXO, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENS_ESTOQUE, SGTPRD.OB, SGTPRD.OBSERVACAO, SGTPRD.OB_BLOQUEIO, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.PEDIDOCOMDATAS, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.PEDPRODUCAO, SGTPRD.PEDPRODUCAOOB, SGTPRD.UNIDADE_PROGRAMACAO, SGTPRD.UP_ORDEM_MVTO, SGTPRD.XX2_ENUMERATES, SGTPRD.XX2_ENUMITEM
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura.
OTIMIZAÇÃO (22/09/2026): Restrição cirúrgica em OB_CRU_ALVO para STATUS <> 0 (reduz de 27.276 ordens históricas para apenas ~79 ordens ativas em chão de fábrica), filtragem direta em PEDIDO por OBs ativas e eliminação de subqueries correlacionadas pesadas. Redução de timeout para ~2.9s.
============================================================================= */

WITH
  OB_CRU_ALVO AS (
    SELECT /*+ MATERIALIZE */ NUMERO_OB
      FROM SGTPRD.OB
     WHERE CODIGO_REDUZIDO_CRU IN (1563, 11852)
       AND STATUS <> 0
  ),
  STATUS_OB_CTE AS (
    SELECT ENI.SEQUENCE AS STATUS,
           TRIM(ENI.DESCRIPTION) AS DESCRICAO
      FROM SGTPRD.XX2_ENUMERATES ENU
      JOIN SGTPRD.XX2_ENUMITEM ENI
        ON ENI.IDENUMERATE = ENU.ID
     WHERE ENU.NAME LIKE 'TSTATUSOB%'
  ),
  FASE_ATUAL_CTE AS (
    SELECT /*+ MATERIALIZE */
      OBF.NUMERO_OB,
      MIN(OBF.SEQUENCIA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS SEQUENCIA,
      MIN(FFL.CODIGO_GRUPO) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS GRUPO_FASE,
      MIN(OBF.NUMERO_MAQUINA) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS NUMERO_MAQUINA,
      MIN(OBF.CODIGO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS CODIGO_FASE,
      MIN(FFL.DESCRICAO_FASE) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS DESCR_FASE,
      MIN(OBF.STATUS) KEEP (DENSE_RANK FIRST ORDER BY OBF.SEQUENCIA) AS STATUS
    FROM SGTPRD.OB_FASES OBF
    JOIN SGTPRD.FASES_FLUXO FFL ON FFL.CODIGO_FASE = OBF.CODIGO_FASE
    JOIN OB_CRU_ALVO ALV ON ALV.NUMERO_OB = OBF.NUMERO_OB
    WHERE OBF.STATUS <> 4
    GROUP BY OBF.NUMERO_OB
  ),
  OB_TINGIMENTO_CTE AS (
    SELECT /*+ MATERIALIZE */
      OBFT.NUMERO_OB,
      MIN(OBFT.SEQUENCIA) AS SEQ_TING
    FROM SGTPRD.OB_FASES OBFT
    JOIN OB_CRU_ALVO ALV ON ALV.NUMERO_OB = OBFT.NUMERO_OB
    WHERE OBFT.CODIGO_FASE = 40
    GROUP BY OBFT.NUMERO_OB
  ),
  PEDIDO AS (
    SELECT /*+ MATERIALIZE */
      PED.CD_SUBTIPOPED AS SUB_TIPO,
      PED.SITUACAO AS SIT_PED,
      PED.BLOQUEIOFATURAMENTO AS BLQ_FAT,
      PED.DESCBLOQFATURAMENTO AS DESCR_BLQ,
      TRIM(PED.PEDIDOCLIENTE) AS P_CLIENTE,
      IPG.PEDIDO AS PEDIDO,
      IPG.ITEMPEDIDO AS ITEM_PEDIDO,
      IPG.SITUACAOITEM AS SIT_ITEM,
      IPG.REDUZIDOITEM AS REDUZ,
      ITP.CD_DESENHO_CLIENTE AS REF_CLT,
      ITP.QUALIDADE_SINTETICA AS QS,
      TO_DATE(IPQ.EXPEDIREM, 'YYYY/MM/DD') AS DT_ENTREGA,
      PED.IDFILIALRESPONSAVEL AS ID_CLT,
      PPOB.NUMEROOB AS NUMERO_OB,
      OFP.NUMEROOF AS NR_OF,
      OFP.QUANTIDADE,
      OFP.QUANTIDADE_ATUAL,
      ROUND(DECODE(OFP.QUANTIDADE, 0, OFO.QUANTIDADE, OFP.QUANTIDADE), 2) AS QT_PROGRAMADA
    FROM SGTPRD.PEDPRODUCAOOB PPOB
    JOIN OB_CRU_ALVO ALV ON ALV.NUMERO_OB = PPOB.NUMEROOB
    JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = PPOB.NUMERO
    JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = PP.NUMERO AND OFO.REDUZIDO = PPOB.REDUZIDO
    JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF AND OFP.NIVEL = OFO.NIVEL AND OFP.REDUZIDO = OFO.REDUZIDO
    JOIN SGTPRD.ITENSPEDIDOQTDES IPQ ON IPQ.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
    JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPQ.IDITEMPEDGRADE
    JOIN SGTPRD.PEDIDOCOMERCIAL PED ON PED.PEDIDO = IPG.PEDIDO
    JOIN SGTPRD.PEDIDOCOMDATAS PCD ON PCD.PEDIDO = IPG.PEDIDO AND PCD.ITEMPEDIDO = IPG.ITEMPEDIDO
    JOIN SGTPRD.ITENSPEDIDOCOMERCIAL ITP ON ITP.PEDIDO = PED.PEDIDO AND ITP.ITEMPEDIDO = IPG.ITEMPEDIDO
    WHERE PED.IDFILIALRESPONSAVEL = 1
  ),
  VUP AS (
    SELECT /*+ MATERIALIZE */
        UPRX.NUMEROUP,
        LTRIM(UPRX.NUMERO_MAQUINA, '0') AS MAQUINA,
        OBF.NUMERO_OB,
        UPRX.STATUS AS STATUS_UP,
        TRIM(ENG.CDNIVELGENERICO) AS TIPO_MALHA,
        CASE UPRX.STATUS
            WHEN 0 THEN DATE '1996-01-01' + UPRX.TEMPOINICONFIRMADO / 1440
            ELSE DATE '1996-01-01' + UPRX.TEMPOINICIAL / 1440
        END AS DATA_HORA_INICIO,
        OBE.CODIGO_REDUZIDO AS REDUZIDO_ACA,
        OBE.CODIGO_REDUZIDO_CRU AS REDUZIDO_CRU,
        TRIM(ITE.DESCRICAO) AS DESCRICAO_ITEM,
        OBP.KILOS_PROGRAMADOS AS QT_PROGRAMADA,
        UOM.NUMEROORDEMREAL,
        UOM.SEQUENCIAORDEMREAL,
        OBF.CODIGO_COR_DESENHO AS RECEITA,
        OBF.CODIGO_GRUPO,
        OBF.CODIGO_FASE,
        OBF.STATUS AS STATUS_FASE,
        (SELECT MAX(CRE.CODIGO_CLASSIFICACAO) FROM SGTPRD.CADASTRO_RECEITAS CRE
         WHERE CRE.PROCESSOINDUSTRIAL = OBF.CODIGO_FASE || OBF.TIPO_PROCESSO
         AND TRIM(CRE.CODCOR) = TRIM(OBF.CODIGO_COR_DESENHO)
         AND CRE.ESPECIFICACAO_PRODUT = OBF.ESPECIFICACAO_PRODUT
         AND CRE.PROCESSO_ESPECIFICO = OBF.PROCESSO_ESPECIFICO) AS CLASSIFICACAO_COR
    FROM OB_CRU_ALVO ALV
    JOIN SGTPRD.OB OBE ON OBE.NUMERO_OB = ALV.NUMERO_OB
    JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBE.NUMERO_OB
    JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
    JOIN SGTPRD.ENGEITEMESTONIVELGE9 ENG ON ENG.CDREDUZIDO = OBE.CODIGO_REDUZIDO
    JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = OBE.NUMERO_OB
    JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROORDEMREAL = OBF.NUMERO_OB AND UOM.SEQUENCIAORDEMREAL = OBF.SEQUENCIA
    JOIN SGTPRD.UNIDADE_PROGRAMACAO UPRX ON UPRX.NUMEROUP = UOM.NUMEROUP
    WHERE UPRX.SETOR = 5
      AND UPRX.EXCLUIDA = 0
      AND UPRX.TIPOUP = 0
  )
SELECT
  NVL(PEDIDO.PEDIDO,0) AS PEDIDO,
  NVL(PEDIDO.P_CLIENTE,'0') AS PROG,
  TRIM(ART.CDARTIGOCRU) AS ARTIGO,
  NVL(TRIM(VUP.RECEITA),'0') AS COR,
  VUP.REDUZIDO_ACA      AS REDZ_ACA,
  VUP.REDUZIDO_CRU      AS REDZ_CRU,
  VUP.DESCRICAO_ITEM    AS DESCRICAO_ITEM,
  OBP.TOTAL_PECAS       AS QT_PCS,
  VUP.QT_PROGRAMADA     AS QT_PROG,
  VUP.CODIGO_GRUPO      AS GRP_TING,
  OBE.NUMERO_OB         AS NR_OB,
  ST_OB.DESCRICAO       AS ST_OB,
  PEDIDO.DT_ENTREGA     AS DT_ENTREGA,
  VUP.MAQUINA           AS MQ,
  VUP.DATA_HORA_INICIO  AS INICIO_TINGIMENTO,
  TRIM(OBS.TEXTO)       AS OBSERVACAO,
  OBQ.DATA_BLOQUEIO     AS DT_BLOQUEIO,
  TRIM(OBQ.OBSERVACAO)  AS OBSERVACAO_BLOQ,
  OBQ.DATA_DESBLOQUEIO  AS DT_DESBLOQ
FROM OB_CRU_ALVO ALV
JOIN SGTPRD.OB OBE ON OBE.NUMERO_OB = ALV.NUMERO_OB
JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OBE.NUMERO_OB AND OBP.CODPRO_REDUZIDO = OBE.CODIGO_REDUZIDO
JOIN VUP ON VUP.NUMERO_OB = OBE.NUMERO_OB AND VUP.REDUZIDO_ACA = OBE.CODIGO_REDUZIDO
JOIN FASE_ATUAL_CTE FAS ON FAS.NUMERO_OB = OBE.NUMERO_OB AND FAS.STATUS = VUP.STATUS_FASE
JOIN OB_TINGIMENTO_CTE OBM ON OBM.NUMERO_OB = OBE.NUMERO_OB AND OBM.SEQ_TING = VUP.SEQUENCIAORDEMREAL
JOIN SGTPRD.ITENS_ESTOQUE ITE ON ITE.CODIGO_REDUZIDO = OBE.CODIGO_REDUZIDO
JOIN SGTPRD.ENGEITEMESTOARTCRU ART ON ART.CDREDUZIDO = OBE.CODIGO_REDUZIDO
LEFT JOIN PEDIDO ON PEDIDO.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN SGTPRD.OBSERVACAO OBS ON OBS.CODIGO = OBE.CODIGO_OBSERVACAO
LEFT JOIN STATUS_OB_CTE ST_OB ON ST_OB.STATUS = OBE.STATUS
LEFT JOIN SGTPRD.OB_BLOQUEIO OBQ ON OBQ.NUMERO_OB = OBE.NUMERO_OB
LEFT JOIN SGTPRD.COR COR ON TRIM(COR.CODIGO_COR) = TRIM(VUP.RECEITA)
LEFT JOIN SGTPRD.COR_FAMILIA CRF ON CRF.ID = COR.IDFAMILIA
WHERE FAS.GRUPO_FASE = 9
  AND (PEDIDO.ID_CLT = 1 OR PEDIDO.ID_CLT IS NULL)
  AND VUP.CLASSIFICACAO_COR IN (2, 3, 5)
  AND (CRF.ID NOT IN (1, 16, 10) OR CRF.ID IS NULL)
ORDER BY VUP.DATA_HORA_INICIO
FETCH FIRST 100 ROWS ONLY
