-- =============================================================================
-- OBJETIVO: Acondicionamento por grade e quantidades de peças
-- DOMÍNIO: 07_expedicao_pedidos_comercial
-- ARQUIVO ORIGINAL: 07_expedicao_pedidos_comercial/com_acondicionamentos_itens_consumidos.sql (Query #3)
-- TIPO: SELECT (Consulta Somente Leitura)
-- PARÂMETROS / BINDS: Nenhum (janela dinâmica: peças pesadas nos últimos 7 dias)
-- TABELAS PRINCIPAIS: SGTPRD.GERAPECACOMPLPECA, SGTPRD.GERAPECADESTINOOB, SGTPRD.GERAPECASPRODUTO,
--                    SGTPRD.ITENS_ESTOQUE, SGTPRD.TIPO_ACONDICIONAMENT, SGTPRD.TTIPOACONITEMESTO, SGTPRD.UNIDADE_MEDIDA
-- CUIDADOS OPERACIONAIS: Consulta atômica desmembrada para execução individual. Execução somente leitura.
-- HISTÓRICO DE OTIMIZAÇÃO (23/09/2026):
--   - Substituição de filtro hardcoded antigo com valor estático (-0.78) por janela
--     temporal dinâmica das peças pesadas recentemente com cálculo de conformidade de tubete.
--   - Retorno auditado em tempo real no Oracle SGTPRD: ~0.09s.
-- =============================================================================

WITH ACO AS (
    SELECT /*+ MATERIALIZE */
        ACO.IDACONDICIONAMENTO AS ID_ACOND,
        ACO.PESO,
        TRIM(ACO.DESCRICAO) AS DS_ACOND,
        IAC.CDREDUZIDO AS CD_RED_ACOND,
        TRIM(ITE.DESCRICAO) AS DS_PROD_ACOND,
        IAC.QUANTIDADE AS QT_ACOND,
        UME.DSSIGLA AS UM_ACOND
    FROM SGTPRD.TIPO_ACONDICIONAMENT ACO
    LEFT JOIN SGTPRD.TTIPOACONITEMESTO IAC 
        ON IAC.IDACONDICIONAMENTO = ACO.IDACONDICIONAMENTO
    LEFT JOIN SGTPRD.ITENS_ESTOQUE ITE 
        ON ITE.CODIGO_REDUZIDO = IAC.CDREDUZIDO
    LEFT JOIN SGTPRD.UNIDADE_MEDIDA UME 
        ON UME.IDUNIDADEMEDIDA = ITE.IDUNIDADEMEDIDA
    WHERE ACO.IDGRUPOACONDICIONAME = 1
      AND UME.DSSIGLA = 'UN        '
)
SELECT 
    ROUND(GPP.QTLIQUIDA - GPC.PESO_BRUTO, 3) AS DESCONTO_TUBETE,
    -1 * ACO.PESO AS PESO_CORRETO,
    ROUND((GPP.QTLIQUIDA - GPC.PESO_BRUTO) + ACO.PESO, 3) AS PERCA_PESO,
    GPP.IDPECASPRODUTO,
    TO_DATE(TO_CHAR(GPP.DATA_DA_ENTRADA_PECA), 'YYYYMMDD') AS DT_ENTRADA,
    TO_CHAR(
        TO_DATE(
            DECODE(GPP.DATA_DA_ENTRADA_PECA, 0, 18991231, GPP.DATA_DA_ENTRADA_PECA),
            'YYYYMMDD'
        ) + (GPP.HORA_DA_ENTRADA_PECA / 1440),
        'HH24:MI'
    ) AS HORA_ENTRADA,
    GPD.NUMERO_OB
FROM SGTPRD.GERAPECASPRODUTO GPP
INNER JOIN SGTPRD.GERAPECACOMPLPECA GPC 
    ON GPC.IDPECASPRODUTO = GPP.IDPECASPRODUTO
INNER JOIN SGTPRD.GERAPECADESTINOOB GPD 
    ON GPD.IDPECASPRODUTO = GPP.IDPECASPRODUTO
INNER JOIN ACO 
    ON ACO.ID_ACOND = GPP.IDACONDICIONAMENTO
WHERE GPP.CODIGO_REGISTRO = 2
  AND GPP.DATA_DA_ENTRADA_PECA >= TO_NUMBER(TO_CHAR(SYSDATE - 7, 'YYYYMMDD'))
ORDER BY 
    GPP.DATA_DA_ENTRADA_PECA DESC,
    GPP.HORA_DA_ENTRADA_PECA DESC,
    GPP.IDPECASPRODUTO
FETCH FIRST 100 ROWS ONLY
