/* =============================================================================
OBJETIVO: Monitoramento Sintético de Programações de Terceiros e Chão de Fábrica
DOMÍNIO: 07_expedicao_pedidos_comercial
TIPO: Consulta Executiva / Painel Sintético de Gestão Comercial, PCP e Diretoria
PARÂMETROS / FILTROS:
  - Pedidos comerciais ativos (TIPOPEDIDO IN (1, 2, 3), SITUACAO não concluída/cancelada)
  - Programação de cliente preenchida (PEDIDOCLIENTE IS NOT NULL)
  - Itens de pedido pendentes de atendimento/faturamento
TABELAS PRINCIPAIS:
  - SGTPRD.PEDIDOCOMERCIAL
  - SGTPRD.PESSOASFJ
  - SGTPRD.ITENSPEDIDOCOMERCIAL
  - SGTPRD.ITENSPEDIDOGRADE
  - SGTPRD.ITENSPEDIDOQTDES
  - SGTPRD.COMPOSICAO_ITEM, SGTPRD.COMPOSICAO_FIBRAS (Engenharia Têxtil)
  - SGTPRD.OFPEDIDO
  - SGTPRD.OFORDENS
  - SGTPRD.PEDPRODUCAO
  - SGTPRD.PEDPRODUCAOOB
  - SGTPRD.OB
  - SGTPRD.OB_PRODUTO
  - SGTPRD.GERAPECAORIGEMOB
  - SGTPRD.GERAPECADESTINOOB
  - SGTPRD.GERAPECAROMSAIDA
  - SGTPRD.ROMANEIO
  - SGTPRD.OB_FASES
  - SGTPRD.FASES_FLUXO
  - SGTPRD.OB_BLOQUEIO
  - SGTPRD.OB_REPROCESSO
CUIDADOS OPERACIONAIS E REVISÃO:
  - Zero views legadas (100% tabelas físicas indexadas).
  - Execução somente leitura sob orçamento estrito (< 2s).
  - Composição Têxtil extraída estritamente das tabelas de ENGENHARIA (COMPOSICAO_ITEM + COMPOSICAO_FIBRAS).
  - Granularidade 1:1 rigorosa: 1 linha por Pedido Comercial / Programação.
  - Balanço de Cobertura Física: confronto entre Saldo Comercial, KGs em OB e KGs a Programar.
  - Avanço Físico Real: leitura de KILOS_ACABADOS e TOTAL_PECAS_CONFIRM de OB_PRODUTO.
  - Rastreamento de Expedição: vinculação de romaneios de saída e status consolidado de faturamento.
  - Proteção contra estouro de string: LISTAGG com ON OVERFLOW TRUNCATE.
============================================================================= */

WITH PEDIDOS_ATIVOS AS (
    SELECT /*+ MATERIALIZE */
           PED.PEDIDO,
           TRIM(PED.PEDIDOCLIENTE)        AS PROGRAMACAO_CLIENTE,
           PED.IDFILIALRESPONSAVEL        AS ID_CLIENTE,
           TRIM(PFJ.NOMEFANTASIA)         AS NOME_CLIENTE,
           PED.BLOQUEIOFATURAMENTO,
           TRIM(PED.DESCBLOQFATURAMENTO)  AS MOTIVO_BLOQ_FAT,
           PED.SITUACAO                   AS SITUACAO_PEDIDO,
           TRUNC(PED.DATEMISSAO)          AS DATA_EMISSAO
      FROM SGTPRD.PEDIDOCOMERCIAL PED
      JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = PED.IDFILIALRESPONSAVEL
     WHERE PED.TIPOPEDIDO IN (1, 2, 3)
       AND PED.SITUACAO NOT IN (6, 12, 13, 14, 18) -- Exclui Cancelados, Concluídos, Encerrados, Atendidos Totais
       AND PED.PEDIDOCLIENTE IS NOT NULL
),
ITENS_RESUMO AS (
    SELECT /*+ MATERIALIZE */
           IPC.PEDIDO,
           MIN(COALESCE(
               IPC.DATAEXPEDIREM, 
               CASE 
                   WHEN NVL(IPC.EXPEDIREM, 0) > 0 
                        THEN TO_DATE(TO_CHAR(IPC.EXPEDIREM) DEFAULT NULL ON CONVERSION ERROR, 'YYYYMMDD') 
               END
           )) AS DATA_ENTREGA_MIN,
           MAX(COALESCE(
               IPC.DATAEXPEDIREM, 
               CASE 
                   WHEN NVL(IPC.EXPEDIREM, 0) > 0 
                        THEN TO_DATE(TO_CHAR(IPC.EXPEDIREM) DEFAULT NULL ON CONVERSION ERROR, 'YYYYMMDD') 
               END
           )) AS DATA_ENTREGA_MAX,
           SUM(NVL(IPC.QUANTIDADE, 0)) AS TOTAL_KG_PROGRAMADO,
           SUM(NVL(IPC.FATURADO, 0))   AS TOTAL_KG_FATURADO,
           SUM(GREATEST(0, NVL(IPC.QUANTIDADE, 0) - NVL(IPC.FATURADO, 0) - NVL(IPC.QTDECANCELADAITEMPED, 0))) AS SALDO_KG_PENDENTE
      FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
      JOIN PEDIDOS_ATIVOS PA ON PA.PEDIDO = IPC.PEDIDO
     WHERE IPC.SITUACAOITEM NOT IN (6, 10, 12, 13, 14, 18)
     GROUP BY IPC.PEDIDO
),
COMPOSICAO_PEDIDO_DISTINCT AS (
    SELECT DISTINCT
           IPC.PEDIDO,
           TRIM(CPF.DESCRICAO) AS FIBRA
      FROM SGTPRD.ITENSPEDIDOCOMERCIAL IPC
      JOIN PEDIDOS_ATIVOS PA ON PA.PEDIDO = IPC.PEDIDO
      JOIN SGTPRD.COMPOSICAO_ITEM CPS ON CPS.CODIGO_REDUZIDO = IPC.REDUZIDOITEM
      JOIN SGTPRD.COMPOSICAO_FIBRAS CPF ON CPF.CODIGO = CPS.CODIGO_DA_COMPOSICAO
     WHERE IPC.SITUACAOITEM NOT IN (6, 10, 12, 13, 14, 18)
),
COMPOSICAO_PEDIDO AS (
    SELECT /*+ MATERIALIZE */
           PEDIDO,
           LISTAGG(FIBRA, ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY FIBRA) AS FIBRAS_ENGENHARIA
      FROM COMPOSICAO_PEDIDO_DISTINCT
     GROUP BY PEDIDO
),
VINCULO_OB AS (
    SELECT /*+ MATERIALIZE */
           IPG.PEDIDO,
           PPOB.NUMEROOB,
           OB.STATUS AS STATUS_OB,
           CASE WHEN OB.TEMPO_INICIO_PRODUCA > 0 THEN DATE '1996-01-01' + OB.TEMPO_INICIO_PRODUCA / 1440 END AS DT_INICIO_PRODUCAO,
           CASE WHEN OB.TEMPO_PROGRAMACAO > 0 THEN DATE '1996-01-01' + OB.TEMPO_PROGRAMACAO / 1440 END AS DT_PROGRAMACAO,
           CASE WHEN OB.TEMPO_EMISSAO_OB > 0 THEN DATE '1996-01-01' + OB.TEMPO_EMISSAO_OB / 1440 END AS DT_EMISSAO_OB
      FROM SGTPRD.ITENSPEDIDOGRADE IPG
      JOIN SGTPRD.ITENSPEDIDOQTDES IPX ON IPX.IDITEMPEDGRADE = IPG.IDITENSPEDIDOGRADE
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.IDITENSPEDIDOQTDES = IPX.IDITENSPEDIDOQTDES
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROOF = OFP.NUMEROOF AND OFO.NIVEL = OFP.NIVEL AND OFO.REDUZIDO = OFP.REDUZIDO
      JOIN SGTPRD.PEDPRODUCAO PP ON PP.NUMERO = OFO.NUMEROPEDPRODUCAO
      JOIN SGTPRD.PEDPRODUCAOOB PPOB ON PPOB.NUMERO = PP.NUMERO AND PPOB.REDUZIDO = OFO.REDUZIDO
      JOIN SGTPRD.OB OB ON OB.NUMERO_OB = PPOB.NUMEROOB
      JOIN PEDIDOS_ATIVOS PA ON PA.PEDIDO = IPG.PEDIDO
     WHERE OB.STATUS <> 0
     GROUP BY IPG.PEDIDO, PPOB.NUMEROOB, OB.STATUS, OB.TEMPO_INICIO_PRODUCA, OB.TEMPO_PROGRAMACAO, OB.TEMPO_EMISSAO_OB
),
OBS_UNICAS AS (
    SELECT /*+ MATERIALIZE */ DISTINCT NUMEROOB FROM VINCULO_OB
),
OB_PECAS AS (
    SELECT /*+ MATERIALIZE */
           OU.NUMEROOB,
           MAX(NVL(OBP.TOTAL_PECAS, 0))               AS PECAS_PROGRAMADAS,
           MAX(NVL(OBP.TOTAL_PECAS_CONFIRM, 0))       AS PECAS_ACABADAS,
           MAX(NVL(OBP.KILOS_PROGRAMADOS, 0))         AS KG_PROGRAMADO_OB,
           MAX(NVL(OBP.KILOS_ACABADOS, 0))            AS KG_ACABADO_OB,
           COUNT(DISTINCT ORI.IDPECASPRODUTO)         AS PECAS_FISICAS_MONTADAS
      FROM OBS_UNICAS OU
      LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = OU.NUMEROOB
      LEFT JOIN SGTPRD.GERAPECAORIGEMOB ORI ON ORI.NUMERO_OB = OU.NUMEROOB
     GROUP BY OU.NUMEROOB
),
OB_FASE_INFO AS (
    SELECT /*+ MATERIALIZE */
           OBF.NUMERO_OB,
           MAX(TRIM(OBF.CODIGO_PLACA)) AS PLACA_KANBAN,
           MAX(CASE WHEN OBF.TEMPO_FINAL_CONFIRMA > 0 THEN DATE '1996-01-01' + OBF.TEMPO_FINAL_CONFIRMA / 1440 END) AS DT_ULT_CONFIRMACAO,
           MAX(CASE WHEN OBF.TEMPO_INICIAL_CONFIR > 0 THEN DATE '1996-01-01' + OBF.TEMPO_INICIAL_CONFIR / 1440 END) AS DT_INICIO_FASE,
           MIN(
               CASE 
                   WHEN OBF.STATUS = 4 THEN '08. CONCLUÍDO'
                   WHEN OBF.CODIGO_FASE BETWEEN 10 AND 26 THEN '01. PREPARAÇÃO'
                   WHEN OBF.CODIGO_FASE BETWEEN 30 AND 47 THEN '02. TINTURARIA'
                   WHEN OBF.CODIGO_FASE BETWEEN 50 AND 60 THEN '03. SECAGEM'
                   WHEN OBF.CODIGO_FASE BETWEEN 65 AND 115 THEN '04. ACABAMENTO'
                   WHEN OBF.CODIGO_FASE BETWEEN 120 AND 145 THEN '05. ESTAMPARIA'
                   WHEN OBF.CODIGO_FASE BETWEEN 150 AND 190 THEN '06. REVISÃO/CQ'
                   ELSE '04. ACABAMENTO'
               END
           ) KEEP (DENSE_RANK FIRST ORDER BY CASE WHEN OBF.STATUS NOT IN (4, 5) THEN 1 ELSE 2 END ASC, OBF.SEQUENCIA ASC) AS MACRO_ETAPA_ATUAL
      FROM SGTPRD.OB_FASES OBF
      JOIN OBS_UNICAS OU ON OU.NUMEROOB = OBF.NUMERO_OB
     WHERE OBF.STATUS <> 5
     GROUP BY OBF.NUMERO_OB
),
ROMANEIOS_DISTINCT AS (
    SELECT DISTINCT
           V.PEDIDO,
           ROM.NUMERO_ROMANEIO
      FROM VINCULO_OB V
      JOIN SGTPRD.GERAPECADESTINOOB GPD ON GPD.NUMERO_OB = V.NUMEROOB
      JOIN SGTPRD.GERAPECAROMSAIDA GPR ON GPR.IDPECASPRODUTO = GPD.IDPECASPRODUTO
      JOIN SGTPRD.ROMANEIO ROM ON ROM.NUMERO_ROMANEIO = GPR.NUMERO_ROMANEIO_SAID
     WHERE ROM.STATUS <> 5
),
ROMANEIOS_PEDIDO AS (
    SELECT /*+ MATERIALIZE */
           PEDIDO,
           LISTAGG(TO_CHAR(NUMERO_ROMANEIO), ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY NUMERO_ROMANEIO) AS ROMANEIOS_EXPEDICAO
      FROM ROMANEIOS_DISTINCT
     GROUP BY PEDIDO
),
OB_STATUS_FLUXO AS (
    SELECT V.PEDIDO,
           V.NUMEROOB,
           OP.PECAS_PROGRAMADAS,
           OP.PECAS_FISICAS_MONTADAS,
           OP.PECAS_ACABADAS,
           OP.KG_PROGRAMADO_OB,
           OP.KG_ACABADO_OB,
           COALESCE(NULLIF(OP.PECAS_FISICAS_MONTADAS, 0), OP.PECAS_PROGRAMADAS, 0) AS TOTAL_PECAS_OB,
           OFI.PLACA_KANBAN,
           OFI.MACRO_ETAPA_ATUAL,
           TRUNC(
               CASE 
                   WHEN SYSDATE - COALESCE(OFI.DT_INICIO_FASE, OFI.DT_ULT_CONFIRMACAO, V.DT_INICIO_PRODUCAO, V.DT_PROGRAMACAO, V.DT_EMISSAO_OB) < 0 THEN 0
                   ELSE SYSDATE - COALESCE(OFI.DT_INICIO_FASE, OFI.DT_ULT_CONFIRMACAO, V.DT_INICIO_PRODUCAO, V.DT_PROGRAMACAO, V.DT_EMISSAO_OB)
               END, 1
           ) AS DIAS_PARADO_FASE,
           CASE WHEN BLQ.NUMERO_OB IS NOT NULL THEN 1 ELSE 0 END AS TEM_BLOQUEIO,
           CASE WHEN REP.NUMERO_OB IS NOT NULL THEN 1 ELSE 0 END AS TEM_REPROCESSO
      FROM VINCULO_OB V
      JOIN OB_PECAS OP ON OP.NUMEROOB = V.NUMEROOB
      LEFT JOIN OB_FASE_INFO OFI ON OFI.NUMERO_OB = V.NUMEROOB
      LEFT JOIN (
          SELECT DISTINCT NUMERO_OB FROM SGTPRD.OB_BLOQUEIO WHERE LIBERADO = 0
      ) BLQ ON BLQ.NUMERO_OB = V.NUMEROOB
      LEFT JOIN (
          SELECT DISTINCT NUMERO_OB FROM SGTPRD.OB_REPROCESSO
      ) REP ON REP.NUMERO_OB = V.NUMEROOB
),
PLACAS_PEDIDO AS (
    SELECT PEDIDO,
           LISTAGG(PLACA_KANBAN, ', ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY PLACA_KANBAN) AS PLACAS_KANBAN
      FROM (
          SELECT DISTINCT PEDIDO, PLACA_KANBAN
            FROM OB_STATUS_FLUXO
           WHERE PLACA_KANBAN IS NOT NULL
      )
     GROUP BY PEDIDO
),
PEDIDO_OBS_RESUMO AS (
    SELECT OSF.PEDIDO,
           COUNT(DISTINCT OSF.NUMEROOB)             AS QTD_OBS_VINCULADAS,
           SUM(OSF.KG_PROGRAMADO_OB)                AS KG_EM_PROCESSO_OB,
           SUM(OSF.KG_ACABADO_OB)                   AS KG_ACABADOS_FABRICA,
           SUM(OSF.PECAS_PROGRAMADAS)               AS PECAS_PROGRAMADAS,
           SUM(OSF.PECAS_FISICAS_MONTADAS)          AS PECAS_FISICAS_MONTADAS,
           SUM(OSF.PECAS_ACABADAS)                  AS PECAS_ACABADAS,
           SUM(OSF.TOTAL_PECAS_OB)                  AS TOTAL_PECAS,
           MAX(OSF.DIAS_PARADO_FASE)                AS MAIOR_DIAS_PARADO_FASE,
           MAX(OSF.TEM_BLOQUEIO)                    AS TEM_OB_BLOQUEADA,
           SUM(OSF.TEM_BLOQUEIO)                    AS QTD_OBS_BLOQUEADAS,
           MAX(OSF.TEM_REPROCESSO)                  AS TEM_REPROCESSO,
           SUM(OSF.TEM_REPROCESSO)                  AS QTD_OBS_REPROCESSO
      FROM OB_STATUS_FLUXO OSF
     GROUP BY OSF.PEDIDO
)
SELECT PA.PROGRAMACAO_CLIENTE,
       PA.ID_CLIENTE,
       PA.NOME_CLIENTE,
       PA.PEDIDO,
       PA.DATA_EMISSAO                      AS DT_EMISSAO_PEDIDO,
       IR.DATA_ENTREGA_MIN                  AS DT_ENTREGA_MIN,
       IR.DATA_ENTREGA_MAX                  AS DT_ENTREGA_MAX,
       CASE 
           WHEN IR.DATA_ENTREGA_MIN IS NULL THEN 'SEM PREVISAO'
           WHEN IR.SALDO_KG_PENDENTE <= 0 THEN 'ATENDIDO TOTAL'
           WHEN TRUNC(SYSDATE) > IR.DATA_ENTREGA_MIN 
                THEN 'ATRASADO (' || TO_CHAR(TRUNC(SYSDATE) - IR.DATA_ENTREGA_MIN) || ' DIAS)'
           WHEN IR.DATA_ENTREGA_MIN - TRUNC(SYSDATE) <= 3 
                THEN 'CRÍTICO (VENCE EM ' || TO_CHAR(IR.DATA_ENTREGA_MIN - TRUNC(SYSDATE)) || ' DIAS)'
           ELSE 'NO PRAZO (' || TO_CHAR(IR.DATA_ENTREGA_MIN - TRUNC(SYSDATE)) || ' DIAS)'
       END AS STATUS_PRAZO,
       NVL(CPE.FIBRAS_ENGENHARIA, 'NÃO CADASTRADA') AS FIBRAS_ENGENHARIA,
       ROUND(IR.TOTAL_KG_PROGRAMADO, 2)     AS KG_CONTRATADO_CLIENTE,
       ROUND(IR.TOTAL_KG_FATURADO, 2)       AS KG_FATURADO,
       ROUND(IR.SALDO_KG_PENDENTE, 2)       AS KG_PENDENTE_ATENDIMENTO,
       CASE 
           WHEN IR.TOTAL_KG_PROGRAMADO > 0 
                THEN ROUND((IR.TOTAL_KG_FATURADO / IR.TOTAL_KG_PROGRAMADO) * 100, 1) || '%'
           ELSE '0%'
       END AS PERC_FATURADO,
       NVL(POR.QTD_OBS_VINCULADAS, 0)       AS QTD_OBS_VINCULADAS,
       ROUND(NVL(POR.KG_EM_PROCESSO_OB, 0), 2) AS KG_EM_OB_TOTAL,
       ROUND(GREATEST(0, IR.SALDO_KG_PENDENTE - NVL(POR.KG_EM_PROCESSO_OB, 0)), 2) AS KG_SALDO_A_PROGRAMAR,
       CASE 
           WHEN IR.SALDO_KG_PENDENTE <= 0 THEN '100%'
           WHEN NVL(POR.KG_EM_PROCESSO_OB, 0) > 0 
                THEN LEAST(100, ROUND((NVL(POR.KG_EM_PROCESSO_OB, 0) / IR.SALDO_KG_PENDENTE) * 100, 1)) || '%'
           ELSE '0%'
       END AS PERC_COBERTURA_PROG,
       ROUND(NVL(POR.KG_ACABADOS_FABRICA, 0), 2) AS KG_ACABADOS_FABRICA,
       NVL(POR.PECAS_PROGRAMADAS, 0)        AS PECAS_PROGRAMADAS,
       NVL(POR.PECAS_FISICAS_MONTADAS, 0)   AS PECAS_MONTADAS_CRU,
       NVL(POR.PECAS_ACABADAS, 0)           AS PECAS_ACABADAS,
       NVL(PP.PLACAS_KANBAN, '-')           AS PLACAS_KANBAN,
       NVL(RP.ROMANEIOS_EXPEDICAO, '-')     AS ROMANEIOS_EXPEDICAO,
       NVL(POR.MAIOR_DIAS_PARADO_FASE, 0)   AS MAIOR_DIAS_PARADO_FASE,
       CASE 
           WHEN IR.SALDO_KG_PENDENTE <= 0 THEN 'FATURADO TOTAL'
           WHEN IR.TOTAL_KG_FATURADO > 0 AND IR.SALDO_KG_PENDENTE > 0 THEN 'PARCIALMENTE FATURADO'
           WHEN RP.ROMANEIOS_EXPEDICAO IS NOT NULL THEN 'EM EXPEDIÇÃO / ROMANEIO'
           WHEN NVL(POR.KG_ACABADOS_FABRICA, 0) >= NVL(POR.KG_EM_PROCESSO_OB, 0) AND NVL(POR.KG_EM_PROCESSO_OB, 0) > 0 
                THEN 'PRODUÇÃO CONCLUÍDA (AGUARDANDO EXPEDIÇÃO)'
           WHEN NVL(POR.QTD_OBS_VINCULADAS, 0) > 0 THEN 'EM PROCESSO INDUSTRIAL'
           ELSE 'PENDENTE DE PROGRAMAÇÃO (SEM OB)'
       END AS SITUACAO_EXPEDICAO_GERAL,
       CASE 
           WHEN IR.SALDO_KG_PENDENTE <= 0 
                THEN 'NENHUMA OCORRENCIA (ATENDIDO TOTAL)'
           WHEN PA.BLOQUEIOFATURAMENTO <> 0 
                THEN 'BLOQUEIO COMERCIAL: ' || NVL(PA.MOTIVO_BLOQ_FAT, 'SEM DESCRICAO')
           WHEN NVL(POR.TEM_OB_BLOQUEADA, 0) = 1 
                THEN 'BLOQUEIO INDUSTRIAL: ' || TO_CHAR(POR.QTD_OBS_BLOQUEADAS) || ' OB(S) RETIDA(S)'
           WHEN NVL(POR.QTD_OBS_VINCULADAS, 0) = 0 
                THEN 'ALERTA: PROGRAMAÇÃO SEM NENHUMA OB EMITIDA'
           WHEN TRUNC(SYSDATE) > IR.DATA_ENTREGA_MIN 
                THEN 'ATRASO DE EXPEDICAO'
           WHEN NVL(POR.TEM_REPROCESSO, 0) = 1 
                THEN 'OCORRENCIA: ' || TO_CHAR(POR.QTD_OBS_REPROCESSO) || ' REPROCESSO(S) EM CURSO'
           WHEN NVL(POR.MAIOR_DIAS_PARADO_FASE, 0) > 3
                THEN 'ATENÇÃO: OB PARADA NA FASE HÁ MAIS DE 3 DIAS'
           ELSE 'NENHUMA OCORRENCIA (NORMAL)'
       END AS OCORRENCIA_PRINCIPAL,
       CASE 
           WHEN IR.SALDO_KG_PENDENTE <= 0 
                THEN 'BAIXA'
           WHEN PA.BLOQUEIOFATURAMENTO <> 0 OR NVL(POR.TEM_OB_BLOQUEADA, 0) = 1 OR TRUNC(SYSDATE) - IR.DATA_ENTREGA_MIN > 3
                THEN 'ALTA'
           WHEN TRUNC(SYSDATE) > IR.DATA_ENTREGA_MIN OR NVL(POR.TEM_REPROCESSO, 0) = 1 OR NVL(POR.QTD_OBS_VINCULADAS, 0) = 0
                THEN 'MEDIA'
           ELSE 'BAIXA'
       END AS GRAVIDADE_OCORRENCIA
  FROM PEDIDOS_ATIVOS PA
  JOIN ITENS_RESUMO IR ON IR.PEDIDO = PA.PEDIDO
  LEFT JOIN COMPOSICAO_PEDIDO CPE ON CPE.PEDIDO = PA.PEDIDO
  LEFT JOIN PEDIDO_OBS_RESUMO POR ON POR.PEDIDO = PA.PEDIDO
  LEFT JOIN PLACAS_PEDIDO PP ON PP.PEDIDO = PA.PEDIDO
  LEFT JOIN ROMANEIOS_PEDIDO RP ON RP.PEDIDO = PA.PEDIDO
 ORDER BY IR.DATA_ENTREGA_MIN ASC NULLS LAST, PA.PROGRAMACAO_CLIENTE ASC;
