# pylint: disable=all
# mypy: ignore-errors
"""Constantes compartilhadas do Orchestrator."""

ORCHESTRATOR_VERSION = "6.5.4"
WORKER_VERSION = "6.5.4"
ORCHESTRATOR_SCHEMA_VERSION = "2026.05.17.1"
ORCHESTRATOR_CONTRACT_VERSION = "2026.05.18.1"

EXECUTION_STATUS_PENDING = "PENDING"
EXECUTION_STATUS_RUNNING = "RUNNING"
EXECUTION_STATUS_SUCCESS = "SUCCESS"
EXECUTION_STATUS_ERROR = "ERROR"
EXECUTION_STATUS_TIMEOUT = "TIMEOUT"
EXECUTION_STATUS_TERMINATED = "TERMINATED"
EXECUTION_STATUS_FAILED_BY_REBOOT = "FAILED_BY_REBOOT"
EXECUTION_STATUS_REQUEUED = "REQUEUED"

EXECUTION_ACTIVE_STATUSES = {
    EXECUTION_STATUS_PENDING,
    EXECUTION_STATUS_RUNNING,
}

EXECUTION_TERMINAL_STATUSES = {
    EXECUTION_STATUS_SUCCESS,
    EXECUTION_STATUS_ERROR,
    EXECUTION_STATUS_TIMEOUT,
    EXECUTION_STATUS_TERMINATED,
    EXECUTION_STATUS_FAILED_BY_REBOOT,
}

EXECUTION_QUEUEABLE_SOURCE_STATUSES = EXECUTION_TERMINAL_STATUSES | {
    EXECUTION_STATUS_REQUEUED,
}

EXECUTION_ALLOWED_STATUSES = (
    EXECUTION_ACTIVE_STATUSES
    | EXECUTION_TERMINAL_STATUSES
    | {EXECUTION_STATUS_REQUEUED}
)

PRIORITY_HIGH = "HIGH"
PRIORITY_NORMAL = "NORMAL"
PRIORITY_LOW = "LOW"
EXECUTION_ALLOWED_PRIORITIES = {PRIORITY_HIGH, PRIORITY_NORMAL, PRIORITY_LOW}

SEVERITY_INFO = "INFO"
SEVERITY_WARN = "WARN"
SEVERITY_ERROR = "ERROR"
DIAGNOSTIC_SEVERITIES = {SEVERITY_INFO, SEVERITY_WARN, SEVERITY_ERROR}

ACTION_CODE_BACKUP = "backup"
ACTION_CODE_CHECKPOINT = "checkpoint"
ACTION_CODE_PURGE = "purge"
ACTION_CODE_SCHEDULER_RELOAD = "scheduler_reload"
ACTION_CODE_WORKER_WAKEUP = "worker_wakeup"
ACTION_CODE_WORKER_RECOVER = "worker_recover"
ACTION_CODE_PAUSE_ALL = "pause_all"
ACTION_CODE_RESUME_ALL = "resume_all"

RECOVERY_ACTION_NONE = "NONE"
RECOVERY_ACTION_REQUEUE_MANUAL = "REQUEUE_MANUAL"
RECOVERY_ACTION_REQUEUED_TO_NEW_EXECUTION = "REQUEUED_TO_NEW_EXECUTION"
RECOVERY_ACTION_REQUEUE_IF_SAFE = "REQUEUE_IF_SAFE"
RECOVERY_ACTION_REAUTHENTICATE_WHATSAPP_SESSION = "REAUTHENTICATE_WHATSAPP_SESSION"
RECOVERY_ACTION_REVIEW_AUTOMATION_REGISTRY = "REVIEW_AUTOMATION_REGISTRY"
RECOVERY_ACTION_REVIEW_CHANNEL_STATE_BEFORE_REQUEUE = (
    "REVIEW_CHANNEL_STATE_BEFORE_REQUEUE"
)
RECOVERY_ACTION_REVIEW_LOGS_AND_OPTIONALLY_REQUEUE = (
    "REVIEW_LOGS_AND_OPTIONALLY_REQUEUE"
)
RECOVERY_ACTION_REVIEW_LOGS_BEFORE_REQUEUE = "REVIEW_LOGS_BEFORE_REQUEUE"
RECOVERY_ACTION_REVIEW_TIMEOUT_AND_REQUEUE = "REVIEW_TIMEOUT_AND_REQUEUE"
RECOVERY_ACTION_REVIEW_WORKER_LOGS = "REVIEW_WORKER_LOGS"

FAILURE_REASON_AUTOMATION_NOT_FOUND = "AUTOMATION_NOT_FOUND"
FAILURE_REASON_CHANNEL_DELIVERY_FAILED = "CHANNEL_DELIVERY_FAILED"
FAILURE_REASON_INTERNAL_WORKER_ERROR = "INTERNAL_WORKER_ERROR"
FAILURE_REASON_MAX_RUNTIME_EXCEEDED = "MAX_RUNTIME_EXCEEDED"
FAILURE_REASON_ORCHESTRATOR_REBOOT = "ORCHESTRATOR_REBOOT"
FAILURE_REASON_USER_TERMINATED = "USER_TERMINATED"
FAILURE_REASON_WHATSAPP_SESSION_EXPIRED = "WHATSAPP_SESSION_EXPIRED"
