# pylint: disable=all
# mypy: ignore-errors
"""Constantes compartilhadas do Orchestrator."""

ORCHESTRATOR_VERSION = "6.4.0"
WORKER_VERSION = "6.4.0"
ORCHESTRATOR_SCHEMA_VERSION = "2026.05.17.1"

EXECUTION_STATUS_PENDING = "PENDING"
EXECUTION_STATUS_RUNNING = "RUNNING"
EXECUTION_STATUS_SUCCESS = "SUCCESS"
EXECUTION_STATUS_ERROR = "ERROR"
EXECUTION_STATUS_TIMEOUT = "TIMEOUT"
EXECUTION_STATUS_TERMINATED = "TERMINATED"
EXECUTION_STATUS_FAILED_BY_REBOOT = "FAILED_BY_REBOOT"
EXECUTION_STATUS_REQUEUED = "REQUEUED"

EXECUTION_ACTIVE_STATUSES = {
    EXECUTION_STATUS_PENDING,
    EXECUTION_STATUS_RUNNING,
}

EXECUTION_TERMINAL_STATUSES = {
    EXECUTION_STATUS_SUCCESS,
    EXECUTION_STATUS_ERROR,
    EXECUTION_STATUS_TIMEOUT,
    EXECUTION_STATUS_TERMINATED,
    EXECUTION_STATUS_FAILED_BY_REBOOT,
}

EXECUTION_QUEUEABLE_SOURCE_STATUSES = EXECUTION_TERMINAL_STATUSES | {
    EXECUTION_STATUS_REQUEUED,
}

EXECUTION_ALLOWED_STATUSES = (
    EXECUTION_ACTIVE_STATUSES
    | EXECUTION_TERMINAL_STATUSES
    | {EXECUTION_STATUS_REQUEUED}
)

PRIORITY_HIGH = "HIGH"
PRIORITY_NORMAL = "NORMAL"
PRIORITY_LOW = "LOW"
EXECUTION_ALLOWED_PRIORITIES = {PRIORITY_HIGH, PRIORITY_NORMAL, PRIORITY_LOW}

SEVERITY_INFO = "INFO"
SEVERITY_WARN = "WARN"
SEVERITY_ERROR = "ERROR"
DIAGNOSTIC_SEVERITIES = {SEVERITY_INFO, SEVERITY_WARN, SEVERITY_ERROR}
