/* =============================================================================
OBJETIVO: Liga Reduzido nas Classes e Sub-Grupos
DOMÍNIO: 09_pcp_kpis_gestao
ARQUIVO ORIGINAL: Comandos SQL - CR\Liga Reduzido nas Classes e Sub-Grupos.sql
TIPO: PCP e Produção
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.CLASSE_INSUMO, SGTPRD.ENGEITEMESTOCLASSE, SGTPRD.GRUPO_INSUMO, SGTPRD.ITENS_ESTOQUE, SGTPRD.SUBGRUPO_INSUMO
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
============================================================================= */

SELECT
  ITE.CODIGO_REDUZIDO,
  ITE.DESCRICAO,
  ENG.CDGRUPO,
  GRU.DESCRICAO_GRUPO,
  ENG.CDSUBGRUPO,
  SUB.DESCRICAO_SUBGRUPO,
  ENG.CDCLASSE,
  CLI.DESCRICAO_CLASSE
FROM
  SGTPRD.ITENS_ESTOQUE ITE
  INNER JOIN SGTPRD.ENGEITEMESTOCLASSE ENG
    ON ENG.CDREDUZIDO = ITE.CODIGO_REDUZIDO
  INNER JOIN SGTPRD.CLASSE_INSUMO CLI
    ON ENG.CDGRUPO = CLI.CODIGO_GRUPO
    AND ENG.CDSUBGRUPO = CLI.CODIGO_SUBGRUPO
  INNER JOIN SGTPRD.SUBGRUPO_INSUMO SUB
    ON ENG.CDGRUPO = SUB.CODIGO_GRUPO
    AND ENG.CDSUBGRUPO = SUB.CODIGO_SUBGRUPO
  INNER JOIN SGTPRD.GRUPO_INSUMO GRU
    ON ENG.CDGRUPO = GRU.CODIGO_GRUPO

