/* =============================================================================
OBJETIVO: Consulta Mensal de Produção por Fase (Comparativo Mês Atual vs Mesmo Mês Ano Anterior - YoY)
          com Indicadores de Gestão Fabril (Acerto de 1ª / RFT, Carga Média de Barca,
          Escoamento Acabamento/Tinturaria, Rendimento Global, Ritmo Diário, Mix de Cores, Tempos e Turnos).
DOMÍNIO: 09_pcp_kpis_gestao
DESTINO: Divulgação em Grupo de WhatsApp de Líderes e Gestão Fabril (Costa Rica Malhas).
TIPO: SELECT (Painel Analítico / Operacional)
PARÂMETROS / BINDS:
  - Formato padrão de data: DD-MM-AAAA
  - Configurado via CTE JANELA para comparar mês fechado com mesmo mês do ano anterior (YoY).
CUIDADOS OPERACIONAIS & DIRETRIZES DE ENGENHARIA ORACLE:
  - Zero Views: Junção direta pelas tabelas físicas com índices operacionais (sem views legadas).
  - Pré-Agregação de Alta Performance: Redução de ~50k apontamentos brutos para blocos pré-agregados,
    reduzindo a cardinalidade submetida aos joins dimensionais.
  - Produção de Acabado Oficial por Peça: Dados de produto acabado extraídos da movimentação oficial por peça
    (SGTPRD.BD_PRD_MOVPROD com NUM_TIPO_MOVIMENTO = 37 e CODIGO IN (1, 8)), trazendo volume em kg, quantidade de peças/rolos
    e peso médio por peça, conforme padrão canônico do PCP.
  - Joins Condicionais por Fase: Junções de receitas restritas à Fase 40.
  - Regra de Reprocesso: DESTINO_RECEITA IN (2, 4).
      * Grupo de Defeito 1 (Beneficiamento), 3 (Benef. Acabamento) e 4: Reprocesso Beneficiamento (Interno).
      * Demais Grupos: Reprocesso Outros Setores (Malharia, Fiação, Facção - Externo).
  - Controle de Mix de Cores & Gráficos de Tingimento (Fase 40):
      * 1. Claras / Branco / Marfim: Gráficos curtos (~1,5h a 3,0h)
      * 2. Cores Médias: Gráficos intermediários (~3,5h a 4,5h)
      * 3. Cores Escuras & Preto: Gráficos longos (~4,5h a 5,5h)
      * 4. Especiais & 2 Fibras: Gráficos extra-longos (~5,5h a 8,0h)
  - Nomenclatura Operacional Normalizada (Chão de Fábrica):
      * 00A a 00F: Indicadores de Gestão (Acerto de 1ª RFT, Reprocesso Interno/Externo, Escoamento, Balanço de Fluxo Embalado/Cru, Carga Média)
       * Nota Metodológica KPI 00E: Indicador mensal de balanço de fluxo/throughput (kg embalado no mês / kg montagem de cru no mês);
         não rastreia nem expressa rendimento físico por coorte de lote/OB.
      * Fases: Montagem de Lote, Revisão Malha Crua, Virar Moletom, Barcas de Tinturaria, Hidros, Secadores, Rama, Produto Acabado
      * Resumo de Fluxo: Tubular (90), Ramado Aberto (91), Estampado Acabado (92), Proporção Tubular/Ramado (93) e Auditoria Não Classificado (94, condicional a ocorrências).
============================================================================= */

WITH JANELA AS (
    SELECT ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)  AS DT_INICIO,
           TRUNC(SYSDATE, 'MM')                  AS DT_FIM,
           ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -13) AS DT_INICIO_ANT,
           ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AS DT_FIM_ANT
      FROM DUAL
),
BASE_FASES_AGR AS (
    SELECT CASE WHEN UPR.DTPRODFIM >= JAN.DT_INICIO     AND UPR.DTPRODFIM < JAN.DT_FIM     THEN 'ATUAL'
                WHEN UPR.DTPRODFIM >= JAN.DT_INICIO_ANT AND UPR.DTPRODFIM < JAN.DT_FIM_ANT THEN 'ANTERIOR'
           END AS PERIODO,
           OBF.CODIGO_FASE,
           NVL(OBF.DESTINO_RECEITA, 1) AS DESTINO_RECEITA,
           TRIM(OBF.GRUPO_DEFEITO) AS GRUPO_DEFEITO,
           MAQ.GRUPO AS GRUPO_MAQUINA,
           UPR.NUMERO_MAQUINA,
           UPR.NRTURNOFIM AS TURNO,
           CL.CODIGO_CLASSIFICACAO,
           TRUNC(UPR.DTPRODFIM) AS DIA,
           SUM(OBF.KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
           COUNT(DISTINCT OBF.NUMERO_OB || '-' || TO_CHAR(OBF.SEQUENCIA)) AS QT_PARTIDAS,
           SUM(CASE WHEN CR.TEMPO_RECEITA > 0 THEN OBF.KILOS_PRODUZIDOS * CR.TEMPO_RECEITA END) AS POND_TEMPO_PREV,
           SUM(CASE WHEN CR.TEMPO_RECEITA > 0 THEN OBF.KILOS_PRODUZIDOS END) AS KG_TEMPO_PREV_VALIDO,
           SUM(CASE WHEN UPR.DTTEMPOFINALCONFIRMA > UPR.DTTEMPOINICONFIRMADO
                    THEN OBF.KILOS_PRODUZIDOS * (UPR.DTTEMPOFINALCONFIRMA - UPR.DTTEMPOINICONFIRMADO) * 24 END) AS POND_TEMPO_REAL,
           SUM(CASE WHEN UPR.DTTEMPOFINALCONFIRMA > UPR.DTTEMPOINICONFIRMADO THEN OBF.KILOS_PRODUZIDOS END) AS KG_TEMPO_REAL_VALIDO
      FROM SGTPRD.UNIDADE_PROGRAMACAO   UPR
      JOIN SGTPRD.UP_ORDEM_MVTO          UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN SGTPRD.OB_FASES               OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL
                                            AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
      LEFT JOIN SGTPRD.MAQUINA           MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA AND MAQ.SETOR = 5
      LEFT JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR ON LCR.ID_LIGA_CADREC_ITEMR = OBF.ID_LIGA_CADREC_ITEMR AND OBF.CODIGO_FASE = 40
      LEFT JOIN SGTPRD.CADASTRO_RECEITAS CR  ON CR.CODIGO_REDUZIDO_RECE = LCR.CODIGO_REDUZIDO_RECE
      LEFT JOIN SGTPRD.CLASSIFICACAO_COR CL  ON CL.CODIGO_CLASSIFICACAO = CR.CODIGO_CLASSIFICACAO
     CROSS JOIN JANELA                   JAN
     WHERE UPR.SETOR = 5
       AND UPR.EXCLUIDA = 0
       AND UPR.TIPOUP = 0
       AND UPR.STATUS = 0
       AND (
             (UPR.DTPRODFIM >= JAN.DT_INICIO     AND UPR.DTPRODFIM < JAN.DT_FIM)
          OR (UPR.DTPRODFIM >= JAN.DT_INICIO_ANT AND UPR.DTPRODFIM < JAN.DT_FIM_ANT)
           )
       AND OBF.CODIGO_FASE IN (10, 20, 26, 40, 50, 55, 60, 65, 70, 80, 90, 100, 110)
     GROUP BY CASE WHEN UPR.DTPRODFIM >= JAN.DT_INICIO     AND UPR.DTPRODFIM < JAN.DT_FIM     THEN 'ATUAL'
                   WHEN UPR.DTPRODFIM >= JAN.DT_INICIO_ANT AND UPR.DTPRODFIM < JAN.DT_FIM_ANT THEN 'ANTERIOR'
              END,
              OBF.CODIGO_FASE,
              NVL(OBF.DESTINO_RECEITA, 1),
              TRIM(OBF.GRUPO_DEFEITO),
              MAQ.GRUPO,
              UPR.NUMERO_MAQUINA,
              UPR.NRTURNOFIM,
              CL.CODIGO_CLASSIFICACAO,
              TRUNC(UPR.DTPRODFIM)
),
BASE_ACABADO_AGR AS (
    -- Pré-agrega por item/dia/turno ANTES de juntar com os cadastros de item (centenas de itens vs ~137 mil peças).
    SELECT MV.PERIODO,
           MV.TURNO,
           NVL(TRIM(E9.CDNIVELGENERICO), 'N/C') AS FLUXO,
           CASE WHEN MV.ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END AS IS_ESTAMPADO,
           MV.DIA,
           SUM(MV.QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           SUM(MV.QT_PECAS) AS QT_PECAS
      FROM (
            SELECT CASE WHEN MVP.PRODUCAO_DATA >= JAN.DT_INICIO     AND MVP.PRODUCAO_DATA < JAN.DT_FIM     THEN 'ATUAL'
                        WHEN MVP.PRODUCAO_DATA >= JAN.DT_INICIO_ANT AND MVP.PRODUCAO_DATA < JAN.DT_FIM_ANT THEN 'ANTERIOR'
                   END AS PERIODO,
                   MVP.PRODUCAO_TURNO AS TURNO,
                   MVP.REDUZIDO_ITEM,
                   MVP.ESTAMPADO,
                   TRUNC(MVP.PRODUCAO_DATA) AS DIA,
                   SUM(MVP.QUANTIDADE_REAL) AS QUANTIDADE_REAL,
                   COUNT(MVP.IDPECASPRODUTO) AS QT_PECAS
              FROM SGTPRD.BD_PRD_MOVPROD MVP
             CROSS JOIN JANELA JAN
             WHERE MVP.NUM_TIPO_MOVIMENTO = 37
               AND MVP.CODIGO IN (1, 8)
               AND (
                     (MVP.PRODUCAO_DATA >= JAN.DT_INICIO     AND MVP.PRODUCAO_DATA < JAN.DT_FIM)
                  OR (MVP.PRODUCAO_DATA >= JAN.DT_INICIO_ANT AND MVP.PRODUCAO_DATA < JAN.DT_FIM_ANT)
                   )
             GROUP BY CASE WHEN MVP.PRODUCAO_DATA >= JAN.DT_INICIO     AND MVP.PRODUCAO_DATA < JAN.DT_FIM     THEN 'ATUAL'
                           WHEN MVP.PRODUCAO_DATA >= JAN.DT_INICIO_ANT AND MVP.PRODUCAO_DATA < JAN.DT_FIM_ANT THEN 'ANTERIOR'
                      END,
                      MVP.PRODUCAO_TURNO,
                      MVP.REDUZIDO_ITEM,
                      MVP.ESTAMPADO,
                      TRUNC(MVP.PRODUCAO_DATA)
           ) MV
      LEFT JOIN SGTPRD.ENGEITEMESTONIVELGE9 E9 ON E9.CDREDUZIDO = MV.REDUZIDO_ITEM
      LEFT JOIN SGTPRD.ITENS_ESTOQUE        ITE ON ITE.CODIGO_REDUZIDO = MV.REDUZIDO_ITEM
     GROUP BY MV.PERIODO,
              MV.TURNO,
              NVL(TRIM(E9.CDNIVELGENERICO), 'N/C'),
              CASE WHEN MV.ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END,
              MV.DIA
),
REFS AS (
    SELECT SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 10 THEN F.KILOS_PRODUZIDOS END) AS KG_MONT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 10 THEN F.KILOS_PRODUZIDOS END) AS KG_MONT_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_NORM_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_NORM_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA IN (2, 4) AND F.GRUPO_DEFEITO IN ('1', '3', '4') THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_INT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA IN (2, 4) AND F.GRUPO_DEFEITO IN ('1', '3', '4') THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_INT_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA IN (2, 4) AND NVL(F.GRUPO_DEFEITO, ' ') NOT IN ('1', '3', '4') THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_EXT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA IN (2, 4) AND NVL(F.GRUPO_DEFEITO, ' ') NOT IN ('1', '3', '4') THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_EXT_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 40 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_TOT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_TOT_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 40 THEN F.QT_PARTIDAS END) AS PART_TING_TOT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 THEN F.QT_PARTIDAS END) AS PART_TING_TOT_ANT,
           COUNT(DISTINCT CASE WHEN F.PERIODO = 'ATUAL' AND F.CODIGO_FASE = 40 THEN F.DIA END) AS DIAS_TING_ATU,
           COUNT(DISTINCT CASE WHEN F.PERIODO = 'ANTERIOR' AND F.CODIGO_FASE = 40 THEN F.DIA END) AS DIAS_TING_ANT,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE = 60 THEN F.KILOS_PRODUZIDOS END) AS KG_SECADOR_TOT_ATU,
           SUM(CASE WHEN F.PERIODO = 'ATUAL'    AND F.CODIGO_FASE IN (100, 110) THEN F.KILOS_PRODUZIDOS END) AS KG_RAMA_TOT_ATU,
           MAX(A.KG_EMB_TOT_ATU)     AS KG_EMB_TOT_ATU,
           MAX(A.KG_EMB_TOT_ANT)     AS KG_EMB_TOT_ANT,
           MAX(A.PECAS_EMB_TOT_ATU)  AS PECAS_EMB_TOT_ATU,
           MAX(A.PECAS_EMB_TOT_ANT)  AS PECAS_EMB_TOT_ANT,
           MAX(A.DIAS_EMB_ATU)       AS DIAS_EMB_ATU,
           MAX(A.DIAS_EMB_ANT)       AS DIAS_EMB_ANT,
           MAX(A.KG_EMB_TUBULAR_ATU) AS KG_EMB_TUBULAR_ATU,
           MAX(A.KG_EMB_TUBULAR_ANT) AS KG_EMB_TUBULAR_ANT,
           MAX(A.KG_EMB_RAMADO_ATU)  AS KG_EMB_RAMADO_ATU,
           MAX(A.KG_EMB_RAMADO_ANT)  AS KG_EMB_RAMADO_ANT,
           MAX(A.KG_EMB_NC_ATU)      AS KG_EMB_NC_ATU,
           MAX(A.KG_EMB_NC_ANT)      AS KG_EMB_NC_ANT
      FROM BASE_FASES_AGR F
      LEFT JOIN (
           SELECT SUM(CASE WHEN PERIODO = 'ATUAL'    THEN QUANTIDADE_REAL END) AS KG_EMB_TOT_ATU,
                  SUM(CASE WHEN PERIODO = 'ANTERIOR' THEN QUANTIDADE_REAL END) AS KG_EMB_TOT_ANT,
                  SUM(CASE WHEN PERIODO = 'ATUAL'    THEN QT_PECAS END) AS PECAS_EMB_TOT_ATU,
                  SUM(CASE WHEN PERIODO = 'ANTERIOR' THEN QT_PECAS END) AS PECAS_EMB_TOT_ANT,
                  COUNT(DISTINCT CASE WHEN PERIODO = 'ATUAL' THEN DIA END) AS DIAS_EMB_ATU,
                  COUNT(DISTINCT CASE WHEN PERIODO = 'ANTERIOR' THEN DIA END) AS DIAS_EMB_ANT,
                  SUM(CASE WHEN PERIODO = 'ATUAL'    AND FLUXO = 'T' THEN QUANTIDADE_REAL END) AS KG_EMB_TUBULAR_ATU,
                  SUM(CASE WHEN PERIODO = 'ANTERIOR' AND FLUXO = 'T' THEN QUANTIDADE_REAL END) AS KG_EMB_TUBULAR_ANT,
                  SUM(CASE WHEN PERIODO = 'ATUAL'    AND FLUXO = 'R' THEN QUANTIDADE_REAL END) AS KG_EMB_RAMADO_ATU,
                  SUM(CASE WHEN PERIODO = 'ANTERIOR' AND FLUXO = 'R' THEN QUANTIDADE_REAL END) AS KG_EMB_RAMADO_ANT,
                   SUM(CASE WHEN PERIODO = 'ATUAL'    AND FLUXO NOT IN ('T', 'R') THEN QUANTIDADE_REAL END) AS KG_EMB_NC_ATU,
                   SUM(CASE WHEN PERIODO = 'ANTERIOR' AND FLUXO NOT IN ('T', 'R') THEN QUANTIDADE_REAL END) AS KG_EMB_NC_ANT
             FROM BASE_ACABADO_AGR
      ) A ON 1 = 1
),
EXPANDIDO AS (
    SELECT '01'  AS ORDEM, '01 - MONTAGEM DE LOTE (CRU)' AS LINHA, PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, TO_NUMBER(NULL) AS POND_TEMPO_PREV, TO_NUMBER(NULL) AS KG_TEMPO_PREV_VALIDO, TO_NUMBER(NULL) AS POND_TEMPO_REAL, TO_NUMBER(NULL) AS KG_TEMPO_REAL_VALIDO, TO_NUMBER(NULL) AS CAPACIDADE_NOMINAL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 10
    UNION ALL
    SELECT '02' , '02 - REVISÃO MALHA CRUA', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 20
    UNION ALL
    SELECT '03' , '03 - VIRAR MOLETOM (FELPA)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 26
    UNION ALL
    SELECT '04A', '04A - TINTURARIA: BARCA 1000 KG (TG001)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, 1000 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG001'
    UNION ALL
    SELECT '04B', '04B - TINTURARIA: BARCA 600 KG (TG002)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, 600 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG002'
    UNION ALL
    SELECT '04C', '04C - TINTURARIA: BARCA 2000 KG (TG003)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, 2000 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG003'
    UNION ALL
    SELECT '04D', '04 - TINTURARIA: PRODUÇÃO NORMAL', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1
    UNION ALL
    SELECT '04E', '04 - TINTURARIA: REPROCESSO BENEFICIAMENTO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA IN (2, 4) AND GRUPO_DEFEITO IN ('1', '3', '4')
    UNION ALL
    SELECT '04F', '04 - TINTURARIA: REPROCESSO MALHARIA/FIAÇÃO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA IN (2, 4) AND NVL(GRUPO_DEFEITO, ' ') NOT IN ('1', '3', '4')
    UNION ALL
    SELECT '04G', '04 - TINTURARIA: TOTAL GERAL (NORMAL + REPROCESSO)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40
    UNION ALL
    SELECT '04H', '[MIX CORES] 1. CLARAS / BRANCO / MARFIM', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (1, 6, 7, 10, 18)
    UNION ALL
    SELECT '04I', '[MIX CORES] 2. CORES MÉDIAS', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (2)
    UNION ALL
    SELECT '04J', '[MIX CORES] 3. CORES ESCURAS E PRETO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (5, 14)
    UNION ALL
    SELECT '04K', '[MIX CORES] 4. ESPECIAIS E 2 FIBRAS', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (3, 8, 9, 11, 12, 15)
    UNION ALL
    SELECT '04L', '[TURNO TINTURARIA] 1º TURNO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 1
    UNION ALL
    SELECT '04M', '[TURNO TINTURARIA] 2º TURNO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 2
    UNION ALL
    SELECT '04N', '[TURNO TINTURARIA] 3º TURNO', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, POND_TEMPO_PREV, KG_TEMPO_PREV_VALIDO, POND_TEMPO_REAL, KG_TEMPO_REAL_VALIDO, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 3
    UNION ALL
    SELECT '05A', '05A - HIDROEXTRATORA 01', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD01'
    UNION ALL
    SELECT '05B', '05B - HIDROEXTRATORA 02', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD02'
    UNION ALL
    SELECT '05C', '05C - HIDROEXTRATORA 03', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD03'
    UNION ALL
    SELECT '05D', '05 - TOTAL HIDROS EXTRATORES', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55)
    UNION ALL
    SELECT '06A', '06A - SECADOR 01 (ÓLEO TÉRMICO)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC01'
    UNION ALL
    SELECT '06B', '06B - SECADOR 02 (VAPOR)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC02'
    UNION ALL
    SELECT '06C', '06 - TOTAL SECADORES', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60
    UNION ALL
    SELECT '07' , '07 - FELPADEIRA', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 65
    UNION ALL
    SELECT '08' , '08 - CALANDRA DE BRILHO (CL 01)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 70
    UNION ALL
    SELECT '09' , '09 - CALANDRA COMPACTA (CL 02)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 80
    UNION ALL
    SELECT '10' , '10 - ABRIDOR DE MALHA (AB 01)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 90
    UNION ALL
    SELECT '11A', '11A - RAMA 01 (RM 01)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM01'
    UNION ALL
    SELECT '11B', '11B - RAMA 02 (RM 02)', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM02'
    UNION ALL
    SELECT '11C', '11 - TOTAL RAMAS', PERIODO, DIA, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110)
    UNION ALL
    -- Produto Acabado Oficial por Peça (BD_PRD_MOVPROD)
    SELECT '12A', '12 - TOTAL PRODUTO ACABADO (KG)', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR
    UNION ALL
    SELECT '12B', '12 - TOTAL PRODUTO ACABADO (PEÇAS / ROLOS)', PERIODO, DIA, QT_PECAS, QT_PECAS, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR
    UNION ALL
    SELECT '12D', '[TURNO ACABAMENTO] 1º TURNO', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 1
    UNION ALL
    SELECT '12E', '[TURNO ACABAMENTO] 2º TURNO', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 2
    UNION ALL
    SELECT '12F', '[TURNO ACABAMENTO] 3º TURNO', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 3
    UNION ALL
    SELECT '90' , '[FLUXO MALHA] TOTAL TUBULAR', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE FLUXO = 'T'
    UNION ALL
    SELECT '91' , '[FLUXO MALHA] TOTAL RAMADO (ABERTO)', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE FLUXO = 'R'
    UNION ALL
    SELECT '92' , '[FLUXO MALHA] ESTAMPADO ACABADO', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE IS_ESTAMPADO = 1
    UNION ALL
    SELECT '94' , '[FLUXO MALHA] NÃO CLASSIFICADO (AUDITORIA)', PERIODO, DIA, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE FLUXO NOT IN ('T', 'R')
),
AGREGADO AS (
    SELECT ORDEM,
           LINHA,
           SUM(CASE WHEN PERIODO = 'ATUAL'    THEN KILOS_PRODUZIDOS END) AS QT_KG,
           COUNT(DISTINCT CASE WHEN PERIODO = 'ATUAL' THEN DIA END) AS DIAS_PRODUTIVOS,
           SUM(CASE WHEN PERIODO = 'ATUAL'    THEN QT_PARTIDAS END) AS QT_PARTIDAS,
           SUM(CASE WHEN PERIODO = 'ANTERIOR' THEN KILOS_PRODUZIDOS END) AS QT_KG_ANT,
           COUNT(DISTINCT CASE WHEN PERIODO = 'ANTERIOR' THEN DIA END) AS DIAS_PRODUTIVOS_ANT,
           SUM(CASE WHEN PERIODO = 'ANTERIOR' THEN QT_PARTIDAS END) AS QT_PARTIDAS_ANT,
           MAX(CAPACIDADE_NOMINAL) AS CAPACIDADE_NOMINAL,
           ROUND(SUM(CASE WHEN PERIODO = 'ATUAL' THEN POND_TEMPO_PREV END)
                 / NULLIF(SUM(CASE WHEN PERIODO = 'ATUAL' THEN KG_TEMPO_PREV_VALIDO END), 0), 2) AS TEMPO_PREV_HORAS,
           ROUND(SUM(CASE WHEN PERIODO = 'ATUAL' THEN POND_TEMPO_REAL END)
                 / NULLIF(SUM(CASE WHEN PERIODO = 'ATUAL' THEN KG_TEMPO_REAL_VALIDO END), 0), 2) AS TEMPO_REAL_HORAS
      FROM EXPANDIDO
     GROUP BY ORDEM, LINHA
),
KPIS_EXECUTIVOS AS (
    SELECT '00A' AS ORDEM,
           '[INDICADOR GESTÃO] ACERTO DE 1ª - TINTURARIA (RFT %)' AS LINHA,
           ROUND(REF.KG_TING_NORM_ATU / NULLIF(REF.KG_TING_TOT_ATU, 0) * 100, 2) AS QT_KG,
           REF.DIAS_TING_ATU AS DIAS_PRODUTIVOS,
           REF.PART_TING_TOT_ATU AS QT_PARTIDAS,
           ROUND(REF.KG_TING_NORM_ANT / NULLIF(REF.KG_TING_TOT_ANT, 0) * 100, 2) AS QT_KG_ANT,
           REF.DIAS_TING_ANT AS DIAS_PRODUTIVOS_ANT,
           REF.PART_TING_TOT_ANT AS QT_PARTIDAS_ANT,
           TO_NUMBER(NULL) AS CAPACIDADE_NOMINAL,
           TO_NUMBER(NULL) AS TEMPO_PREV_HORAS,
           TO_NUMBER(NULL) AS TEMPO_REAL_HORAS
      FROM REFS REF
     UNION ALL
    SELECT '00B',
           '[INDICADOR GESTÃO] REPROCESSO BENEFICIAMENTO (%)',
           ROUND(REF.KG_TING_REP_INT_ATU / NULLIF(REF.KG_TING_NORM_ATU, 0) * 100, 2),
           REF.DIAS_TING_ATU,
           NULL,
           ROUND(REF.KG_TING_REP_INT_ANT / NULLIF(REF.KG_TING_NORM_ANT, 0) * 100, 2),
           REF.DIAS_TING_ANT,
           NULL,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '00C',
           '[INDICADOR GESTÃO] REPROCESSO MALHARIA / FIAÇÃO (%)',
           ROUND(REF.KG_TING_REP_EXT_ATU / NULLIF(REF.KG_TING_NORM_ATU, 0) * 100, 2),
           REF.DIAS_TING_ATU,
           NULL,
           ROUND(REF.KG_TING_REP_EXT_ANT / NULLIF(REF.KG_TING_NORM_ANT, 0) * 100, 2),
           REF.DIAS_TING_ANT,
           NULL,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '00D',
           '[INDICADOR GESTÃO] ESCOAMENTO EMBALADO / TINGIDO (%)',
           ROUND(REF.KG_EMB_TOT_ATU / NULLIF(REF.KG_TING_TOT_ATU, 0) * 100, 2),
           REF.DIAS_EMB_ATU,
           NULL,
           ROUND(REF.KG_EMB_TOT_ANT / NULLIF(REF.KG_TING_TOT_ANT, 0) * 100, 2),
           REF.DIAS_EMB_ANT,
           NULL,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '00E',
           '[INDICADOR GESTÃO] BALANÇO DE FLUXO EMBALADO / CRU (%)',
           ROUND(REF.KG_EMB_TOT_ATU / NULLIF(REF.KG_MONT_ATU, 0) * 100, 2),
           REF.DIAS_EMB_ATU,
           NULL,
           ROUND(REF.KG_EMB_TOT_ANT / NULLIF(REF.KG_MONT_ANT, 0) * 100, 2),
           REF.DIAS_EMB_ANT,
           NULL,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '00F',
           '[INDICADOR GESTÃO] PESO MÉDIO POR PARTIDA (KG)',
           ROUND(REF.KG_TING_TOT_ATU / NULLIF(REF.PART_TING_TOT_ATU, 0), 0),
           REF.DIAS_TING_ATU,
           REF.PART_TING_TOT_ATU,
           ROUND(REF.KG_TING_TOT_ANT / NULLIF(REF.PART_TING_TOT_ANT, 0), 0),
           REF.DIAS_TING_ANT,
           REF.PART_TING_TOT_ANT,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '12C' AS ORDEM,
           '12 - PESO MÉDIO POR PEÇA ACABADA (KG/PEÇA)' AS LINHA,
           ROUND(REF.KG_EMB_TOT_ATU / NULLIF(REF.PECAS_EMB_TOT_ATU, 0), 2) AS QT_KG,
           REF.DIAS_EMB_ATU AS DIAS_PRODUTIVOS,
           REF.PECAS_EMB_TOT_ATU AS QT_PARTIDAS,
           ROUND(REF.KG_EMB_TOT_ANT / NULLIF(REF.PECAS_EMB_TOT_ANT, 0), 2) AS QT_KG_ANT,
           REF.DIAS_EMB_ANT AS DIAS_PRODUTIVOS_ANT,
           REF.PECAS_EMB_TOT_ANT AS QT_PARTIDAS_ANT,
           NULL, NULL, NULL
      FROM REFS REF
     UNION ALL
    SELECT '93' AS ORDEM,
           '[FLUXO MALHA] PROPORÇÃO TUBULAR / RAMADO (%)',
           ROUND(REF.KG_EMB_TUBULAR_ATU / NULLIF(REF.KG_EMB_RAMADO_ATU, 0) * 100, 2),
           REF.DIAS_EMB_ATU,
           NULL,
           ROUND(REF.KG_EMB_TUBULAR_ANT / NULLIF(REF.KG_EMB_RAMADO_ANT, 0) * 100, 2),
           REF.DIAS_EMB_ANT,
           NULL,
           NULL, NULL, NULL
      FROM REFS REF
),
UNIFICADO AS (
    SELECT ORDEM, LINHA, QT_KG, DIAS_PRODUTIVOS, QT_PARTIDAS, QT_KG_ANT, DIAS_PRODUTIVOS_ANT, QT_PARTIDAS_ANT, CAPACIDADE_NOMINAL, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS FROM KPIS_EXECUTIVOS
    UNION ALL
    SELECT ORDEM, LINHA, QT_KG, DIAS_PRODUTIVOS, QT_PARTIDAS, QT_KG_ANT, DIAS_PRODUTIVOS_ANT, QT_PARTIDAS_ANT, CAPACIDADE_NOMINAL, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS FROM AGREGADO
)
SELECT TO_CHAR(JAN.DT_INICIO, 'DD-MM-YYYY') || ' a ' || TO_CHAR(JAN.DT_FIM - 1, 'DD-MM-YYYY') || ' (vs ' || TO_CHAR(JAN.DT_INICIO_ANT, 'MM-YYYY') || ')' AS PERIODO_REFERENCIA,
       TO_CHAR(JAN.DT_INICIO, 'MM-YYYY')   AS COMPETENCIA,
       UNI.ORDEM,
       UNI.LINHA                           AS LINHA_RELATORIO,
       ROUND(NVL(UNI.QT_KG, 0), 2)         AS QT_KG,
       ROUND(NVL(UNI.QT_KG_ANT, 0), 2)     AS QT_KG_ANO_ANT,
       CASE WHEN UNI.ORDEM IN ('00A', '00B', '00C', '00D', '00E', '93') THEN
                 ROUND(NVL(UNI.QT_KG, 0) - NVL(UNI.QT_KG_ANT, 0), 2)
            WHEN UNI.ORDEM IN ('00F', '12C') THEN
                 ROUND(NVL(UNI.QT_KG, 0) - NVL(UNI.QT_KG_ANT, 0), 2)
            ELSE
                 ROUND((NVL(UNI.QT_KG, 0) - UNI.QT_KG_ANT) / NULLIF(UNI.QT_KG_ANT, 0) * 100, 1)
       END AS VAR_YOY_PCT,
       CASE WHEN UNI.ORDEM IN ('00A', '00B', '00C', '00D', '00E', '93') THEN
                 'DIF_PP'
            WHEN UNI.ORDEM IN ('00F', '12C') THEN
                 'DIF_ABS'
            ELSE
                 'VAR_PCT'
       END AS TIPO_VARIACAO_YOY,
       CASE WHEN UNI.ORDEM NOT LIKE '00%' AND UNI.ORDEM NOT IN ('12B', '12C', '93') THEN
            ROUND(NVL(UNI.QT_KG, 0) / NULLIF(UNI.DIAS_PRODUTIVOS, 0), 2)
       END AS MEDIA_KG_DIA,
       CASE WHEN UNI.ORDEM NOT LIKE '00%' AND UNI.ORDEM NOT IN ('12B', '12C', '93') THEN
            ROUND(NVL(UNI.QT_KG_ANT, 0) / NULLIF(UNI.DIAS_PRODUTIVOS_ANT, 0), 2)
       END AS MEDIA_KG_DIA_ANT,
       CASE WHEN UNI.ORDEM NOT LIKE '00%' AND UNI.ORDEM NOT IN ('12B', '12C', '93') AND UNI.DIAS_PRODUTIVOS > 0 AND UNI.DIAS_PRODUTIVOS_ANT > 0 THEN
            ROUND(( (NVL(UNI.QT_KG, 0) / UNI.DIAS_PRODUTIVOS) - (NVL(UNI.QT_KG_ANT, 0) / UNI.DIAS_PRODUTIVOS_ANT) )
                  / NULLIF(NVL(UNI.QT_KG_ANT, 0) / UNI.DIAS_PRODUTIVOS_ANT, 0) * 100, 1)
       END AS VAR_RITMO_PCT,
       UNI.QT_PARTIDAS,
       CASE WHEN UNI.ORDEM = '00F' THEN
                 UNI.QT_KG
            WHEN UNI.ORDEM = '12C' THEN
                 UNI.QT_KG
            WHEN UNI.QT_PARTIDAS > 0 AND UNI.ORDEM NOT LIKE '00%' AND UNI.ORDEM NOT LIKE '12%' THEN
                 ROUND(NVL(UNI.QT_KG, 0) / UNI.QT_PARTIDAS, 0)
       END AS CARGA_MEDIA_KG,
       CASE WHEN UNI.ORDEM IN ('00A', '00B', '00C', '00D', '00E', '93') THEN
                 UNI.QT_KG
            WHEN UNI.ORDEM IN ('04A', '04B', '04C') AND UNI.CAPACIDADE_NOMINAL > 0 THEN
                 ROUND((NVL(UNI.QT_KG, 0) / NULLIF(UNI.QT_PARTIDAS, 0)) / UNI.CAPACIDADE_NOMINAL * 100, 1)
            WHEN UNI.ORDEM IN ('04E', '04F', '04H', '04I', '04J', '04K', '04L', '04M', '04N') THEN
                 ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_TING_NORM_ATU, 0) * 100, 2)
            WHEN UNI.ORDEM IN ('06A', '06B') THEN
                 ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_SECADOR_TOT_ATU, 0) * 100, 2)
            WHEN UNI.ORDEM IN ('11A', '11B') THEN
                 ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_RAMA_TOT_ATU, 0) * 100, 2)
            WHEN UNI.ORDEM IN ('12D', '12E', '12F', '90', '91', '92', '94') THEN
                 ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_EMB_TOT_ATU, 0) * 100, 2)
       END AS PERC_ESPECIFICO,
       CASE WHEN UNI.ORDEM LIKE '00%' THEN
                 CASE UNI.ORDEM
                      WHEN '00A' THEN '% ACERTO DE 1ª (RFT)'
                      WHEN '00B' THEN '% REPROCESSO BENEFICIAMENTO'
                      WHEN '00C' THEN '% REPROCESSO EXTERNO'
                      WHEN '00D' THEN '% ESCOAMENTO (EMBALADO / TINGIDO)'
                      WHEN '00E' THEN '% BALANÇO DE FLUXO (EMB / CRU)'
                      WHEN '00F' THEN 'KG / PARTIDA (TINTURARIA)'
                 END
            WHEN UNI.ORDEM IN ('04A', '04B', '04C') THEN '% CARGA NOMINAL BARCA'
            WHEN UNI.ORDEM IN ('04E', '04F') THEN '% S/ TINGIMENTO NORMAL'
            WHEN UNI.ORDEM IN ('04H', '04I', '04J', '04K') THEN '% MIX DE CORES'
            WHEN UNI.ORDEM IN ('04L', '04M', '04N') THEN '% PARTICIPAÇÃO TURNO TINTURARIA'
            WHEN UNI.ORDEM IN ('06A', '06B') THEN '% CARGA SECADOR (ÓLEO / VAPOR)'
            WHEN UNI.ORDEM IN ('11A', '11B') THEN '% CARGA RAMA (RM 01 / RM 02)'
            WHEN UNI.ORDEM = '12B' THEN 'QUANTIDADE DE PEÇAS / ROLOS'
            WHEN UNI.ORDEM = '12C' THEN 'KG MÉDIO POR PEÇA ACABADA'
            WHEN UNI.ORDEM IN ('12D', '12E', '12F') THEN '% PARTICIPAÇÃO TURNO ACABAMENTO'
            WHEN UNI.ORDEM IN ('90', '91', '92', '94') THEN '% S/ TOTAL PRODUTO ACABADO'
            WHEN UNI.ORDEM = '93' THEN '% PROPORÇÃO TUBULAR / RAMADO'
       END AS TIPO_METRICA,
       UNI.TEMPO_PREV_HORAS,
       UNI.TEMPO_REAL_HORAS,
       CASE WHEN UNI.TEMPO_REAL_HORAS IS NOT NULL AND UNI.TEMPO_PREV_HORAS IS NOT NULL THEN
            ROUND((UNI.TEMPO_REAL_HORAS - UNI.TEMPO_PREV_HORAS) * 60, 0)
       END AS DESVIO_TEMPO_MIN,
       CASE WHEN UNI.TEMPO_REAL_HORAS > 0 AND UNI.TEMPO_PREV_HORAS > 0 THEN
            ROUND((UNI.TEMPO_PREV_HORAS / UNI.TEMPO_REAL_HORAS) * 100, 1)
       END AS EFIC_TEMPO_PCT
  FROM UNIFICADO UNI
 CROSS JOIN JANELA JAN
 CROSS JOIN REFS REF
 ORDER BY UNI.ORDEM;
