/* =============================================================================
OBJETIVO: Balanço e Proporção de Fluxo de Malha (Cru, Facção Pendente e Em Processo)
DOMÍNIO: 09_pcp_kpis_gestao
ARQUIVO ORIGINAL: Novo artefato homologado no acervo (consolidando Estoque, Facção e PCP)
TIPO: PCP / Gestão de Fluxo e Pipeline Produtivo
PARÂMETROS / BINDS: Nenhum (janela móvel de 21 dias para NFs pendentes de pesagem)
TABELAS PRINCIPAIS:
  - SGTPRD.GERAPECASPRODUTO (Estoque Físico de Rolos Cru)
  - SGTPRD.ENGEITEMESTONIVELGE / ENGEITEMESTONIVELGE9 (Nível Genérico Tubular/Ramado)
  - SGTPRD.OB, SGTPRD.OB_FASES, SGTPRD.OB_PRODUTO, SGTPRD.FASES_FLUXO, SGTPRD.GRUPO_FASES (Montagem/Revisão e Processo)
  - SGTPRD.MESTRE_NOTA_ENTRADA, SGTPRD.ITENS_NOTA_ENTRADA, SGTPRD.LOTE_ITENS_NOTA_ENTR (NFs de Facção)
  - SGTPRD.PESSOASFJ, SGTPRD.DEPOSITO, SGTPRD.ITENS_ESTOQUE (Cadastros de Apoio)
CUIDADOS OPERACIONAIS & DIRETRIZES DE ENGENHARIA ORACLE:
  - Consulta analítica somente leitura de alto nível gerencial.
  - OTIMIZAÇÃO (Zero Views): Eliminação de SGTPRD.VW_PI_CBPAP01_PROCBENEF e SGTPRD.VW_BNF_FASEATUALOB,
    substituídas pela CTE determinística FASE_ATUAL_OB com janela ROW_NUMBER() sobre OB_FASES e OB.
  - Regra de Negócio dos Estágios:
      * QTD_CRU: Estoque em galpão (MCP/MCR/MCT) + OBs em Montagem (GF 1) e Revisão (GF 2).
      * QTD_FACAO_PENDENTE: NFs de facção dos últimos 21 dias confirmadas (status 5) sem lote finalizado (stfinalizacao <> 2).
      * EM_PROCESSO: OBs ativas nas fases de Abridor/Rama (Ramado) e Calandras Brilho/Compacta (Tubular).
============================================================================= */

-- =============================================================================
-- 1. VERSÃO PRINCIPAL (OTIMIZADA PARA PRODUÇÃO - ZERO VIEWS)
-- =============================================================================
WITH
    FLUXOS_BASE AS (
        SELECT 'TUBULAR' AS FLUXO FROM DUAL
        UNION ALL
        SELECT 'RAMADO'  AS FLUXO FROM DUAL
    ),
    FASE_ATUAL_OB AS (
        SELECT NUMERO_OB,
               CODIGO_FASE,
               SETOR_SEQUENCIA,
               CODIGO_GRUPO AS GRUPO_FASE,
               PI,
               STATUS,
               CODIGO_FLUXO
          FROM (
            SELECT OBF.NUMERO_OB,
                   OBF.CODIGO_FASE,
                   NVL(GF.SETOR_SEQUENCIA, 0) AS SETOR_SEQUENCIA,
                   FF.CODIGO_GRUPO,
                   (OBF.CODIGO_FASE * 10 + OBF.TIPO_PROCESSO) AS PI,
                   OBF.STATUS,
                   O.CODIGO_FLUXO,
                   ROW_NUMBER() OVER (
                       PARTITION BY OBF.NUMERO_OB
                       ORDER BY OBF.SEQUENCIA ASC
                   ) AS RN
              FROM SGTPRD.OB O
              JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = O.NUMERO_OB
              JOIN SGTPRD.FASES_FLUXO FF ON FF.CODIGO_FASE = OBF.CODIGO_FASE
              LEFT JOIN SGTPRD.GRUPO_FASES GF ON GF.CODIGO = FF.CODIGO_GRUPO
             WHERE O.TIPO_ORDEM IN (0, 6)
               AND O.STATUS <> 0
               AND OBF.STATUS <> 4
          )
         WHERE RN = 1
    ),
    ESTOQUE AS (
        SELECT
            CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END AS FLUXO,
            SUM(NVL(PROD.QTLIQUIDA, 0)) AS QT_ESTOQUE
        FROM SGTPRD.GERAPECASPRODUTO PROD
        JOIN SGTPRD.ENGEITEMESTONIVELGE NIV
             ON NIV.CDREDUZIDO = PROD.CODIGO_REDUZIDO_PROD
        WHERE PROD.PADRAO_QUALIDADE_SIN = 1
          AND PROD.TISITUACAOESTOQUE IN (0, 1)
          AND PROD.STPECAPRODUTO    IN (0, 16, 18)
          AND PROD.CODIGO_DEPOSITO <> 30
          AND TRIM(NIV.IDMASCARATIPOINSUMO) IN ('MCP', 'MCR', 'MCT')
        GROUP BY CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END
    ),
    PRODUCAO AS (
        SELECT
            CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END AS FLUXO,
            SUM(CASE WHEN FASE.GRUPO_FASE = 1 THEN NVL(OBP.KILOS, 0) ELSE 0 END) AS QT_MONTADO,
            SUM(CASE WHEN FASE.GRUPO_FASE = 2 AND FASE.STATUS <> 3 THEN NVL(OBP.KILOS, 0) ELSE 0 END) AS QT_REVISADO
        FROM FASE_ATUAL_OB FASE
        JOIN SGTPRD.OB_PRODUTO OBP
             ON OBP.NUMERO_OB = FASE.NUMERO_OB
        JOIN SGTPRD.ENGEITEMESTONIVELGE9 NIV
             ON NIV.CDREDUZIDO = OBP.CODPRO_REDUZIDO
        WHERE FASE.SETOR_SEQUENCIA IN (10, 20)
        GROUP BY CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END
    ),
    PEC_FINALIZADAS AS (
        SELECT DISTINCT
            NUMERO_NOTA,
            SERIE_NOTA,
            IDPESSOAFJ,
            CODINSREDUZIDO,
            SEQUENCIA_DIGITACAO,
            QUALIDADE
        FROM SGTPRD.LOTE_ITENS_NOTA_ENTR
        WHERE STFINALIZACAO = 2
    ),
    NF_PENDENTES AS (
        SELECT
            CASE WHEN SUBSTR(ITE.CODIGO, 17, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END AS FLUXO,
            SUM(NVL(LTI.QUANTIDADE, 0)) AS QT_TOTAL_NF
        FROM SGTPRD.MESTRE_NOTA_ENTRADA MNE
        JOIN SGTPRD.ITENS_NOTA_ENTRADA INE
             ON INE.NUMERO_NOTA = MNE.NUMERO_NOTA
            AND INE.SERIE_NOTA  = MNE.SERIE_NOTA
            AND INE.IDPESSOAFJ  = MNE.IDPESSOAFJ_CLIENTE
        JOIN SGTPRD.LOTE_ITENS_NOTA_ENTR LTI
             ON LTI.NUMERO_NOTA         = INE.NUMERO_NOTA
            AND LTI.SERIE_NOTA          = INE.SERIE_NOTA
            AND LTI.IDPESSOAFJ          = INE.IDPESSOAFJ
            AND LTI.SEQUENCIA_DIGITACAO = INE.SEQUENCIA_DIGITACAO
            AND LTI.CODINSREDUZIDO      = INE.CODINSREDUZIDO
        JOIN SGTPRD.ITENS_ESTOQUE ITE
             ON ITE.CODIGO_REDUZIDO = INE.CODINSREDUZIDO
        JOIN SGTPRD.PESSOASFJ PES
             ON PES.IDPESSOAFJ = MNE.IDPESSOAFJ_CLIENTE
        JOIN SGTPRD.DEPOSITO DEP
             ON DEP.CODIGO_DEPOSITO = INE.DEPOSITO
            AND DEP.SOCONTROLAQUILOS = '0'
        WHERE MNE.DATA_DA_ENTRADA >= TO_CHAR(TRUNC(CURRENT_DATE, 'IW') - INTERVAL '21' DAY, 'YYYYMMDD')
          AND MNE.STATUS = 5
          AND LTI.QUALIDADE = 1
          AND ITE.TIPO_ITEM = 9
          AND PES.IDCATEGORIFORNECEDOR = 1
          AND NOT EXISTS (
                SELECT 1
                FROM PEC_FINALIZADAS PF
                WHERE PF.NUMERO_NOTA         = LTI.NUMERO_NOTA
                  AND PF.SERIE_NOTA          = LTI.SERIE_NOTA
                  AND PF.IDPESSOAFJ          = LTI.IDPESSOAFJ
                  AND PF.CODINSREDUZIDO      = LTI.CODINSREDUZIDO
                  AND PF.SEQUENCIA_DIGITACAO = LTI.SEQUENCIA_DIGITACAO
                  AND PF.QUALIDADE           = LTI.QUALIDADE
          )
        GROUP BY CASE WHEN SUBSTR(ITE.CODIGO, 17, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END
    ),
    PROCESSO AS (
        SELECT
            CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END AS FLUXO,
            SUM(CASE WHEN FASE.PI IN (451, 901, 1001, 1101) THEN NVL(OBP.KILOS, 0) ELSE 0 END) AS QT_RAMADO_ABRIDOR_RAMA,
            SUM(CASE WHEN FASE.PI IN (451, 501, 551, 601, 701) AND FASE.CODIGO_FLUXO IN (101, 105, 109, 111, 113)
                     THEN NVL(OBP.KILOS, 0) ELSE 0 END) AS QT_TUBULAR_CALANDRA_BRILHO,
            SUM(CASE WHEN FASE.PI IN (451, 501, 551, 601, 651, 801) AND FASE.CODIGO_FLUXO IN (102, 103, 107, 110, 112)
                     THEN NVL(OBP.KILOS, 0) ELSE 0 END) AS QT_TUBULAR_CALANDRA_COMPACTA
        FROM FASE_ATUAL_OB FASE
        JOIN SGTPRD.OB_PRODUTO OBP
             ON OBP.NUMERO_OB = FASE.NUMERO_OB
        JOIN SGTPRD.ENGEITEMESTONIVELGE9 NIV
             ON NIV.CDREDUZIDO = OBP.CODPRO_REDUZIDO
        GROUP BY CASE WHEN SUBSTR(NIV.CDNIVELGENERICO, 1, 1) = 'T' THEN 'TUBULAR' ELSE 'RAMADO' END
    ),
    COMBINADO AS (
        SELECT
            FB.FLUXO,
            NVL(EST.QT_ESTOQUE, 0)                    AS QT_ESTOQUE,
            NVL(PROD.QT_MONTADO, 0)                   AS QT_MONTADO,
            NVL(PROD.QT_REVISADO, 0)                  AS QT_REVISADO,
            NVL(NFP.QT_TOTAL_NF, 0)                   AS QT_FACAO_PENDENTE,
            NVL(PROC.QT_RAMADO_ABRIDOR_RAMA, 0)       AS QT_RAMADO_ABRIDOR_RAMA,
            NVL(PROC.QT_TUBULAR_CALANDRA_BRILHO, 0)   AS QT_TUBULAR_CALANDRA_BRILHO,
            NVL(PROC.QT_TUBULAR_CALANDRA_COMPACTA, 0) AS QT_TUBULAR_CALANDRA_COMPACTA
        FROM FLUXOS_BASE FB
        LEFT JOIN ESTOQUE      EST  ON EST.FLUXO  = FB.FLUXO
        LEFT JOIN PRODUCAO     PROD ON PROD.FLUXO = FB.FLUXO
        LEFT JOIN NF_PENDENTES NFP  ON NFP.FLUXO  = FB.FLUXO
        LEFT JOIN PROCESSO     PROC ON PROC.FLUXO = FB.FLUXO
    ),
    RESUMO_FLUXO AS (
        SELECT
            C.FLUXO,
            (C.QT_ESTOQUE + C.QT_MONTADO + C.QT_REVISADO) AS QTD_CRU,
            C.QT_FACAO_PENDENTE                            AS QTD_FACAO_PENDENTE,
            CASE
                WHEN C.FLUXO = 'RAMADO'
                    THEN C.QT_RAMADO_ABRIDOR_RAMA
                ELSE C.QT_TUBULAR_CALANDRA_BRILHO + C.QT_TUBULAR_CALANDRA_COMPACTA
            END AS EM_PROCESSO
        FROM COMBINADO C
    )
SELECT
    RF.FLUXO,
    ROUND(RF.QTD_CRU, 2)            AS QTD_CRU,
    ROUND(RF.QTD_FACAO_PENDENTE, 2) AS QTD_FACAO_PENDENTE,
    ROUND(RF.EM_PROCESSO, 2)        AS EM_PROCESSO,
    ROUND(RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO, 2) AS TOTAL_GERAL,
    CASE
        WHEN (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO) > 0
            THEN ROUND(RF.QTD_CRU / (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO), 4)
        ELSE 0
    END AS PERC_CRU,
    CASE
        WHEN (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO) > 0
            THEN ROUND(RF.QTD_FACAO_PENDENTE / (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO), 4)
        ELSE 0
    END AS PERC_FACAO,
    CASE
        WHEN (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO) > 0
            THEN ROUND(RF.EM_PROCESSO / (RF.QTD_CRU + RF.QTD_FACAO_PENDENTE + RF.EM_PROCESSO), 4)
        ELSE 0
    END AS PERC_PROCESSO
FROM RESUMO_FLUXO RF
ORDER BY RF.FLUXO DESC
