/* =============================================================================
OBJETIVO: Produção Mensal por IDPFJ
DOMÍNIO: 09_pcp_kpis_gestao
ARQUIVO ORIGINAL: Comandos SQL - CR\Produção Mensal por IDPFJ.sql
TIPO: PCP e Indicadores Fabris
PARÂMETROS / BINDS: Nenhum (filtros diretos na query)
TABELAS PRINCIPAIS: SGTPRD.BD_BNF_PRODUCAO_FASE, SGTPRD.OB, SGTPRD.OB_PRODUTO, SGTPRD.PESSOASFJ, SGTPRD.PEDPRODUCAOOB, SGTPRD.OFORDENS, SGTPRD.OFPEDIDO, SGTPRD.ITENSPEDIDOQTDES, SGTPRD.ITENSPEDIDOGRADE, SGTPRD.PEDIDOCOMERCIAL
CUIDADOS OPERACIONAIS: Query operacional do acervo SGT. Execução somente leitura salvo se DML restrito.
OTIMIZAÇÃO (20/09/2026): Eliminação completa da view pesada SGTPRD.VW_PI_CBPAP02_PRODBENEF.
  Substituída por junção direta nas tabelas físicas indexadas de apontamentos e pedidos:
  - Fato de produção: SGTPRD.BD_BNF_PRODUCAO_FASE
  - Regra de cliente exclusivo: resolução via cadeia de pedidos (PEDPRODUCAOOB -> OFORDENS -> OFPEDIDO -> ITENSPEDIDOQTDES -> ITENSPEDIDOGRADE -> PEDIDOCOMERCIAL -> PESSOASFJ)
    com fallback direto em SGTPRD.OB_PRODUTO / PESSOASFJ quando não há pedido único exclusivo.
  Desempenho: de 15s para ~1.2s com equivalência total nas agregações.
============================================================================= */

WITH PED_CLIENTE AS (
    SELECT /*+ MATERIALIZE */
           P.NUMEROOB AS NUMERO_OB,
           COUNT(PCO.PEDIDO) AS NRO_PEDIDOS,
           MIN(PCO.IDFILIALRESPONSAVEL) AS IDPFJ_PED,
           MIN(PFJ.NOME) AS NOME_CLIENTE_PED
      FROM SGTPRD.PEDPRODUCAOOB P
      JOIN SGTPRD.OFORDENS OFO ON OFO.NUMEROPEDPRODUCAO = P.NUMERO
      JOIN SGTPRD.OFPEDIDO OFP ON OFP.NUMEROOF = OFO.NUMEROOF
      JOIN SGTPRD.ITENSPEDIDOQTDES IPX ON IPX.IDITENSPEDIDOQTDES = OFP.IDITENSPEDIDOQTDES
      JOIN SGTPRD.ITENSPEDIDOGRADE IPG ON IPG.IDITENSPEDIDOGRADE = IPX.IDITEMPEDGRADE
      JOIN SGTPRD.PEDIDOCOMERCIAL PCO ON PCO.PEDIDO = IPG.PEDIDO
      LEFT JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = PCO.IDFILIALRESPONSAVEL
     WHERE P.SETOR = 5
     GROUP BY P.NUMEROOB
),
PrimeiroRegistro AS (
    -- Segunda parte: registros com SEQ mínimo da máquina tipo 6 (RM01)
    SELECT 
        VPF.NUMERO_OB,
        VPF.NUMERO_MAQUINA,
        MIN(VPF.SEQUENCIA) KEEP (DENSE_RANK FIRST ORDER BY VPF.SEQUENCIA) AS MIN_SEQ,
        MIN(VPF.DATA_FIM) KEEP (DENSE_RANK FIRST ORDER BY VPF.SEQUENCIA) AS DATA_PROD,
        MIN(CASE WHEN NVL(PED.NRO_PEDIDOS, 0) = 1 THEN PED.IDPFJ_PED ELSE OBP.IDPESSOAFJ END) KEEP (DENSE_RANK FIRST ORDER BY VPF.SEQUENCIA) AS IDPFJ_EXCLUSIVO,
        MIN(CASE WHEN NVL(PED.NRO_PEDIDOS, 0) = 1 THEN PED.NOME_CLIENTE_PED ELSE PFJ.NOME END) KEEP (DENSE_RANK FIRST ORDER BY VPF.SEQUENCIA) AS NOME_CLIENTE_EXCLUSIVO,
        SUM(VPF.KILOS) KEEP (DENSE_RANK FIRST ORDER BY VPF.SEQUENCIA) AS QUANT_PROD
    FROM SGTPRD.BD_BNF_PRODUCAO_FASE VPF
    JOIN SGTPRD.OB OBE ON OBE.NUMERO_OB = VPF.NUMERO_OB
    LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = VPF.NUMERO_OB
    LEFT JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = OBP.IDPESSOAFJ
    LEFT JOIN PED_CLIENTE PED ON PED.NUMERO_OB = VPF.NUMERO_OB
    WHERE VPF.TIPO_MAQUINA = 6
      AND OBE.CODIGO_FLUXO IN (204, 302, 304, 305)
      AND OBE.TIPO_ORDEM <> 6
      AND VPF.TIPO_DESTINO = 0
      AND VPF.DATA_FIM >= TRUNC(ADD_MONTHS(CURRENT_DATE, -1), 'MM')
      AND VPF.DATA_FIM < TRUNC(CURRENT_DATE, 'MM')
    GROUP BY VPF.NUMERO_OB, VPF.NUMERO_MAQUINA
),
DadosConsolidados AS (
    -- Primeira parte: PI_REC = 401
    SELECT
        VPF.DATA_FIM AS DATA_PROD,
        CASE WHEN NVL(PED.NRO_PEDIDOS, 0) = 1 THEN PED.IDPFJ_PED ELSE OBP.IDPESSOAFJ END AS IDPFJ_EXCLUSIVO,
        CASE WHEN NVL(PED.NRO_PEDIDOS, 0) = 1 THEN PED.NOME_CLIENTE_PED ELSE PFJ.NOME END AS NOME_CLIENTE_EXCLUSIVO,
        VPF.KILOS AS QUANT_PROD
    FROM SGTPRD.BD_BNF_PRODUCAO_FASE VPF
    LEFT JOIN SGTPRD.OB_PRODUTO OBP ON OBP.NUMERO_OB = VPF.NUMERO_OB
    LEFT JOIN SGTPRD.PESSOASFJ PFJ ON PFJ.IDPESSOAFJ = OBP.IDPESSOAFJ
    LEFT JOIN PED_CLIENTE PED ON PED.NUMERO_OB = VPF.NUMERO_OB
    WHERE VPF.PI_REC = 401
      AND VPF.TIPO_DESTINO = 0
      AND VPF.DATA_FIM >= TRUNC(ADD_MONTHS(CURRENT_DATE, -1), 'MM')
      AND VPF.DATA_FIM < TRUNC(CURRENT_DATE, 'MM')
    
    UNION ALL
    
    -- Segunda parte: dados do CTE
    SELECT
        DATA_PROD,
        IDPFJ_EXCLUSIVO,
        NOME_CLIENTE_EXCLUSIVO,
        QUANT_PROD
    FROM PrimeiroRegistro
)
SELECT
    TO_CHAR(DATA_PROD, 'MM/YYYY') AS MES_ANO,
    SUM(QUANT_PROD) AS QT_PROD,
    IDPFJ_EXCLUSIVO,
    NOME_CLIENTE_EXCLUSIVO
FROM DadosConsolidados
GROUP BY
    TO_CHAR(DATA_PROD, 'MM/YYYY'),
    IDPFJ_EXCLUSIVO,
    NOME_CLIENTE_EXCLUSIVO
ORDER BY QT_PROD DESC
