/*
OBJETIVO: Faturamento mensal por comprador com atendimento ao prazo de expedicao fisica
DOMINIO: 09_pcp_kpis_gestao
ARQUIVO ORIGINAL: pcp_faturamento_mensal_cliente_entrega_bi.sql (baseline preservada)
ARQUIVO BASE: pcp_faturamento_mensal_cliente_prazo_expedicao_v2_1.sql (baseline funcional preservada)
CORRECAO FUNCIONAL: meta valida sem saida fisica = Atraso; DIAS_DESVIO_PRAZO permanece NULL
TIPO: Painel/KPI
PARAMETROS / BINDS: Janela automatica: 12 meses fechados + mes corrente
GRAO: Mes de emissao da NF + subtipo + comprador + classe de atendimento + tipo + natureza
TABELAS PRINCIPAIS: SGTPRD.NOTAFISCALCAPA, SGTPRD.NOTAFISCALITENS, SGTPRD.BD_FAT_FATURAMENTO, SGTPRD.ITENS_ESTOQUE, SGTPRD.NATUREZA_OPERACAO, SGTPRD.PRODUTO_ROMANEIO, SGTPRD.PEDIDOCOMERCIAL, SGTPRD.ITENSPEDIDOCOMERCIAL, SGTPRD.COML_SUBTIPOPED, SGTPRD.COML_TIPOSPEDIDOS, SGTPRD.PESSOASFJ, SGTPRD.ROMANEIO, SGTPRD.GERAPECAROMSAIDA, SGTPRD.GERAPECASPRODUTO
SEMANTICA: Data efetiva = ROMANEIO.DATA_EXPEDICAO (saida fisica da empresa); prazo comparado = ITENSPEDIDOCOMERCIAL.DATAEXPEDIREM. Mede atendimento ao prazo de expedicao, nao chegada ao cliente.
GRANULARIDADE INTERNA: FATOS_FILTRADOS/BASE_FATURAMENTO preservam IDPNS + IDPRODUTO_ROMANEIO; contagem agregada de pecas por NUMERO_ROMANEIO + PNS.CDREDUZIDO em subconsulta escalar; DATA_EXPEDICAO numerica YYYYMMDD.
ARQUITETURA V2.2 (ESTABILIZADA): fatos fisicos filtrados estreitos com decomposicao temporal disjunta (UNION ALL), enriquecimento comercial uma vez, COUNT de pecas por chave sem expandir a base principal.
ESTABILIDADE: 5/5 execucoes consecutivas validas comprovadas (04/10/2026), 0 erros ORA-00028, Golden Hash f51ad8d51ecfbcb25b139589ee8e639100bcf4e8215445c2e8cbe6d3d0532fa7.
*/

WITH JANELA AS (
    SELECT ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AS DT_INICIO,
           ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)  AS DT_CORTE,
           TRUNC(SYSDATE) + 1                   AS DT_FIM
      FROM DUAL
),
FATOS_FILTRADOS AS (
    SELECT NSA.DTEMISSAO, NSA.IDPESSOAFJ,
           VFA.PEDIDO, VFA.ITEM_PEDIDO, VFA.NUMERO_ROMANEIO,
           PNS.CDREDUZIDO AS CODIGO_REDUZIDO_PNS,
           ROM.DATA_EXPEDICAO, NAT.DESCOPERACAO,
        CASE
            WHEN PRO.TIITEMPRODROM = 4 THEN 0
            WHEN ROUND(VFA.QUANT, 4) <> ROUND(PNS.QTITEM * VFA.FATOR_ROMANEIO, 4)
                THEN ROUND(PNS.QTITEM * VFA.FATOR_ROMANEIO, 4)
            ELSE VFA.QUANT
        END AS QTD_FATURADA
      FROM SGTPRD.NOTAFISCALCAPA NSA
      CROSS JOIN JANELA JAN
      JOIN SGTPRD.NOTAFISCALITENS PNS
        ON PNS.IDNOTAFISCALCAPA = NSA.ID
       AND PNS.TIITENSFATU = 0
      JOIN SGTPRD.BD_FAT_FATURAMENTO VFA
        ON VFA.IDPNS = PNS.ID
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = VFA.CODIGO_REDUZIDO
      JOIN SGTPRD.NATUREZA_OPERACAO NAT
        ON NAT.IDNATUREZAOPERACAO = PNS.IDNATUOPER
      JOIN SGTPRD.PRODUTO_ROMANEIO PRO
        ON PRO.IDPRODUTO_ROMANEIO = VFA.IDPRODUTO_ROMANEIO
      JOIN SGTPRD.ROMANEIO ROM
        ON ROM.NUMERO_ROMANEIO = VFA.NUMERO_ROMANEIO
     WHERE NSA.IDFILIAL = 1
       AND VFA.FILIALNOTA = 1
       AND ITE.TIPO_ITEM = 10
       AND NSA.STNOTAFATURAMENTO = 3
       AND NVL(TRIM(NAT.ENTRADA), '0') <> '1'
       AND TRIM(NAT.DESCOPERACAO) NOT LIKE 'REMESSA%'
       AND NSA.DTEMISSAO >= JAN.DT_INICIO
       AND NSA.DTEMISSAO < JAN.DT_CORTE
    UNION ALL
    SELECT NSA.DTEMISSAO, NSA.IDPESSOAFJ,
           VFA.PEDIDO, VFA.ITEM_PEDIDO, VFA.NUMERO_ROMANEIO,
           PNS.CDREDUZIDO AS CODIGO_REDUZIDO_PNS,
           ROM.DATA_EXPEDICAO, NAT.DESCOPERACAO,
        CASE
            WHEN PRO.TIITEMPRODROM = 4 THEN 0
            WHEN ROUND(VFA.QUANT, 4) <> ROUND(PNS.QTITEM * VFA.FATOR_ROMANEIO, 4)
                THEN ROUND(PNS.QTITEM * VFA.FATOR_ROMANEIO, 4)
            ELSE VFA.QUANT
        END AS QTD_FATURADA
      FROM SGTPRD.NOTAFISCALCAPA NSA
      CROSS JOIN JANELA JAN
      JOIN SGTPRD.NOTAFISCALITENS PNS
        ON PNS.IDNOTAFISCALCAPA = NSA.ID
       AND PNS.TIITENSFATU = 0
      JOIN SGTPRD.BD_FAT_FATURAMENTO VFA
        ON VFA.IDPNS = PNS.ID
      JOIN SGTPRD.ITENS_ESTOQUE ITE
        ON ITE.CODIGO_REDUZIDO = VFA.CODIGO_REDUZIDO
      JOIN SGTPRD.NATUREZA_OPERACAO NAT
        ON NAT.IDNATUREZAOPERACAO = PNS.IDNATUOPER
      JOIN SGTPRD.PRODUTO_ROMANEIO PRO
        ON PRO.IDPRODUTO_ROMANEIO = VFA.IDPRODUTO_ROMANEIO
      JOIN SGTPRD.ROMANEIO ROM
        ON ROM.NUMERO_ROMANEIO = VFA.NUMERO_ROMANEIO
     WHERE NSA.IDFILIAL = 1
       AND VFA.FILIALNOTA = 1
       AND ITE.TIPO_ITEM = 10
       AND NSA.STNOTAFATURAMENTO = 3
       AND NVL(TRIM(NAT.ENTRADA), '0') <> '1'
       AND TRIM(NAT.DESCOPERACAO) NOT LIKE 'REMESSA%'
       AND NSA.DTEMISSAO >= JAN.DT_CORTE
       AND NSA.DTEMISSAO < JAN.DT_FIM
),
BASE_FATURAMENTO AS (
    SELECT TRUNC(F.DTEMISSAO, 'MM') AS DATA_REFERENCIA,
           TRIM(CST.DS_SUBTIPOPED) AS DESCR_SUB_TIPO_PEDIDO,
           TO_NUMBER(TO_CHAR(F.DTEMISSAO, 'MM')) AS MES,
           TO_NUMBER(TO_CHAR(F.DTEMISSAO, 'RRRR')) AS ANO,
           TRIM(PFJ1.NOMEFANTASIA) AS NOME_FANT_CLIENTE_COMPRADOR,
           TRIM(CTP.DESCRICAO) AS DESCR_TIPOPEDIDO,
           TRIM(F.DESCOPERACAO) AS DESCR_NATUREZA_OPERACAO,
           F.NUMERO_ROMANEIO, F.CODIGO_REDUZIDO_PNS,
           IPC.DATAEXPEDIREM AS DATA_PRAZO_EXPEDICAO,
           TO_DATE(TO_CHAR(F.DATA_EXPEDICAO, 'FM00000000'), 'FXYYYYMMDD') AS DATA_EXPEDICAO_FISICA,
           F.QTD_FATURADA
      FROM FATOS_FILTRADOS F
      LEFT JOIN SGTPRD.PEDIDOCOMERCIAL PCO ON PCO.PEDIDO = F.PEDIDO
      LEFT JOIN SGTPRD.ITENSPEDIDOCOMERCIAL IPC ON IPC.PEDIDO = F.PEDIDO AND IPC.ITEMPEDIDO = F.ITEM_PEDIDO
      LEFT JOIN SGTPRD.COML_SUBTIPOPED CST ON CST.CD_SUBTIPOPED = PCO.CD_SUBTIPOPED
      LEFT JOIN SGTPRD.COML_TIPOSPEDIDOS CTP ON CTP.TIPOPEDIDO = PCO.TIPOPEDIDO
      LEFT JOIN SGTPRD.PESSOASFJ PFJ1 ON PFJ1.IDPESSOAFJ = NVL(PCO.IDFILIALRESPONSAVEL, F.IDPESSOAFJ)
),
BASE_COM_PECAS AS (
    SELECT BF.DATA_REFERENCIA, BF.DESCR_SUB_TIPO_PEDIDO, BF.MES, BF.ANO, BF.NOME_FANT_CLIENTE_COMPRADOR, BF.DESCR_TIPOPEDIDO, BF.DESCR_NATUREZA_OPERACAO, BF.DATA_PRAZO_EXPEDICAO, BF.QTD_FATURADA, BF.DATA_EXPEDICAO_FISICA,
           (SELECT COUNT(GPEC.IDPECASPRODUTO)
              FROM SGTPRD.GERAPECAROMSAIDA GPEC
              JOIN SGTPRD.GERAPECASPRODUTO GPP ON GPP.IDPECASPRODUTO = GPEC.IDPECASPRODUTO
             WHERE GPEC.NUMERO_ROMANEIO_SAID = BF.NUMERO_ROMANEIO
               AND GPP.CODIGO_REDUZIDO_PROD = BF.CODIGO_REDUZIDO_PNS) AS QTD_PECAS
      FROM BASE_FATURAMENTO BF
),
BASE_ANALITICA AS (
    SELECT BP.DATA_REFERENCIA, BP.DESCR_SUB_TIPO_PEDIDO, BP.MES, BP.ANO, BP.NOME_FANT_CLIENTE_COMPRADOR, BP.DESCR_TIPOPEDIDO, BP.DESCR_NATUREZA_OPERACAO, BP.DATA_PRAZO_EXPEDICAO, BP.QTD_FATURADA, BP.DATA_EXPEDICAO_FISICA, BP.QTD_PECAS,
           CASE
               WHEN BP.DATA_PRAZO_EXPEDICAO IS NULL THEN CAST(NULL AS NUMBER)
               ELSE TRUNC(BP.DATA_EXPEDICAO_FISICA) - TRUNC(BP.DATA_PRAZO_EXPEDICAO)
           END AS DIAS_DESVIO_PRAZO,
           CASE
               WHEN BP.DATA_PRAZO_EXPEDICAO IS NULL THEN 'Sem Prazo'
               WHEN BP.DATA_EXPEDICAO_FISICA IS NULL THEN 'Atraso'
               WHEN TRUNC(BP.DATA_EXPEDICAO_FISICA) - TRUNC(BP.DATA_PRAZO_EXPEDICAO) > 0 THEN 'Atraso'
               WHEN TRUNC(BP.DATA_EXPEDICAO_FISICA) - TRUNC(BP.DATA_PRAZO_EXPEDICAO) = 0 THEN 'Na Data'
               ELSE 'Antecipado'
           END AS DESCR_ATENDIMENTO_PRAZO_EXPEDICAO
      FROM BASE_COM_PECAS BP
)
SELECT
    DATA_REFERENCIA,
    DESCR_SUB_TIPO_PEDIDO,
    MES,
    ANO,
    NOME_FANT_CLIENTE_COMPRADOR,
    DESCR_ATENDIMENTO_PRAZO_EXPEDICAO,
    DESCR_TIPOPEDIDO,
    DESCR_NATUREZA_OPERACAO,
    SUM(QTD_PECAS) AS QTD_PECAS,
    SUM(QTD_FATURADA) AS QTD_FATURADA,
    MAX(CASE WHEN NOME_FANT_CLIENTE_COMPRADOR LIKE '%CR-MATR%'
                  AND DESCR_TIPOPEDIDO LIKE '%PRÓPRIO%'
             THEN 1 ELSE 0 END) AS MATRIZ,
    MAX(CASE WHEN NOME_FANT_CLIENTE_COMPRADOR NOT LIKE '%CR-MATR%'
                  AND DESCR_TIPOPEDIDO LIKE '%PRÓPRIO%'
             THEN 1 ELSE 0 END) AS VENDA_DIRETA,
    MAX(CASE WHEN DESCR_TIPOPEDIDO LIKE '%VENDA%'
                  OR DESCR_NATUREZA_OPERACAO LIKE 'VENDA%'
             THEN 1 ELSE 0 END) AS VENDA,
    MAX(CASE WHEN DESCR_TIPOPEDIDO LIKE '%VENDA%'
                  AND DESCR_NATUREZA_OPERACAO LIKE 'VENDA%'
             THEN 1 ELSE 0 END) AS VENDA_INTERNA,
    MAX(CASE WHEN DESCR_TIPOPEDIDO LIKE '%TERCEIRO%'
             THEN 1 ELSE 0 END) AS TERCEIROS,
    COUNT(*) AS QTD_REGISTROS,
    COUNT(CASE WHEN DESCR_ATENDIMENTO_PRAZO_EXPEDICAO = 'Atraso' THEN 1 END) AS QTD_ATRASO,
    COUNT(CASE WHEN DESCR_ATENDIMENTO_PRAZO_EXPEDICAO = 'Na Data' THEN 1 END) AS QTD_NA_DATA,
    COUNT(CASE WHEN DESCR_ATENDIMENTO_PRAZO_EXPEDICAO = 'Antecipado' THEN 1 END) AS QTD_ANTECIPADO,
    COUNT(CASE WHEN DESCR_ATENDIMENTO_PRAZO_EXPEDICAO = 'Sem Prazo' THEN 1 END) AS QTD_SEM_PRAZO,
    COUNT(DATA_PRAZO_EXPEDICAO) AS QTD_COM_PRAZO,
    ROUND(COUNT(DATA_PRAZO_EXPEDICAO) / NULLIF(COUNT(*), 0) * 100, 2) AS PCT_COBERTURA_PRAZO,
    AVG(DIAS_DESVIO_PRAZO) AS DIAS_DESVIO_PRAZO_MEDIO
FROM BASE_ANALITICA
GROUP BY
    DATA_REFERENCIA,
    DESCR_SUB_TIPO_PEDIDO,
    MES,
    ANO,
    NOME_FANT_CLIENTE_COMPRADOR,
    DESCR_ATENDIMENTO_PRAZO_EXPEDICAO,
    DESCR_TIPOPEDIDO,
    DESCR_NATUREZA_OPERACAO
ORDER BY DATA_REFERENCIA DESC
