/* =============================================================================
OBJETIVO: Série Temporal Histórica de Produção por Fase e Indicadores Fabris (Últimos 12 Meses + Mês Aberto)
          Modelo Fato / Série Longa (Ideal para Dashboards FastAPI, Power BI e Análises Históricas).
DOMÍNIO: 09_pcp_kpis_gestao
DESTINO: Ingestão de Dados Analíticos, Dashboards Gerenciais e APIs do Hub de Automações.
TIPO: SELECT (Painel Analítico / Histórico Contínuo)
PARÂMETROS / BINDS:
  - Janela temporal automática: Últimos 12 meses fechados + Mês corrente em aberto (TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM') até SYSDATE).
CUIDADOS OPERACIONAIS & DIRETRIZES DE ENGENHARIA ORACLE:
  - Zero Views: Junção direta pelas tabelas físicas com índices operacionais (sem views legadas).
  - Pré-agregação por dimensões operacionais; ganhos de buffer gets/tempo ainda dependem de medição Oracle.
  - Produção de Acabado Oficial por Peça: Dados de produto acabado extraídos da movimentação oficial por peça
    (SGTPRD.BD_PRD_MOVPROD com NUM_TIPO_MOVIMENTO = 37 e CODIGO IN (1, 8)), trazendo volume em kg, quantidade de peças/rolos
    e peso médio por peça, conforme padrão canônico do PCP.
  - Reprocesso total: volume identificado pelo cadastro oficial DESTINO → GRUPO_DESTINO.TIPO_DESTINO = 1.
    Subdivisões por origem permanecem pendentes de regra oficial do PCP.
  - QT_KG é um campo legado de valor da métrica; interprete a unidade efetiva por UNIDADE_METRICA.
  - Dias Produtivos Segmentados: Dias produtivos de Tinturaria (DIAS_TING) e de Acabamento (DIAS_ACABADO) segregados por processo.
  - Métricas Avançadas de Série Temporal: Variação Mês a Mês (MoM % para volumes e MoM p.p. para taxas), Média Móvel 3M
    e balanço mensal dos fluxos tingido e acabado (sem comprovação de estoque WIP).
  - TEMPO_PREV_HORAS, desvio e eficiência permanecem nulos até o PCP confirmar unidade/ponderação de TEMPO_RECEITA.
============================================================================= */

WITH JANELA AS (
    SELECT ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AS DT_INICIO,
           TRUNC(SYSDATE) + 1                    AS DT_FIM,
           TRUNC(SYSDATE, 'MM')                  AS DT_MES_ABERTO
      FROM DUAL
),
MESES AS (
    SELECT ADD_MONTHS(JAN.DT_MES_ABERTO, LEVEL - 13) AS DT_MES,
           CASE WHEN LEVEL = 13 THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES
      FROM JANELA JAN
    CONNECT BY LEVEL <= 13
),
FASES_RAW AS (
    -- Junção UPR -> UOM -> OB_FASES feita uma vez só (13 meses, fases do painel);
    -- FASES_DIA_AGR e PARTIDAS_TING_MENSAL leem daqui.
    SELECT /*+ MATERIALIZE */
           UPR.DTPRODFIM,
           UPR.NUMERO_MAQUINA,
           UPR.NRTURNOFIM,
           UPR.DTTEMPOINICONFIRMADO,
           UPR.DTTEMPOFINALCONFIRMA,
           OBF.CODIGO_FASE,
           OBF.DESTINO_RECEITA,
           OBF.GRUPO_DEFEITO,
           OBF.KILOS_PRODUZIDOS,
           OBF.ID_LIGA_CADREC_ITEMR,
           OBF.NUMEROORDEMMOVIMENTO,
           OBF.SEQUENCIAORDEMMOVIME
      FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
      JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL
                              AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
     CROSS JOIN JANELA JAN
     WHERE UPR.SETOR = 5 AND UPR.EXCLUIDA = 0 AND UPR.TIPOUP = 0 AND UPR.STATUS = 0
       AND UPR.DTPRODFIM >= JAN.DT_INICIO AND UPR.DTPRODFIM < JAN.DT_FIM
       AND OBF.CODIGO_FASE IN (10, 20, 26, 40, 50, 55, 60, 65, 70, 80, 90, 100, 110)
),
FASES_DIA_AGR AS (
    -- Base única no grão diário (07/10/2026). Antes BASE_FASES_AGR, FASES_DIA_BASE
    -- e DIAS_TING_MENSAL refaziam a mesma junção de 13 meses três vezes e a
    -- consulta passava da janela de rede (~4-6 s). As três derivam desta: somas e
    -- o tempo ponderado (numerador/denominador) agregam do dia para o mês sem perda.
    SELECT /*+ MATERIALIZE */
           TRUNC(R.DTPRODFIM, 'MM') AS DT_MES,
           CASE WHEN R.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           TRUNC(R.DTPRODFIM) AS DIA,
           R.CODIGO_FASE,
           R.DESTINO_RECEITA AS DESTINO_RECEITA,
           GD.TIPO_DESTINO,
           TRIM(R.GRUPO_DEFEITO) AS GRUPO_DEFEITO,
           MAQ.GRUPO AS GRUPO_MAQUINA,
           R.NUMERO_MAQUINA,
           R.NRTURNOFIM AS TURNO,
           CL.CODIGO_CLASSIFICACAO,
           SUM(R.KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
           SUM(CASE WHEN R.DTTEMPOFINALCONFIRMA > R.DTTEMPOINICONFIRMADO
                    THEN R.KILOS_PRODUZIDOS * (R.DTTEMPOFINALCONFIRMA - R.DTTEMPOINICONFIRMADO) * 24 END) AS TEMPO_NUM,
           SUM(CASE WHEN R.DTTEMPOFINALCONFIRMA > R.DTTEMPOINICONFIRMADO THEN R.KILOS_PRODUZIDOS END) AS TEMPO_DEN
      FROM FASES_RAW R
      LEFT JOIN SGTPRD.MAQUINA           MAQ ON MAQ.NUMERO_MAQUINA = R.NUMERO_MAQUINA AND MAQ.SETOR = 5
      LEFT JOIN SGTPRD.DESTINO           DST ON DST.DESTINO = R.DESTINO_RECEITA
      LEFT JOIN SGTPRD.GRUPO_DESTINO     GD ON GD.CODIGO_GRUPO = DST.CODIGO_GRUPO
      LEFT JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR ON LCR.ID_LIGA_CADREC_ITEMR = R.ID_LIGA_CADREC_ITEMR AND R.CODIGO_FASE = 40
      LEFT JOIN SGTPRD.CADASTRO_RECEITAS CR  ON CR.CODIGO_REDUZIDO_RECE = LCR.CODIGO_REDUZIDO_RECE
      LEFT JOIN SGTPRD.CLASSIFICACAO_COR CL  ON CL.CODIGO_CLASSIFICACAO = CR.CODIGO_CLASSIFICACAO
     CROSS JOIN JANELA                   JAN
     GROUP BY TRUNC(R.DTPRODFIM, 'MM'),
              CASE WHEN R.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END,
              TRUNC(R.DTPRODFIM),
              R.CODIGO_FASE,
              R.DESTINO_RECEITA,
              GD.TIPO_DESTINO,
              TRIM(R.GRUPO_DEFEITO),
              MAQ.GRUPO,
              R.NUMERO_MAQUINA,
              R.NRTURNOFIM,
              CL.CODIGO_CLASSIFICACAO
),
BASE_FASES_AGR AS (
    SELECT /*+ MATERIALIZE */ DT_MES,
           STATUS_MES,
           CODIGO_FASE,
           DESTINO_RECEITA,
           TIPO_DESTINO,
           GRUPO_DEFEITO,
           GRUPO_MAQUINA,
           NUMERO_MAQUINA,
           TURNO,
           CODIGO_CLASSIFICACAO,
           SUM(KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
           TO_NUMBER(NULL) AS QT_PARTIDAS,
           TO_NUMBER(NULL) AS DIAS_PRODUTIVOS,
           TO_NUMBER(NULL) AS TEMPO_PREV_HORAS,
           ROUND(SUM(TEMPO_NUM) / NULLIF(SUM(TEMPO_DEN), 0), 2) AS TEMPO_REAL_HORAS
      FROM FASES_DIA_AGR
     GROUP BY DT_MES, STATUS_MES, CODIGO_FASE, DESTINO_RECEITA, TIPO_DESTINO,
              GRUPO_DEFEITO, GRUPO_MAQUINA, NUMERO_MAQUINA, TURNO, CODIGO_CLASSIFICACAO
),
FASES_DIA_BASE AS (
    SELECT /*+ MATERIALIZE */ DISTINCT DT_MES, STATUS_MES, DIA, CODIGO_FASE, DESTINO_RECEITA, TIPO_DESTINO,
           GRUPO_DEFEITO, GRUPO_MAQUINA, NUMERO_MAQUINA, TURNO, CODIGO_CLASSIFICACAO
      FROM FASES_DIA_AGR
),
DIAS_FASE_LINHA AS (
    SELECT DT_MES, STATUS_MES, ORDEM, COUNT(DISTINCT DIA) AS DIAS_PRODUTIVOS
      FROM (
            SELECT DT_MES, STATUS_MES, DIA, '01' AS ORDEM FROM FASES_DIA_BASE WHERE CODIGO_FASE = 10
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '02' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 20
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '03' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 26
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04A' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG001'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04B' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG002'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04C' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG003'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04D' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04E' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND TIPO_DESTINO = 1
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04G' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04H' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (1, 6, 7, 10, 18)
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04I' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO = 2
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04J' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (5, 14)
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04K' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (3, 8, 9, 11, 12, 15)
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04L' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 1
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04M' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 2
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '04N' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 3
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '05A' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD01'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '05B' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD02'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '05C' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD03'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '05D' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (50, 55)
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '06A' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC01'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '06B' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC02'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '06C' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 60
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '07' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 65
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '08' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 70
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '09' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 80
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '10' FROM FASES_DIA_BASE WHERE CODIGO_FASE = 90
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '11A' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM01'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '11B' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM02'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '11C' FROM FASES_DIA_BASE WHERE CODIGO_FASE IN (100, 110)
      ) LINHAS
     GROUP BY DT_MES, STATUS_MES, ORDEM
),
DIAS_TING_MENSAL AS (
    SELECT DT_MES,
           STATUS_MES,
           COUNT(DISTINCT DIA) AS DIAS_TING
      FROM FASES_DIA_AGR
     WHERE CODIGO_FASE = 40
     GROUP BY DT_MES, STATUS_MES
),
PARTIDAS_TING_MENSAL AS (
    SELECT TRUNC(R.DTPRODFIM, 'MM') AS DT_MES,
           CASE WHEN R.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           COUNT(DISTINCT R.NUMEROORDEMMOVIMENTO || '~' || R.SEQUENCIAORDEMMOVIME) AS PART_TING_TOT,
           COUNT(DISTINCT CASE WHEN R.DESTINO_RECEITA = 1 THEN R.NUMEROORDEMMOVIMENTO || '~' || R.SEQUENCIAORDEMMOVIME END) AS PART_TING_NORMAL,
           COUNT(DISTINCT CASE WHEN R.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG001' THEN R.NUMEROORDEMMOVIMENTO || '~' || R.SEQUENCIAORDEMMOVIME END) AS PART_B1000,
           COUNT(DISTINCT CASE WHEN R.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG002' THEN R.NUMEROORDEMMOVIMENTO || '~' || R.SEQUENCIAORDEMMOVIME END) AS PART_B600,
           COUNT(DISTINCT CASE WHEN R.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG003' THEN R.NUMEROORDEMMOVIMENTO || '~' || R.SEQUENCIAORDEMMOVIME END) AS PART_B2000
      FROM FASES_RAW R
      LEFT JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = R.NUMERO_MAQUINA AND MAQ.SETOR = 5
      CROSS JOIN JANELA JAN
     WHERE R.CODIGO_FASE = 40
       AND R.NUMEROORDEMMOVIMENTO IS NOT NULL AND R.SEQUENCIAORDEMMOVIME IS NOT NULL
     GROUP BY TRUNC(R.DTPRODFIM, 'MM'),
              CASE WHEN R.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END
),
ACABADO_MOV_DIA AS (
    -- Agrega os movimentos antes das junções de cadastro (fluxo e estampado só
    -- dependem do reduzido): a junção com ITENS_ESTOQUE/LIKE roda sobre milhares
    -- de linhas agregadas em vez de cada peça de 12 meses.
    SELECT /*+ MATERIALIZE */
           TRUNC(MVP.PRODUCAO_DATA) AS DIA,
           MVP.PRODUCAO_TURNO AS TURNO,
           MVP.REDUZIDO_ITEM,
           CASE WHEN MVP.ESTAMPADO = 1 THEN 1 ELSE 0 END AS FLAG_ESTAMPADO,
           SUM(MVP.QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           COUNT(MVP.IDPECASPRODUTO) AS QT_PECAS
      FROM SGTPRD.BD_PRD_MOVPROD MVP
     WHERE MVP.NUM_TIPO_MOVIMENTO = 37
       AND MVP.CODIGO IN (1, 8)
       AND MVP.PRODUCAO_DATA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
       AND MVP.PRODUCAO_DATA <  TRUNC(SYSDATE) + 1
     GROUP BY TRUNC(MVP.PRODUCAO_DATA),
              MVP.PRODUCAO_TURNO,
              MVP.REDUZIDO_ITEM,
              CASE WHEN MVP.ESTAMPADO = 1 THEN 1 ELSE 0 END
),
ACABADO_DIA_AGR AS (
    SELECT /*+ MATERIALIZE */
           TRUNC(M.DIA, 'MM') AS DT_MES,
           CASE WHEN M.DIA >= TRUNC(SYSDATE, 'MM') THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           M.DIA,
           M.TURNO,
           TRIM(E9.CDNIVELGENERICO) AS FLUXO,
           CASE WHEN M.FLAG_ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END AS IS_ESTAMPADO,
           SUM(M.QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           SUM(M.QT_PECAS) AS QT_PECAS
      FROM ACABADO_MOV_DIA M
      LEFT JOIN SGTPRD.ENGEITEMESTONIVELGE9 E9 ON E9.CDREDUZIDO = M.REDUZIDO_ITEM
      LEFT JOIN SGTPRD.ITENS_ESTOQUE        ITE ON ITE.CODIGO_REDUZIDO = M.REDUZIDO_ITEM
     GROUP BY TRUNC(M.DIA, 'MM'),
              CASE WHEN M.DIA >= TRUNC(SYSDATE, 'MM') THEN 'EM ABERTO' ELSE 'FECHADO' END,
              M.DIA,
              M.TURNO,
              TRIM(E9.CDNIVELGENERICO),
              CASE WHEN M.FLAG_ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END
),
BASE_ACABADO_AGR AS (
    SELECT DT_MES,
           STATUS_MES,
           TURNO,
           FLUXO,
           IS_ESTAMPADO,
           SUM(QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           SUM(QT_PECAS) AS QT_PECAS,
           TO_NUMBER(NULL) AS DIAS_PRODUTIVOS
      FROM ACABADO_DIA_AGR
     GROUP BY DT_MES, STATUS_MES, TURNO, FLUXO, IS_ESTAMPADO
),
DIAS_ACABADO_MENSAL AS (
    SELECT DT_MES,
           COUNT(DISTINCT DIA) AS DIAS_ACABADO
      FROM ACABADO_DIA_AGR
     GROUP BY DT_MES
),
DIAS_ACABADO_BASE AS (
    SELECT DT_MES, STATUS_MES, DIA, TURNO, FLUXO, IS_ESTAMPADO
      FROM ACABADO_DIA_AGR
),
DIAS_ACABADO_LINHA AS (
    SELECT DT_MES, STATUS_MES, ORDEM, COUNT(DISTINCT DIA) AS DIAS_PRODUTIVOS
      FROM (
            SELECT DT_MES, STATUS_MES, DIA, '12A' AS ORDEM FROM DIAS_ACABADO_BASE
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '12D' FROM DIAS_ACABADO_BASE WHERE TURNO = 1
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '12E' FROM DIAS_ACABADO_BASE WHERE TURNO = 2
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '12F' FROM DIAS_ACABADO_BASE WHERE TURNO = 3
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '90' FROM DIAS_ACABADO_BASE WHERE FLUXO = 'T'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '91' FROM DIAS_ACABADO_BASE WHERE FLUXO = 'R'
            UNION ALL SELECT DT_MES, STATUS_MES, DIA, '92' FROM DIAS_ACABADO_BASE WHERE IS_ESTAMPADO = 1
      ) LINHAS
     GROUP BY DT_MES, STATUS_MES, ORDEM
),
FASES_MENSAIS AS (
    SELECT F.DT_MES,
           F.STATUS_MES,
           SUM(CASE WHEN F.CODIGO_FASE = 10 THEN F.KILOS_PRODUZIDOS END) AS KG_MONT,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_NORM,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TIPO_DESTINO = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_TOTAL,
           SUM(CASE WHEN F.CODIGO_FASE = 40 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_TOT,
           SUM(CASE WHEN F.CODIGO_FASE = 60 THEN F.KILOS_PRODUZIDOS END) AS KG_SECADOR_TOT,
           SUM(CASE WHEN F.CODIGO_FASE IN (100, 110) THEN F.KILOS_PRODUZIDOS END) AS KG_RAMA_TOT
      FROM BASE_FASES_AGR F
     GROUP BY F.DT_MES, F.STATUS_MES
),
ACABADO_MENSAL AS (
    SELECT B.DT_MES,
           B.ACAB_KG_TOT,
           B.ACAB_PECAS_TOT,
           D.DIAS_ACABADO,
           B.ACAB_KG_TUBULAR,
           B.ACAB_KG_RAMADO
      FROM (
            SELECT DT_MES,
                   SUM(QUANTIDADE_REAL) AS ACAB_KG_TOT,
                   SUM(QT_PECAS) AS ACAB_PECAS_TOT,
                   SUM(CASE WHEN FLUXO = 'T' THEN QUANTIDADE_REAL END) AS ACAB_KG_TUBULAR,
                   SUM(CASE WHEN FLUXO = 'R' THEN QUANTIDADE_REAL END) AS ACAB_KG_RAMADO
              FROM BASE_ACABADO_AGR
             GROUP BY DT_MES
      ) B
      LEFT JOIN DIAS_ACABADO_MENSAL D ON D.DT_MES = B.DT_MES
),
REFS_MENSAIS AS (
    SELECT M.DT_MES,
           M.STATUS_MES,
           F.KG_MONT,
           F.KG_TING_NORM,
           F.KG_TING_REP_TOTAL,
           F.KG_TING_TOT,
           PM.PART_TING_TOT,
           PM.PART_TING_NORMAL,
           PM.PART_B1000,
           PM.PART_B600,
           PM.PART_B2000,
           DT.DIAS_TING,
           F.KG_SECADOR_TOT,
           F.KG_RAMA_TOT,
           A.ACAB_KG_TOT,
           A.ACAB_PECAS_TOT,
           A.DIAS_ACABADO,
           A.ACAB_KG_TUBULAR,
           A.ACAB_KG_RAMADO
      FROM MESES M
      LEFT JOIN FASES_MENSAIS F ON F.DT_MES = M.DT_MES AND F.STATUS_MES = M.STATUS_MES
      LEFT JOIN ACABADO_MENSAL A ON A.DT_MES = M.DT_MES
      LEFT JOIN DIAS_TING_MENSAL DT ON DT.DT_MES = M.DT_MES AND DT.STATUS_MES = M.STATUS_MES
      LEFT JOIN PARTIDAS_TING_MENSAL PM ON PM.DT_MES = M.DT_MES AND PM.STATUS_MES = M.STATUS_MES
),
EXPANDIDO AS (
    SELECT DT_MES, STATUS_MES, '01'  AS ORDEM, 'FASE PRODUTIVA' AS CATEGORIA, '01 - MONTAGEM DE LOTE (CRU)' AS LINHA, DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TO_NUMBER(NULL) AS TEMPO_RECEITA, TO_NUMBER(NULL) AS TEMPO_REAL_HORAS, TO_NUMBER(NULL) AS CAPACIDADE_NOMINAL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 10
    UNION ALL
    SELECT DT_MES, STATUS_MES, '02' , 'FASE PRODUTIVA', '02 - REVISÃO MALHA CRUA', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 20
    UNION ALL
    SELECT DT_MES, STATUS_MES, '03' , 'FASE PRODUTIVA', '03 - VIRAR MOLETOM (FELPA)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 26
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04A', 'TINTURARIA - BARCAS', '04A - TINTURARIA: BARCA 1000 KG (TG001)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, 1000 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG001'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04B', 'TINTURARIA - BARCAS', '04B - TINTURARIA: BARCA 600 KG (TG002)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, 600 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG002'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04C', 'TINTURARIA - BARCAS', '04C - TINTURARIA: BARCA 2000 KG (TG003)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, 2000 FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG003'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04D', 'TINTURARIA - RESUMO', '04 - TINTURARIA: PRODUÇÃO NORMAL', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04E', 'TINTURARIA - REPROCESSO', '04 - TINTURARIA: REPROCESSO TOTAL (DESTINO OFICIAL)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND TIPO_DESTINO = 1
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04F', 'TINTURARIA - REPROCESSO', '04 - TINTURARIA: SUBCLASSIFICAÇÃO PENDENTE DO PCP', DIAS_PRODUTIVOS, QT_PARTIDAS, TO_NUMBER(NULL), TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA IN (2, 4)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04G', 'TINTURARIA - RESUMO', '04 - TINTURARIA: TOTAL GERAL TINTURARIA', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04H', 'TINTURARIA - MIX CORES', '[MIX CORES] 1. CLARAS / BRANCO / MARFIM', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (1, 6, 7, 10, 18)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04I', 'TINTURARIA - MIX CORES', '[MIX CORES] 2. CORES MÉDIAS', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (2)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04J', 'TINTURARIA - MIX CORES', '[MIX CORES] 3. CORES ESCURAS E PRETO', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (5, 14)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04K', 'TINTURARIA - MIX CORES', '[MIX CORES] 4. ESPECIAIS E 2 FIBRAS', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (3, 8, 9, 11, 12, 15)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04L', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 1º TURNO', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 1
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04M', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 2º TURNO', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 2
    UNION ALL
    SELECT DT_MES, STATUS_MES, '04N', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 3º TURNO', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 3
    UNION ALL
    SELECT DT_MES, STATUS_MES, '05A', 'HIDROS EXTRATORES', '05A - HIDROEXTRATORA 01', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD01'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '05B', 'HIDROS EXTRATORES', '05B - HIDROEXTRATORA 02', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD02'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '05C', 'HIDROS EXTRATORES', '05C - HIDROEXTRATORA 03', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD03'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '05D', 'HIDROS EXTRATORES', '05 - TOTAL HIDROS EXTRATORES', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55)
    UNION ALL
    SELECT DT_MES, STATUS_MES, '06A', 'SECADORES', '06A - SECADOR 01 (ÓLEO TÉRMICO)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC01'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '06B', 'SECADORES', '06B - SECADOR 02 (VAPOR)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC02'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '06C', 'SECADORES', '06 - TOTAL SECADORES', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60
    UNION ALL
    SELECT DT_MES, STATUS_MES, '07' , 'ACABAMENTO INTERMEDIÁRIO', '07 - FELPADEIRA', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 65
    UNION ALL
    SELECT DT_MES, STATUS_MES, '08' , 'ACABAMENTO INTERMEDIÁRIO', '08 - CALANDRA DE BRILHO (CL 01)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 70
    UNION ALL
    SELECT DT_MES, STATUS_MES, '09' , 'ACABAMENTO INTERMEDIÁRIO', '09 - CALANDRA COMPACTA (CL 02)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 80
    UNION ALL
    SELECT DT_MES, STATUS_MES, '10' , 'ACABAMENTO INTERMEDIÁRIO', '10 - ABRIDOR DE MALHA (AB 01)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE = 90
    UNION ALL
    SELECT DT_MES, STATUS_MES, '11A', 'RAMAS', '11A - RAMA 01 (RM 01)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM01'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '11B', 'RAMAS', '11B - RAMA 02 (RM 02)', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM02'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '11C', 'RAMAS', '11 - TOTAL RAMAS', DIAS_PRODUTIVOS, QT_PARTIDAS, KILOS_PRODUZIDOS, NULL, NULL, NULL FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110)
    UNION ALL
    -- Produção Oficial por Peça (BD_PRD_MOVPROD)
    SELECT DT_MES, STATUS_MES, '12A', 'PRODUTO ACABADO', '12 - TOTAL PRODUTO ACABADO (KG)', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR
    UNION ALL
    SELECT DT_MES, STATUS_MES, '12D', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 1º TURNO', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 1
    UNION ALL
    SELECT DT_MES, STATUS_MES, '12E', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 2º TURNO', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 2
    UNION ALL
    SELECT DT_MES, STATUS_MES, '12F', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 3º TURNO', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE TURNO = 3
    UNION ALL
    SELECT DT_MES, STATUS_MES, '90' , 'FLUXO DE MALHA', '[FLUXO MALHA] TOTAL TUBULAR', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE FLUXO = 'T'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '91' , 'FLUXO DE MALHA', '[FLUXO MALHA] TOTAL RAMADO (ABERTO)', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE FLUXO = 'R'
    UNION ALL
    SELECT DT_MES, STATUS_MES, '92' , 'FLUXO DE MALHA', '[FLUXO MALHA] ESTAMPADO ACABADO', DIAS_PRODUTIVOS, QT_PECAS, QUANTIDADE_REAL, NULL, NULL, NULL FROM BASE_ACABADO_AGR WHERE IS_ESTAMPADO = 1
),
AGREGADO AS (
    SELECT DT_MES,
           STATUS_MES,
           ORDEM,
           CATEGORIA,
           LINHA,
           SUM(KILOS_PRODUZIDOS) AS QT_KG,
           TO_NUMBER(NULL) AS DIAS_PRODUTIVOS,
           TO_NUMBER(NULL) AS QT_PARTIDAS,
           MAX(CAPACIDADE_NOMINAL) AS CAPACIDADE_NOMINAL,
           ROUND(SUM(CASE WHEN TEMPO_RECEITA > 0 THEN KILOS_PRODUZIDOS * TEMPO_RECEITA END)
                 / NULLIF(SUM(CASE WHEN TEMPO_RECEITA > 0 THEN KILOS_PRODUZIDOS END), 0), 2) AS TEMPO_PREV_HORAS,
           ROUND(SUM(CASE WHEN TEMPO_REAL_HORAS > 0 THEN KILOS_PRODUZIDOS * TEMPO_REAL_HORAS END)
                 / NULLIF(SUM(CASE WHEN TEMPO_REAL_HORAS > 0 THEN KILOS_PRODUZIDOS END), 0), 2) AS TEMPO_REAL_HORAS
      FROM EXPANDIDO
     GROUP BY DT_MES, STATUS_MES, ORDEM, CATEGORIA, LINHA
),
KPIS_EXECUTIVOS AS (
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00A' AS ORDEM,
           'INDICADOR DE GESTÃO' AS CATEGORIA,
           '[INDICADOR GESTÃO] PRODUÇÃO NORMAL / PRODUÇÃO TINGIDA (%)' AS LINHA,
           ROUND(REF.KG_TING_NORM / NULLIF(REF.KG_TING_TOT, 0) * 100, 2) AS QT_KG,
           REF.DIAS_TING AS DIAS_PRODUTIVOS,
           REF.PART_TING_TOT AS QT_PARTIDAS,
           TO_NUMBER(NULL) AS CAPACIDADE_NOMINAL,
           TO_NUMBER(NULL) AS TEMPO_PREV_HORAS,
           TO_NUMBER(NULL) AS TEMPO_REAL_HORAS
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00B',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] REPROCESSO TOTAL / NORMAL (%)',
           ROUND(REF.KG_TING_REP_TOTAL / NULLIF(REF.KG_TING_NORM, 0) * 100, 2),
           REF.DIAS_TING,
           NULL,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00C',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] SUBCLASSIFICAÇÃO DO REPROCESSO PENDENTE PCP',
           TO_NUMBER(NULL),
           REF.DIAS_TING,
           NULL,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00D',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] ACABADO MENSAL / TINGIDO MENSAL (%)',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.KG_TING_TOT, 0) * 100, 2),
           REF.DIAS_ACABADO,
           NULL,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00E',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] ACABADO MENSAL / MONTADO MENSAL (%)',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.KG_MONT, 0) * 100, 2),
           REF.DIAS_ACABADO,
           NULL,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '00F',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] PESO MÉDIO POR PARTIDA (KG)',
           ROUND(REF.KG_TING_TOT / NULLIF(REF.PART_TING_TOT, 0), 0),
           REF.DIAS_TING,
           REF.PART_TING_TOT,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '12B',
           'PRODUTO ACABADO',
           '12 - TOTAL PRODUTO ACABADO (PEÇAS / ROLOS)',
           REF.ACAB_PECAS_TOT,
           REF.DIAS_ACABADO,
           REF.ACAB_PECAS_TOT,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '12C',
           'PRODUTO ACABADO',
           '12 - PESO MÉDIO POR PEÇA ACABADA (KG/PEÇA)',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.ACAB_PECAS_TOT, 0), 2),
           REF.DIAS_ACABADO,
           REF.ACAB_PECAS_TOT,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           REF.STATUS_MES,
           '93',
           'FLUXO DE MALHA',
           '[FLUXO MALHA] PROPORÇÃO TUBULAR / RAMADO (%)',
           ROUND(REF.ACAB_KG_TUBULAR / NULLIF(REF.ACAB_KG_RAMADO, 0) * 100, 2),
           REF.DIAS_ACABADO,
           NULL,
           NULL, NULL, NULL
      FROM REFS_MENSAIS REF
),
UNIFICADO AS (
    SELECT DT_MES, STATUS_MES, ORDEM, CATEGORIA, LINHA, QT_KG, DIAS_PRODUTIVOS, QT_PARTIDAS, CAPACIDADE_NOMINAL, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS FROM KPIS_EXECUTIVOS
    UNION ALL
    SELECT DT_MES, STATUS_MES, ORDEM, CATEGORIA, LINHA, QT_KG, DIAS_PRODUTIVOS, QT_PARTIDAS, CAPACIDADE_NOMINAL, TEMPO_PREV_HORAS, TEMPO_REAL_HORAS FROM AGREGADO
),
UNIFICADO_COM_UNIDADE AS (
    SELECT UNI.*,
           CASE
               WHEN UNI.ORDEM IN ('00A', '00B', '00C', '00D', '00E', '93') THEN '%'
               WHEN UNI.ORDEM = '00F' THEN 'kg/partida'
               WHEN UNI.ORDEM = '12B' THEN 'peças'
               WHEN UNI.ORDEM = '12C' THEN 'kg/peça'
               ELSE 'kg'
           END AS UNIDADE_METRICA
      FROM UNIFICADO UNI
),
ORDENS_SERIE AS (
    SELECT ORDEM,
           MAX(CATEGORIA) AS CATEGORIA,
           MAX(LINHA) AS LINHA,
           MAX(UNIDADE_METRICA) AS UNIDADE_METRICA
      FROM UNIFICADO_COM_UNIDADE
     GROUP BY ORDEM
),
UNIFICADO_COMPLETO AS (
    SELECT M.DT_MES,
           M.STATUS_MES,
           O.ORDEM,
           O.CATEGORIA,
           O.LINHA,
           U.QT_KG,
           U.DIAS_PRODUTIVOS,
           U.QT_PARTIDAS,
           U.CAPACIDADE_NOMINAL,
           U.TEMPO_PREV_HORAS,
           U.TEMPO_REAL_HORAS,
           O.UNIDADE_METRICA,
           CASE WHEN U.ORDEM IS NULL THEN 0 ELSE 1 END AS TEM_FATO
      FROM MESES M
     CROSS JOIN ORDENS_SERIE O
      LEFT JOIN UNIFICADO_COM_UNIDADE U
        ON U.ORDEM = O.ORDEM
       AND U.DT_MES = M.DT_MES
),
CALCULADO AS (
    SELECT TO_CHAR(UNI.DT_MES, 'YYYY-MM')     AS COMPETENCIA,
           UNI.DT_MES,
           UNI.STATUS_MES,
           UNI.ORDEM,
           UNI.CATEGORIA,
           UNI.LINHA                           AS INDICADOR_FABRIL,
           CASE WHEN UNI.TEM_FATO = 0 OR UNI.ORDEM IN ('00C', '04F') THEN NULL
                ELSE ROUND(NVL(UNI.QT_KG, 0), 2)
           END AS QT_KG,
           CASE WHEN UNI.TEM_FATO = 0 THEN NULL
                ELSE COALESCE(UNI.DIAS_PRODUTIVOS, DLF.DIAS_PRODUTIVOS, DLA.DIAS_PRODUTIVOS)
           END AS DIAS_PRODUTIVOS,
            CASE WHEN UNI.TEM_FATO = 1 AND UNI.UNIDADE_METRICA = 'kg' THEN
                 ROUND(NVL(UNI.QT_KG, 0) / NULLIF(COALESCE(UNI.DIAS_PRODUTIVOS, DLF.DIAS_PRODUTIVOS, DLA.DIAS_PRODUTIVOS), 0), 2)
            END AS MEDIA_KG_DIA,
           CASE WHEN UNI.TEM_FATO = 0 THEN NULL
                WHEN UNI.ORDEM IN ('00A', '00F', '04G') THEN REF.PART_TING_TOT
                WHEN UNI.ORDEM = '04A' THEN REF.PART_B1000
                WHEN UNI.ORDEM = '04B' THEN REF.PART_B600
                WHEN UNI.ORDEM = '04C' THEN REF.PART_B2000
                WHEN UNI.ORDEM = '04D' THEN REF.PART_TING_NORMAL
                ELSE TO_NUMBER(NULL)
           END AS QT_PARTIDAS,
           CASE WHEN UNI.TEM_FATO = 0 THEN NULL
                WHEN UNI.ORDEM = '00F' THEN
                     UNI.QT_KG
                WHEN UNI.ORDEM = '04A' THEN ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B1000, 0), 0)
                WHEN UNI.ORDEM = '04B' THEN ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B600, 0), 0)
                WHEN UNI.ORDEM = '04C' THEN ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B2000, 0), 0)
                WHEN UNI.ORDEM = '04D' AND REF.PART_TING_NORMAL > 0 THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_TING_NORMAL, 0), 0)
                WHEN UNI.ORDEM = '04G' AND REF.PART_TING_TOT > 0 THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_TING_TOT, 0), 0)
           END AS CARGA_MEDIA_KG,
           CASE WHEN UNI.TEM_FATO = 0 THEN NULL
                WHEN UNI.ORDEM IN ('00A', '00B', '00C', '00D', '00E', '93') THEN
                     UNI.QT_KG
                 WHEN UNI.ORDEM = '04A' AND UNI.CAPACIDADE_NOMINAL > 0 THEN
                      ROUND((NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B1000, 0)) / UNI.CAPACIDADE_NOMINAL * 100, 1)
                 WHEN UNI.ORDEM = '04B' AND UNI.CAPACIDADE_NOMINAL > 0 THEN
                      ROUND((NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B600, 0)) / UNI.CAPACIDADE_NOMINAL * 100, 1)
                 WHEN UNI.ORDEM = '04C' AND UNI.CAPACIDADE_NOMINAL > 0 THEN
                      ROUND((NVL(UNI.QT_KG, 0) / NULLIF(REF.PART_B2000, 0)) / UNI.CAPACIDADE_NOMINAL * 100, 1)
                WHEN UNI.ORDEM = '04F' THEN TO_NUMBER(NULL)
                WHEN UNI.ORDEM IN ('04E', '04H', '04I', '04J', '04K', '04L', '04M', '04N') THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_TING_NORM, 0) * 100, 2)
                WHEN UNI.ORDEM IN ('06A', '06B') THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_SECADOR_TOT, 0) * 100, 2)
                WHEN UNI.ORDEM IN ('11A', '11B') THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.KG_RAMA_TOT, 0) * 100, 2)
                WHEN UNI.ORDEM IN ('12D', '12E', '12F', '90', '91', '92') THEN
                     ROUND(NVL(UNI.QT_KG, 0) / NULLIF(REF.ACAB_KG_TOT, 0) * 100, 2)
           END AS PERC_ESPECIFICO,
           CASE WHEN UNI.ORDEM LIKE '00%' THEN
                     CASE UNI.ORDEM
                          WHEN '00A' THEN '% PROPORÇÃO NORMAL NA PRODUÇÃO DE TINTURARIA'
                          WHEN '00B' THEN '% REPROCESSO TOTAL / PRODUÇÃO NORMAL'
                          WHEN '00C' THEN 'SUBCLASSIFICAÇÃO DO REPROCESSO PENDENTE PCP'
                          WHEN '00D' THEN '% ACABADO MENSAL / TINGIDO MENSAL'
                          WHEN '00E' THEN '% ACABADO MENSAL / MONTADO MENSAL'
                          WHEN '00F' THEN 'KG / PARTIDA (TINTURARIA)'
                     END
                WHEN UNI.ORDEM IN ('04A', '04B', '04C') THEN '% CARGA NOMINAL BARCA'
                WHEN UNI.ORDEM = '04E' THEN '% REPROCESSO TOTAL S/ PRODUÇÃO NORMAL'
                WHEN UNI.ORDEM = '04F' THEN 'SUBCLASSIFICAÇÃO DO REPROCESSO PENDENTE PCP'
                WHEN UNI.ORDEM IN ('04H', '04I', '04J', '04K') THEN '% MIX DE CORES'
                WHEN UNI.ORDEM IN ('04L', '04M', '04N') THEN '% PARTICIPAÇÃO TURNO TINTURARIA'
                WHEN UNI.ORDEM IN ('06A', '06B') THEN '% CARGA SECADOR (ÓLEO / VAPOR)'
                WHEN UNI.ORDEM IN ('11A', '11B') THEN '% CARGA RAMA (RM 01 / RM 02)'
                WHEN UNI.ORDEM IN ('12D', '12E', '12F') THEN '% PARTICIPAÇÃO TURNO ACABAMENTO'
                WHEN UNI.ORDEM IN ('90', '91', '92') THEN '% S/ TOTAL PRODUTO ACABADO'
                WHEN UNI.ORDEM = '93' THEN '% PROPORÇÃO TUBULAR / RAMADO'
                WHEN UNI.ORDEM = '12B' THEN 'QUANTIDADE DE PEÇAS / ROLOS'
                WHEN UNI.ORDEM = '12C' THEN 'KG MÉDIO POR PEÇA ACABADA'
           END AS TIPO_METRICA,
           UNI.TEMPO_PREV_HORAS,
           UNI.TEMPO_REAL_HORAS,
           TO_NUMBER(NULL) AS DESVIO_TEMPO_MIN,
           TO_NUMBER(NULL) AS EFIC_TEMPO_PCT,
           CASE WHEN UNI.TEM_FATO = 1 AND UNI.ORDEM IN ('04G', '12A') THEN
                ROUND((REF.KG_TING_TOT - REF.ACAB_KG_TOT), 2)
           END AS SALDO_WIP_TING_MENOS_EMB_KG,
            CASE WHEN UNI.UNIDADE_METRICA = '%' THEN
                      ROUND(UNI.QT_KG - LAG(UNI.QT_KG) OVER (PARTITION BY UNI.ORDEM ORDER BY UNI.DT_MES), 2)
                 ELSE
                      ROUND((UNI.QT_KG - LAG(UNI.QT_KG) OVER (PARTITION BY UNI.ORDEM ORDER BY UNI.DT_MES))
                            / NULLIF(LAG(UNI.QT_KG) OVER (PARTITION BY UNI.ORDEM ORDER BY UNI.DT_MES), 0) * 100, 1)
            END AS VAR_MOM,
            CASE WHEN UNI.UNIDADE_METRICA = '%' THEN
                      'PONTOS PERCENTUAIS (p.p.)'
                 ELSE
                      'PERCENTUAL (%)'
            END AS TIPO_VAR_MOM,
            ROUND(AVG(UNI.QT_KG) OVER (PARTITION BY UNI.ORDEM ORDER BY UNI.DT_MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS MEDIA_MOVEL_3M,
            UNI.UNIDADE_METRICA
       FROM UNIFICADO_COMPLETO UNI
      LEFT JOIN REFS_MENSAIS REF ON REF.DT_MES = UNI.DT_MES
      LEFT JOIN DIAS_FASE_LINHA DLF ON DLF.DT_MES = UNI.DT_MES AND DLF.STATUS_MES = UNI.STATUS_MES AND DLF.ORDEM = UNI.ORDEM
      LEFT JOIN DIAS_ACABADO_LINHA DLA ON DLA.DT_MES = UNI.DT_MES AND DLA.STATUS_MES = UNI.STATUS_MES AND DLA.ORDEM = UNI.ORDEM
)
SELECT COMPETENCIA,
       STATUS_MES,
       ORDEM,
       CATEGORIA,
       INDICADOR_FABRIL,
       QT_KG,
       DIAS_PRODUTIVOS,
       MEDIA_KG_DIA,
       QT_PARTIDAS,
       CARGA_MEDIA_KG,
       PERC_ESPECIFICO,
       TIPO_METRICA,
       TEMPO_PREV_HORAS,
       TEMPO_REAL_HORAS,
       DESVIO_TEMPO_MIN,
       EFIC_TEMPO_PCT,
       SALDO_WIP_TING_MENOS_EMB_KG,
       VAR_MOM,
       TIPO_VAR_MOM,
       MEDIA_MOVEL_3M,
       UNIDADE_METRICA
  FROM CALCULADO
 ORDER BY ORDEM ASC, COMPETENCIA DESC;
