/* =============================================================================
OBJETIVO: Matriz Pivotada Executiva de Produção por Fases e KPIs Fabris (Últimos 12 Meses + Mês Aberto)
          Modelo Pivotado Horizontal (Versão Oficial Consolidada com ACABADO_DIA_AGR).
DOMÍNIO: 09_pcp_kpis_gestao
DESTINO: Relatórios Gerenciais, Fechamento Mensal da Diretoria e Exportação Tabular.
TIPO: SELECT (Painel Analítico / Matriz Comparativa)
PARÂMETROS / BINDS:
  - Janela temporal automática: 12 meses retroativos fechados + Mês corrente em aberto (TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM') até SYSDATE).
CUIDADOS OPERACIONAIS & DIRETRIZES DE ENGENHARIA ORACLE:
  - Zero Views: Junção direta pelas tabelas físicas com índices operacionais (sem views legadas).
  - Pré-agregação por dimensões operacionais com consolidação de leitura única de BD_PRD_MOVPROD.
  - Produção de Acabado Oficial por Peça: Dados de produto acabado extraídos da movimentação oficial por peça
    (SGTPRD.BD_PRD_MOVPROD com NUM_TIPO_MOVIMENTO = 37 e CODIGO IN (1, 8)), trazendo volume em kg, quantidade de peças/rolos
    e peso médio por peça, conforme padrão canônico do PCP.
  - Reprocesso total: volume identificado pelo cadastro oficial DESTINO → GRUPO_DESTINO.TIPO_DESTINO = 1.
    Subdivisões por origem permanecem pendentes de regra oficial do PCP.
  - Métricas Avançadas Integradas:
      * Tempo real de processo derivado de datas; previsão e eficiência pendentes de unidade homologada
      * Carga Média e Aproveitamento Nominal das Barcas (1000kg, 600kg, 2000kg)
      * Ritmo Diário de Produção (kg/dia) da Tinturaria e do Acabamento
      * Balanço mensal de fluxos tingido versus acabado (sem comprovação de estoque físico)
  - Joins Condicionais por Fase: Junções de receita restritas à Fase 40.
  - Agregação Condicional Pura: Pivotamento via MAX(CASE WHEN ...) dinâmico por mês relativo sem PL/SQL.
============================================================================= */

WITH JANELA AS (
    SELECT ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AS DT_INICIO,
           TRUNC(SYSDATE) + 1                    AS DT_FIM,
           TRUNC(SYSDATE, 'MM')                  AS DT_MES_ABERTO
      FROM DUAL
),
MESES AS (
    SELECT ADD_MONTHS(JAN.DT_MES_ABERTO, LEVEL - 13) AS DT_MES,
           CASE WHEN LEVEL = 13 THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES
      FROM JANELA JAN
    CONNECT BY LEVEL <= 13
),
BASE_FASES_AGR AS (
    SELECT /*+ MATERIALIZE */
           TRUNC(UPR.DTPRODFIM, 'MM') AS DT_MES,
           CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           OBF.CODIGO_FASE,
           OBF.DESTINO_RECEITA AS DESTINO_RECEITA,
           GD.TIPO_DESTINO,
           TRIM(OBF.GRUPO_DEFEITO) AS GRUPO_DEFEITO,
           MAQ.GRUPO AS GRUPO_MAQUINA,
           UPR.NUMERO_MAQUINA,
           UPR.NRTURNOFIM AS TURNO,
           CL.CODIGO_CLASSIFICACAO,
           SUM(OBF.KILOS_PRODUZIDOS) AS KILOS_PRODUZIDOS,
           TO_NUMBER(NULL) AS QT_PARTIDAS,
           TO_NUMBER(NULL) AS DIAS_PRODUTIVOS,
           TO_NUMBER(NULL) AS TEMPO_PREV_HORAS,
           ROUND(SUM(CASE WHEN UPR.DTTEMPOFINALCONFIRMA > UPR.DTTEMPOINICONFIRMADO
                          THEN OBF.KILOS_PRODUZIDOS * (UPR.DTTEMPOFINALCONFIRMA - UPR.DTTEMPOINICONFIRMADO) * 24 END)
                 / NULLIF(SUM(CASE WHEN UPR.DTTEMPOFINALCONFIRMA > UPR.DTTEMPOINICONFIRMADO THEN OBF.KILOS_PRODUZIDOS END), 0), 2) AS TEMPO_REAL_HORAS
      FROM SGTPRD.UNIDADE_PROGRAMACAO   UPR
      JOIN SGTPRD.UP_ORDEM_MVTO          UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN SGTPRD.OB_FASES               OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL
                                            AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
      LEFT JOIN SGTPRD.MAQUINA           MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA AND MAQ.SETOR = 5
      LEFT JOIN SGTPRD.DESTINO           DST ON DST.DESTINO = OBF.DESTINO_RECEITA
      LEFT JOIN SGTPRD.GRUPO_DESTINO     GD ON GD.CODIGO_GRUPO = DST.CODIGO_GRUPO
      LEFT JOIN SGTPRD.LIGA_CADREC_ITEMREC LCR ON LCR.ID_LIGA_CADREC_ITEMR = OBF.ID_LIGA_CADREC_ITEMR AND OBF.CODIGO_FASE = 40
      LEFT JOIN SGTPRD.CADASTRO_RECEITAS CR  ON CR.CODIGO_REDUZIDO_RECE = LCR.CODIGO_REDUZIDO_RECE
      LEFT JOIN SGTPRD.CLASSIFICACAO_COR CL  ON CL.CODIGO_CLASSIFICACAO = CR.CODIGO_CLASSIFICACAO
     CROSS JOIN JANELA                   JAN
     WHERE UPR.SETOR = 5
       AND UPR.EXCLUIDA = 0
       AND UPR.TIPOUP = 0
       AND UPR.STATUS = 0
       AND UPR.DTPRODFIM >= JAN.DT_INICIO
       AND UPR.DTPRODFIM <  JAN.DT_FIM
       AND OBF.CODIGO_FASE IN (10, 20, 26, 40, 50, 55, 60, 65, 70, 80, 90, 100, 110)
     GROUP BY TRUNC(UPR.DTPRODFIM, 'MM'),
              CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END,
              OBF.CODIGO_FASE,
              OBF.DESTINO_RECEITA,
              GD.TIPO_DESTINO,
              TRIM(OBF.GRUPO_DEFEITO),
              MAQ.GRUPO,
              UPR.NUMERO_MAQUINA,
              UPR.NRTURNOFIM,
              CL.CODIGO_CLASSIFICACAO
),
DIAS_TING_MENSAL AS (
    SELECT TRUNC(UPR.DTPRODFIM, 'MM') AS DT_MES,
           CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           COUNT(DISTINCT TRUNC(UPR.DTPRODFIM)) AS DIAS_TING
      FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
      JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL
                              AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
      CROSS JOIN JANELA JAN
     WHERE UPR.SETOR = 5
       AND UPR.EXCLUIDA = 0
       AND UPR.TIPOUP = 0
       AND UPR.STATUS = 0
       AND UPR.DTPRODFIM >= JAN.DT_INICIO
       AND UPR.DTPRODFIM < JAN.DT_FIM
       AND OBF.CODIGO_FASE = 40
     GROUP BY TRUNC(UPR.DTPRODFIM, 'MM'),
              CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END
),
PARTIDAS_TING_MENSAL AS (
    SELECT TRUNC(UPR.DTPRODFIM, 'MM') AS DT_MES,
           CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           COUNT(DISTINCT OBF.NUMEROORDEMMOVIMENTO || '~' || OBF.SEQUENCIAORDEMMOVIME) AS PART_TING_TOT,
           COUNT(DISTINCT CASE WHEN OBF.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG001' THEN OBF.NUMEROORDEMMOVIMENTO || '~' || OBF.SEQUENCIAORDEMMOVIME END) AS PART_B1000,
           COUNT(DISTINCT CASE WHEN OBF.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG002' THEN OBF.NUMEROORDEMMOVIMENTO || '~' || OBF.SEQUENCIAORDEMMOVIME END) AS PART_B600,
           COUNT(DISTINCT CASE WHEN OBF.DESTINO_RECEITA = 1 AND MAQ.GRUPO = 'TG003' THEN OBF.NUMEROORDEMMOVIMENTO || '~' || OBF.SEQUENCIAORDEMMOVIME END) AS PART_B2000
      FROM SGTPRD.UNIDADE_PROGRAMACAO UPR
      JOIN SGTPRD.UP_ORDEM_MVTO UOM ON UOM.NUMEROUP = UPR.NUMEROUP
      JOIN SGTPRD.OB_FASES OBF ON OBF.NUMERO_OB = UOM.NUMEROORDEMREAL
                              AND OBF.SEQUENCIA = UOM.SEQUENCIAORDEMREAL
      LEFT JOIN SGTPRD.MAQUINA MAQ ON MAQ.NUMERO_MAQUINA = UPR.NUMERO_MAQUINA AND MAQ.SETOR = 5
      CROSS JOIN JANELA JAN
     WHERE UPR.SETOR = 5 AND UPR.EXCLUIDA = 0 AND UPR.TIPOUP = 0 AND UPR.STATUS = 0
       AND UPR.DTPRODFIM >= JAN.DT_INICIO AND UPR.DTPRODFIM < JAN.DT_FIM
       AND OBF.CODIGO_FASE = 40
       AND OBF.NUMEROORDEMMOVIMENTO IS NOT NULL AND OBF.SEQUENCIAORDEMMOVIME IS NOT NULL
     GROUP BY TRUNC(UPR.DTPRODFIM, 'MM'),
              CASE WHEN UPR.DTPRODFIM >= JAN.DT_MES_ABERTO THEN 'EM ABERTO' ELSE 'FECHADO' END
),
ACABADO_DIA_AGR AS (
    SELECT
           TRUNC(MVP.PRODUCAO_DATA, 'MM') AS DT_MES,
           CASE WHEN MVP.PRODUCAO_DATA >= TRUNC(SYSDATE, 'MM') THEN 'EM ABERTO' ELSE 'FECHADO' END AS STATUS_MES,
           TRUNC(MVP.PRODUCAO_DATA) AS DIA,
           MVP.PRODUCAO_TURNO AS TURNO,
           TRIM(E9.CDNIVELGENERICO) AS FLUXO,
           CASE WHEN MVP.ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END AS IS_ESTAMPADO,
           SUM(MVP.QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           COUNT(MVP.IDPECASPRODUTO) AS QT_PECAS
      FROM SGTPRD.BD_PRD_MOVPROD MVP
      LEFT JOIN SGTPRD.ENGEITEMESTONIVELGE9 E9 ON E9.CDREDUZIDO = MVP.REDUZIDO_ITEM
      LEFT JOIN SGTPRD.ITENS_ESTOQUE        ITE ON ITE.CODIGO_REDUZIDO = MVP.REDUZIDO_ITEM
     WHERE MVP.NUM_TIPO_MOVIMENTO = 37
       AND MVP.CODIGO IN (1, 8)
       AND MVP.PRODUCAO_DATA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
       AND MVP.PRODUCAO_DATA <  TRUNC(SYSDATE) + 1
     GROUP BY TRUNC(MVP.PRODUCAO_DATA, 'MM'),
              CASE WHEN MVP.PRODUCAO_DATA >= TRUNC(SYSDATE, 'MM') THEN 'EM ABERTO' ELSE 'FECHADO' END,
              TRUNC(MVP.PRODUCAO_DATA),
              MVP.PRODUCAO_TURNO,
              TRIM(E9.CDNIVELGENERICO),
              CASE WHEN MVP.ESTAMPADO = 1 OR UPPER(ITE.DESCRICAO) LIKE '%ESTAMP%' THEN 1 ELSE 0 END
),
BASE_ACABADO_AGR AS (
    SELECT DT_MES,
           STATUS_MES,
           TURNO,
           FLUXO,
           IS_ESTAMPADO,
           SUM(QUANTIDADE_REAL) AS QUANTIDADE_REAL,
           SUM(QT_PECAS) AS QT_PECAS
      FROM ACABADO_DIA_AGR
     GROUP BY DT_MES, STATUS_MES, TURNO, FLUXO, IS_ESTAMPADO
),
DIAS_ACABADO_MENSAL AS (
    SELECT DT_MES,
           COUNT(DISTINCT DIA) AS DIAS_ACABADO
      FROM ACABADO_DIA_AGR
     GROUP BY DT_MES
),
FASES_MENSAIS AS (
    SELECT F.DT_MES,
           F.STATUS_MES,
           SUM(CASE WHEN F.CODIGO_FASE = 10 THEN F.KILOS_PRODUZIDOS END) AS KG_MONT,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_NORM,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TIPO_DESTINO = 1 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_REP_TOTAL,
           SUM(CASE WHEN F.CODIGO_FASE = 40 THEN F.KILOS_PRODUZIDOS END) AS KG_TING_TOT,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 AND F.GRUPO_MAQUINA = 'TG001' THEN F.KILOS_PRODUZIDOS END) AS KG_B1000,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 AND F.GRUPO_MAQUINA = 'TG002' THEN F.KILOS_PRODUZIDOS END) AS KG_B600,
           SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.DESTINO_RECEITA = 1 AND F.GRUPO_MAQUINA = 'TG003' THEN F.KILOS_PRODUZIDOS END) AS KG_B2000,
           ROUND(SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TEMPO_PREV_HORAS > 0 THEN F.KILOS_PRODUZIDOS * F.TEMPO_PREV_HORAS END)
                 / NULLIF(SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TEMPO_PREV_HORAS > 0 THEN F.KILOS_PRODUZIDOS END), 0), 2) AS TING_TEMPO_PREV,
           ROUND(SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TEMPO_REAL_HORAS > 0 THEN F.KILOS_PRODUZIDOS * F.TEMPO_REAL_HORAS END)
                 / NULLIF(SUM(CASE WHEN F.CODIGO_FASE = 40 AND F.TEMPO_REAL_HORAS > 0 THEN F.KILOS_PRODUZIDOS END), 0), 2) AS TING_TEMPO_REAL,
           SUM(CASE WHEN F.CODIGO_FASE = 60 THEN F.KILOS_PRODUZIDOS END) AS KG_SECADOR_TOT,
           SUM(CASE WHEN F.CODIGO_FASE IN (100, 110) THEN F.KILOS_PRODUZIDOS END) AS KG_RAMA_TOT
      FROM BASE_FASES_AGR F
     GROUP BY F.DT_MES, F.STATUS_MES
),
ACABADO_MENSAL AS (
    SELECT B.DT_MES,
           B.ACAB_KG_TOT,
           B.ACAB_PECAS_TOT,
           D.DIAS_ACABADO,
           B.ACAB_KG_TUBULAR,
           B.ACAB_KG_RAMADO
      FROM (
            SELECT DT_MES,
                   SUM(QUANTIDADE_REAL) AS ACAB_KG_TOT,
                   SUM(QT_PECAS) AS ACAB_PECAS_TOT,
                   SUM(CASE WHEN FLUXO = 'T' THEN QUANTIDADE_REAL END) AS ACAB_KG_TUBULAR,
                   SUM(CASE WHEN FLUXO = 'R' THEN QUANTIDADE_REAL END) AS ACAB_KG_RAMADO
              FROM BASE_ACABADO_AGR
             GROUP BY DT_MES
      ) B
      LEFT JOIN DIAS_ACABADO_MENSAL D ON D.DT_MES = B.DT_MES
),
REFS_MENSAIS AS (
    SELECT M.DT_MES,
           M.STATUS_MES,
           F.KG_MONT,
           F.KG_TING_NORM,
           F.KG_TING_REP_TOTAL,
           F.KG_TING_TOT,
           PM.PART_TING_TOT,
           DT.DIAS_TING,
           F.KG_B1000,
           PM.PART_B1000,
           F.KG_B600,
           PM.PART_B600,
           F.KG_B2000,
           PM.PART_B2000,
           F.TING_TEMPO_PREV,
           F.TING_TEMPO_REAL,
           F.KG_SECADOR_TOT,
           F.KG_RAMA_TOT,
           A.ACAB_KG_TOT,
           A.ACAB_PECAS_TOT,
           A.DIAS_ACABADO,
           A.ACAB_KG_TUBULAR,
           A.ACAB_KG_RAMADO
      FROM MESES M
      LEFT JOIN FASES_MENSAIS F ON F.DT_MES = M.DT_MES AND F.STATUS_MES = M.STATUS_MES
      LEFT JOIN ACABADO_MENSAL A ON A.DT_MES = M.DT_MES
      LEFT JOIN DIAS_TING_MENSAL DT ON DT.DT_MES = M.DT_MES AND DT.STATUS_MES = M.STATUS_MES
      LEFT JOIN PARTIDAS_TING_MENSAL PM ON PM.DT_MES = M.DT_MES AND PM.STATUS_MES = M.STATUS_MES
),
EXPANDIDO AS (
    -- Fases Produtivas (Preparação / Beneficiamento)
    SELECT DT_MES, '01'  AS ORDEM, 'FASE PRODUTIVA' AS CATEGORIA, '01 - MONTAGEM DE LOTE (CRU)' AS LINHA, 'kg' AS UNIDADE, KILOS_PRODUZIDOS AS VALOR FROM BASE_FASES_AGR WHERE CODIGO_FASE = 10
    UNION ALL
    SELECT DT_MES, '02' , 'FASE PRODUTIVA', '02 - REVISÃO MALHA CRUA', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 20
    UNION ALL
    SELECT DT_MES, '03' , 'FASE PRODUTIVA', '03 - VIRAR MOLETOM (FELPA)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 26
    UNION ALL
    SELECT DT_MES, '04A', 'TINTURARIA - BARCAS', '04A - TINTURARIA: BARCA 1000 KG (TG001)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG001'
    UNION ALL
    SELECT DT_MES, '04B', 'TINTURARIA - BARCAS', '04B - TINTURARIA: BARCA 600 KG (TG002)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG002'
    UNION ALL
    SELECT DT_MES, '04C', 'TINTURARIA - BARCAS', '04C - TINTURARIA: BARCA 2000 KG (TG003)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND GRUPO_MAQUINA = 'TG003'
    UNION ALL
    SELECT DT_MES, '04D', 'TINTURARIA - RESUMO', '04 - TINTURARIA: PRODUÇÃO NORMAL', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1
    UNION ALL
    SELECT DT_MES, '04E', 'TINTURARIA - REPROCESSO', '04 - TINTURARIA: REPROCESSO TOTAL (DESTINO OFICIAL)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND TIPO_DESTINO = 1
    UNION ALL
    SELECT DT_MES, '04F', 'TINTURARIA - REPROCESSO', '04 - TINTURARIA: SUBCLASSIFICAÇÃO PENDENTE DO PCP', 'kg', TO_NUMBER(NULL) FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA IN (2, 4)
    UNION ALL
    SELECT DT_MES, '04G', 'TINTURARIA - RESUMO', '04 - TINTURARIA: TOTAL GERAL TINTURARIA', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40
    UNION ALL
    SELECT DT_MES, '04H', 'TINTURARIA - MIX CORES', '[MIX CORES] 1. CLARAS / BRANCO / MARFIM', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (1, 6, 7, 10, 18)
    UNION ALL
    SELECT DT_MES, '04I', 'TINTURARIA - MIX CORES', '[MIX CORES] 2. CORES MÉDIAS', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (2)
    UNION ALL
    SELECT DT_MES, '04J', 'TINTURARIA - MIX CORES', '[MIX CORES] 3. CORES ESCURAS E PRETO', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (5, 14)
    UNION ALL
    SELECT DT_MES, '04K', 'TINTURARIA - MIX CORES', '[MIX CORES] 4. ESPECIAIS E 2 FIBRAS', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND CODIGO_CLASSIFICACAO IN (3, 8, 9, 11, 12, 15)
    UNION ALL
    SELECT DT_MES, '04L', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 1º TURNO', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 1
    UNION ALL
    SELECT DT_MES, '04M', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 2º TURNO', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 2
    UNION ALL
    SELECT DT_MES, '04N', 'TINTURARIA - TURNOS', '[TURNO TINTURARIA] 3º TURNO', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 40 AND DESTINO_RECEITA = 1 AND TURNO = 3
    UNION ALL
    SELECT DT_MES, '05A', 'HIDROS EXTRATORES', '05A - HIDROEXTRATORA 01', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD01'
    UNION ALL
    SELECT DT_MES, '05B', 'HIDROS EXTRATORES', '05B - HIDROEXTRATORA 02', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD02'
    UNION ALL
    SELECT DT_MES, '05C', 'HIDROS EXTRATORES', '05C - HIDROEXTRATORA 03', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55) AND NUMERO_MAQUINA = '000000HD03'
    UNION ALL
    SELECT DT_MES, '05D', 'HIDROS EXTRATORES', '05 - TOTAL HIDROS EXTRATORES', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (50, 55)
    UNION ALL
    SELECT DT_MES, '06A', 'SECADORES', '06A - SECADOR 01 (ÓLEO TÉRMICO)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC01'
    UNION ALL
    SELECT DT_MES, '06B', 'SECADORES', '06B - SECADOR 02 (VAPOR)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60 AND NUMERO_MAQUINA = '000000SC02'
    UNION ALL
    SELECT DT_MES, '06C', 'SECADORES', '06 - TOTAL SECADORES', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 60
    UNION ALL
    SELECT DT_MES, '07' , 'ACABAMENTO INTERMEDIÁRIO', '07 - FELPADEIRA', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 65
    UNION ALL
    SELECT DT_MES, '08' , 'ACABAMENTO INTERMEDIÁRIO', '08 - CALANDRA DE BRILHO (CL 01)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 70
    UNION ALL
    SELECT DT_MES, '09' , 'ACABAMENTO INTERMEDIÁRIO', '09 - CALANDRA COMPACTA (CL 02)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 80
    UNION ALL
    SELECT DT_MES, '10' , 'ACABAMENTO INTERMEDIÁRIO', '10 - ABRIDOR DE MALHA (AB 01)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE = 90
    UNION ALL
    SELECT DT_MES, '11A', 'RAMAS', '11A - RAMA 01 (RM 01)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM01'
    UNION ALL
    SELECT DT_MES, '11B', 'RAMAS', '11B - RAMA 02 (RM 02)', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110) AND NUMERO_MAQUINA = '000000RM02'
    UNION ALL
    SELECT DT_MES, '11C', 'RAMAS', '11 - TOTAL RAMAS', 'kg', KILOS_PRODUZIDOS FROM BASE_FASES_AGR WHERE CODIGO_FASE IN (100, 110)
    UNION ALL
    -- Produção Oficial de Acabado por Peça (BD_PRD_MOVPROD)
    SELECT DT_MES, '12A', 'PRODUTO ACABADO', '12 - TOTAL PRODUTO ACABADO (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR
    UNION ALL
    SELECT DT_MES, '12B', 'PRODUTO ACABADO', '12 - TOTAL PRODUTO ACABADO (PEÇAS / ROLOS)', 'peças', QT_PECAS FROM BASE_ACABADO_AGR
    UNION ALL
    SELECT DT_MES, '12D', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 1º TURNO (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE TURNO = 1
    UNION ALL
    SELECT DT_MES, '12E', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 2º TURNO (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE TURNO = 2
    UNION ALL
    SELECT DT_MES, '12F', 'PRODUTO ACABADO - TURNOS', '[TURNO ACABAMENTO] 3º TURNO (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE TURNO = 3
    UNION ALL
    SELECT DT_MES, '90' , 'FLUXO DE MALHA', '[FLUXO MALHA] TOTAL TUBULAR (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE FLUXO = 'T'
    UNION ALL
    SELECT DT_MES, '91' , 'FLUXO DE MALHA', '[FLUXO MALHA] TOTAL RAMADO (ABERTO) (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE FLUXO = 'R'
    UNION ALL
    SELECT DT_MES, '92' , 'FLUXO DE MALHA', '[FLUXO MALHA] ESTAMPADO ACABADO (KG)', 'kg', QUANTIDADE_REAL FROM BASE_ACABADO_AGR WHERE IS_ESTAMPADO = 1
),
AGREGADO AS (
    SELECT DT_MES,
           ORDEM,
           CATEGORIA,
           LINHA,
           UNIDADE,
           ROUND(SUM(VALOR), 2) AS VALOR
      FROM EXPANDIDO
     GROUP BY DT_MES, ORDEM, CATEGORIA, LINHA, UNIDADE
),
KPIS_EXECUTIVOS AS (
    SELECT REF.DT_MES,
           '00A' AS ORDEM,
           'INDICADOR DE GESTÃO' AS CATEGORIA,
           '[INDICADOR GESTÃO] PRODUÇÃO NORMAL / PRODUÇÃO TINGIDA (%)' AS LINHA,
           '%' AS UNIDADE,
           ROUND(REF.KG_TING_NORM / NULLIF(REF.KG_TING_TOT, 0) * 100, 2) AS VALOR
      FROM REFS_MENSAIS REF
     UNION ALL
    SELECT REF.DT_MES,
           '00B',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] REPROCESSO TOTAL / NORMAL (%)',
           '%',
           ROUND(REF.KG_TING_REP_TOTAL / NULLIF(REF.KG_TING_NORM, 0) * 100, 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00C',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] SUBCLASSIFICAÇÃO DO REPROCESSO PENDENTE PCP',
           '%',
           TO_NUMBER(NULL)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00D',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] ACABADO MENSAL / TINGIDO MENSAL (%)',
           '%',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.KG_TING_TOT, 0) * 100, 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00E',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] ACABADO MENSAL / MONTADO MENSAL (%)',
           '%',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.KG_MONT, 0) * 100, 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00F',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] PESO MÉDIO POR PARTIDA (KG)',
           'kg/partida',
           ROUND(REF.KG_TING_TOT / NULLIF(REF.PART_TING_TOT, 0), 0)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00G',
           'INDICADOR DE GESTÃO',
           '[INDICADOR GESTÃO] BALANÇO MENSAL TINGIDO - ACABADO (KG)',
           'kg',
           ROUND(REF.KG_TING_TOT - REF.ACAB_KG_TOT, 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00H',
           'RITMO DE PRODUÇÃO',
           '[RITMO DIÁRIO] TINTURARIA TOTAL (KG/DIA)',
           'kg/dia',
           ROUND(REF.KG_TING_TOT / NULLIF(REF.DIAS_TING, 0), 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '00I',
           'RITMO DE PRODUÇÃO',
           '[RITMO DIÁRIO] PRODUTO ACABADO (KG/DIA)',
           'kg/dia',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.DIAS_ACABADO, 0), 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04A_CARGA',
           'TINTURARIA - CARGA',
           '[CARGA BARCA] 04A - BARCA 1000 KG (KG/PARTIDA)',
           'kg/partida',
           ROUND(REF.KG_B1000 / NULLIF(REF.PART_B1000, 0), 0)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04A_APROV',
           'TINTURARIA - CARGA',
           '[APROVEITAMENTO BARCA] 04A - BARCA 1000 KG (% NOMINAL)',
           '%',
           ROUND((REF.KG_B1000 / NULLIF(REF.PART_B1000, 0)) / 1000 * 100, 1)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04B_CARGA',
           'TINTURARIA - CARGA',
           '[CARGA BARCA] 04B - BARCA 600 KG (KG/PARTIDA)',
           'kg/partida',
           ROUND(REF.KG_B600 / NULLIF(REF.PART_B600, 0), 0)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04B_APROV',
           'TINTURARIA - CARGA',
           '[APROVEITAMENTO BARCA] 04B - BARCA 600 KG (% NOMINAL)',
           '%',
           ROUND((REF.KG_B600 / NULLIF(REF.PART_B600, 0)) / 600 * 100, 1)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04C_CARGA',
           'TINTURARIA - CARGA',
           '[CARGA BARCA] 04C - BARCA 2000 KG (KG/PARTIDA)',
           'kg/partida',
           ROUND(REF.KG_B2000 / NULLIF(REF.PART_B2000, 0), 0)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04C_APROV',
           'TINTURARIA - CARGA',
           '[APROVEITAMENTO BARCA] 04C - BARCA 2000 KG (% NOMINAL)',
           '%',
           ROUND((REF.KG_B2000 / NULLIF(REF.PART_B2000, 0)) / 2000 * 100, 1)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04_T_PREV',
           'TINTURARIA - TEMPOS',
           '[TEMPO TINTURARIA] TEMPO MÉDIO PREVISTO (UNIDADE A CONFIRMAR)',
           'a confirmar',
           REF.TING_TEMPO_PREV
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04_T_REAL',
           'TINTURARIA - TEMPOS',
           '[TEMPO TINTURARIA] TEMPO MÉDIO REAL (HORAS)',
           'horas',
           REF.TING_TEMPO_REAL
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '04_T_EFIC',
           'TINTURARIA - TEMPOS',
           '[TEMPO TINTURARIA] EFICIÊNCIA PENDENTE DE UNIDADE HOMOLOGADA',
           'a confirmar',
           TO_NUMBER(NULL)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '12C',
           'PRODUTO ACABADO',
           '12 - PESO MÉDIO POR PEÇA ACABADA (KG/PEÇA)',
           'kg/peça',
           ROUND(REF.ACAB_KG_TOT / NULLIF(REF.ACAB_PECAS_TOT, 0), 2)
       FROM REFS_MENSAIS REF
      UNION ALL
    SELECT REF.DT_MES,
           '93',
           'FLUXO DE MALHA',
           '[FLUXO MALHA] PROPORÇÃO TUBULAR / RAMADO (%)',
           '%',
           ROUND(REF.ACAB_KG_TUBULAR / NULLIF(REF.ACAB_KG_RAMADO, 0) * 100, 2)
       FROM REFS_MENSAIS REF
),
UNIFICADO AS (
    SELECT DT_MES, ORDEM, CATEGORIA, LINHA, UNIDADE, VALOR FROM KPIS_EXECUTIVOS
    UNION ALL
    SELECT DT_MES, ORDEM, CATEGORIA, LINHA, UNIDADE, VALOR FROM AGREGADO
),
PIVOTADO AS (
    SELECT ORDEM,
           CATEGORIA,
           LINHA AS INDICADOR_FABRIL,
           UNIDADE AS UNIDADE_METRICA,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) THEN VALOR END), 2) AS M12_FECHADO,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11) THEN VALOR END), 2) AS M11,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -10) THEN VALOR END), 2) AS M10,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -9)  THEN VALOR END), 2) AS M09,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -8)  THEN VALOR END), 2) AS M08,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -7)  THEN VALOR END), 2) AS M07,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)  THEN VALOR END), 2) AS M06,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)  THEN VALOR END), 2) AS M05,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4)  THEN VALOR END), 2) AS M04,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3)  THEN VALOR END), 2) AS M03,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2)  THEN VALOR END), 2) AS M02,
           ROUND(MAX(CASE WHEN DT_MES = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)  THEN VALOR END), 2) AS M01_FECHADO,
           ROUND(MAX(CASE WHEN DT_MES = TRUNC(SYSDATE, 'MM')                 THEN VALOR END), 2) AS M_ATUAL_ABERTO,
           ROUND(AVG(CASE WHEN DT_MES < TRUNC(SYSDATE, 'MM') THEN VALOR END), 2)                  AS MEDIA_12M_FECHADO,
           CASE WHEN UNIDADE IN ('kg', 'peças') AND ORDEM NOT IN ('00G') THEN
                ROUND(SUM(CASE WHEN DT_MES < TRUNC(SYSDATE, 'MM') THEN VALOR END), 2)
           END AS TOTAL_12M_FECHADO
      FROM UNIFICADO
     GROUP BY ORDEM, CATEGORIA, LINHA, UNIDADE
)
SELECT P.ORDEM,
       P.CATEGORIA,
       P.INDICADOR_FABRIL,
       P.UNIDADE_METRICA,
       P.M12_FECHADO,
       P.M11,
       P.M10,
       P.M09,
       P.M08,
       P.M07,
       P.M06,
       P.M05,
       P.M04,
       P.M03,
       P.M02,
       P.M01_FECHADO,
       P.M_ATUAL_ABERTO,
       P.MEDIA_12M_FECHADO,
       P.TOTAL_12M_FECHADO,
       CASE
            WHEN P.M01_FECHADO IS NULL OR P.MEDIA_12M_FECHADO IS NULL OR P.MEDIA_12M_FECHADO = 0 THEN '-'
            WHEN P.M01_FECHADO >= P.MEDIA_12M_FECHADO * 1.02 THEN 'ALTA'
            WHEN P.M01_FECHADO <= P.MEDIA_12M_FECHADO * 0.98 THEN 'QUEDA'
            ELSE 'ESTAVEL'
       END AS TENDENCIA_VS_MED12M
  FROM PIVOTADO P
 ORDER BY P.ORDEM ASC;
